import {
  createGenericOperationalTemporalRefV1, createOperationalObservationRefV1,
  createOperationalPlanElementRefV1, createOperationalPlanRelationshipRefV1,
  createOperationalSubjectRefV1, createOperationsEvidenceProfileV1,
  type GenericOperationalTemporalRefV1, type OperationalObservationRefV1,
  type OperationalPlanElementRefV1, type OperationalPlanRelationshipRefV1,
  type OperationalSubjectRefV1,
} from "../../cognition/canonical.operational.roles.v1";

export type GovernedOperationsFactFamilyV1 = "ORDERS"|"INVENTORY"|"MOVEMENTS"|"PRODUCTION_ORDERS"|"MATERIAL_MOVEMENTS"|"MASTER_BOM";
type Quantity = Readonly<{ value:number; source_unit:string; canonical_unit?:"EACH" }>;
export type MovementSourceAttributionV1=Readonly<{order_ref?:string;delivery_ref?:string;shipment_ref?:string;production_order_ref?:string;destination_ref?:string;source_location_ref?:string;destination_location_ref?:string;movement_line_ref?:string;reservation_ref?:string;allocation_ref?:string}>;
type Provenance = Readonly<{ acquisition_reference:string; authorization_reference:string; acquired_at:string; source_system:string; connector_identity_id:string; connector_revision:number; capability_id:string; source_representation:string }>;
type RoleBindings = Readonly<{ subject:OperationalSubjectRefV1; plan_element?:OperationalPlanElementRefV1; plan_relationship?:OperationalPlanRelationshipRefV1; observation?:OperationalObservationRefV1; temporal?:GenericOperationalTemporalRefV1; evidence_roles:readonly string[] }>;
type Common = Readonly<{ version:1; fact_family:GovernedOperationsFactFamilyV1; fact_id:string; fact_digest:string; domain_ref:"domain:operations"; profile_ref:"profile:operations-v1"; source_fact_ref:string; company_id:string; provenance:Provenance; role_bindings:RoleBindings; grants_execution:false; observational_only:true }>;
export type GovernedOperationsFactV1 = Common & Readonly<{ semantic:
  | Readonly<{family:"ORDERS";order_id:string;order_version:string;sku:string;quantity:Quantity;status:string;observed_at:string;effective_at:string;due_at:string}>
  | Readonly<{family:"INVENTORY";inventory_id:string;warehouse_id:string;sku:string;quantity:Quantity;observed_at:string}>
  | Readonly<{family:"MOVEMENTS";movement_id:string;sku:string;quantity:Quantity;movement_type:string;occurred_at:string;source_attribution:MovementSourceAttributionV1}>
  | Readonly<{family:"PRODUCTION_ORDERS";production_order_id:string;article:string;output_article:string;quantity:Quantity;scheduled_at:string;planned_output_available_at?:string}>
  | Readonly<{family:"MATERIAL_MOVEMENTS";movement_id:string;production_order_id:string;article:string;quantity:Quantity;movement_type:string;occurred_at:string;source_attribution:MovementSourceAttributionV1}>
  | Readonly<{family:"MASTER_BOM";parent:string;component:string;ratio:number;source_unit:string;canonical_unit?:"EACH";revision:string;valid_from:string}>
}>;
export type GovernedAcquisitionMetadataV1 = Readonly<{tenantId:string;companyId:string;sourceSystem:string;connectorIdentityId:string;connectorRevision:number;acquisitionReference:string;authorizationReference:string;acquiredAt:string;capabilityId:string;sourceRepresentation:string}>;

function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object"){const e=Object.entries(v as Record<string,unknown>).filter(([,x])=>x!==undefined).sort(([a],[b])=>a.localeCompare(b));return`{${e.map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(",")}}`;}return JSON.stringify(v);}
async function sha(v:unknown){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(v)));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("");}
function freeze<T>(v:T):Readonly<T>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v as Record<string,unknown>).forEach(freeze);Object.freeze(v);}return v;}
function q(value:number,source_unit:string):Quantity{return freeze({value,source_unit,...(source_unit==="EA"?{canonical_unit:"EACH" as const}:{})});}
function optionalProductionOutputAvailability(row:Readonly<Record<string,unknown>>):Readonly<Partial<{planned_output_available_at:string}>>{if(row.planned_output_available_at===undefined)return{};const value=row.planned_output_available_at;if(typeof value!=="string"||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value)||!Number.isFinite(Date.parse(value)))throw new Error("GOVERNED_PRODUCTION_OUTPUT_AVAILABILITY_INVALID");return{planned_output_available_at:value};}
const attributionFields=["order_ref","delivery_ref","shipment_ref","production_order_ref","destination_ref","source_location_ref","destination_location_ref","movement_line_ref","reservation_ref","allocation_ref"] as const;
function attribution(row:Readonly<Record<string,unknown>>,productionOrder?:string):MovementSourceAttributionV1{const value:Record<string,string>={};for(const field of attributionFields)if(row[field]!==undefined)value[field]=String(row[field]);if(productionOrder&&!value.production_order_ref)value.production_order_ref=productionOrder;return freeze(value);}

export async function preserveGovernedOperationsFactV1(family:GovernedOperationsFactFamilyV1,row:Readonly<Record<string,unknown>>,a:GovernedAcquisitionMetadataV1):Promise<GovernedOperationsFactV1>{
  const profile=await createOperationsEvidenceProfileV1();
  const identity=family==="ORDERS"?`${row.external_order_id}:${row.external_order_version}`:family==="INVENTORY"?String(row.inventory_id):family==="MASTER_BOM"?`${row.parent}:${row.component}:${row.revision}`:String(row.movement_id??row.production_order_id);
  const sourceIdentity={family,identity,company_id:a.companyId,source_system:a.sourceSystem,source_representation:a.sourceRepresentation};const sourceDigest=await sha(sourceIdentity);const source_fact_ref=`governed-source-fact:sha256:${sourceDigest}`;
  const subjectKind=family==="ORDERS"?"ORDER":"SKU";const subjectRef=family==="ORDERS"?`order:${row.external_order_id}`:`sku:${row.sku??row.article??row.parent}`;
  const subject=await createOperationalSubjectRefV1({version:1,tenant_id:`tenant:${a.tenantId}`,company_id:`company:${a.companyId}`,profile,subject_kind:subjectKind,subject_ref:subjectRef});
  const evidence_refs=[source_fact_ref],provenance_refs=[`source-provenance:sha256:${await sha(a)}`],causal_lineage_refs=[`acquisition-lineage:sha256:${await sha({acquisition:a.acquisitionReference,authorization:a.authorizationReference})}`],scope_ref=`company-scope:${a.companyId}`;
  const base={version:1 as const,subject,scope_ref,evidence_refs,provenance_refs,causal_lineage_refs};let semantic:GovernedOperationsFactV1["semantic"];const role_bindings:{subject:OperationalSubjectRefV1;plan_element?:OperationalPlanElementRefV1;plan_relationship?:OperationalPlanRelationshipRefV1;observation?:OperationalObservationRefV1;temporal?:GenericOperationalTemporalRefV1;evidence_roles:string[]}={subject,evidence_roles:[]};
  if(family==="ORDERS"){semantic={family,order_id:String(row.external_order_id),order_version:String(row.external_order_version),sku:String(row.sku),quantity:q(Number(row.quantity_value),String(row.quantity_unit)),status:String(row.status),observed_at:String(row.observed_at),effective_at:String(row.effective_at),due_at:String(row.due_at)};role_bindings.plan_element=await createOperationalPlanElementRefV1({...base,plan_element_ref:`operations-order:${row.external_order_id}`});role_bindings.temporal=await createGenericOperationalTemporalRefV1({...base,temporal_ref:`order-delivery-deadline:${row.external_order_id}`,temporal_role:"REQUIREMENT_DEADLINE",authoritative_time_ref:source_fact_ref});role_bindings.evidence_roles.push("PLAN_ELEMENT","TEMPORAL_REQUIREMENT");}
  else if(family==="INVENTORY"){semantic={family,inventory_id:String(row.inventory_id),warehouse_id:String(row.warehouse_id),sku:String(row.sku),quantity:q(Number(row.quantity),String(row.unit)),observed_at:String(row.observed_at)};role_bindings.observation=await createOperationalObservationRefV1({...base,observation_ref:`inventory-observation:${row.inventory_id}`,observed_at:String(row.observed_at),effective_at:String(row.observed_at),qualification_ref:source_fact_ref});role_bindings.evidence_roles.push("OBSERVATION");}
  else if(family==="MOVEMENTS"){semantic={family,movement_id:String(row.movement_id),sku:String(row.sku),quantity:q(Number(row.quantity),String(row.unit)),movement_type:String(row.type),occurred_at:String(row.occurred_at),source_attribution:attribution(row)};role_bindings.observation=await createOperationalObservationRefV1({...base,observation_ref:`movement-observation:${row.movement_id}`,observed_at:String(row.occurred_at),effective_at:String(row.occurred_at),qualification_ref:source_fact_ref});role_bindings.evidence_roles.push("OBSERVATION","BEHAVIORAL_EVENT");}
  else if(family==="PRODUCTION_ORDERS"){semantic={family,production_order_id:String(row.production_order_id),article:String(row.article),output_article:String(row.output_article),quantity:q(Number(row.quantity),String(row.unit)),scheduled_at:String(row.scheduled_at),...optionalProductionOutputAvailability(row)};role_bindings.plan_element=await createOperationalPlanElementRefV1({...base,plan_element_ref:`production-order:${row.production_order_id}`});role_bindings.evidence_roles.push("PLAN_ELEMENT");}
  else if(family==="MATERIAL_MOVEMENTS"){semantic={family,movement_id:String(row.movement_id),production_order_id:String(row.production_order_id),article:String(row.article),quantity:q(Number(row.quantity),String(row.unit)),movement_type:String(row.type),occurred_at:String(row.occurred_at),source_attribution:attribution(row,String(row.production_order_id))};role_bindings.observation=await createOperationalObservationRefV1({...base,observation_ref:`material-movement-observation:${row.movement_id}`,observed_at:String(row.occurred_at),effective_at:String(row.occurred_at),qualification_ref:source_fact_ref});role_bindings.evidence_roles.push("OBSERVATION","BEHAVIORAL_EVENT");}
  else {semantic={family,parent:String(row.parent),component:String(row.component),ratio:Number(row.ratio),source_unit:String(row.unit),...(row.unit==="EA"?{canonical_unit:"EACH" as const}:{}),revision:String(row.revision),valid_from:String(row.valid_from)};role_bindings.plan_relationship=await createOperationalPlanRelationshipRefV1({...base,relationship_ref:`bom-relation:${row.parent}:${row.component}:${row.revision}`,relationship_kind_ref:"operations-relationship:BOM_COMPONENT",source_plan_element_ref:`operations-item:${row.parent}`,target_plan_element_ref:`operations-item:${row.component}`});role_bindings.evidence_roles.push("PLAN_RELATIONSHIP","STRUCTURAL_RELATIONSHIP");}
  const provenance={acquisition_reference:a.acquisitionReference,authorization_reference:a.authorizationReference,acquired_at:a.acquiredAt,source_system:a.sourceSystem,connector_identity_id:a.connectorIdentityId,connector_revision:a.connectorRevision,capability_id:a.capabilityId,source_representation:a.sourceRepresentation};const factSemantic={version:1 as const,fact_family:family,domain_ref:"domain:operations" as const,profile_ref:"profile:operations-v1" as const,source_fact_ref,company_id:a.companyId,semantic,provenance,role_bindings};const fact_digest=await sha(factSemantic);return freeze({...factSemantic,fact_id:`governed-operations-fact:sha256:${sourceDigest}`,fact_digest,grants_execution:false,observational_only:true}) as GovernedOperationsFactV1;
}
