import { applyD1Migrations, env } from "cloudflare:test";
import { beforeAll, beforeEach, describe, expect, it } from "vitest";
import m7 from "../../../../../migrations/0007_oir_track_a_persistence.sql?raw";
import m9 from "../../../../../migrations/0009_oir_participation_runtime.sql?raw";
import m12 from "../../../../../migrations/0012_knowledge_exposure_persistence.sql?raw";
import m13 from "../../../../../migrations/0013_cognitive_transport_evidence.sql?raw";
import { deepCopyAndFreeze } from "../../knowledge.projection.guard.v1";
import { buildKnowledgeExposureEvidenceV1 } from "../../knowledge.exposure.evidence.v1";
import { evaluateKnowledgeExposurePolicyV1 } from "../../knowledge.exposure.policy.v1";
import { NOW, request } from "../../__tests__/fixtures";
import { D1KnowledgeExposureCurrentStateV1, D1KnowledgeExposureRepositoryV1, KnowledgeExposureLifecycleV1, type KnowledgeExposureConsumptionClaimV1 } from "../../persistence";
import { D1CognitiveTransportEvidenceRepositoryV1 } from "../cognitive.transport.d1.v1";
import type { CognitiveTransportEvidenceV1 } from "../cognitive.transport.contracts.v1";

const db=env.POLICIES_DB;
const migrations=[m7,m9,m12,m13].map((sql,index)=>({name:`m${index}`,queries:sql.split(/;\s*\r?\n(?=CREATE (?:TABLE|(?:UNIQUE )?INDEX|TRIGGER))/).map(q=>q.trim()).filter(Boolean).map(q=>q.endsWith(";")?q:`${q};`)}));
const store=new D1KnowledgeExposureRepositoryV1(db);
const lifecycle=new KnowledgeExposureLifecycleV1(store,new D1KnowledgeExposureCurrentStateV1(db,async()=>({authority_current:true,target_permitted:true,region_permitted:true,retention_permitted:true})),()=>"2026-08-02T10:00:30.000Z");
const transport=new D1CognitiveTransportEvidenceRepositoryV1(db);

async function issued(){const source=deepCopyAndFreeze(request()) as ReturnType<typeof request>,decision=evaluateKnowledgeExposurePolicyV1(source,NOW),evidence=buildKnowledgeExposureEvidenceV1(source,decision),persisted=await lifecycle.issue(source,decision,evidence);return{source,decision,...persisted};}
function claim(x:Awaited<ReturnType<typeof issued>>):KnowledgeExposureConsumptionClaimV1{return deepCopyAndFreeze({version:1,decision_id:x.decision.decision_id,binding_id:x.binding_id!,principal_id:x.decision.principal_id,session_id:x.decision.session_id,membership_id:x.decision.membership_id,tenant_id:x.decision.tenant_id,company_id:x.decision.company_id,operation:x.decision.operation,purpose:x.decision.purpose,target_class:x.decision.target_class,target_identity:x.decision.target_identity,target_region:x.source.target_region,requested_retention:x.decision.effective_retention,manifest_id:`${x.source.projection.schema_id}@${x.source.projection.schema_version}`,projection_digest:x.decision.projection_digest,knowledge_digests:x.decision.knowledge_digests,consuming_runtime:"oks-wu3.d1.test",intended_transport_class:"LLM",correlation_id:x.decision.correlation_id,causal_references:[]}) as KnowledgeExposureConsumptionClaimV1;}
async function fixture(){const x=await issued(),eligibility=await lifecycle.consume(claim(x));const evidence=deepCopyAndFreeze({version:1,evidence_id:"transport-evidence:1",decision_id:eligibility.decision_id,binding_id:eligibility.binding_id,consumption_id:eligibility.consumption_id,projection_digest:eligibility.projection_digest,request_digest:"b".repeat(64),provider:"openai",model:"model-1",provider_deployment_class:eligibility.target_class,purpose:eligibility.purpose,region:eligibility.target_region,retention:eligibility.requested_retention,dispatched_at:"2026-08-02T10:01:00.000Z",status:"SUCCEEDED",response_digest:"c".repeat(64),causal_references:eligibility.causal_references}) as CognitiveTransportEvidenceV1;return{eligibility,evidence};}

beforeAll(async()=>applyD1Migrations(db,migrations));
beforeEach(async()=>{for(const table of ["cognitive_transport_evidence","cognitive_transport_dispatch_reservations","knowledge_exposure_audit_events","knowledge_exposure_consumptions","knowledge_exposure_projection_bindings","knowledge_exposure_decisions","oir_company_selections","oir_organization_memberships","oir_tenant_company_ownership","oir_companies","oir_tenants","oir_server_sessions","oir_external_authentication_bindings","oir_principals"])await db.prepare(`DELETE FROM ${table}`).run();const p=request().participation;await db.prepare("INSERT INTO oir_principals VALUES (?,?,?,?)").bind(p.principal_id,"HUMAN","ACTIVE",NOW).run();await db.prepare("INSERT INTO oir_external_authentication_bindings VALUES (?,?,?,?,?,?,?,?,?,?)").bind("external:wu3",p.principal_id,"HUMAN","test","issuer","subject","mfa","MULTI_FACTOR",NOW,"verification").run();await db.prepare("INSERT INTO oir_server_sessions VALUES (?,?,?,?,?,?,?,?,?)").bind(p.session_id,p.principal_id,"external:wu3",NOW,"2026-08-02T11:00:00.000Z","MULTI_FACTOR","ACTIVE",null,null).run();await db.prepare("INSERT INTO oir_tenants VALUES (?,?,?)").bind(p.tenant_id,"ACTIVE",NOW).run();await db.prepare("INSERT INTO oir_companies VALUES (?,?,?)").bind(p.company_id,"ACTIVE",NOW).run();await db.prepare("INSERT INTO oir_tenant_company_ownership VALUES (?,?,?,?,?)").bind(p.company_id,p.tenant_id,NOW,null,"ownership:wu3").run();await db.prepare("INSERT INTO oir_organization_memberships VALUES (?,?,?,?,?,?,?,?,?,?)").bind(p.membership_id,p.principal_id,p.company_id,"REQUESTED",NOW,"request",null,null,null,null).run();await db.prepare("UPDATE oir_organization_memberships SET lifecycle_state='ACTIVE',activation_reference='activation',activated_at=? WHERE membership_id=?").bind(NOW,p.membership_id).run();await db.prepare("INSERT INTO oir_company_selections VALUES (?,?,?,?,?,?,?,?,?)").bind("selection:wu3",p.session_id,p.principal_id,p.membership_id,p.company_id,NOW,"selection",null,null).run();});

describe("OKS-WU3 cognitive transport evidence (actual D1)",()=>{
 it("applies the migration with foreign keys and exact durable tables",async()=>{const rows=await db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'cognitive_transport_%' ORDER BY name").all<{name:string}>();expect(rows.results.map(r=>r.name)).toEqual(["cognitive_transport_dispatch_reservations","cognitive_transport_evidence"]);expect((await db.prepare("PRAGMA foreign_keys").first<{foreign_keys:number}>())?.foreign_keys).toBe(1);});
 it("persists exact digests without prompts, provider responses, or credentials",async()=>{const{eligibility,evidence}=await fixture();expect(await transport.reserve(eligibility.consumption_id,"openai",evidence.dispatched_at)).toBe(true);await transport.append(evidence);const row=await db.prepare("SELECT * FROM cognitive_transport_evidence WHERE evidence_id=?").bind(evidence.evidence_id).first<Record<string,unknown>>();expect(row).toMatchObject({projection_digest:eligibility.projection_digest,request_digest:"b".repeat(64),response_digest:"c".repeat(64)});expect(Object.keys(row??{}).join(" ")).not.toMatch(/prompt|provider_response|credential|api_key/i);expect(JSON.stringify(row)).not.toMatch(/secret|advisory response/i);});
 it("enforces reservation uniqueness and replay protection",async()=>{const{eligibility,evidence}=await fixture();expect(await transport.reserve(eligibility.consumption_id,"openai",evidence.dispatched_at)).toBe(true);expect(await transport.reserve(eligibility.consumption_id,"openai",evidence.dispatched_at)).toBe(false);await transport.append(evidence);await expect(transport.append({...evidence,evidence_id:"transport-evidence:replay"})).rejects.toMatchObject({code:"COGNITIVE_TRANSPORT_EVIDENCE_FAILED"});});
 it("makes reservation and evidence rows immutable",async()=>{const{eligibility,evidence}=await fixture();await transport.reserve(eligibility.consumption_id,"openai",evidence.dispatched_at);await transport.append(evidence);for(const sql of ["UPDATE cognitive_transport_dispatch_reservations SET provider='anthropic'","DELETE FROM cognitive_transport_dispatch_reservations","UPDATE cognitive_transport_evidence SET model='other'","DELETE FROM cognitive_transport_evidence"])await expect(db.prepare(sql).run()).rejects.toThrow(/IMMUTABLE/);});
});
