import { describe,expect,it,vi } from "vitest";
import { deepCopyAndFreeze } from "../../knowledge.projection.guard.v1";
import { manifest,knowledge } from "../../__tests__/fixtures";
import type { KnowledgeExposureEligibilityV1 } from "../../persistence";
import type { CognitiveProviderV1,CognitiveTransportEvidenceRepositoryV1,CognitiveTransportEvidenceV1 } from "../cognitive.transport.contracts.v1";
import { CognitiveTransportMediatorV1 } from "../cognitive.transport.mediator.v1";
import { sealCognitiveExposureV1,verifySealedCognitiveExposureV1 } from "../cognitive.exposure.seal.v1";
const refs=[knowledge()];const m=deepCopyAndFreeze(manifest(refs));
function model(provider:CognitiveProviderV1){return provider==="openrouter"?"openai/gpt-4o-mini":"model-1";}function eligibility(provider:CognitiveProviderV1,overrides:Partial<KnowledgeExposureEligibilityV1>={}):KnowledgeExposureEligibilityV1{return deepCopyAndFreeze({version:1,decision_id:`decision:${provider}`,binding_id:`binding:${provider}`,consumption_id:`consumption:${provider}:${Math.random()}`,principal_id:"principal",session_id:"session",membership_id:"membership",tenant_id:"tenant:oks",company_id:"company:oks",operation:"COGNITIVE_EXPOSURE",purpose:"LANGUAGE_REFINEMENT",target_class:"SHARED_REMOTE_PROVIDER",target_identity:`${provider}:${model(provider)}`,target_region:"EU",requested_retention:"NO_RETENTION",manifest_id:`${m.schema_id}@${m.schema_version}`,projection_digest:m.projection_digest,knowledge_digests:["a".repeat(64)],correlation_id:"correlation",causal_references:[],policy_version:"KNOWLEDGE_EXPOSURE_POLICY_V1",consumed_at:"2026-08-02T10:00:00.000Z",...overrides}) as KnowledgeExposureEligibilityV1;}
function sealed(provider:CognitiveProviderV1,overrides:Partial<KnowledgeExposureEligibilityV1>={}){const selected=model(provider);return sealCognitiveExposureV1({eligibility:eligibility(provider,overrides),manifest:m,projection:{price:42},provider,provider_identity:`${provider}:${selected}`,model:selected});}
class Evidence implements CognitiveTransportEvidenceRepositoryV1{used=new Set<string>();events:CognitiveTransportEvidenceV1[]=[];async reserve(id:string){if(this.used.has(id))return false;this.used.add(id);return true;}async append(e:CognitiveTransportEvidenceV1){this.events.push(e);}}
const response=(provider:CognitiveProviderV1,text="advisory")=>new Response(JSON.stringify(provider==="openai"?{output_text:text,usage:{input_tokens:2,output_tokens:3}}:provider==="anthropic"?{content:[{type:"text",text}],usage:{input_tokens:2,output_tokens:3}}:{choices:[{message:{content:text}}],usage:{prompt_tokens:2,completion_tokens:3}}),{status:200});
async function dispatch(provider:CognitiveProviderV1,s=sealed(provider),res=response(provider)){const evidence=new Evidence(),fetcher=vi.fn(async(_url:unknown,_init?:RequestInit)=>res);const out=await new CognitiveTransportMediatorV1({fetch:fetcher as any,evidence,now:()=>"2026-08-02T10:01:00.000Z"}).dispatch({sealed:s,provider,model:s.model,api_key:"secret"});return{out,evidence,fetcher};}
describe("OKS-WU3 sealed cognitive transport",()=>{
 it("seals deterministically, deeply immutably, and defensively",()=>{const projection={price:42},a=sealCognitiveExposureV1({eligibility:eligibility("openai"),manifest:m,projection,provider:"openai",provider_identity:"openai:model-1",model:"model-1"});projection.price=99;const b=sealCognitiveExposureV1({eligibility:a.eligibility,manifest:m,projection:{price:42},provider:"openai",provider_identity:"openai:model-1",model:"model-1"});expect(a.canonical_projection_digest).toBe(b.canonical_projection_digest);expect(a.canonical_projection).toBe('{"price":42}');expect(Object.isFrozen(a)).toBe(true);expect(Object.isFrozen(a.eligibility)).toBe(true);});
 it("rejects arbitrary fields and disclosure eligibility",()=>{expect(()=>sealCognitiveExposureV1({eligibility:eligibility("openai"),manifest:m,projection:{price:42,secret:1},provider:"openai",provider_identity:"openai:model-1",model:"model-1"})).toThrow(/COGNITIVE_MANIFEST_MISMATCH/);expect(()=>sealed("openai",{operation:"OUTBOUND_DISCLOSURE"} as any)).toThrow(/COGNITIVE_ELIGIBILITY_OPERATION_MISMATCH/);});
 it.each(["openai","anthropic","openrouter"] as const)("dispatches one exact sealed projection through %s",async provider=>{const {out,fetcher,evidence}=await dispatch(provider);expect(out.advisory_only).toBe(true);expect(out.response_digest).toMatch(/^[0-9a-f]{64}$/);const body=JSON.parse(String(fetcher.mock.calls[0]![1]?.body));expect(JSON.stringify(body)).toContain('{\\"price\\":42}');expect(JSON.stringify(body)).not.toContain("secret");expect(evidence.events[0]).toMatchObject({provider,status:"SUCCEEDED",projection_digest:m.projection_digest});expect(JSON.stringify(evidence.events)).not.toContain("advisory");});
 it("requires a sealed exposure at the legacy boundary",async()=>{const evidence=new Evidence(),fetcher=vi.fn();await expect(new CognitiveTransportMediatorV1({fetch:fetcher as any,evidence,now:()=>"now"}).dispatch({sealed:undefined as any,provider:"openai",model:"m",api_key:"k"})).rejects.toMatchObject({code:"COGNITIVE_EXPOSURE_REQUIRED"});expect(fetcher).not.toHaveBeenCalled();});
 it("denies provider, model, purpose, region, retention, manifest, digest and reference substitution",()=>{const s=sealed("openai");expect(()=>verifySealedCognitiveExposureV1(s,"anthropic","model-1")).toThrow(/COGNITIVE_PROVIDER_NOT_ADMITTED/);expect(()=>verifySealedCognitiveExposureV1(s,"openai","other")).toThrow(/COGNITIVE_MODEL_NOT_ADMITTED/);for(const [field,value,code] of [["purpose","TRANSLATION","PURPOSE"],["region","US","REGION"],["retention","TRANSIENT_PROCESSING","RETENTION"],["manifest_id","other","MANIFEST"],["projection_digest","b".repeat(64),"PROJECTION_DIGEST"],["knowledge_digests",["b".repeat(64)],"REFERENCE_SET"]] as const)expect(()=>verifySealedCognitiveExposureV1(deepCopyAndFreeze({...s,[field]:value}) as any,"openai","model-1")).toThrow(new RegExp(`COGNITIVE_.*${code}`));});
 it("detects projection mutation even when a caller bypasses readonly typing",()=>{const s=sealed("openai") as any;const changed={...s,canonical_projection:'{"price":99}'};Object.freeze(changed);expect(()=>verifySealedCognitiveExposureV1(changed,"openai","model-1")).toThrow(/COGNITIVE_PROJECTION_MUTATED/);});
 it("permits only one network dispatch per consumed eligibility",async()=>{const evidence=new Evidence(),s=sealed("openai"),fetcher=vi.fn(async()=>response("openai")),mediator=new CognitiveTransportMediatorV1({fetch:fetcher as any,evidence,now:()=>"now"});await mediator.dispatch({sealed:s,provider:"openai",model:s.model,api_key:"k"});await expect(mediator.dispatch({sealed:s,provider:"openai",model:s.model,api_key:"k"})).rejects.toMatchObject({code:"COGNITIVE_FANOUT_NOT_ADMITTED"});expect(fetcher).toHaveBeenCalledTimes(1);});
 it("bounds malformed and oversized responses and sanitizes provider failures",async()=>{for(const res of [new Response("not-json"),new Response(JSON.stringify({error:{message:"credential secret endpoint"}}),{status:500}),new Response("x".repeat(262145))]){await expect(dispatch("openai",sealed("openai"),res)).rejects.toMatchObject({code:expect.stringMatching(/^COGNITIVE_/)});}});
});
