import { applyD1Migrations, env } from "cloudflare:test";
import { beforeAll, beforeEach, describe, expect, it } from "vitest";
import m7 from "../../../../../migrations/0007_oir_track_a_persistence.sql?raw";
import m9 from "../../../../../migrations/0009_oir_participation_runtime.sql?raw";
import m12 from "../../../../../migrations/0012_knowledge_exposure_persistence.sql?raw";
import { buildKnowledgeExposureEvidenceV1 } from "../../knowledge.exposure.evidence.v1";
import { evaluateKnowledgeExposurePolicyV1 } from "../../knowledge.exposure.policy.v1";
import { deepCopyAndFreeze } from "../../knowledge.projection.guard.v1";
import { NOW, request } from "../../__tests__/fixtures";
import { D1KnowledgeExposureCurrentStateV1, D1KnowledgeExposureRepositoryV1 } from "../knowledge.exposure.d1.v1";
import { KnowledgeExposureLifecycleV1 } from "../knowledge.exposure.lifecycle.v1";
import type { KnowledgeExposureConsumptionClaimV1 } from "../knowledge.exposure.repositories.v1";

const db=env.POLICIES_DB;
const queries=(sql:string)=>sql.split(/;\s*\r?\n(?=CREATE (?:TABLE|(?:UNIQUE )?INDEX|TRIGGER))/).map(x=>x.trim()).filter(Boolean).map(x=>x.endsWith(";")?x:`${x};`);
let clock="2026-08-02T10:00:30.000Z";
const store=new D1KnowledgeExposureRepositoryV1(db);
const runtime=()=>new KnowledgeExposureLifecycleV1(store,new D1KnowledgeExposureCurrentStateV1(db,async()=>({authority_current:true,target_permitted:true,region_permitted:true,retention_permitted:true})),()=>clock);

function admitted(){const r=deepCopyAndFreeze(request()) as ReturnType<typeof request>;const d=evaluateKnowledgeExposurePolicyV1(r,NOW);const e=buildKnowledgeExposureEvidenceV1(r,d);return {r,d,e};}
async function issued(){const x=admitted();const persisted=await runtime().issue(x.r,x.d,x.e);return {...x,...persisted};}
function claim(x:Awaited<ReturnType<typeof issued>>):KnowledgeExposureConsumptionClaimV1{const r=x.r,d=x.d;return deepCopyAndFreeze({version:1 as const,decision_id:d.decision_id,binding_id:x.binding_id!,principal_id:d.principal_id,session_id:d.session_id,membership_id:d.membership_id,tenant_id:d.tenant_id,company_id:d.company_id,operation:d.operation,purpose:d.purpose,target_class:d.target_class,target_identity:d.target_identity,target_region:r.target_region,requested_retention:d.effective_retention,manifest_id:`${r.projection.schema_id}@${r.projection.schema_version}`,projection_digest:d.projection_digest,knowledge_digests:d.knowledge_digests,consuming_runtime:"oks-wu2.test",intended_transport_class:"LLM",correlation_id:d.correlation_id,causal_references:[]}) as KnowledgeExposureConsumptionClaimV1;}

beforeAll(async()=>applyD1Migrations(db,[{name:"m7",queries:queries(m7)},{name:"m9",queries:queries(m9)},{name:"m12",queries:queries(m12)}]));
beforeEach(async()=>{
  clock="2026-08-02T10:00:30.000Z";
  for(const table of ["knowledge_exposure_audit_events","knowledge_exposure_consumptions","knowledge_exposure_projection_bindings","knowledge_exposure_decisions","oir_company_selections","oir_organization_memberships","oir_tenant_company_ownership","oir_companies","oir_tenants","oir_server_sessions","oir_external_authentication_bindings","oir_principals"]) await db.prepare(`DELETE FROM ${table}`).run();
  const r=request(),p=r.participation;
  await db.prepare("INSERT INTO oir_principals VALUES (?,?,?,?)").bind(p.principal_id,"HUMAN","ACTIVE",NOW).run();
  await db.prepare("INSERT INTO oir_external_authentication_bindings VALUES (?,?,?,?,?,?,?,?,?,?)").bind("external:oks",p.principal_id,"HUMAN","test","issuer","subject","mfa","MULTI_FACTOR",NOW,"verification").run();
  await db.prepare("INSERT INTO oir_server_sessions VALUES (?,?,?,?,?,?,?,?,?)").bind(p.session_id,p.principal_id,"external:oks",NOW,"2026-08-02T11:00:00.000Z","MULTI_FACTOR","ACTIVE",null,null).run();
  await db.prepare("INSERT INTO oir_tenants VALUES (?,?,?)").bind(p.tenant_id,"ACTIVE",NOW).run();
  await db.prepare("INSERT INTO oir_companies VALUES (?,?,?)").bind(p.company_id,"ACTIVE",NOW).run();
  await db.prepare("INSERT INTO oir_tenant_company_ownership VALUES (?,?,?,?,?)").bind(p.company_id,p.tenant_id,"2026-08-02T09:00:00.000Z",null,"ownership:oks").run();
  await db.prepare("INSERT INTO oir_organization_memberships VALUES (?,?,?,?,?,?,?,?,?,?)").bind(p.membership_id,p.principal_id,p.company_id,"REQUESTED",NOW,"request",null,null,null,null).run();
  await db.prepare("UPDATE oir_organization_memberships SET lifecycle_state='ACTIVE',activation_reference='activation',activated_at=? WHERE membership_id=?").bind(NOW,p.membership_id).run();
  await db.prepare("INSERT INTO oir_company_selections VALUES (?,?,?,?,?,?,?,?,?)").bind("selection:oks",p.session_id,p.principal_id,p.membership_id,p.company_id,NOW,"selection-reference",null,null).run();
});

describe("OKS-WU2 durable exposure lifecycle (actual D1)",()=>{
  it("persists an admitted decision and exact immutable projection binding idempotently",async()=>{const x=admitted();const a=await runtime().issue(x.r,x.d,x.e);const b=await runtime().issue(x.r,x.d,x.e);expect(a.disposition).toBe("CREATED");expect(b.disposition).toBe("IDENTICAL");const row=await db.prepare("SELECT * FROM knowledge_exposure_projection_bindings").first<any>();expect(row).toMatchObject({decision_id:x.d.decision_id,manifest_id:"quotation.customer-facing@1",projection_digest:x.d.projection_digest,knowledge_digests_json:JSON.stringify(x.d.knowledge_digests),operation:x.d.operation,purpose:x.d.purpose,target_class:x.d.target_class,tenant_id:x.d.tenant_id,company_id:x.d.company_id});});
  it("persists denied evidence without a consumable binding",async()=>{const r=deepCopyAndFreeze(request({target_region:"US"})) as ReturnType<typeof request>;const d=evaluateKnowledgeExposurePolicyV1(r,NOW),e=buildKnowledgeExposureEvidenceV1(r,d);const out=await runtime().issue(r,d,e);expect(d.outcome).toBe("DENIED");expect(out.binding_id).toBeUndefined();expect((await db.prepare("SELECT COUNT(*) n FROM knowledge_exposure_projection_bindings").first<any>()).n).toBe(0);});
  it("rejects evidence mismatch, mutable input, and decision identity reuse",async()=>{const x=admitted();await expect(runtime().issue(x.r,x.d,{...x.e,evidence_id:"changed"})).rejects.toMatchObject({code:"KNOWLEDGE_DECISION_PERSISTENCE_INVALID"});const altered=deepCopyAndFreeze({...x.e,evidence_id:"changed"}) as typeof x.e;await expect(runtime().issue(x.r,x.d,altered)).rejects.toMatchObject({code:"KNOWLEDGE_DECISION_EVIDENCE_MISMATCH"});});
  it("rejects mutation of decisions, bindings, consumptions, and audit",async()=>{const x=await issued();await runtime().consume(claim(x));for(const sql of ["UPDATE knowledge_exposure_decisions SET purpose='x'","UPDATE knowledge_exposure_projection_bindings SET purpose='x'","UPDATE knowledge_exposure_consumptions SET outcome='CONSUMED'","DELETE FROM knowledge_exposure_audit_events"])await expect(db.prepare(sql).run()).rejects.toThrow(/IMMUTABLE/);});
  it("revalidates active state and returns an exact deeply immutable content-free eligibility artifact",async()=>{const x=await issued();const artifact=await runtime().consume(claim(x));expect(artifact).toMatchObject({decision_id:x.d.decision_id,binding_id:x.binding_id,projection_digest:x.d.projection_digest,knowledge_digests:x.d.knowledge_digests,policy_version:x.d.policy_version});expect(Object.isFrozen(artifact)).toBe(true);expect(Object.isFrozen(artifact.knowledge_digests)).toBe(true);expect(JSON.stringify(artifact)).not.toMatch(/prompt|html|credential|customer_name|price|terms/i);});
  it.each([["principal","UPDATE oir_principals SET lifecycle_state='SUSPENDED'"],["session","UPDATE oir_server_sessions SET lifecycle_state='REVOKED',revocation_reference='r'"],["membership","UPDATE oir_organization_memberships SET lifecycle_state='SUSPENDED',lifecycle_decision_reference='s',lifecycle_changed_at='2026-08-02T10:00:31.000Z'"],["selection","UPDATE oir_company_selections SET invalidated_at='2026-08-02T10:00:31.000Z',invalidation_reason='stale'"]])("denies invalid current %s state",async(_label,sql)=>{const x=await issued();await db.prepare(sql).run();await expect(runtime().consume(claim(x))).rejects.toMatchObject({code:"KNOWLEDGE_DECISION_CURRENT_STATE_INVALID"});});
  it("denies expiry and every bound substitution class",async()=>{const x=await issued(),base=claim(x);clock="2026-08-02T10:02:00.000Z";await expect(runtime().consume(base)).rejects.toMatchObject({code:"KNOWLEDGE_DECISION_EXPIRED"});clock="2026-08-02T10:00:30.000Z";for(const [field,value,code] of [["binding_id","other","KNOWLEDGE_BINDING_SUBSTITUTED"],["manifest_id","other","KNOWLEDGE_MANIFEST_SUBSTITUTED"],["projection_digest","b".repeat(64),"KNOWLEDGE_PROJECTION_DIGEST_SUBSTITUTED"],["knowledge_digests",["b".repeat(64)],"KNOWLEDGE_REFERENCE_SET_SUBSTITUTED"],["operation","OUTBOUND_DISCLOSURE","KNOWLEDGE_OPERATION_SUBSTITUTED"],["purpose","TRANSLATION","KNOWLEDGE_PURPOSE_SUBSTITUTED"],["target_identity","other","KNOWLEDGE_TARGET_SUBSTITUTED"],["target_region","US","KNOWLEDGE_REGION_SUBSTITUTED"],["requested_retention","TENANT_CONTROLLED_RETENTION","KNOWLEDGE_RETENTION_SUBSTITUTED"],["principal_id","other","KNOWLEDGE_PARTICIPATION_INVALID"]] as const)await expect(runtime().consume(deepCopyAndFreeze({...base,[field]:value}) as any)).rejects.toMatchObject({code});});
  it("allows exactly one sequential and concurrent consumption",async()=>{const a=await issued(),c=claim(a);await runtime().consume(c);await expect(runtime().consume(c)).rejects.toMatchObject({code:"KNOWLEDGE_CONSUMPTION_REPLAYED"});const r2=deepCopyAndFreeze(request({requested_at:"2026-08-02T10:00:01.000Z"})) as ReturnType<typeof request>,d2=evaluateKnowledgeExposurePolicyV1(r2,r2.requested_at),e2=buildKnowledgeExposureEvidenceV1(r2,d2),p2=await runtime().issue(r2,d2,e2),c2=claim({r:r2,d:d2,e:e2,...p2});const results=await Promise.allSettled([runtime().consume(c2),runtime().consume(c2)]);expect(results.filter(x=>x.status==="fulfilled")).toHaveLength(1);expect((await db.prepare("SELECT COUNT(*) n FROM knowledge_exposure_consumptions WHERE decision_id=?").bind(d2.decision_id).first<any>()).n).toBe(1);});
  it("persists content-free issuance, verification, denial, replay, and consumption audit",async()=>{const x=await issued(),c=claim(x);await runtime().consume(c);await expect(runtime().consume(c)).rejects.toBeTruthy();const rows=await db.prepare("SELECT * FROM knowledge_exposure_audit_events WHERE decision_id=?").bind(x.d.decision_id).all<any>();expect(rows.results.map((r:any)=>r.event_kind)).toEqual(expect.arrayContaining(["DECISION_PERSISTED","DECISION_VERIFIED","CONSUMED","REPLAY_DENIED"]));expect(JSON.stringify(rows.results)).not.toMatch(/customer_name|price|terms|credential|prompt|html/i);});
});
