import { applyD1Migrations,env } from "cloudflare:test";
import { beforeAll,beforeEach,describe,expect,it,vi } from "vitest";
import m12 from "../../../../../migrations/0012_knowledge_exposure_persistence.sql?raw";
import m30 from "../../../../../migrations/0030_knowledge_exposure_authority_binding.sql?raw";
import { disclosure,request,NOW } from "../../__tests__/fixtures";
import { evaluateKnowledgeExposurePolicyV1 } from "../../knowledge.exposure.policy.v1";
import { buildKnowledgeExposureEvidenceV1 } from "../../knowledge.exposure.evidence.v1";
import { deepCopyAndFreeze } from "../../knowledge.projection.guard.v1";
import { KnowledgeExposureLifecycleV1 } from "../knowledge.exposure.lifecycle.v1";
import { D1KnowledgeExposureRepositoryV1 } from "../knowledge.exposure.d1.v1";
import { D1KnowledgeExposureAuthorityBindingRepositoryV1 } from "../knowledge.exposure.authority.d1.v1";
import { KnowledgeExposureAuthorityRuntimeV1 } from "../../knowledge.exposure.authority.runtime.v1";

const db=env.POLICIES_DB,queries=(sql:string)=>sql.split(/;\s*\r?\n(?=CREATE (?:TABLE|(?:UNIQUE )?INDEX|TRIGGER))/).map(x=>x.trim()).filter(Boolean).map(x=>x.endsWith(";")?x:`${x};`);
beforeAll(async()=>applyD1Migrations(db,[{name:"m12",queries:queries(m12)},{name:"m30",queries:queries(m30)}]));
beforeEach(async()=>{for(const t of ["knowledge_exposure_authority_audit","knowledge_exposure_authority_evidence","security_evidence_applicability","knowledge_exposure_authority_bindings","knowledge_exposure_audit_events","knowledge_exposure_projection_bindings","knowledge_exposure_decisions"])await db.prepare(`DELETE FROM ${t}`).run();});
async function persisted(){const r=deepCopyAndFreeze(request({operation:"COGNITIVE_EXPOSURE",purpose:{version:1,code:"EXPLANATION",operation:"COGNITIVE_EXPOSURE"},target_class:"SHARED_REMOTE_PROVIDER"})),d=evaluateKnowledgeExposurePolicyV1(r,NOW),e=buildKnowledgeExposureEvidenceV1(r,d),store=new D1KnowledgeExposureRepositoryV1(db);await new KnowledgeExposureLifecycleV1(store,{} as any,()=>"2026-08-02T10:00:30.000Z").issue(r,d,e);return {r,d};}
describe("SEC-WU2 authority applicability persistence (actual D1)",()=>{
  it("persists immutable content-free OAG and P9 not-applicable evidence idempotently",async()=>{const {r,d}=await persisted(),runtime=new KnowledgeExposureAuthorityRuntimeV1({resolveCurrentEffectiveOperationalAuthorityProofV1:vi.fn()} as any,new D1KnowledgeExposureAuthorityBindingRepositoryV1(db),()=>"2026-08-02T10:00:30.000Z"),input={version:1 as const,request:r,decision:d};const a=await runtime.bind(input),b=await runtime.bind(input);expect(a).toEqual(b);const rows=await db.prepare("SELECT domain,status,reason FROM security_evidence_applicability ORDER BY domain").all<any>();expect(rows.results).toEqual([{domain:"ORGANIZATIONAL_AUTHORITY",status:"NOT_APPLICABLE",reason:"COGNITIVE_TRANSFORMATION_ONLY"},{domain:"P9",status:"NOT_APPLICABLE",reason:"ORDINARY_COGNITIVE_PROVIDER_OPERATION"}]);expect((await db.prepare("SELECT COUNT(*) n FROM knowledge_exposure_authority_evidence").first<any>()).n).toBe(0);expect(JSON.stringify(rows.results)).not.toMatch(/prompt|knowledge|credential|signature|price/i);});
  it("makes binding, applicability, and audit immutable",async()=>{const {r,d}=await persisted(),runtime=new KnowledgeExposureAuthorityRuntimeV1({resolveCurrentEffectiveOperationalAuthorityProofV1:vi.fn()} as any,new D1KnowledgeExposureAuthorityBindingRepositoryV1(db),()=>"2026-08-02T10:00:30.000Z");await runtime.bind({version:1,request:r,decision:d});for(const sql of ["UPDATE knowledge_exposure_authority_bindings SET projection_digest='x'","UPDATE security_evidence_applicability SET status='UNDEFINED'","DELETE FROM knowledge_exposure_authority_audit"])await expect(db.prepare(sql).run()).rejects.toThrow(/IMMUTABLE/);});
  it("persists exact content-free canonical quotation authority identity and scope",async()=>{const proofId=`oag-authority-proof:sha256:${"a".repeat(64)}`,r=deepCopyAndFreeze(disclosure({authority_reference:proofId})),d=evaluateKnowledgeExposurePolicyV1(r,NOW),e=buildKnowledgeExposureEvidenceV1(r,d),store=new D1KnowledgeExposureRepositoryV1(db);await new KnowledgeExposureLifecycleV1(store,{} as any,()=>"2026-08-02T10:00:30.000Z").issue(r,d,e);const scope={domain:"CUSTOMER_COMMERCIAL_COMMUNICATION",intents:["DISCLOSE_CUSTOMER_QUOTATION"],scopes:["DISCLOSE_CUSTOMER_QUOTATION"],limits:[],team_or_subordinate_actor_ids:[],operational_constraints:[]},proof:any={version:1,authority_source_class:"ORGANIZATIONAL_OPERATIONAL_AUTHORITY",authority_basis:"DIRECT",authority_proof_id:proofId,proof_digest:"b".repeat(64),oag_actor_id:"actor:1",oag_actor_binding_id:"binding:1",principal_id:"principal:oks",membership_id:"membership:oks",tenant_id:"tenant:oks",company_id:"company:oks",root_reference:"root:1",responsibility_references:["responsibility:1"],declaration_version_ids:["declaration:1"],confirmation_chain_id:"confirmation:1",confirmation_chain_references:["confirmation:1"],graph_version:"graph:1",graph_digest:"c".repeat(64),delegation_references:[],effective_scope:scope,policy_id:"OAG_AUTHORITY_POLICY_V2",policy_version:"OAG_AUTHORITY_POLICY_V2",policy_numeric_version:2,issued_at:NOW,expires_at:"2026-08-02T11:00:00.000Z",eligibility_state:"ELIGIBLE",invalidation_reasons:[],correlation_id:"correlation:oks",causal_references:[]};const runtime=new KnowledgeExposureAuthorityRuntimeV1({resolveCurrentEffectiveOperationalAuthorityProofV1:vi.fn(async()=>proof)},new D1KnowledgeExposureAuthorityBindingRepositoryV1(db),()=>"2026-08-02T10:00:30.000Z");await runtime.bind({version:1,request:r,decision:d,oag_actor_id:"actor:1",authority_proof_id:proofId,authority_proof_digest:proof.proof_digest});const row=await db.prepare("SELECT * FROM knowledge_exposure_authority_evidence").first<any>();expect(row).toMatchObject({authority_proof_id:proofId,authority_proof_digest:proof.proof_digest,effective_operational_domain:"CUSTOMER_COMMERCIAL_COMMUNICATION",purpose:"CUSTOMER_QUOTATION_DISCLOSURE",current_state_resolution:"CURRENT"});expect(JSON.parse(row.effective_scope_json)).toEqual(scope);expect(JSON.stringify(row)).not.toMatch(/price|terms|prompt|credential/i);await expect(db.prepare("UPDATE knowledge_exposure_authority_evidence SET authority_proof_id='x'").run()).rejects.toThrow(/IMMUTABLE/);});
});
