import {createHash} from "node:crypto";import {applyD1Migrations,env} from "cloudflare:test";import {beforeAll,beforeEach,describe,expect,it} from "vitest";
import m7 from "../../../../../migrations/0007_oir_track_a_persistence.sql?raw";import m12 from "../../../../../migrations/0012_knowledge_exposure_persistence.sql?raw";import m14 from "../../../../../migrations/0014_outbound_disclosure_admission.sql?raw";import m17 from "../../../../../migrations/0017_platform_operational_alert.sql?raw";import m18 from "../../../../../migrations/0018_platform_alert_recipient_entitlement.sql?raw";
import {deepCopyAndFreeze} from "../../../knowledge-exposure/knowledge.projection.guard.v1";import {PLATFORM_COMPANY_ID,PLATFORM_TENANT_ID,type PlatformAlertChannelV1,type PlatformAuthorityProofV1,type PlatformRecipientEndpointV1,type PlatformRecipientEntitlementV1,type PlatformRecipientResolutionRequestV1} from "../platform.recipient.contracts.v1";import {D1PlatformRecipientRepositoryV1} from "../platform.recipient.d1.v1";import {PlatformRecipientResolverV1} from "../platform.recipient.resolver.v1";
const db=env.POLICIES_DB,NOW="2026-08-02T10:01:00.000Z",hash=(s:string)=>createHash("sha256").update(s).digest("hex"),queries=(s:string)=>s.split(/;\s*\r?\n(?=CREATE (?:TABLE|(?:UNIQUE )?INDEX|TRIGGER))/).map(q=>q.trim()).filter(Boolean).map(q=>q.endsWith(";")?q:`${q};`);
beforeAll(async()=>applyD1Migrations(db,[m7,m12,m14,m17,m18].map((sql,i)=>({name:`r${i}`,queries:queries(sql)}))));
beforeEach(async()=>{await db.prepare("INSERT INTO oir_principals VALUES (?,?,?,?)").bind("principal:operator","HUMAN","ACTIVE","2026-01-01T00:00:00.000Z").run();await db.prepare("INSERT INTO oir_tenants VALUES (?,?,?)").bind(PLATFORM_TENANT_ID,"ACTIVE","2026-01-01T00:00:00.000Z").run();await db.prepare("INSERT INTO oir_companies VALUES (?,?,?)").bind(PLATFORM_COMPANY_ID,"ACTIVE","2026-01-01T00:00:00.000Z").run();await db.prepare("INSERT INTO oir_tenant_company_ownership VALUES (?,?,?,?,?)").bind(PLATFORM_COMPANY_ID,PLATFORM_TENANT_ID,"2026-01-01T00:00:00.000Z",null,"ownership:platform").run();await db.prepare("INSERT INTO oir_organization_memberships VALUES (?,?,?,?,?,?,?,?,?,?)").bind("membership:operator","principal:operator",PLATFORM_COMPANY_ID,"INVITED","2026-01-01T00:00:00.000Z","invite:1",null,null,null,null).run();await db.prepare("UPDATE oir_organization_memberships SET lifecycle_state='ACTIVE',activation_reference='activation:1',activated_at='2026-01-02T00:00:00.000Z' WHERE membership_id='membership:operator'").run();await db.prepare(`INSERT INTO platform_alert_intents VALUES (${Array(22).fill("?").join(",")})`).bind("platform-alert:1","dedup:1","PLATFORM_OPERATIONAL_ALERT","platform-owner:planneragent-walcorp-operations","WU4C_TWILIO_DELIVERY","source:1","a".repeat(64),"FAILED","GOVERNED_DELIVERY_REVIEW","REVIEW_REQUIRED",1,"PLANNERAGENT_DELIVERY_OPERATIONS",null,null,JSON.stringify({version:1}),"PLATFORM_DELIVERY_OUTCOME_POLICY","PLATFORM_ALERT_POLICY_V1","2026-08-02T10:00:40.000Z","2026-08-03T10:00:40.000Z","correlation:1","[]","b".repeat(64)).run();await db.prepare("INSERT INTO platform_alert_admission_decisions VALUES (?,?,?,?,?,?,?)").bind("decision:alert","platform-alert:1","ADMITTED","PLATFORM_DELIVERY_OUTCOME_POLICY","PLATFORM_ALERT_POLICY_V1","PLATFORM_ALERT_ADMITTED",NOW).run();});
const proof=():PlatformAuthorityProofV1=>deepCopyAndFreeze({authority_proof_id:"proof:1",platform_tenant_id:PLATFORM_TENANT_ID,platform_company_id:PLATFORM_COMPANY_ID,actor_id:"actor:operator",principal_id:"principal:operator",membership_id:"membership:operator",authority_domain:"PLATFORM_OPERATIONS",effective_scope:["GOVERNED_DELIVERY_REVIEW"],confirmation_chain_reference:"chain:1",delegation_references:["delegation:1"],graph_version:"graph:1",eligibility_state:"ELIGIBLE",drift_state:"CURRENT",issued_at:"2026-08-01T00:00:00.000Z",expires_at:"2026-08-04T00:00:00.000Z",policy_version:"OAG_POLICY_V1",causal_references:["audit:authority"]}) as PlatformAuthorityProofV1;
const entitlement=(channel:PlatformAlertChannelV1="EMAIL"):PlatformRecipientEntitlementV1=>deepCopyAndFreeze({version:1,entitlement_id:"entitlement:1",platform_tenant_id:PLATFORM_TENANT_ID,platform_company_id:PLATFORM_COMPANY_ID,actor_id:"actor:operator",principal_id:"principal:operator",membership_id:"membership:operator",authority_domain:"PLATFORM_OPERATIONS",authority_proof_id:"proof:1",communication_family:"PLATFORM_OPERATIONAL_ALERT",purpose:"GOVERNED_DELIVERY_REVIEW",urgency_ceiling:"URGENT_REVIEW",allowed_channels:[channel],preferred_channel:channel,recipient_priority:"PRIMARY",supervisor_fallback_authorized:false,lifecycle_state:"ACTIVE",effective_at:"2026-08-01T00:00:00.000Z",expires_at:"2026-08-04T00:00:00.000Z",correlation_id:"correlation:1",causal_references:["audit:entitlement"]}) as PlatformRecipientEntitlementV1;
const endpoint=(channel:PlatformAlertChannelV1="EMAIL"):PlatformRecipientEndpointV1=>{const value=channel==="EMAIL"?"ops@example.com":channel==="SMS"?"+391234567890":"whatsapp:+391234567890";return deepCopyAndFreeze({endpoint_id:"endpoint:1",entitlement_id:"entitlement:1",actor_id:"actor:operator",channel,normalized_destination:value,destination_digest:hash(value),lifecycle_state:"ACTIVE",verification_state:"VERIFIED",effective_at:"2026-08-01T00:00:00.000Z",expires_at:"2026-08-04T00:00:00.000Z",verification_reference:"verify:1",causal_references:["audit:endpoint"]}) as PlatformRecipientEndpointV1};
const request=deepCopyAndFreeze({version:1,alert_id:"platform-alert:1",requested_at:NOW,correlation_id:"correlation:1",causal_references:["platform-alert:1"]}) as PlatformRecipientResolutionRequestV1;
describe("PA-WU2 recipient persistence (actual D1)",()=>{
it("applies normalized recipient schema",async()=>{const rows=await db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'platform_alert_%' AND name NOT LIKE '%audit_events' ORDER BY name").all<{name:string}>();expect(rows.results.map(r=>r.name)).toEqual(expect.arrayContaining(["platform_alert_recipient_entitlements","platform_alert_recipient_endpoints","platform_alert_recipient_resolution_decisions","platform_alert_recipient_bindings"]));});
it.each(["EMAIL","SMS","WHATSAPP"] as const)("persists and resolves a verified %s endpoint",async channel=>{const repo=new D1PlatformRecipientRepositoryV1(db);await repo.createAuthorityProof(proof());await repo.createEntitlement(entitlement(channel));await repo.bindEndpoint(endpoint(channel));const out=await new PlatformRecipientResolverV1(repo).resolve(request);expect(out).toMatchObject({accountable_actor_id:"actor:operator",channel,endpoint_destination_digest:hash(endpoint(channel).normalized_destination)});const audit=await db.prepare("SELECT * FROM platform_alert_recipient_audit_events WHERE event_kind='RECIPIENT_RESOLVED'").first<Record<string,unknown>>();expect(audit).toMatchObject({endpoint_id:"endpoint:1",destination_digest:hash(endpoint(channel).normalized_destination)});expect(JSON.stringify(audit)).not.toContain(endpoint(channel).normalized_destination);});
it("durably denies revoked entitlement and audits denial",async()=>{const repo=new D1PlatformRecipientRepositoryV1(db);await repo.createAuthorityProof(proof());await repo.createEntitlement(entitlement());await repo.bindEndpoint(endpoint());await repo.revokeEntitlement("entitlement:1",NOW,"revoke:1");await expect(new PlatformRecipientResolverV1(repo).resolve(request)).rejects.toMatchObject({code:"PLATFORM_RECIPIENT_ENTITLEMENT_REVOKED"});expect(await db.prepare("SELECT 1 ok FROM platform_alert_recipient_audit_events WHERE outcome='DENIED'").first()).toBeTruthy();});
it("makes authority, entitlement, endpoint, resolution, binding and audit immutable",async()=>{const repo=new D1PlatformRecipientRepositoryV1(db);await repo.createAuthorityProof(proof());await repo.createEntitlement(entitlement());await repo.bindEndpoint(endpoint());await new PlatformRecipientResolverV1(repo).resolve(request);for(const table of ["platform_operational_authority_proofs","platform_alert_recipient_entitlements","platform_alert_recipient_endpoints","platform_alert_recipient_resolution_decisions","platform_alert_recipient_bindings","platform_alert_recipient_audit_events"])for(const verb of ["UPDATE","DELETE"]){const sql=verb==="UPDATE"?`UPDATE ${table} SET rowid=rowid`:`DELETE FROM ${table}`;await expect(db.prepare(sql).run()).rejects.toThrow(/IMMUTABLE/);}});
});
