import type { CompanyLegalEntityBindingV1, LegalEntityIdentityV1 } from "../legal-entity";
import type { OagProof } from "../oag/types";

export type OrganizationalRepresentationScopeV1 = "ACCEPT_ENTERPRISE_NDA"|"ACCEPT_DATA_PROCESSING_AGREEMENT"|"ACCEPT_PROVIDER_PROCESSING_TERMS"|"DEFINE_TENANT_PROVIDER_TRUST_REQUIREMENTS"|"APPOINT_PROCESSING_AUTHORITY"|"REPRESENT_LEGAL_ENTITY_FOR_PLATFORM_ONBOARDING";
export type OrpaFailureCodeV1 = "ORPA_REQUEST_INVALID"|"ORPA_LEGAL_ENTITY_NOT_VERIFIED"|"ORPA_LEGAL_ENTITY_EXPIRED"|"ORPA_LEGAL_ENTITY_REVOKED"|"ORPA_COMPANY_BINDING_INVALID"|"ORPA_PRINCIPAL_INVALID"|"ORPA_SESSION_INVALID"|"ORPA_MEMBERSHIP_REQUIRED"|"ORPA_MEMBERSHIP_INVALID"|"ORPA_ACTOR_SUBSTITUTED"|"ORPA_AUTHORITY_PROOF_REQUIRED"|"ORPA_AUTHORITY_PROOF_INVALID"|"ORPA_AUTHORITY_DRIFTED"|"ORPA_REPRESENTATION_EVIDENCE_REQUIRED"|"ORPA_REPRESENTATION_EVIDENCE_INVALID"|"ORPA_REPRESENTATION_EVIDENCE_EXPIRED"|"ORPA_REPRESENTATION_ISSUER_UNTRUSTED"|"ORPA_SCOPE_UNSUPPORTED"|"ORPA_SCOPE_NOT_GRANTED"|"ORPA_SCOPE_PROHIBITED"|"ORPA_SCOPE_EXPANSION_PROHIBITED"|"ORPA_RECIPIENT_AMBIGUOUS"|"ORPA_AUTHORITY_REVOKED"|"ORPA_AUTHORITY_SUPERSEDED"|"ORPA_ELIGIBILITY_EXPIRED"|"ORPA_ELIGIBILITY_REPLAYED"|"ORPA_PERSISTENCE_FAILED"|"ORPA_AUDIT_FAILED";
export class OrpaFailureV1 extends Error { constructor(readonly code:OrpaFailureCodeV1){super(code);this.name="OrpaFailureV1";} }

export interface OrganizationalRepresentationClaimV1 { readonly version:1;readonly claim_id:string;readonly legal_entity_id:string;readonly company_binding_id:string;readonly actor_principal_id:string;readonly membership_id:string;readonly claimed_position?:string;readonly representation_basis:"GOVERNED_REPRESENTATION_REVIEW";readonly requested_scope:OrganizationalRepresentationScopeV1;readonly requested_processing_scope?:string;readonly requested_policy_ownership_scope?:string;readonly effective_at:string;readonly expires_at:string;readonly evidence_references:readonly string[];readonly correlation_id:string;readonly caused_by:readonly string[]; }
export interface OrganizationalRepresentationEvidenceV1 { readonly version:1;readonly evidence_id:string;readonly evidence_class:"GOVERNED_MANUAL_REPRESENTATION_DECISION"|"EFFECTIVE_OAG_AUTHORITY_PROOF";readonly actor_principal_id:string;readonly legal_entity_id:string;readonly company_binding_id:string;readonly authorized_scopes:readonly OrganizationalRepresentationScopeV1[];readonly issuer_id:string;readonly effective_at:string;readonly expires_at:string;readonly revoked_at?:string;readonly superseded_by_evidence_id?:string;readonly immutable_digest:string;readonly governed_reference:string;readonly caused_by:readonly string[]; }
export interface OrganizationalRepresentationDecisionV1 { readonly version:1;readonly decision_id:string;readonly claim_id:string;readonly decision:"GRANTED"|"DENIED";readonly approver_id:string;readonly reason_codes:readonly string[];readonly decided_at:string;readonly correlation_id:string;readonly caused_by:readonly string[]; }
export interface OrganizationalRepresentationAuthorityV1 { readonly version:1;readonly authority_id:string;readonly actor_principal_id:string;readonly membership_id:string;readonly legal_entity_id:string;readonly company_binding_id:string;readonly oag_proof_id?:string;readonly representation_evidence_ids:readonly string[];readonly authorized_scopes:readonly OrganizationalRepresentationScopeV1[];readonly prohibited_scopes:readonly string[];readonly approver_id:string;readonly policy_version:"ORPA_POLICY_V1";readonly effective_at:string;readonly expires_at:string;readonly lifecycle_state:"ACTIVE"|"REVOKED"|"SUPERSEDED";readonly correlation_id:string;readonly caused_by:readonly string[];readonly grants_execution:false; }
export interface OrganizationalRepresentationEligibilityV1 { readonly version:1;readonly eligibility_id:string;readonly authority_id:string;readonly actor_principal_id:string;readonly membership_id:string;readonly legal_entity_id:string;readonly company_binding_id:string;readonly requested_scope:OrganizationalRepresentationScopeV1;readonly future_consumer:"PT_WU2_TENANT_PROVIDER_TRUST_POLICY"|"PLATFORM_CONTRACT_ACCEPTANCE";readonly issued_at:string;readonly expires_at:string;readonly oag_proof_id?:string;readonly policy_version:"ORPA_POLICY_V1";readonly correlation_id:string;readonly caused_by:readonly string[];readonly transferable:false;readonly executable:false; }
export interface OrpaCurrentStateV1 { readonly state_source:"TRUSTED_DURABLE_READ_MODEL";readonly legal_entity:LegalEntityIdentityV1;readonly company_binding:CompanyLegalEntityBindingV1;readonly principal:{readonly principal_id:string;readonly lifecycle_state:string};readonly session:{readonly session_id:string;readonly principal_id:string;readonly lifecycle_state:string;readonly expires_at:string};readonly membership:{readonly membership_id:string;readonly principal_id:string;readonly company_id:string;readonly lifecycle_state:string};readonly oag_proof?:OagProof&{readonly proof_id:string;readonly expires_at?:string;readonly drifted?:boolean}; }
export interface OrpaAuthorityRequestV1 { readonly claim:OrganizationalRepresentationClaimV1;readonly evidence:readonly OrganizationalRepresentationEvidenceV1[];readonly state:OrpaCurrentStateV1;readonly approver_id:string;readonly prohibited_scopes?:readonly string[]; }
