import { OrpaFailureV1,type OrganizationalRepresentationAuthorityV1,type OrganizationalRepresentationClaimV1,type OrganizationalRepresentationEligibilityV1,type OrganizationalRepresentationEvidenceV1 } from "./organizational.representation.contracts.v1";
export class OrganizationalRepresentationD1V1{constructor(private readonly db:D1Database){}
 async persistGrant(claim:OrganizationalRepresentationClaimV1,evidence:readonly OrganizationalRepresentationEvidenceV1[],authority:OrganizationalRepresentationAuthorityV1,at:string):Promise<void>{const decision=`decision:${authority.authority_id}`;try{await this.db.batch([
  this.db.prepare("INSERT INTO orpa_representation_claims VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(claim.claim_id,1,claim.legal_entity_id,claim.company_binding_id,claim.actor_principal_id,claim.membership_id,claim.claimed_position??null,claim.representation_basis,claim.requested_scope,claim.requested_processing_scope??null,claim.requested_policy_ownership_scope??null,claim.effective_at,claim.expires_at,JSON.stringify(claim.evidence_references),claim.correlation_id,JSON.stringify(claim.caused_by)),
  ...evidence.map(e=>this.db.prepare("INSERT INTO orpa_representation_evidence VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(e.evidence_id,1,e.evidence_class,e.actor_principal_id,e.legal_entity_id,e.company_binding_id,JSON.stringify(e.authorized_scopes),e.issuer_id,e.effective_at,e.expires_at,e.revoked_at??null,e.superseded_by_evidence_id??null,e.immutable_digest,e.governed_reference,JSON.stringify(e.caused_by))),
  this.db.prepare("INSERT INTO orpa_authority_decisions VALUES (?,?,?,?,?,?,?,?)").bind(decision,claim.claim_id,"GRANTED",authority.approver_id,"[]",at,claim.correlation_id,JSON.stringify(authority.caused_by)),
  this.db.prepare("INSERT INTO orpa_authorities VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(authority.authority_id,1,decision,authority.actor_principal_id,authority.membership_id,authority.legal_entity_id,authority.company_binding_id,authority.oag_proof_id??null,JSON.stringify(authority.representation_evidence_ids),authority.approver_id,authority.policy_version,authority.effective_at,authority.expires_at,"ACTIVE",authority.correlation_id,JSON.stringify(authority.caused_by),0),
  ...authority.authorized_scopes.map(s=>this.db.prepare("INSERT INTO orpa_authority_scopes VALUES (?,?,'GRANTED')").bind(authority.authority_id,s)),...authority.prohibited_scopes.map(s=>this.db.prepare("INSERT INTO orpa_authority_scopes VALUES (?,?,'PROHIBITED')").bind(authority.authority_id,s)),
  this.audit(`audit:${authority.authority_id}`,"AUTHORITY_GRANTED",authority.authority_id,claim.requested_scope,"GRANTED",null,authority.approver_id,claim.correlation_id,authority.caused_by,at)
 ]);}catch(error){const found=await this.db.prepare("SELECT authority_id FROM orpa_authorities WHERE authority_id=?").bind(authority.authority_id).first();if(found)return;throw new OrpaFailureV1("ORPA_PERSISTENCE_FAILED");}}
 async persistEligibility(e:OrganizationalRepresentationEligibilityV1):Promise<void>{try{await this.db.batch([this.db.prepare("INSERT INTO orpa_eligibilities VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NULL,NULL)").bind(e.eligibility_id,1,e.authority_id,e.actor_principal_id,e.membership_id,e.legal_entity_id,e.company_binding_id,e.requested_scope,e.future_consumer,e.issued_at,e.expires_at,e.oag_proof_id??null,e.policy_version,e.correlation_id,JSON.stringify(e.caused_by),0,0),this.audit(`audit:${e.eligibility_id}`,"ELIGIBILITY_ISSUED",e.eligibility_id,e.requested_scope,"ISSUED",null,e.actor_principal_id,e.correlation_id,e.caused_by,e.issued_at)]);}catch{throw new OrpaFailureV1("ORPA_PERSISTENCE_FAILED");}}
 async persistDenial(claim:OrganizationalRepresentationClaimV1,approver:string,reason:string,at:string):Promise<void>{try{await this.db.batch([this.db.prepare("INSERT INTO orpa_representation_claims VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(claim.claim_id,1,claim.legal_entity_id,claim.company_binding_id,claim.actor_principal_id,claim.membership_id,claim.claimed_position??null,claim.representation_basis,claim.requested_scope,claim.requested_processing_scope??null,claim.requested_policy_ownership_scope??null,claim.effective_at,claim.expires_at,JSON.stringify(claim.evidence_references),claim.correlation_id,JSON.stringify(claim.caused_by)),this.db.prepare("INSERT INTO orpa_authority_decisions VALUES (?,?,?,?,?,?,?,?)").bind(`decision:${claim.claim_id}`,claim.claim_id,"DENIED",approver,JSON.stringify([reason]),at,claim.correlation_id,JSON.stringify(claim.caused_by)),this.audit(`audit:denial:${claim.claim_id}`,"AUTHORITY_DENIED",claim.claim_id,claim.requested_scope,"DENIED",reason,approver,claim.correlation_id,claim.caused_by,at)]);}catch{throw new OrpaFailureV1("ORPA_PERSISTENCE_FAILED");}}
 async consumeEligibility(id:string,at:string,reference:string):Promise<boolean>{const r=await this.db.prepare("UPDATE orpa_eligibilities SET consumed_at=?,consumption_reference=? WHERE eligibility_id=? AND consumed_at IS NULL AND expires_at>?").bind(at,reference,id,at).run();return r.meta.changes===1;}
 async transition(authorityId:string,to:"REVOKED"|"SUPERSEDED",reference:string,at:string,correlation:string,causedBy:readonly string[],successor?:string){try{await this.db.batch([this.db.prepare("INSERT INTO orpa_authority_transitions VALUES (?,?,?,?,?,?,?,?,?)").bind(`transition:${reference}`,authorityId,"ACTIVE",to,reference,at,successor??null,correlation,JSON.stringify(causedBy)),this.audit(`audit:transition:${reference}`,`AUTHORITY_${to}`,authorityId,null,to,null,"ORPA_RUNTIME",correlation,causedBy,at)]);}catch{throw new OrpaFailureV1("ORPA_PERSISTENCE_FAILED");}}
 private audit(id:string,type:string,subject:string,scope:string|null,outcome:string,reason:string|null,actor:string,correlation:string,caused:readonly string[],at:string){return this.db.prepare("INSERT INTO orpa_audit_events VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(id,type,subject,scope,outcome,reason,actor,"ORPA_POLICY_V1",correlation,JSON.stringify(caused),at);}}
