import { OrpaFailureV1,type OrpaAuthorityRequestV1,type OrganizationalRepresentationAuthorityV1,type OrganizationalRepresentationEligibilityV1,type OrganizationalRepresentationScopeV1 } from "./organizational.representation.contracts.v1";
import { ORPA_OAG_REQUIRED_SCOPES_V1,ORPA_POLICY_VERSION_V1,ORPA_SCOPES_V1,ORPA_TRUSTED_REPRESENTATION_ISSUERS_V1,deepFreeze } from "./organizational.representation.policy.v1";
async function id(prefix:string,value:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return `${prefix}_${Array.from(new Uint8Array(d)).map(x=>x.toString(16).padStart(2,"0")).join("").slice(0,32)}`;}
export async function grantOrganizationalRepresentationAuthorityV1(req:OrpaAuthorityRequestV1,now:string):Promise<OrganizationalRepresentationAuthorityV1>{
 const c=req.claim,s=req.state;if(s.state_source!=="TRUSTED_DURABLE_READ_MODEL"||!c.claim_id||c.expires_at<=now||!ORPA_SCOPES_V1.includes(c.requested_scope))throw new OrpaFailureV1(!ORPA_SCOPES_V1.includes(c.requested_scope)?"ORPA_SCOPE_UNSUPPORTED":"ORPA_REQUEST_INVALID");
 if(s.legal_entity.legal_entity_id!==c.legal_entity_id)throw new OrpaFailureV1("ORPA_LEGAL_ENTITY_NOT_VERIFIED");if(s.legal_entity.verification_status==="REVOKED")throw new OrpaFailureV1("ORPA_LEGAL_ENTITY_REVOKED");if(s.legal_entity.verification_status!=="VERIFIED_BY_AUTHORIZED_REVIEW"||s.legal_entity.reverify_at&&s.legal_entity.reverify_at<=now)throw new OrpaFailureV1("ORPA_LEGAL_ENTITY_EXPIRED");
 if(s.company_binding.binding_id!==c.company_binding_id||s.company_binding.legal_entity_id!==c.legal_entity_id)throw new OrpaFailureV1("ORPA_COMPANY_BINDING_INVALID");
 if(s.principal.principal_id!==c.actor_principal_id||s.session.principal_id!==c.actor_principal_id)throw new OrpaFailureV1("ORPA_ACTOR_SUBSTITUTED");if(s.principal.lifecycle_state!=="ACTIVE")throw new OrpaFailureV1("ORPA_PRINCIPAL_INVALID");if(s.session.lifecycle_state!=="ACTIVE"||s.session.expires_at<=now)throw new OrpaFailureV1("ORPA_SESSION_INVALID");
 if(!s.membership)throw new OrpaFailureV1("ORPA_MEMBERSHIP_REQUIRED");if(s.membership.membership_id!==c.membership_id||s.membership.principal_id!==c.actor_principal_id||s.membership.company_id!==s.company_binding.company_id||s.membership.lifecycle_state!=="ACTIVE")throw new OrpaFailureV1("ORPA_MEMBERSHIP_INVALID");
 const manual=req.evidence.filter(e=>e.evidence_class==="GOVERNED_MANUAL_REPRESENTATION_DECISION");if(manual.length===0)throw new OrpaFailureV1("ORPA_REPRESENTATION_EVIDENCE_REQUIRED");if(manual.length>1)throw new OrpaFailureV1("ORPA_RECIPIENT_AMBIGUOUS");
 for(const e of req.evidence){if(e.actor_principal_id!==c.actor_principal_id||e.legal_entity_id!==c.legal_entity_id||e.company_binding_id!==c.company_binding_id)throw new OrpaFailureV1("ORPA_REPRESENTATION_EVIDENCE_INVALID");if(!ORPA_TRUSTED_REPRESENTATION_ISSUERS_V1.includes(e.issuer_id))throw new OrpaFailureV1("ORPA_REPRESENTATION_ISSUER_UNTRUSTED");if(e.expires_at<=now)throw new OrpaFailureV1("ORPA_REPRESENTATION_EVIDENCE_EXPIRED");if(e.revoked_at)throw new OrpaFailureV1("ORPA_AUTHORITY_REVOKED");if(!e.authorized_scopes.includes(c.requested_scope))throw new OrpaFailureV1("ORPA_SCOPE_NOT_GRANTED");}
 const prohibited=req.prohibited_scopes??[];if(prohibited.includes(c.requested_scope))throw new OrpaFailureV1("ORPA_SCOPE_PROHIBITED");
 if(ORPA_OAG_REQUIRED_SCOPES_V1.includes(c.requested_scope)){const p=s.oag_proof;if(!p)throw new OrpaFailureV1("ORPA_AUTHORITY_PROOF_REQUIRED");if(p.actor_id!==c.actor_principal_id||p.company_id!==s.company_binding.company_id)throw new OrpaFailureV1("ORPA_AUTHORITY_PROOF_INVALID");if(p.drifted)throw new OrpaFailureV1("ORPA_AUTHORITY_DRIFTED");if(p.expires_at&&p.expires_at<=now)throw new OrpaFailureV1("ORPA_AUTHORITY_PROOF_INVALID");}
 const evidenceIds=req.evidence.map(e=>e.evidence_id).sort();const authorityId=await id("orpa",[c.legal_entity_id,c.company_binding_id,c.actor_principal_id,c.membership_id,c.requested_scope,...evidenceIds].join("|"));
 return deepFreeze({version:1,authority_id:authorityId,actor_principal_id:c.actor_principal_id,membership_id:c.membership_id,legal_entity_id:c.legal_entity_id,company_binding_id:c.company_binding_id,...(s.oag_proof?{oag_proof_id:s.oag_proof.proof_id}:{}),representation_evidence_ids:evidenceIds,authorized_scopes:[c.requested_scope],prohibited_scopes:[...prohibited],approver_id:req.approver_id,policy_version:ORPA_POLICY_VERSION_V1,effective_at:c.effective_at,expires_at:c.expires_at,lifecycle_state:"ACTIVE",correlation_id:c.correlation_id,caused_by:[...c.caused_by,...evidenceIds],grants_execution:false});
}
export async function issueOrganizationalRepresentationEligibilityV1(authority:OrganizationalRepresentationAuthorityV1,state:OrpaAuthorityRequestV1["state"],scope:OrganizationalRepresentationScopeV1,consumer:OrganizationalRepresentationEligibilityV1["future_consumer"],now:string,expiresAt:string):Promise<OrganizationalRepresentationEligibilityV1>{if(state.state_source!=="TRUSTED_DURABLE_READ_MODEL"||state.legal_entity.legal_entity_id!==authority.legal_entity_id||state.company_binding.binding_id!==authority.company_binding_id||state.principal.principal_id!==authority.actor_principal_id||state.membership.membership_id!==authority.membership_id)throw new OrpaFailureV1("ORPA_ACTOR_SUBSTITUTED");if(state.principal.lifecycle_state!=="ACTIVE"||state.session.lifecycle_state!=="ACTIVE"||state.membership.lifecycle_state!=="ACTIVE"||state.session.expires_at<=now)throw new OrpaFailureV1("ORPA_MEMBERSHIP_INVALID");if(authority.oag_proof_id&&(!state.oag_proof||state.oag_proof.proof_id!==authority.oag_proof_id||state.oag_proof.drifted))throw new OrpaFailureV1("ORPA_AUTHORITY_DRIFTED");if(authority.lifecycle_state==="REVOKED")throw new OrpaFailureV1("ORPA_AUTHORITY_REVOKED");if(authority.lifecycle_state==="SUPERSEDED")throw new OrpaFailureV1("ORPA_AUTHORITY_SUPERSEDED");if(authority.expires_at<=now||expiresAt<=now||expiresAt>authority.expires_at)throw new OrpaFailureV1("ORPA_ELIGIBILITY_EXPIRED");if(!authority.authorized_scopes.includes(scope))throw new OrpaFailureV1("ORPA_SCOPE_EXPANSION_PROHIBITED");const eid=await id("orpe",[authority.authority_id,scope,consumer,now,expiresAt].join("|"));return deepFreeze({version:1,eligibility_id:eid,authority_id:authority.authority_id,actor_principal_id:authority.actor_principal_id,membership_id:authority.membership_id,legal_entity_id:authority.legal_entity_id,company_binding_id:authority.company_binding_id,requested_scope:scope,future_consumer:consumer,issued_at:now,expires_at:expiresAt,...(authority.oag_proof_id?{oag_proof_id:authority.oag_proof_id}:{}),policy_version:ORPA_POLICY_VERSION_V1,correlation_id:authority.correlation_id,caused_by:[authority.authority_id],transferable:false,executable:false});}
