import {deepCopyAndFreeze} from "../../knowledge-exposure/knowledge.projection.guard.v1";import {D1PlatformAlertRepositoryV1} from "../platform.alert.d1.v1";import {PLATFORM_COMPANY_ID,PLATFORM_RECIPIENT_POLICY_VERSION,PLATFORM_TENANT_ID,type PlatformAlertRecipientEligibilityV1} from "../recipient";import {PlatformAlertDisclosureError,type PlatformAlertDisclosureAdmissionV1,type PlatformAlertDisclosureConsumptionClaimV1,type PlatformAlertDisclosureContextV1,type PlatformAlertDisclosureRepositoryV1} from "./platform.alert.disclosure.contracts.v1";
const list=(v:unknown):readonly string[]=>{try{const x=JSON.parse(String(v));if(Array.isArray(x)&&x.every(y=>typeof y==="string"))return Object.freeze(x);}catch{}throw new PlatformAlertDisclosureError("PLATFORM_ALERT_DISCLOSURE_ADMISSION_FAILED");};
export class D1PlatformAlertDisclosureRepositoryV1 implements PlatformAlertDisclosureRepositoryV1{constructor(private readonly db:D1Database){}
 async load(alertId:string,eligibilityId:string,now:string):Promise<PlatformAlertDisclosureContextV1|null>{const row=await this.db.prepare(`SELECT r.*,a.deduplication_id,a.source_evidence_id alert_source_id,a.source_evidence_digest alert_source_digest,a.expires_at alert_expires,
 p.lifecycle_state actor_state,m.lifecycle_state membership_state,o.effective_until ownership_until,t.lifecycle_state entitlement_state,t.effective_at entitlement_effective,t.expires_at entitlement_expires,t.allowed_channels_json,
 ap.eligibility_state authority_eligibility,ap.drift_state authority_drift,ap.expires_at authority_expires,
 ep.lifecycle_state endpoint_state,ep.verification_state,ep.effective_at endpoint_effective,ep.expires_at endpoint_expires,
 er.entitlement_id entitlement_revoked,xr.endpoint_id endpoint_revoked,
 EXISTS(SELECT 1 FROM platform_alert_admission_decisions d WHERE d.alert_id=a.alert_id AND d.decision='ADMITTED') alert_admitted,
 EXISTS(SELECT 1 FROM platform_alert_source_bindings b WHERE b.alert_id=a.alert_id AND b.source_evidence_id=a.source_evidence_id AND b.source_evidence_digest=a.source_evidence_digest) source_current
 FROM platform_alert_recipient_resolution_decisions r JOIN platform_alert_intents a ON a.alert_id=r.alert_id
 JOIN platform_alert_recipient_entitlements t ON t.entitlement_id=r.entitlement_id JOIN platform_operational_authority_proofs ap ON ap.authority_proof_id=r.authority_proof_id
 JOIN platform_alert_recipient_endpoints ep ON ep.endpoint_id=r.endpoint_id JOIN oir_principals p ON p.principal_id=t.principal_id
 JOIN oir_organization_memberships m ON m.membership_id=t.membership_id AND m.principal_id=t.principal_id AND m.company_id=t.platform_company_id
 JOIN oir_tenant_company_ownership o ON o.tenant_id=t.platform_tenant_id AND o.company_id=t.platform_company_id
 LEFT JOIN platform_alert_entitlement_revocations er ON er.entitlement_id=t.entitlement_id LEFT JOIN platform_alert_endpoint_revocations xr ON xr.endpoint_id=ep.endpoint_id
 WHERE r.alert_id=? AND r.eligibility_id=?`).bind(alertId,eligibilityId).first<Record<string,unknown>>();if(!row)return null;const alert=await new D1PlatformAlertRepositoryV1(this.db).findByDeduplicationId(String(row.deduplication_id));if(!alert)return null;const recipient=deepCopyAndFreeze({version:1,eligibility_id:String(row.eligibility_id),resolution_id:String(row.resolution_id),alert_id:String(row.alert_id),alert_admission_decision_reference:`platform-alert-admission:${row.alert_id}`,platform_tenant_id:PLATFORM_TENANT_ID,platform_company_id:PLATFORM_COMPANY_ID,accountable_actor_id:String(row.actor_id),authority_proof_id:String(row.authority_proof_id),recipient_entitlement_id:String(row.entitlement_id),endpoint_id:String(row.endpoint_id),endpoint_destination_digest:String(row.destination_digest),channel:row.channel,communication_family:"PLATFORM_OPERATIONAL_ALERT",purpose:"GOVERNED_DELIVERY_REVIEW",urgency:row.urgency,issued_at:String(row.issued_at),expires_at:String(row.expires_at),policy_version:PLATFORM_RECIPIENT_POLICY_VERSION,correlation_id:String(row.correlation_id),causal_references:list(row.causal_references_json)}) as PlatformAlertRecipientEligibilityV1;const active=(from:unknown,to:unknown)=>Date.parse(String(from))<=Date.parse(now)&&Date.parse(String(to))>Date.parse(now);return deepCopyAndFreeze({alert,recipient,alert_admitted:Number(row.alert_admitted)===1&&Date.parse(String(row.alert_expires))>Date.parse(now),source_current:Number(row.source_current)===1,recipient_current:Date.parse(String(row.expires_at))>Date.parse(now),actor_current:row.actor_state==="ACTIVE"&&row.membership_state==="ACTIVE"&&(row.ownership_until==null||Date.parse(String(row.ownership_until))>Date.parse(now)),authority_current:row.authority_eligibility==="ELIGIBLE"&&row.authority_drift==="CURRENT"&&Date.parse(String(row.authority_expires))>Date.parse(now),entitlement_current:row.entitlement_state==="ACTIVE"&&!row.entitlement_revoked&&active(row.entitlement_effective,row.entitlement_expires),endpoint_current:row.endpoint_state==="ACTIVE"&&row.verification_state==="VERIFIED"&&!row.endpoint_revoked&&active(row.endpoint_effective,row.endpoint_expires),channel_permitted:list(row.allowed_channels_json).includes(String(row.channel))}) as PlatformAlertDisclosureContextV1;}
 async persist(a:PlatformAlertDisclosureAdmissionV1){const old=await this.db.prepare("SELECT canonical_digest FROM platform_alert_disclosure_admissions WHERE disclosure_id=?").bind(a.disclosure_id).first<{canonical_digest:string}>();if(old){if(old.canonical_digest!==a.canonical_digest)throw new PlatformAlertDisclosureError("PLATFORM_ALERT_DISCLOSURE_ADMISSION_FAILED");return"IDENTICAL" as const;}try{await this.db.batch([this.db.prepare(`INSERT INTO platform_alert_disclosure_admissions VALUES (${Array(32).fill("?").join(",")})`).bind(a.disclosure_id,a.alert_id,a.recipient_eligibility_id,a.profile_id,a.profile_version,a.alert_admission_decision_reference,a.recipient_resolution_id,a.family,a.purpose,JSON.stringify(a.projection),a.manifest_id,a.projection_digest,a.representation,a.classification,a.sovereignty,a.retention,a.accountable_actor_id,a.recipient_entitlement_id,a.endpoint_id,a.endpoint_destination_digest,a.channel,a.authority_proof_id,a.urgency,a.policy_version,a.admitted_at,a.expires_at,a.correlation_id,JSON.stringify(a.causal_references),a.canonical_digest,1,1,1),this.statement({audit_event_id:`audit:platform-disclosure:admit:${a.disclosure_id}`,event_kind:"ADMISSION_PERSISTED",disclosure_id:a.disclosure_id,alert_id:a.alert_id,recipient_eligibility_id:a.recipient_eligibility_id,profile_id:a.profile_id,profile_version:a.profile_version,projection_digest:a.projection_digest,recipient_entitlement_id:a.recipient_entitlement_id,endpoint_id:a.endpoint_id,endpoint_destination_digest:a.endpoint_destination_digest,channel:a.channel,authority_proof_id:a.authority_proof_id,outcome:"ADMITTED",reason_code:"PLATFORM_ALERT_DISCLOSURE_ADMITTED",correlation_id:a.correlation_id,causal_references:a.causal_references,recorded_at:a.admitted_at})]);return"CREATED" as const;}catch{throw new PlatformAlertDisclosureError("PLATFORM_ALERT_DISCLOSURE_ADMISSION_FAILED");}}
 async read(id:string){const x=await this.db.prepare("SELECT * FROM platform_alert_disclosure_admissions WHERE disclosure_id=?").bind(id).first<Record<string,unknown>>();if(!x)return null;return deepCopyAndFreeze({version:1,disclosure_id:x.disclosure_id,alert_id:x.alert_id,recipient_eligibility_id:x.recipient_eligibility_id,profile_id:x.profile_id,profile_version:x.profile_version,alert_admission_decision_reference:x.alert_admission_decision_reference,recipient_resolution_id:x.recipient_resolution_id,family:x.family,purpose:x.purpose,projection:JSON.parse(String(x.projection_json)),manifest_id:x.manifest_id,projection_digest:x.projection_digest,representation:x.representation,classification:x.classification,sovereignty:x.sovereignty,retention:x.retention,accountable_actor_id:x.accountable_actor_id,recipient_entitlement_id:x.recipient_entitlement_id,endpoint_id:x.endpoint_id,endpoint_destination_digest:x.endpoint_destination_digest,channel:x.channel,authority_proof_id:x.authority_proof_id,urgency:x.urgency,policy_version:x.policy_version,admitted_at:x.admitted_at,expires_at:x.expires_at,correlation_id:x.correlation_id,causal_references:list(x.causal_references_json),canonical_digest:x.canonical_digest}) as PlatformAlertDisclosureAdmissionV1;}
 async consume(a:PlatformAlertDisclosureAdmissionV1,c:PlatformAlertDisclosureConsumptionClaimV1,id:string,at:string){try{await this.db.prepare("INSERT INTO platform_alert_disclosure_consumptions VALUES (?,?,?,?,?,?,?)").bind(id,a.disclosure_id,c.consuming_runtime,at,c.correlation_id,JSON.stringify(c.causal_references),"CONSUMED").run();return true;}catch{return false;}}
 async audit(e:Readonly<Record<string,unknown>>){try{await this.statement(e).run();}catch{throw new PlatformAlertDisclosureError("PLATFORM_ALERT_DISCLOSURE_AUDIT_FAILED");}}
 private statement(e:Readonly<Record<string,unknown>>){return this.db.prepare(`INSERT INTO platform_alert_disclosure_audit_events VALUES (${Array(19).fill("?").join(",")})`).bind(e.audit_event_id,e.event_kind,e.disclosure_id??null,e.alert_id??null,e.recipient_eligibility_id??null,e.profile_id,e.profile_version,e.projection_digest??null,e.recipient_entitlement_id??null,e.endpoint_id??null,e.endpoint_destination_digest??null,e.channel??null,e.authority_proof_id??null,e.outcome,e.reason_code,e.correlation_id,JSON.stringify(e.causal_references??[]),e.recorded_at,null);}}
