import { describe,expect,it,vi } from "vitest";
import { deepCopyAndFreeze } from "../../../knowledge-exposure/knowledge.projection.guard.v1";
import { knowledge,manifest } from "../../../knowledge-exposure/__tests__/fixtures";
import type { OutboundDisclosureDispatchEligibilityV1 } from "../../outbound.disclosure.contracts.v1";
import { GovernedEmailDeliveryV1 } from "../governed.email.delivery.v1";import { sealGovernedEmailV1,verifySealedGovernedEmailV1 } from "../governed.email.seal.v1";import type { GovernedEmailDeliveryEvidenceV1,GovernedEmailEvidenceRepositoryV1 } from "../governed.email.contracts.v1";
const NOW="2026-08-02T10:00:40.000Z",m=deepCopyAndFreeze(manifest([knowledge()]));
function eligibility(overrides:Partial<OutboundDisclosureDispatchEligibilityV1>={}):OutboundDisclosureDispatchEligibilityV1{return deepCopyAndFreeze({version:1,disclosure_id:"outbound-disclosure:1",decision_id:"decision:1",binding_id:"binding:1",knowledge_consumption_id:"knowledge-consumption:1",authority_reference:"authority:1",governance_references:["governance:opaque"],tenant_id:"tenant:1",company_id:"company:1",purpose:"CUSTOMER_QUOTATION_DISCLOSURE",communication_family:"TENANT_OPERATIONAL_DISCLOSURE",manifest_id:`${m.schema_id}@${m.schema_version}`,projection_digest:m.projection_digest,recipient:{version:1,recipient_id:"customer:001",recipient_class:"AUTHORIZED_BUSINESS_RECIPIENT",entitlement_reference:"entitlement:1",tenant_id:"tenant:1",company_id:"company:1"},channel:"EMAIL",representation:"STRUCTURED_JSON",classification:"INTERNAL",policy_version:"OUTBOUND_DISCLOSURE_POLICY_V1",admitted_at:"2026-08-02T10:00:30.000Z",expires_at:"2026-08-02T10:01:30.000Z",correlation_id:"correlation:1",causal_references:["audit:1"],canonical_digest:"a".repeat(64),disclosure_consumption_id:"disclosure-consumption:1",consumed_at:"2026-08-02T10:00:35.000Z",transport_executed:false,...overrides}) as OutboundDisclosureDispatchEligibilityV1;}
class Evidence implements GovernedEmailEvidenceRepositoryV1{used=new Set<string>();events:GovernedEmailDeliveryEvidenceV1[]=[];async reserve(id:string){if(this.used.has(id))return false;this.used.add(id);return true;}async append(e:GovernedEmailDeliveryEvidenceV1){this.events.push(e);}}
function sealed(e=eligibility()){return sealGovernedEmailV1({eligibility:e,manifest:m,projection:{price:42}});}
function services(evidence=new Evidence()){const send=vi.fn(async()=>({ok:true,provider_message_reference:"provider-message-secret"}));return{evidence,send,delivery:new GovernedEmailDeliveryV1({endpoint:{resolve:async()=>({recipient_id:"customer:001",entitlement_reference:"entitlement:1",endpoint_reference:"email-endpoint:1",address:"customer@example.test"})},provider:{provider_id:"email-relay",send},evidence,now:()=>NOW})};}
describe("OKS-WU4B governed email delivery",()=>{
 it("seals the exact structured projection deterministically and immutably",()=>{const a=sealed(),b=sealed();expect(a.canonical_projection).toBe('{"price":42}');expect(a.canonical_projection_digest).toBe(b.canonical_projection_digest);expect(Object.isFrozen(a)).toBe(true);});
 it("rejects non-email channels and unsupported rendering representations",()=>{expect(()=>sealed(eligibility({channel:"SMS"}))).toThrow(/EMAIL_CHANNEL_NOT_ADMITTED/);expect(()=>sealed(eligibility({representation:"PLAIN_TEXT"}))).toThrow(/EMAIL_REPRESENTATION_NOT_SUPPORTED/);});
 it("rejects manifest, field, value, and sealed projection substitution",()=>{expect(()=>sealGovernedEmailV1({eligibility:eligibility(),manifest:{...m,projection_digest:"b".repeat(64)},projection:{price:42}})).toThrow(/EMAIL_MANIFEST_SUBSTITUTED/);expect(()=>sealGovernedEmailV1({eligibility:eligibility(),manifest:m,projection:{price:42,secret:1}})).toThrow(/EMAIL_PROJECTION_SUBSTITUTED/);expect(()=>sealGovernedEmailV1({eligibility:eligibility(),manifest:m,projection:{price:Number.NaN}})).toThrow(/EMAIL_PROJECTION_SUBSTITUTED/);const changed=deepCopyAndFreeze({...sealed(),canonical_projection:'{"price":99}'});expect(()=>verifySealedGovernedEmailV1(changed as any,NOW)).toThrow(/EMAIL_PROJECTION_MUTATED/);});
 it("resolves the bound recipient and sends one exact payload",async()=>{const x=services(),out=await x.delivery.deliver(sealed());expect(x.send).toHaveBeenCalledWith({to:"customer@example.test",subject:"PlannerAgent disclosure",body:'{"price":42}',content_type:"application/json; charset=utf-8"});expect(out).toMatchObject({status:"SUCCEEDED",content_returned:false});expect(JSON.stringify(out.delivery_evidence)).not.toMatch(/example\.test|provider-message-secret|price/i);});
 it("rejects missing or substituted resolved recipients before sending",async()=>{const send=vi.fn(),base={provider:{provider_id:"email-relay",send},evidence:new Evidence(),now:()=>NOW};for(const resolved of [null,{recipient_id:"other",entitlement_reference:"entitlement:1",endpoint_reference:"endpoint",address:"x@example.test"}]){const delivery=new GovernedEmailDeliveryV1({...base,endpoint:{resolve:async()=>resolved as any}});await expect(delivery.deliver(sealed())).rejects.toMatchObject({code:resolved?"EMAIL_RECIPIENT_SUBSTITUTED":"EMAIL_RECIPIENT_RESOLUTION_FAILED"});}expect(send).not.toHaveBeenCalled();});
 it("allows only one delivery attempt per disclosure consumption",async()=>{const x=services(),s=sealed();await x.delivery.deliver(s);await expect(x.delivery.deliver(s)).rejects.toMatchObject({code:"EMAIL_FANOUT_NOT_ADMITTED"});expect(x.send).toHaveBeenCalledTimes(1);});
 it("fails closed on expiry and provider failure",async()=>{expect(()=>verifySealedGovernedEmailV1(sealed(),"2026-08-02T10:01:30.000Z")).toThrow(/EMAIL_DISCLOSURE_EXPIRED/);const evidence=new Evidence(),delivery=new GovernedEmailDeliveryV1({endpoint:{resolve:async()=>({recipient_id:"customer:001",entitlement_reference:"entitlement:1",endpoint_reference:"endpoint",address:"x@example.test"})},provider:{provider_id:"email-relay",send:async()=>({ok:false})},evidence,now:()=>NOW});await expect(delivery.deliver(sealed())).rejects.toMatchObject({code:"EMAIL_PROVIDER_FAILURE"});expect(evidence.events[0]).toMatchObject({status:"FAILED",failure_code:"EMAIL_PROVIDER_FAILURE"});});
 it("never returns content and persists only content-free digests",async()=>{const x=services(),out=await x.delivery.deliver(sealed());expect("body" in out).toBe(false);expect(out.delivery_evidence.canonical_projection_digest).toMatch(/^[0-9a-f]{64}$/);expect(out.delivery_evidence.request_digest).toMatch(/^[0-9a-f]{64}$/);});
});
