import { applyD1Migrations,env } from "cloudflare:test";
import { beforeAll,beforeEach,describe,expect,it } from "vitest";
import m12 from "../../../../../migrations/0012_knowledge_exposure_persistence.sql?raw";import m14 from "../../../../../migrations/0014_outbound_disclosure_admission.sql?raw";import m15 from "../../../../../migrations/0015_governed_email_delivery.sql?raw";
import { D1GovernedEmailEvidenceRepositoryV1 } from "../governed.email.d1.v1";import type { GovernedEmailDeliveryEvidenceV1 } from "../governed.email.contracts.v1";
const db=env.POLICIES_DB,queries=(sql:string)=>sql.split(/;\s*\r?\n(?=CREATE (?:TABLE|(?:UNIQUE )?INDEX|TRIGGER))/).map(q=>q.trim()).filter(Boolean).map(q=>q.endsWith(";")?q:`${q};`),repository=new D1GovernedEmailEvidenceRepositoryV1(db),DIGEST="a".repeat(64);
beforeAll(async()=>applyD1Migrations(db,[m12,m14,m15].map((sql,i)=>({name:`m${i}`,queries:queries(sql)}))));
beforeEach(async()=>{for(const table of ["governed_email_delivery_evidence","governed_email_delivery_reservations","outbound_disclosure_audit_events","outbound_disclosure_consumptions","outbound_disclosure_admissions","knowledge_exposure_audit_events","knowledge_exposure_consumptions","knowledge_exposure_projection_bindings","knowledge_exposure_decisions"])await db.prepare(`DELETE FROM ${table}`).run();await db.prepare(`INSERT INTO knowledge_exposure_decisions VALUES (${Array(30).fill("?").join(",")})`).bind("decision:1","request:1","ADMITTED","participation:1","principal:1","session:1","membership:1","tenant:1","company:1","authority:1",null,"OUTBOUND_DISCLOSURE","CUSTOMER_QUOTATION_DISCLOSURE","POLICY","AUTHORIZED_BUSINESS_RECIPIENT","recipient:1","INTERNAL","TENANT_LOCAL","EU","NO_RETENTION","schema@1",DIGEST,"[]","2026-08-02T10:00:00.000Z","2026-08-02T10:02:00.000Z","[]","knowledge-evidence:1","correlation:1","[]","canonical:1").run();await db.prepare("INSERT INTO knowledge_exposure_projection_bindings VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").bind("binding:1","decision:1","schema@1",DIGEST,"[]","OUTBOUND_DISCLOSURE","CUSTOMER_QUOTATION_DISCLOSURE","AUTHORIZED_BUSINESS_RECIPIENT","recipient:1","tenant:1","company:1","2026-08-02T10:00:00.000Z").run();await db.prepare("INSERT INTO knowledge_exposure_consumptions VALUES (?,?,?,?,?,?,?,?,?,?)").bind("knowledge-consumption:1","decision:1","binding:1","wu4a","OUTBOUND_COMMUNICATION","recipient:1","2026-08-02T10:00:10.000Z","correlation:1","[]","CONSUMED").run();await db.prepare("INSERT INTO outbound_disclosure_admissions VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind("disclosure:1","decision:1","binding:1","knowledge-consumption:1","authority:1","[]","tenant:1","company:1","CUSTOMER_QUOTATION_DISCLOSURE","TENANT_OPERATIONAL_DISCLOSURE","schema@1",DIGEST,"recipient:1","AUTHORIZED_BUSINESS_RECIPIENT","entitlement:1","EMAIL","STRUCTURED_JSON","INTERNAL","OUTBOUND_DISCLOSURE_POLICY_V1","2026-08-02T10:00:20.000Z","2026-08-02T10:01:20.000Z","correlation:1","[]","canonical:2").run();await db.prepare("INSERT INTO outbound_disclosure_consumptions VALUES (?,?,?,?,?,?,?)").bind("disclosure-consumption:1","disclosure:1","wu4b","2026-08-02T10:00:30.000Z","correlation:1","[]","CONSUMED").run();});
function evidence(overrides:Partial<GovernedEmailDeliveryEvidenceV1>={}):GovernedEmailDeliveryEvidenceV1{return{version:1,delivery_evidence_id:"email-evidence:1",disclosure_id:"disclosure:1",disclosure_consumption_id:"disclosure-consumption:1",recipient_id:"recipient:1",entitlement_reference:"entitlement:1",endpoint_reference:"endpoint:1",projection_digest:DIGEST,canonical_projection_digest:"b".repeat(64),request_digest:"c".repeat(64),provider:"email-relay",dispatched_at:"2026-08-02T10:00:40.000Z",status:"SUCCEEDED",provider_message_digest:"d".repeat(64),causal_references:[],...overrides};}
describe("OKS-WU4B governed email evidence (actual D1)",()=>{
 it("applies the exact reservation and evidence schema with foreign keys",async()=>{const rows=await db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'governed_email_%' ORDER BY name").all<{name:string}>();expect(rows.results.map(r=>r.name)).toEqual(["governed_email_delivery_evidence","governed_email_delivery_reservations"]);expect((await db.prepare("PRAGMA foreign_keys").first<{foreign_keys:number}>())?.foreign_keys).toBe(1);});
 it("persists exact content-free digests without address, body, response, or credential",async()=>{expect(await repository.reserve("disclosure-consumption:1","email-relay","2026-08-02T10:00:40.000Z")).toBe(true);await repository.append(evidence());const row=await db.prepare("SELECT * FROM governed_email_delivery_evidence").first<Record<string,unknown>>();expect(row).toMatchObject({projection_digest:DIGEST,canonical_projection_digest:"b".repeat(64),request_digest:"c".repeat(64)});expect(Object.keys(row??{}).join(" ")).not.toMatch(/address|body|response|credential|api_key/i);});
 it("enforces one reservation and one evidence row per disclosure consumption",async()=>{expect(await repository.reserve("disclosure-consumption:1","email-relay","now")).toBe(true);expect(await repository.reserve("disclosure-consumption:1","email-relay","now")).toBe(false);await repository.append(evidence());await expect(repository.append(evidence({delivery_evidence_id:"email-evidence:2"}))).rejects.toMatchObject({code:"EMAIL_DELIVERY_EVIDENCE_FAILED"});});
 it("makes reservations and delivery evidence immutable",async()=>{await repository.reserve("disclosure-consumption:1","email-relay","now");await repository.append(evidence());for(const sql of ["UPDATE governed_email_delivery_reservations SET provider='other'","DELETE FROM governed_email_delivery_reservations","UPDATE governed_email_delivery_evidence SET provider='other'","DELETE FROM governed_email_delivery_evidence"])await expect(db.prepare(sql).run()).rejects.toThrow(/IMMUTABLE/);});
});
