import type {OperationalSignalScopeBindingV1} from "../cockpit/operational.signal.evaluation.scope.v1";
import {verifyOperationalSignalEvaluationScopeV1} from "../cockpit/operational.signal.evaluation.scope.v1";
import type {MaterialOperationalConsequenceRefV1} from "../cognition/canonical.operational.roles.v1";
import {createProtectedOperationalObjectiveBindingV1,type ProtectedOperationalObjectiveBindingV1} from "../cognition/protected.operational.objective.v1";
import type {CanonicalDecisionOpportunityPurposeV1} from "./canonical.decision.opportunity.v1";

export type CanonicalDecisionInfluenceabilityStatusV1="INFLUENCEABLE"|"NOT_INFLUENCEABLE"|"UNRESOLVED"|"INSUFFICIENT_EVIDENCE";
export type CanonicalDecisionInfluenceabilityInputV1=Readonly<{version:1;request_id:string;company_id:string;evaluation_scope:OperationalSignalScopeBindingV1;protected_objective?:ProtectedOperationalObjectiveBindingV1;material_consequence?:MaterialOperationalConsequenceRefV1;governing_condition_ref:string;trajectory_ref:string;decision_purpose:CanonicalDecisionOpportunityPurposeV1;status:CanonicalDecisionInfluenceabilityStatusV1;intervention_class_refs:readonly string[];material_effect_refs:readonly string[];determination_basis_refs:readonly string[];evidence_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[];evidence_as_of:string;evaluated_at:string}>;
export type CanonicalDecisionInfluenceabilityV1=Readonly<{version:1;request_id:string;company_id:string;scope_id:string;scope_digest:string;protected_objective_ref?:string;protected_objective_digest?:string;material_consequence_ref?:string;material_consequence_digest?:string;governing_condition_ref:string;trajectory_ref:string;decision_purpose:CanonicalDecisionOpportunityPurposeV1;status:CanonicalDecisionInfluenceabilityStatusV1;intervention_class_refs:readonly string[];material_effect_refs:readonly string[];determination_basis_refs:readonly string[];evidence_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[];evidence_as_of:string;evaluated_at:string;influenceability_id:string;influenceability_digest:string;digest_algorithm:"SHA-256";global_no_decision_claim:false;guarantees_success:false;selects_option:false;recommended:false;executable:false;observational_only:true;grants_authority:false;grants_execution:false;grants_remediation:false;company_global_claim:false}>;

const statuses=new Set(["INFLUENCEABLE","NOT_INFLUENCEABLE","UNRESOLVED","INSUFFICIENT_EVIDENCE"]),purposes=new Set(["PRESERVATION","RECOVERY","CONTAINMENT","ADAPTATION"]);
function ref(v:string|undefined,c:string){const x=v?.trim();if(!x||!/^[A-Za-z0-9][A-Za-z0-9._-]*:[^\s]+$/.test(x))throw new Error(c);return x;}
function refs(v:readonly string[],c:string,required=true):readonly string[]{if(!Array.isArray(v))throw new Error(c);const x=[...new Set(v.map(i=>ref(i,c)))].sort();if(required&&!x.length)throw new Error(c);return x;}
function time(v:string|undefined,c:string){if(!v||!Number.isFinite(Date.parse(v)))throw new Error(c);return v;}
function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return`{${Object.entries(v as Record<string,unknown>).filter(([,x])=>x!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(",")}}`;return JSON.stringify(v);}
async function sha(v:unknown){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(v)));return Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,"0")).join("");}
function freeze<T>(v:T):Readonly<T>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v as Record<string,unknown>).forEach(freeze);Object.freeze(v);}return v;}
function semantic(i:CanonicalDecisionInfluenceabilityV1){return{version:i.version,request_id:i.request_id,company_id:i.company_id,scope_id:i.scope_id,scope_digest:i.scope_digest,...(i.protected_objective_ref?{protected_objective_ref:i.protected_objective_ref,protected_objective_digest:i.protected_objective_digest}:{}),...(i.material_consequence_ref?{material_consequence_ref:i.material_consequence_ref,material_consequence_digest:i.material_consequence_digest}:{}),governing_condition_ref:i.governing_condition_ref,trajectory_ref:i.trajectory_ref,decision_purpose:i.decision_purpose,status:i.status,intervention_class_refs:i.intervention_class_refs,material_effect_refs:i.material_effect_refs,determination_basis_refs:i.determination_basis_refs,evidence_refs:i.evidence_refs,qualification_refs:i.qualification_refs,provenance_refs:i.provenance_refs,causal_lineage_refs:i.causal_lineage_refs,evidence_as_of:i.evidence_as_of,evaluated_at:i.evaluated_at};}

export async function verifyCanonicalDecisionInfluenceabilityV1(i:CanonicalDecisionInfluenceabilityV1):Promise<void>{const d=await sha(semantic(i));if(d!==i.influenceability_digest||i.influenceability_id!==`canonical-decision-influenceability:sha256:${d}`)throw new Error("DECISION_INFLUENCEABILITY_INTEGRITY_INVALID");if(i.digest_algorithm!=="SHA-256"||i.global_no_decision_claim!==false||i.guarantees_success!==false||i.selects_option!==false||i.recommended!==false||i.executable!==false||i.observational_only!==true||i.grants_authority!==false||i.grants_execution!==false||i.grants_remediation!==false||i.company_global_claim!==false)throw new Error("DECISION_INFLUENCEABILITY_BOUNDARY_INVALID");}

export async function createCanonicalDecisionInfluenceabilityV1(input:CanonicalDecisionInfluenceabilityInputV1):Promise<CanonicalDecisionInfluenceabilityV1>{
 if(input.version!==1)throw new Error("DECISION_INFLUENCEABILITY_VERSION_UNSUPPORTED");if(!statuses.has(input.status))throw new Error("DECISION_INFLUENCEABILITY_STATUS_INVALID");if(!purposes.has(input.decision_purpose))throw new Error("DECISION_INFLUENCEABILITY_PURPOSE_INVALID");
 for(const k of ["authority_tier","subscription_tier","approval_ref","delegation_ref","credential_ref","execution_capability_ref","recommended_action_ref","selected_option_ref","optimizer_candidate_ref","capability_registry_ref","decision_margin_ref","urgency","cost_of_waiting","pressure"]){if(k in (input as unknown as Record<string,unknown>))throw new Error("DECISION_INFLUENCEABILITY_UNSUPPORTED_INPUT");}
 await verifyOperationalSignalEvaluationScopeV1(input.evaluation_scope.scope,input);const s=input.evaluation_scope.scope;if(s.request_id!==input.request_id||s.company_id!==input.company_id)throw new Error("DECISION_INFLUENCEABILITY_SCOPE_BINDING_MISMATCH");
 const evidence_as_of=time(input.evidence_as_of,"DECISION_INFLUENCEABILITY_AS_OF_INVALID"),evaluated_at=time(input.evaluated_at,"DECISION_INFLUENCEABILITY_EVALUATED_AT_INVALID");if(evidence_as_of!==input.evaluation_scope.evidence_as_of||evaluated_at!==input.evaluation_scope.evaluated_at||Date.parse(evidence_as_of)>Date.parse(evaluated_at))throw new Error("DECISION_INFLUENCEABILITY_TIME_BINDING_INVALID");
 if(!input.protected_objective&&!input.material_consequence)throw new Error("DECISION_INFLUENCEABILITY_CONTEXT_REQUIRED");
 if(input.protected_objective){const o=input.protected_objective,r=await createProtectedOperationalObjectiveBindingV1(o);if(r.objective_binding_id!==o.objective_binding_id||r.objective_binding_digest!==o.objective_binding_digest)throw new Error("DECISION_INFLUENCEABILITY_OBJECTIVE_INTEGRITY_INVALID");if(o.request_id!==input.request_id||o.company_id!==input.company_id||o.scope_id!==s.scope_id||o.scope_digest!==s.scope_digest)throw new Error("DECISION_INFLUENCEABILITY_OBJECTIVE_SCOPE_MISMATCH");}
 if(input.material_consequence){const c=input.material_consequence,x={version:c.version,subject:c.subject,scope_ref:c.scope_ref,evidence_refs:c.evidence_refs,provenance_refs:c.provenance_refs,causal_lineage_refs:c.causal_lineage_refs,role:c.role,consequence_ref:c.consequence_ref,consequence_kind_ref:c.consequence_kind_ref,materiality_ref:c.materiality_ref},d=await sha(x);if(d!==c.role_digest||c.role_id!==`operational-role:consequence:sha256:${d}`)throw new Error("DECISION_INFLUENCEABILITY_CONSEQUENCE_INTEGRITY_INVALID");if(c.subject.company_id!==input.company_id||c.scope_ref!==s.scope_id)throw new Error("DECISION_INFLUENCEABILITY_CONSEQUENCE_SCOPE_MISMATCH");}
 const intervention_class_refs=refs(input.intervention_class_refs,"DECISION_INFLUENCEABILITY_INTERVENTION_INVALID",false);if(input.status==="INFLUENCEABLE"&&!intervention_class_refs.length)throw new Error("DECISION_INFLUENCEABILITY_INTERVENTION_REQUIRED");if(input.status!=="INFLUENCEABLE"&&intervention_class_refs.length)throw new Error("DECISION_INFLUENCEABILITY_INTERVENTION_NOT_ESTABLISHED");
 const normalized={version:1 as const,request_id:input.request_id.trim(),company_id:input.company_id.trim(),scope_id:s.scope_id,scope_digest:s.scope_digest,...(input.protected_objective?{protected_objective_ref:input.protected_objective.objective_binding_id,protected_objective_digest:input.protected_objective.objective_binding_digest}:{}),...(input.material_consequence?{material_consequence_ref:input.material_consequence.role_id,material_consequence_digest:input.material_consequence.role_digest}:{}),governing_condition_ref:ref(input.governing_condition_ref,"DECISION_INFLUENCEABILITY_CONDITION_REQUIRED"),trajectory_ref:ref(input.trajectory_ref,"DECISION_INFLUENCEABILITY_TRAJECTORY_REQUIRED"),decision_purpose:input.decision_purpose,status:input.status,intervention_class_refs,material_effect_refs:refs(input.material_effect_refs,"DECISION_INFLUENCEABILITY_MATERIAL_EFFECT_REQUIRED"),determination_basis_refs:refs(input.determination_basis_refs,"DECISION_INFLUENCEABILITY_BASIS_REQUIRED"),evidence_refs:refs(input.evidence_refs,"DECISION_INFLUENCEABILITY_EVIDENCE_REQUIRED"),qualification_refs:refs(input.qualification_refs,"DECISION_INFLUENCEABILITY_QUALIFICATION_REQUIRED"),provenance_refs:refs(input.provenance_refs,"DECISION_INFLUENCEABILITY_PROVENANCE_REQUIRED"),causal_lineage_refs:refs(input.causal_lineage_refs,"DECISION_INFLUENCEABILITY_LINEAGE_REQUIRED"),evidence_as_of,evaluated_at};const influenceability_digest=await sha(normalized);
 return freeze({...normalized,influenceability_id:`canonical-decision-influenceability:sha256:${influenceability_digest}`,influenceability_digest,digest_algorithm:"SHA-256" as const,global_no_decision_claim:false as const,guarantees_success:false as const,selects_option:false as const,recommended:false as const,executable:false as const,observational_only:true as const,grants_authority:false as const,grants_execution:false as const,grants_remediation:false as const,company_global_claim:false as const});
}
