import {createCanonicalDecisionPressureDimensionV1,type CanonicalDecisionPressureDimensionIdentityV1,type CanonicalDecisionPressureDimensionV1} from "./canonical.decision.pressure.dimension.v1";

export const CANONICAL_PRESSURE_COMPOSITION_POLICY_ID="pressure-composition-policy:certified-dimension-vector-v1" as const;
export type CanonicalPressureDimensionOperandStatusV1="ESTABLISHED"|"UNRESOLVED"|"INSUFFICIENT_EVIDENCE"|"WINDOW_EXHAUSTED";
export type CanonicalPressureDimensionOperandV1=Readonly<{dimension:CanonicalDecisionPressureDimensionIdentityV1;status:CanonicalPressureDimensionOperandStatusV1;value?:CanonicalDecisionPressureDimensionV1;evidence_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[]}>;
export type CanonicalDecisionPressureCompositionV1=Readonly<{version:1;pressure_kind:"CERTIFIED_DIMENSION_VECTOR";composition_policy_id:typeof CANONICAL_PRESSURE_COMPOSITION_POLICY_ID;composition_policy_version:"1";composition_policy_digest:string;aggregation_semantics:"VECTOR_PRESERVING_NO_AGGREGATE_WEIGHTS_OR_THRESHOLDS";request_id:string;company_id:string;scope_id:string;scope_digest:string;evidence_as_of:string;evaluated_at:string;completeness_status:"COMPLETE"|"QUALIFIED_PARTIAL_UNRESOLVED"|"QUALIFIED_PARTIAL_INSUFFICIENT_EVIDENCE";components:readonly Readonly<{dimension:CanonicalDecisionPressureDimensionIdentityV1;status:CanonicalPressureDimensionOperandStatusV1;dimension_id?:string;dimension_digest?:string;projection_mode?:"CONTINUOUS"|"ORDINAL";continuous_value?:number;ordinal_state?:string}>[];evidence_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[];pressure_id:string;pressure_digest:string;digest_algorithm:"SHA-256";observational_only:true;recommended:false;executable:false;grants_authority:false;grants_execution:false;grants_remediation:false;opens_attention:false;company_global_claim:false}>;
const identities=["IMPACT","URGENCY","COST_OF_WAITING"]as const,forbidden=["decision_margin","raw_lateness","simulator_score","optimizer_score","llm_score","level","priority","attention","authority_tier","subscription_tier","commercial_plan","credit_balance","provider","model","approval","delegation","recommendation","action"];
function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return`{${Object.entries(v as Record<string,unknown>).filter(([,x])=>x!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(",")}}`;return JSON.stringify(v)}
async function sha(v:unknown){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(v)));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}
function freeze<T>(v:T):Readonly<T>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v as Record<string,unknown>).forEach(freeze);Object.freeze(v)}return v}
function refs(v:readonly string[],code:string){const x=[...new Set(v.map(y=>y.trim()).filter(Boolean))].sort();if(!x.length)throw new Error(code);return x}
async function verifyDimension(d:CanonicalDecisionPressureDimensionV1){const rebuilt=await createCanonicalDecisionPressureDimensionV1(d);if(rebuilt.dimension_id!==d.dimension_id||rebuilt.dimension_digest!==d.dimension_digest)throw new Error("PRESSURE_COMPOSITION_DIMENSION_INTEGRITY_INVALID")}
async function policyDigest(){return sha({policy_id:CANONICAL_PRESSURE_COMPOSITION_POLICY_ID,version:"1",dimensions:identities,aggregation_semantics:"VECTOR_PRESERVING_NO_AGGREGATE_WEIGHTS_OR_THRESHOLDS",minimum_sufficient:"IMPACT_ESTABLISHED_WITH_EXPLICIT_OTHER_DIMENSION_STATUS",zero_semantics:"ESTABLISHED_ZERO_IS_NOT_MISSING",window_exhausted_semantics:"EXPLICIT_NON_NUMERIC_STATUS_NO_MAXIMUM_FABRICATION"})}

export async function composeCanonicalDecisionPressureV1(input:Readonly<{version:1;impact:CanonicalPressureDimensionOperandV1;urgency:CanonicalPressureDimensionOperandV1;cost_of_waiting:CanonicalPressureDimensionOperandV1}>):Promise<CanonicalDecisionPressureCompositionV1>{
 if(input.version!==1)throw new Error("PRESSURE_COMPOSITION_VERSION_UNSUPPORTED");for(const k of forbidden)if(k in (input as object))throw new Error("PRESSURE_COMPOSITION_UNSUPPORTED_INPUT");const operands=[input.impact,input.urgency,input.cost_of_waiting];if(operands.some((x,i)=>x.dimension!==identities[i]))throw new Error("PRESSURE_COMPOSITION_DIMENSION_ORDER_INVALID");if(input.impact.status!=="ESTABLISHED"||!input.impact.value)throw new Error("PRESSURE_COMPOSITION_IMPACT_REQUIRED");for(const o of operands){refs(o.evidence_refs,"PRESSURE_COMPOSITION_EVIDENCE_REQUIRED");refs(o.qualification_refs,"PRESSURE_COMPOSITION_QUALIFICATION_REQUIRED");refs(o.provenance_refs,"PRESSURE_COMPOSITION_PROVENANCE_REQUIRED");refs(o.causal_lineage_refs,"PRESSURE_COMPOSITION_LINEAGE_REQUIRED");if(o.status==="ESTABLISHED"){if(!o.value||o.value.dimension!==o.dimension)throw new Error("PRESSURE_COMPOSITION_ESTABLISHED_VALUE_REQUIRED");await verifyDimension(o.value)}else if(o.value)throw new Error("PRESSURE_COMPOSITION_MISSING_VALUE_FORBIDDEN")}
 const established=operands.filter(x=>x.value).map(x=>x.value!),anchor=established[0]!;for(const d of established)if(d.request_id!==anchor.request_id||d.company_id!==anchor.company_id||d.scope_id!==anchor.scope_id||d.scope_digest!==anchor.scope_digest||d.evidence_as_of!==anchor.evidence_as_of||d.evaluated_at!==anchor.evaluated_at)throw new Error("PRESSURE_COMPOSITION_CONTEXT_MISMATCH");const components=operands.map(o=>({dimension:o.dimension,status:o.status,...(o.value?{dimension_id:o.value.dimension_id,dimension_digest:o.value.dimension_digest,projection_mode:o.value.projection_mode,...(o.value.projection_mode==="CONTINUOUS"?{continuous_value:o.value.value}:{ordinal_state:o.value.ordinal_state})}:{})}));const completeness_status:CanonicalDecisionPressureCompositionV1["completeness_status"]=operands.some(x=>x.status==="INSUFFICIENT_EVIDENCE")?"QUALIFIED_PARTIAL_INSUFFICIENT_EVIDENCE":operands.every(x=>x.status==="ESTABLISHED")?"COMPLETE":"QUALIFIED_PARTIAL_UNRESOLVED",composition_policy_digest=await policyDigest();const semantic={version:1 as const,pressure_kind:"CERTIFIED_DIMENSION_VECTOR"as const,composition_policy_id:CANONICAL_PRESSURE_COMPOSITION_POLICY_ID,composition_policy_version:"1"as const,composition_policy_digest,aggregation_semantics:"VECTOR_PRESERVING_NO_AGGREGATE_WEIGHTS_OR_THRESHOLDS"as const,request_id:anchor.request_id,company_id:anchor.company_id,scope_id:anchor.scope_id,scope_digest:anchor.scope_digest,evidence_as_of:anchor.evidence_as_of,evaluated_at:anchor.evaluated_at,completeness_status,components,evidence_refs:refs(operands.flatMap(x=>x.evidence_refs),"PRESSURE_COMPOSITION_EVIDENCE_REQUIRED"),qualification_refs:refs(operands.flatMap(x=>x.qualification_refs),"PRESSURE_COMPOSITION_QUALIFICATION_REQUIRED"),provenance_refs:refs(operands.flatMap(x=>x.provenance_refs),"PRESSURE_COMPOSITION_PROVENANCE_REQUIRED"),causal_lineage_refs:refs([...operands.flatMap(x=>x.causal_lineage_refs),...established.map(x=>x.dimension_id)],"PRESSURE_COMPOSITION_LINEAGE_REQUIRED")};const pressure_digest=await sha(semantic);return freeze({...semantic,pressure_id:`canonical-decision-pressure-composition:sha256:${pressure_digest}`,pressure_digest,digest_algorithm:"SHA-256"as const,observational_only:true as const,recommended:false as const,executable:false as const,grants_authority:false as const,grants_execution:false as const,grants_remediation:false as const,opens_attention:false as const,company_global_claim:false as const})
}
export async function verifyCanonicalDecisionPressureCompositionV1(value:CanonicalDecisionPressureCompositionV1):Promise<void>{const{pressure_id:_id,pressure_digest:_digest,digest_algorithm:_algorithm,observational_only:_observational,recommended:_recommended,executable:_executable,grants_authority:_authority,grants_execution:_execution,grants_remediation:_remediation,opens_attention:_attention,company_global_claim:_global,...semantic}=value,digest=await sha(semantic),policy=await policyDigest();if(value.pressure_digest!==digest||value.pressure_id!==`canonical-decision-pressure-composition:sha256:${digest}`||value.composition_policy_digest!==policy||value.observational_only!==true||value.recommended!==false||value.executable!==false||value.grants_authority!==false||value.grants_execution!==false||value.grants_remediation!==false||value.opens_attention!==false||value.company_global_claim!==false)throw new Error("PRESSURE_COMPOSITION_INTEGRITY_INVALID")}
