import type { OperationalSignalScopeBindingV1 } from "../cockpit/operational.signal.evaluation.scope.v1";
import { verifyOperationalSignalEvaluationScopeV1 } from "../cockpit/operational.signal.evaluation.scope.v1";
import type { DecisionPressureConsequenceCategoryV1 } from "./canonical.decision.pressure.contract.v1";

export type TemporalResolutionStatusV1 = "KNOWN" | "UNRESOLVED" | "INSUFFICIENT_EVIDENCE";
export type DecisionWindowStatusV1 = "OPEN" | "CLOSED" | "UNRESOLVED" | "INSUFFICIENT_EVIDENCE";
export type DecisionWindowEndReasonV1 = "MATERIAL_CONSEQUENCE_ONSET" | "EFFECTIVE_OPTION_LOSS" | "EFFECTIVE_OPTION_MATERIAL_WORSENING" | "UNRESOLVED";
export type CorrectiveOptionFeasibilityStatusV1 = "FEASIBLE" | "UNAVAILABLE" | "UNRESOLVED" | "INSUFFICIENT_EVIDENCE";
export type AvailabilityClassV1 = "CURRENT_INVENTORY" | "SCHEDULED_RECEIPT" | "SUPPLIER_COMMITMENT" | "PRODUCTION_COMPLETION" | "RECONCILED_EXTERNAL_OBSERVATION";
export type CanonicalQuantityV1 = Readonly<{ value: number; unit_ref: string; quantity_evidence_ref: string }>;
export type CanonicalDurationV1 = Readonly<{ value: number; unit_ref: string }>;

type BoundInput = Readonly<{ version: 1; request_id: string; company_id: string; evaluation_scope: OperationalSignalScopeBindingV1; evidence_refs: readonly string[]; provenance_refs: readonly string[]; causal_lineage_refs: readonly string[] }>;
type BoundOutput = Readonly<{ evidence_as_of: string; evaluated_at: string; scope_id: string; scope_digest: string; digest_algorithm: "SHA-256"; company_global_claim: false; grants_execution: false; grants_remediation: false; observational_only: true }>;

export type DatedOperationalRequirementInputV1 = BoundInput & Readonly<{ item_ref: string; order_ref?: string; production_order_ref?: string; quantity: CanonicalQuantityV1; requirement_time: string }>;
export type DatedOperationalRequirementV1 = DatedOperationalRequirementInputV1 & BoundOutput & Readonly<{ requirement_id: string; requirement_digest: string }>;
export type DatedOperationalAvailabilityInputV1 = BoundInput & Readonly<{ item_ref: string; quantity: CanonicalQuantityV1; availability_time: string; availability_class: AvailabilityClassV1 }>;
export type DatedOperationalAvailabilityV1 = DatedOperationalAvailabilityInputV1 & BoundOutput & Readonly<{ availability_id: string; availability_digest: string }>;
export type SupplierCommitmentInputV1 = BoundInput & Readonly<{ supplier_ref: string; item_ref: string; commitment_ref: string; commitment_version_ref: string; committed_arrival_time: string; observed_at: string; effective_at: string; qualification_ref: string }>;
export type SupplierCommitmentV1 = SupplierCommitmentInputV1 & BoundOutput & Readonly<{ supplier_commitment_id: string; supplier_commitment_digest: string }>;
export type MaterialConsequenceOccurrenceInputV1 = BoundInput & Readonly<{ occurrence_status: TemporalResolutionStatusV1; consequence_ref: string; category: DecisionPressureConsequenceCategoryV1; affected_operational_refs: readonly string[]; causal_condition_ref: string; consequence_time?: string }>;
export type MaterialConsequenceOccurrenceV1 = MaterialConsequenceOccurrenceInputV1 & BoundOutput & Readonly<{ occurrence_id: string; occurrence_digest: string }>;
export type OperationalSlackAssessmentInputV1 = BoundInput & Readonly<{ requirement: DatedOperationalRequirementV1; availability: DatedOperationalAvailabilityV1; consequence_occurrence_ref?: string }>;
export type OperationalSlackAssessmentV1 = OperationalSlackAssessmentInputV1 & BoundOutput & Readonly<{ slack_assessment_id: string; slack_assessment_digest: string }>;
export type OperationalSlackResultInputV1 = Readonly<{ version: 1; assessment: OperationalSlackAssessmentV1; status: TemporalResolutionStatusV1; absorbable_delay?: CanonicalDurationV1; reason_ref: string }>;
export type OperationalSlackResultV1 = BoundOutput & Readonly<{ version: 1; slack_result_id: string; slack_result_digest: string; slack_assessment_id: string; status: TemporalResolutionStatusV1; absorbable_delay?: CanonicalDurationV1; reason_ref: string; request_id: string; company_id: string }>;
export type CorrectiveOptionFeasibilityInputV1 = BoundInput & Readonly<{ corrective_option_ref: string; item_refs: readonly string[]; affected_path_ref?: string; feasibility_status: CorrectiveOptionFeasibilityStatusV1; unavailable_at?: string; materially_worsens_at?: string; consequence_refs: readonly string[] }>;
export type CorrectiveOptionFeasibilityV1 = CorrectiveOptionFeasibilityInputV1 & BoundOutput & Readonly<{ feasibility_id: string; feasibility_digest: string }>;
export type CanonicalDecisionWindowAssessmentInputV1 = BoundInput & Readonly<{ governing_condition_ref: string; consequence_occurrences: readonly MaterialConsequenceOccurrenceV1[]; slack_results: readonly OperationalSlackResultV1[]; corrective_option_feasibility: readonly CorrectiveOptionFeasibilityV1[]; local_window_refs: readonly string[] }>;
export type CanonicalDecisionWindowAssessmentV1 = CanonicalDecisionWindowAssessmentInputV1 & BoundOutput & Readonly<{ assessment_id: string; assessment_digest: string }>;
export type CanonicalDecisionWindowResultInputV1 = Readonly<{ version: 1; assessment: CanonicalDecisionWindowAssessmentV1; status: DecisionWindowStatusV1; reference_time?: string; end_time?: string; remaining_duration?: CanonicalDurationV1; end_reason: DecisionWindowEndReasonV1; governing_consequence_occurrence_ref?: string; governing_option_feasibility_ref?: string; causal_lineage_refs: readonly string[] }>;
export type CanonicalDecisionWindowResultV1 = BoundOutput & Readonly<{ version: 1; result_id: string; result_digest: string; assessment_id: string; request_id: string; company_id: string; status: DecisionWindowStatusV1; reference_time?: string; end_time?: string; remaining_duration?: CanonicalDurationV1; end_reason: DecisionWindowEndReasonV1; governing_consequence_occurrence_ref?: string; governing_option_feasibility_ref?: string; causal_lineage_refs: readonly string[] }>;

const categories = new Set(["PRODUCTION_INTERRUPTION", "CAPACITY_LOSS", "DOWNSTREAM_DISRUPTION", "SERVICE_IMPACT", "CORRECTION_COST_INCREASE", "CORRECTIVE_OPTION_LOSS"]);
const availabilityClasses = new Set(["CURRENT_INVENTORY", "SCHEDULED_RECEIPT", "SUPPLIER_COMMITMENT", "PRODUCTION_COMPLETION", "RECONCILED_EXTERNAL_OBSERVATION"]);
const temporalStatuses = new Set(["KNOWN", "UNRESOLVED", "INSUFFICIENT_EVIDENCE"]);

function ref(value: string | undefined, code: string): string { const v = value?.trim(); if (!v || !/^[A-Za-z0-9][A-Za-z0-9._-]*:[^\s]+$/.test(v)) throw new Error(code); return v; }
function refs(values: readonly string[], code: string, required = true): readonly string[] { const v = [...new Set(values.map(x => ref(x, code)))].sort(); if (required && !v.length) throw new Error(code); return v; }
function time(value: string | undefined, code: string): string { if (!value || !Number.isFinite(Date.parse(value))) throw new Error(code); return value; }
function quantity(value: CanonicalQuantityV1, code: string): CanonicalQuantityV1 { if (!value || !Number.isFinite(value.value) || value.value < 0) throw new Error(code); return { value: value.value, unit_ref: ref(value.unit_ref, code), quantity_evidence_ref: ref(value.quantity_evidence_ref, code) }; }
function duration(value: CanonicalDurationV1 | undefined, code: string): CanonicalDurationV1 { if (!value || !Number.isFinite(value.value) || value.value < 0) throw new Error(code); return { value: value.value, unit_ref: ref(value.unit_ref, code) }; }
function canonicalJson(value: unknown): string { if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`; if (value && typeof value === "object") { const entries = Object.entries(value as Record<string, unknown>).filter(([,v]) => v !== undefined).sort(([a],[b]) => a.localeCompare(b)); return `{${entries.map(([k,v]) => `${JSON.stringify(k)}:${canonicalJson(v)}`).join(",")}}`; } return JSON.stringify(value); }
async function digest(value: unknown): Promise<string> { const hash = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(canonicalJson(value))); return Array.from(new Uint8Array(hash), b => b.toString(16).padStart(2,"0")).join(""); }
function freeze<T>(value: T): Readonly<T> { if (value && typeof value === "object" && !Object.isFrozen(value)) { Object.values(value as Record<string, unknown>).forEach(freeze); Object.freeze(value); } return value; }
async function bound(input: BoundInput): Promise<BoundOutput> { if (input.version !== 1) throw new Error("WINDOW_VERSION_UNSUPPORTED"); await verifyOperationalSignalEvaluationScopeV1(input.evaluation_scope.scope, input); if (input.evaluation_scope.scope.request_id !== input.request_id || input.evaluation_scope.scope.company_id !== input.company_id) throw new Error("WINDOW_SCOPE_BINDING_MISMATCH"); const asOf = Date.parse(input.evaluation_scope.evidence_as_of), evaluated = Date.parse(input.evaluation_scope.evaluated_at); if (!Number.isFinite(asOf) || !Number.isFinite(evaluated) || asOf > evaluated) throw new Error("WINDOW_TIME_INVALID"); refs(input.evidence_refs, "WINDOW_EVIDENCE_REQUIRED"); refs(input.provenance_refs, "WINDOW_PROVENANCE_REQUIRED"); refs(input.causal_lineage_refs, "WINDOW_LINEAGE_REQUIRED"); return { evidence_as_of: input.evaluation_scope.evidence_as_of, evaluated_at: input.evaluation_scope.evaluated_at, scope_id: input.evaluation_scope.scope.scope_id, scope_digest: input.evaluation_scope.scope.scope_digest, digest_algorithm: "SHA-256", company_global_claim: false, grants_execution: false, grants_remediation: false, observational_only: true }; }
async function artifact<T extends BoundInput>(kind: string, input: T, semantic: object): Promise<T & BoundOutput & Record<string,string>> { const envelope = await bound(input); const d = await digest({ kind, scope_digest: envelope.scope_digest, ...semantic }); return freeze({ ...input, ...envelope, [`${kind}_id`]: `canonical-${kind.replaceAll("_","-")}:sha256:${d}`, [`${kind}_digest`]: d }) as T & BoundOutput & Record<string,string>; }

export async function createDatedOperationalRequirementV1(input: DatedOperationalRequirementInputV1): Promise<DatedOperationalRequirementV1> { const normalized = { ...input, item_ref: ref(input.item_ref,"REQUIREMENT_ITEM_REQUIRED"), ...(input.order_ref ? { order_ref: ref(input.order_ref,"REQUIREMENT_ORDER_INVALID") } : {}), ...(input.production_order_ref ? { production_order_ref: ref(input.production_order_ref,"REQUIREMENT_PRODUCTION_ORDER_INVALID") } : {}), quantity: quantity(input.quantity,"REQUIREMENT_QUANTITY_INVALID"), requirement_time: time(input.requirement_time,"REQUIREMENT_TIME_INVALID") }; return artifact("requirement", normalized, normalized) as unknown as Promise<DatedOperationalRequirementV1>; }
export async function createDatedOperationalAvailabilityV1(input: DatedOperationalAvailabilityInputV1): Promise<DatedOperationalAvailabilityV1> { if (!availabilityClasses.has(input.availability_class)) throw new Error("AVAILABILITY_CLASS_INVALID"); const normalized = { ...input, item_ref: ref(input.item_ref,"AVAILABILITY_ITEM_REQUIRED"), quantity: quantity(input.quantity,"AVAILABILITY_QUANTITY_INVALID"), availability_time: time(input.availability_time,"AVAILABILITY_TIME_INVALID") }; return artifact("availability", normalized, normalized) as unknown as Promise<DatedOperationalAvailabilityV1>; }
export async function createSupplierCommitmentV1(input: SupplierCommitmentInputV1): Promise<SupplierCommitmentV1> { const normalized = { ...input, supplier_ref: ref(input.supplier_ref,"COMMITMENT_SUPPLIER_REQUIRED"), item_ref: ref(input.item_ref,"COMMITMENT_ITEM_REQUIRED"), commitment_ref: ref(input.commitment_ref,"COMMITMENT_REF_REQUIRED"), commitment_version_ref: ref(input.commitment_version_ref,"COMMITMENT_VERSION_REQUIRED"), qualification_ref: ref(input.qualification_ref,"COMMITMENT_QUALIFICATION_REQUIRED"), committed_arrival_time: time(input.committed_arrival_time,"COMMITMENT_ARRIVAL_INVALID"), observed_at: time(input.observed_at,"COMMITMENT_OBSERVED_INVALID"), effective_at: time(input.effective_at,"COMMITMENT_EFFECTIVE_INVALID") }; return artifact("supplier_commitment", normalized, normalized) as unknown as Promise<SupplierCommitmentV1>; }
export async function createMaterialConsequenceOccurrenceV1(input: MaterialConsequenceOccurrenceInputV1): Promise<MaterialConsequenceOccurrenceV1> { if (!temporalStatuses.has(input.occurrence_status) || !categories.has(input.category)) throw new Error("CONSEQUENCE_OCCURRENCE_INVALID"); if (input.occurrence_status === "KNOWN" && !input.consequence_time) throw new Error("CONSEQUENCE_TIME_REQUIRED"); if (input.occurrence_status !== "KNOWN" && input.consequence_time) throw new Error("CONSEQUENCE_TIME_NOT_RESOLVED"); const normalized = { ...input, consequence_ref: ref(input.consequence_ref,"CONSEQUENCE_REF_REQUIRED"), causal_condition_ref: ref(input.causal_condition_ref,"CONSEQUENCE_CONDITION_REQUIRED"), affected_operational_refs: refs(input.affected_operational_refs,"CONSEQUENCE_AFFECTED_REQUIRED"), ...(input.consequence_time ? { consequence_time: time(input.consequence_time,"CONSEQUENCE_TIME_INVALID") } : {}) }; return artifact("occurrence", normalized, normalized) as unknown as Promise<MaterialConsequenceOccurrenceV1>; }
export async function createOperationalSlackAssessmentV1(input: OperationalSlackAssessmentInputV1): Promise<OperationalSlackAssessmentV1> { if (input.requirement.item_ref !== input.availability.item_ref) throw new Error("SLACK_ITEM_MISMATCH"); if (input.requirement.quantity.unit_ref !== input.availability.quantity.unit_ref) throw new Error("SLACK_UNIT_MISMATCH"); if (input.requirement.scope_digest !== input.evaluation_scope.scope.scope_digest || input.availability.scope_digest !== input.evaluation_scope.scope.scope_digest || input.requirement.request_id !== input.request_id || input.availability.company_id !== input.company_id) throw new Error("SLACK_SCOPE_MISMATCH"); const normalized = { ...input, ...(input.consequence_occurrence_ref ? { consequence_occurrence_ref: ref(input.consequence_occurrence_ref,"SLACK_CONSEQUENCE_INVALID") } : {}) }; return artifact("slack_assessment", normalized, { requirement_id: input.requirement.requirement_id, availability_id: input.availability.availability_id, consequence_occurrence_ref: normalized.consequence_occurrence_ref }) as unknown as Promise<OperationalSlackAssessmentV1>; }
export async function createOperationalSlackResultV1(input: OperationalSlackResultInputV1): Promise<OperationalSlackResultV1> { if (!temporalStatuses.has(input.status)) throw new Error("SLACK_STATUS_INVALID"); if (input.status === "KNOWN" && !input.absorbable_delay) throw new Error("SLACK_DURATION_REQUIRED"); if (input.status !== "KNOWN" && input.absorbable_delay) throw new Error("SLACK_DURATION_NOT_RESOLVED"); const delay = input.absorbable_delay ? duration(input.absorbable_delay,"SLACK_DURATION_INVALID") : undefined; const semantic = { assessment_id: input.assessment.slack_assessment_id, status: input.status, absorbable_delay: delay, reason_ref: ref(input.reason_ref,"SLACK_REASON_REQUIRED") }; const d = await digest(semantic); return freeze({ version: 1, slack_result_id: `canonical-slack-result:sha256:${d}`, slack_result_digest: d, slack_assessment_id: input.assessment.slack_assessment_id, request_id: input.assessment.request_id, company_id: input.assessment.company_id, ...semantic, evidence_as_of: input.assessment.evidence_as_of, evaluated_at: input.assessment.evaluated_at, scope_id: input.assessment.scope_id, scope_digest: input.assessment.scope_digest, digest_algorithm: "SHA-256", company_global_claim: false, grants_execution: false, grants_remediation: false, observational_only: true }); }
export async function createCorrectiveOptionFeasibilityV1(input: CorrectiveOptionFeasibilityInputV1): Promise<CorrectiveOptionFeasibilityV1> { if (!new Set(["FEASIBLE","UNAVAILABLE","UNRESOLVED","INSUFFICIENT_EVIDENCE"]).has(input.feasibility_status)) throw new Error("OPTION_STATUS_INVALID"); if (input.feasibility_status === "UNAVAILABLE" && !input.unavailable_at) throw new Error("OPTION_UNAVAILABLE_TIME_REQUIRED"); const normalized = { ...input, corrective_option_ref: ref(input.corrective_option_ref,"OPTION_REF_REQUIRED"), item_refs: refs(input.item_refs,"OPTION_ITEM_REQUIRED",false), consequence_refs: refs(input.consequence_refs,"OPTION_CONSEQUENCE_INVALID",false), ...(input.affected_path_ref ? { affected_path_ref: ref(input.affected_path_ref,"OPTION_PATH_INVALID") } : {}), ...(input.unavailable_at ? { unavailable_at: time(input.unavailable_at,"OPTION_UNAVAILABLE_TIME_INVALID") } : {}), ...(input.materially_worsens_at ? { materially_worsens_at: time(input.materially_worsens_at,"OPTION_WORSENING_TIME_INVALID") } : {}) }; return artifact("feasibility", normalized, normalized) as unknown as Promise<CorrectiveOptionFeasibilityV1>; }
export async function createCanonicalDecisionWindowAssessmentV1(input: CanonicalDecisionWindowAssessmentInputV1): Promise<CanonicalDecisionWindowAssessmentV1> { const scope = input.evaluation_scope.scope.scope_digest; const children = [...input.consequence_occurrences,...input.slack_results,...input.corrective_option_feasibility]; if (children.some(x => x.scope_digest !== scope || x.request_id !== input.request_id || x.company_id !== input.company_id)) throw new Error("WINDOW_CHILD_SCOPE_MISMATCH"); const normalized = { ...input, governing_condition_ref: ref(input.governing_condition_ref,"WINDOW_CONDITION_REQUIRED"), local_window_refs: refs(input.local_window_refs,"WINDOW_LOCAL_REF_INVALID",false) }; return artifact("assessment", normalized, { governing_condition_ref: normalized.governing_condition_ref, consequence_occurrence_ids: input.consequence_occurrences.map(x=>x.occurrence_id).sort(), slack_result_ids: input.slack_results.map(x=>x.slack_result_id).sort(), feasibility_ids: input.corrective_option_feasibility.map(x=>x.feasibility_id).sort(), local_window_refs: normalized.local_window_refs }) as unknown as Promise<CanonicalDecisionWindowAssessmentV1>; }
export async function createCanonicalDecisionWindowResultV1(input: CanonicalDecisionWindowResultInputV1): Promise<CanonicalDecisionWindowResultV1> { const unresolved = input.status === "UNRESOLVED" || input.status === "INSUFFICIENT_EVIDENCE"; if (unresolved && (input.end_reason !== "UNRESOLVED" || input.end_time || input.remaining_duration)) throw new Error("WINDOW_UNRESOLVED_MUST_NOT_FABRICATE_TIME"); if (!unresolved && input.end_reason === "UNRESOLVED") throw new Error("WINDOW_END_REASON_INVALID"); if (input.status === "CLOSED" && !input.end_time) throw new Error("WINDOW_CLOSED_TIME_REQUIRED"); if (input.end_reason === "MATERIAL_CONSEQUENCE_ONSET" && !input.governing_consequence_occurrence_ref) throw new Error("WINDOW_CONSEQUENCE_REF_REQUIRED"); if ((input.end_reason === "EFFECTIVE_OPTION_LOSS" || input.end_reason === "EFFECTIVE_OPTION_MATERIAL_WORSENING") && !input.governing_option_feasibility_ref) throw new Error("WINDOW_OPTION_REF_REQUIRED"); const semantic = { assessment_id: input.assessment.assessment_id, status: input.status, ...(input.reference_time ? { reference_time: time(input.reference_time,"WINDOW_REFERENCE_TIME_INVALID") } : {}), ...(input.end_time ? { end_time: time(input.end_time,"WINDOW_END_TIME_INVALID") } : {}), ...(input.remaining_duration ? { remaining_duration: duration(input.remaining_duration,"WINDOW_REMAINING_INVALID") } : {}), end_reason: input.end_reason, ...(input.governing_consequence_occurrence_ref ? { governing_consequence_occurrence_ref: ref(input.governing_consequence_occurrence_ref,"WINDOW_CONSEQUENCE_REF_INVALID") } : {}), ...(input.governing_option_feasibility_ref ? { governing_option_feasibility_ref: ref(input.governing_option_feasibility_ref,"WINDOW_OPTION_REF_INVALID") } : {}), causal_lineage_refs: refs(input.causal_lineage_refs,"WINDOW_RESULT_LINEAGE_REQUIRED") }; const d = await digest(semantic); return freeze({ version: 1, result_id: `canonical-decision-window-result:sha256:${d}`, result_digest: d, request_id: input.assessment.request_id, company_id: input.assessment.company_id, ...semantic, evidence_as_of: input.assessment.evidence_as_of, evaluated_at: input.assessment.evaluated_at, scope_id: input.assessment.scope_id, scope_digest: input.assessment.scope_digest, digest_algorithm: "SHA-256", company_global_claim: false, grants_execution: false, grants_remediation: false, observational_only: true }); }
