import type { KnowledgeProjectionManifestV1,KnowledgeRetentionV1 } from "../../knowledge-exposure/knowledge.exposure.contracts.v1";
import type { OutboundDisclosureDispatchEligibilityV1 } from "../outbound.disclosure.contracts.v1";
export type GovernedTwilioChannelV1="SMS"|"WHATSAPP";export type GovernedTwilioProductV1="TWILIO_SMS"|"TWILIO_WHATSAPP";
export type GovernedTwilioFailureCode="GOVERNED_TWILIO_ELIGIBILITY_REQUIRED"|"GOVERNED_TWILIO_ELIGIBILITY_INVALID"|"GOVERNED_TWILIO_OPERATION_MISMATCH"|"GOVERNED_TWILIO_CHANNEL_MISMATCH"|"GOVERNED_TWILIO_RECIPIENT_INVALID"|"GOVERNED_TWILIO_RECIPIENT_SUBSTITUTED"|"GOVERNED_TWILIO_SENDER_INVALID"|"GOVERNED_TWILIO_PRODUCT_MISMATCH"|"GOVERNED_TWILIO_PROJECTION_MISMATCH"|"GOVERNED_TWILIO_MESSAGE_DIGEST_MISMATCH"|"GOVERNED_TWILIO_MESSAGE_MUTATED"|"GOVERNED_TWILIO_MESSAGE_TOO_LARGE"|"GOVERNED_TWILIO_CONFIGURATION_INVALID"|"GOVERNED_TWILIO_CREDENTIAL_UNAVAILABLE"|"GOVERNED_TWILIO_ALREADY_DISPATCHED"|"GOVERNED_TWILIO_RESERVATION_FAILED"|"GOVERNED_TWILIO_TIMEOUT"|"GOVERNED_TWILIO_PROVIDER_FAILURE"|"GOVERNED_TWILIO_RESPONSE_INVALID"|"GOVERNED_TWILIO_EVIDENCE_FAILED"|"GOVERNED_TWILIO_LEGACY_BYPASS_PROHIBITED"|"GOVERNED_TWILIO_FALLBACK_NOT_ADMITTED";
export class GovernedTwilioError extends Error{constructor(readonly code:GovernedTwilioFailureCode){super(code);this.name="GovernedTwilioError";}}
export interface GovernedTwilioLineageV1{readonly decision_id:string;readonly binding_id:string;readonly knowledge_consumption_id:string;readonly principal_id:string;readonly region:string;readonly retention:KnowledgeRetentionV1;readonly knowledge_digests:readonly string[];}
export interface GovernedTwilioDestinationV1{readonly recipient_id:string;readonly entitlement_reference:string;readonly channel:GovernedTwilioChannelV1;readonly address:string;}
export interface GovernedTwilioProviderBindingV1{readonly provider_identity:"twilio";readonly product:GovernedTwilioProductV1;readonly sender_identity_reference:string;}
export interface SealedGovernedTwilioMessageV1{readonly version:1;readonly sealed_message_id:string;readonly eligibility:OutboundDisclosureDispatchEligibilityV1;readonly lineage:GovernedTwilioLineageV1;readonly manifest:KnowledgeProjectionManifestV1;readonly communication_family:string;readonly purpose:string;readonly tenant_id:string;readonly company_id:string;readonly principal_id:string;readonly recipient_entitlement_reference:string;readonly destination_digest:string;readonly channel:GovernedTwilioChannelV1;readonly product:GovernedTwilioProductV1;readonly canonical_message:string;readonly message_digest:string;readonly manifest_id:string;readonly projection_digest:string;readonly knowledge_digests:readonly string[];readonly provider_identity:"twilio";readonly sender_identity_reference:string;readonly region:string;readonly retention:KnowledgeRetentionV1;readonly policy_version:string;readonly correlation_id:string;readonly causal_references:readonly string[];}
export interface GovernedTwilioConfigurationV1{readonly account_credential_reference:string;readonly sms_sender:Readonly<{identity_reference:string;address:string}>;readonly whatsapp_sender:Readonly<{identity_reference:string;address:string}>;readonly provider_endpoint:string;readonly timeout_ms:number;readonly response_size_limit:number;}
export interface GovernedTwilioCredentialsV1{readonly account_sid:string;readonly auth_token:string;}
export interface GovernedTwilioCredentialResolverV1{resolve(reference:string):Promise<GovernedTwilioCredentialsV1|null>;}
export interface GovernedTwilioDestinationResolverV1{resolve(recipientId:string,entitlementReference:string,channel:GovernedTwilioChannelV1):Promise<GovernedTwilioDestinationV1|null>;}
export interface GovernedTwilioLineageRepositoryV1{resolve(eligibility:OutboundDisclosureDispatchEligibilityV1):Promise<GovernedTwilioLineageV1|null>;}
export interface GovernedTwilioTransportResultV1{readonly provider_message_reference:string;}
export interface GovernedTwilioTransportV1{readonly binding:GovernedTwilioProviderBindingV1;send(input:Readonly<{channel:GovernedTwilioChannelV1;product:GovernedTwilioProductV1;destination:string;message:string;sender_identity_reference:string}>):Promise<GovernedTwilioTransportResultV1>;}
export interface GovernedTwilioEvidenceV1{readonly version:1;readonly evidence_id:string;readonly disclosure_id:string;readonly decision_id:string;readonly binding_id:string;readonly disclosure_consumption_id:string;readonly sealed_message_id:string;readonly projection_digest:string;readonly message_digest:string;readonly recipient_entitlement_reference:string;readonly destination_digest:string;readonly channel:GovernedTwilioChannelV1;readonly product:GovernedTwilioProductV1;readonly provider_identity:string;readonly sender_identity_reference:string;readonly purpose:string;readonly tenant_id:string;readonly company_id:string;readonly dispatched_at:string;readonly status:"SUCCEEDED"|"FAILED"|"INDETERMINATE";readonly failure_code?:GovernedTwilioFailureCode;readonly provider_message_reference_digest?:string;readonly correlation_id:string;readonly causal_references:readonly string[];}
export interface GovernedTwilioEvidenceRepositoryV1{reserve(consumptionId:string,sealedId:string,channel:GovernedTwilioChannelV1,product:GovernedTwilioProductV1,at:string):Promise<boolean>;append(evidence:GovernedTwilioEvidenceV1):Promise<void>;}
export interface GovernedTwilioDeliveryResultV1{readonly version:1;readonly status:"SUCCEEDED";readonly evidence:GovernedTwilioEvidenceV1;readonly content_returned:false;}
