import { createHash,randomUUID } from "node:crypto";
import { deepCopyAndFreeze } from "../../knowledge-exposure/knowledge.projection.guard.v1";
import type { KnowledgeProjectionManifestV1 } from "../../knowledge-exposure/knowledge.exposure.contracts.v1";
import type { OutboundDisclosureDispatchEligibilityV1 } from "../outbound.disclosure.contracts.v1";
import { sealGovernedTwilioMessageV1,verifySealedGovernedTwilioMessageV1 } from "./governed.twilio.seal.v1";
import { GovernedTwilioError,type GovernedTwilioDeliveryResultV1,type GovernedTwilioDestinationResolverV1,type GovernedTwilioEvidenceRepositoryV1,type GovernedTwilioEvidenceV1,type GovernedTwilioFailureCode,type GovernedTwilioLineageRepositoryV1,type GovernedTwilioTransportV1 } from "./governed.twilio.contracts.v1";
const hash=(s:string)=>createHash("sha256").update(s,"utf8").digest("hex");
export class GovernedTwilioDeliveryV1{constructor(private readonly d:Readonly<{lineage:GovernedTwilioLineageRepositoryV1;destination:GovernedTwilioDestinationResolverV1;transport:GovernedTwilioTransportV1;evidence:GovernedTwilioEvidenceRepositoryV1;now:()=>string}>){ }
 async deliver(input:{readonly eligibility:OutboundDisclosureDispatchEligibilityV1;readonly manifest:KnowledgeProjectionManifestV1;readonly projection:Readonly<Record<string,unknown>>;}):Promise<GovernedTwilioDeliveryResultV1>{const e=input?.eligibility;if(!e)throw new GovernedTwilioError("GOVERNED_TWILIO_ELIGIBILITY_REQUIRED");if(e.channel!=="SMS"&&e.channel!=="WHATSAPP")throw new GovernedTwilioError("GOVERNED_TWILIO_CHANNEL_MISMATCH");const lineage=await this.d.lineage.resolve(e);if(!lineage)throw new GovernedTwilioError("GOVERNED_TWILIO_ELIGIBILITY_INVALID");const destination=await this.d.destination.resolve(e.recipient.recipient_id,e.recipient.entitlement_reference,e.channel);if(!destination)throw new GovernedTwilioError("GOVERNED_TWILIO_RECIPIENT_INVALID");const sealed=sealGovernedTwilioMessageV1({...input,lineage,destination,provider:this.d.transport.binding});const at=this.d.now();verifySealedGovernedTwilioMessageV1(sealed,at);if(!await this.d.evidence.reserve(e.disclosure_consumption_id,sealed.sealed_message_id,sealed.channel,sealed.product,at))throw new GovernedTwilioError("GOVERNED_TWILIO_ALREADY_DISPATCHED");try{const result=await this.d.transport.send({channel:sealed.channel,product:sealed.product,destination:destination.address,message:sealed.canonical_message,sender_identity_reference:sealed.sender_identity_reference}),evidence=this.record(sealed,at,"SUCCEEDED",undefined,hash(result.provider_message_reference));await this.d.evidence.append(evidence);return deepCopyAndFreeze({version:1,status:"SUCCEEDED",evidence,content_returned:false}) as GovernedTwilioDeliveryResultV1;}catch(error){const code=error instanceof GovernedTwilioError?error.code:"GOVERNED_TWILIO_PROVIDER_FAILURE",status=code==="GOVERNED_TWILIO_TIMEOUT"?"INDETERMINATE":"FAILED",evidence=this.record(sealed,at,status,code);try{await this.d.evidence.append(evidence);}catch{throw new GovernedTwilioError("GOVERNED_TWILIO_EVIDENCE_FAILED");}throw new GovernedTwilioError(code);}}
 private record(s:ReturnType<typeof sealGovernedTwilioMessageV1>,at:string,status:"SUCCEEDED"|"FAILED"|"INDETERMINATE",failure?:GovernedTwilioFailureCode,reference?:string):GovernedTwilioEvidenceV1{const e=s.eligibility;return deepCopyAndFreeze({version:1,evidence_id:`governed-twilio-evidence:${randomUUID()}`,disclosure_id:e.disclosure_id,decision_id:e.decision_id,binding_id:e.binding_id,disclosure_consumption_id:e.disclosure_consumption_id,sealed_message_id:s.sealed_message_id,projection_digest:s.projection_digest,message_digest:s.message_digest,recipient_entitlement_reference:s.recipient_entitlement_reference,destination_digest:s.destination_digest,channel:s.channel,product:s.product,provider_identity:s.provider_identity,sender_identity_reference:s.sender_identity_reference,purpose:s.purpose,tenant_id:s.tenant_id,company_id:s.company_id,dispatched_at:at,status,...(failure?{failure_code:failure}:{}),...(reference?{provider_message_reference_digest:reference}:{}),correlation_id:s.correlation_id,causal_references:s.causal_references}) as GovernedTwilioEvidenceV1;}}
