import assert from"node:assert/strict";import crypto from"node:crypto";import fs from"node:fs";import path from"node:path";import test from"node:test";import{classifyBoundaryCase,evaluateMateriality,roleFidelityGate}from"./hard.boundary.materiality.policy.v1.mjs";
const here=path.dirname(new URL(import.meta.url).pathname.replace(/^\/(.:)/,"$1")),policy=JSON.parse(fs.readFileSync(path.join(here,"hard.boundary.materiality.policy.v1.json"),"utf8")),design=JSON.parse(fs.readFileSync(path.join(here,"v05.targeted.remediation.design.json"),"utf8"));
test("constitutional violations and role typo correction always fail",()=>{assert.equal(evaluateMateriality([{name:"x",cases:[{constitutional_violation:true,expected:"PRODUCT_QUESTION",predicted:"PRODUCT_QUESTION"}]}]).status,"FAIL");assert.equal(roleFidelityGate([{diagnostic:"ROLE_SURFACE_CHANGED"}]),false)});
test("historical oracle conflict is not a model role failure",()=>assert.equal(roleFidelityGate([{diagnostic:"EVALUATION_ORACLE_CONFLICT"},{diagnostic:"ROLE_SURFACE_EXACT"}]),true));
test("boundary severity and materiality are deterministic",()=>{const suites=[{name:"gold",cases:[{expected:"DATA_INTRODUCTION",predicted:"EXECUTION_REQUEST"}]},{name:"ood",cases:[{expected:"DATA_INTRODUCTION",predicted:"EXECUTION_REQUEST"}]},{name:"validation",cases:[{expected:"EXECUTION_REQUEST",predicted:"CONVERSATIONAL_CONTINUITY"}]}],a=evaluateMateriality(suites),b=evaluateMateriality(suites);assert.deepEqual(a,b);assert.equal(a.status,"FAIL");assert.equal(classifyBoundaryCase({expected:"EXECUTION_REQUEST",predicted:"CONVERSATIONAL_CONTINUITY"}),"LEVEL_2_CRITICAL");assert.equal(classifyBoundaryCase({expected:"PRODUCT_QUESTION",predicted:"PRODUCT_QUESTION"}),"LEVEL_3_NON_HARD_SEMANTIC")});
test("frozen policy preserves decisions and residual visibility",()=>{assert.equal(policy.retrospective["v0.4"].raw_metrics_unchanged,true);assert.equal(policy.retrospective["v0.2"].status,"NOT_ASSERTABLE");assert.equal(policy.retrospective["v0.3"].status,"FAIL");assert.equal(policy.retrospective["v0.4"].status,"FAIL");assert.equal(design.decision_100k,"100K_NOT_JUSTIFIED");assert.equal(design.model_size_decision,"QWEN_0_6B_CAPACITY_NOT_YET_LIMITING");assert.deepEqual(design.targeted_delta.categories.find(x=>x.category==="PRODUCT_FOCUS_TARGETED").balanced_focus_counts,{TIER:80,DOMAIN:80,LIMITATION:80})});
const auditFile=path.resolve(here,"../../../training-artifacts/gcc4q/v04.qualification.audit.json");
test("GCC-4Q raw evidence is read-only and v0.2/v0.4 metrics remain unchanged",()=>{const before=fs.readFileSync(auditFile),hash=crypto.createHash("sha256").update(before).digest("hex"),audit=JSON.parse(before);assert.equal(audit.raw_metrics_preserved["v04.historical.adversarial"].hard_boundary_recall,0.8);assert.equal(audit.version_comparison.v02.metrics.historical.adversarial.hard_boundary_recall,0.9333333333333333);assert.equal(audit.product_focus_audit.ood_v1.by_class.TIER,0);assert.equal(audit.product_focus_audit.ood_v1.by_class.DOMAIN,0);assert.equal(audit.product_focus_audit.ood_v1.by_class.LIMITATION,0);assert.equal(crypto.createHash("sha256").update(fs.readFileSync(auditFile)).digest("hex"),hash)});
test("actual preserved v0.4 boundary evidence fails the frozen materiality gate",()=>{const audit=JSON.parse(fs.readFileSync(auditFile,"utf8")),suites=Object.entries(audit.hard_boundary_audit).map(([name,value])=>({name,cases:value.misses.map(x=>({expected:x.expected,predicted:x.predicted}))})),result=evaluateMateriality(suites);assert.equal(result.status,"FAIL");assert.equal(result.counts.level_1,0);assert.equal(result.counts.level_2_critical,1);assert.ok(result.repeated_major_transition_families.includes("DATA_INTRODUCTION_TO_EXECUTION_REQUEST"))});
