import type { CognitiveTransportEvidenceRepositoryV1, SealedCognitiveExposureV1 } from "../governance/knowledge-exposure/transport";
import { CognitiveTransportError, CognitiveTransportMediatorV1 } from "../governance/knowledge-exposure/transport";
export type LlmProvider="openai"|"anthropic";
export interface LlmCall{readonly callId:string;readonly provider:LlmProvider;readonly model:string;readonly sealed_exposure:SealedCognitiveExposureV1;readonly temperature?:number;readonly maxTokens?:number;}
export type LlmUsage={readonly inputTokens?:number;readonly outputTokens?:number};
export type LlmResult={readonly ok:true;readonly callId:string;readonly provider:LlmProvider;readonly model:string;readonly text:string;readonly responseDigest:string;readonly usage?:LlmUsage;readonly latencyMs:number;readonly advisoryOnly:true}|{readonly ok:false;readonly callId:string;readonly provider:LlmProvider;readonly model:string;readonly error:string;readonly latencyMs:number};
export interface SandboxEnv{readonly OPENAI_API_KEY?:string;readonly ANTHROPIC_API_KEY?:string;readonly cognitiveTransportEvidence?:CognitiveTransportEvidenceRepositoryV1;readonly cognitiveFetch?:typeof fetch;readonly cognitiveNow?:()=>string;}
export async function callOneLLM(env:SandboxEnv,call:LlmCall):Promise<LlmResult>{const started=Date.now();if(!call?.sealed_exposure)return fail(call,"COGNITIVE_EXPOSURE_REQUIRED",started);const key=call.provider==="openai"?env.OPENAI_API_KEY:env.ANTHROPIC_API_KEY;if(!key||!env.cognitiveTransportEvidence)return fail(call,"COGNITIVE_EXPOSURE_REQUIRED",started);try{const out=await new CognitiveTransportMediatorV1({fetch:env.cognitiveFetch??fetch,evidence:env.cognitiveTransportEvidence,now:env.cognitiveNow??(()=>new Date().toISOString())}).dispatch({sealed:call.sealed_exposure,provider:call.provider,model:call.model,api_key:key,max_tokens:call.maxTokens,temperature:call.temperature});return{ok:true,callId:call.callId,provider:call.provider,model:call.model,text:out.text,responseDigest:out.response_digest,usage:out.usage?{inputTokens:out.usage.input_tokens,outputTokens:out.usage.output_tokens}:undefined,latencyMs:Date.now()-started,advisoryOnly:true};}catch(e){return fail(call,e instanceof CognitiveTransportError?e.code:"COGNITIVE_PROVIDER_FAILURE",started);}}
export async function callManyLLMs(env:SandboxEnv,calls:readonly LlmCall[]):Promise<LlmResult[]>{return Promise.all(calls.map(c=>callOneLLM(env,c)));}
function fail(call:Pick<LlmCall,"callId"|"provider"|"model">|undefined,error:string,started:number):LlmResult{return{ok:false,callId:call?.callId??"UNKNOWN",provider:call?.provider??"openai",model:call?.model??"UNKNOWN",error,latencyMs:Date.now()-started};}
