import{describe,expect,it}from"vitest";import{bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1}from"../../cockpit/operational.signal.evaluation.scope.v1";import{bindGovernedObservedOperationalOutcomeV1,createGovernedInterventionContextV1}from"../../experience/observedOutcome";import{composeCanonicalOperationalRealityV1,type CanonicalOperationalRealityEvidenceV1}from"../../reality/canonical.operational.reality.composition.v1";import{createGovernedOperationalExperienceV1,createGovernedPriorExpectationV1,learnFromGovernedOperationalExperienceV1,verifyGovernedExperienceLearningResultV1,verifyGovernedOperationalExperienceV1,verifyGovernedPriorExpectationV1}from"../governedLearning";
const bAt="2026-08-17T10:00:00.000Z",iAt="2026-08-17T11:00:00.000Z",aAt="2026-08-17T12:00:00.000Z",hex=(x:string)=>x.repeat(64).slice(0,64);
async function reality(at:string,n:number){const scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"REQUEST_DATASET",request_id:"request:1",company_id:"company:1",domain:"operations",evidence_selection_ref:"selection:current",source_snapshot_ref:"snapshot:current"}),binding=await bindOperationalSignalsToScopeV1({scope,request_id:"request:1",company_id:"company:1",evidence_as_of:at,evaluated_at:at}),e:CanonicalOperationalRealityEvidenceV1={version:1,tenant_id:"tenant:1",company_id:"company:1",request_id:"request:1",scope_id:scope.scope_id,scope_digest:scope.scope_digest,evidence_as_of:at,evidence_ref:`evidence:${n}`,evidence_digest:hex(String(n)),source_identity_ref:"source:1",source_namespace:"neutral",semantic_key:"order:1",claim_digest:hex(String(n+2)),evidence_role:"CURRENT_FACT",canonical_subject_refs:["order:1"],canonical_location_refs:[],qualification_refs:[`qualification:${n}`],provenance_refs:[`provenance:${n}`],causal_lineage_refs:[`lineage:${n}`]};return composeCanonicalOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:binding,evidence:[e],coverage:[]})}
async function operands(expected:"DIFFERENCE"|"NO_MATERIAL_CHANGE"|"UNSPECIFIED"="DIFFERENCE",observed:"DIFFERENCE_ESTABLISHED"|"MATERIAL_EQUIVALENCE_ESTABLISHED"|"NOT_EVALUATED"="DIFFERENCE_ESTABLISHED",correction?:"CORRECTED"|"SUPERSEDED"){const before=await reality(bAt,1),after=await reality(aAt,2),intervention=await createGovernedInterventionContextV1({version:1,tenant_id:"tenant:1",company_id:before.company_id,request_id:before.request_id,scope_id:before.scope_id,scope_digest:before.scope_digest,context_kind:"INTERVENTION",artifact_ref:"intervention:1",artifact_digest:hex("a"),occurred_at:iAt,execution_status:"NOT_APPLICABLE",qualification_refs:["qualification:intervention"],provenance_refs:["provenance:intervention"],causal_lineage_refs:["lineage:intervention"]}),comparison=observed==="NOT_EVALUATED"?undefined:{status:observed,ref:"comparison:1",digest:hex("c"),qualification_refs:["qualification:comparison"],provenance_refs:["provenance:comparison"],causal_lineage_refs:["lineage:comparison"]},correctionBinding=correction?{status:correction,ref:"correction:1",digest:hex(correction==="CORRECTED"?"d":"e"),qualification_refs:["qualification:correction"],provenance_refs:["provenance:correction"],causal_lineage_refs:["lineage:correction"]}:undefined,outcome=await bindGovernedObservedOperationalOutcomeV1({version:1,before,intervention,after,...(comparison?{comparison}:{}),...(correctionBinding?{correction:correctionBinding}:{})}),none=expected==="UNSPECIFIED",expectation=await createGovernedPriorExpectationV1({version:1,expectation_kind:none?"NO_DIRECTIONAL_EXPECTATION":"GOVERNED_CAUSAL_EVALUATION",tenant_id:outcome.tenant_id,company_id:outcome.company_id,request_id:outcome.request_id,scope_id:outcome.scope_id,scope_digest:outcome.scope_digest,before_reality_ref:outcome.before_reality_ref,before_reality_digest:outcome.before_reality_digest,...(none?{}:{expectation_ref:"causal-result:1",expectation_digest:hex("f")}),expected_relation:expected,qualification_refs:["qualification:expectation"],provenance_refs:["provenance:expectation"],causal_lineage_refs:["lineage:expectation"]}),experience=await createGovernedOperationalExperienceV1({version:1,expectation,outcome}),learning=await learnFromGovernedOperationalExperienceV1({version:1,experience,expectation,outcome});return{before,after,intervention,outcome,expectation,experience,learning}}
describe("GOVERNED-EXPERIENCE-LEARNING-CANONICAL-COMPLETION-WU1-RESUME",()=>{
 it("consumes a verified governed observed outcome",async()=>expect((await operands()).experience.observed_outcome_ref).toBe((await operands()).outcome.outcome_id));
 it("creates and verifies a canonical prior expectation",async()=>await expect(verifyGovernedPriorExpectationV1((await operands()).expectation)).resolves.toBeUndefined());
 it("creates and verifies governed experience",async()=>await expect(verifyGovernedOperationalExperienceV1((await operands()).experience)).resolves.toBeUndefined());
 it("creates and verifies canonical guidance",async()=>await expect(verifyGovernedExperienceLearningResultV1((await operands()).learning)).resolves.toBeUndefined());
 it("confirms an expected difference",async()=>expect((await operands("DIFFERENCE","DIFFERENCE_ESTABLISHED")).learning.learning_status).toBe("CONFIRMED_BY_OBSERVATION"));
 it("confirms expected no material change",async()=>expect((await operands("NO_MATERIAL_CHANGE","MATERIAL_EQUIVALENCE_ESTABLISHED")).learning.learning_status).toBe("NO_MATERIAL_CHANGE_OBSERVED"));
 it.each([["DIFFERENCE","MATERIAL_EQUIVALENCE_ESTABLISHED"],["NO_MATERIAL_CHANGE","DIFFERENCE_ESTABLISHED"]]as const)("preserves contradiction %s vs %s",async(e,o)=>expect((await operands(e,o)).learning.learning_status).toBe("CONTRADICTED_BY_OBSERVATION"));
 it("preserves unresolved comparison",async()=>expect((await operands("DIFFERENCE","NOT_EVALUATED")).learning.learning_status).toBe("UNRESOLVED"));
 it("preserves insufficient evidence without a directional expectation",async()=>expect((await operands("UNSPECIFIED","DIFFERENCE_ESTABLISHED")).learning.learning_status).toBe("INSUFFICIENT_EVIDENCE"));
 it("binds exact before, intervention and after identities",async()=>{const x=await operands();expect(x.experience).toMatchObject({before_reality_ref:x.outcome.before_reality_ref,intervention_context_ref:x.outcome.intervention_context_ref,after_reality_ref:x.outcome.after_reality_ref})});
 it("rejects forged observed outcome",async()=>{const x=await operands();await expect(createGovernedOperationalExperienceV1({version:1,expectation:x.expectation,outcome:{...x.outcome,outcome_digest:hex("0")}})).rejects.toThrow()});
 it("rejects forged expectation",async()=>{const x=await operands();await expect(createGovernedOperationalExperienceV1({version:1,expectation:{...x.expectation,expected_relation:"NO_MATERIAL_CHANGE"},outcome:x.outcome}as never)).rejects.toThrow()});
 it("rejects mismatched experience operands",async()=>{const x=await operands(),y=await operands("NO_MATERIAL_CHANGE","MATERIAL_EQUIVALENCE_ESTABLISHED");await expect(learnFromGovernedOperationalExperienceV1({version:1,experience:x.experience,expectation:y.expectation,outcome:x.outcome})).rejects.toThrow("GOVERNED_LEARNING_OPERAND_MISMATCH")});
 it("rejects cross-company expectation",async()=>{const x=await operands(),e=await createGovernedPriorExpectationV1({...x.expectation,company_id:"company:2"});await expect(createGovernedOperationalExperienceV1({version:1,expectation:e,outcome:x.outcome})).rejects.toThrow("GOVERNED_EXPERIENCE_CONTEXT_MISMATCH")});
 it("rejects cross-tenant expectation",async()=>{const x=await operands(),e=await createGovernedPriorExpectationV1({...x.expectation,tenant_id:"tenant:2"});await expect(createGovernedOperationalExperienceV1({version:1,expectation:e,outcome:x.outcome})).rejects.toThrow("GOVERNED_EXPERIENCE_CONTEXT_MISMATCH")});
 it("a corrected outcome produces distinct learning identity",async()=>{const a=await operands(),b=await operands("DIFFERENCE","DIFFERENCE_ESTABLISHED","CORRECTED");expect(a.learning.learning_id).not.toBe(b.learning.learning_id);expect(b.learning.guidance_active).toBe(true)});
 it("a superseded outcome disables old guidance",async()=>{const x=await operands("DIFFERENCE","DIFFERENCE_ESTABLISHED","SUPERSEDED");expect(x.learning).toMatchObject({learning_status:"SUPERSEDED_OUTCOME",guidance_active:false})});
 it.each(["simulation","optimizer","counterfactual","learned_expectation","llm_claim"])("rejects %s as canonical learning input",async key=>{const x=await operands();await expect(learnFromGovernedOperationalExperienceV1({version:1,experience:x.experience,expectation:x.expectation,outcome:x.outcome,[key]:"artifact:1"}as never)).rejects.toThrow("GOVERNED_LEARNING_UNSAFE_INPUT")});
 it("retains qualification, provenance and lineage",async()=>{const x=await operands();expect(x.learning.qualification_refs).toEqual(expect.arrayContaining(["qualification:expectation","qualification:1","qualification:2"]));expect(x.learning.provenance_refs).toEqual(expect.arrayContaining(["provenance:expectation","provenance:1","provenance:2"]));expect(x.learning.causal_lineage_refs).toContain(x.experience.experience_id)});
 it("is deterministic and recursively immutable",async()=>{const a=await operands(),b=await operands();expect(a.learning).toEqual(b.learning);expect(Object.isFrozen(a.learning)).toBe(true);expect(Object.isFrozen(a.learning.causal_lineage_refs)).toBe(true)});
 it("does not mutate current reality or observed outcome",async()=>{const x=await operands();expect(x.learning).toMatchObject({current_fact:false,rewrites_operational_reality:false});expect(x.outcome.observed_outcome).toBe(true);expect(Object.isFrozen(x.outcome)).toBe(true)});
 it("does not claim causal attribution",async()=>expect((await operands()).learning.causal_attribution_established).toBe(false));
 it.each(["VISION","GRADUATE","JUNIOR","SENIOR","PRINCIPAL","CHARTER"])("is tier-independent for %s",async()=>{const x=await operands();expect(x.learning.tier_independent).toBe(true);expect(x.learning).not.toHaveProperty("tier")});
 it("is guidance only and grants no recommendation, authority or execution",async()=>expect((await operands()).learning).toMatchObject({guidance_semantics:"GUIDANCE_ONLY",recommended:false,executable:false,grants_authority:false,grants_execution:false}));
 it("is independent of Pressure, Attention, commercial plan and credits",async()=>{const v=(await operands()).learning;for(const key of["pressure","attention","commercial_plan","credit_balance","economic_capacity"])expect(v).not.toHaveProperty(key)});
 it("rejects forged learning digest",async()=>{const v=(await operands()).learning;await expect(verifyGovernedExperienceLearningResultV1({...v,learning_digest:hex("0")})).rejects.toThrow("GOVERNED_LEARNING_INTEGRITY_INVALID")});
});
