import {describe,expect,it} from "vitest";
import {bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1} from "../../cockpit/operational.signal.evaluation.scope.v1";
import {createGovernedInterventionDiscoveryV1} from "../../decision/governed.intervention.discovery.policy.v1";
import {createOperationsDomainContextBindingV1,createOperationsDomainInterventionProfileV1} from "../../industrial/cognition/operations.domain.intervention.profile.v1";
import {createCanonicalDomainContextBindingV1,verifyCanonicalDomainContextBindingV1} from "../canonical.domain.context.v1";
import {createCanonicalDomainInterventionProfileV1} from "../canonical.domain.intervention.profile.v1";
import {createOperationalDomainEvidenceProfileV1,createOperationsEvidenceProfileV1} from "../canonical.operational.roles.v1";
import {createProtectedOperationalObjectiveBindingV1} from "../protected.operational.objective.v1";

async function context(){return createOperationsDomainContextBindingV1();}
async function domain(name:string){const evidence=await createOperationalDomainEvidenceProfileV1({version:1,profile_ref:`profile:${name}-v1`,domain_ref:`domain:${name}`,profile_version:"1",supported_subject_kinds:["DOMAIN_OBJECT"],evidence_mappings:[],relationship_family_ref:`relationship-family:${name}`}),intervention=await createCanonicalDomainInterventionProfileV1({version:1,binding_profile_ref:`intervention-profile:${name}-v1`,binding_profile_version:"1",evidence_profile:evidence,policy_ref:`policy:${name}`,dimension_primitives:[{dimension_key:"DOMAIN_DIMENSION"}],intervention_primitives:[{primitive_key:"DOMAIN_CHANGE",admitted_intervention_class_ref:`${name}-class:admitted`,admitted_intervention_class_digest:"a".repeat(64),knowledge_hypothesis_refs:[],experience_hypothesis_refs:[]}],constraint_family_keys:["DOMAIN_CONSTRAINT"],evaluator_family_keys:["DOMAIN_EVALUATOR"],dimension_intervention_bindings:[{dimension_key:"DOMAIN_DIMENSION",primitive_key:"DOMAIN_CHANGE"}],intervention_constraint_bindings:[{primitive_key:"DOMAIN_CHANGE",constraint_family_key:"DOMAIN_CONSTRAINT"}],intervention_evaluator_bindings:[{dimension_key:"DOMAIN_DIMENSION",primitive_key:"DOMAIN_CHANGE",evaluator_family_key:"DOMAIN_EVALUATOR"}],qualification_refs:[`qualification:${name}`]});return{evidence,intervention};}

describe("OPERATIONS-DOMAIN-PROFILE-IDENTITY-ALIGNMENT-WU1",()=>{
 it("creates deterministic recursively immutable Operations domain context",async()=>{const a=await context(),b=await context();expect(a.domain_context_id).toBe(b.domain_context_id);expect(Object.isFrozen(a)&&Object.isFrozen(a.qualification_refs)).toBe(true);await expect(verifyCanonicalDomainContextBindingV1(a)).resolves.toBeUndefined();});
 it("preserves distinct domain, semantic, evidence and intervention identities",async()=>{const x=await context(),e=await createOperationsEvidenceProfileV1(),i=await createOperationsDomainInterventionProfileV1();expect(x).toMatchObject({domain_ref:"domain:operations",domain_semantic_profile_ref:"domain-profile:operations",evidence_profile_ref:e.profile_ref,evidence_profile_id:e.profile_id,intervention_profile_ref:i.binding_profile_ref,intervention_profile_id:i.binding_profile_id});expect(new Set([x.domain_semantic_profile_ref,x.evidence_profile_ref,x.intervention_profile_ref]).size).toBe(3);});
 it("rejects forged identity, version, digest and cross-domain profile composition",async()=>{const x=await context();await expect(verifyCanonicalDomainContextBindingV1({...x,domain_context_digest:"0".repeat(64)})).rejects.toThrow("DOMAIN_CONTEXT_INTEGRITY_INVALID");const ops=await createOperationsEvidenceProfileV1(),pm=await domain("project-management");await expect(createCanonicalDomainContextBindingV1({version:1,domain_ref:"domain:operations",domain_semantic_profile_ref:"domain-profile:operations",domain_semantic_profile_version:"1",evidence_profile:ops,intervention_profile:pm.intervention,policy_ref:"policy:test",qualification_refs:["qualification:test"]})).rejects.toThrow("DOMAIN_CONTEXT_DOMAIN_MISMATCH");await expect(createCanonicalDomainContextBindingV1({version:1,domain_ref:"domain:project-management",domain_semantic_profile_ref:"domain-profile:project-management",domain_semantic_profile_version:"1",evidence_profile:pm.evidence,intervention_profile:{...pm.intervention,domain_profile_version:"2"},policy_ref:"policy:test",qualification_refs:["qualification:test"]})).rejects.toThrow();});
 it.each(["project-management","maintenance","finance"])("supports independent %s context through identical universal semantics",async name=>{const d=await domain(name),x=await createCanonicalDomainContextBindingV1({version:1,domain_ref:`domain:${name}`,domain_semantic_profile_ref:`domain-profile:${name}`,domain_semantic_profile_version:"1",evidence_profile:d.evidence,intervention_profile:d.intervention,policy_ref:`policy:${name}-context`,qualification_refs:[`qualification:${name}-context`]});expect(x.domain_ref).toBe(`domain:${name}`);});
 it("changes context identity when either artifact version changes",async()=>{const a=await context(),d=await domain("version-proof"),v1=await createCanonicalDomainContextBindingV1({version:1,domain_ref:"domain:version-proof",domain_semantic_profile_ref:"domain-profile:version-proof",domain_semantic_profile_version:"1",evidence_profile:d.evidence,intervention_profile:d.intervention,policy_ref:"policy:version-proof",qualification_refs:["qualification:proof"]}),v2=await createCanonicalDomainContextBindingV1({version:1,domain_ref:"domain:version-proof",domain_semantic_profile_ref:"domain-profile:version-proof",domain_semantic_profile_version:"2",evidence_profile:d.evidence,intervention_profile:d.intervention,policy_ref:"policy:version-proof",qualification_refs:["qualification:proof"]});expect(v1.domain_context_id).not.toBe(v2.domain_context_id);expect(a.domain_context_id).not.toBe(v1.domain_context_id);});
 it("allows discovery to validate distinct artifacts through one canonical domain context",async()=>{const c=await context(),scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"REQUEST_DATASET",request_id:"request:1",company_id:"company:1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1"}),evaluation_scope=await bindOperationalSignalsToScopeV1({scope,request_id:"request:1",company_id:"company:1",evidence_as_of:"2026-08-15T10:00:00Z",evaluated_at:"2026-08-15T10:01:00Z"}),objective=await createProtectedOperationalObjectiveBindingV1({version:1,request_id:"request:1",company_id:"company:1",evaluation_scope,domain_profile_ref:"domain-profile:operations",domain_profile_version:"1",objective_kind_ref:"objective-kind:delivery",objective_ref:"objective:1",governing_expected_state_refs:[],governing_plan_element_refs:["plan:1"],protected_subject_refs:["subject:1"],commitment_criteria_refs:["criterion:1"],objective_selection_ref:"selection:objective",source_evidence_refs:["evidence:1"],provenance_refs:["provenance:1"],qualification_refs:["qualification:1"],causal_lineage_refs:["lineage:1"],plan_lineage_refs:["lineage:plan"],effective_at:"2026-08-15T09:00:00Z",evidence_as_of:evaluation_scope.evidence_as_of,evaluated_at:evaluation_scope.evaluated_at});const input={version:1 as const,request_id:"request:1",company_id:"company:1",evaluation_scope,domain_context:c,domain_profile_ref:"domain-profile:operations",domain_profile_version:"1",current_state_ref:"state:1",dimension_ref:"dimension:allocation",changeability_status:"UNRESOLVED" as const,changeability_evidence_refs:["evidence:1"],principle_hypothesis_ref:"hypothesis:1",principle_origin_ref:"profile:operations-v1",admission_status:"UNRESOLVED" as const,admission_evidence_refs:["evidence:admission"],admissibility_status:"UNRESOLVED" as const,constraint_refs:["constraint:1"],admissibility_evidence_refs:["evidence:constraint"],baseline_ref:"baseline:1",perturbation_ref:"perturbation:1",evaluator_ref:"evaluator:1",causal_test_result_ref:"causal-result:1",material_effect_status:"UNRESOLVED" as const,material_effect_evidence_refs:["evidence:effect"],protected_objective:objective,governing_condition_ref:"condition:1",trajectory_ref:"trajectory:1",determination_basis_refs:["basis:1"],qualification_refs:["qualification:1"],provenance_refs:["provenance:1"],causal_lineage_refs:["lineage:1"],epistemic_basis:"DETERMINISTIC" as const,evidence_as_of:evaluation_scope.evidence_as_of,evaluated_at:evaluation_scope.evaluated_at};expect(await createGovernedInterventionDiscoveryV1(input)).toMatchObject({domain_context_ref:c.domain_context_id,domain_profile_ref:"domain-profile:operations"});await expect(createGovernedInterventionDiscoveryV1({...input,domain_profile_ref:"domain-profile:finance"})).rejects.toThrow();await expect(createGovernedInterventionDiscoveryV1({...input,domain_context:{...c,domain_ref:"domain:finance"}})).rejects.toThrow();});
 it("contains no current facts, source, tier, recommendation, authority or execution",async()=>{const x=await context(),json=JSON.stringify(x);expect(x).toMatchObject({declarative_only:true,establishes_current_truth:false,recommended:false,grants_authority:false,grants_execution:false});expect(json).not.toMatch(/company|tenant|order|sku|supplier|inventory|SAP|ERP|MES|email|chat|API|VISION|GRADUATE|JUNIOR|SENIOR|PRINCIPAL|CHARTER|approval|delegation|credential/i);});
});
