import { describe, expect, it } from "vitest";
import { createOperationalSignalEvaluationScopeV1 } from "../../cockpit/operational.signal.evaluation.scope.v1";
import { buildOperationalCockpitSnapshotV1 } from "../../cockpit/operational.cockpit.snapshot.v1";
import * as roles from "../canonical.operational.roles.v1";

async function profile(){return roles.createOperationsEvidenceProfileV1();}
async function subject(kind="SKU",subject_ref="sku:1"){return roles.createOperationalSubjectRefV1({version:1,tenant_id:"tenant:1",company_id:"company:1",profile:await profile(),subject_kind:kind,subject_ref});}
async function base(){return{version:1 as const,subject:await subject(),scope_ref:"scope:1",evidence_refs:["evidence:1"],provenance_refs:["provenance:1"],causal_lineage_refs:["lineage:1"]};}

describe("CROSS-DOMAIN-OPERATIONAL-ROLES-WU1",()=>{
  it("creates deterministic immutable subject identity",async()=>{const a=await subject(),b=await subject();expect(a).toEqual(b);expect(a.subject_id).toMatch(/sha256:[0-9a-f]{64}$/);expect(Object.isFrozen(a)).toBe(true);});
  it.each(["SKU","ORDER","SUPPLIER"])("binds Operations %s without renaming",async kind=>{const value=await subject(kind,`${kind.toLowerCase()}:1`);expect(value.subject_kind).toBe(kind);expect(value.subject_ref).toBe(`${kind.toLowerCase()}:1`);});
  it("rejects arbitrary ungoverned subject kinds",async()=>{await expect(subject("MILESTONE","milestone:1")).rejects.toThrow("SUBJECT_KIND_NOT_GOVERNED_BY_PROFILE");});
  it("changes identity on subject substitution",async()=>{expect((await subject()).subject_digest).not.toBe((await subject("SKU","sku:2")).subject_digest);});
  it("changes identity on governed profile substitution",async()=>{const p=await roles.createOperationalDomainEvidenceProfileV1({version:1,profile_ref:"profile:alternate",domain_ref:"domain:operations",profile_version:"1",supported_subject_kinds:["SKU"],evidence_mappings:[],relationship_family_ref:"relationship-family:alternate"});const x=await roles.createOperationalSubjectRefV1({version:1,company_id:"company:1",profile:p,subject_kind:"SKU",subject_ref:"sku:1"});expect(x.subject_digest).not.toBe((await subject()).subject_digest);});
  it("plan element requires no order semantics",async()=>{const x=await roles.createOperationalPlanElementRefV1({...await base(),plan_element_ref:"plan-element:1"});expect(x.role).toBe("PLAN_ELEMENT");expect(x).not.toHaveProperty("order");});
  it("plan relationship requires no BOM semantics",async()=>{const x=await roles.createOperationalPlanRelationshipRefV1({...await base(),relationship_ref:"relationship:1",relationship_kind_ref:"relationship-kind:domain-owned",source_plan_element_ref:"plan-element:1",target_plan_element_ref:"plan-element:2"});expect(x).not.toHaveProperty("bom");expect(x.relationship_kind_ref).toBe("relationship-kind:domain-owned");});
  it("baseline remains domain neutral",async()=>{const x=await roles.createExpectedOperationalStateRefV1({...await base(),baseline_ref:"baseline:1"});expect(x.role).toBe("BASELINE");expect(JSON.stringify(x)).not.toMatch(/inventory|milestone|cash/i);});
  it("observation is source neutral and time bound",async()=>{const x=await roles.createOperationalObservationRefV1({...await base(),observation_ref:"observation:1",observed_at:"2026-08-13T10:00:00Z",effective_at:"2026-08-13T09:00:00Z",qualification_ref:"qualification:1"});expect(x.role).toBe("OBSERVATION");expect(JSON.stringify(x)).not.toMatch(/ERP|SAP|MES|EMAIL|CHAT/);});
  it("provenance changes identity but not observation role",async()=>{const input={...await base(),observation_ref:"observation:1",observed_at:"2026-08-13T10:00:00Z",effective_at:"2026-08-13T09:00:00Z",qualification_ref:"qualification:1"};const a=await roles.createOperationalObservationRefV1(input),b=await roles.createOperationalObservationRefV1({...input,provenance_refs:["provenance:2"]});expect(a.role).toBe(b.role);expect(a.role_digest).not.toBe(b.role_digest);});
  it("deviation is distinct from observation",async()=>{const x=await roles.createOperationalDeviationRefV1({...await base(),deviation_ref:"deviation:1",baseline_role_ref:"role:baseline",observation_role_ref:"role:observation"});expect(x.role).toBe("DEVIATION");});
  it("Operations consequence binds through domain-owned kind",async()=>{const x=await roles.createMaterialOperationalConsequenceRefV1({...await base(),consequence_ref:"consequence:1",consequence_kind_ref:"operations-consequence:PRODUCTION_INTERRUPTION",materiality_ref:"materiality:1"});expect(x.consequence_kind_ref).toContain("PRODUCTION_INTERRUPTION");expect(x.role).toBe("CONSEQUENCE");});
  it("corrective option grants no authority",async()=>{const x=await roles.createCorrectiveOperationalOptionRefV1({...await base(),corrective_option_ref:"option:1"});expect(x).toMatchObject({grants_execution:false,grants_authority:false,observational_only:true});});
  it.each(["REQUIREMENT_DEADLINE","FULFILLMENT_EXPECTATION","CONSEQUENCE_EVENT","MARGIN_EVIDENCE","OPTION_EVENT"] as const)("supports generic temporal role %s without supplier commitment",async temporal_role=>{const x=await roles.createGenericOperationalTemporalRefV1({...await base(),temporal_ref:`temporal:${temporal_role}`,temporal_role});expect(x).not.toHaveProperty("supplier_commitment");});
  it("creates deterministic domain profile mappings",async()=>{expect(await profile()).toEqual(await profile());expect((await profile()).declarative_only).toBe(true);});
  it("fails closed on unsupported evidence mapping",async()=>{const p=await profile();expect(()=>roles.resolveOperationalEvidenceRoleV1(p,"PAYROLL_DATA")).toThrow("EVIDENCE_ROLE_MAPPING_UNSUPPORTED");});
  it.each([["PLAN_ORDER","PLAN_ELEMENT"],["ORDER_RELATIONSHIP","PLAN_RELATIONSHIP"],["PLAN_BOM_EDGE","STRUCTURAL_RELATIONSHIP"],["MOVEMENT_EVENT","BEHAVIORAL_EVENT"],["INVENTORY_SNAPSHOT","OBSERVATION"]] as const)("maps Operations %s without renaming it",async(kind,role)=>{const m=roles.resolveOperationalEvidenceRoleV1(await profile(),kind);expect(m).toMatchObject({evidence_kind:kind,role});});
  it.each(["PLAN_STRUCTURE_QUALITY","CORRECTION_EFFECT"])("fails closed on ambiguous Operations mapping %s",async kind=>{const p=await profile();expect(()=>roles.resolveOperationalEvidenceRoleV1(p,kind)).toThrow("EVIDENCE_ROLE_MAPPING_UNSUPPORTED");});
  it("keeps Data Awareness modalities unchanged",async()=>{expect([...new Set((await profile()).evidence_mappings.map(x=>x.modality))].sort()).toEqual(["BEHAVIORAL","SNAPSHOT","STRUCTURAL"]);});
  it("retains legacy ENTITY compatibility",async()=>{for(const entity_type of ["SKU","ORDER","SUPPLIER"] as const)await expect(createOperationalSignalEvaluationScopeV1({version:1,scope_type:"ENTITY",request_id:"request:1",company_id:"company:1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1",entity:{entity_type,entity_ref:`${entity_type.toLowerCase()}:1`}})).resolves.toMatchObject({entity:{entity_type}});});
  it("binds future domain subjects without changing universal vocabularies",async()=>{const p=await roles.createOperationalDomainEvidenceProfileV1({version:1,profile_ref:"profile:future",domain_ref:"domain:future-planning",profile_version:"1",supported_subject_kinds:["DOMAIN_OBJECT"],evidence_mappings:[],relationship_family_ref:"relationship-family:future"});const s=await roles.createOperationalSubjectRefV1({version:1,company_id:"company:1",profile:p,subject_kind:"DOMAIN_OBJECT",subject_ref:"domain-object:1"});expect(s.subject_kind).toBe("DOMAIN_OBJECT");});
  it("binds governed subject into ENTITY scope",async()=>{const s=await subject();const scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"ENTITY",request_id:"request:1",company_id:"company:1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1",operational_subject:s});expect(scope.operational_subject?.subject_id).toBe(s.subject_id);});
  it("fails closed on scope subject company substitution",async()=>{await expect(createOperationalSignalEvaluationScopeV1({version:1,scope_type:"ENTITY",request_id:"request:1",company_id:"company:other",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1",operational_subject:await subject()})).rejects.toThrow("SCOPE_SUBJECT_BINDING_MISMATCH");});
  it.each(["REQUEST_DATASET","PATH"] as const)("retains %s boundary",async scope_type=>{const common={version:1 as const,scope_type,request_id:"request:1",company_id:"company:1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1"};const scope=await createOperationalSignalEvaluationScopeV1(scope_type==="PATH"?{...common,path:{subgraph_ref:"subgraph:1",seed_refs:["subject:1"]}}:common);expect(scope).toMatchObject({scope_type,company_global_claim:false,grants_execution:false});});
  it("creates machine-traceable causal chains",async()=>{const x=await roles.createOperationalCausalChainV1({version:1,scope_ref:"scope:1",ordered_role_refs:["role:baseline","role:observation","role:deviation","role:consequence"],evidence_refs:["evidence:1"]});expect(x.ordered_role_refs).toHaveLength(4);expect(x).not.toHaveProperty("explanation_text");});
  it("contains no raw content or authority capability",async()=>{const x=await roles.createOperationalPlanElementRefV1({...await base(),plan_element_ref:"plan-element:1"});expect(JSON.stringify(x)).not.toMatch(/raw_|prompt|credential|provider_response|email_text|chat_text/i);expect(x).toMatchObject({grants_execution:false,grants_authority:false});});
  it("does not alter public cockpit vocabularies",async()=>{const states={awareness:["SNAPSHOT","BEHAVIORAL","STRUCTURAL"],plan:["COHERENT","SOME_GAPS","INCOHERENT"],reality:["STABLE","SHIFTING","UNSTABLE","ASSUMED"],pressure:["LOW","MEDIUM","HIGH"]};expect(states).toEqual({awareness:["SNAPSHOT","BEHAVIORAL","STRUCTURAL"],plan:["COHERENT","SOME_GAPS","INCOHERENT"],reality:["STABLE","SHIFTING","UNSTABLE","ASSUMED"],pressure:["LOW","MEDIUM","HIGH"]});expect(buildOperationalCockpitSnapshotV1).toBeTypeOf("function");});
});
