import {describe,expect,it} from "vitest";

async function evidence(domain="operations",profile="operations-v1"){const {createOperationalDomainEvidenceProfileV1}=await import("../canonical.operational.roles.v1");return createOperationalDomainEvidenceProfileV1({version:1,profile_ref:`profile:${profile}`,domain_ref:`domain:${domain}`,profile_version:"1",supported_subject_kinds:["DOMAIN_OBJECT"],evidence_mappings:[],relationship_family_ref:`relationship-family:${domain}`});}
async function binding(domain="operations",overrides:Record<string,unknown>={}){const {createCanonicalDomainInterventionProfileV1}=await import("../canonical.domain.intervention.profile.v1");const ep=await evidence(domain,`${domain}-v1`);return createCanonicalDomainInterventionProfileV1({version:1,binding_profile_ref:`intervention-profile:${domain}-v1`,binding_profile_version:"1",evidence_profile:ep,policy_ref:`policy:${domain}-intervention-binding-v1`,dimension_primitives:[{dimension_key:"RESOURCE_RELATION"}],intervention_primitives:[{primitive_key:"REASSIGN_RESOURCE",admitted_intervention_class_ref:`${domain}-intervention-class:admitted`,admitted_intervention_class_digest:"a".repeat(64),knowledge_hypothesis_refs:[`knowledge-hypothesis:${domain}`],experience_hypothesis_refs:[`experience-hypothesis:${domain}`]}],constraint_family_keys:["RESOURCE_FEASIBILITY"],evaluator_family_keys:["DOMAIN_CAUSAL_EVALUATOR"],dimension_intervention_bindings:[{dimension_key:"RESOURCE_RELATION",primitive_key:"REASSIGN_RESOURCE"}],intervention_constraint_bindings:[{primitive_key:"REASSIGN_RESOURCE",constraint_family_key:"RESOURCE_FEASIBILITY"}],intervention_evaluator_bindings:[{dimension_key:"RESOURCE_RELATION",primitive_key:"REASSIGN_RESOURCE",evaluator_family_key:"DOMAIN_CAUSAL_EVALUATOR"}],qualification_refs:[`qualification:${domain}-binding`],...overrides} as any);}

describe("DOMAIN-INTERVENTION-PRIMITIVE-BINDING-SEMANTICS-WU1",()=>{
 it("creates deterministic recursively immutable identity and verifies integrity",async()=>{const {verifyCanonicalDomainInterventionProfileV1}=await import("../canonical.domain.intervention.profile.v1");const a=await binding(),b=await binding();expect(a.binding_profile_id).toBe(b.binding_profile_id);expect(Object.isFrozen(a)&&Object.isFrozen(a.dimension_primitives)&&Object.isFrozen(a.intervention_primitives[0].knowledge_hypothesis_refs)).toBe(true);await expect(verifyCanonicalDomainInterventionProfileV1(a)).resolves.toBeUndefined();});
 it.each(["operations","project-management","maintenance","finance","future-domain"])("supports governed opaque domain %s through the same contract",async domain=>{const x=await binding(domain);expect(x.domain_ref).toBe(`domain:${domain}`);expect(x.domain_profile_ref).toBe(`profile:${domain}-v1`);});
 it("binds extensible dimensions, admitted primitives, constraints, and specialized evaluators",async()=>{const x=await binding();expect(x.dimension_intervention_bindings).toEqual([{dimension_key:"RESOURCE_RELATION",primitive_key:"REASSIGN_RESOURCE"}]);expect(x.intervention_constraint_bindings[0].constraint_family_key).toBe("RESOURCE_FEASIBILITY");expect(x.intervention_evaluator_bindings[0]).toMatchObject({dimension_key:"RESOURCE_RELATION",primitive_key:"REASSIGN_RESOURCE",evaluator_family_key:"DOMAIN_CAUSAL_EVALUATOR"});});
 it("supports future unknown primitive and family keys without a universal ontology",async()=>{const x=await binding("future-domain",{dimension_primitives:[{dimension_key:"NOVEL_DIMENSION"}],intervention_primitives:[{primitive_key:"NOVEL_PRINCIPLE",admitted_intervention_class_ref:"future-class:admitted",admitted_intervention_class_digest:"b".repeat(64),knowledge_hypothesis_refs:[],experience_hypothesis_refs:[]}],constraint_family_keys:["NOVEL_CONSTRAINT"],evaluator_family_keys:["NOVEL_EVALUATOR"],dimension_intervention_bindings:[{dimension_key:"NOVEL_DIMENSION",primitive_key:"NOVEL_PRINCIPLE"}],intervention_constraint_bindings:[{primitive_key:"NOVEL_PRINCIPLE",constraint_family_key:"NOVEL_CONSTRAINT"}],intervention_evaluator_bindings:[{dimension_key:"NOVEL_DIMENSION",primitive_key:"NOVEL_PRINCIPLE",evaluator_family_key:"NOVEL_EVALUATOR"}]});expect(x.intervention_primitives[0].primitive_key).toBe("NOVEL_PRINCIPLE");});
 it("keeps knowledge and experience hypotheses separate from governed admission",async()=>{const x=await binding();expect(x.intervention_primitives[0]).toMatchObject({knowledge_hypothesis_refs:["knowledge-hypothesis:operations"],experience_hypothesis_refs:["experience-hypothesis:operations"],admitted_intervention_class_ref:"operations-intervention-class:admitted"});expect(x.hypothesis_is_truth).toBe(false);});
 it("normalizes ordering and duplicate declarative bindings deterministically",async()=>{const a=await binding(),b=await binding("operations",{dimension_primitives:[{dimension_key:"RESOURCE_RELATION"},{dimension_key:"RESOURCE_RELATION"}],dimension_intervention_bindings:[{dimension_key:"RESOURCE_RELATION",primitive_key:"REASSIGN_RESOURCE"},{dimension_key:"RESOURCE_RELATION",primitive_key:"REASSIGN_RESOURCE"}],intervention_constraint_bindings:[{primitive_key:"REASSIGN_RESOURCE",constraint_family_key:"RESOURCE_FEASIBILITY"},{primitive_key:"REASSIGN_RESOURCE",constraint_family_key:"RESOURCE_FEASIBILITY"}],intervention_evaluator_bindings:[{dimension_key:"RESOURCE_RELATION",primitive_key:"REASSIGN_RESOURCE",evaluator_family_key:"DOMAIN_CAUSAL_EVALUATOR"},{dimension_key:"RESOURCE_RELATION",primitive_key:"REASSIGN_RESOURCE",evaluator_family_key:"DOMAIN_CAUSAL_EVALUATOR"}]});expect(b.binding_profile_id).toBe(a.binding_profile_id);});
 it("rejects undeclared relationships and forged identities fail closed",async()=>{const {verifyCanonicalDomainInterventionProfileV1}=await import("../canonical.domain.intervention.profile.v1");await expect(binding("operations",{dimension_intervention_bindings:[{dimension_key:"UNKNOWN",primitive_key:"REASSIGN_RESOURCE"}]})).rejects.toThrow("DOMAIN_BINDING_DIMENSION_INTERVENTION_UNDECLARED");const x=await binding();await expect(verifyCanonicalDomainInterventionProfileV1({...x,binding_profile_digest:"0".repeat(64)})).rejects.toThrow("DOMAIN_BINDING_INTEGRITY_INVALID");});
 it("rejects evidence-profile substitution and binds its digest into identity",async()=>{const ep=await evidence();await expect(binding("operations",{evidence_profile:{...ep,profile_digest:"0".repeat(64)}})).rejects.toThrow("DOMAIN_BINDING_EVIDENCE_PROFILE_INTEGRITY_INVALID");const other=await evidence("operations","other");expect((await binding("operations",{evidence_profile:other})).binding_profile_id).not.toBe((await binding()).binding_profile_id);});
 it("is compatible with opaque Operations class identity and general discovery fields",async()=>{const {createOperationsGovernedInterventionClassV1}=await import("../../industrial/cognition/operations.governed.intervention.class.v1");const c=await createOperationsGovernedInterventionClassV1({version:1,domain_profile_ref:"profile:operations-v1",domain_profile_version:"1",class_key:"INVENTORY_REALLOCATION",producer_ref:"producer:ops",policy_ref:"policy:ops"}),x=await binding("operations",{intervention_primitives:[{primitive_key:"REASSIGN_RESOURCE",admitted_intervention_class_ref:c.intervention_class_id,admitted_intervention_class_digest:c.intervention_class_digest,knowledge_hypothesis_refs:[],experience_hypothesis_refs:[]}]});expect(x).toMatchObject({domain_profile_ref:c.domain_profile_ref,domain_profile_version:c.domain_profile_version});expect(x.intervention_primitives[0].admitted_intervention_class_ref).toBe(c.intervention_class_id);expect({domain_profile_ref:x.domain_profile_ref,domain_profile_version:x.domain_profile_version,dimension_ref:`dimension:${x.dimension_primitives[0].dimension_key.toLowerCase()}`,admitted_intervention_class_ref:x.intervention_primitives[0].admitted_intervention_class_ref,admitted_intervention_class_digest:x.intervention_primitives[0].admitted_intervention_class_digest,evaluator_ref:`evaluator:${x.intervention_evaluator_bindings[0].evaluator_family_key.toLowerCase()}`}).toMatchObject({domain_profile_ref:"profile:operations-v1"});});
 it.each(["current_state_ref","changeability_status","admissibility_status","material_effect_status","recommendation_ref","selected_action_ref","action_instance","execution_payload","source_system","authority_tier","subscription_tier","approval_ref","delegation_ref","credential_ref","decision_influenceability_ref","decision_opportunity_ref","decision_margin_ref","urgency","cost_of_waiting","pressure"])("rejects runtime, source, authority, execution, or downstream input %s",async key=>await expect(binding("operations",{[key]:"forbidden:1"})).rejects.toThrow("DOMAIN_BINDING_UNSUPPORTED_INPUT"));
 it("establishes no current truth, recommendation, authority, execution, or downstream decision output",async()=>{const x=await binding(),json=JSON.stringify(x);expect(x).toMatchObject({declarative_only:true,establishes_current_truth:false,establishes_changeability:false,establishes_admissibility:false,establishes_material_effect:false,recommended:false,selected:false,executable:false,grants_authority:false,grants_execution:false});for(const key of ["changeability_status","admissibility_status","material_effect_status","recommendation","action","payload","influenceability","opportunity","margin","urgency","cost_of_waiting","pressure"])expect(x).not.toHaveProperty(key);expect(json).not.toMatch(/ERP|SAP|MES|email|chat|telephone|VISION|JUNIOR|SENIOR|PRINCIPAL/);});
 it("contains no Operations-specific universal field or parent/default domain",async()=>{const operations=await binding(),project=await binding("project-management");for(const key of Object.keys(operations))expect(key).not.toMatch(/operations|inventory|sku|order|supplier|warehouse|bom/i);expect(Object.keys(operations)).toEqual(Object.keys(project));});
});
