import { applyD1Migrations,env } from "cloudflare:test";
import { beforeAll,beforeEach,describe,expect,it } from "vitest";
import m7 from "../../../../migrations/0007_oir_track_a_persistence.sql?raw";import m9 from "../../../../migrations/0009_oir_participation_runtime.sql?raw";import m12 from "../../../../migrations/0012_knowledge_exposure_persistence.sql?raw";import m14 from "../../../../migrations/0014_outbound_disclosure_admission.sql?raw";
import { NOW,disclosure } from "../../knowledge-exposure/__tests__/fixtures";
import { buildKnowledgeExposureEvidenceV1 } from "../../knowledge-exposure/knowledge.exposure.evidence.v1";import { evaluateKnowledgeExposurePolicyV1 } from "../../knowledge-exposure/knowledge.exposure.policy.v1";import { deepCopyAndFreeze } from "../../knowledge-exposure/knowledge.projection.guard.v1";
import { D1KnowledgeExposureCurrentStateV1,D1KnowledgeExposureRepositoryV1,KnowledgeExposureLifecycleV1,type KnowledgeExposureConsumptionClaimV1 } from "../../knowledge-exposure/persistence";
import { D1OutboundDisclosureCurrentStateV1,D1OutboundDisclosureRepositoryV1 } from "../outbound.disclosure.d1.v1";import { OutboundDisclosureRuntimeV1 } from "../outbound.disclosure.runtime.v1";import type { OutboundDisclosureAdmissionRequestV1,OutboundDisclosureConsumptionClaimV1 } from "../outbound.disclosure.contracts.v1";
const db=env.POLICIES_DB,queries=(sql:string)=>sql.split(/;\s*\r?\n(?=CREATE (?:TABLE|(?:UNIQUE )?INDEX|TRIGGER))/).map(q=>q.trim()).filter(Boolean).map(q=>q.endsWith(";")?q:`${q};`),migrations=[m7,m9,m12,m14].map((sql,i)=>({name:`m${i}`,queries:queries(sql)}));let clock="2026-08-02T10:00:30.000Z",current={authority_current:true,recipient_entitled:true,channel_permitted:true};
const knowledgeStore=new D1KnowledgeExposureRepositoryV1(db),knowledgeRuntime=()=>new KnowledgeExposureLifecycleV1(knowledgeStore,new D1KnowledgeExposureCurrentStateV1(db,async()=>({authority_current:true,target_permitted:true,region_permitted:true,retention_permitted:true})),()=>clock),repository=new D1OutboundDisclosureRepositoryV1(db),runtime=()=>new OutboundDisclosureRuntimeV1(repository,new D1OutboundDisclosureCurrentStateV1(db,async()=>current),()=>clock);
async function eligibility(){const source=deepCopyAndFreeze(disclosure()) as ReturnType<typeof disclosure>,decision=evaluateKnowledgeExposurePolicyV1(source,NOW),evidence=buildKnowledgeExposureEvidenceV1(source,decision),persisted=await knowledgeRuntime().issue(source,decision,evidence),claim=deepCopyAndFreeze({version:1,decision_id:decision.decision_id,binding_id:persisted.binding_id!,principal_id:decision.principal_id,session_id:decision.session_id,membership_id:decision.membership_id,tenant_id:decision.tenant_id,company_id:decision.company_id,operation:decision.operation,purpose:decision.purpose,target_class:decision.target_class,target_identity:decision.target_identity,target_region:source.target_region,requested_retention:decision.effective_retention,manifest_id:`${source.projection.schema_id}@${source.projection.schema_version}`,projection_digest:decision.projection_digest,knowledge_digests:decision.knowledge_digests,consuming_runtime:"oks-wu4a",intended_transport_class:"OUTBOUND_COMMUNICATION",correlation_id:decision.correlation_id,causal_references:decision.reason_codes}) as KnowledgeExposureConsumptionClaimV1;return knowledgeRuntime().consume(claim);}
async function request(overrides:Partial<OutboundDisclosureAdmissionRequestV1>={}){const e=await eligibility();return deepCopyAndFreeze({version:1,eligibility:e,authority_reference:"authority-proof:oks",governance_references:["governance-review:opaque"],communication_family:"TENANT_OPERATIONAL_DISCLOSURE",recipient:{version:1,recipient_id:"customer:001",recipient_class:"AUTHORIZED_BUSINESS_RECIPIENT",entitlement_reference:"recipient-entitlement:001",tenant_id:e.tenant_id,company_id:e.company_id},channel:"EMAIL",representation:"STRUCTURED_JSON",classification:"INTERNAL",requested_at:clock,expires_at:"2026-08-02T10:01:00.000Z",correlation_id:e.correlation_id,causal_references:e.causal_references,...overrides}) as OutboundDisclosureAdmissionRequestV1;}
function claim(a:Awaited<ReturnType<OutboundDisclosureRuntimeV1["admit"]>>["admission"],overrides:Partial<OutboundDisclosureConsumptionClaimV1>={}):OutboundDisclosureConsumptionClaimV1{return deepCopyAndFreeze({version:1,disclosure_id:a.disclosure_id,authority_reference:a.authority_reference,recipient_id:a.recipient.recipient_id,entitlement_reference:a.recipient.entitlement_reference,channel:a.channel,representation:a.representation,manifest_id:a.manifest_id,projection_digest:a.projection_digest,consuming_runtime:"oks-wu4b",correlation_id:a.correlation_id,causal_references:a.causal_references,...overrides}) as OutboundDisclosureConsumptionClaimV1;}
beforeAll(async()=>applyD1Migrations(db,migrations));beforeEach(async()=>{clock="2026-08-02T10:00:30.000Z";current={authority_current:true,recipient_entitled:true,channel_permitted:true};for(const table of ["outbound_disclosure_audit_events","outbound_disclosure_consumptions","outbound_disclosure_admissions","knowledge_exposure_audit_events","knowledge_exposure_consumptions","knowledge_exposure_projection_bindings","knowledge_exposure_decisions","oir_company_selections","oir_organization_memberships","oir_tenant_company_ownership","oir_companies","oir_tenants","oir_server_sessions","oir_external_authentication_bindings","oir_principals"])await db.prepare(`DELETE FROM ${table}`).run();const p=disclosure().participation;await db.prepare("INSERT INTO oir_principals VALUES (?,?,?,?)").bind(p.principal_id,"HUMAN","ACTIVE",NOW).run();await db.prepare("INSERT INTO oir_external_authentication_bindings VALUES (?,?,?,?,?,?,?,?,?,?)").bind("external:wu4a",p.principal_id,"HUMAN","test","issuer","subject","mfa","MULTI_FACTOR",NOW,"verification").run();await db.prepare("INSERT INTO oir_server_sessions VALUES (?,?,?,?,?,?,?,?,?)").bind(p.session_id,p.principal_id,"external:wu4a",NOW,"2026-08-02T11:00:00.000Z","MULTI_FACTOR","ACTIVE",null,null).run();await db.prepare("INSERT INTO oir_tenants VALUES (?,?,?)").bind(p.tenant_id,"ACTIVE",NOW).run();await db.prepare("INSERT INTO oir_companies VALUES (?,?,?)").bind(p.company_id,"ACTIVE",NOW).run();await db.prepare("INSERT INTO oir_tenant_company_ownership VALUES (?,?,?,?,?)").bind(p.company_id,p.tenant_id,NOW,null,"ownership:wu4a").run();await db.prepare("INSERT INTO oir_organization_memberships VALUES (?,?,?,?,?,?,?,?,?,?)").bind(p.membership_id,p.principal_id,p.company_id,"REQUESTED",NOW,"request",null,null,null,null).run();await db.prepare("UPDATE oir_organization_memberships SET lifecycle_state='ACTIVE',activation_reference='activation',activated_at=? WHERE membership_id=?").bind(NOW,p.membership_id).run();await db.prepare("INSERT INTO oir_company_selections VALUES (?,?,?,?,?,?,?,?,?)").bind("selection:wu4a",p.session_id,p.principal_id,p.membership_id,p.company_id,NOW,"selection",null,null).run();});
describe("OKS-WU4A governed outbound disclosure (actual D1)",()=>{
 it("admits and persists one exact transport-neutral disclosure idempotently",async()=>{const r=await request(),a=await runtime().admit(r),b=await runtime().admit(r);expect(a.disposition).toBe("CREATED");expect(b.disposition).toBe("IDENTICAL");expect(a.admission).toMatchObject({communication_family:"TENANT_OPERATIONAL_DISCLOSURE",channel:"EMAIL",representation:"STRUCTURED_JSON",authority_reference:"authority-proof:oks",governance_references:["governance-review:opaque"]});expect(JSON.stringify(a)).not.toMatch(/customer_name|price|terms|prompt|credential/i);});
 it("rejects inferred families, non-disclosure eligibility, and owner or recipient substitution",async()=>{const base=await request();for(const [change,code] of [[{communication_family:"ORGANIZATIONAL_GOVERNANCE_COMMUNICATION"},"DISCLOSURE_FAMILY_NOT_ADMITTED"],[{authority_reference:""},"DISCLOSURE_REQUEST_INVALID"],[{recipient:{...base.recipient,company_id:"other"}},"DISCLOSURE_OWNER_SUBSTITUTED"],[{recipient:{...base.recipient,recipient_id:"other"}},"DISCLOSURE_RECIPIENT_SUBSTITUTED"]] as const)await expect(runtime().admit(deepCopyAndFreeze({...base,...change}) as any)).rejects.toMatchObject({code});});
 it("binds authority, recipient, channel, representation and projection without transport",async()=>{const a=(await runtime().admit(await request())).admission,out=await runtime().consume(claim(a));expect(out).toMatchObject({disclosure_id:a.disclosure_id,projection_digest:a.projection_digest,transport_executed:false});expect(Object.isFrozen(out)).toBe(true);expect((await db.prepare("SELECT COUNT(*) n FROM outbound_disclosure_consumptions").first<any>()).n).toBe(1);});
 it("rejects every bound substitution",async()=>{const a=(await runtime().admit(await request())).admission;for(const [change,code] of [[{authority_reference:"other"},"DISCLOSURE_AUTHORITY_SUBSTITUTED"],[{recipient_id:"other"},"DISCLOSURE_RECIPIENT_SUBSTITUTED"],[{entitlement_reference:"other"},"DISCLOSURE_RECIPIENT_SUBSTITUTED"],[{channel:"SMS"},"DISCLOSURE_CHANNEL_SUBSTITUTED"],[{representation:"PLAIN_TEXT"},"DISCLOSURE_REPRESENTATION_SUBSTITUTED"],[{manifest_id:"other"},"DISCLOSURE_PROJECTION_SUBSTITUTED"],[{projection_digest:"b".repeat(64)},"DISCLOSURE_PROJECTION_SUBSTITUTED"]] as const)await expect(runtime().consume(claim(a,change as any))).rejects.toMatchObject({code});});
 it("revalidates current authority, entitlement, ownership, and channel",async()=>{const a=(await runtime().admit(await request())).admission;for(const state of [{authority_current:false,recipient_entitled:true,channel_permitted:true},{authority_current:true,recipient_entitled:false,channel_permitted:true},{authority_current:true,recipient_entitled:true,channel_permitted:false}]){current=state;await expect(runtime().consume(claim(a))).rejects.toMatchObject({code:"DISCLOSURE_CURRENT_STATE_INVALID"});}current={authority_current:true,recipient_entitled:true,channel_permitted:true};await db.prepare("UPDATE oir_tenant_company_ownership SET effective_until='2026-08-02T10:00:29.000Z'").run();await expect(runtime().consume(claim(a))).rejects.toMatchObject({code:"DISCLOSURE_CURRENT_STATE_INVALID"});});
 it("allows exactly one concurrent consumption and rejects sequential replay",async()=>{const a=(await runtime().admit(await request())).admission,c=claim(a),results=await Promise.allSettled([runtime().consume(c),runtime().consume(c)]);expect(results.filter(x=>x.status==="fulfilled")).toHaveLength(1);expect(results.filter(x=>x.status==="rejected")).toHaveLength(1);await expect(runtime().consume(c)).rejects.toMatchObject({code:"DISCLOSURE_REPLAYED"});expect((await db.prepare("SELECT COUNT(*) n FROM outbound_disclosure_consumptions").first<any>()).n).toBe(1);});
 it("rejects expiry before consumption",async()=>{const a=(await runtime().admit(await request())).admission;clock="2026-08-02T10:01:00.000Z";await expect(runtime().consume(claim(a))).rejects.toMatchObject({code:"DISCLOSURE_EXPIRED"});});
 it("preserves immutable admissions, consumptions and content-free audit",async()=>{const a=(await runtime().admit(await request())).admission;await runtime().consume(claim(a));for(const sql of ["UPDATE outbound_disclosure_admissions SET channel='SMS'","DELETE FROM outbound_disclosure_consumptions","UPDATE outbound_disclosure_audit_events SET outcome='x'"])await expect(db.prepare(sql).run()).rejects.toThrow(/IMMUTABLE/);const rows=await db.prepare("SELECT * FROM outbound_disclosure_audit_events").all();expect(JSON.stringify(rows.results)).not.toMatch(/customer_name|price|terms|prompt|credential/i);});
});
