export type Gcc4mIdentityV1 = Readonly<{ candidate_id:string; candidate_version:string; base_model:string; base_revision:string; corpus_id:string; corpus_version:string; corpus_digest:string; training_config_digest:string; seed:number; lora_rank:number; lora_alpha:number; lora_dropout:number }>;
export type Gcc4mPersistedSnapshotV1 = Readonly<{ complete:boolean; identity?:Gcc4mIdentityV1; hashes_valid:boolean; files:readonly string[]; checkpoint_step?:number; adapter_digest?:string; dataset_digest?:string; evaluation_config_digest?:string }>;
const requiredAdapter=["adapter/adapter_model.safetensors","adapter/adapter_config.json","candidate.manifest.json","training.config.json","training.metrics.json","environment.manifest.json"] as const;
const requiredCheckpoint=["adapter_model.safetensors","adapter_config.json","optimizer.pt","scheduler.pt","trainer_state.json","rng_state.pth","checkpoint.manifest.json"] as const;
export const sameGcc4mIdentityV1=(left:Gcc4mIdentityV1|undefined,right:Gcc4mIdentityV1)=>Boolean(left)&&Object.keys(right).every((key)=>left![key as keyof Gcc4mIdentityV1]===right[key as keyof Gcc4mIdentityV1]);
export function validGcc4mFinalAdapterV1(value:Gcc4mPersistedSnapshotV1|undefined,expected:Gcc4mIdentityV1){return Boolean(value?.complete&&value.hashes_valid&&sameGcc4mIdentityV1(value.identity,expected)&&requiredAdapter.every((name)=>value.files.includes(name)));}
export function validGcc4mCheckpointV1(value:Gcc4mPersistedSnapshotV1,expected:Gcc4mIdentityV1){return Boolean(value.complete&&value.hashes_valid&&sameGcc4mIdentityV1(value.identity,expected)&&Number.isInteger(value.checkpoint_step)&&requiredCheckpoint.every((name)=>value.files.includes(name)));}
export function decideGcc4mTrainingActionV1(finalAdapter:Gcc4mPersistedSnapshotV1|undefined,checkpoints:readonly Gcc4mPersistedSnapshotV1[],expected:Gcc4mIdentityV1){if(validGcc4mFinalAdapterV1(finalAdapter,expected))return{action:"SKIP_ALREADY_COMPLETE" as const};const valid=checkpoints.filter((value)=>validGcc4mCheckpointV1(value,expected)).sort((a,b)=>b.checkpoint_step!-a.checkpoint_step!);return valid[0]?{action:"RESUME_FROM_CHECKPOINT" as const,checkpoint_step:valid[0].checkpoint_step}:{action:"FRESH_TRAIN" as const};}
export function reusableGcc4mEvaluationV1(value:Gcc4mPersistedSnapshotV1|undefined,expected:Gcc4mIdentityV1,adapterDigest:string,datasetDigest:string,evaluationConfigDigest:string){return Boolean(value?.complete&&value.hashes_valid&&sameGcc4mIdentityV1(value.identity,expected)&&value.adapter_digest===adapterDigest&&value.dataset_digest===datasetDigest&&value.evaluation_config_digest===evaluationConfigDigest&&value.files.includes("result.json")&&value.files.includes("evaluation.manifest.json")&&value.files.includes("SHA256SUMS.txt"));}
export const safeGcc4mResultEntriesV1=(entries:readonly string[])=>entries.every((entry)=>!/(?:^|\/)(?:config\.json|pytorch_model\.bin|model\.safetensors)$/.test(entry)&&!/credential|api[_-]?key|token\.json/i.test(entry)&&!entry.includes("checkpoints/"));
