import {buildGraphVersionV1} from "./organizational.authority.runtime.v1";
import {OagCanonicalErrorV1,type CanonicalActorBindingV1,type CanonicalAuthorityRootV1,type CanonicalConfirmationChainV1,type CanonicalPositionV1,type CanonicalResponsibilityV1,type OagGraphStateReferenceV1,type OagGraphVersionV1,type OperationalAuthorityDelegationV1,type OrganizationalAuthorityPolicyV1} from "./organizational.authority.contracts.v1";
const j=(v:unknown)=>JSON.stringify(v);
export class CanonicalOrganizationalAuthorityD1V1{
 constructor(private readonly db:D1Database){}
 async persistPolicy(p:OrganizationalAuthorityPolicyV1){return this.run(this.db.prepare("INSERT INTO oag_can_policies VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(p.policy_id,p.version,p.policy_version,p.effective_from,p.effective_until??null,p.root_activation_rule,p.responsibility_confirmation_rule,p.delegation_confirmation_rule,p.max_delegation_depth,p.proof_validity_rule,p.graph_supersession_rule,p.correlation_id,j(p.causal_references)));}
 async persistActorBinding(v:CanonicalActorBindingV1){const b=v.binding;return this.run(this.db.prepare("INSERT INTO oag_can_actor_bindings VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").bind(b.oag_actor_binding_id,1,b.oag_actor_id,b.principal_id,b.membership_id,v.tenant_id,b.company_id,v.effective_from,v.policy_id,b.binding_reference,j(v.causal_references)));}
 async bootstrapRoot(v:CanonicalAuthorityRootV1,at:string){const state=await this.db.prepare(`SELECT e.*,a.lifecycle_state authority_state,a.expires_at authority_expires,cb.company_id,m.principal_id membership_principal,m.company_id membership_company,m.lifecycle_state membership_state,p.lifecycle_state principal_state,o.tenant_id FROM orpa_eligibilities e JOIN orpa_authorities a ON a.authority_id=e.authority_id JOIN legal_entity_company_bindings cb ON cb.binding_id=e.company_binding_id JOIN oir_organization_memberships m ON m.membership_id=e.membership_id JOIN oir_principals p ON p.principal_id=e.actor_principal_id JOIN oir_tenant_company_ownership o ON o.company_id=cb.company_id LEFT JOIN orpa_authority_transitions t ON t.authority_id=a.authority_id WHERE e.eligibility_id=? AND e.consumed_at IS NULL AND e.expires_at>? AND e.requested_scope='REPRESENT_LEGAL_ENTITY_FOR_PLATFORM_ONBOARDING' AND e.future_consumer='OAG_AUTHORITY_ROOT_BOOTSTRAP_V1' AND e.transferable=0 AND e.executable=0 AND a.lifecycle_state='ACTIVE' AND a.expires_at>? AND t.transition_id IS NULL AND m.lifecycle_state='ACTIVE' AND p.lifecycle_state='ACTIVE' AND o.effective_from<=? AND (o.effective_until IS NULL OR o.effective_until>?)`).bind(v.bootstrap_eligibility_id,at,at,at,at).first<Record<string,unknown>>();if(!state||state.authority_id!==v.bootstrap_authority_id||state.actor_principal_id!==v.principal_id||state.membership_id!==v.membership_id||state.legal_entity_id!==v.legal_entity_id||state.company_binding_id!==v.company_binding_id||state.company_id!==v.company_id||state.membership_principal!==v.principal_id||state.membership_company!==v.company_id||state.tenant_id!==v.tenant_id)throw new OagCanonicalErrorV1("OAG_CAN_ROOT_BOOTSTRAP_UNAUTHORIZED");try{await this.db.batch([this.db.prepare("INSERT INTO oag_can_roots VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(v.root_id,v.tenant_id,v.company_id,v.oag_actor_id,v.actor_binding_id,v.principal_id,v.membership_id,v.domain,j(v.permitted_scope),v.effective_from,v.effective_until??null,v.bootstrap_eligibility_id,v.bootstrap_authority_id,v.legal_entity_id,v.company_binding_id,v.policy_id,v.graph_version_id,j(v.causal_references)),this.db.prepare("UPDATE orpa_eligibilities SET consumed_at=?,consumption_reference=? WHERE eligibility_id=? AND consumed_at IS NULL").bind(at,v.root_id,v.bootstrap_eligibility_id)]);}catch{const old=await this.db.prepare("SELECT root_id FROM oag_can_roots WHERE root_id=? AND bootstrap_eligibility_id=?").bind(v.root_id,v.bootstrap_eligibility_id).first();if(old)return;throw new OagCanonicalErrorV1("OAG_CAN_PERSISTENCE_FAILED");}}
 async persistPosition(v:CanonicalPositionV1){const p=v.position;return this.run(this.db.prepare("INSERT INTO oag_can_positions VALUES (?,?,?,?,?,?,?,?,?,?)").bind(p.declaration_version_id,p.declaration_id,p.subject_actor_id,p.tenant_id,p.company_id,p.position_code,p.position_title,v.effective_from,v.effective_until??null,j(v.causal_references)));}
 async persistResponsibility(v:CanonicalResponsibilityV1){return this.run(this.db.prepare("INSERT INTO oag_can_responsibilities VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").bind(v.responsibility_id,v.declaration_version_id,v.tenant_id,v.company_id,v.subject_actor_id,j(v.scope),v.effective_from,v.effective_until??null,v.lifecycle_state,v.confirmation_chain_id??null,v.policy_id,j(v.causal_references)));}
 async persistConfirmation(v:CanonicalConfirmationChainV1){const c=v.chain;return this.run(this.db.prepare("INSERT INTO oag_can_confirmation_chains VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(c.confirmation_chain_id,c.subject_actor_id,c.tenant_id,c.company_id,c.declaration_version_id,j(c.steps),j(c.terminal_scope),c.graph_version,v.authority_source_id,v.authority_source_actor_id,v.subject_fact_id,v.policy_id,v.effective_from,v.effective_until??null,j(v.evidence_references),j(v.causal_references)));}
 async persistDelegation(v:OperationalAuthorityDelegationV1){return this.run(this.db.prepare("INSERT INTO oag_can_delegations VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(v.delegation_id,v.tenant_id,v.company_id,v.source_authority_id,v.source_actor_id,v.target_actor_id,v.target_actor_binding_id,v.domain,j(v.delegated_scope),v.effective_from,v.effective_until,v.depth,v.confirmation_chain_id,v.policy_id,v.graph_version_id,j(v.causal_references)));}
 async persistGraph(v:OagGraphVersionV1){try{await this.db.batch([this.db.prepare("INSERT INTO oag_can_graph_versions VALUES (?,?,?,?,?,?,?,?)").bind(v.graph_version_id,v.tenant_id,v.company_id,v.policy_id,v.graph_digest,v.effective_from,v.correlation_id,j(v.causal_references)),...v.state_references.map(r=>this.db.prepare("INSERT INTO oag_can_graph_references VALUES (?,?,?,?)").bind(v.graph_version_id,r.kind,r.identity,r.semantic_digest))]);}catch(error){throw new OagCanonicalErrorV1("OAG_CAN_PERSISTENCE_FAILED",{cause:error});}}
 async transition(kind:string,id:string,to:"REVOKED"|"SUPERSEDED"|"INVALIDATED",at:string,correlation:string,caused:readonly string[],successor?:string){return this.run(this.db.prepare("INSERT INTO oag_can_transitions VALUES (?,?,?,?,?,?,?,?)").bind(`oag-transition:${kind}:${id}:${to}`,kind,id,to,successor??null,at,correlation,j(caused)));}
 async resolveCurrentGraph(tenant:string,company:string):Promise<{graph_version_id:string;graph_digest:string}|null>{const rows=await this.db.prepare("SELECT g.graph_version_id,g.graph_digest FROM oag_can_graph_versions g LEFT JOIN oag_can_transitions t ON t.subject_kind='GRAPH' AND t.subject_id=g.graph_version_id WHERE g.tenant_id=? AND g.company_id=? AND t.transition_id IS NULL").bind(tenant,company).all<{graph_version_id:string;graph_digest:string}>();if(rows.results.length>1)throw new OagCanonicalErrorV1("OAG_CAN_GRAPH_VERSION_AMBIGUOUS");return rows.results[0]??null;}
 async resolveCurrentState(tenant:string,company:string){const current=await this.resolveCurrentGraph(tenant,company);if(!current)return null;const graph=await this.db.prepare("SELECT * FROM oag_can_graph_versions WHERE graph_version_id=?").bind(current.graph_version_id).first<Record<string,unknown>>(),rows=await this.db.prepare("SELECT kind,identity,semantic_digest FROM oag_can_graph_references WHERE graph_version_id=? ORDER BY kind,identity").bind(current.graph_version_id).all<OagGraphStateReferenceV1>();if(!graph)throw new OagCanonicalErrorV1("OAG_CAN_GRAPH_VERSION_INVALID");const rebuilt=buildGraphVersionV1({version:1,tenant_id:tenant,company_id:company,policy_id:String(graph.policy_id)as"OAG_AUTHORITY_POLICY_V1",state_references:rows.results,effective_from:String(graph.effective_from),correlation_id:String(graph.correlation_id),causal_references:JSON.parse(String(graph.causal_references_json))});if(rebuilt.graph_digest!==current.graph_digest)throw new OagCanonicalErrorV1("OAG_CAN_GRAPH_DIGEST_MISMATCH");return Object.freeze({graph:rebuilt,references:Object.freeze([...rows.results])});}
 async audit(event:{id:string;kind:string;subject_kind:string;subject_id:string;outcome:string;reason?:string;actor?:string;policy_id:string;correlation:string;caused:readonly string[];at:string}){try{await this.db.prepare("INSERT INTO oag_can_audit_events VALUES (?,?,?,?,?,?,?,?,?,?,?,NULL)").bind(event.id,event.kind,event.subject_kind,event.subject_id,event.outcome,event.reason??null,event.actor??null,event.policy_id,event.correlation,j(event.caused),event.at).run();}catch{throw new OagCanonicalErrorV1("OAG_CAN_AUDIT_FAILED");}}
 private async run(statement:D1PreparedStatement){try{await statement.run();}catch{throw new OagCanonicalErrorV1("OAG_CAN_PERSISTENCE_FAILED");}}
}
