import { applyD1Migrations,env } from 'cloudflare:test';
import { beforeAll,describe,expect,it } from 'vitest';
import m12 from '../../../../migrations/0012_knowledge_exposure_persistence.sql?raw';
import m13 from '../../../../migrations/0013_cognitive_transport_evidence.sql?raw';
import m26 from '../../../../migrations/0026_runtime_provider_trust_admission.sql?raw';
import m27 from '../../../../migrations/0027_security_runtime_evidence.sql?raw';
import m30 from '../../../../migrations/0030_knowledge_exposure_authority_binding.sql?raw';
import m31 from '../../../../migrations/0031_canonical_runtime_provider_binding.sql?raw';
import m32 from '../../../../migrations/0032_security_evidence_composition.sql?raw';
import { canonicalProviderRuntimeBindingDigestV1 } from '../../provider-trust/provider.precredential.boundary.v1';
import { createSecurityEvidenceCompositionV1,SecurityEvidenceCompositionD1V1,verifyPersistedSecurityEvidenceCompositionV1 } from '..';
const db=()=>env.POLICIES_DB as D1Database,NOW='2026-08-11T10:00:00.000Z',AT='2026-08-11T10:00:01.000Z',LATER='2026-08-11T10:01:00.000Z',J='[]',queries=(s:string)=>s.split(/;\s*(?=CREATE)/).map(x=>x.trim()).filter(Boolean).map(x=>x.endsWith(';')?x:x+';');
const insert=async(table:string,values:unknown[])=>db().prepare(`INSERT INTO ${table} VALUES (${values.map(()=>'?').join(',')})`).bind(...values).run();
async function composition(){const binding:any={version:1,binding_id:'binding:1',mapping_id:'mapping:1',provider:'openai',provider_account_id:'account:1',provider_deployment_id:'deployment:1',adapter_identity:'adapter:1',selected_model:'model:1',credential_reference:'secret://openai',environment_class:'PRODUCTION',downstream_provider_identity_status:'PROVEN',downstream_deployment_identity_status:'PROVEN',binding_policy_version:'PROVIDER_RUNTIME_BINDING_POLICY_V1',issued_at:AT,correlation_id:'correlation:1',causal_references:[],admission_granted:false,transport_executed:false},digest=await canonicalProviderRuntimeBindingDigestV1(binding);return{binding,digest,c:createSecurityEvidenceCompositionV1({version:1,request_id:'operation:1',principal_id:'principal:1',session_id:'session:1',tenant_id:'tenant:1',company_id:'company:1',oks_request_id:'request:1',oks_decision_id:'decision:1',projection_id:'manifest:1',projection_digest:'a'.repeat(64),oks_consumption_id:'consumption:1',organizational_authority:{applicability_evidence_id:'app:oag',requirement:'NOT_APPLICABLE'},p9:{applicability_evidence_id:'app:p9',status:'NOT_APPLICABLE'},pt_admissions:[{admission_id:'admission:1',admission_digest:'b'.repeat(64)}],runtime_bindings:[{runtime_binding_id:'binding:1',runtime_binding_digest:digest}],credential_access_evidence_ids:['credential:1'],attempts:[{attempt_id:'attempt:1',sequence:0,outcome:'TRANSPORT_SUCCEEDED',admission_id:'admission:1',admission_digest:'b'.repeat(64),runtime_binding_id:'binding:1',runtime_binding_digest:digest,credential_access_evidence_id:'credential:1',transport_evidence_id:'transport:1'}],transport_evidence_ids:['transport:1'],fallback_edges:[],edges:[],final_outcome:'COMPLETED',verification_result:'VERIFIED',historical_validity_basis:'VALID_AT_OPERATION_TIME',composed_at:LATER,causal_lineage:['attempt:1']})};}
async function sources(binding:any,digest:string){
 await insert('knowledge_exposure_decisions',['decision:1','request:1','ADMITTED','participation:1','principal:1','session:1','membership:1','tenant:1','company:1','authority:1',null,'COGNITIVE_EXPOSURE','LANGUAGE_REFINEMENT','KNOWLEDGE_EXPOSURE_POLICY_V1','SHARED_REMOTE_PROVIDER',null,'INTERNAL','TENANT_CONTROLLED','EU','NO_RETENTION','manifest:1','a'.repeat(64),J,NOW,LATER,J,'oks-evidence:1','correlation:1',J,'canonical:1']);
 await insert('knowledge_exposure_projection_bindings',['oks-binding:1','decision:1','manifest:1','a'.repeat(64),J,'COGNITIVE_EXPOSURE','LANGUAGE_REFINEMENT','SHARED_REMOTE_PROVIDER',null,'tenant:1','company:1',NOW]);
 await insert('knowledge_exposure_consumptions',['consumption:1','decision:1','oks-binding:1','runtime','COGNITIVE_PROVIDER',null,AT,'correlation:1',J,'CONSUMED']);
 await insert('knowledge_exposure_authority_bindings',['authority-binding:1','authority-binding-digest','request:1','decision:1','a'.repeat(64),AT,'correlation:1']);
 for(const [id,domain,reason]of[['app:oag','ORGANIZATIONAL_AUTHORITY','COGNITIVE_TRANSFORMATION_ONLY'],['app:p9','P9','ORDINARY_COGNITIVE_PROVIDER_OPERATION']])await insert('security_evidence_applicability',[id,'authority-binding:1',domain,'NOT_APPLICABLE',reason,'request:1','decision:1','LANGUAGE_REFINEMENT','a'.repeat(64),'principal:1','session:1','tenant:1','company:1',AT,'correlation:1',J]);
 await insert('runtime_provider_trust_admissions',['admission:1',1,'b'.repeat(64),'tenant:1','company:1','legal:1','decision:1','oks-binding:1','consumption:1','manifest:1','a'.repeat(64),'{}','pt:1','evaluation:1','e'.repeat(64),J,J,'p'.repeat(64),'s'.repeat(64),'binding:1',digest,'openai','account:1','deployment:1','adapter:1','model:1','secret://openai',AT,LATER,'reservation:pt','COGNITIVE_PROVIDER_INVOCATION','correlation:1',J,0]);
 await insert('provider_runtime_binding_evidence',[binding.binding_id,1,digest,binding.mapping_id,binding.provider,binding.provider_account_id,binding.provider_deployment_id,binding.adapter_identity,binding.selected_model,binding.credential_reference,binding.environment_class,binding.downstream_provider_identity_status,binding.downstream_deployment_identity_status,binding.binding_policy_version,binding.issued_at,binding.correlation_id,J,0,0,AT]);
 await insert('security_credential_access_evidence',['credential:1',1,'admission:1','b'.repeat(64),'permit','binding:1',digest,'openai','account:1','deployment:1','adapter:1','secret://openai','RESOLUTION_SUCCEEDED',AT,AT,null,'correlation:1',J]);
 await insert('security_provider_runtime_attempts',['attempt:1',1,'operation:1',0,null,'binding:1',digest,'admission:1','b'.repeat(64),'consumption:1','credential:1','openai','account:1','deployment:1','adapter:1','model:1','TRANSPORT_SUCCEEDED',null,null,'transport:1',AT,LATER,'correlation:1',J]);
 await insert('cognitive_transport_dispatch_reservations',['consumption:1','openai',AT]);await insert('cognitive_transport_evidence',['transport:1','decision:1','oks-binding:1','consumption:1','a'.repeat(64),'request-digest','openai','model:1','SHARED_REMOTE_PROVIDER','LANGUAGE_REFINEMENT','EU','NO_RETENTION',AT,'SUCCEEDED','response-digest',null,J]);
}
describe('SEC-WU3C canonical composition actual D1',()=>{
 beforeAll(()=>applyD1Migrations(db(),[m12,m13,m26,m27,m30,m31,m32].map((sql,i)=>({name:String(i),queries:queries(sql)}))));
 it('applies normalized immutable content-free migration',async()=>{const names=(await db().prepare("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'security%composition%' ORDER BY name").all<any>()).results.map(x=>x.name);expect(names).toHaveLength(9);expect(m32).not.toMatch(/prompt|projection_body|credential_secret|authorization_header|provider_response|business_payload/i);});
 it('persists, reconstructs, verifies digest, and converges identically',async()=>{const {c}=await composition(),repo=new SecurityEvidenceCompositionD1V1(db());expect(await repo.persist(c)).toBe('CREATED');expect(await repo.persist(c)).toBe('IDENTICAL');expect(await repo.read(c.composition_id)).toEqual(c);expect((await repo.read(c.composition_id))?.composition_digest).toBe(c.composition_digest);expect((await db().prepare('SELECT COUNT(*) n FROM security_evidence_compositions').first<any>()).n).toBe(1);},15000);
 it('fails closed for the same identity with a competing digest',async()=>{const {c}=await composition(),repo=new SecurityEvidenceCompositionD1V1(db());await repo.persist(c);await expect(repo.persist({...c,composition_digest:'0'.repeat(64)})).rejects.toMatchObject({code:'SECURITY_COMPOSITION_CONFLICT'});});
 it('concurrent identical persistence converges without competing rows',async()=>{const {c}=await composition(),repo=new SecurityEvidenceCompositionD1V1(db()),results=await Promise.all([repo.persist(c),repo.persist(c)]);expect(results.filter(x=>x==='CREATED')).toHaveLength(1);expect(results.filter(x=>x==='IDENTICAL')).toHaveLength(1);expect((await db().prepare('SELECT COUNT(*) n FROM security_evidence_compositions').first<any>()).n).toBe(1);});
 it('makes canonical, reference, and audit rows immutable',async()=>{const {c}=await composition();await new SecurityEvidenceCompositionD1V1(db()).persist(c);await expect(db().prepare("UPDATE security_evidence_compositions SET request_id='x'").run()).rejects.toThrow(/IMMUTABLE/);await expect(db().prepare("UPDATE security_composition_attempts SET attempt_id='x'").run()).rejects.toThrow(/IMMUTABLE/);await expect(db().prepare("UPDATE security_composition_audit SET outcome='x'").run()).rejects.toThrow(/IMMUTABLE/);});
 it('returns INCOMPLETE when authoritative sources are absent',async()=>{const {c}=await composition();await new SecurityEvidenceCompositionD1V1(db()).persist(c);const r=await verifyPersistedSecurityEvidenceCompositionV1(db(),c.composition_id,LATER);expect(r.result).toBe('INCOMPLETE');expect(r.failures).toContain('SECURITY_COMPOSITION_SOURCE_EVIDENCE_NOT_FOUND');expect(r.unresolved_sources.length).toBeGreaterThan(0);});
 it('independently verifies the exact authoritative cognitive chain',async()=>{const {c,binding,digest}=await composition();await new SecurityEvidenceCompositionD1V1(db()).persist(c);await sources(binding,digest);const r=await verifyPersistedSecurityEvidenceCompositionV1(db(),c.composition_id,LATER);expect(r.result).toBe('VERIFIED');expect(r.unresolved_sources).toEqual([]);expect(r.verified_sources).toEqual(expect.arrayContaining(['decision:1','binding:1','credential:1','attempt:1','transport:1','app:oag','app:p9']));});
 it('detects authoritative substitution and never accepts a caller copy',async()=>{const {c,binding,digest}=await composition();await new SecurityEvidenceCompositionD1V1(db()).persist(c);await sources(binding,digest);await db().exec('DROP TRIGGER cognitive_transport_evidence_no_update');await db().prepare("UPDATE cognitive_transport_evidence SET projection_digest='forged'").run();const r=await verifyPersistedSecurityEvidenceCompositionV1(db(),c.composition_id,LATER);expect(r.result).toBe('DENIED');expect(r.failures).toContain('SECURITY_COMPOSITION_TRANSPORT_MISMATCH');expect(verifyPersistedSecurityEvidenceCompositionV1.length).toBe(3);});
 it.each([
  ['runtime_provider_trust_admissions','runtime_provider_trust_admission_immutable','provider_account_id'],
  ['runtime_provider_trust_admissions','runtime_provider_trust_admission_immutable','provider_deployment_id'],
  ['runtime_provider_trust_admissions','runtime_provider_trust_admission_immutable','adapter_identity'],
  ['runtime_provider_trust_admissions','runtime_provider_trust_admission_immutable','selected_model'],
  ['runtime_provider_trust_admissions','runtime_provider_trust_admission_immutable','credential_reference'],
  ['security_provider_runtime_attempts','security_attempt_evidence_immutable','provider_account_id'],
  ['security_provider_runtime_attempts','security_attempt_evidence_immutable','provider_deployment_id'],
  ['security_provider_runtime_attempts','security_attempt_evidence_immutable','adapter_identity'],
  ['security_provider_runtime_attempts','security_attempt_evidence_immutable','model'],
 ] as const)('denies authoritative %s.%s substitution',async(table,trigger,column)=>{const {c,binding,digest}=await composition();await new SecurityEvidenceCompositionD1V1(db()).persist(c);await sources(binding,digest);await db().exec(`DROP TRIGGER ${trigger}`);await db().prepare(`UPDATE ${table} SET ${column}='substituted'`).run();const r=await verifyPersistedSecurityEvidenceCompositionV1(db(),c.composition_id,LATER);expect(r.result).toBe('DENIED');expect(r.failures).toEqual(expect.arrayContaining(['SECURITY_COMPOSITION_RUNTIME_BINDING_MISMATCH']));});
 it('returns typed not-found without fabricating composition identity',async()=>{const r=await verifyPersistedSecurityEvidenceCompositionV1(db(),'missing:composition',LATER);expect(r).toMatchObject({result:'INCOMPLETE',failures:['SECURITY_COMPOSITION_NOT_FOUND']});});
 it('keeps storage content-free',async()=>{const {c}=await composition();await new SecurityEvidenceCompositionD1V1(db()).persist(c);const dump=JSON.stringify((await db().prepare("SELECT * FROM security_evidence_compositions").all()).results)+JSON.stringify((await db().prepare('SELECT * FROM security_composition_edges').all()).results);expect(dump).not.toMatch(/prompt|projection body|credential secret|authorization header|provider response|customer terms/i);});
});
