import { describe, expect, it } from 'vitest';
import { canonicalProviderRuntimeBindingDigestV1 } from '../../provider-trust/provider.precredential.boundary.v1';
import { composeSecurityEvidenceV1, createSecurityEvidenceCompositionResultV1, type SecurityEvidenceComposerInputV1 } from '..';

const T={request:'2026-08-11T10:00:00.000Z',decision:'2026-08-11T10:00:01.000Z',admission:'2026-08-11T10:00:02.000Z',credential:'2026-08-11T10:00:03.000Z',transport:'2026-08-11T10:00:04.000Z',attempt:'2026-08-11T10:00:05.000Z',composed:'2026-08-11T10:00:06.000Z'};
async function fixture(purpose='LANGUAGE_REFINEMENT'):Promise<SecurityEvidenceComposerInputV1>{
	const binding:any={version:1,binding_id:'binding:1',mapping_id:'mapping:1',provider:'openai',provider_account_id:'account:1',provider_deployment_id:'deployment:1',adapter_identity:'adapter:1',selected_model:'model:1',credential_reference:'secret://openai',environment_class:'PRODUCTION',downstream_provider_identity_status:'PROVEN',downstream_deployment_identity_status:'PROVEN',binding_policy_version:'PROVIDER_RUNTIME_BINDING_POLICY_V1',issued_at:T.admission,correlation_id:'correlation:1',causal_references:[],admission_granted:false,transport_executed:false};
	const digest=await canonicalProviderRuntimeBindingDigestV1(binding), requestId='oks-request:1',decisionId='decision:1',consumptionId='consumption:1',projection='a'.repeat(64);
	const request:any={version:1,participation:{version:1,participation_context_id:'participation:1',principal_id:'principal:1',session_id:'session:1',membership_id:'membership:1',tenant_id:'tenant:1',company_id:'company:1',principal_active:true,session_active:true,membership_active:true},authority_reference:'authority:source',operation:'COGNITIVE_EXPOSURE',purpose:{version:1,code:purpose,operation:'COGNITIVE_EXPOSURE'},knowledge:[],projection:{version:1,schema_id:'schema:1',schema_version:'1',representation:'STRUCTURED_JSON',included_fields:[],excluded_categories:[],source_knowledge_references:[],projection_digest:projection},target_class:'SHARED_REMOTE_PROVIDER',source_region:'eu',target_region:'eu',requested_retention:'NO_RETENTION',requested_validity_ms:1000,requested_at:T.request,correlation_id:'correlation:1',causal_references:[]};
	const decision:any={version:1,decision_id:decisionId,request_id:requestId,outcome:'ADMITTED',principal_id:'principal:1',session_id:'session:1',membership_id:'membership:1',tenant_id:'tenant:1',company_id:'company:1',authority_reference:'authority:source',operation:'COGNITIVE_EXPOSURE',purpose,knowledge_digests:[],projection_digest:projection,target_class:'SHARED_REMOTE_PROVIDER',effective_classification:'INTERNAL',effective_sovereignty:'TENANT_CONTROLLED',effective_regions:['eu'],effective_retention:'NO_RETENTION',policy_version:'KNOWLEDGE_EXPOSURE_POLICY_V1',reason_codes:[],issued_at:T.decision,expires_at:T.composed,consumption_identity:'claim:1',correlation_id:'correlation:1'};
	const eligibility:any={version:1,decision_id:decisionId,binding_id:'oks-binding:1',principal_id:'principal:1',session_id:'session:1',membership_id:'membership:1',tenant_id:'tenant:1',company_id:'company:1',operation:'COGNITIVE_EXPOSURE',purpose,target_class:'SHARED_REMOTE_PROVIDER',target_region:'eu',requested_retention:'NO_RETENTION',manifest_id:'manifest:1',projection_digest:projection,knowledge_digests:[],correlation_id:'correlation:1',causal_references:[],consumption_id:consumptionId,policy_version:'KNOWLEDGE_EXPOSURE_POLICY_V1',consumed_at:T.decision};
	const applicability=(domain:string,status:string,reason:string):any=>({version:1,applicability_id:`applicability:${domain}`,domain,status,reason,request_id:requestId,decision_id:decisionId,purpose,projection_digest:projection,principal_id:'principal:1',session_id:'session:1',tenant_id:'tenant:1',company_id:'company:1',recorded_at:T.decision,correlation_id:'correlation:1',causal_references:[]});
	const admission:any={version:1,admission_id:'admission:1',admission_digest:'b'.repeat(64),tenant_id:'tenant:1',company_id:'company:1',legal_entity_id:'legal:1',oks_decision_id:decisionId,oks_binding_id:'oks-binding:1',oks_consumption_id:consumptionId,manifest_id:'manifest:1',projection_digest:projection,effective_context:{},provider_trust_eligibility_id:'pt:1',evaluation_id:'evaluation:1',evaluation_digest:'e'.repeat(64),policy_ids:[],policy_versions:[],policy_digest:'p'.repeat(64),attestation_set_digest:'s'.repeat(64),runtime_binding_id:'binding:1',runtime_binding_digest:digest,provider:'openai',provider_account_id:'account:1',provider_deployment_id:'deployment:1',adapter_identity:'adapter:1',selected_model:'model:1',credential_reference:'secret://openai',issued_at:T.admission,expires_at:T.composed,reservation_id:'reservation:1',invocation_consumer:'COGNITIVE_PROVIDER_INVOCATION',correlation_id:'correlation:1',causal_references:[],transport_executed:false};
	const credential:any={version:1,evidence_id:'credential:1',admission_id:'admission:1',admission_digest:admission.admission_digest,permit_digest:'d'.repeat(64),runtime_binding_id:'binding:1',runtime_binding_digest:digest,provider:'openai',provider_account_id:'account:1',provider_deployment_id:'deployment:1',adapter_identity:'adapter:1',credential_reference:'secret://openai',outcome:'RESOLUTION_SUCCEEDED',attempted_at:T.credential,completed_at:T.credential,failure_code:undefined,correlation_id:'correlation:1',causal_references:[]};
	const attempt:any={version:1,attempt_id:'attempt:1',request_id:'operation:1',sequence:0,runtime_binding_id:'binding:1',runtime_binding_digest:digest,admission_id:'admission:1',admission_digest:admission.admission_digest,oks_consumption_id:consumptionId,credential_access_evidence_id:'credential:1',provider:'openai',provider_account_id:'account:1',provider_deployment_id:'deployment:1',adapter_identity:'adapter:1',model:'model:1',outcome:'TRANSPORT_SUCCEEDED',transport_evidence_id:'transport:1',started_at:T.admission,completed_at:T.attempt,correlation_id:'correlation:1',causal_references:[]};
	const transport:any={version:1,evidence_id:'transport:1',decision_id:decisionId,binding_id:'oks-binding:1',consumption_id:consumptionId,projection_digest:projection,request_digest:'r'.repeat(64),provider:'openai',model:'model:1',provider_deployment_class:'SHARED_REMOTE_PROVIDER',purpose,region:'eu',retention:'NO_RETENTION',dispatched_at:T.transport,status:'SUCCEEDED',response_digest:'x'.repeat(64),causal_references:[]};
	return{version:1,request_id:'operation:1',oks_request_id:requestId,oks_request:request,oks_decision:decision,oks_eligibility:eligibility,organizational_authority_applicability:applicability('ORGANIZATIONAL_AUTHORITY',purpose==='CUSTOMER_QUOTATION_DISCLOSURE'?'APPLICABLE':'NOT_APPLICABLE',purpose==='CUSTOMER_QUOTATION_DISCLOSURE'?'CUSTOMER_QUOTATION_DISCLOSURE':'COGNITIVE_TRANSFORMATION_ONLY'),p9_applicability:applicability('P9','NOT_APPLICABLE','ORDINARY_COGNITIVE_PROVIDER_OPERATION'),pt_admissions:[admission],authoritative_runtime_bindings:[{version:1,binding,binding_digest:digest}],credential_evidence:[credential],attempts:[attempt],transport_evidence:[transport],fallback_edges:[],historical_validity_basis:'VALID_AT_OPERATION_TIME',composed_at:T.composed,causal_lineage:['attempt:1']};
}
const withAuthority=(x:SecurityEvidenceComposerInputV1,patch:any={}):SecurityEvidenceComposerInputV1=>({...x,expected_oag_actor_id:'actor:1',authority_evidence:{version:1,evidence_id:'authority-evidence:1',authority_source_class:'ORGANIZATIONAL_OPERATIONAL_AUTHORITY',authority_proof_id:'proof:1',authority_proof_digest:'f'.repeat(64),oag_actor_id:'actor:1',principal_id:'principal:1',tenant_id:'tenant:1',company_id:'company:1',effective_operational_domain:'CUSTOMER_COMMERCIAL_COMMUNICATION',effective_scope:{domain:'CUSTOMER_COMMERCIAL_COMMUNICATION',intents:['DISCLOSE_CUSTOMER_QUOTATION'],scopes:['DISCLOSE_CUSTOMER_QUOTATION'],limits:[],team_or_subordinate_actor_ids:[],operational_constraints:[]},graph_version:'graph:1',graph_digest:'g'.repeat(64),authority_policy_id:'OAG_AUTHORITY_POLICY_V2',authority_policy_version:2,confirmation_chain_references:[],delegation_lineage:[],issued_at:T.request,expires_at:T.composed,current_state_resolution:'CURRENT',request_id:'oks-request:1',decision_id:'decision:1',purpose:'CUSTOMER_QUOTATION_DISCLOSURE',projection_digest:'a'.repeat(64),correlation_id:'correlation:1',causal_references:[],...patch} as any});

describe('composeSecurityEvidenceV1',()=>{
	it('rejects invalid result-envelope composition presence',()=>{const base:any={version:1,request_id:'operation:1',failures:[],missing_evidence:[],evaluated_at:T.composed,causal_lineage:[]};expect(()=>createSecurityEvidenceCompositionResultV1({...base,result:'VERIFIED'})).toThrow(/SECURITY_COMPOSITION_IDENTITY_MISMATCH/);expect(()=>createSecurityEvidenceCompositionResultV1({...base,result:'INCOMPLETE',composition:{},missing_evidence:['PT_ADMISSION']})).toThrow(/SECURITY_COMPOSITION_IDENTITY_MISMATCH/);expect(createSecurityEvidenceCompositionResultV1({...base,result:'DENIED',failures:['SECURITY_COMPOSITION_DENIED']})).not.toHaveProperty('composition');});
	it.each(['LANGUAGE_REFINEMENT','TRANSLATION','EXPLANATION','STRUCTURED_EXTRACTION'])('verifies complete %s evidence without OAG or P9 evidence',async purpose=>{const r=await composeSecurityEvidenceV1(await fixture(purpose));expect(r.result).toBe('VERIFIED');expect(r.composition).toBeDefined();expect(r.composition?.organizational_authority.requirement).toBe('NOT_APPLICABLE');expect(r.composition?.p9.status).toBe('NOT_APPLICABLE');});
	it('returns immutable envelopes and enforces composition presence rules by construction',async()=>{const verified=await composeSecurityEvidenceV1(await fixture());expect(Object.isFrozen(verified)).toBe(true);expect(verified.result).toBe('VERIFIED');expect(verified.composition).toBeDefined();const incomplete=await composeSecurityEvidenceV1({...await fixture('CUSTOMER_QUOTATION_DISCLOSURE')});expect(incomplete).toMatchObject({result:'INCOMPLETE',missing_evidence:['AUTHORITY_EVIDENCE'],failures:['SECURITY_COMPOSITION_AUTHORITY_REQUIRED']});expect(incomplete).not.toHaveProperty('composition');expect(JSON.stringify(incomplete)).not.toMatch(/composition_(id|digest)/);});
	it('verifies exact quotation authority and denies contradictory authority',async()=>{const good=await composeSecurityEvidenceV1(withAuthority(await fixture('CUSTOMER_QUOTATION_DISCLOSURE')));expect(good.result).toBe('VERIFIED');expect(good.composition).toBeDefined();for(const patch of [{authority_proof_digest:''},{oag_actor_id:'wrong'},{principal_id:'wrong'},{tenant_id:'wrong'},{company_id:'wrong'},{purpose:'LANGUAGE_REFINEMENT'},{projection_digest:'wrong'}])expect((await composeSecurityEvidenceV1(withAuthority(await fixture('CUSTOMER_QUOTATION_DISCLOSURE'),patch))).result).toBe('DENIED');});
	it('prioritizes contradiction over missing evidence',async()=>{const x=await fixture();const r=await composeSecurityEvidenceV1({...x,pt_admissions:[],attempts:[{...x.attempts[0],request_id:'wrong'}]});expect(r.result).toBe('DENIED');expect(r.missing_evidence).toContain('PT_ADMISSION');expect(r).not.toHaveProperty('composition');});
	it('distinguishes missing from mismatched PT admission and authoritative binding',async()=>{const x=await fixture();expect((await composeSecurityEvidenceV1({...x,pt_admissions:[]})).result).toBe('INCOMPLETE');expect((await composeSecurityEvidenceV1({...x,pt_admissions:[{...x.pt_admissions[0],oks_decision_id:'wrong'}]})).result).toBe('DENIED');expect((await composeSecurityEvidenceV1({...x,authoritative_runtime_bindings:[]})).result).toBe('INCOMPLETE');expect((await composeSecurityEvidenceV1({...x,authoritative_runtime_bindings:[{...x.authoritative_runtime_bindings[0],binding_digest:'0'.repeat(64)}]})).result).toBe('DENIED');});
	it('denies consistently forged cross-artifact binding digests',async()=>{const x=await fixture(),forged='0'.repeat(64);const r=await composeSecurityEvidenceV1({...x,pt_admissions:[{...x.pt_admissions[0],runtime_binding_digest:forged}],credential_evidence:[{...x.credential_evidence[0],runtime_binding_digest:forged}],attempts:[{...x.attempts[0],runtime_binding_digest:forged}]});expect(r.result).toBe('DENIED');expect(r.failures).toContain('SECURITY_COMPOSITION_RUNTIME_BINDING_DIGEST_MISMATCH');});
	it('distinguishes missing and substituted credential evidence',async()=>{const x=await fixture();expect((await composeSecurityEvidenceV1({...x,credential_evidence:[]})).result).toBe('INCOMPLETE');expect((await composeSecurityEvidenceV1({...x,credential_evidence:[{...x.credential_evidence[0],credential_reference:'secret://wrong'}]})).result).toBe('DENIED');});
	it('distinguishes missing and substituted success or failed transport',async()=>{const x=await fixture();expect((await composeSecurityEvidenceV1({...x,transport_evidence:[]})).result).toBe('INCOMPLETE');expect((await composeSecurityEvidenceV1({...x,transport_evidence:[{...x.transport_evidence[0],model:'wrong'}]})).result).toBe('DENIED');const failed={...x,attempts:[{...x.attempts[0],outcome:'TRANSPORT_FAILED',failure_class:'TECHNICAL'}],transport_evidence:[{...x.transport_evidence[0],status:'FAILED',response_digest:undefined,failure_code:'COGNITIVE_PROVIDER_FAILURE'}]} as any;expect((await composeSecurityEvidenceV1(failed)).result).toBe('VERIFIED');expect((await composeSecurityEvidenceV1({...failed,transport_evidence:[]})).result).toBe('INCOMPLETE');});
	it('denies fabricated transport on pre-transport outcomes',async()=>{const x=await fixture();for(const outcome of ['GOVERNANCE_DENIED','CONFIGURATION_FAILED'])expect((await composeSecurityEvidenceV1({...x,attempts:[{...x.attempts[0],outcome,failure_class:outcome==='GOVERNANCE_DENIED'?'GOVERNANCE':'CONFIGURATION'}] as any})).result).toBe('DENIED');});
	it('validates technical fallback and derives completed-after-fallback',async()=>{const x=await fixture(),a={...x.attempts[0],attempt_id:'attempt:a',sequence:0,outcome:'TRANSPORT_FAILED',failure_class:'TECHNICAL',transport_evidence_id:'transport:a',completed_at:T.transport},b={...x.attempts[0],attempt_id:'attempt:b',sequence:1,predecessor_attempt_id:'attempt:a',started_at:T.transport},ta={...x.transport_evidence[0],evidence_id:'transport:a',status:'FAILED',response_digest:undefined,failure_code:'COGNITIVE_PROVIDER_FAILURE'},f:any={lineage_id:'fallback:1',predecessor_attempt_id:'attempt:a',successor_attempt_id:'attempt:b',reason:'TECHNICAL_FAILURE',linked_at:T.transport,correlation_id:'correlation:1'};const good=await composeSecurityEvidenceV1({...x,attempts:[b,a] as any,transport_evidence:[x.transport_evidence[0],ta] as any,fallback_edges:[f]});expect(good.result).toBe('VERIFIED');expect(good.composition?.final_outcome).toBe('COMPLETED_AFTER_TECHNICAL_FALLBACK');expect(good.composition?.attempts).toHaveLength(2);expect((await composeSecurityEvidenceV1({...x,attempts:[b,a] as any,transport_evidence:[x.transport_evidence[0],ta] as any,fallback_edges:[]})).result).toBe('INCOMPLETE');for(const bad of [{...f,predecessor_attempt_id:'attempt:b',successor_attempt_id:'attempt:a'},{...f,successor_attempt_id:'attempt:a'},{...f,predecessor_attempt_id:'orphan'}])expect((await composeSecurityEvidenceV1({...x,attempts:[b,a] as any,transport_evidence:[x.transport_evidence[0],ta] as any,fallback_edges:[bad]})).result).toBe('DENIED');});
	it('is deterministic across input ordering and content-free',async()=>{const x=await fixture(),one=await composeSecurityEvidenceV1({...x,causal_lineage:['z','a']}),two=await composeSecurityEvidenceV1({...x,causal_lineage:['a','z'],pt_admissions:[...x.pt_admissions].reverse(),attempts:[...x.attempts].reverse()});expect(one.composition?.composition_digest).toBe(two.composition?.composition_digest);expect(JSON.stringify(one)).not.toMatch(/prompt|projection_body|authorization_header|credential_secret|provider_response|source_document|business_payload/i);});
});
