import { createHash, randomUUID } from "node:crypto";
import { deepCopyAndFreeze } from "../knowledge.projection.guard.v1";
import type { CognitiveAdvisoryResponseV1,CognitiveProviderV1,CognitiveTransportEvidenceRepositoryV1,CognitiveTransportEvidenceV1,SealedCognitiveExposureV1 } from "./cognitive.transport.contracts.v1";
import { CognitiveTransportError } from "./cognitive.transport.contracts.v1";
import { verifySealedCognitiveExposureV1 } from "./cognitive.exposure.seal.v1";
const digest=(s:string)=>createHash("sha256").update(s,"utf8").digest("hex");
const INSTRUCTION="Provide advisory analysis only. Return concise plain text or the requested JSON shape. Do not make decisions or authorize execution.";
export interface CognitiveTransportDependenciesV1{readonly fetch:typeof fetch;readonly evidence:CognitiveTransportEvidenceRepositoryV1;readonly now:()=>string;}
export class CognitiveTransportMediatorV1{
 constructor(private readonly d:CognitiveTransportDependenciesV1){}
 async dispatch(input:{readonly sealed:SealedCognitiveExposureV1;readonly provider:CognitiveProviderV1;readonly model:string;readonly api_key:string;readonly max_tokens?:number;readonly temperature?:number;readonly runtime_governance_references?:readonly string[];}):Promise<CognitiveAdvisoryResponseV1>{
  const s=input?.sealed;if(!s)throw new CognitiveTransportError("COGNITIVE_EXPOSURE_REQUIRED");verifySealedCognitiveExposureV1(s,input.provider,input.model);if(!input.api_key)throw new CognitiveTransportError("COGNITIVE_PROVIDER_FAILURE");
  if(!await this.d.evidence.reserve(s.eligibility.consumption_id,input.provider,this.d.now()))throw new CognitiveTransportError("COGNITIVE_FANOUT_NOT_ADMITTED");
  const body=this.body(input.provider,input.model,s.canonical_projection,input.max_tokens,input.temperature),wire=JSON.stringify(body);if(wire.length>300000)throw new CognitiveTransportError("COGNITIVE_REQUEST_TOO_LARGE");const requestDigest=digest(wire),at=this.d.now();
  try{const response=await this.d.fetch(this.url(input.provider),{method:"POST",headers:this.headers(input.provider,input.api_key),body:wire,redirect:"error"});const raw=await response.text();if(raw.length>262144)throw new CognitiveTransportError("COGNITIVE_RESPONSE_TOO_LARGE");if(!response.ok)throw new CognitiveTransportError("COGNITIVE_PROVIDER_FAILURE");const parsed=this.parse(input.provider,raw);const text=this.text(input.provider,parsed);if(typeof text!=="string"||text.length===0||text.length>65536)throw new CognitiveTransportError("COGNITIVE_PROVIDER_RESPONSE_INVALID");const responseDigest=digest(text),e=this.evidence(s,input.provider,input.model,at,requestDigest,"SUCCEEDED",responseDigest,undefined,input.runtime_governance_references);await this.d.evidence.append(e);return deepCopyAndFreeze({version:1,provider:input.provider,model:input.model,text,response_digest:responseDigest,usage:this.usage(input.provider,parsed),evidence:e,advisory_only:true}) as CognitiveAdvisoryResponseV1;
  }catch(error){const code=error instanceof CognitiveTransportError?error.code:"COGNITIVE_PROVIDER_FAILURE";const e=this.evidence(s,input.provider,input.model,at,requestDigest,"FAILED",undefined,code,input.runtime_governance_references);try{await this.d.evidence.append(e);}catch{throw new CognitiveTransportError("COGNITIVE_TRANSPORT_EVIDENCE_FAILED");}throw new CognitiveTransportError(code);}
 }
 private url(p:CognitiveProviderV1){return p==="openai"?"https://api.openai.com/v1/responses":p==="anthropic"?"https://api.anthropic.com/v1/messages":"https://openrouter.ai/api/v1/chat/completions";}
 private headers(p:CognitiveProviderV1,key:string):HeadersInit{return p==="anthropic"?{"x-api-key":key,"anthropic-version":"2023-06-01","content-type":"application/json"}:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"};}
 private body(p:CognitiveProviderV1,model:string,projection:string,max=700,temperature=.2){if(p==="openai")return{model,input:[{role:"system",content:[{type:"text",text:INSTRUCTION}]},{role:"user",content:[{type:"text",text:projection}]}],temperature,max_output_tokens:max};if(p==="anthropic")return{model,system:INSTRUCTION,max_tokens:max,temperature,messages:[{role:"user",content:projection}]};return{model,messages:[{role:"system",content:INSTRUCTION},{role:"user",content:projection}],temperature,max_tokens:max};}
 private parse(_p:CognitiveProviderV1,raw:string):any{try{return JSON.parse(raw);}catch{throw new CognitiveTransportError("COGNITIVE_PROVIDER_RESPONSE_INVALID");}}
 private text(p:CognitiveProviderV1,x:any):unknown{return p==="openai"?x.output_text??x.output?.[0]?.content?.[0]?.text:p==="anthropic"?x.content?.[0]?.text:x.choices?.[0]?.message?.content;}
 private usage(p:CognitiveProviderV1,x:any){const u=x?.usage;if(!u)return undefined;return p==="openrouter"?{input_tokens:u.prompt_tokens,output_tokens:u.completion_tokens}:{input_tokens:u.input_tokens,output_tokens:u.output_tokens};}
 private evidence(s:SealedCognitiveExposureV1,p:CognitiveProviderV1,model:string,at:string,request_digest:string,status:"SUCCEEDED"|"FAILED",response_digest?:string,failure_code?:any,runtimeRefs:readonly string[]=[]):CognitiveTransportEvidenceV1{return deepCopyAndFreeze({version:1,evidence_id:`cognitive-transport-evidence:${randomUUID()}`,decision_id:s.eligibility.decision_id,binding_id:s.eligibility.binding_id,consumption_id:s.eligibility.consumption_id,projection_digest:s.projection_digest,request_digest,provider:p,model,provider_deployment_class:s.provider_target_class,purpose:s.purpose,region:s.region,retention:s.retention,dispatched_at:at,status,...(response_digest?{response_digest}:{}),...(failure_code?{failure_code}:{}),causal_references:[...s.causal_references,...runtimeRefs]}) as CognitiveTransportEvidenceV1;}
}
