import { createHash } from "node:crypto";
import type { KnowledgeProjectionManifestV1 } from "../knowledge.exposure.contracts.v1";
import { knowledgeProjectionDigestV1, deepCopyAndFreeze } from "../knowledge.projection.guard.v1";
import type { KnowledgeExposureEligibilityV1 } from "../persistence";
import type { CognitiveProviderV1, SealedCognitiveExposureV1 } from "./cognitive.transport.contracts.v1";
import { CognitiveTransportError } from "./cognitive.transport.contracts.v1";
const hash=(s:string)=>createHash("sha256").update(s,"utf8").digest("hex");
function canonical(v:unknown):string{if(v===null||typeof v==="boolean"||typeof v==="number")return JSON.stringify(v);if(typeof v==="string")return JSON.stringify(v);if(Array.isArray(v))return `[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return `{${Object.keys(v as object).sort().map(k=>`${JSON.stringify(k)}:${canonical((v as any)[k])}`).join(",")}}`;throw new CognitiveTransportError("COGNITIVE_ELIGIBILITY_INVALID");}
export function sealCognitiveExposureV1(input:{readonly eligibility:KnowledgeExposureEligibilityV1;readonly manifest:KnowledgeProjectionManifestV1;readonly projection:Readonly<Record<string,unknown>>;readonly provider:CognitiveProviderV1;readonly provider_identity:string;readonly model:string;}):SealedCognitiveExposureV1{
 const e=input?.eligibility,m=input?.manifest;if(!e||!m||!Object.isFrozen(e)||e.operation!=="COGNITIVE_EXPOSURE")throw new CognitiveTransportError(e?.operation?"COGNITIVE_ELIGIBILITY_OPERATION_MISMATCH":"COGNITIVE_EXPOSURE_REQUIRED");
 const manifestId=`${m.schema_id}@${m.schema_version}`;if(manifestId!==e.manifest_id||knowledgeProjectionDigestV1(m)!==e.projection_digest)throw new CognitiveTransportError("COGNITIVE_MANIFEST_MISMATCH");
 if(!Object.isFrozen(e.knowledge_digests)||e.knowledge_digests.length===0)throw new CognitiveTransportError("COGNITIVE_REFERENCE_SET_MISMATCH");
 if(e.target_class!=="SHARED_REMOTE_PROVIDER")throw new CognitiveTransportError("COGNITIVE_ELIGIBILITY_TARGET_MISMATCH");
 if(!e.target_identity||e.target_identity!==input.provider_identity)throw new CognitiveTransportError("COGNITIVE_PROVIDER_NOT_ADMITTED");
 if(input.provider_identity!==`${input.provider}:${input.model}`)throw new CognitiveTransportError("COGNITIVE_MODEL_NOT_ADMITTED");
 const allowed=new Set(m.included_fields.map(f=>f.field));const keys=Object.keys(input.projection);if(keys.some(k=>!allowed.has(k))||keys.length!==allowed.size)throw new CognitiveTransportError("COGNITIVE_MANIFEST_MISMATCH");
 const bytes=canonical(input.projection);if(bytes.length>262144)throw new CognitiveTransportError("COGNITIVE_REQUEST_TOO_LARGE");
 return deepCopyAndFreeze({version:1,eligibility:e,manifest:m,manifest_id:manifestId,projection_digest:e.projection_digest,knowledge_digests:e.knowledge_digests,canonical_projection:bytes,canonical_projection_digest:hash(bytes),purpose:e.purpose,provider:input.provider,provider_target_class:e.target_class,provider_identity:input.provider_identity,model:input.model,region:e.target_region,retention:e.requested_retention,correlation_id:e.correlation_id,causal_references:e.causal_references}) as SealedCognitiveExposureV1;
}
export function verifySealedCognitiveExposureV1(s:SealedCognitiveExposureV1,provider:CognitiveProviderV1,model:string){if(!s||!Object.isFrozen(s)||!Object.isFrozen(s.eligibility))throw new CognitiveTransportError("COGNITIVE_ELIGIBILITY_INVALID");if(s.provider!==provider)throw new CognitiveTransportError("COGNITIVE_PROVIDER_NOT_ADMITTED");if(s.model!==model||s.provider_identity!==`${provider}:${model}`)throw new CognitiveTransportError("COGNITIVE_MODEL_NOT_ADMITTED");if(s.eligibility.target_identity!==s.provider_identity||s.eligibility.target_class!=="SHARED_REMOTE_PROVIDER")throw new CognitiveTransportError("COGNITIVE_ELIGIBILITY_TARGET_MISMATCH");if(s.eligibility.consumption_id.length<1)throw new CognitiveTransportError("COGNITIVE_ELIGIBILITY_CONSUMPTION_MISMATCH");if(hash(s.canonical_projection)!==s.canonical_projection_digest)throw new CognitiveTransportError("COGNITIVE_PROJECTION_MUTATED");if(s.manifest_id!==s.eligibility.manifest_id)throw new CognitiveTransportError("COGNITIVE_MANIFEST_MISMATCH");if(s.projection_digest!==s.eligibility.projection_digest)throw new CognitiveTransportError("COGNITIVE_PROJECTION_DIGEST_MISMATCH");if(JSON.stringify(s.knowledge_digests)!==JSON.stringify(s.eligibility.knowledge_digests))throw new CognitiveTransportError("COGNITIVE_REFERENCE_SET_MISMATCH");if(s.purpose!==s.eligibility.purpose)throw new CognitiveTransportError("COGNITIVE_ELIGIBILITY_PURPOSE_MISMATCH");if(s.region!==s.eligibility.target_region)throw new CognitiveTransportError("COGNITIVE_ELIGIBILITY_REGION_MISMATCH");if(s.retention!==s.eligibility.requested_retention)throw new CognitiveTransportError("COGNITIVE_ELIGIBILITY_RETENTION_MISMATCH");}
