import { describe,expect,it } from "vitest";
import config from "../../../training/interpretation/gcc4k/experiment.config.json";
import kaggle from "../../../training/interpretation/gcc4k/gcc4k_kaggle.ipynb?raw";
import training from "../../../training/interpretation/gcc4k/train_targeted_student_v02.py?raw";

describe("GCC-4K Kaggle execution portability",()=>{
  it("isolates exactly one GPU before torch initialization and enables no distributed training",()=>{expect(kaggle.indexOf("CUDA_VISIBLE_DEVICES']='0")).toBeLessThan(kaggle.indexOf("import torch"));expect(kaggle).toContain("torch.cuda.device_count()==1");expect(kaggle).not.toMatch(/torchrun|DistributedDataParallel|\bDDP\b|CUDA_VISIBLE_DEVICES[^\n]*0,1/);});
  it("uses the configurable Kaggle persistence root and shared recovery runner",()=>{expect(kaggle).toContain("/kaggle/working/PlannerAgent/GCC4K");expect(kaggle).toContain("PLANNERAGENT_GCC4K_PERSIST_ROOT");expect(kaggle).toContain("scripts/train_targeted_student_v02.py");expect(kaggle).not.toContain("def training_action");expect(training).toContain("from gcc4k_recovery import");});
  it("pins the same experiment and recovery input",()=>{expect(config).toMatchObject({candidate_id:"PA-INTERPRETATION-STUDENT-v0.2",corpus_id:"PA-INTERPRETATION-CURRICULUM-v2",base_model:"Qwen/Qwen3-0.6B-Base",base_revision:"da87bfb608c14b7cf20ba1ce41287e8de496c0cd",transformers_version:"4.51.3",epochs:3,learning_rate:.0002,batch_size:2,gradient_accumulation_steps:4,max_sequence_length:384,lora_rank:8,lora_alpha:16,lora_dropout:.05,warmup_ratio:.05,scheduler:"cosine",optimizer:"adamw_torch",seed:4701});expect(kaggle).toContain("ab13d4b3bc7c6d19b8f83f0fc5e764687dde8acdc29239ff8d4782750e80205c");expect(kaggle).toContain("sha256:bd1b19fc6733cca6622051e30ac03dc3cbac3a602997894c7b4a1733467f3619");expect(kaggle).toContain("scripts/train_targeted_student_v02.py");expect(training).toContain('SCRIPTS/"experiment.config.json"');});
  it("exposes the adapter before evaluation and final result afterward",()=>{const train=kaggle.indexOf("'--phase','train'");const adapter=kaggle.indexOf("ADAPTER_READY_FOR_KAGGLE_OUTPUT_PRESERVATION");const evaluate=kaggle.indexOf("'--phase','evaluate'");const result=kaggle.indexOf("FINAL_RESULT_READY_FOR_KAGGLE_OUTPUT_PRESERVATION");expect(train).toBeGreaterThan(-1);expect(train).toBeLessThan(adapter);expect(adapter).toBeLessThan(evaluate);expect(evaluate).toBeLessThan(result);});
  it("records Kaggle provenance without changing identity",()=>{expect(kaggle).toContain("'execution_surface':'KAGGLE'");expect(kaggle).toContain("'visible_gpu_count':torch.cuda.device_count()");expect(kaggle).toContain("state/'kaggle.environment.json'");expect(training).not.toContain("PLANNERAGENT_EXECUTION_SURFACE");});
});
