import { createHash } from "node:crypto";
import { describe,expect,it } from "vitest";
import trainNotebook from "../../../training/interpretation/gcc4k/gcc4k_kaggle_train.ipynb?raw";
import evaluateNotebook from "../../../training/interpretation/gcc4k/gcc4k_kaggle_evaluate.ipynb?raw";
import { GCC4K_CORPUS_DIGEST,GCC4K_EXPLODED_REQUIRED,GCC4K_RECOVERY_ZIP_SHA256,safeGcc4kPayloadPathV1,selectGcc4kKaggleInputV1,selectGcc4kManifestBoundAdapterV1,verifyGcc4kPayloadV1 } from "../../../training/interpretation/gcc4k/gcc4k.kaggle.input.policy";

const bytes=new TextEncoder().encode("x");const hash=createHash("sha256").update(bytes).digest("hex");
const entries=new Map(GCC4K_EXPLODED_REQUIRED.filter(path=>path!=="SHA256SUMS.txt").map(path=>[path,bytes] as const));
const sums=[...entries].map(([path])=>`${hash}  ${path}`).join("\n")+"\n";
describe("GCC-4K Kaggle committed runs",()=>{
  it("selects one exploded input before ZIP and requires unique input",()=>{expect(selectGcc4kKaggleInputV1(["/exploded"],["/bundle.zip"]).mode).toBe("EXPLODED_KAGGLE_DATASET");expect(selectGcc4kKaggleInputV1([], ["/bundle.zip"])).toMatchObject({mode:"RECOVERY_ZIP",outer_zip_digest:GCC4K_RECOVERY_ZIP_SHA256});expect(()=>selectGcc4kKaggleInputV1([],[])).toThrow("GCC4K_INPUT_NOT_FOUND");expect(()=>selectGcc4kKaggleInputV1(["a","b"],[])).toThrow("MULTIPLE_GCC4K_EXPLODED_INPUTS");});
  it("verifies every payload and fails closed on missing files, hashes, unsafe paths, and corpus drift",()=>{expect(verifyGcc4kPayloadV1(entries,sums,GCC4K_CORPUS_DIGEST)).toBe(entries.size);expect(()=>verifyGcc4kPayloadV1(new Map([...entries].slice(1)),sums,GCC4K_CORPUS_DIGEST)).toThrow("GCC4K_PAYLOAD_MISSING");expect(()=>verifyGcc4kPayloadV1(entries,sums.replace(hash,"0".repeat(64)),GCC4K_CORPUS_DIGEST)).toThrow("GCC4K_PAYLOAD_HASH_MISMATCH");expect(safeGcc4kPayloadPathV1("a/../secret")).toBe(false);expect(safeGcc4kPayloadPathV1("corpus\\train.jsonl")).toBe(false);expect(()=>verifyGcc4kPayloadV1(entries,sums,"wrong")).toThrow("GCC4K_CORPUS_DIGEST_MISMATCH");});
  it("makes train a fresh-kernel, single-GPU, train-only committed run",()=>{expect(trainNotebook).toContain("SAVE VERSION → SAVE & RUN ALL");expect(trainNotebook.indexOf("CUDA_VISIBLE_DEVICES']='0")).toBeLessThan(trainNotebook.indexOf("import torch"));expect(trainNotebook).toContain("torch.cuda.device_count()==1");expect(trainNotebook).toContain("'--phase','train'");expect(trainNotebook).not.toContain("'--phase','evaluate'");expect(trainNotebook).not.toContain("'--phase','all'");expect(trainNotebook.indexOf("'--phase','train'")).toBeLessThan(trainNotebook.indexOf("KAGGLE_COMMITTED_TRAIN_OUTPUT_READY"));expect(trainNotebook).toContain("/kaggle/working/PA-INTERPRETATION-STUDENT-v0.2-ADAPTER-GCC4K.zip");});
  it("makes evaluate a verified-adapter, evaluation-only committed run",()=>{expect(evaluateNotebook).toContain("SAVE VERSION → SAVE & RUN ALL");expect(evaluateNotebook.indexOf("CUDA_VISIBLE_DEVICES']='0")).toBeLessThan(evaluateNotebook.indexOf("import torch"));expect(evaluateNotebook).toContain("PA-INTERPRETATION-STUDENT-v0.2-ADAPTER-GCC4K.zip");expect(evaluateNotebook).toContain("valid_final_adapter");expect(evaluateNotebook).toContain("'--phase','evaluate'");expect(evaluateNotebook).not.toContain("'--phase','train'");expect(evaluateNotebook).not.toContain("'--phase','all'");expect(evaluateNotebook).not.toContain("trainer.train(");expect(evaluateNotebook).toContain("/kaggle/working/PA-INTERPRETATION-STUDENT-v0.2-GCC4K.zip");expect(evaluateNotebook).toContain("KAGGLE_COMMITTED_EVALUATION_OUTPUT_READY");});
  it("selects one manifest-bound adapter and permits identical duplicate copies deterministically",()=>{const manifest=["/input/run/PA-INTERPRETATION-STUDENT-v0.2-TRAIN-RUN.json"];expect(selectGcc4kManifestBoundAdapterV1(manifest,"same",[{path:"/input/run/adapter.zip",sha256:"same"}]).adapter_selected_path).toBe("/input/run/adapter.zip");const duplicates=[{path:"/input/nested/adapter.zip",sha256:"same"},{path:"/input/run/adapter.zip",sha256:"same"}];expect(selectGcc4kManifestBoundAdapterV1(manifest,"same",duplicates)).toMatchObject({adapter_candidate_count:2,adapter_matching_count:2,adapter_selected_path:"/input/run/adapter.zip",adapter_input_sha256:"same"});expect(selectGcc4kManifestBoundAdapterV1(manifest,"same",duplicates.reverse()).adapter_selected_path).toBe("/input/run/adapter.zip");const noSibling=[{path:"/input/z/adapter.zip",sha256:"same"},{path:"/input/a/adapter.zip",sha256:"same"}];expect(selectGcc4kManifestBoundAdapterV1(manifest,"same",noSibling).adapter_selected_path).toBe("/input/a/adapter.zip");expect(selectGcc4kManifestBoundAdapterV1(manifest,"same",noSibling.reverse()).adapter_selected_path).toBe("/input/a/adapter.zip");});
  it("excludes nonmatching copies and fails closed for invalid handoffs",()=>{const manifest=["/input/run/train.json"];expect(selectGcc4kManifestBoundAdapterV1(manifest,"bound",[{path:"/z.zip",sha256:"wrong"},{path:"/a.zip",sha256:"bound"}]).adapter_selected_path).toBe("/a.zip");expect(()=>selectGcc4kManifestBoundAdapterV1(manifest,"bound",[{path:"/a.zip",sha256:"wrong"}])).toThrow("PRESERVED_V02_ADAPTER_NOT_FOUND");expect(()=>selectGcc4kManifestBoundAdapterV1([],"bound",[])).toThrow("TRAIN_RUN_MANIFEST_NOT_FOUND");expect(()=>selectGcc4kManifestBoundAdapterV1(["a","b"],"bound",[])).toThrow("MULTIPLE_TRAIN_RUN_MANIFESTS");expect(()=>selectGcc4kManifestBoundAdapterV1(manifest,"bound",[{path:"/input/run/a.zip",sha256:"bound"},{path:"/input/run/b.zip",sha256:"bound"}])).toThrow("MULTIPLE_MANIFEST_SIBLING_ADAPTERS");});
  it("documents TRAIN Version as the only evaluate input and records handoff evidence",()=>{expect(evaluateNotebook).toContain("Attach ONLY the successful committed TRAIN Version output");expect(evaluateNotebook).toContain("do not attach recovery input separately");for(const field of ["adapter_candidate_count","adapter_matching_count","adapter_selected_path","adapter_input_sha256"])expect(evaluateNotebook).toContain(field);});
  it("freezes input and experiment identity in both notebooks",()=>{for(const notebook of [trainNotebook,evaluateNotebook]){expect(notebook).toContain(GCC4K_CORPUS_DIGEST);expect(notebook).toContain("da87bfb608c14b7cf20ba1ce41287e8de496c0cd");expect(notebook).toContain("scripts/experiment.config.json");expect(notebook).toContain("EXPLODED_KAGGLE_DATASET");expect(notebook).toContain("RECOVERY_ZIP");}});
});
