import { describe,expect,it } from "vitest";
import { decideGcc4kTrainingActionV1,reusableGcc4kEvaluationV1,safeGcc4kResultEntriesV1,validGcc4kFinalAdapterV1,type Gcc4kIdentityV1,type Gcc4kPersistedSnapshotV1 } from "../../../training/interpretation/gcc4k/gcc4k.recovery.policy";
import notebook from "../../../training/interpretation/gcc4k/gcc4k_colab.ipynb?raw";
import training from "../../../training/interpretation/gcc4k/train_targeted_student_v02.py?raw";
const identity:Gcc4kIdentityV1={candidate_id:"PA-INTERPRETATION-STUDENT-v0.2",candidate_version:"0.2",base_model:"Qwen/Qwen3-0.6B-Base",base_revision:"da87bfb608c14b7cf20ba1ce41287e8de496c0cd",corpus_id:"PA-INTERPRETATION-CURRICULUM-v2",corpus_version:"2",corpus_digest:"sha256:bd1b19fc6733cca6622051e30ac03dc3cbac3a602997894c7b4a1733467f3619",training_config_digest:"sha256:config",seed:4701,lora_rank:8,lora_alpha:16,lora_dropout:.05};
const adapterFiles=["adapter/adapter_model.safetensors","adapter/adapter_config.json","candidate.manifest.json","training.config.json","training.metrics.json","environment.manifest.json"];
const checkpointFiles=["adapter_model.safetensors","adapter_config.json","optimizer.pt","scheduler.pt","trainer_state.json","rng_state.pth","checkpoint.manifest.json"];
const snapshot=(overrides:Partial<Gcc4kPersistedSnapshotV1>={}):Gcc4kPersistedSnapshotV1=>({complete:true,identity,hashes_valid:true,files:adapterFiles,...overrides});
describe("GCC-4K recovery persistence",()=>{
  it("recognizes final adapters only with COMPLETE, exact identity, required files, and valid hashes",()=>{expect(validGcc4kFinalAdapterV1(snapshot(),identity)).toBe(true);expect(validGcc4kFinalAdapterV1(snapshot({complete:false}),identity)).toBe(false);expect(validGcc4kFinalAdapterV1(snapshot({hashes_valid:false}),identity)).toBe(false);expect(validGcc4kFinalAdapterV1(snapshot({files:adapterFiles.slice(1)}),identity)).toBe(false);});
  it.each(["base_revision","corpus_digest","training_config_digest"] as const)("rejects mismatched %s",(key)=>{const wrong={...identity,[key]:"wrong"};expect(validGcc4kFinalAdapterV1(snapshot({identity:wrong}),identity)).toBe(false);});
  it("selects latest valid checkpoint and rejects partial/corrupt checkpoints",()=>{const values=[snapshot({files:checkpointFiles,checkpoint_step:1125}),snapshot({files:checkpointFiles,checkpoint_step:2250,complete:false}),snapshot({files:checkpointFiles,checkpoint_step:3375,hashes_valid:false})];expect(decideGcc4kTrainingActionV1(undefined,values,identity)).toEqual({action:"RESUME_FROM_CHECKPOINT",checkpoint_step:1125});});
  it("chooses skip, resume, and fresh actions in the required order",()=>{expect(decideGcc4kTrainingActionV1(snapshot(),[snapshot({files:checkpointFiles,checkpoint_step:3375})],identity)).toEqual({action:"SKIP_ALREADY_COMPLETE"});expect(decideGcc4kTrainingActionV1(undefined,[snapshot({files:checkpointFiles,checkpoint_step:2250})],identity)).toEqual({action:"RESUME_FROM_CHECKPOINT",checkpoint_step:2250});expect(decideGcc4kTrainingActionV1(undefined,[],identity)).toEqual({action:"FRESH_TRAIN"});});
  it("skips only complete matching evaluation results",()=>{const value=snapshot({files:["result.json","evaluation.manifest.json","SHA256SUMS.txt"],adapter_digest:"adapter",dataset_digest:"dataset",evaluation_config_digest:"eval"});expect(reusableGcc4kEvaluationV1(value,identity,"adapter","dataset","eval")).toBe(true);expect(reusableGcc4kEvaluationV1({...value,complete:false},identity,"adapter","dataset","eval")).toBe(false);expect(reusableGcc4kEvaluationV1({...value,hashes_valid:false},identity,"adapter","dataset","eval")).toBe(false);expect(reusableGcc4kEvaluationV1(value,identity,"wrong","dataset","eval")).toBe(false);});
  it("excludes base weights, checkpoints, and credential-like files from result ZIP",()=>{expect(safeGcc4kResultEntriesV1(["final-adapter/adapter/adapter_model.safetensors","evaluation/v02.blind/result.json"])).toBe(true);expect(safeGcc4kResultEntriesV1(["model.safetensors"])).toBe(false);expect(safeGcc4kResultEntriesV1(["checkpoints/checkpoint-1/optimizer.pt"])).toBe(false);expect(safeGcc4kResultEntriesV1(["api_key.json"])).toBe(false);});
  it("persists adapter before evaluation and mounts Drive before training",()=>{expect(training.indexOf("persist_final(")).toBeLessThan(training.indexOf("evaluate_phase("));expect(training).toContain("persistent_adapter_reloaded");expect(training).toContain("--phase");const drive=notebook.indexOf("drive.mount('/content/drive')");const train=notebook.indexOf("--phase train");const evaluate=notebook.indexOf("--phase evaluate");expect(drive).toBeGreaterThan(-1);expect(drive).toBeLessThan(train);expect(train).toBeLessThan(evaluate);});
});
