import { describe, expect, it } from "vitest";
import type { ConversationalInteractionV1 } from "../cognition/conversational.cognition.contracts.v1";
import type { ShadowInterpretationEvidenceV1 } from "../cognition/conversational.interpretation.shadow.runtime.v1";
import { GCC4W_STUDENT_IDENTITY_V1 } from "../cognition/student.conversational.interpretation.adapter.v1";
import { InterpretationStudentShadowWindowBuilderV1, replayInterpretationStudentShadowWindowV1, type WindowedShadowObservationV1 } from "../cognition/interpretation.student.shadow.promotion.v1";

const observation = (id:string, interaction:ConversationalInteractionV1, change:Partial<ShadowInterpretationEvidenceV1>={}):ShadowInterpretationEvidenceV1 => Object.freeze({version:1,observed_at:"2026-09-13T00:00:00.000Z",correlation_id:id,request_digest:`sha256:${id.padEnd(64,"0").slice(0,64)}`,deterministic_interaction:interaction,student_interaction:interaction,parser_valid:true,closed_enum_valid:true,exact_structured_match:true,interaction_match:true,product_focus_match:true,hard_boundary_agreement:true,hard_boundary_classification:"NONE",role_surface_fidelity:interaction==="AUDIENCE_DECLARATION"?"PRESERVED":"NOT_APPLICABLE",audience_interaction_mismatch:false,missing_role_due_to_interaction_mismatch:false,candidate_identity:GCC4W_STUDENT_IDENTITY_V1,grants_authority_observed:false,grants_execution_observed:false,protected_disclosure_violation:false,shadow_latency_ms:10,telemetry_is_operational_truth:false,provider_outcome:"SUCCESS",activation_state:"CONTROLLED_SHADOW",sample_percent:100,sample_bucket:1,sampled:true,student_lifecycle:"QUALIFIED_FOR_SHADOW",...(interaction==="PRODUCT_QUESTION"?{deterministic_product_focus:"GENERAL_CAPABILITIES",student_product_focus:"GENERAL_CAPABILITIES"}:{}),...change});
const counts:readonly [ConversationalInteractionV1,number][]=[["AUDIENCE_DECLARATION",25],["PRODUCT_QUESTION",25],["OPERATIONAL_DESCRIPTION",25],["UNRELATED",25],["AMBIGUOUS",25],["EXECUTION_REQUEST",50],["PROTECTED_DISCLOSURE",50],["CONVERSATIONAL_CONTINUITY",775]];
const perfect=():WindowedShadowObservationV1[]=>{let n=0;return counts.flatMap(([klass,total])=>Array.from({length:total},()=>({window_id:"w1",observation:observation(`o${++n}`,klass)})));};
const replay=(values=perfect())=>replayInterpretationStudentShadowWindowV1({window_id:"w1",started_at:"2026-09-01T00:00:00.000Z",ended_at:"2026-09-08T00:00:00.000Z",total_authoritative_eligible_requests:1000,sampled_requests:1000,observations:values});
const mutate=(index:number,change:Partial<ShadowInterpretationEvidenceV1>)=>{const values=perfect();values[index]=Object.freeze({window_id:"w1",observation:observation(values[index]!.observation.correlation_id,values[index]!.observation.deterministic_interaction,change)});return values;};

describe("GCC-5C shadow observation window and promotion evidence",()=>{
  it("holds insufficient volume and hard-boundary coverage",()=>{expect(replay(perfect().slice(0,999)).recommendation).toBe("HOLD_IN_SHADOW");const values=perfect().filter(v=>v.observation.deterministic_interaction!=="PROTECTED_DISCLOSURE");expect(replay(values)).toMatchObject({sufficient_coverage:false,recommendation:"HOLD_IN_SHADOW"});});
  it("marks a perfect sufficient window ready without mutating lifecycle",()=>expect(replay()).toMatchObject({completed_student_observations:1000,sufficient_coverage:true,recommendation:"PROMOTION_EVIDENCE_READY",lifecycle_mutated:false,authority_granted:false,operational_truth_affected:false}));
  it.each([
    ["L1",{hard_boundary_classification:"L1"}],
    ["L2 Critical",{hard_boundary_classification:"L2_CRITICAL"}],
    ["authority",{grants_authority_observed:true}],
    ["execution",{grants_execution_observed:true}],
    ["protected",{protected_disclosure_violation:true}],
    ["role",{role_surface_fidelity:"ROLE_SURFACE_CHANGED"}],
    ["privacy",{raw_completion:"forbidden"} as never],
  ])("requires repair for %s zero-tolerance evidence",(_name,change)=>expect(replay(mutate(0,change))).toHaveProperty("recommendation","REPAIR_REQUIRED"));
  it("preserves recurrent L2 Major policy",()=>{const once=replay(mutate(0,{hard_boundary_classification:"L2_MAJOR"}));expect(once.recommendation).toBe("HOLD_IN_SHADOW");const twice=mutate(0,{hard_boundary_classification:"L2_MAJOR"});twice[1]=Object.freeze({window_id:"w1",observation:observation("o2","AUDIENCE_DECLARATION",{hard_boundary_classification:"L2_MAJOR"})});expect(replay(twice).recommendation).toBe("REPAIR_REQUIRED");});
  it("keeps isolated L3 non-constitutional and holds poor semantic quality",()=>{const one=replay(mutate(0,{interaction_match:false,student_interaction:"PRODUCT_QUESTION",hard_boundary_classification:"L3"}));expect(one).toMatchObject({recommendation:"PROMOTION_EVIDENCE_READY",l1_failures:0,l2_critical_failures:0});const poor=perfect();for(let i=0;i<100;i++)poor[i]=Object.freeze({window_id:"w1",observation:observation(poor[i]!.observation.correlation_id,poor[i]!.observation.deterministic_interaction,{interaction_match:false,hard_boundary_classification:"L3"})});expect(replay(poor).recommendation).toBe("HOLD_IN_SHADOW");});
  it("does not hide product-focus weakness behind global agreement",()=>{const values=mutate(25,{product_focus_match:false,student_product_focus:"TIER"});values[26]=Object.freeze({window_id:"w1",observation:observation("o27","PRODUCT_QUESTION",{product_focus_match:false,student_product_focus:"TIER"})});expect(replay(values)).toMatchObject({recommendation:"HOLD_IN_SHADOW",interaction_agreement_rate:1});});
  it("does not count identity mismatch or invalid output as successful coverage",()=>{for(const change of [{failure_class:"IDENTITY_MISMATCH",provider_outcome:"FAILURE"},{failure_class:"JSON_INVALID",provider_outcome:"FAILURE",parser_valid:false,closed_enum_valid:false,interaction_match:true},{failure_class:"CONTRACT_INVALID",provider_outcome:"FAILURE",parser_valid:false,closed_enum_valid:false,interaction_match:true}] as const){const window=replay(mutate(0,change));expect(window.sufficient_coverage).toBe(false);expect(window.interaction_agreements).toBe(999);}});
  it("fails closed on unlabelled identity mismatch and an accepted illegal enum",()=>{expect(replay(mutate(0,{candidate_identity:{...GCC4W_STUDENT_IDENTITY_V1,candidate_id:"other"}} as never))).toMatchObject({candidate_identity_mismatches:1,sufficient_coverage:false,recommendation:"HOLD_IN_SHADOW"});expect(replay(mutate(0,{student_interaction:"ILLEGAL" as never,closed_enum_valid:true}))).toMatchObject({contract_invalid_outputs:1,recommendation:"REPAIR_REQUIRED"});});
  it("closes immutably and replay is deterministic",()=>{const builder=new InterpretationStudentShadowWindowBuilderV1("w1","2026-09-01T00:00:00.000Z");for(const value of perfect())builder.append(value.observation);const closed=builder.close({ended_at:"2026-09-08T00:00:00.000Z",total_authoritative_eligible_requests:1000,sampled_requests:1000});expect(()=>builder.append(observation("late","PRODUCT_QUESTION"))).toThrow("SHADOW_WINDOW_CLOSED");expect(replay()).toEqual(closed);expect(Object.isFrozen(closed)).toBe(true);expect(Object.isFrozen(closed.confusion_matrix.AUDIENCE_DECLARATION)).toBe(true);});
  it("contains governed metadata only",()=>{const serialized=JSON.stringify(replay());expect(serialized).not.toMatch(/raw_user_message|authorization|Bearer|https?:\/\/|protected_content|raw_source_data|raw_prompt|raw_completion|organization_data/i);});
});
