import {describe,expect,it} from "vitest";
import oodText from "../../../training-artifacts/PA-INTERPRETATION-OOD-BENCHMARK-v1/benchmark.jsonl?raw";
import {CONVERSATIONAL_INTERACTIONS_V1,CONVERSATIONAL_PRODUCT_FOCUSES_V1,parseConversationalInterpretationResultV1} from "../cognition/conversational.cognition.contracts.v1";
import {DECLARED_ROLE_FIDELITY_POLICY_V1} from "../cognition/declared.role.fidelity.policy.v1";
import {CONVERSATIONAL_INTERPRETATION_GOLD_CORPUS_V1} from "../evaluation/conversational.interpretation.gold.corpus.v1";
import {auditInterpretationCurriculumV4SentinelIsolation,auditInterpretationCurriculumV4StyleLeakage,buildInterpretationCurriculumV4,CURRICULUM_V4_SPLITS} from "../learning/curriculum/interpretation.curriculum.v4";
import {buildInterpretationPilotCorpusV1} from "../learning/pilot/interpretation.pilot.corpus.v1";

describe("PA-INTERPRETATION-CURRICULUM-v4 controlled repair",()=>{
 const built=buildInterpretationCurriculumV4();
 it("is deterministic, closed, constitutional, marker-free, and collision-free",()=>{const again=buildInterpretationCurriculumV4();expect(built.items.length).toBeGreaterThanOrEqual(8000);expect(built.items.length).toBeLessThanOrEqual(10000);expect(built.manifest.total_records).toBe(built.items.length);expect(again.manifest.aggregate_corpus_digest).toBe(built.manifest.aggregate_corpus_digest);expect(built.manifest.audits).toEqual({visible_synthetic_identifier_count:0,exact_collision_count:0,normalized_collision_count:0,family_collision_count:0,renderer_cross_split_overlap_count:0,role_span_conflict_count:0,oracle_conflict_count:0,product_focus_rotation_count:0,constitutional_invariant_violations:0});for(const row of built.items){expect(parseConversationalInterpretationResultV1(row.target)).toEqual(row.target);expect(row.target).toMatchObject({interpretation_only:true,requester_content_non_authoritative:true,grants_authority:false,grants_execution:false})}},15000);
 it("keeps families and renderer styles split-exclusive",()=>{for(const key of ["family_id","renderer_family_id"]as const){const memberships=new Map<string,Set<string>>();for(const row of built.items){const splits=memberships.get(row[key])??new Set<string>();splits.add(row.split);memberships.set(row[key],splits)}for(const splits of memberships.values())expect(splits.size).toBe(1)}expect(Object.values(built.manifest.renderer_family_counts)).toEqual([2,2,2,2,2]);expect(CURRICULUM_V4_SPLITS.every(split=>built.bySplit[split].length>0)).toBe(true)});
 it("red-teams renderer artifacts and repeated lexical skeletons",()=>{const audit=auditInterpretationCurriculumV4StyleLeakage(built.items);expect(audit.visible_renderer_identifier_count).toBe(0);expect(audit.generator_only_label_shortcut_count).toBe(0);expect(audit.renderer_families_covering_all_interactions).toBe(audit.renderer_family_count);expect(audit.unique_skeleton_count).toBeGreaterThan(1000);expect(audit.max_repeated_skeleton_concentration).toBeLessThan(0.01);expect(Object.keys(audit.top_class_associated_tokens)).toEqual(expect.arrayContaining([...CONVERSATIONAL_INTERACTIONS_V1]))});
 it("derives every audience oracle from an exact explicit post-render role span",()=>{const audience=built.items.filter(row=>row.target.interaction==="AUDIENCE_DECLARATION");expect(built.manifest.role_fidelity_policy).toBe(DECLARED_ROLE_FIDELITY_POLICY_V1);for(const row of audience){expect(row.role_span).toBeDefined();expect(row.input_text.slice(row.role_span!.start,row.role_span!.end)).toBe(row.role_span!.text);expect(row.target.audience_declaration?.declared_role).toBe(row.role_span!.text)}});
 it("preserves product-focus semantics and all closed classes",()=>{expect(new Set(built.items.map(row=>row.target.interaction))).toEqual(new Set(CONVERSATIONAL_INTERACTIONS_V1));expect(new Set(built.items.flatMap(row=>row.target.product_focus?[row.target.product_focus]:[]))).toEqual(new Set(CONVERSATIONAL_PRODUCT_FOCUSES_V1));expect(built.items.filter(row=>row.target.interaction==="PRODUCT_QUESTION").every(row=>row.negative_enum_candidates.includes("SERVICE_LEVEL"))).toBe(true)});
 it("keeps historical and OOD sentinels isolated after generation",()=>{const historical=[...buildInterpretationPilotCorpusV1().items.filter(row=>row.split!=="TRAIN").map(row=>row.input_text),...CONVERSATIONAL_INTERPRETATION_GOLD_CORPUS_V1.map(row=>row.message)],ood=oodText.trim().split(/\r?\n/).map(line=>JSON.parse(line).input_text),audit=auditInterpretationCurriculumV4SentinelIsolation(built.items,historical,ood);expect(audit).toEqual({historical_exact_overlap:0,historical_normalized_overlap:0,ood_exact_overlap:0,ood_normalized_overlap:0})});
});
