import type { OperationalSignalScopeBindingV1 } from "../../cockpit/operational.signal.evaluation.scope.v1";
import { verifyOperationalSignalEvaluationScopeV1 } from "../../cockpit/operational.signal.evaluation.scope.v1";
import type { GovernedSourceEventCoverageCapabilityV1 } from "../../cognition/governed.source.event.coverage.capability.v1";
import { verifyGovernedSourceEventCoverageCapabilityV1 } from "../../cognition/governed.source.event.coverage.capability.v1";
import type { CanonicalOrderFact } from "../canonicalization/authoritative.order.fact";
import type { BaselinePlanOrderV1 } from "./operations.baseline.commitment.feasibility.v1";

export const OPERATIONS_CURRENT_PLAN_ORDER_EVENT_CLASS = "event-class:canonical-open-order-version" as const;
export const OPERATIONS_CURRENT_PLAN_REQUIRED_FIELDS = Object.freeze(["field:effective-at", "field:external-order-identity", "field:item", "field:order-fact-id", "field:order-status", "field:order-version", "field:quantity", "field:unit"] as const);

export type OperationsCurrentPlanMembershipPolicyV1 = Readonly<{ version:1; policy_ref:"policy:operations-current-plan-membership-v1"; policy_version:"1"; baseline_semantics:"BASELINE_CURRENT_PLAN"; eligible_status:"OPEN"; activation_rule:"ORDER_VERSION_EFFECTIVE_AT"; current_version_rule:"LATEST_EFFECTIVE_AT_FAIL_ON_TIE"; complete_candidate_universe_required:true; declarative_only:true; policy_id:string; policy_digest:string; digest_algorithm:"SHA-256"; recommended:false; executable:false; grants_authority:false; grants_execution:false }>;
export type OperationsCurrentPlanMembershipV1 = Readonly<{ version:1; policy_ref:string; policy_version:string; baseline_context_ref:string; baseline_context_digest:string; order_fact_ref:string; order_version_ref:string; source_system:string; external_order_id:string; membership_effective_from:string; request_id:string; tenant_id:string; company_id:string; scope_id:string; scope_digest:string; evidence_selection_ref:string; source_snapshot_ref:string; evidence_as_of:string; qualification_refs:readonly string[]; provenance_refs:readonly string[]; causal_lineage_refs:readonly string[]; membership_id:string; membership_digest:string; digest_algorithm:"SHA-256"; current_membership:true; historical_predecessor_refs:readonly string[]; observational_only:true; recommended:false; executable:false; grants_authority:false; grants_execution:false }>;
export type OperationsCurrentPlanContextV1 = Readonly<{ version:1; policy_ref:string; policy_version:string; baseline_semantics:"BASELINE_CURRENT_PLAN"; request_id:string; tenant_id:string; company_id:string; scope_id:string; scope_digest:string; evidence_selection_ref:string; source_snapshot_ref:string; evidence_as_of:string; candidate_universe_coverage_ref:string; member_order_fact_refs:readonly string[]; context_id:string; context_digest:string; digest_algorithm:"SHA-256"; separately_authored_plan_version:false; observational_only:true; recommended:false; executable:false; grants_authority:false; grants_execution:false }>;
export type OperationsCurrentPlanMembershipSetV1 = Readonly<{ policy:OperationsCurrentPlanMembershipPolicyV1; context:OperationsCurrentPlanContextV1; memberships:readonly OperationsCurrentPlanMembershipV1[]; plan_orders:readonly BaselinePlanOrderV1[] }>;

function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return`{${Object.entries(v as Record<string,unknown>).filter(([,x])=>x!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(",")}}`;return JSON.stringify(v)}
async function sha(v:unknown){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(v)));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}
function freeze<T>(v:T):Readonly<T>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v as Record<string,unknown>).forEach(freeze);Object.freeze(v)}return v}
function refs(v:readonly string[],code:string){const x=[...new Set(v.map(y=>y.trim()).filter(Boolean))].sort();if(!x.length)throw new Error(code);return x}
function time(v:string,code:string){const n=Date.parse(v);if(!Number.isFinite(n)||new Date(n).toISOString()!==v)throw new Error(code);return n}

export async function createOperationsCurrentPlanMembershipPolicyV1():Promise<OperationsCurrentPlanMembershipPolicyV1>{const value={version:1 as const,policy_ref:"policy:operations-current-plan-membership-v1" as const,policy_version:"1" as const,baseline_semantics:"BASELINE_CURRENT_PLAN" as const,eligible_status:"OPEN" as const,activation_rule:"ORDER_VERSION_EFFECTIVE_AT" as const,current_version_rule:"LATEST_EFFECTIVE_AT_FAIL_ON_TIE" as const,complete_candidate_universe_required:true as const};const policy_digest=await sha(value);return freeze({...value,declarative_only:true as const,policy_id:`operations-current-plan-membership-policy:sha256:${policy_digest}`,policy_digest,digest_algorithm:"SHA-256" as const,recommended:false as const,executable:false as const,grants_authority:false as const,grants_execution:false as const})}

export async function produceOperationsCurrentPlanMembershipV1(input:Readonly<{version:1;tenant_id:string;evaluation_scope:OperationalSignalScopeBindingV1;candidate_universe_coverage:GovernedSourceEventCoverageCapabilityV1;canonical_order_candidates:readonly CanonicalOrderFact[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[]}>):Promise<OperationsCurrentPlanMembershipSetV1>{
 if(input.version!==1)throw new Error("OPS_PLAN_MEMBERSHIP_VERSION_UNSUPPORTED");await Promise.all([verifyOperationalSignalEvaluationScopeV1(input.evaluation_scope.scope,input.evaluation_scope.scope),verifyGovernedSourceEventCoverageCapabilityV1(input.candidate_universe_coverage)]);const s=input.evaluation_scope.scope,c=input.candidate_universe_coverage;if(s.domain!=="operations"||(s.scope_type!=="REQUEST_DATASET"&&s.scope_type!=="ENTITY"))throw new Error("OPS_PLAN_MEMBERSHIP_SCOPE_UNSUPPORTED");if(c.coverage_status!=="COMPLETE")throw new Error("OPS_PLAN_MEMBERSHIP_COMPLETE_UNIVERSE_REQUIRED");if(c.tenant_id!==input.tenant_id||c.company_id!==s.company_id||c.request_id!==s.request_id||c.scope_id!==s.scope_id||c.scope_digest!==s.scope_digest||c.evidence_selection_ref!==s.evidence_selection_ref||c.source_snapshot_ref!==s.source_snapshot_ref||c.coverage_end!==input.evaluation_scope.evidence_as_of)throw new Error("OPS_PLAN_MEMBERSHIP_COVERAGE_CONTEXT_MISMATCH");const classCapability=c.event_class_capabilities.find(x=>x.domain_ref==="domain:operations"&&x.event_class_ref===OPERATIONS_CURRENT_PLAN_ORDER_EVENT_CLASS);if(!classCapability||OPERATIONS_CURRENT_PLAN_REQUIRED_FIELDS.some(x=>!classCapability.guaranteed_semantic_field_refs.includes(x)))throw new Error("OPS_PLAN_MEMBERSHIP_ORDER_UNIVERSE_FIELDS_REQUIRED");
 const asOf=time(input.evaluation_scope.evidence_as_of,"OPS_PLAN_MEMBERSHIP_AS_OF_INVALID"),eligible=input.canonical_order_candidates.filter(o=>{if(o.owner.tenantId!==input.tenant_id||o.owner.companyId!==s.company_id)throw new Error("OPS_PLAN_MEMBERSHIP_OWNER_MISMATCH");if(o.factFamily!=="INDUSTRIAL_ORDER"||o.order.status!=="OPEN")return false;time(o.effectiveAt,"OPS_PLAN_MEMBERSHIP_EFFECTIVE_AT_INVALID");return Date.parse(o.effectiveAt)<=asOf&&(s.scope_type!=="ENTITY"||(s.entity?.entity_type==="ORDER"&&s.entity.entity_ref===o.factId))});
 const groups=new Map<string,CanonicalOrderFact[]>();for(const o of eligible){const k=`${o.owner.tenantId}|${o.owner.companyId}|${o.source.systemId}|${o.source.externalObjectId}`,g=groups.get(k)??[];g.push(o);groups.set(k,g)}const selected:CanonicalOrderFact[]=[],historical=new Map<string,string[]>();for(const g of groups.values()){const ordered=[...g].sort((a,b)=>Date.parse(b.effectiveAt)-Date.parse(a.effectiveAt)),latest=ordered[0]!;if(ordered.length>1&&ordered[1]!.effectiveAt===latest.effectiveAt)throw new Error("OPS_PLAN_MEMBERSHIP_CURRENT_VERSION_AMBIGUOUS");selected.push(latest);historical.set(latest.factId,ordered.slice(1).map(x=>x.factId).sort())}selected.sort((a,b)=>a.factId.localeCompare(b.factId));if(!selected.length)throw new Error("OPS_PLAN_MEMBERSHIP_NO_ELIGIBLE_ORDERS");
 const policy=await createOperationsCurrentPlanMembershipPolicyV1(),contextValue={version:1 as const,policy_ref:policy.policy_ref,policy_version:policy.policy_version,baseline_semantics:"BASELINE_CURRENT_PLAN" as const,request_id:s.request_id,tenant_id:input.tenant_id,company_id:s.company_id,scope_id:s.scope_id,scope_digest:s.scope_digest,evidence_selection_ref:s.evidence_selection_ref,source_snapshot_ref:s.source_snapshot_ref,evidence_as_of:input.evaluation_scope.evidence_as_of,candidate_universe_coverage_ref:c.capability_id,member_order_fact_refs:selected.map(x=>x.factId)};const context_digest=await sha(contextValue),context=freeze({...contextValue,context_id:`operations-current-plan-context:sha256:${context_digest}`,context_digest,digest_algorithm:"SHA-256" as const,separately_authored_plan_version:false as const,observational_only:true as const,recommended:false as const,executable:false as const,grants_authority:false as const,grants_execution:false as const});
 const qualification=refs(input.qualification_refs,"OPS_PLAN_MEMBERSHIP_QUALIFICATION_REQUIRED"),provenance=refs(input.provenance_refs,"OPS_PLAN_MEMBERSHIP_PROVENANCE_REQUIRED"),memberships:OperationsCurrentPlanMembershipV1[]=[],plan_orders:BaselinePlanOrderV1[]=[];for(const o of selected){const q=refs([...qualification,...c.qualification_refs],"OPS_PLAN_MEMBERSHIP_QUALIFICATION_REQUIRED"),p=refs([...provenance,...c.provenance_refs,`provenance:${o.provenance.acquisitionReference}`],"OPS_PLAN_MEMBERSHIP_PROVENANCE_REQUIRED"),lineage=refs([...input.causal_lineage_refs,o.factId,context.context_id,policy.policy_id,c.capability_id],"OPS_PLAN_MEMBERSHIP_LINEAGE_REQUIRED"),value={version:1 as const,policy_ref:policy.policy_ref,policy_version:policy.policy_version,baseline_context_ref:context.context_id,baseline_context_digest:context.context_digest,order_fact_ref:o.factId,order_version_ref:`order-version:${o.source.externalObjectVersion}`,source_system:o.source.systemId,external_order_id:o.source.externalObjectId,membership_effective_from:o.effectiveAt,request_id:s.request_id,tenant_id:input.tenant_id,company_id:s.company_id,scope_id:s.scope_id,scope_digest:s.scope_digest,evidence_selection_ref:s.evidence_selection_ref,source_snapshot_ref:s.source_snapshot_ref,evidence_as_of:input.evaluation_scope.evidence_as_of,qualification_refs:q,provenance_refs:p,causal_lineage_refs:lineage};const membership_digest=await sha(value),membership=freeze({...value,membership_id:`operations-current-plan-membership:sha256:${membership_digest}`,membership_digest,digest_algorithm:"SHA-256" as const,current_membership:true as const,historical_predecessor_refs:historical.get(o.factId)??[],observational_only:true as const,recommended:false as const,executable:false as const,grants_authority:false as const,grants_execution:false as const});memberships.push(membership);plan_orders.push(freeze({evidence_observed_at:o.observedAt,evidence_refs:[o.factId,membership.membership_id],qualification_refs:q,provenance_refs:p,causal_lineage_refs:[...lineage,membership.membership_id],order_fact_ref:o.factId,order_version_ref:`order-version:${o.source.externalObjectVersion}`,item_ref:`operations-item:${o.order.sku}`,quantity:{value:o.order.quantity.value,unit_ref:"unit:EACH" as const},due_at:o.order.dueAt}))}
 return freeze({policy,context,memberships,plan_orders})
}

export async function verifyOperationsCurrentPlanMembershipSetV1(value:OperationsCurrentPlanMembershipSetV1):Promise<void>{
 const p=value.policy,pv={version:p.version,policy_ref:p.policy_ref,policy_version:p.policy_version,baseline_semantics:p.baseline_semantics,eligible_status:p.eligible_status,activation_rule:p.activation_rule,current_version_rule:p.current_version_rule,complete_candidate_universe_required:p.complete_candidate_universe_required},pd=await sha(pv);if(p.policy_id!==`operations-current-plan-membership-policy:sha256:${pd}`||p.policy_digest!==pd||p.digest_algorithm!=="SHA-256"||p.declarative_only!==true||p.recommended!==false||p.executable!==false||p.grants_authority!==false||p.grants_execution!==false)throw new Error("OPS_PLAN_MEMBERSHIP_POLICY_INTEGRITY_INVALID");
 const c=value.context,cv={version:c.version,policy_ref:c.policy_ref,policy_version:c.policy_version,baseline_semantics:c.baseline_semantics,request_id:c.request_id,tenant_id:c.tenant_id,company_id:c.company_id,scope_id:c.scope_id,scope_digest:c.scope_digest,evidence_selection_ref:c.evidence_selection_ref,source_snapshot_ref:c.source_snapshot_ref,evidence_as_of:c.evidence_as_of,candidate_universe_coverage_ref:c.candidate_universe_coverage_ref,member_order_fact_refs:c.member_order_fact_refs},cd=await sha(cv);if(c.context_id!==`operations-current-plan-context:sha256:${cd}`||c.context_digest!==cd||c.digest_algorithm!=="SHA-256"||c.policy_ref!==p.policy_ref||c.policy_version!==p.policy_version||c.separately_authored_plan_version!==false||c.observational_only!==true||c.recommended!==false||c.executable!==false||c.grants_authority!==false||c.grants_execution!==false)throw new Error("OPS_PLAN_CONTEXT_INTEGRITY_INVALID");
 const facts=value.memberships.map(x=>x.order_fact_ref);if(!facts.length||new Set(facts).size!==facts.length||[...facts].sort().join("|")!==[...c.member_order_fact_refs].sort().join("|")||value.plan_orders.length!==facts.length||new Set(value.plan_orders.map(x=>x.order_fact_ref)).size!==facts.length||value.plan_orders.some(x=>!facts.includes(x.order_fact_ref)))throw new Error("OPS_PLAN_MEMBERSHIP_SET_INCOMPLETE");
 for(const m of value.memberships){const mv={version:m.version,policy_ref:m.policy_ref,policy_version:m.policy_version,baseline_context_ref:m.baseline_context_ref,baseline_context_digest:m.baseline_context_digest,order_fact_ref:m.order_fact_ref,order_version_ref:m.order_version_ref,source_system:m.source_system,external_order_id:m.external_order_id,membership_effective_from:m.membership_effective_from,request_id:m.request_id,tenant_id:m.tenant_id,company_id:m.company_id,scope_id:m.scope_id,scope_digest:m.scope_digest,evidence_selection_ref:m.evidence_selection_ref,source_snapshot_ref:m.source_snapshot_ref,evidence_as_of:m.evidence_as_of,qualification_refs:m.qualification_refs,provenance_refs:m.provenance_refs,causal_lineage_refs:m.causal_lineage_refs},md=await sha(mv);if(m.membership_id!==`operations-current-plan-membership:sha256:${md}`||m.membership_digest!==md||m.digest_algorithm!=="SHA-256"||m.baseline_context_ref!==c.context_id||m.baseline_context_digest!==c.context_digest||m.request_id!==c.request_id||m.tenant_id!==c.tenant_id||m.company_id!==c.company_id||m.scope_id!==c.scope_id||m.scope_digest!==c.scope_digest||m.evidence_selection_ref!==c.evidence_selection_ref||m.source_snapshot_ref!==c.source_snapshot_ref||m.evidence_as_of!==c.evidence_as_of||m.current_membership!==true||m.observational_only!==true||m.recommended!==false||m.executable!==false||m.grants_authority!==false||m.grants_execution!==false)throw new Error("OPS_PLAN_MEMBERSHIP_INTEGRITY_INVALID")}
}
