import { propagateDemand, type BomEdge } from "../../decision/optimizer/demandPropagation.v1";
import type { OperationalSignalScopeBindingV1 } from "../../cockpit/operational.signal.evaluation.scope.v1";
import type { GovernedSourceEventCoverageCapabilityV1 } from "../../cognition/governed.source.event.coverage.capability.v1";
import type { GovernedOperationsFactV1 } from "../preservation/governed.operational.fact.preservation.v1";
import type { BaselineAvailabilityV1 } from "./operations.baseline.commitment.feasibility.v1";
import { assertOperationsPlannedProductionSnapshotCoverageV1 } from "./operations.planned.production.snapshot.coverage.v1";

export type OperationsPlannedProductionFeasibilityStatusV1 = "FEASIBLE" | "PARTIALLY_FEASIBLE" | "ZERO_FEASIBLE" | "UNRESOLVED";
export type OperationsPlannedProductionMaterialFeasibilityV1 = Readonly<{
  version:1; result_kind:"CURRENT_PLANNED_PRODUCTION_MATERIAL_FEASIBILITY"; production_fact_ref:string; production_fact_digest:string;
  tenant_id:string; company_id:string; request_id:string; scope_id:string; scope_digest:string; evidence_selection_ref:string; source_snapshot_ref:string; evidence_as_of:string;
  item_ref:string; planned_quantity:Readonly<{value:number;unit_ref:"unit:EACH"}>; feasible_quantity:Readonly<{value:number;unit_ref:"unit:EACH"}>; planned_output_available_at:string;
  status:OperationsPlannedProductionFeasibilityStatusV1; material_evidence_boundary:"COMPLETE"|"PARTIAL"; requirement_refs:readonly string[];
  evidence_refs:readonly string[]; qualification_refs:readonly string[]; provenance_refs:readonly string[]; causal_lineage_refs:readonly string[];
  result_id:string; result_digest:string; digest_algorithm:"SHA-256"; epistemic_basis:"DETERMINISTIC_GOVERNED_CURRENT_STATE"; observational_only:true; counterfactual:false; recommended:false; executable:false; grants_authority:false; grants_execution:false;
}>;
export type OperationsPlannedProductionMaterialFeasibilitySetV1=Readonly<{results:readonly OperationsPlannedProductionMaterialFeasibilityV1[];availability:readonly BaselineAvailabilityV1[]}>;

const forbidden=["scenario","counterfactual","chat_hypothesis","alternative_plan","optimizer_candidate","authority_tier","commercial_plan","credit_balance","quantity_override","timing_override"];
function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return`{${Object.entries(v as Record<string,unknown>).filter(([,x])=>x!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(",")}}`;return JSON.stringify(v)}
async function sha(v:unknown):Promise<string>{const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(v)));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}
function freeze<T>(v:T):Readonly<T>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v as Record<string,unknown>).forEach(freeze);Object.freeze(v)}return v}
function refs(v:readonly string[],code:string,empty=false){const x=[...new Set(v.map(y=>y.trim()).filter(Boolean))].sort();if(!empty&&!x.length)throw new Error(code);return x}
function instant(v:string,code:string){const n=Date.parse(v);if(!Number.isFinite(n)||new Date(n).toISOString()!==v)throw new Error(code);return n}
type ProductionSemantic=Extract<GovernedOperationsFactV1["semantic"],{family:"PRODUCTION_ORDERS"}>;type BomSemantic=Extract<GovernedOperationsFactV1["semantic"],{family:"MASTER_BOM"}>;type ProductionFact=GovernedOperationsFactV1&Readonly<{fact_family:"PRODUCTION_ORDERS";semantic:ProductionSemantic}>;type BomFact=GovernedOperationsFactV1&Readonly<{fact_family:"MASTER_BOM";semantic:BomSemantic}>;
function production(f:GovernedOperationsFactV1):ProductionFact|undefined{return f.fact_family==="PRODUCTION_ORDERS"&&f.semantic.family==="PRODUCTION_ORDERS"?f as ProductionFact:undefined}
function bom(f:GovernedOperationsFactV1):BomFact|undefined{return f.fact_family==="MASTER_BOM"&&f.semantic.family==="MASTER_BOM"?f as BomFact:undefined}
function assertAcyclic(edges:readonly BomEdge[]){const children=new Map<string,string[]>();for(const e of edges)children.set(e.parent,[...(children.get(e.parent)??[]),e.component]);const visiting=new Set<string>(),done=new Set<string>();const walk=(x:string)=>{if(visiting.has(x))throw new Error("OPS_PRODUCTION_FEASIBILITY_BOM_CYCLE");if(done.has(x))return;visiting.add(x);for(const y of children.get(x)??[])walk(y);visiting.delete(x);done.add(x)};for(const x of children.keys())walk(x)}

export async function evaluateOperationsPlannedProductionMaterialFeasibilityV1(input:Readonly<{
 version:1;tenant_id:string;source_namespace:string;evaluation_scope:OperationalSignalScopeBindingV1;coverage:GovernedSourceEventCoverageCapabilityV1;
 production_facts:readonly GovernedOperationsFactV1[];bom_facts:readonly GovernedOperationsFactV1[];material_availability:readonly BaselineAvailabilityV1[];material_evidence_boundary:"COMPLETE"|"PARTIAL";
 qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[];
}>):Promise<OperationsPlannedProductionMaterialFeasibilitySetV1>{
 if(input.version!==1)throw new Error("OPS_PRODUCTION_FEASIBILITY_VERSION_UNSUPPORTED");for(const k of forbidden)if(k in (input as object))throw new Error("OPS_PRODUCTION_FEASIBILITY_UNSAFE_INPUT");
 await assertOperationsPlannedProductionSnapshotCoverageV1({version:1,tenant_id:input.tenant_id,source_namespace:input.source_namespace,evaluation_scope:input.evaluation_scope,coverage:input.coverage,production_facts:input.production_facts});
 const s=input.evaluation_scope.scope,asOf=instant(input.evaluation_scope.evidence_as_of,"OPS_PRODUCTION_FEASIBILITY_AS_OF_INVALID");
 const q=refs([...input.coverage.qualification_refs,...input.qualification_refs],"OPS_PRODUCTION_FEASIBILITY_QUALIFICATION_REQUIRED"),p=refs([...input.coverage.provenance_refs,...input.provenance_refs],"OPS_PRODUCTION_FEASIBILITY_PROVENANCE_REQUIRED");
 const bomFacts=input.bom_facts.map(f=>{const x=bom(f);if(!x)throw new Error("OPS_PRODUCTION_FEASIBILITY_BOM_FACT_INVALID");if(f.company_id!==s.company_id)throw new Error("OPS_PRODUCTION_FEASIBILITY_COMPANY_MISMATCH");if(x.semantic.source_unit!=="EA"||!Number.isFinite(x.semantic.ratio)||x.semantic.ratio<=0)throw new Error("OPS_PRODUCTION_FEASIBILITY_BOM_UNIT_UNSUPPORTED");return x});
 const allEdges:BomEdge[]=bomFacts.map(f=>({parent:f.semantic.parent,component:f.semantic.component,ratio:f.semantic.ratio}));assertAcyclic(allEdges);
 for(const a of input.material_availability){if(a.kind==="PLANNED_PRODUCTION")throw new Error("OPS_PRODUCTION_FEASIBILITY_RECURSIVE_SUPPLY_REJECTED");if(a.quantity.unit_ref!=="unit:EACH"||!Number.isInteger(a.quantity.value)||a.quantity.value<=0)throw new Error("OPS_PRODUCTION_FEASIBILITY_MATERIAL_UNIT_UNSUPPORTED");if(instant(a.evidence_observed_at,"OPS_PRODUCTION_FEASIBILITY_EVIDENCE_TIME_INVALID")>asOf)throw new Error("OPS_PRODUCTION_FEASIBILITY_EVIDENCE_AFTER_AS_OF");refs(a.evidence_refs,"OPS_PRODUCTION_FEASIBILITY_EVIDENCE_REQUIRED");refs(a.qualification_refs,"OPS_PRODUCTION_FEASIBILITY_QUALIFICATION_REQUIRED");refs(a.provenance_refs,"OPS_PRODUCTION_FEASIBILITY_PROVENANCE_REQUIRED");refs(a.causal_lineage_refs,"OPS_PRODUCTION_FEASIBILITY_LINEAGE_REQUIRED")}
 const consumed=new Map<string,number>();
 const ordered=[...input.production_facts].sort((a,b)=>{const pa=production(a),pb=production(b);return String(pa?.semantic.planned_output_available_at).localeCompare(String(pb?.semantic.planned_output_available_at))||a.fact_id.localeCompare(b.fact_id)}),results:OperationsPlannedProductionMaterialFeasibilityV1[]=[],availability:BaselineAvailabilityV1[]=[];
 for(const fact of ordered){const f=production(fact)!;const outputAt=f.semantic.planned_output_available_at!;instant(outputAt,"OPS_PRODUCTION_FEASIBILITY_OUTPUT_TIME_INVALID");if(f.semantic.quantity.source_unit!=="EA"||!Number.isInteger(f.semantic.quantity.value)||f.semantic.quantity.value<=0)throw new Error("OPS_PRODUCTION_FEASIBILITY_OUTPUT_UNIT_UNSUPPORTED");
  const applicable=bomFacts.filter(x=>Date.parse(x.semantic.valid_from)<=Date.parse(outputAt)),pairs=new Set<string>(),ambiguous=applicable.some(x=>{const k=`${x.semantic.parent}|${x.semantic.component}`;if(pairs.has(k))return true;pairs.add(k);return false});
  let status:OperationsPlannedProductionFeasibilityStatusV1="UNRESOLVED",feasible=0,requirements=new Map<string,number>();
  if(!ambiguous&&applicable.some(x=>x.semantic.parent===f.semantic.output_article)){const expanded=propagateDemand([{sku:f.semantic.output_article,qty:1}],applicable.map(x=>({parent:x.semantic.parent,component:x.semantic.component,ratio:x.semantic.ratio})));expanded.delete(f.semantic.output_article);requirements=new Map([...expanded].filter(([item])=>!applicable.some(x=>x.semantic.parent===item)));const req=[...requirements].filter(([,ratio])=>ratio>0);if(req.length){const supported=Math.min(...req.map(([item,ratio])=>Math.floor(Math.max(0,input.material_availability.filter(a=>a.item_ref===`operations-item:${item}`&&Date.parse(a.available_at)<=Date.parse(outputAt)).reduce((n,a)=>n+a.quantity.value,0)-(consumed.get(item)??0))/ratio)),f.semantic.quantity.value);if(input.material_evidence_boundary==="COMPLETE"){feasible=Math.max(0,supported);status=feasible===0?"ZERO_FEASIBLE":feasible<f.semantic.quantity.value?"PARTIALLY_FEASIBLE":"FEASIBLE";for(const [item,ratio]of req)consumed.set(item,(consumed.get(item)??0)+feasible*ratio)}}}
  const evidence=input.material_availability.filter(a=>requirements.has(a.item_ref.replace(/^operations-item:/,""))&&Date.parse(a.available_at)<=Date.parse(outputAt));const requirement_refs=refs(applicable.filter(x=>requirements.has(x.semantic.component)).map(x=>x.fact_id),"OPS_PRODUCTION_FEASIBILITY_REQUIREMENTS_REQUIRED",status==="UNRESOLVED");const evidence_refs=refs([fact.fact_id,input.coverage.capability_id,...applicable.map(x=>x.fact_id),...evidence.flatMap(x=>x.evidence_refs)],"OPS_PRODUCTION_FEASIBILITY_EVIDENCE_REQUIRED"),qualification_refs=refs([...q,...evidence.flatMap(x=>x.qualification_refs)],"OPS_PRODUCTION_FEASIBILITY_QUALIFICATION_REQUIRED"),provenance_refs=refs([...p,`provenance:${fact.provenance.acquisition_reference}`,...evidence.flatMap(x=>x.provenance_refs)],"OPS_PRODUCTION_FEASIBILITY_PROVENANCE_REQUIRED"),causal_lineage_refs=refs([...input.causal_lineage_refs,input.coverage.capability_id,fact.fact_id,...requirement_refs,...evidence.flatMap(x=>x.causal_lineage_refs)],"OPS_PRODUCTION_FEASIBILITY_LINEAGE_REQUIRED");
  const semantic={version:1 as const,result_kind:"CURRENT_PLANNED_PRODUCTION_MATERIAL_FEASIBILITY"as const,production_fact_ref:fact.fact_id,production_fact_digest:fact.fact_digest,tenant_id:input.tenant_id,company_id:s.company_id,request_id:s.request_id,scope_id:s.scope_id,scope_digest:s.scope_digest,evidence_selection_ref:s.evidence_selection_ref,source_snapshot_ref:s.source_snapshot_ref,evidence_as_of:input.evaluation_scope.evidence_as_of,item_ref:`operations-item:${f.semantic.output_article}`,planned_quantity:{value:f.semantic.quantity.value,unit_ref:"unit:EACH"as const},feasible_quantity:{value:feasible,unit_ref:"unit:EACH"as const},planned_output_available_at:outputAt,status,material_evidence_boundary:input.material_evidence_boundary,requirement_refs,evidence_refs,qualification_refs,provenance_refs,causal_lineage_refs};const result_digest=await sha(semantic),result=freeze({...semantic,result_id:`operations-planned-production-material-feasibility:sha256:${result_digest}`,result_digest,digest_algorithm:"SHA-256"as const,epistemic_basis:"DETERMINISTIC_GOVERNED_CURRENT_STATE"as const,observational_only:true as const,counterfactual:false as const,recommended:false as const,executable:false as const,grants_authority:false as const,grants_execution:false as const});results.push(result);
  if(feasible>0){availability.push(freeze({evidence_observed_at:input.evaluation_scope.evidence_as_of,evidence_refs:[result.result_id,fact.fact_id,input.coverage.capability_id],qualification_refs,provenance_refs,causal_lineage_refs:refs([...causal_lineage_refs,result.result_id],"OPS_PRODUCTION_FEASIBILITY_LINEAGE_REQUIRED"),availability_ref:result.result_id,kind:"PLANNED_PRODUCTION"as const,item_ref:result.item_ref,quantity:{value:feasible,unit_ref:"unit:EACH"as const},available_at:outputAt,material_feasibility:"ESTABLISHED"as const}))}
 }
 return freeze({results,availability});
}

export async function verifyOperationsPlannedProductionMaterialFeasibilityV1(value:OperationsPlannedProductionMaterialFeasibilityV1):Promise<void>{
 const {result_id:_id,result_digest:_digest,digest_algorithm:_algorithm,epistemic_basis:_basis,observational_only:_observational,counterfactual:_counterfactual,recommended:_recommended,executable:_executable,grants_authority:_authority,grants_execution:_execution,...semantic}=value;const digest=await sha(semantic);
 if(value.result_digest!==digest||value.result_id!==`operations-planned-production-material-feasibility:sha256:${digest}`||value.digest_algorithm!=="SHA-256"||value.epistemic_basis!=="DETERMINISTIC_GOVERNED_CURRENT_STATE"||value.observational_only!==true||value.counterfactual!==false||value.recommended!==false||value.executable!==false||value.grants_authority!==false||value.grants_execution!==false)throw new Error("OPS_PRODUCTION_FEASIBILITY_INTEGRITY_INVALID");
}
