import {createCanonicalDecisionMarginV1,type CanonicalDecisionMarginStatusV1,type CanonicalDecisionMarginV1} from "../../decision/canonical.decision.margin.v1";
import {createCanonicalDecisionPressureDimensionV1,type CanonicalDecisionPressureDimensionV1} from "../../decision/canonical.decision.pressure.dimension.v1";
import {createCanonicalDecisionPressureProducerCertificationV1} from "../../decision/canonical.decision.pressure.normalization.policy.v1";
import type {OperationsOrderDeliveryCommitmentV1} from "./operations.protected.objective.v1";

export type OperationsUrgencyStatusV1="WINDOW_OPEN"|"WINDOW_EXHAUSTED"|"UNRESOLVED"|"INSUFFICIENT_EVIDENCE";
export type OperationsUrgencyV1=Readonly<{version:1;urgency_kind:"CURRENT_INTERVENTION_WINDOW_CONSUMPTION";request_id:string;company_id:string;scope_id:string;scope_digest:string;objective_ref:string;objective_digest:string;material_consequence_refs:readonly string[];trajectory_ref:string;governing_condition_ref:string;evidence_as_of:string;evaluated_at:string;decision_margin_ref:string;decision_margin_digest:string;decision_margin_status:CanonicalDecisionMarginStatusV1;status:OperationsUrgencyStatusV1;remaining_window?:Readonly<{value:number;unit_ref:"duration:milliseconds"}>;reference_window?:Readonly<{value:number;unit_ref:"duration:milliseconds"}>;window_consumption_ratio?:number;pressure_dimension?:CanonicalDecisionPressureDimensionV1;evidence_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[];urgency_id:string;urgency_digest:string;digest_algorithm:"SHA-256";epistemic_basis:"DETERMINISTIC_CURRENT_TEMPORAL_EVIDENCE";observational_only:true;recommended:false;executable:false;grants_authority:false;grants_execution:false;grants_remediation:false;company_global_claim:false}>;
const forbidden=["impact","impact_score","cost_of_waiting","loss","authority_tier","subscription_tier","commercial_plan","credit_balance","provider","model","approval","delegation","recommendation","scenario","simulation","optimizer_candidate","llm_classification","learned_urgency"];
function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return`{${Object.entries(v as Record<string,unknown>).filter(([,x])=>x!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(",")}}`;return JSON.stringify(v)}
async function sha(v:unknown){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(v)));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}
function freeze<T>(v:T):Readonly<T>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v as Record<string,unknown>).forEach(freeze);Object.freeze(v)}return v}
function refs(v:readonly string[],code:string){const x=[...new Set(v.map(y=>y.trim()).filter(Boolean))].sort();if(!x.length)throw new Error(code);return x}
function instant(v:string,code:string){const n=Date.parse(v);if(!Number.isFinite(n))throw new Error(code);return n}
async function verifyMargin(m:CanonicalDecisionMarginV1){const rebuilt=await createCanonicalDecisionMarginV1(m);if(rebuilt.margin_id!==m.margin_id||rebuilt.margin_digest!==m.margin_digest)throw new Error("OPS_URGENCY_MARGIN_INTEGRITY_INVALID")}
async function verifyCommitment(c:OperationsOrderDeliveryCommitmentV1){const semantic={version:1 as const,kind:c.kind,order_fact_ref:c.order_fact_ref,order_version_ref:c.order_version_ref,item_ref:c.item_ref,committed_quantity:c.committed_quantity,committed_due_at:c.committed_due_at,commitment_status:c.commitment_status},digest=await sha(semantic);if(c.commitment_digest!==digest||c.commitment_id!==`operations-order-delivery-commitment:sha256:${digest}`)throw new Error("OPS_URGENCY_OBJECTIVE_INTEGRITY_INVALID")}
async function certification(){return createCanonicalDecisionPressureProducerCertificationV1({version:1,dimension:"URGENCY",producer_id:"producer:operations-urgency-v1",producer_version:"1",normalization_policy_id:"normalization-policy:operations-relative-window-consumption-v1",normalization_policy_version:"1",domain_profile_id:"domain-profile:operations",domain_profile_version:"1",supported_scope_kinds:["ENTITY"],endpoint_semantics:"CANONICAL_PRESSURE_DIMENSION_ENDPOINTS_V1",monotonicity:"NON_DECREASING_CANONICAL_MAGNITUDE",reference_basis_semantics:"elapsed share of the governed evidence-as-of to objective-deadline window implied by remaining Decision Margin",evidence_requirement_refs:["requirement:canonical-decision-margin","requirement:objective-deadline"],qualification_requirement_refs:["requirement:governed-current-temporal-evidence"],composition_restriction:"DOMAIN_SCOPED_PROJECTION_NO_GENERIC_CHILD_COMPOSITION",provenance_required:true,causal_lineage_required:true,projection_mode:"CONTINUOUS",precision_policy:{kind:"DECIMAL_PLACES",decimal_places:4}})}

export async function deriveOperationsUrgencyV1(input:Readonly<{version:1;commitment:OperationsOrderDeliveryCommitmentV1;decision_margin:CanonicalDecisionMarginV1}>):Promise<OperationsUrgencyV1>{
 if(input.version!==1)throw new Error("OPS_URGENCY_VERSION_UNSUPPORTED");for(const k of forbidden)if(k in (input as object))throw new Error("OPS_URGENCY_UNSAFE_INPUT");const c=input.commitment,m=input.decision_margin;await Promise.all([verifyCommitment(c),verifyMargin(m)]);const b=c.objective_binding,s=b.evaluation_scope.scope;
 if(c.kind!=="ORDER_DELIVERY_COMMITMENT"||c.commitment_status!=="OPEN")throw new Error("OPS_URGENCY_OBJECTIVE_UNSUPPORTED");if(m.objective_binding_ref!==b.objective_binding_id||m.objective_binding_digest!==b.objective_binding_digest||m.protected_objective.objective_binding_id!==b.objective_binding_id)throw new Error("OPS_URGENCY_OBJECTIVE_MISMATCH");if(m.request_id!==b.request_id||m.company_id!==b.company_id||m.scope_id!==b.scope_id||m.scope_digest!==b.scope_digest)throw new Error("OPS_URGENCY_CONTEXT_MISMATCH");if(m.evidence_as_of!==b.evidence_as_of||m.evaluated_at!==b.evaluated_at)throw new Error("OPS_URGENCY_TIME_BINDING_MISMATCH");if(m.governing_dimension_ref!=="dimension:time"||m.epistemic_basis!=="DETERMINISTIC")throw new Error("OPS_URGENCY_TEMPORAL_MARGIN_REQUIRED");
 const evidenceAsOf=instant(m.evidence_as_of,"OPS_URGENCY_AS_OF_INVALID"),deadline=instant(c.committed_due_at,"OPS_URGENCY_DEADLINE_INVALID"),reference=deadline-evidenceAsOf;if(reference<=0&&m.status==="AVAILABLE")throw new Error("OPS_URGENCY_REFERENCE_WINDOW_INVALID");let status:OperationsUrgencyStatusV1,remaining_window:OperationsUrgencyV1["remaining_window"],reference_window:OperationsUrgencyV1["reference_window"],window_consumption_ratio:number|undefined,pressure_dimension:CanonicalDecisionPressureDimensionV1|undefined;
 if(m.status==="UNRESOLVED")status="UNRESOLVED";else if(m.status==="INSUFFICIENT_EVIDENCE")status="INSUFFICIENT_EVIDENCE";else if(m.status==="BOUNDARY_REACHED"||m.status==="BOUNDARY_EXCEEDED")status="WINDOW_EXHAUSTED";else{if(!m.remaining_margin||m.remaining_margin.unit_ref!=="duration:milliseconds")throw new Error("OPS_URGENCY_REMAINING_WINDOW_INVALID");status="WINDOW_OPEN";remaining_window={value:m.remaining_margin.value,unit_ref:"duration:milliseconds"};reference_window={value:reference,unit_ref:"duration:milliseconds"};window_consumption_ratio=Math.round(Math.min(1,Math.max(0,1-m.remaining_margin.value/reference))*10000)/10000;const cert=await certification();pressure_dimension=await createCanonicalDecisionPressureDimensionV1({version:1,dimension:"URGENCY",projection_mode:"CONTINUOUS",value:window_consumption_ratio,numerator_ref:`normalization-input:${m.margin_id}:consumed-window`,denominator_ref:`normalization-input:${c.commitment_id}:reference-window`,precision_decimal_places:4,request_id:m.request_id,company_id:m.company_id,evaluation_scope:b.evaluation_scope,evidence_as_of:m.evidence_as_of,evaluated_at:m.evaluated_at,producer_certification:cert,normalization_input_refs:[m.margin_id,c.commitment_id,m.current_position_ref],evidence_refs:m.evidence_refs,provenance_refs:m.provenance_refs,causal_lineage_refs:[...m.causal_lineage_refs,m.margin_id],qualification_refs:m.qualification_refs,decision_opportunity_status:"USEFUL_DECISION_REMAINS"})}
 const semantic={version:1 as const,urgency_kind:"CURRENT_INTERVENTION_WINDOW_CONSUMPTION"as const,request_id:m.request_id,company_id:m.company_id,scope_id:s.scope_id,scope_digest:s.scope_digest,objective_ref:c.commitment_id,objective_digest:c.commitment_digest,material_consequence_refs:refs(m.material_compromise_refs,"OPS_URGENCY_CONSEQUENCE_REQUIRED"),trajectory_ref:m.current_position_ref,governing_condition_ref:m.governing_condition_ref,evidence_as_of:m.evidence_as_of,evaluated_at:m.evaluated_at,decision_margin_ref:m.margin_id,decision_margin_digest:m.margin_digest,decision_margin_status:m.status,status,...(remaining_window?{remaining_window}:{}),...(reference_window?{reference_window}:{}),...(window_consumption_ratio!==undefined?{window_consumption_ratio}:{}),...(pressure_dimension?{pressure_dimension}:{}),evidence_refs:m.evidence_refs,qualification_refs:m.qualification_refs,provenance_refs:m.provenance_refs,causal_lineage_refs:refs([...m.causal_lineage_refs,m.margin_id,c.commitment_id,m.current_position_ref],"OPS_URGENCY_LINEAGE_REQUIRED")};const urgency_digest=await sha(semantic);return freeze({...semantic,urgency_id:`operations-urgency:sha256:${urgency_digest}`,urgency_digest,digest_algorithm:"SHA-256"as const,epistemic_basis:"DETERMINISTIC_CURRENT_TEMPORAL_EVIDENCE"as const,observational_only:true as const,recommended:false as const,executable:false as const,grants_authority:false as const,grants_execution:false as const,grants_remediation:false as const,company_global_claim:false as const})
}
export async function verifyOperationsUrgencyV1(value:OperationsUrgencyV1):Promise<void>{const{urgency_id:_id,urgency_digest:_digest,digest_algorithm:_algorithm,epistemic_basis:_basis,observational_only:_observational,recommended:_recommended,executable:_executable,grants_authority:_authority,grants_execution:_execution,grants_remediation:_remediation,company_global_claim:_global,...semantic}=value,digest=await sha(semantic);if(value.urgency_digest!==digest||value.urgency_id!==`operations-urgency:sha256:${digest}`||value.epistemic_basis!=="DETERMINISTIC_CURRENT_TEMPORAL_EVIDENCE"||value.observational_only!==true||value.recommended!==false||value.executable!==false||value.grants_authority!==false||value.grants_execution!==false||value.grants_remediation!==false||value.company_global_claim!==false)throw new Error("OPS_URGENCY_INTEGRITY_INVALID")}
