import type { GovernedBoundedPerturbationV1, GovernedCausalBaselineV1 } from "../../cognition/qualified.causal.evaluation.v1";
import { createGovernedBoundedPerturbationV1, verifyGovernedCausalBaselineV1 } from "../../cognition/qualified.causal.evaluation.v1";
import type { CanonicalDomainContextBindingV1 } from "../../cognition/canonical.domain.context.v1";
import { verifyCanonicalDomainContextBindingV1 } from "../../cognition/canonical.domain.context.v1";
import type { CanonicalDomainInterventionProfileV1 } from "../../cognition/canonical.domain.intervention.profile.v1";
import { verifyCanonicalDomainInterventionProfileV1 } from "../../cognition/canonical.domain.intervention.profile.v1";
import { createOperationsDomainContextBindingV1, createOperationsDomainInterventionProfileV1 } from "./operations.domain.intervention.profile.v1";

export type OperationsPerturbationQuantityInvariantV1=Readonly<{baseline_quantity_ref:string;counterfactual_quantity_ref:string;unit_ref:string;conservation_evidence_ref:string}>;
export type OperationsPerturbationEffectivityBindingV1=Readonly<{baseline_effectivity_ref:string;counterfactual_effectivity_ref:string;temporal_bound_refs:readonly string[]}>;
export type OperationsGovernedPerturbationOperandV1=Readonly<{
 version:1;domain_ref:"domain:operations";request_id:string;company_id:string;scope_id:string;scope_digest:string;
 domain_context_ref:string;domain_context_digest:string;intervention_profile_ref:string;intervention_profile_digest:string;
 baseline_ref:string;baseline_digest:string;dimension_key:string;intervention_primitive_key:string;
 admitted_intervention_class_ref:string;admitted_intervention_class_digest:string;affected_relationship_ref:string;
 baseline_state_ref:string;counterfactual_state_ref:string;derivation_basis:"EXISTING_GOVERNED_ALTERNATIVE";
 derivation_policy_ref:string;governed_alternative_evidence_ref:string;constraint_family_keys:readonly string[];bound_refs:readonly string[];
 quantity_invariant?:OperationsPerturbationQuantityInvariantV1;effectivity_binding?:OperationsPerturbationEffectivityBindingV1;
 evidence_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[];
 epistemic_basis:"DETERMINISTIC_COUNTERFACTUAL";operand_id:string;operand_digest:string;digest_algorithm:"SHA-256";
 derived_not_observed:true;current_fact:false;claims_changeability:false;claims_admissibility:false;establishes_material_effect:false;
 recommended:false;selected:false;executable:false;grants_authority:false;grants_execution:false;grants_remediation:false;company_global_claim:false;
}>;

const forbidden=["action","action_instance","action_payload","recommendation","recommendation_ref","execution_payload","authority_tier","subscription_tier","approval_ref","delegation_ref","credential_ref","optimizer_candidate","optimizer_candidate_ref","candidate_plan","random_candidate","generated_candidate","heuristic_action","scenario_mutation","simulation_result","decision_influenceability_ref","decision_opportunity_ref","urgency","cost_of_waiting","pressure"];
function required(v:string|undefined,c:string){const n=v?.trim();if(!n)throw new Error(c);return n;}
function ref(v:string|undefined,c:string){const n=required(v,c);if(!/^[A-Za-z0-9][A-Za-z0-9._-]*:[^\s]+$/.test(n))throw new Error(c);return n;}
function token(v:string|undefined,c:string){const n=required(v,c);if(!/^[A-Z][A-Z0-9_]{0,95}$/.test(n))throw new Error(c);return n;}
function refs(v:readonly string[],c:string){if(!Array.isArray(v))throw new Error(c);const n=[...new Set(v.map(x=>ref(x,c)))].sort();if(!n.length)throw new Error(c);return n;}
function tokens(v:readonly string[],c:string){if(!Array.isArray(v))throw new Error(c);const n=[...new Set(v.map(x=>token(x,c)))].sort();if(!n.length)throw new Error(c);return n;}
function rejectForbidden(v:object){for(const k of forbidden)if(k in (v as Record<string,unknown>))throw new Error("OPS_PERTURBATION_UNSUPPORTED_SOURCE");}
function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return`{${Object.entries(v as Record<string,unknown>).filter(([,x])=>x!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(",")}}`;return JSON.stringify(v);}
async function sha(v:unknown){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(v)));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("");}
function freeze<T>(v:T):Readonly<T>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v as Record<string,unknown>).forEach(freeze);Object.freeze(v);}return v;}
function semantic(v:OperationsGovernedPerturbationOperandV1){const {operand_id:_id,operand_digest:_digest,digest_algorithm:_algorithm,derived_not_observed:_derived,current_fact:_current,claims_changeability:_changeability,claims_admissibility:_admissibility,establishes_material_effect:_material,recommended:_recommended,selected:_selected,executable:_executable,grants_authority:_authority,grants_execution:_execution,grants_remediation:_remediation,company_global_claim:_global,...value}=v;return value;}

async function exactOperations(input:Readonly<{baseline:GovernedCausalBaselineV1;domain_context:CanonicalDomainContextBindingV1;intervention_profile:CanonicalDomainInterventionProfileV1}>){await verifyGovernedCausalBaselineV1(input.baseline);await verifyCanonicalDomainContextBindingV1(input.domain_context);await verifyCanonicalDomainInterventionProfileV1(input.intervention_profile);const [context,profile]=await Promise.all([createOperationsDomainContextBindingV1(),createOperationsDomainInterventionProfileV1()]);if(input.domain_context.domain_context_id!==context.domain_context_id||input.intervention_profile.binding_profile_id!==profile.binding_profile_id||input.baseline.domain_context_ref!==context.domain_context_id)throw new Error("OPS_PERTURBATION_CONTEXT_PROFILE_MISMATCH");}

export async function createOperationsGovernedPerturbationOperandV1(input:Readonly<{version:1;baseline:GovernedCausalBaselineV1;domain_context:CanonicalDomainContextBindingV1;intervention_profile:CanonicalDomainInterventionProfileV1;dimension_key:string;intervention_primitive_key:string;affected_relationship_ref:string;baseline_state_ref:string;counterfactual_state_ref:string;derivation_basis:"EXISTING_GOVERNED_ALTERNATIVE";derivation_policy_ref:string;governed_alternative_evidence_ref:string;constraint_family_keys:readonly string[];bound_refs:readonly string[];quantity_invariant?:OperationsPerturbationQuantityInvariantV1;effectivity_binding?:OperationsPerturbationEffectivityBindingV1;evidence_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[]}>):Promise<OperationsGovernedPerturbationOperandV1>{
 if(input.version!==1)throw new Error("OPS_PERTURBATION_VERSION_UNSUPPORTED");rejectForbidden(input);await exactOperations(input);if(input.derivation_basis!=="EXISTING_GOVERNED_ALTERNATIVE")throw new Error("OPS_PERTURBATION_DERIVATION_UNSUPPORTED");
 const dimension_key=token(input.dimension_key,"OPS_PERTURBATION_DIMENSION_REQUIRED"),intervention_primitive_key=token(input.intervention_primitive_key,"OPS_PERTURBATION_PRIMITIVE_REQUIRED");const primitive=input.intervention_profile.intervention_primitives.find(x=>x.primitive_key===intervention_primitive_key);if(!primitive||!input.intervention_profile.dimension_intervention_bindings.some(x=>x.dimension_key===dimension_key&&x.primitive_key===intervention_primitive_key))throw new Error("OPS_PERTURBATION_PROFILE_BINDING_UNSUPPORTED");
 const constraint_family_keys=tokens(input.constraint_family_keys,"OPS_PERTURBATION_CONSTRAINT_REQUIRED");if(constraint_family_keys.some(k=>!input.intervention_profile.intervention_constraint_bindings.some(x=>x.primitive_key===intervention_primitive_key&&x.constraint_family_key===k)))throw new Error("OPS_PERTURBATION_CONSTRAINT_UNSUPPORTED");
 const baseline_state_ref=ref(input.baseline_state_ref,"OPS_PERTURBATION_BASELINE_STATE_REQUIRED"),counterfactual_state_ref=ref(input.counterfactual_state_ref,"OPS_PERTURBATION_ALTERNATIVE_STATE_REQUIRED");if(baseline_state_ref===counterfactual_state_ref)throw new Error("OPS_PERTURBATION_ALTERNATIVE_MUST_DIFFER");
 const quantity_invariant=input.quantity_invariant?{baseline_quantity_ref:ref(input.quantity_invariant.baseline_quantity_ref,"OPS_PERTURBATION_BASELINE_QUANTITY_REQUIRED"),counterfactual_quantity_ref:ref(input.quantity_invariant.counterfactual_quantity_ref,"OPS_PERTURBATION_ALTERNATIVE_QUANTITY_REQUIRED"),unit_ref:ref(input.quantity_invariant.unit_ref,"OPS_PERTURBATION_UNIT_REQUIRED"),conservation_evidence_ref:ref(input.quantity_invariant.conservation_evidence_ref,"OPS_PERTURBATION_CONSERVATION_REQUIRED")}:undefined;
 const effectivity_binding=input.effectivity_binding?{baseline_effectivity_ref:ref(input.effectivity_binding.baseline_effectivity_ref,"OPS_PERTURBATION_BASELINE_EFFECTIVITY_REQUIRED"),counterfactual_effectivity_ref:ref(input.effectivity_binding.counterfactual_effectivity_ref,"OPS_PERTURBATION_ALTERNATIVE_EFFECTIVITY_REQUIRED"),temporal_bound_refs:refs(input.effectivity_binding.temporal_bound_refs,"OPS_PERTURBATION_TEMPORAL_BOUND_REQUIRED")}:undefined;
 if(!quantity_invariant&&!effectivity_binding)throw new Error("OPS_PERTURBATION_DOMAIN_INVARIANT_REQUIRED");
 const value={version:1 as const,domain_ref:"domain:operations" as const,request_id:input.baseline.request_id,company_id:input.baseline.company_id,scope_id:input.baseline.scope_id,scope_digest:input.baseline.scope_digest,domain_context_ref:input.domain_context.domain_context_id,domain_context_digest:input.domain_context.domain_context_digest,intervention_profile_ref:input.intervention_profile.binding_profile_id,intervention_profile_digest:input.intervention_profile.binding_profile_digest,baseline_ref:input.baseline.baseline_id,baseline_digest:input.baseline.baseline_digest,dimension_key,intervention_primitive_key,admitted_intervention_class_ref:primitive.admitted_intervention_class_ref,admitted_intervention_class_digest:primitive.admitted_intervention_class_digest,affected_relationship_ref:ref(input.affected_relationship_ref,"OPS_PERTURBATION_RELATIONSHIP_REQUIRED"),baseline_state_ref,counterfactual_state_ref,derivation_basis:"EXISTING_GOVERNED_ALTERNATIVE" as const,derivation_policy_ref:ref(input.derivation_policy_ref,"OPS_PERTURBATION_POLICY_REQUIRED"),governed_alternative_evidence_ref:ref(input.governed_alternative_evidence_ref,"OPS_PERTURBATION_ALTERNATIVE_EVIDENCE_REQUIRED"),constraint_family_keys,bound_refs:refs(input.bound_refs,"OPS_PERTURBATION_BOUND_REQUIRED"),...(quantity_invariant?{quantity_invariant}:{}),...(effectivity_binding?{effectivity_binding}:{}),evidence_refs:refs(input.evidence_refs,"OPS_PERTURBATION_EVIDENCE_REQUIRED"),qualification_refs:refs(input.qualification_refs,"OPS_PERTURBATION_QUALIFICATION_REQUIRED"),provenance_refs:refs(input.provenance_refs,"OPS_PERTURBATION_PROVENANCE_REQUIRED"),causal_lineage_refs:refs([...input.causal_lineage_refs,input.baseline.baseline_id,baseline_state_ref,counterfactual_state_ref],"OPS_PERTURBATION_LINEAGE_REQUIRED"),epistemic_basis:"DETERMINISTIC_COUNTERFACTUAL" as const};const operand_digest=await sha(value);return freeze({...value,operand_id:`operations-governed-perturbation-operand:sha256:${operand_digest}`,operand_digest,digest_algorithm:"SHA-256" as const,derived_not_observed:true as const,current_fact:false as const,claims_changeability:false as const,claims_admissibility:false as const,establishes_material_effect:false as const,recommended:false as const,selected:false as const,executable:false as const,grants_authority:false as const,grants_execution:false as const,grants_remediation:false as const,company_global_claim:false as const});
}

export async function verifyOperationsGovernedPerturbationOperandV1(v:OperationsGovernedPerturbationOperandV1){const d=await sha(semantic(v));if(v.operand_digest!==d||v.operand_id!==`operations-governed-perturbation-operand:sha256:${d}`)throw new Error("OPS_PERTURBATION_INTEGRITY_INVALID");if(v.digest_algorithm!=="SHA-256"||v.derived_not_observed!==true||v.current_fact!==false||v.claims_changeability!==false||v.claims_admissibility!==false||v.establishes_material_effect!==false||v.recommended!==false||v.selected!==false||v.executable!==false||v.grants_authority!==false||v.grants_execution!==false||v.grants_remediation!==false||v.company_global_claim!==false)throw new Error("OPS_PERTURBATION_BOUNDARY_INVALID");}

export async function bindOperationsGovernedPerturbationV1(input:Readonly<{operand:OperationsGovernedPerturbationOperandV1;baseline:GovernedCausalBaselineV1;domain_context:CanonicalDomainContextBindingV1;intervention_profile:CanonicalDomainInterventionProfileV1;admissibility_boundary_ref:string}>):Promise<GovernedBoundedPerturbationV1>{await verifyOperationsGovernedPerturbationOperandV1(input.operand);await exactOperations(input);if(input.operand.baseline_ref!==input.baseline.baseline_id||input.operand.domain_context_ref!==input.domain_context.domain_context_id||input.operand.intervention_profile_ref!==input.intervention_profile.binding_profile_id)throw new Error("OPS_PERTURBATION_OPERAND_BINDING_MISMATCH");return createGovernedBoundedPerturbationV1({version:1,baseline:input.baseline,domain_context:input.domain_context,intervention_profile:input.intervention_profile,dimension_key:input.operand.dimension_key,intervention_primitive_key:input.operand.intervention_primitive_key,admitted_intervention_class_ref:input.operand.admitted_intervention_class_ref,admitted_intervention_class_digest:input.operand.admitted_intervention_class_digest,perturbation_parameter_ref:input.operand.operand_id,constraint_family_keys:input.operand.constraint_family_keys,bound_refs:input.operand.bound_refs,admissibility_ref:ref(input.admissibility_boundary_ref,"OPS_PERTURBATION_ADMISSIBILITY_BOUNDARY_REQUIRED"),evidence_refs:input.operand.evidence_refs,qualification_refs:input.operand.qualification_refs,provenance_refs:input.operand.provenance_refs,causal_lineage_refs:[...input.operand.causal_lineage_refs,input.operand.operand_id]});}
