import {createCanonicalDecisionPressureDimensionV1,type CanonicalDecisionPressureDimensionV1} from "../../decision/canonical.decision.pressure.dimension.v1";
import {createCanonicalDecisionPressureProducerCertificationV1} from "../../decision/canonical.decision.pressure.normalization.policy.v1";
import type {OperationsCurrentFulfillmentPositionV1} from "./operations.current.fulfillment.position.v1";
import type {OperationsOrderDeliveryCommitmentV1} from "./operations.protected.objective.v1";
import {verifyOperationsUrgencyV1,type OperationsUrgencyV1} from "./operations.urgency.v1";

export type OperationsCostOfWaitingStatusV1="NO_ADDITIONAL_COST_ESTABLISHED"|"ADDITIONAL_LATENESS_ESTABLISHED"|"FEASIBILITY_LOSS_ESTABLISHED"|"UNRESOLVED"|"INSUFFICIENT_EVIDENCE";
export type OperationsCostOfWaitingV1=Readonly<{version:1;cost_kind:"BOUNDED_DELAY_MATERIAL_DETERIORATION";request_id:string;company_id:string;scope_id:string;scope_digest:string;objective_ref:string;objective_digest:string;material_consequence_refs:readonly string[];trajectory_ref:string;governing_condition_ref:string;evidence_as_of:string;evaluated_at:string;urgency_ref:string;urgency_digest:string;urgency_status:OperationsUrgencyV1["status"];waiting_interval:Readonly<{start_at:string;end_at:string;duration:Readonly<{value:number;unit_ref:"duration:milliseconds"}>}>;current_expected_fulfillment_at?:string;delayed_expected_fulfillment_at?:string;baseline_lateness?:Readonly<{value:number;unit_ref:"duration:milliseconds"}>;delayed_lateness?:Readonly<{value:number;unit_ref:"duration:milliseconds"}>;additional_lateness?:Readonly<{value:number;unit_ref:"duration:milliseconds"}>;status:OperationsCostOfWaitingStatusV1;pressure_dimension?:CanonicalDecisionPressureDimensionV1;evidence_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[];cost_of_waiting_id:string;cost_of_waiting_digest:string;digest_algorithm:"SHA-256";epistemic_basis:"DETERMINISTIC_BOUNDED_DELAY_COMPARISON";monetary_cost_asserted:false;observational_only:true;recommended:false;executable:false;grants_authority:false;grants_execution:false;grants_remediation:false;company_global_claim:false}>;
export type OperationsBoundedDelayConsequenceV1=Readonly<{status:"RESOLVED"|"UNRESOLVED"|"INSUFFICIENT_EVIDENCE";delayed_expected_fulfillment_at?:string;evidence_ref:string;evidence_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[]}>;
const forbidden=["impact","impact_score","decision_margin","cost","money","currency","authority_tier","subscription_tier","commercial_plan","credit_balance","provider","model","approval","delegation","recommendation","scenario","simulation","optimizer_candidate","llm_output","learned_result"];
function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return`{${Object.entries(v as Record<string,unknown>).filter(([,x])=>x!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(",")}}`;return JSON.stringify(v)}
async function sha(v:unknown){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(v)));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}
function freeze<T>(v:T):Readonly<T>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v as Record<string,unknown>).forEach(freeze);Object.freeze(v)}return v}
function refs(v:readonly string[],code:string){const x=[...new Set(v.map(y=>y.trim()).filter(Boolean))].sort();if(!x.length)throw new Error(code);return x}
function instant(v:string,code:string){const n=Date.parse(v);if(!Number.isFinite(n))throw new Error(code);return n}
async function verifyCommitment(c:OperationsOrderDeliveryCommitmentV1){const semantic={version:1 as const,kind:c.kind,order_fact_ref:c.order_fact_ref,order_version_ref:c.order_version_ref,item_ref:c.item_ref,committed_quantity:c.committed_quantity,committed_due_at:c.committed_due_at,commitment_status:c.commitment_status},digest=await sha(semantic);if(c.commitment_digest!==digest||c.commitment_id!==`operations-order-delivery-commitment:sha256:${digest}`)throw new Error("OPS_WAITING_OBJECTIVE_INTEGRITY_INVALID")}
async function verifyPosition(p:OperationsCurrentFulfillmentPositionV1){const{position_id:_id,position_digest:_digest,digest_algorithm:_algorithm,observational_only:_observational,grants_authority:_authority,grants_execution:_execution,grants_remediation:_remediation,company_global_claim:_global,...semantic}=p,digest=await sha(semantic);if(p.position_digest!==digest||p.position_id!==`operations-current-fulfillment-position:sha256:${digest}`)throw new Error("OPS_WAITING_TRAJECTORY_INTEGRITY_INVALID")}
async function certification(){return createCanonicalDecisionPressureProducerCertificationV1({version:1,dimension:"COST_OF_WAITING",producer_id:"producer:operations-cost-of-waiting-v1",producer_version:"1",normalization_policy_id:"normalization-policy:operations-additional-lateness-per-bounded-delay-v1",normalization_policy_version:"1",domain_profile_id:"domain-profile:operations",domain_profile_version:"1",supported_scope_kinds:["ENTITY"],endpoint_semantics:"CANONICAL_PRESSURE_DIMENSION_ENDPOINTS_V1",monotonicity:"NON_DECREASING_CANONICAL_MAGNITUDE",reference_basis_semantics:"additional governed fulfillment lateness attributable to the explicit bounded waiting interval divided by that interval and capped at the canonical endpoint",evidence_requirement_refs:["requirement:current-fulfillment","requirement:bounded-delay-consequence"],qualification_requirement_refs:["requirement:governed-delay-comparison"],composition_restriction:"DOMAIN_SCOPED_PROJECTION_NO_GENERIC_CHILD_COMPOSITION",provenance_required:true,causal_lineage_required:true,projection_mode:"CONTINUOUS",precision_policy:{kind:"DECIMAL_PLACES",decimal_places:4}})}

export async function deriveOperationsCostOfWaitingV1(input:Readonly<{version:1;commitment:OperationsOrderDeliveryCommitmentV1;current_position:OperationsCurrentFulfillmentPositionV1;urgency:OperationsUrgencyV1;waiting_interval:Readonly<{start_at:string;end_at:string}>;bounded_delay_consequence:OperationsBoundedDelayConsequenceV1;governing_condition_ref:string}>):Promise<OperationsCostOfWaitingV1>{
 if(input.version!==1)throw new Error("OPS_WAITING_VERSION_UNSUPPORTED");for(const k of forbidden)if(k in (input as object))throw new Error("OPS_WAITING_UNSAFE_INPUT");await Promise.all([verifyCommitment(input.commitment),verifyPosition(input.current_position),verifyOperationsUrgencyV1(input.urgency)]);const c=input.commitment,p=input.current_position,u=input.urgency,b=c.objective_binding,s=b.evaluation_scope.scope,d=input.bounded_delay_consequence;
 if(p.protected_objective_ref!==c.commitment_id||p.protected_objective_digest!==c.commitment_digest||u.objective_ref!==c.commitment_id||u.objective_digest!==c.commitment_digest)throw new Error("OPS_WAITING_OBJECTIVE_MISMATCH");if(p.request_id!==u.request_id||p.company_id!==u.company_id||p.scope_id!==u.scope_id||p.scope_digest!==u.scope_digest||p.request_id!==b.request_id||p.company_id!==b.company_id)throw new Error("OPS_WAITING_CONTEXT_MISMATCH");if(p.position_id!==u.trajectory_ref||p.evidence_as_of!==u.evidence_as_of||p.evidence_as_of!==b.evidence_as_of)throw new Error("OPS_WAITING_TRAJECTORY_MISMATCH");if(!input.governing_condition_ref.trim())throw new Error("OPS_WAITING_CONDITION_REQUIRED");const start=instant(input.waiting_interval.start_at,"OPS_WAITING_START_INVALID"),end=instant(input.waiting_interval.end_at,"OPS_WAITING_END_INVALID");if(input.waiting_interval.start_at!==p.evidence_as_of||end<=start)throw new Error("OPS_WAITING_INTERVAL_INVALID");const duration=end-start;refs(d.evidence_refs,"OPS_WAITING_EVIDENCE_REQUIRED");refs(d.qualification_refs,"OPS_WAITING_QUALIFICATION_REQUIRED");refs(d.provenance_refs,"OPS_WAITING_PROVENANCE_REQUIRED");refs(d.causal_lineage_refs,"OPS_WAITING_LINEAGE_REQUIRED");if(!d.evidence_ref.trim())throw new Error("OPS_WAITING_EVIDENCE_REF_REQUIRED");
 let status:OperationsCostOfWaitingStatusV1,current:number|undefined,delayed:number|undefined,baseline:number|undefined,after:number|undefined,additional:number|undefined,pressure_dimension:CanonicalDecisionPressureDimensionV1|undefined;if(p.status==="UNRESOLVED"||d.status==="UNRESOLVED")status="UNRESOLVED";else if(p.status==="INSUFFICIENT_EVIDENCE"||d.status==="INSUFFICIENT_EVIDENCE")status="INSUFFICIENT_EVIDENCE";else{if(!p.current_position_at||!d.delayed_expected_fulfillment_at)throw new Error("OPS_WAITING_FULFILLMENT_TIME_REQUIRED");current=instant(p.current_position_at,"OPS_WAITING_CURRENT_TIME_INVALID");delayed=instant(d.delayed_expected_fulfillment_at,"OPS_WAITING_DELAYED_TIME_INVALID");if(delayed<current)throw new Error("OPS_WAITING_TEMPORAL_ORDER_INVALID");const due=instant(c.committed_due_at,"OPS_WAITING_DEADLINE_INVALID");baseline=Math.max(0,current-due);after=Math.max(0,delayed-due);additional=after-baseline;status=additional===0?"NO_ADDITIONAL_COST_ESTABLISHED":baseline===0&&after>0?"FEASIBILITY_LOSS_ESTABLISHED":"ADDITIONAL_LATENESS_ESTABLISHED";const value=Math.round(Math.min(1,additional/duration)*10000)/10000,cert=await certification();pressure_dimension=await createCanonicalDecisionPressureDimensionV1({version:1,dimension:"COST_OF_WAITING",projection_mode:"CONTINUOUS",value,numerator_ref:`normalization-input:${d.evidence_ref}:additional-lateness`,denominator_ref:`normalization-input:${d.evidence_ref}:waiting-interval`,precision_decimal_places:4,request_id:p.request_id,company_id:p.company_id,evaluation_scope:b.evaluation_scope,evidence_as_of:p.evidence_as_of,evaluated_at:p.evaluated_at,producer_certification:cert,normalization_input_refs:[p.position_id,u.urgency_id,d.evidence_ref],evidence_refs:[...p.evidence_refs,...d.evidence_refs],provenance_refs:[...p.provenance_refs,...d.provenance_refs],causal_lineage_refs:[...p.causal_lineage_refs,...d.causal_lineage_refs,p.position_id,u.urgency_id],qualification_refs:[...p.qualification_refs,...d.qualification_refs]})}
 const semantic={version:1 as const,cost_kind:"BOUNDED_DELAY_MATERIAL_DETERIORATION"as const,request_id:p.request_id,company_id:p.company_id,scope_id:s.scope_id,scope_digest:s.scope_digest,objective_ref:c.commitment_id,objective_digest:c.commitment_digest,material_consequence_refs:u.material_consequence_refs,trajectory_ref:p.position_id,governing_condition_ref:input.governing_condition_ref.trim(),evidence_as_of:p.evidence_as_of,evaluated_at:p.evaluated_at,urgency_ref:u.urgency_id,urgency_digest:u.urgency_digest,urgency_status:u.status,waiting_interval:{start_at:input.waiting_interval.start_at,end_at:input.waiting_interval.end_at,duration:{value:duration,unit_ref:"duration:milliseconds"as const}},...(current!==undefined?{current_expected_fulfillment_at:p.current_position_at}:{}),...(delayed!==undefined?{delayed_expected_fulfillment_at:d.delayed_expected_fulfillment_at}:{}),...(baseline!==undefined?{baseline_lateness:{value:baseline,unit_ref:"duration:milliseconds"as const}}:{}),...(after!==undefined?{delayed_lateness:{value:after,unit_ref:"duration:milliseconds"as const}}:{}),...(additional!==undefined?{additional_lateness:{value:additional,unit_ref:"duration:milliseconds"as const}}:{}),status,...(pressure_dimension?{pressure_dimension}:{}),evidence_refs:refs([...p.evidence_refs,...d.evidence_refs,d.evidence_ref],"OPS_WAITING_EVIDENCE_REQUIRED"),qualification_refs:refs([...p.qualification_refs,...d.qualification_refs],"OPS_WAITING_QUALIFICATION_REQUIRED"),provenance_refs:refs([...p.provenance_refs,...d.provenance_refs],"OPS_WAITING_PROVENANCE_REQUIRED"),causal_lineage_refs:refs([...p.causal_lineage_refs,...d.causal_lineage_refs,p.position_id,u.urgency_id,c.commitment_id,d.evidence_ref],"OPS_WAITING_LINEAGE_REQUIRED")};const cost_of_waiting_digest=await sha(semantic);return freeze({...semantic,cost_of_waiting_id:`operations-cost-of-waiting:sha256:${cost_of_waiting_digest}`,cost_of_waiting_digest,digest_algorithm:"SHA-256"as const,epistemic_basis:"DETERMINISTIC_BOUNDED_DELAY_COMPARISON"as const,monetary_cost_asserted:false as const,observational_only:true as const,recommended:false as const,executable:false as const,grants_authority:false as const,grants_execution:false as const,grants_remediation:false as const,company_global_claim:false as const})
}
export async function verifyOperationsCostOfWaitingV1(value:OperationsCostOfWaitingV1):Promise<void>{const{cost_of_waiting_id:_id,cost_of_waiting_digest:_digest,digest_algorithm:_algorithm,epistemic_basis:_basis,monetary_cost_asserted:_money,observational_only:_observational,recommended:_recommended,executable:_executable,grants_authority:_authority,grants_execution:_execution,grants_remediation:_remediation,company_global_claim:_global,...semantic}=value,digest=await sha(semantic);if(value.cost_of_waiting_digest!==digest||value.cost_of_waiting_id!==`operations-cost-of-waiting:sha256:${digest}`||value.epistemic_basis!=="DETERMINISTIC_BOUNDED_DELAY_COMPARISON"||value.monetary_cost_asserted!==false||value.observational_only!==true||value.recommended!==false||value.executable!==false||value.grants_authority!==false||value.grants_execution!==false||value.grants_remediation!==false||value.company_global_claim!==false)throw new Error("OPS_WAITING_INTEGRITY_INVALID")}
