import { verifyOperationalSignalEvaluationScopeV1, type OperationalSignalScopeBindingV1 } from "../../cockpit/operational.signal.evaluation.scope.v1";
import { verifyOperationsCurrentPlanMembershipSetV1, type OperationsCurrentPlanMembershipSetV1 } from "./operations.current.plan.membership.v1";
import { verifyOperationsOrderDeliveryCommitmentV1, type OperationsOrderDeliveryCommitmentV1 } from "./operations.protected.objective.v1";

export type OperationsNormativeObjectiveSetMemberV1=Readonly<{plan_membership_ref:string;plan_membership_digest:string;order_fact_ref:string;order_version_ref:string;plan_element_ref:string;protected_objective_ref:string;protected_objective_digest:string;objective_binding_ref:string;objective_binding_digest:string;objective_scope_id:string;objective_scope_digest:string;normative:true;composition_role:"REQUIRED_CONJUNCT"}>;
export type OperationsProtectedObjectiveSetV1=Readonly<{version:1;policy_ref:"policy:operations-current-plan-protected-objective-set-v1";objective_family:"ORDER_DELIVERY_COMMITMENT";composition:"CONJUNCTIVE_REQUIRED_COMMITMENTS";current_plan_context_ref:string;current_plan_context_digest:string;candidate_universe_coverage_ref:string;request_id:string;tenant_id:string;company_id:string;scope_id:string;scope_digest:string;evidence_selection_ref:string;source_snapshot_ref:string;evidence_as_of:string;evaluated_at:string;members:readonly OperationsNormativeObjectiveSetMemberV1[];member_count:number;complete_current_plan_membership_coverage:true;complete_normative_objective_coverage:true;optional_objectives_admitted:false;evidence_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[];objective_set_id:string;objective_set_digest:string;digest_algorithm:"SHA-256";observational_only:true;recommended:false;executable:false;grants_authority:false;grants_execution:false}>;

function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return`{${Object.entries(v as Record<string,unknown>).filter(([,x])=>x!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(",")}}`;return JSON.stringify(v)}
async function sha(v:unknown){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(v)));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}
function freeze<T>(v:T):Readonly<T>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v as Record<string,unknown>).forEach(freeze);Object.freeze(v)}return v}
function refs(v:readonly string[],code:string){const x=[...new Set(v.map(y=>y.trim()).filter(Boolean))].sort();if(!x.length)throw new Error(code);return Object.freeze(x)}

export async function createOperationsProtectedObjectiveSetV1(input:Readonly<{version:1;evaluation_scope:OperationalSignalScopeBindingV1;current_plan:OperationsCurrentPlanMembershipSetV1;objective_bindings:readonly Readonly<{plan_membership_ref:string;plan_element_ref:string;commitment:OperationsOrderDeliveryCommitmentV1}>[]}>):Promise<OperationsProtectedObjectiveSetV1>{
 if(input.version!==1)throw new Error("OPS_OBJECTIVE_SET_VERSION_UNSUPPORTED");await Promise.all([verifyOperationalSignalEvaluationScopeV1(input.evaluation_scope.scope,input.evaluation_scope.scope),verifyOperationsCurrentPlanMembershipSetV1(input.current_plan)]);const s=input.evaluation_scope.scope,c=input.current_plan.context;if(s.scope_type!=="REQUEST_DATASET"||s.domain!=="operations")throw new Error("OPS_OBJECTIVE_SET_SCOPE_UNSUPPORTED");if(c.scope_id!==s.scope_id||c.scope_digest!==s.scope_digest||c.request_id!==s.request_id||c.company_id!==s.company_id||c.evidence_selection_ref!==s.evidence_selection_ref||c.source_snapshot_ref!==s.source_snapshot_ref||c.evidence_as_of!==input.evaluation_scope.evidence_as_of)throw new Error("OPS_OBJECTIVE_SET_PLAN_CONTEXT_MISMATCH");if(input.objective_bindings.length!==input.current_plan.memberships.length)throw new Error("OPS_OBJECTIVE_SET_INCOMPLETE");
 const byMembership=new Map(input.current_plan.memberships.map(x=>[x.membership_id,x] as const)),seenMembership=new Set<string>(),seenObjective=new Set<string>(),members:OperationsNormativeObjectiveSetMemberV1[]=[];for(const candidate of input.objective_bindings){const membership=byMembership.get(candidate.plan_membership_ref),commitment=candidate.commitment;if(!membership||seenMembership.has(candidate.plan_membership_ref))throw new Error("OPS_OBJECTIVE_SET_MEMBERSHIP_INVALID");await verifyOperationsOrderDeliveryCommitmentV1(commitment);const b=commitment.objective_binding,child=b.evaluation_scope.scope;if(seenObjective.has(commitment.commitment_id))throw new Error("OPS_OBJECTIVE_SET_OBJECTIVE_DUPLICATE");if(commitment.order_fact_ref!==membership.order_fact_ref||commitment.order_version_ref!==membership.order_version_ref||!b.governing_plan_element_refs.includes(candidate.plan_element_ref)||!b.source_evidence_refs.includes(membership.order_fact_ref))throw new Error("OPS_OBJECTIVE_SET_MEMBER_BINDING_MISMATCH");if(child.scope_type!=="ENTITY"||child.entity?.entity_type!=="ORDER"||child.entity.entity_ref!==membership.order_fact_ref||child.request_id!==s.request_id||child.company_id!==s.company_id||child.domain!==s.domain||child.evidence_selection_ref!==s.evidence_selection_ref||child.source_snapshot_ref!==s.source_snapshot_ref||b.evidence_as_of!==input.evaluation_scope.evidence_as_of||b.evaluated_at!==input.evaluation_scope.evaluated_at)throw new Error("OPS_OBJECTIVE_SET_CHILD_SCOPE_MISMATCH");seenMembership.add(candidate.plan_membership_ref);seenObjective.add(commitment.commitment_id);members.push(freeze({plan_membership_ref:membership.membership_id,plan_membership_digest:membership.membership_digest,order_fact_ref:membership.order_fact_ref,order_version_ref:membership.order_version_ref,plan_element_ref:candidate.plan_element_ref,protected_objective_ref:commitment.commitment_id,protected_objective_digest:commitment.commitment_digest,objective_binding_ref:b.objective_binding_id,objective_binding_digest:b.objective_binding_digest,objective_scope_id:child.scope_id,objective_scope_digest:child.scope_digest,normative:true as const,composition_role:"REQUIRED_CONJUNCT"as const}))}members.sort((a,b)=>a.plan_membership_ref.localeCompare(b.plan_membership_ref));if(seenMembership.size!==byMembership.size)throw new Error("OPS_OBJECTIVE_SET_INCOMPLETE");
 const evidence_refs=refs(input.objective_bindings.flatMap(x=>x.commitment.objective_binding.source_evidence_refs),"OPS_OBJECTIVE_SET_EVIDENCE_REQUIRED"),qualification_refs=refs([...input.current_plan.memberships.flatMap(x=>x.qualification_refs),...input.objective_bindings.flatMap(x=>x.commitment.objective_binding.qualification_refs)],"OPS_OBJECTIVE_SET_QUALIFICATION_REQUIRED"),provenance_refs=refs([...input.current_plan.memberships.flatMap(x=>x.provenance_refs),...input.objective_bindings.flatMap(x=>x.commitment.objective_binding.provenance_refs)],"OPS_OBJECTIVE_SET_PROVENANCE_REQUIRED"),causal_lineage_refs=refs([...input.current_plan.memberships.flatMap(x=>x.causal_lineage_refs),...input.objective_bindings.flatMap(x=>x.commitment.objective_binding.causal_lineage_refs),c.context_id,...members.map(x=>x.objective_binding_ref)],"OPS_OBJECTIVE_SET_LINEAGE_REQUIRED");const semantic={version:1 as const,policy_ref:"policy:operations-current-plan-protected-objective-set-v1"as const,objective_family:"ORDER_DELIVERY_COMMITMENT"as const,composition:"CONJUNCTIVE_REQUIRED_COMMITMENTS"as const,current_plan_context_ref:c.context_id,current_plan_context_digest:c.context_digest,candidate_universe_coverage_ref:c.candidate_universe_coverage_ref,request_id:s.request_id,tenant_id:c.tenant_id,company_id:s.company_id,scope_id:s.scope_id,scope_digest:s.scope_digest,evidence_selection_ref:s.evidence_selection_ref,source_snapshot_ref:s.source_snapshot_ref,evidence_as_of:input.evaluation_scope.evidence_as_of,evaluated_at:input.evaluation_scope.evaluated_at,members:Object.freeze(members),member_count:members.length,complete_current_plan_membership_coverage:true as const,complete_normative_objective_coverage:true as const,optional_objectives_admitted:false as const,evidence_refs,qualification_refs,provenance_refs,causal_lineage_refs},objective_set_digest=await sha(semantic);return freeze({...semantic,objective_set_id:`operations-protected-objective-set:sha256:${objective_set_digest}`,objective_set_digest,digest_algorithm:"SHA-256"as const,observational_only:true as const,recommended:false as const,executable:false as const,grants_authority:false as const,grants_execution:false as const})
}

export async function verifyOperationsProtectedObjectiveSetV1(value:OperationsProtectedObjectiveSetV1):Promise<void>{const{objective_set_id,objective_set_digest,digest_algorithm,observational_only,recommended,executable,grants_authority,grants_execution,...semantic}=value,expected=await sha(semantic);if(objective_set_id!==`operations-protected-objective-set:sha256:${expected}`||objective_set_digest!==expected||digest_algorithm!=="SHA-256"||observational_only!==true||recommended!==false||executable!==false||grants_authority!==false||grants_execution!==false||value.complete_current_plan_membership_coverage!==true||value.complete_normative_objective_coverage!==true||value.optional_objectives_admitted!==false||value.member_count!==value.members.length||new Set(value.members.map(x=>x.plan_membership_ref)).size!==value.members.length||new Set(value.members.map(x=>x.objective_binding_ref)).size!==value.members.length||value.members.some(x=>x.normative!==true||x.composition_role!=="REQUIRED_CONJUNCT"))throw new Error("OPS_OBJECTIVE_SET_INTEGRITY_INVALID")}
