import type { OperationalSignalScopeBindingV1 } from "../../cockpit/operational.signal.evaluation.scope.v1";
import type { GovernedSourceEventCoverageCapabilityV1 } from "../../cognition/governed.source.event.coverage.capability.v1";
import { retrieveCanonicalAdmittedGovernedFactV1, type GovernedAcquisitionEvaluationResultV1 } from "../../reality/governed.acquisition.evaluation.batch.v1";
import type { CanonicalOrderFact } from "../canonicalization/authoritative.order.fact";
import type { GovernedOperationsFactV1 } from "../preservation/governed.operational.fact.preservation.v1";
import type { BaselineAvailabilityV1 } from "./operations.baseline.commitment.feasibility.v1";
import { bindOperationsCanonicalEffectiveInventoryV1, projectOperationsCanonicalEffectiveInventoryToBaselineAvailabilityV1 } from "./operations.canonical.effective.inventory.v1";
import type { OperationsCanonicalLocationV1 } from "./operations.canonical.location.v1";
import { reconstructOperationsCurrentInventoryV1 } from "./operations.inventory.currentness.reconstruction.v1";
import { bindOperationsOrderDeliveryCommitmentV1, type OperationsOrderDeliveryCommitmentV1 } from "./operations.protected.objective.v1";

export type CanonicalRealityOperationsProjectionLineageV1=Readonly<{canonical_evidence_ref:string;canonical_reality_ref:string;canonical_reality_digest:string}>;
const projection="CANONICAL_ADMITTED_GOVERNED_FACT_TO_OPERATIONS_COGNITION_V1";
function tenant(value:string){return value.replace(/^tenant:/,"")}
function eligible(value:Awaited<ReturnType<typeof retrieveCanonicalAdmittedGovernedFactV1>>){if(!value.cognition_eligible)throw new Error("OPS_CANONICAL_REALITY_EVIDENCE_NOT_COGNITION_ELIGIBLE");return value}
function orderFact(fact:GovernedOperationsFactV1,result:GovernedAcquisitionEvaluationResultV1):CanonicalOrderFact{const value=fact.semantic;if(value.family!=="ORDERS")throw new Error("OPS_CANONICAL_REALITY_ORDER_REQUIRED");if(value.quantity.canonical_unit!=="EACH")throw new Error("OPS_CANONICAL_REALITY_ORDER_UNIT_UNSUPPORTED");return Object.freeze({factId:fact.fact_id,factFamily:"INDUSTRIAL_ORDER",schemaVersion:"1.0.0",owner:{tenantId:tenant(fact.role_bindings.subject.tenant_id),companyId:fact.company_id,ownerId:fact.role_bindings.subject.subject_id},source:{systemId:fact.provenance.source_system,externalObjectId:value.order_id,externalObjectVersion:value.order_version},observedAt:value.observed_at,effectiveAt:value.effective_at,order:{sku:value.sku,quantity:{value:value.quantity.value,unit:"EACH"},status:value.status,dueAt:value.due_at},provenance:{acquisitionReference:fact.provenance.acquisition_reference,authorizationReference:fact.provenance.authorization_reference,acquiredAt:fact.provenance.acquired_at,capabilityId:fact.provenance.capability_id,connectorIdentityId:fact.provenance.connector_identity_id,connectorRevision:fact.provenance.connector_revision,sourceRepresentation:fact.provenance.source_representation,transformationId:projection,transformationVersion:"1.0.0",canonicalSchemaVersion:"1.0.0",tenantId:tenant(fact.role_bindings.subject.tenant_id),companyId:fact.company_id,ownerId:fact.role_bindings.subject.subject_id,sourceSystem:fact.provenance.source_system,externalObjectId:value.order_id,externalObjectVersion:value.order_version}})}

export async function projectCanonicalAdmittedOrderToOperationsCommitmentV1(input:Readonly<{version:1;acquisition_result:GovernedAcquisitionEvaluationResultV1;canonical_evidence_ref:string;evaluation_scope:OperationalSignalScopeBindingV1;objective_selection_ref:string;plan_element_ref:string;protected_subject_ref:string}>):Promise<Readonly<{commitment:OperationsOrderDeliveryCommitmentV1;order_fact:CanonicalOrderFact;lineage:CanonicalRealityOperationsProjectionLineageV1}>>{if(input.version!==1)throw new Error("OPS_CANONICAL_REALITY_PROJECTION_VERSION_UNSUPPORTED");const admitted=eligible(await retrieveCanonicalAdmittedGovernedFactV1(input.acquisition_result,input.canonical_evidence_ref)),fact=orderFact(admitted.fact,input.acquisition_result),scope=input.evaluation_scope.scope;if(scope.company_id!==input.acquisition_result.company_id||scope.request_id!==input.acquisition_result.request_id||scope.evidence_selection_ref!==input.acquisition_result.evidence_selection_ref||scope.source_snapshot_ref!==input.acquisition_result.source_snapshot_ref||input.evaluation_scope.evidence_as_of!==input.acquisition_result.evidence_as_of)throw new Error("OPS_CANONICAL_REALITY_PROJECTION_SCOPE_MISMATCH");const lineage=Object.freeze({canonical_evidence_ref:admitted.canonical_evidence_ref,canonical_reality_ref:admitted.canonical_reality_ref,canonical_reality_digest:admitted.canonical_reality_digest}),commitment=await bindOperationsOrderDeliveryCommitmentV1({version:1,order_fact:fact,evaluation_scope:input.evaluation_scope,selected_objective_kind:"ORDER_DELIVERY_COMMITMENT",objective_selection_ref:input.objective_selection_ref,plan_element_ref:input.plan_element_ref,protected_subject_ref:input.protected_subject_ref,qualification_refs:admitted.fact.role_bindings.plan_element?.qualification_refs??admitted.fact.role_bindings.subject.qualification_refs,causal_lineage_refs:[admitted.fact.fact_id,admitted.fact.fact_digest,...Object.values(lineage)],plan_lineage_refs:[admitted.fact.role_bindings.plan_element?.role_id??admitted.fact.fact_id,admitted.canonical_reality_ref]});return Object.freeze({commitment,order_fact:fact,lineage})}

export async function projectCanonicalAdmittedInventoryToBaselineAvailabilityV1(input:Readonly<{version:1;acquisition_result:GovernedAcquisitionEvaluationResultV1;canonical_evidence_ref:string;evaluation_scope:OperationalSignalScopeBindingV1;observation_coverage:GovernedSourceEventCoverageCapabilityV1;delta_coverage:GovernedSourceEventCoverageCapabilityV1;location_candidates:readonly OperationsCanonicalLocationV1[]}>):Promise<Readonly<{availability:BaselineAvailabilityV1;lineage:CanonicalRealityOperationsProjectionLineageV1}>>{if(input.version!==1)throw new Error("OPS_CANONICAL_REALITY_PROJECTION_VERSION_UNSUPPORTED");const admitted=eligible(await retrieveCanonicalAdmittedGovernedFactV1(input.acquisition_result,input.canonical_evidence_ref));if(admitted.fact.semantic.family!=="INVENTORY")throw new Error("OPS_CANONICAL_REALITY_INVENTORY_REQUIRED");const lineage=Object.freeze({canonical_evidence_ref:admitted.canonical_evidence_ref,canonical_reality_ref:admitted.canonical_reality_ref,canonical_reality_digest:admitted.canonical_reality_digest}),reconstructions=await reconstructOperationsCurrentInventoryV1({version:1,tenant_id:tenant(admitted.fact.role_bindings.subject.tenant_id),evaluation_scope:input.evaluation_scope,observation_coverage:input.observation_coverage,delta_coverage:input.delta_coverage,inventory_observation_candidates:[admitted.fact],movement_deltas:[],location_candidates:input.location_candidates,qualification_refs:admitted.fact.role_bindings.subject.qualification_refs,provenance_refs:[...admitted.fact.role_bindings.subject.provenance_refs,...input.acquisition_result.provenance_refs],causal_lineage_refs:[admitted.fact.fact_id,admitted.fact.fact_digest,...Object.values(lineage)]});if(reconstructions.length!==1)throw new Error("OPS_CANONICAL_REALITY_INVENTORY_AMBIGUOUS");const inventory=await bindOperationsCanonicalEffectiveInventoryV1({version:1,reconstruction:reconstructions[0]!,qualification_refs:[`qualification:${projection}`],provenance_refs:input.acquisition_result.provenance_refs,causal_lineage_refs:Object.values(lineage)}),availability=await projectOperationsCanonicalEffectiveInventoryToBaselineAvailabilityV1(inventory);return Object.freeze({availability,lineage})}
