import type { OperationsGovernedAllocationStateV1 } from "./operations.qualified.causal.evaluation.v1";
import { verifyOperationsGovernedAllocationStateV1 } from "./operations.qualified.causal.evaluation.v1";
import type { OperationsInterventionCurrentPolicyProfileV1 } from "./operations.intervention.current.policy.profile.v1";
import { verifyOperationsInterventionCurrentPolicyProfileV1 } from "./operations.intervention.current.policy.profile.v1";

export type OperationsAllocationFixationEvidenceV1=Readonly<{
 version:1;request_id:string;company_id:string;scope_id:string;scope_digest:string;evidence_selection_ref:string;
 domain_context_ref:string;domain_context_digest:string;policy_profile_ref:string;policy_profile_digest:string;
 allocation_relationship_ref:string;allocation_current_state_ref:string;fixation_class_key:string;fixation_class_ref:string;
 governed_event_ref:string;canonical_event_identity_ref:string;allocation_attribution_ref:string;item_ref:string;
 allocation_quantity:Readonly<{value:number;unit_ref:"unit:EACH"}>;attributed_fixation_quantity:Readonly<{value:number;unit_ref:"unit:EACH"}>;
 partial_fixation:boolean;whole_relationship_fixation_asserted:false;destination_or_commitment_ref?:string;process_or_usage_ref?:string;
 occurred_at:string;effected_at:string;policy_ref:string;policy_version:string;evidence_refs:readonly string[];
 qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[];evidence_as_of:string;
 fixation_evidence_id:string;fixation_evidence_digest:string;digest_algorithm:"SHA-256";observational_only:true;
 establishes_changeability:false;establishes_constraint_result:false;establishes_admissibility:false;recommended:false;
 executable:false;grants_authority:false;grants_execution:false;
}>;
export type OperationsFixationCoverageStatusV1="COMPLETE"|"PARTIAL"|"INSUFFICIENT";
export type OperationsAllocationFixationEvidenceCoverageV1=Readonly<{
 version:1;request_id:string;company_id:string;scope_id:string;scope_digest:string;evidence_selection_ref:string;
 domain_context_ref:string;domain_context_digest:string;policy_profile_ref:string;policy_profile_digest:string;
 allocation_relationship_ref:string;allocation_current_state_ref:string;covered_fixation_class_keys:readonly string[];
 coverage_from:string;coverage_through:string;coverage_basis_ref:string;coverage_status:OperationsFixationCoverageStatusV1;
 evidence_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[];
 coverage_id:string;coverage_digest:string;digest_algorithm:"SHA-256";observational_only:true;asserts_event_absence:false;
 establishes_changeability:false;recommended:false;executable:false;grants_authority:false;grants_execution:false;
}>;

const forbidden=["source_movement_type","sku_only_attribution","quantity_coincidence","timestamp_proximity","order_guess","planned_allocation","reservation","optimizer_assignment","internal_freeze","llm_attribution","changeability_status","constraint_result","admissibility_status","authority_tier","execution_capability"];
function required(v:string|undefined,c:string){const n=v?.trim();if(!n)throw new Error(c);return n;}
function ref(v:string|undefined,c:string){const n=required(v,c);if(!/^[A-Za-z0-9][A-Za-z0-9._-]*:[^\s]+$/.test(n))throw new Error(c);return n;}
function refs(v:readonly string[],c:string){if(!Array.isArray(v))throw new Error(c);const n=[...new Set(v.map(x=>ref(x,c)))].sort();if(!n.length)throw new Error(c);return n;}
function token(v:string|undefined,c:string){const n=required(v,c);if(!/^[A-Z][A-Z0-9_]{0,95}$/.test(n))throw new Error(c);return n;}
function time(v:string,c:string){if(!Number.isFinite(Date.parse(v)))throw new Error(c);return v;}
function positive(v:number,c:string){if(!Number.isFinite(v)||v<=0)throw new Error(c);return v;}
function reject(v:object,c:string){for(const k of forbidden)if(k in (v as Record<string,unknown>))throw new Error(c);}
function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return`{${Object.entries(v as Record<string,unknown>).filter(([,x])=>x!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(",")}}`;return JSON.stringify(v);}
async function sha(v:unknown){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(v)));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("");}
function freeze<T>(v:T):Readonly<T>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v as Record<string,unknown>).forEach(freeze);Object.freeze(v);}return v;}
function semantic(v:Record<string,unknown>,id:string,digest:string,extra:string[]=[]){const x={...v};for(const k of [id,digest,"digest_algorithm","observational_only","establishes_changeability","establishes_constraint_result","establishes_admissibility","recommended","executable","grants_authority","grants_execution",...extra])delete x[k];return x;}
async function exact(input:{policy:OperationsInterventionCurrentPolicyProfileV1;current_state:OperationsGovernedAllocationStateV1}){await Promise.all([verifyOperationsInterventionCurrentPolicyProfileV1(input.policy),verifyOperationsGovernedAllocationStateV1(input.current_state)]);if(input.current_state.state_semantics!=="CURRENT_GOVERNED"||input.policy.domain_context_ref===undefined)throw new Error("OPS_FIXATION_CURRENT_STATE_REQUIRED");if(input.current_state.company_id.length===0||input.current_state.scope_id.length===0)throw new Error("OPS_FIXATION_STATE_BINDING_INVALID");}

export async function createOperationsAllocationFixationEvidenceV1(input:Readonly<{version:1;policy:OperationsInterventionCurrentPolicyProfileV1;current_state:OperationsGovernedAllocationStateV1;evidence_selection_ref:string;allocation_relationship_ref:string;fixation_class_key:string;governed_event_ref:string;canonical_event_identity_ref:string;allocation_attribution_ref:string;item_ref:string;allocation_quantity:Readonly<{value:number;unit_ref:"unit:EACH"}>;attributed_fixation_quantity:Readonly<{value:number;unit_ref:"unit:EACH"}>;destination_or_commitment_ref?:string;process_or_usage_ref?:string;occurred_at:string;effected_at:string;evidence_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[];evidence_as_of:string}>):Promise<OperationsAllocationFixationEvidenceV1>{
 if(input.version!==1)throw new Error("OPS_FIXATION_VERSION_UNSUPPORTED");reject(input,"OPS_FIXATION_UNSAFE_ATTRIBUTION");await exact(input);const key=token(input.fixation_class_key,"OPS_FIXATION_CLASS_INVALID"),fixation=input.policy.fixation_classes.find(x=>x.fixation_class_key===key);if(!fixation)throw new Error("OPS_FIXATION_CLASS_UNSUPPORTED");if(key==="EFFECTED_DESTINATION_SHIPMENT"&&!input.destination_or_commitment_ref)throw new Error("OPS_FIXATION_DESTINATION_REQUIRED");if(key==="EFFECTED_CONSUMPTION_OR_USE"&&!input.process_or_usage_ref)throw new Error("OPS_FIXATION_USAGE_REQUIRED");if(input.allocation_quantity.unit_ref!=="unit:EACH"||input.attributed_fixation_quantity.unit_ref!=="unit:EACH")throw new Error("OPS_FIXATION_UNIT_MISMATCH");const allocated=positive(input.allocation_quantity.value,"OPS_FIXATION_ALLOCATION_QUANTITY_INVALID"),attributed=positive(input.attributed_fixation_quantity.value,"OPS_FIXATION_ATTRIBUTED_QUANTITY_INVALID");if(attributed>allocated)throw new Error("OPS_FIXATION_ATTRIBUTED_QUANTITY_EXCEEDS_ALLOCATION");const occurred_at=time(input.occurred_at,"OPS_FIXATION_OCCURRED_AT_INVALID"),effected_at=time(input.effected_at,"OPS_FIXATION_EFFECTED_AT_INVALID"),evidence_as_of=time(input.evidence_as_of,"OPS_FIXATION_AS_OF_INVALID");if(Date.parse(occurred_at)>Date.parse(effected_at)||Date.parse(effected_at)>Date.parse(evidence_as_of)||evidence_as_of!==input.current_state.evidence_as_of)throw new Error("OPS_FIXATION_TIME_CONTRADICTION");
 const suppliedLineage=refs(input.causal_lineage_refs,"OPS_FIXATION_LINEAGE_REQUIRED");const value={version:1 as const,request_id:input.current_state.request_id,company_id:input.current_state.company_id,scope_id:input.current_state.scope_id,scope_digest:input.current_state.scope_digest,evidence_selection_ref:ref(input.evidence_selection_ref,"OPS_FIXATION_SELECTION_REQUIRED"),domain_context_ref:input.policy.domain_context_ref,domain_context_digest:input.policy.domain_context_digest,policy_profile_ref:input.policy.policy_profile_id,policy_profile_digest:input.policy.policy_profile_digest,allocation_relationship_ref:ref(input.allocation_relationship_ref,"OPS_FIXATION_RELATIONSHIP_REQUIRED"),allocation_current_state_ref:input.current_state.state_id,fixation_class_key:key,fixation_class_ref:fixation.fixation_class_ref,governed_event_ref:ref(input.governed_event_ref,"OPS_FIXATION_EVENT_REQUIRED"),canonical_event_identity_ref:ref(input.canonical_event_identity_ref,"OPS_FIXATION_EVENT_IDENTITY_REQUIRED"),allocation_attribution_ref:ref(input.allocation_attribution_ref,"OPS_FIXATION_ATTRIBUTION_REQUIRED"),item_ref:ref(input.item_ref,"OPS_FIXATION_ITEM_REQUIRED"),allocation_quantity:{value:allocated,unit_ref:"unit:EACH" as const},attributed_fixation_quantity:{value:attributed,unit_ref:"unit:EACH" as const},partial_fixation:attributed<allocated,whole_relationship_fixation_asserted:false as const,...(input.destination_or_commitment_ref?{destination_or_commitment_ref:ref(input.destination_or_commitment_ref,"OPS_FIXATION_DESTINATION_INVALID")}:{}) ,...(input.process_or_usage_ref?{process_or_usage_ref:ref(input.process_or_usage_ref,"OPS_FIXATION_USAGE_INVALID")}:{}) ,occurred_at,effected_at,policy_ref:input.policy.changeability_boundary_policy_ref,policy_version:input.policy.changeability_boundary_policy_version,evidence_refs:refs(input.evidence_refs,"OPS_FIXATION_EVIDENCE_REQUIRED"),qualification_refs:refs(input.qualification_refs,"OPS_FIXATION_QUALIFICATION_REQUIRED"),provenance_refs:refs(input.provenance_refs,"OPS_FIXATION_PROVENANCE_REQUIRED"),causal_lineage_refs:refs([...suppliedLineage,input.current_state.state_id,input.policy.policy_profile_id],"OPS_FIXATION_LINEAGE_REQUIRED"),evidence_as_of};const fixation_evidence_digest=await sha(value);return freeze({...value,fixation_evidence_id:`operations-allocation-fixation-evidence:sha256:${fixation_evidence_digest}`,fixation_evidence_digest,digest_algorithm:"SHA-256" as const,observational_only:true as const,establishes_changeability:false as const,establishes_constraint_result:false as const,establishes_admissibility:false as const,recommended:false as const,executable:false as const,grants_authority:false as const,grants_execution:false as const});
}
export async function verifyOperationsAllocationFixationEvidenceV1(v:OperationsAllocationFixationEvidenceV1){const d=await sha(semantic(v as unknown as Record<string,unknown>,"fixation_evidence_id","fixation_evidence_digest"));if(v.fixation_evidence_digest!==d||v.fixation_evidence_id!==`operations-allocation-fixation-evidence:sha256:${d}`||v.whole_relationship_fixation_asserted!==false||v.observational_only!==true||v.establishes_changeability!==false||v.establishes_constraint_result!==false||v.establishes_admissibility!==false||v.recommended!==false||v.executable!==false||v.grants_authority!==false||v.grants_execution!==false)throw new Error("OPS_FIXATION_INTEGRITY_INVALID");}

export async function createOperationsAllocationFixationEvidenceCoverageV1(input:Readonly<{version:1;policy:OperationsInterventionCurrentPolicyProfileV1;current_state:OperationsGovernedAllocationStateV1;evidence_selection_ref:string;allocation_relationship_ref:string;covered_fixation_class_keys:readonly string[];coverage_from:string;coverage_through:string;coverage_basis_ref:string;coverage_status:OperationsFixationCoverageStatusV1;evidence_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[]}>):Promise<OperationsAllocationFixationEvidenceCoverageV1>{
 if(input.version!==1)throw new Error("OPS_FIXATION_COVERAGE_VERSION_UNSUPPORTED");reject(input,"OPS_FIXATION_COVERAGE_UNSAFE_INPUT");await exact(input);if(!new Set(["COMPLETE","PARTIAL","INSUFFICIENT"]).has(input.coverage_status))throw new Error("OPS_FIXATION_COVERAGE_STATUS_INVALID");const covered=[...new Set(input.covered_fixation_class_keys.map(x=>token(x,"OPS_FIXATION_COVERAGE_CLASS_INVALID")))].sort(),supported=input.policy.fixation_classes.map(x=>x.fixation_class_key).sort();if(covered.some(x=>!supported.includes(x)))throw new Error("OPS_FIXATION_COVERAGE_CLASS_UNSUPPORTED");if(input.coverage_status==="COMPLETE"&&canonical(covered)!==canonical(supported))throw new Error("OPS_FIXATION_COVERAGE_COMPLETE_CLASSES_REQUIRED");const coverage_from=time(input.coverage_from,"OPS_FIXATION_COVERAGE_FROM_INVALID"),coverage_through=time(input.coverage_through,"OPS_FIXATION_COVERAGE_THROUGH_INVALID");if(Date.parse(coverage_from)>Date.parse(coverage_through)||coverage_through!==input.current_state.evidence_as_of)throw new Error("OPS_FIXATION_COVERAGE_TIME_MISMATCH");const value={version:1 as const,request_id:input.current_state.request_id,company_id:input.current_state.company_id,scope_id:input.current_state.scope_id,scope_digest:input.current_state.scope_digest,evidence_selection_ref:ref(input.evidence_selection_ref,"OPS_FIXATION_COVERAGE_SELECTION_REQUIRED"),domain_context_ref:input.policy.domain_context_ref,domain_context_digest:input.policy.domain_context_digest,policy_profile_ref:input.policy.policy_profile_id,policy_profile_digest:input.policy.policy_profile_digest,allocation_relationship_ref:ref(input.allocation_relationship_ref,"OPS_FIXATION_COVERAGE_RELATIONSHIP_REQUIRED"),allocation_current_state_ref:input.current_state.state_id,covered_fixation_class_keys:covered,coverage_from,coverage_through,coverage_basis_ref:ref(input.coverage_basis_ref,"OPS_FIXATION_COVERAGE_BASIS_REQUIRED"),coverage_status:input.coverage_status,evidence_refs:refs(input.evidence_refs,"OPS_FIXATION_COVERAGE_EVIDENCE_REQUIRED"),qualification_refs:refs(input.qualification_refs,"OPS_FIXATION_COVERAGE_QUALIFICATION_REQUIRED"),provenance_refs:refs(input.provenance_refs,"OPS_FIXATION_COVERAGE_PROVENANCE_REQUIRED"),causal_lineage_refs:refs([...input.causal_lineage_refs,input.current_state.state_id,input.policy.policy_profile_id],"OPS_FIXATION_COVERAGE_LINEAGE_REQUIRED")};const coverage_digest=await sha(value);return freeze({...value,coverage_id:`operations-allocation-fixation-coverage:sha256:${coverage_digest}`,coverage_digest,digest_algorithm:"SHA-256" as const,observational_only:true as const,asserts_event_absence:false as const,establishes_changeability:false as const,recommended:false as const,executable:false as const,grants_authority:false as const,grants_execution:false as const});
}
