import type { KnowledgeProjectionManifestV1 } from "../../knowledge-exposure/knowledge.exposure.contracts.v1";
import type { OutboundDisclosureDispatchEligibilityV1 } from "../outbound.disclosure.contracts.v1";
export type GovernedEmailFailureCode="EMAIL_DISCLOSURE_REQUIRED"|"EMAIL_CHANNEL_NOT_ADMITTED"|"EMAIL_REPRESENTATION_NOT_SUPPORTED"|"EMAIL_DISCLOSURE_EXPIRED"|"EMAIL_MANIFEST_SUBSTITUTED"|"EMAIL_PROJECTION_SUBSTITUTED"|"EMAIL_PROJECTION_MUTATED"|"EMAIL_PAYLOAD_TOO_LARGE"|"EMAIL_RECIPIENT_RESOLUTION_FAILED"|"EMAIL_RECIPIENT_SUBSTITUTED"|"EMAIL_FANOUT_NOT_ADMITTED"|"EMAIL_PROVIDER_FAILURE"|"EMAIL_DELIVERY_EVIDENCE_FAILED";
export class GovernedEmailError extends Error{constructor(readonly code:GovernedEmailFailureCode){super(code);this.name="GovernedEmailError";}}
export interface SealedGovernedEmailV1{readonly version:1;readonly eligibility:OutboundDisclosureDispatchEligibilityV1;readonly manifest:KnowledgeProjectionManifestV1;readonly manifest_id:string;readonly projection_digest:string;readonly canonical_projection:string;readonly canonical_projection_digest:string;readonly subject:"PlannerAgent disclosure";readonly content_type:"application/json; charset=utf-8";readonly correlation_id:string;readonly causal_references:readonly string[];}
export interface GovernedEmailEndpointV1{readonly recipient_id:string;readonly entitlement_reference:string;readonly endpoint_reference:string;readonly address:string;}
export interface GovernedEmailEndpointResolverV1{resolve(recipientId:string,entitlementReference:string):Promise<GovernedEmailEndpointV1|null>;}
export interface GovernedEmailProviderResultV1{readonly ok:boolean;readonly provider_message_reference?:string;}
export interface GovernedEmailProviderV1{readonly provider_id:string;send(request:Readonly<{to:string;subject:string;body:string;content_type:string}>):Promise<GovernedEmailProviderResultV1>;}
export interface GovernedEmailDeliveryEvidenceV1{readonly version:1;readonly delivery_evidence_id:string;readonly disclosure_id:string;readonly disclosure_consumption_id:string;readonly recipient_id:string;readonly entitlement_reference:string;readonly endpoint_reference:string;readonly projection_digest:string;readonly canonical_projection_digest:string;readonly request_digest:string;readonly provider:string;readonly dispatched_at:string;readonly status:"SUCCEEDED"|"FAILED";readonly provider_message_digest?:string;readonly failure_code?:GovernedEmailFailureCode;readonly causal_references:readonly string[];}
export interface GovernedEmailEvidenceRepositoryV1{reserve(disclosureConsumptionId:string,provider:string,at:string):Promise<boolean>;append(evidence:GovernedEmailDeliveryEvidenceV1):Promise<void>;}
export interface GovernedEmailDeliveryResultV1{readonly version:1;readonly status:"SUCCEEDED";readonly provider:string;readonly delivery_evidence:GovernedEmailDeliveryEvidenceV1;readonly content_returned:false;}
