import { createHash } from "node:crypto";
import { deepCopyAndFreeze,knowledgeProjectionDigestV1 } from "../../knowledge-exposure/knowledge.projection.guard.v1";
import type { KnowledgeProjectionManifestV1 } from "../../knowledge-exposure/knowledge.exposure.contracts.v1";
import type { OutboundDisclosureDispatchEligibilityV1 } from "../outbound.disclosure.contracts.v1";
import { GovernedEmailError,type SealedGovernedEmailV1 } from "./governed.email.contracts.v1";
const hash=(s:string)=>createHash("sha256").update(s,"utf8").digest("hex");
function canonical(v:unknown):string{if(v===null||typeof v==="boolean")return JSON.stringify(v);if(typeof v==="number"){if(!Number.isFinite(v))throw new GovernedEmailError("EMAIL_PROJECTION_SUBSTITUTED");return JSON.stringify(v);}if(typeof v==="string")return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return`{${Object.keys(v as object).sort().map(k=>`${JSON.stringify(k)}:${canonical((v as any)[k])}`).join(",")}}`;throw new GovernedEmailError("EMAIL_PROJECTION_SUBSTITUTED");}
export function sealGovernedEmailV1(input:{readonly eligibility:OutboundDisclosureDispatchEligibilityV1;readonly manifest:KnowledgeProjectionManifestV1;readonly projection:Readonly<Record<string,unknown>>;}):SealedGovernedEmailV1{const e=input?.eligibility,m=input?.manifest;if(!e||!Object.isFrozen(e)||e.transport_executed!==false)throw new GovernedEmailError("EMAIL_DISCLOSURE_REQUIRED");if(e.channel!=="EMAIL")throw new GovernedEmailError("EMAIL_CHANNEL_NOT_ADMITTED");if(e.representation!=="STRUCTURED_JSON"||m?.representation!=="STRUCTURED_JSON")throw new GovernedEmailError("EMAIL_REPRESENTATION_NOT_SUPPORTED");const manifestId=`${m.schema_id}@${m.schema_version}`;if(manifestId!==e.manifest_id||m.projection_digest!==e.projection_digest||knowledgeProjectionDigestV1(m)!==e.projection_digest)throw new GovernedEmailError("EMAIL_MANIFEST_SUBSTITUTED");const allowed=new Set(m.included_fields.map(f=>f.field)),keys=Object.keys(input.projection);if(keys.length!==allowed.size||keys.some(k=>!allowed.has(k)))throw new GovernedEmailError("EMAIL_PROJECTION_SUBSTITUTED");const body=canonical(input.projection);if(body.length>262144)throw new GovernedEmailError("EMAIL_PAYLOAD_TOO_LARGE");return deepCopyAndFreeze({version:1,eligibility:e,manifest:m,manifest_id:manifestId,projection_digest:e.projection_digest,canonical_projection:body,canonical_projection_digest:hash(body),subject:"PlannerAgent disclosure",content_type:"application/json; charset=utf-8",correlation_id:e.correlation_id,causal_references:e.causal_references}) as SealedGovernedEmailV1;}
export function verifySealedGovernedEmailV1(s:SealedGovernedEmailV1,now:string){if(!s||!Object.isFrozen(s)||!Object.isFrozen(s.eligibility))throw new GovernedEmailError("EMAIL_DISCLOSURE_REQUIRED");if(s.eligibility.channel!=="EMAIL")throw new GovernedEmailError("EMAIL_CHANNEL_NOT_ADMITTED");if(s.eligibility.representation!=="STRUCTURED_JSON"||s.manifest.representation!=="STRUCTURED_JSON")throw new GovernedEmailError("EMAIL_REPRESENTATION_NOT_SUPPORTED");if(Date.parse(s.eligibility.expires_at)<=Date.parse(now))throw new GovernedEmailError("EMAIL_DISCLOSURE_EXPIRED");if(s.manifest_id!==s.eligibility.manifest_id||s.projection_digest!==s.eligibility.projection_digest||knowledgeProjectionDigestV1(s.manifest)!==s.projection_digest)throw new GovernedEmailError("EMAIL_MANIFEST_SUBSTITUTED");if(hash(s.canonical_projection)!==s.canonical_projection_digest)throw new GovernedEmailError("EMAIL_PROJECTION_MUTATED");}
