import { applyD1Migrations, env } from "cloudflare:test";
import { beforeAll, beforeEach, describe, expect, it } from "vitest";
import m12 from "../../../../migrations/0012_knowledge_exposure_persistence.sql?raw";
import m14 from "../../../../migrations/0014_outbound_disclosure_admission.sql?raw";
import m15 from "../../../../migrations/0015_governed_email_delivery.sql?raw";
import m16 from "../../../../migrations/0016_governed_twilio_delivery.sql?raw";
import m17 from "../../../../migrations/0017_platform_operational_alert.sql?raw";
import { deepCopyAndFreeze } from "../../knowledge-exposure/knowledge.projection.guard.v1";
import { PLATFORM_ALERT_POLICY_ID,PLATFORM_ALERT_POLICY_VERSION,PLATFORM_OWNER_ID,type PlatformAlertAdmissionRequestV1,type VerifiedPlatformAlertSourceV1 } from "../platform.alert.contracts.v1";
import { D1PlatformAlertRepositoryV1,D1PlatformAlertSourceRepositoryV1 } from "../platform.alert.d1.v1";
import { PlatformAlertAdmissionRuntimeV1 } from "../platform.alert.runtime.v1";

const db=env.POLICIES_DB,DIGEST="a".repeat(64),NOW="2026-08-02T10:01:00.000Z";
const queries=(sql:string)=>sql.split(/;\s*\r?\n(?=CREATE (?:TABLE|(?:UNIQUE )?INDEX|TRIGGER))/).map(q=>q.trim()).filter(Boolean).map(q=>q.endsWith(";")?q:`${q};`);
beforeAll(async()=>applyD1Migrations(db,[m12,m14,m15,m16,m17].map((sql,i)=>({name:`pa-m${i}`,queries:queries(sql)}))));

async function upstream(index:number,channel:"EMAIL"|"SMS") {
  const suffix=String(index),decision=`decision:${suffix}`,binding=`binding:${suffix}`,knowledgeConsumption=`knowledge-consumption:${suffix}`,disclosure=`disclosure:${suffix}`,consumption=`disclosure-consumption:${suffix}`;
  await db.prepare(`INSERT INTO knowledge_exposure_decisions VALUES (${Array(30).fill("?").join(",")})`).bind(decision,`request:${suffix}`,"ADMITTED",`participation:${suffix}`,`principal:${suffix}`,`session:${suffix}`,`membership:${suffix}`,"tenant:private","company:private",`authority:${suffix}`,null,"OUTBOUND_DISCLOSURE","CUSTOMER_QUOTATION_DISCLOSURE","POLICY","AUTHORIZED_BUSINESS_RECIPIENT",`recipient:${suffix}`,"INTERNAL","TENANT_LOCAL","EU","NO_RETENTION",`schema:${suffix}@1`,DIGEST,"[]","2026-08-02T10:00:00.000Z","2026-08-02T10:02:00.000Z","[]",`knowledge-evidence:${suffix}`,"correlation:platform-alert",'[]',`canonical:${suffix}`).run();
  await db.prepare("INSERT INTO knowledge_exposure_projection_bindings VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").bind(binding,decision,`schema:${suffix}@1`,DIGEST,"[]","OUTBOUND_DISCLOSURE","CUSTOMER_QUOTATION_DISCLOSURE","AUTHORIZED_BUSINESS_RECIPIENT",`recipient:${suffix}`,"tenant:private","company:private","2026-08-02T10:00:00.000Z").run();
  await db.prepare("INSERT INTO knowledge_exposure_consumptions VALUES (?,?,?,?,?,?,?,?,?,?)").bind(knowledgeConsumption,decision,binding,"wu4a","OUTBOUND_COMMUNICATION",`recipient:${suffix}`,"2026-08-02T10:00:10.000Z","correlation:platform-alert","[]","CONSUMED").run();
  await db.prepare("INSERT INTO outbound_disclosure_admissions VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(disclosure,decision,binding,knowledgeConsumption,`authority:${suffix}`,"[]","tenant:private","company:private","CUSTOMER_QUOTATION_DISCLOSURE","TENANT_OPERATIONAL_DISCLOSURE",`schema:${suffix}@1`,DIGEST,`recipient:${suffix}`,"AUTHORIZED_BUSINESS_RECIPIENT",`entitlement:${suffix}`,channel,"STRUCTURED_JSON","INTERNAL","OUTBOUND_DISCLOSURE_POLICY_V1","2026-08-02T10:00:20.000Z","2026-08-02T10:01:20.000Z","correlation:platform-alert","[]",`canonical-disclosure:${suffix}`).run();
  await db.prepare("INSERT INTO outbound_disclosure_consumptions VALUES (?,?,?,?,?,?,?)").bind(consumption,disclosure,channel==="EMAIL"?"wu4b":"wu4c","2026-08-02T10:00:30.000Z","correlation:platform-alert","[]","CONSUMED").run();
  return {suffix,decision,binding,disclosure,consumption};
}

beforeEach(async()=>{
  for(const table of ["platform_alert_audit_events","platform_alert_suppressions","platform_alert_admission_decisions","platform_alert_source_bindings","platform_alert_intents","governed_email_delivery_evidence","governed_email_delivery_reservations","governed_twilio_delivery_evidence","governed_twilio_dispatch_reservations","outbound_disclosure_audit_events","outbound_disclosure_consumptions","outbound_disclosure_admissions","knowledge_exposure_audit_events","knowledge_exposure_consumptions","knowledge_exposure_projection_bindings","knowledge_exposure_decisions"])await db.prepare(`DELETE FROM ${table}`).run();
  const email=await upstream(1,"EMAIL");
  await db.prepare("INSERT INTO governed_email_delivery_reservations VALUES (?,?,?)").bind(email.consumption,"email-relay","2026-08-02T10:00:40.000Z").run();
  await db.prepare("INSERT INTO governed_email_delivery_evidence VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind("email-evidence:failed",email.disclosure,email.consumption,"recipient:1","entitlement:1","endpoint:opaque",DIGEST,"b".repeat(64),"c".repeat(64),"email-relay","2026-08-02T10:00:40.000Z","FAILED",null,"EMAIL_PROVIDER_FAILURE",JSON.stringify(["audit:delivery"])).run();
  const twilio=await upstream(2,"SMS");
  await db.prepare("INSERT INTO governed_twilio_dispatch_reservations VALUES (?,?,?,?,?)").bind(twilio.consumption,"sealed:2","SMS","TWILIO_SMS","2026-08-02T10:00:40.000Z").run();
  await db.prepare(`INSERT INTO governed_twilio_delivery_evidence VALUES (${Array(23).fill("?").join(",")})`).bind("twilio-evidence:indeterminate",twilio.disclosure,twilio.decision,twilio.binding,twilio.consumption,"sealed:2",DIGEST,"d".repeat(64),"entitlement:2","e".repeat(64),"SMS","TWILIO_SMS","twilio","sender:sms","CUSTOMER_QUOTATION_DISCLOSURE","tenant:private","company:private","2026-08-02T10:00:40.000Z","INDETERMINATE","GOVERNED_TWILIO_TIMEOUT",null,"correlation:platform-alert",JSON.stringify(["audit:delivery"])).run();
});

function request(source:VerifiedPlatformAlertSourceV1,correlation=source.correlation_id):PlatformAlertAdmissionRequestV1{return deepCopyAndFreeze({version:1,source_class:source.source_class,source_evidence_id:source.source_evidence_id,source_evidence_digest:source.source_evidence_digest,platform_owner_id:PLATFORM_OWNER_ID,communication_family:"PLATFORM_OPERATIONAL_ALERT",purpose:"GOVERNED_DELIVERY_REVIEW",policy_id:PLATFORM_ALERT_POLICY_ID,policy_version:PLATFORM_ALERT_POLICY_VERSION,requested_at:NOW,correlation_id:correlation,causal_references:[source.source_evidence_id,...source.causal_references]}) as PlatformAlertAdmissionRequestV1;}

describe("PA-WU1 platform alerts (actual D1)",()=>{
  it("applies exact durable schema and immutable source guards",async()=>{const rows=await db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'platform_alert_%' ORDER BY name").all<{name:string}>();expect(rows.results.map(r=>r.name)).toEqual(["platform_alert_admission_decisions","platform_alert_audit_events","platform_alert_intents","platform_alert_source_bindings","platform_alert_suppressions"]);expect((await db.prepare("PRAGMA foreign_keys").first<{foreign_keys:number}>())?.foreign_keys).toBe(1);});
  it.each([["WU4B_EMAIL_DELIVERY","email-evidence:failed","FAILED"],["WU4C_TWILIO_DELIVERY","twilio-evidence:indeterminate","INDETERMINATE"]] as const)("verifies durable %s evidence without returning content",async(sourceClass,id,outcome)=>{const value=await new D1PlatformAlertSourceRepositoryV1(db).resolve(sourceClass,id);expect(value).toMatchObject({source_class:sourceClass,source_evidence_id:id,source_outcome:outcome,tenant_reference_digest:expect.stringMatching(/^[a-f0-9]{64}$/)});expect(JSON.stringify(value)).not.toMatch(/private|endpoint:opaque|message|response|credential/i);});
  it("atomically admits once and suppresses duplicates across runtime instances",async()=>{const sources=new D1PlatformAlertSourceRepositoryV1(db),repository=new D1PlatformAlertRepositoryV1(db),value=(await sources.resolve("WU4C_TWILIO_DELIVERY","twilio-evidence:indeterminate"))!,input=request(value),a=new PlatformAlertAdmissionRuntimeV1({source:sources,repository}),b=new PlatformAlertAdmissionRuntimeV1({source:sources,repository});const results=await Promise.all([a.admit(input),b.admit(input)]);expect(results.map(x=>x.status).sort()).toEqual(["ADMITTED","SUPPRESSED"]);expect((await db.prepare("SELECT COUNT(*) count FROM platform_alert_intents").first<{count:number}>())?.count).toBe(1);expect((await db.prepare("SELECT COUNT(*) count FROM platform_alert_suppressions").first<{count:number}>())?.count).toBe(1);await expect(new PlatformAlertAdmissionRuntimeV1({source:sources,repository:new D1PlatformAlertRepositoryV1(db)}).admit(input)).resolves.toMatchObject({status:"SUPPRESSED"});});
  it("persists content-free admission, denial, duplicate, and suppression audit",async()=>{const sources=new D1PlatformAlertSourceRepositoryV1(db),repository=new D1PlatformAlertRepositoryV1(db),runtime=new PlatformAlertAdmissionRuntimeV1({source:sources,repository}),value=(await sources.resolve("WU4B_EMAIL_DELIVERY","email-evidence:failed"))!,input=request(value);await runtime.admit(input);await runtime.admit(input);await expect(runtime.admit(request({...value,source_evidence_id:"missing"} as any))).rejects.toBeDefined();const rows=await db.prepare("SELECT * FROM platform_alert_audit_events").all<Record<string,unknown>>(),text=JSON.stringify(rows.results);expect(rows.results.map(r=>r.event_kind)).toEqual(expect.arrayContaining(["SOURCE_VERIFIED","INTENT_CONSTRUCTED","ADMITTED","DENIED","DUPLICATE_DETECTED","SUPPRESSED"]));expect(text).not.toMatch(/endpoint:opaque|tenant:private|company:private|message text|auth.token|provider response/i);});
  it("makes intents, decisions, bindings, suppressions, and audit immutable",async()=>{const sources=new D1PlatformAlertSourceRepositoryV1(db),repository=new D1PlatformAlertRepositoryV1(db),value=(await sources.resolve("WU4B_EMAIL_DELIVERY","email-evidence:failed"))!,runtime=new PlatformAlertAdmissionRuntimeV1({source:sources,repository}),input=request(value);await runtime.admit(input);await runtime.admit(input);for(const table of ["platform_alert_intents","platform_alert_admission_decisions","platform_alert_source_bindings","platform_alert_suppressions","platform_alert_audit_events"]){await expect(db.prepare(`UPDATE ${table} SET rowid=rowid`).run()).rejects.toThrow(/IMMUTABLE/);await expect(db.prepare(`DELETE FROM ${table}`).run()).rejects.toThrow(/IMMUTABLE/);}});
});
