import{describe,expect,it}from"vitest";import{bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1}from"../operational.signal.evaluation.scope.v1";import{buildOperationalCockpitSnapshotV1}from"../operational.cockpit.snapshot.v1";import{buildOperationalCockpitManifestationV1}from"../operational.cockpit.manifestation.v1";import{qualifyCockpitSignalEvidenceV1,type CockpitSignalFamilyV1,type OperationalEvidenceKindV1}from"../../minimum-operational-evidence";
async function fixtures(sufficient:readonly CockpitSignalFamilyV1[]=["DATA_AWARENESS","PLAN_COHERENCE","REALITY_STABILITY","DECISION_PRESSURE"],reality="STABLE"as const,pressure:any={level:"HIGH",pressure_type:"DATA_QUALITY",blocked_reason:"UNRELIABLE_REALITY"}){const scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"REQUEST_DATASET",request_id:"r1",company_id:"c1",domain:"supply_chain",evidence_selection_ref:"selection:1",source_snapshot_ref:"source:1"}),binding=await bindOperationalSignalsToScopeV1({scope,request_id:"r1",company_id:"c1",evidence_as_of:"2026-08-13T10:00:00Z",evaluated_at:"2026-08-13T10:01:00Z"}),snapshot=await buildOperationalCockpitSnapshotV1({request_id:"r1",company_id:"c1",domain:"supply_chain",evaluation_scope:binding,data_awareness:"SNAPSHOT",plan:{level:"INCOHERENT",source:"ASSUMED",confidence:0,score:0,quality:"UNUSABLE",quality_score:0},reality:{state:reality,confidence:.8,reasons:["reason"]},decision_pressure:pressure});const evidence:Record<CockpitSignalFamilyV1,OperationalEvidenceKindV1[]>={DATA_AWARENESS:["INVENTORY_SNAPSHOT"],PLAN_COHERENCE:["PLAN_ORDER"],REALITY_STABILITY:["REALITY_ASSESSMENT"],DECISION_PRESSURE:["DEMAND_ORDER","INVENTORY_POSITION","PROBLEM_CLASSIFICATION","CORRECTION_EFFECT","OPTIMIZER_SHORTAGE_RESULT","EXECUTION_GAP_ASSESSMENT"]};const deps:any=["DEMAND_AND_INVENTORY_SHARE_ITEM_IDENTITY","PRESSURE_QUANTITIES_SHARE_UNIT"];const qualifications=await Promise.all((Object.keys(evidence)as CockpitSignalFamilyV1[]).map(f=>qualifyCockpitSignalEvidenceV1({signal_family:f,evaluation_scope:binding,evidence_scope:binding,presented_evidence:(sufficient.includes(f)?evidence[f]:[]).map(kind=>({kind,occurrences:1})),satisfied_dependencies:deps,evidence_qualification_refs:[`e:${f}`],qualified_at:"2026-08-13T10:02:00Z"})));return{snapshot,qualifications};}
describe("COCKPIT-ASSERT-WU1",()=>{
 it("represents zero through four independently manifested families",async()=>{const fs=["DATA_AWARENESS","PLAN_COHERENCE","REALITY_STABILITY","DECISION_PRESSURE"]as const;for(let n=0;n<=4;n++){const x=await fixtures(fs.slice(0,n)),m=await buildOperationalCockpitManifestationV1({...x,manifested_at:"2026-08-13T10:03:00Z"});expect(m.manifested_family_count).toBe(n);for(const[f,a]of Object.entries(m.assertability))expect(a.status==="ASSERTABLE").toBe(fs.slice(0,n).includes(f as any));}});
 it("suppresses fallback SNAPSHOT and INCOHERENT when MOE is insufficient",async()=>{const x=await fixtures(["REALITY_STABILITY","DECISION_PRESSURE"]),m=await buildOperationalCockpitManifestationV1({...x,manifested_at:"2026-08-13T10:03:00Z"});expect(m.assertability.DATA_AWARENESS).toMatchObject({status:"NOT_ASSERTABLE",reason_codes:["MOE_INSUFFICIENT"]});expect(m.assertability.PLAN_COHERENCE).not.toHaveProperty("manifested_state");});
 it.each(["STABLE","SHIFTING","UNSTABLE"]as const)("manifests grounded Reality %s",async state=>{const x=await fixtures(undefined,state),m=await buildOperationalCockpitManifestationV1({...x,manifested_at:"2026-08-13T10:03:00Z"});expect(m.assertability.REALITY_STABILITY).toMatchObject({status:"ASSERTABLE",manifested_state:state});});
 it("never manifests ASSUMED even with sufficient MOE",async()=>{const x=await fixtures(undefined,"ASSUMED"),m=await buildOperationalCockpitManifestationV1({...x,manifested_at:"2026-08-13T10:03:00Z"});expect(m.assertability.REALITY_STABILITY).toMatchObject({status:"NOT_ASSERTABLE",reason_codes:["INSUFFICIENT_GROUNDING"]});expect(m.assertability.REALITY_STABILITY).not.toHaveProperty("manifested_state");});
 it("preserves manifestable Pressure with DATA_QUALITY and UNRELIABLE_REALITY qualifiers",async()=>{const x=await fixtures(),m=await buildOperationalCockpitManifestationV1({...x,manifested_at:"2026-08-13T10:03:00Z"});expect(m.assertability.DECISION_PRESSURE).toMatchObject({status:"ASSERTABLE",manifested_state:"HIGH",pressure_type:"DATA_QUALITY",blocked_reason:"UNRELIABLE_REALITY"});});
 it("is deterministic, content-free, and fails closed on substitution",async()=>{const x=await fixtures(),a=await buildOperationalCockpitManifestationV1({...x,manifested_at:"2026-08-13T10:03:00Z"}),b=await buildOperationalCockpitManifestationV1({...x,manifested_at:"2026-08-13T10:03:00Z"});expect(a).toEqual(b);expect(JSON.stringify(a)).not.toMatch(/orders|movements|credentials|business_payload/i);await expect(buildOperationalCockpitManifestationV1({snapshot:x.snapshot,qualifications:x.qualifications.slice(0,3),manifested_at:"2026-08-13T10:03:00Z"})).rejects.toThrow("COCKPIT_MANIFESTATION_QUALIFICATIONS_INVALID");});
});
