import{describe,expect,it}from"vitest";
import{bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1}from"../operational.signal.evaluation.scope.v1";
import{buildOperationalCockpitSnapshotV1,type CanonicalCockpitSignalBindingV1}from"../operational.cockpit.snapshot.v1";
import{evaluateCockpitSignalAssertabilityV1,COCKPIT_SIGNAL_CAPABILITIES_V1}from"../cockpit.signal.assertability.v1";
import{composeCanonicalOperationalRealityV1,type CanonicalOperationalRealityEvidenceV1}from"../../reality/canonical.operational.reality.composition.v1";
import{createCanonicalDecisionPressureProducerCertificationV1}from"../../decision/canonical.decision.pressure.normalization.policy.v1";
import{createCanonicalDecisionPressureDimensionV1,type CanonicalDecisionPressureDimensionV1}from"../../decision/canonical.decision.pressure.dimension.v1";
import{composeCanonicalDecisionPressureV1,type CanonicalPressureDimensionOperandV1}from"../../decision/canonical.decision.pressure.composition.v1";
import{createCanonicalExplanationBasisV1}from"../../explainability/canonicalExplanation";
import{bindAttentionV1}from"../../attention/canonicalAttention";
const at="2026-08-17T10:00:00.000Z",evaluated="2026-08-17T10:01:00.000Z",hex=(x:string)=>x.repeat(64).slice(0,64),meta={evidence_refs:["evidence:canonical"],qualification_refs:["qualification:canonical"],provenance_refs:["provenance:canonical"],causal_lineage_refs:["lineage:canonical"]};
async function scope(company="company-1"){const s=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"REQUEST_DATASET",request_id:"request-1",company_id:company,domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1"});return bindOperationalSignalsToScopeV1({scope:s,request_id:"request-1",company_id:company,evidence_as_of:at,evaluated_at:evaluated})}
async function reality(b:Awaited<ReturnType<typeof scope>>,conflict=false){const e=(n:number,claim:string):CanonicalOperationalRealityEvidenceV1=>({version:1,tenant_id:"tenant-1",company_id:b.scope.company_id,request_id:b.scope.request_id,scope_id:b.scope.scope_id,scope_digest:b.scope.scope_digest,evidence_as_of:at,evidence_ref:`evidence:${n}`,evidence_digest:hex(String(n)),source_identity_ref:`source:${n}`,source_namespace:`namespace:${n}`,semantic_key:"inventory:item",claim_digest:hex(claim),evidence_role:"CURRENT_FACT",canonical_subject_refs:["item:1"],canonical_location_refs:["location:1"],qualification_refs:[`qualification:${n}`],provenance_refs:[`provenance:${n}`],causal_lineage_refs:[`lineage:${n}`]});return composeCanonicalOperationalRealityV1({version:1,tenant_id:"tenant-1",evaluation_scope:b,evidence:conflict?[e(1,"a"),e(2,"b")]:[e(1,"a")],coverage:[]})}
async function dim(b:Awaited<ReturnType<typeof scope>>,kind:"IMPACT"|"URGENCY"|"COST_OF_WAITING",value:number|string){const continuous=typeof value==="number",cert=await createCanonicalDecisionPressureProducerCertificationV1({version:1,dimension:kind,producer_id:`producer:${kind}`,producer_version:"1",normalization_policy_id:`policy:${kind}`,normalization_policy_version:"1",domain_profile_id:"domain:operations",domain_profile_version:"1",supported_scope_kinds:["REQUEST_DATASET"],endpoint_semantics:"CANONICAL_PRESSURE_DIMENSION_ENDPOINTS_V1",monotonicity:"NON_DECREASING_CANONICAL_MAGNITUDE",reference_basis_semantics:"canonical cockpit fixture",evidence_requirement_refs:["requirement:evidence"],qualification_requirement_refs:["requirement:qualification"],composition_restriction:"DOMAIN_SCOPED_PROJECTION_NO_GENERIC_CHILD_COMPOSITION",provenance_required:true,causal_lineage_required:true,...(continuous?{projection_mode:"CONTINUOUS"as const,precision_policy:{kind:"DECIMAL_PLACES"as const,decimal_places:4}}:{projection_mode:"ORDINAL"as const,ordinal_vocabulary:["LOW","MODERATE","HIGH","CRITICAL"]})});return createCanonicalDecisionPressureDimensionV1({version:1,dimension:kind,request_id:"request-1",company_id:"company-1",evaluation_scope:b,evidence_as_of:at,evaluated_at:evaluated,producer_certification:cert,normalization_input_refs:[`input:${kind}`],...meta,...(continuous?{projection_mode:"CONTINUOUS"as const,value,numerator_ref:`numerator:${kind}`,denominator_ref:`denominator:${kind}`,precision_decimal_places:4,...(kind==="URGENCY"?{decision_opportunity_status:"USEFUL_DECISION_REMAINS"as const}:{})}:{projection_mode:"ORDINAL"as const,ordinal_state:value as"HIGH"})})}
async function pressure(b:Awaited<ReturnType<typeof scope>>,partial=false){const ds=await Promise.all([dim(b,"IMPACT","HIGH"),dim(b,"URGENCY",.8),dim(b,"COST_OF_WAITING",0)]),op=(d:CanonicalDecisionPressureDimensionV1):CanonicalPressureDimensionOperandV1=>({dimension:d.dimension,status:"ESTABLISHED",value:d,...meta});return composeCanonicalDecisionPressureV1({version:1,impact:op(ds[0]!),urgency:op(ds[1]!),cost_of_waiting:partial?{dimension:"COST_OF_WAITING",status:"UNRESOLVED",...meta}:op(ds[2]!)})}
function signal(b:Awaited<ReturnType<typeof scope>>,kind:string):CanonicalCockpitSignalBindingV1{return{tenant_id:"tenant-1",company_id:"company-1",request_id:"request-1",scope_id:b.scope.scope_id,scope_digest:b.scope.scope_digest,artifact_ref:`canonical:${kind}`,artifact_digest:hex("a"),...meta}}
async function input(opts:{conflict?:boolean;partial?:boolean;attention?:boolean}={}){const b=await scope(),r=await reality(b,opts.conflict),p=await pressure(b,opts.partial),e=await createCanonicalExplanationBasisV1({version:1,reality:r,pressure:p}),a=opts.attention?await bindAttentionV1({version:1,subscription:{attention_id:"attention:1",tenant_id:"tenant-1",company_id:"company-1",context_id:"request-1",actor_id:"actor:1",scope:"ORDER",trigger:"DECISION_PRESSURE_HIGH",priority:"HIGH",status:"ACTIVE",noise_policy:"SILENT_UNLESS_TRIGGERED",human_request:"watch",created_at:at,updated_at:at},lifecycle:{attention_id:"attention:1",status:"ACTIVE",lifecycleState:"ACTIVE",realityPresence:"PRESENT",cancellable:false,humanReviewRequired:false,reason:"active",summary:["active"]},pressure:p}):undefined;return{request_id:"request-1",company_id:"company-1",domain:"operations",evaluation_scope:b,data_awareness:"STRUCTURAL"as const,plan:{level:"COHERENT"as const,source:"MASTER"as const,confidence:1,score:1,quality:"HIGH"as const,quality_score:1},reality:{state:"STABLE"as const,confidence:1,reasons:[]},decision_pressure:{level:"HIGH"as const,pressure_type:"EXECUTION"as const},canonical_cognition:{tenant_id:"tenant-1",data_awareness:signal(b,"awareness"),plan_coherence:signal(b,"plan"),reality:r,decision_pressure:p,explanation:e,...(a?{working_attention:a}:{}),pressure_compatibility_projection:"LEGACY_PUBLIC_V2_PRESENTATION_ONLY"as const,current_reality:true as const,counterfactual:false as const,tier_independent:true as const}}}
function q(x:Awaited<ReturnType<typeof buildOperationalCockpitSnapshotV1>>,family:"REALITY_STABILITY"|"DECISION_PRESSURE"){return{signal_family:family,capability_id:COCKPIT_SIGNAL_CAPABILITIES_V1[family],request_id:x.request_id,company_id:x.company_id,scope_id:x.evaluation_scope.scope.scope_id,scope_digest:x.evaluation_scope.scope.scope_digest,evidence_selection_ref:x.source_evidence.evidence_selection_ref,evidence_as_of:x.evidence_as_of,qualification_id:"q:1",qualification_digest:hex("b"),moe_result:{status:"SUFFICIENT",sufficient:true}}as any}
describe("CANONICAL-COCKPIT-COMPLETION-WU1",()=>{
 it("reuses and deterministically verifies the existing snapshot",async()=>{const i=await input(),a=await buildOperationalCockpitSnapshotV1(i),b=await buildOperationalCockpitSnapshotV1(i);expect(a.snapshot_id).toBe(b.snapshot_id);expect(a.canonical_cognition?.explanation.basis_id).toBe(i.canonical_cognition.explanation.basis_id)});
 it("binds the four signal families to exact canonical scope",async()=>{const x=await buildOperationalCockpitSnapshotV1(await input());expect(x.canonical_cognition).toMatchObject({tenant_id:"tenant-1",current_reality:true,counterfactual:false,tier_independent:true});expect(x.lineage_refs).toEqual(expect.arrayContaining(["canonical:awareness","canonical:plan",x.canonical_cognition!.reality.composition_id,x.canonical_cognition!.decision_pressure.pressure_id]))});
 it("manifests canonical Pressure completeness instead of legacy scalar truth",async()=>{const x=await buildOperationalCockpitSnapshotV1(await input());expect((await evaluateCockpitSignalAssertabilityV1(x,q(x,"DECISION_PRESSURE"))).manifested_state).toBe("COMPLETE");expect(x.signals.decision_pressure.level).toBe("HIGH")});
 it("preserves zero Cost of Waiting",async()=>expect((await buildOperationalCockpitSnapshotV1(await input())).canonical_cognition?.decision_pressure.components[2]?.continuous_value).toBe(0));
 it("preserves partial Pressure instead of fake LOW",async()=>{const x=await buildOperationalCockpitSnapshotV1(await input({partial:true}));expect((await evaluateCockpitSignalAssertabilityV1(x,q(x,"DECISION_PRESSURE"))).manifested_state).toBe("QUALIFIED_PARTIAL_UNRESOLVED")});
 it("preserves unresolved multi-source Reality without selecting a winner",async()=>{const x=await buildOperationalCockpitSnapshotV1(await input({conflict:true}));expect((await evaluateCockpitSignalAssertabilityV1(x,q(x,"REALITY_STABILITY"))).manifested_state).toBe("UNRESOLVED_CONFLICT");expect(x.canonical_cognition?.reality.semantic_groups[0]).not.toHaveProperty("selected_evidence_ref")});
 it("references existing Working Attention without notification or mutation",async()=>{const x=await buildOperationalCockpitSnapshotV1(await input({attention:true}));expect(x.canonical_cognition?.working_attention).toMatchObject({attention_origin:"USER_SUBSCRIPTION",notification_requested:false});expect(x.lineage_refs).toContain(x.canonical_cognition?.working_attention?.binding_id)});
 it.each(["VISION","GRADUATE","JUNIOR","SENIOR","PRINCIPAL","CHARTER"])("keeps canonical truth tier-independent for %s",async()=>expect((await buildOperationalCockpitSnapshotV1(await input())).canonical_cognition?.tier_independent).toBe(true));
 it.each(["commercial_plan","credit_balance","economic_capacity","provider","model","simulation","optimizer_candidate","raw_source_rows"])("rejects %s contamination",async key=>{const i:any=await input();i.canonical_cognition={...i.canonical_cognition,[key]:"forbidden"};await expect(buildOperationalCockpitSnapshotV1(i)).rejects.toThrow("COCKPIT_CANONICAL_UNSAFE_INPUT")});
 it("rejects cross-client signal cognition",async()=>{const i:any=await input();i.canonical_cognition={...i.canonical_cognition,data_awareness:{...i.canonical_cognition.data_awareness,tenant_id:"tenant-2"}};await expect(buildOperationalCockpitSnapshotV1(i)).rejects.toThrow("COCKPIT_CANONICAL_SIGNAL_MISMATCH")});
 it("rejects counterfactual explanation as current cockpit",async()=>{const i:any=await input();i.canonical_cognition={...i.canonical_cognition,explanation:{...i.canonical_cognition.explanation,context:{mode:"COUNTERFACTUAL",scenario_ref:"scenario:1"}}};await expect(buildOperationalCockpitSnapshotV1(i)).rejects.toThrow()});
 it("remains observational, non-recommending, non-authoritative and non-executing",async()=>{const x=await buildOperationalCockpitSnapshotV1(await input());expect(x).toMatchObject({observational_only:true,grants_execution:false});expect(x.canonical_cognition?.explanation).toMatchObject({recommended:false,executable:false,grants_authority:false,grants_execution:false})});
});
