import {verifyCanonicalDecisionPressureCompositionV1,type CanonicalDecisionPressureCompositionV1} from "../decision/canonical.decision.pressure.composition.v1";
import type {AttentionLifecycleEvaluation} from "./attention.lifecycle";
import type {AttentionSubscription} from "./attention.types";

export type CanonicalPressureAttentionBindingV1=Readonly<{version:1;attention_id:string;attention_origin:"USER_SUBSCRIPTION";tenant_id:string;company_id:string;context_id:string;scope_id:string;scope_digest:string;attention_subject_ref:string;pressure_ref:string;pressure_digest:string;pressure_completeness:CanonicalDecisionPressureCompositionV1["completeness_status"];component_statuses:readonly Readonly<{dimension:"IMPACT"|"URGENCY"|"COST_OF_WAITING";status:string}>[];lifecycle_state:AttentionLifecycleEvaluation["lifecycleState"];continuity_action:"OPENED"|"MAINTAINED"|"CLOSED";uncertainty_preserved:boolean;notification_requested:false;recommended:false;executable:false;grants_authority:false;grants_execution:false;learning_record_created:false;evidence_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[];binding_id:string;binding_digest:string;digest_algorithm:"SHA-256"}>;
const forbidden=["attention_priority_score","pressure_level","authority_tier","subscription_tier","commercial_plan","credit_balance","provider","model","approval","delegation","recommendation","execution_payload","llm_output","learned_attention"];
function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return`{${Object.entries(v as Record<string,unknown>).filter(([,x])=>x!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(",")}}`;return JSON.stringify(v)}
async function sha(v:unknown){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(v)));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}
function freeze<T>(v:T):Readonly<T>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v as Record<string,unknown>).forEach(freeze);Object.freeze(v)}return v}
function refs(v:readonly string[],code:string){const x=[...new Set(v.map(y=>y.trim()).filter(Boolean))].sort();if(!x.length)throw new Error(code);return x}

export async function bindAttentionV1(input:Readonly<{version:1;subscription:AttentionSubscription;lifecycle:AttentionLifecycleEvaluation;pressure:CanonicalDecisionPressureCompositionV1;previous?:CanonicalPressureAttentionBindingV1}>):Promise<CanonicalPressureAttentionBindingV1>{
 if(input.version!==1)throw new Error("ATTENTION_PRESSURE_VERSION_UNSUPPORTED");for(const k of forbidden)if(k in (input as object))throw new Error("ATTENTION_PRESSURE_UNSUPPORTED_INPUT");await verifyCanonicalDecisionPressureCompositionV1(input.pressure);const s=input.subscription,l=input.lifecycle,p=input.pressure;if(!s.attention_id.trim()||!s.tenant_id.trim()||!s.company_id.trim()||!s.context_id.trim()||s.trigger!=="DECISION_PRESSURE_HIGH")throw new Error("ATTENTION_PRESSURE_SUBSCRIPTION_INVALID");if(s.company_id!==p.company_id||s.context_id!==p.request_id)throw new Error("ATTENTION_PRESSURE_CONTEXT_MISMATCH");if(s.target_ref&&s.target_ref!==p.scope_id)throw new Error("ATTENTION_PRESSURE_SCOPE_MISMATCH");if(l.attention_id!==s.attention_id)throw new Error("ATTENTION_PRESSURE_LIFECYCLE_MISMATCH");if(input.previous&&(input.previous.attention_id!==s.attention_id||input.previous.tenant_id!==s.tenant_id||input.previous.company_id!==s.company_id||input.previous.context_id!==s.context_id||input.previous.scope_id!==p.scope_id))throw new Error("ATTENTION_PRESSURE_CONTINUITY_MISMATCH");const closed=["RESOLVED","OBSOLETE","EXPIRED","DISABLED"].includes(l.lifecycleState),continuity_action:CanonicalPressureAttentionBindingV1["continuity_action"]=closed?"CLOSED":input.previous?"MAINTAINED":"OPENED",uncertainty_preserved=p.completeness_status!=="COMPLETE"||l.lifecycleState==="STALE";const semantic={version:1 as const,attention_id:s.attention_id,attention_origin:"USER_SUBSCRIPTION"as const,tenant_id:s.tenant_id,company_id:s.company_id,context_id:s.context_id,scope_id:p.scope_id,scope_digest:p.scope_digest,attention_subject_ref:s.target_ref??p.scope_id,pressure_ref:p.pressure_id,pressure_digest:p.pressure_digest,pressure_completeness:p.completeness_status,component_statuses:p.components.map(x=>({dimension:x.dimension,status:x.status})),lifecycle_state:l.lifecycleState,continuity_action,uncertainty_preserved,notification_requested:false as const,recommended:false as const,executable:false as const,grants_authority:false as const,grants_execution:false as const,learning_record_created:false as const,evidence_refs:refs(p.evidence_refs,"ATTENTION_PRESSURE_EVIDENCE_REQUIRED"),qualification_refs:refs(p.qualification_refs,"ATTENTION_PRESSURE_QUALIFICATION_REQUIRED"),provenance_refs:refs(p.provenance_refs,"ATTENTION_PRESSURE_PROVENANCE_REQUIRED"),causal_lineage_refs:refs([...p.causal_lineage_refs,p.pressure_id,s.attention_id],"ATTENTION_PRESSURE_LINEAGE_REQUIRED")};const binding_digest=await sha(semantic);return freeze({...semantic,binding_id:`working-attention-pressure-binding:sha256:${binding_digest}`,binding_digest,digest_algorithm:"SHA-256"as const})
}
export async function verifyAttentionBindingV1(value:CanonicalPressureAttentionBindingV1):Promise<void>{const{binding_id:_id,binding_digest:_digest,digest_algorithm:_algorithm,...semantic}=value,digest=await sha(semantic);if(value.binding_digest!==digest||value.binding_id!==`working-attention-pressure-binding:sha256:${digest}`||value.attention_origin!=="USER_SUBSCRIPTION"||value.notification_requested!==false||value.recommended!==false||value.executable!==false||value.grants_authority!==false||value.grants_execution!==false||value.learning_record_created!==false)throw new Error("ATTENTION_PRESSURE_INTEGRITY_INVALID")}
