import { describe,expect,it,vi } from "vitest";
import type { CanonicalEffectiveOperationalAuthorityProofV1 } from "../../organizational-authority";
import { buildKnowledgeExposureEvidenceV1 } from "../knowledge.exposure.evidence.v1";
import { evaluateKnowledgeExposurePolicyV1 } from "../knowledge.exposure.policy.v1";
import { deepCopyAndFreeze } from "../knowledge.projection.guard.v1";
import { disclosure,request,NOW } from "./fixtures";
import { CUSTOMER_QUOTATION_AUTHORITY_DOMAIN_V1,CUSTOMER_QUOTATION_AUTHORITY_SCOPE_V1,classifyKnowledgeExposureAuthorityV1 } from "../knowledge.exposure.authority.contracts.v1";
import { KnowledgeExposureAuthorityRuntimeV1 } from "../knowledge.exposure.authority.runtime.v1";

const AT="2026-08-02T10:00:30.000Z",PROOF_ID="oag-authority-proof:sha256:"+"a".repeat(64),PROOF_DIGEST="b".repeat(64);
const quotation=()=>{const r=deepCopyAndFreeze(disclosure({authority_reference:PROOF_ID}));return {r,d:evaluateKnowledgeExposurePolicyV1(r,NOW)};};
const proof=(patch:Partial<CanonicalEffectiveOperationalAuthorityProofV1>={}):CanonicalEffectiveOperationalAuthorityProofV1=>deepCopyAndFreeze({version:1,authority_source_class:"ORGANIZATIONAL_OPERATIONAL_AUTHORITY",authority_basis:"DIRECT",authority_proof_id:PROOF_ID,proof_digest:PROOF_DIGEST,oag_actor_id:"actor:1",oag_actor_binding_id:"binding:1",principal_id:"principal:oks",membership_id:"membership:oks",tenant_id:"tenant:oks",company_id:"company:oks",root_reference:"root:1",responsibility_references:["responsibility:1"],declaration_version_ids:["declaration:1"],confirmation_chain_id:"confirmation:1",confirmation_chain_references:["confirmation:1"],graph_version:"graph:1",graph_digest:"c".repeat(64),delegation_references:[],effective_scope:CUSTOMER_QUOTATION_AUTHORITY_SCOPE_V1,policy_id:"OAG_AUTHORITY_POLICY_V2",policy_version:"OAG_AUTHORITY_POLICY_V2",policy_numeric_version:2,issued_at:NOW,expires_at:"2026-08-02T11:00:00.000Z",eligibility_state:"ELIGIBLE",invalidation_reasons:[],correlation_id:"correlation:oks",causal_references:[],...patch}) as CanonicalEffectiveOperationalAuthorityProofV1;
const setup=(p=proof())=>{const resolve=vi.fn(async()=>p);return {resolve,runtime:new KnowledgeExposureAuthorityRuntimeV1({resolveCurrentEffectiveOperationalAuthorityProofV1:resolve},undefined,()=>AT)};};
const input=(overrides:Record<string,unknown>={})=>{const {r,d}=quotation();return {version:1 as const,request:r,decision:d,oag_actor_id:"actor:1",authority_proof_id:PROOF_ID,authority_proof_digest:PROOF_DIGEST,...overrides};};
const cognitive=(code:"LANGUAGE_REFINEMENT"|"TRANSLATION"|"EXPLANATION"|"STRUCTURED_EXTRACTION")=>{const r=deepCopyAndFreeze(request({authority_reference:"compatibility:opaque",operation:"COGNITIVE_EXPOSURE",purpose:{version:1,code,operation:"COGNITIVE_EXPOSURE"},target_class:"SHARED_REMOTE_PROVIDER"}));return {version:1 as const,request:r,decision:evaluateKnowledgeExposurePolicyV1(r,NOW)};};

describe("SEC-WU2 knowledge-exposure authority applicability",()=>{
  it.each(["LANGUAGE_REFINEMENT","TRANSLATION","EXPLANATION","STRUCTURED_EXTRACTION"] as const)("classifies %s as OAG not applicable without fabricating proof",async code=>{const {resolve,runtime}=setup();const b=await runtime.bind(cognitive(code));expect(b.organizational_authority).toMatchObject({domain:"ORGANIZATIONAL_AUTHORITY",status:"NOT_APPLICABLE",reason:"COGNITIVE_TRANSFORMATION_ONLY",purpose:code});expect(b.p9).toMatchObject({domain:"P9",status:"NOT_APPLICABLE",reason:"ORDINARY_COGNITIVE_PROVIDER_OPERATION"});expect(b.authority_evidence).toBeUndefined();expect(resolve).not.toHaveBeenCalled();expect(JSON.stringify(b)).not.toMatch(/operation_id|ledger|signature/i);});
  it("keeps undefined distinct from not applicable",()=>{expect(classifyKnowledgeExposureAuthorityV1("FUTURE_PURPOSE")).toBe("AUTHORITY_SOURCE_UNDEFINED");expect(classifyKnowledgeExposureAuthorityV1("FUTURE_PURPOSE")).not.toBe("ORGANIZATIONAL_AUTHORITY_NOT_APPLICABLE");});
  it("fails closed for an unknown future purpose on the governed binding path",async()=>{const {runtime}=setup(),base=cognitive("EXPLANATION");await expect(runtime.bind({...base,decision:{...base.decision,purpose:"FUTURE_PURPOSE"}} as any)).rejects.toMatchObject({code:"SECURITY_EVIDENCE_AUTHORITY_SOURCE_UNDEFINED"});});
  it("denies fabricated real-P9 references on ordinary cognitive transport",async()=>{const {runtime}=setup();await expect(runtime.bind({...cognitive("EXPLANATION"),p9_operation_id:"fake:p9"} as any)).rejects.toMatchObject({code:"SECURITY_EVIDENCE_P9_REFERENCE_INVALID"});});
  it("resolves and binds the exact current quotation proof without copying its body",async()=>{const {resolve,runtime}=setup();const b=await runtime.bind(input());expect(resolve).toHaveBeenCalledWith(expect.objectContaining({requested_domain:CUSTOMER_QUOTATION_AUTHORITY_DOMAIN_V1,requested_scope:CUSTOMER_QUOTATION_AUTHORITY_SCOPE_V1,principal_id:"principal:oks",tenant_id:"tenant:oks",company_id:"company:oks"}));expect(b.organizational_authority.status).toBe("APPLICABLE");expect(b.authority_evidence).toMatchObject({authority_proof_id:PROOF_ID,authority_proof_digest:PROOF_DIGEST,purpose:"CUSTOMER_QUOTATION_DISCLOSURE",current_state_resolution:"CURRENT"});expect(b.authority_evidence?.projection_digest).toBe(input().decision.projection_digest);expect(JSON.stringify(b)).not.toMatch(/root_reference|responsibility_references/);});
  it.each([[{},"SECURITY_EVIDENCE_AUTHORITY_REQUIRED"],[{authority_proof:{version:1}},"SECURITY_EVIDENCE_AUTHORITY_PROOF_INVALID"],[{authority_proof_id:"other"},"SECURITY_EVIDENCE_LEGACY_AUTHORITY_MISMATCH"],[{authority_proof_digest:"d".repeat(64)},"SECURITY_EVIDENCE_AUTHORITY_DIGEST_MISMATCH"]] as const)("denies missing, caller-supplied, substituted, or mismatched proof %#",async(patch,code)=>{const {runtime}=setup();const value=Object.keys(patch).length?input(patch as any):(()=>{const {r,d}=quotation();return {version:1 as const,request:r,decision:d};})();await expect(runtime.bind(value as any)).rejects.toMatchObject({code});});
  it.each([[{oag_actor_id:"actor:2"},"SECURITY_EVIDENCE_AUTHORITY_ACTOR_MISMATCH"],[{principal_id:"other"},"SECURITY_EVIDENCE_AUTHORITY_PRINCIPAL_MISMATCH"],[{tenant_id:"other"},"SECURITY_EVIDENCE_AUTHORITY_TENANT_MISMATCH"],[{company_id:"other"},"SECURITY_EVIDENCE_AUTHORITY_COMPANY_MISMATCH"],[{expires_at:AT},"SECURITY_EVIDENCE_AUTHORITY_EXPIRED"],[{effective_scope:{...CUSTOMER_QUOTATION_AUTHORITY_SCOPE_V1,intents:[]}},"SECURITY_EVIDENCE_AUTHORITY_SCOPE_MISMATCH"]] as const)("denies resolved proof mismatch %#",async(patch,code)=>{const {runtime}=setup(proof(patch as any));await expect(runtime.bind(input())).rejects.toMatchObject({code});});
  it("maps resolver denial and current-state revocation to stale proof",async()=>{const runtime=new KnowledgeExposureAuthorityRuntimeV1({resolveCurrentEffectiveOperationalAuthorityProofV1:vi.fn(async()=>{throw new Error("revoked");})},undefined,()=>AT);await expect(runtime.bind(input())).rejects.toMatchObject({code:"SECURITY_EVIDENCE_AUTHORITY_PROOF_STALE"});});
  it("binds exact request, decision, purpose, and projection identities",async()=>{const {runtime}=setup(),a=await runtime.bind(input());const {r}=quotation(),changed=deepCopyAndFreeze({...r,projection:{...r.projection,projection_digest:"d".repeat(64)}});await expect(runtime.bind({...input(),request:changed} as any)).rejects.toMatchObject({code:"SECURITY_EVIDENCE_AUTHORITY_PURPOSE_MISMATCH"});expect(a.authority_evidence).toMatchObject({request_id:input().decision.request_id,decision_id:input().decision.decision_id,projection_digest:input().decision.projection_digest});});
  it("leaves existing OKS evidence and policy semantics intact",()=>{const {r,d}=quotation();expect(d.outcome).toBe("ADMITTED");expect(buildKnowledgeExposureEvidenceV1(r,d).purpose).toBe("CUSTOMER_QUOTATION_DISCLOSURE");});
  it("keeps quotation disclosure scope narrow and non-commercially expanding",()=>{expect(CUSTOMER_QUOTATION_AUTHORITY_SCOPE_V1).toEqual({domain:"CUSTOMER_COMMERCIAL_COMMUNICATION",intents:["DISCLOSE_CUSTOMER_QUOTATION"],scopes:["DISCLOSE_CUSTOMER_QUOTATION"],limits:[],team_or_subordinate_actor_ids:[],operational_constraints:[]});expect(JSON.stringify(CUSTOMER_QUOTATION_AUTHORITY_SCOPE_V1)).not.toMatch(/PRICE|DISCOUNT|CONTRACT/);});
});
