import { describe, expect, it } from "vitest";
import { identifier } from "../../../operational-identity/contracts/identifiers.v1";
import { evaluateKnowledgeExposurePolicyV1, validateKnowledgeExposureDecisionV1 } from "../knowledge.exposure.policy.v1";
import { disclosure, knowledge, manifest, NOW, request } from "./fixtures";

const decide = (overrides = {}) => evaluateKnowledgeExposurePolicyV1(request(overrides), NOW);
const denies = (code: string, overrides = {}) => expect(decide(overrides).reason_codes).toContain(code);

describe("OKS-WU1 deterministic exposure policy", () => {
  it("admits valid narrow cognitive exposure", () => expect(decide().outcome).toBe("ADMITTED"));
  it("admits valid narrow outbound disclosure", () => expect(evaluateKnowledgeExposurePolicyV1(disclosure(), NOW).outcome).toBe("ADMITTED"));
  it("denies missing principal", () => denies("KNOWLEDGE_EXPOSURE_REQUEST_INVALID", { participation: { ...request().participation, principal_id: "" as never } }));
  it("denies inactive session", () => denies("KNOWLEDGE_EXPOSURE_REQUEST_INVALID", { participation: { ...request().participation, session_active: false as true } }));
  it("denies inactive membership", () => denies("KNOWLEDGE_EXPOSURE_REQUEST_INVALID", { participation: { ...request().participation, membership_active: false as true } }));
  it("denies missing tenant", () => denies("KNOWLEDGE_EXPOSURE_REQUEST_INVALID", { participation: { ...request().participation, tenant_id: "" as never } }));
  it("denies missing company", () => denies("KNOWLEDGE_EXPOSURE_REQUEST_INVALID", { participation: { ...request().participation, company_id: "" as never } }));
  it("denies cross-tenant knowledge", () => { const k = knowledge({ tenant_id: identifier("TenantId", "tenant:other") }); denies("KNOWLEDGE_TENANT_CONTRADICTION", { knowledge: [k], projection: manifest([k]) }); });
  it("denies cross-company knowledge", () => { const k = knowledge({ company_id: identifier("CompanyId", "company:other") }); denies("KNOWLEDGE_OWNER_CONTRADICTION", { knowledge: [k], projection: manifest([k]) }); });
  it("denies missing authority", () => denies("KNOWLEDGE_AUTHORITY_MISSING", { authority_reference: "" }));
  it("denies invalid purpose", () => denies("KNOWLEDGE_PURPOSE_INVALID", { purpose: { version: 1, code: "GENERIC_AI_USE", operation: "COGNITIVE_EXPOSURE" } as never }));
  it("denies broad purpose", () => denies("KNOWLEDGE_PURPOSE_INVALID", { purpose: { version: 1, code: "GENERIC_AI_USE", operation: "COGNITIVE_EXPOSURE" } as never }));
  it("denies purpose substitution", () => denies("KNOWLEDGE_OPERATION_MISMATCH", { purpose: { version: 1, code: "CUSTOMER_QUOTATION_DISCLOSURE", operation: "OUTBOUND_DISCLOSURE" } }));
  it("denies cognitive and disclosure operation confusion", () => denies("KNOWLEDGE_OPERATION_MISMATCH", { operation: "OUTBOUND_DISCLOSURE" }));
  it("denies missing classification", () => { const k = knowledge({ classification: undefined as never }); denies("KNOWLEDGE_CLASSIFICATION_MISSING", { knowledge: [k], projection: manifest([k]) }); });
  it("denies LLM-forbidden domain", () => { const k = knowledge({ encryption_domain: "DECISION_MEMORY", classification: "CRITICAL", llm_access_allowed: false, export_allowed: false }); denies("KNOWLEDGE_DOMAIN_LLM_PROHIBITED", { knowledge: [k], projection: manifest([k]) }); });
  it("denies export-forbidden domain", () => { const k = knowledge({ encryption_domain: "DECISION_MEMORY", classification: "CRITICAL", llm_access_allowed: false, export_allowed: false }); const q = disclosure({ knowledge: [k], projection: manifest([k]) }); expect(evaluateKnowledgeExposurePolicyV1(q, NOW).reason_codes).toContain("KNOWLEDGE_DOMAIN_EXPORT_PROHIBITED"); });
  it("denies non-exportable knowledge", () => { const k = knowledge({ encryption_domain: "OAG", classification: "CONSTITUTIONAL", sovereignty: "NON_EXPORTABLE", llm_access_allowed: false, export_allowed: false }); const q = disclosure({ knowledge: [k], projection: manifest([k]) }); expect(evaluateKnowledgeExposurePolicyV1(q, NOW).reason_codes).toContain("KNOWLEDGE_NON_EXPORTABLE"); });
  it("denies region conflict", () => denies("KNOWLEDGE_REGION_CONFLICT", { target_region: "US" }));
  it("denies retention conflict", () => denies("KNOWLEDGE_RETENTION_CONFLICT", { requested_retention: "TENANT_CONTROLLED_RETENTION" }));
  it("denies unsupported provider class", () => denies("KNOWLEDGE_PROVIDER_CLASS_PROHIBITED", { target_class: "AUTHORIZED_BUSINESS_RECIPIENT" }));
  it("denies unsupported recipient class", () => { const q = disclosure({ target_class: "SHARED_REMOTE_PROVIDER" }); expect(evaluateKnowledgeExposurePolicyV1(q, NOW).reason_codes).toContain("KNOWLEDGE_RECIPIENT_CLASS_PROHIBITED"); });
  it("requires authority for a local model", () => denies("KNOWLEDGE_AUTHORITY_MISSING", { target_class: "LOCAL_SELF_HOSTED_MODEL", authority_reference: "" }));
  it("denies substituted target", () => { const q = request(); const d = decide(); expect(validateKnowledgeExposureDecisionV1(d, { ...q, target_identity: "provider:other" }, NOW)).toContain("KNOWLEDGE_DECISION_SUBSTITUTED"); });
  it("denies expired decision", () => { const d = decide(); expect(validateKnowledgeExposureDecisionV1(d, request(), "2026-08-02T10:02:00.000Z")).toContain("KNOWLEDGE_DECISION_EXPIRED"); });
  it("denies unknown contributing restriction", () => { const k = knowledge({ derived_from: ["knowledge:missing"] }); denies("KNOWLEDGE_DERIVATION_RESTRICTION_UNKNOWN", { knowledge: [k], projection: manifest([k]) }); });
  it("denies derived classification downgrade", () => { const parent = knowledge({ knowledge_reference: "knowledge:parent", digest: "b".repeat(64), encryption_domain: "DECISION_MEMORY", classification: "CRITICAL", llm_access_allowed: false, export_allowed: false }); const child = knowledge({ derived_from: [parent.knowledge_reference], provenance_references: ["derivation:1"] }); denies("KNOWLEDGE_DERIVATION_DOWNGRADE_PROHIBITED", { knowledge: [child, parent], projection: manifest([child]) }); });
  it("derives exact most-restrictive ceiling", () => { const k = knowledge(); const d = decide({ knowledge: [k], projection: manifest([k]) }); expect(d).toMatchObject({ effective_classification: "INTERNAL", effective_sovereignty: "TENANT_LOCAL", effective_retention: "TRANSIENT_PROCESSING", effective_regions: ["EU"] }); });
  it("produces deterministic request identity", () => expect(decide().request_id).toBe(decide().request_id));
  it("produces deterministic decision identity", () => expect(decide().decision_id).toBe(decide().decision_id));
  it("produces repeated-run deterministic results", () => expect(decide()).toEqual(decide()));
  it("quotation calculation authority does not imply LLM exposure", () => denies("KNOWLEDGE_PURPOSE_INVALID", { purpose: { version: 1, code: "QUOTATION_CALCULATION", operation: "COGNITIVE_EXPOSURE" } as never }));
  it("LLM exposure does not imply customer disclosure", () => { const q = disclosure({ authority_reference: decide().decision_id }); expect(evaluateKnowledgeExposurePolicyV1(q, NOW).request_id).not.toBe(decide().request_id); });
  it("customer disclosure excludes costs and margins", () => { const k = knowledge({ authorized_fields: ["price", "supplier_cost", "margin"] }); const p = manifest([k], [{ field: "supplier_cost", knowledge_reference: k.knowledge_reference, category: k.category }], { excluded_categories: [k.category] }); const q = disclosure({ knowledge: [k], projection: p }); expect(evaluateKnowledgeExposurePolicyV1(q, NOW).outcome).toBe("DENIED"); });
  it("admits narrow customer-facing quotation terms", () => expect(evaluateKnowledgeExposurePolicyV1(disclosure(), NOW).outcome).toBe("ADMITTED"));
  it("keeps cognitive and disclosure decisions independently auditable", () => expect(decide().decision_id).not.toBe(evaluateKnowledgeExposurePolicyV1(disclosure(), NOW).decision_id));
  it("contains no transport capability", () => expect(evaluateKnowledgeExposurePolicyV1.toString()).not.toContain("fetch("));
  it("contains no cognition invocation", () => expect(evaluateKnowledgeExposurePolicyV1.toString()).not.toContain("cognition"));
  it("contains no memory write", () => expect(evaluateKnowledgeExposurePolicyV1.toString()).not.toContain("appendMemory"));
  it("contains no ORS or composition contract", () => { const text = JSON.stringify(decide()); expect(text).not.toContain("ORS"); expect(text).not.toContain("composition"); });
});
