import { createHash } from "node:crypto";import { describe,expect,it,vi } from "vitest";
import { deepCopyAndFreeze,knowledgeProjectionDigestV1 } from "../../../knowledge-exposure/knowledge.projection.guard.v1";import { knowledge,manifest } from "../../../knowledge-exposure/__tests__/fixtures";
import type { OutboundDisclosureDispatchEligibilityV1 } from "../../outbound.disclosure.contracts.v1";import { GovernedTwilioDeliveryV1 } from "../governed.twilio.delivery.v1";import { sealGovernedTwilioMessageV1,verifySealedGovernedTwilioMessageV1 } from "../governed.twilio.seal.v1";import { TwilioHttpTransportV1 } from "../governed.twilio.transport.v1";import { GovernedTwilioError,type GovernedTwilioChannelV1,type GovernedTwilioEvidenceRepositoryV1,type GovernedTwilioEvidenceV1,type GovernedTwilioLineageV1,type GovernedTwilioTransportV1 } from "../governed.twilio.contracts.v1";
const NOW="2026-08-02T10:00:40.000Z",hash=(s:string)=>createHash("sha256").update(s,"utf8").digest("hex"),ref=knowledge({authorized_fields:["message"]}),manifestBase=manifest([ref],[{field:"message",knowledge_reference:ref.knowledge_reference,category:ref.category}]),manifestSubject={...manifestBase,schema_id:"tenant.message"},m=deepCopyAndFreeze({...manifestSubject,projection_digest:knowledgeProjectionDigestV1(manifestSubject)});
function eligibility(channel:GovernedTwilioChannelV1="SMS",overrides:Partial<OutboundDisclosureDispatchEligibilityV1>={}):OutboundDisclosureDispatchEligibilityV1{return deepCopyAndFreeze({version:1,disclosure_id:`disclosure:${channel}`,decision_id:`decision:${channel}`,binding_id:`binding:${channel}`,knowledge_consumption_id:`knowledge-consumption:${channel}`,authority_reference:"authority:1",governance_references:[],tenant_id:"tenant:1",company_id:"company:1",purpose:"CUSTOMER_QUOTATION_DISCLOSURE",communication_family:"TENANT_OPERATIONAL_DISCLOSURE",manifest_id:`${m.schema_id}@${m.schema_version}`,projection_digest:m.projection_digest,recipient:{version:1,recipient_id:"recipient:1",recipient_class:"AUTHORIZED_BUSINESS_RECIPIENT",entitlement_reference:"entitlement:1",tenant_id:"tenant:1",company_id:"company:1"},channel,representation:"STRUCTURED_JSON",classification:"INTERNAL",policy_version:"OUTBOUND_DISCLOSURE_POLICY_V1",admitted_at:"2026-08-02T10:00:20.000Z",expires_at:"2026-08-02T10:01:20.000Z",correlation_id:"correlation:1",causal_references:["audit:1"],canonical_digest:"a".repeat(64),disclosure_consumption_id:`disclosure-consumption:${channel}`,consumed_at:"2026-08-02T10:00:30.000Z",transport_executed:false,...overrides}) as OutboundDisclosureDispatchEligibilityV1;}
function lineage(channel:GovernedTwilioChannelV1="SMS"):GovernedTwilioLineageV1{return deepCopyAndFreeze({decision_id:`decision:${channel}`,binding_id:`binding:${channel}`,knowledge_consumption_id:`knowledge-consumption:${channel}`,principal_id:"principal:1",region:"EU",retention:"NO_RETENTION",knowledge_digests:["b".repeat(64)]}) as GovernedTwilioLineageV1;}
const destination=(channel:GovernedTwilioChannelV1)=>deepCopyAndFreeze({recipient_id:"recipient:1",entitlement_reference:"entitlement:1",channel,address:channel==="SMS"?"+391234567890":"whatsapp:+391234567890"});
const provider=(channel:GovernedTwilioChannelV1)=>deepCopyAndFreeze({provider_identity:"twilio" as const,product:channel==="SMS"?"TWILIO_SMS" as const:"TWILIO_WHATSAPP" as const,sender_identity_reference:`sender:${channel}`});
function sealed(channel:GovernedTwilioChannelV1="SMS",message="Order 42 confirmed"){return sealGovernedTwilioMessageV1({eligibility:eligibility(channel),lineage:lineage(channel),destination:destination(channel),provider:provider(channel),manifest:m,projection:{message}});}
class Evidence implements GovernedTwilioEvidenceRepositoryV1{used=new Set<string>();events:GovernedTwilioEvidenceV1[]=[];async reserve(id:string){if(this.used.has(id))return false;this.used.add(id);return true;}async append(e:GovernedTwilioEvidenceV1){this.events.push(e);}}
function services(channel:GovernedTwilioChannelV1="SMS",transport?:GovernedTwilioTransportV1){const evidence=new Evidence(),send=vi.fn(async()=>({provider_message_reference:"provider-message-secret"})),t=transport??{binding:provider(channel),send},delivery=new GovernedTwilioDeliveryV1({lineage:{resolve:async()=>lineage(channel)},destination:{resolve:async()=>destination(channel)},transport:t,evidence,now:()=>NOW});return{delivery,evidence,send,transport:t};}
describe("OKS-WU4C governed Twilio sealing and delivery",()=>{
 it.each(["SMS","WHATSAPP"] as const)("requires consumed WU4A eligibility for %s",async channel=>{const x=services(channel);await expect(x.delivery.deliver({eligibility:undefined as any,manifest:m,projection:{message:"x"}})).rejects.toMatchObject({code:"GOVERNED_TWILIO_ELIGIBILITY_REQUIRED"});});
 it("rejects cognitive, denied, unconsumed, email-bound, and expired shapes",async()=>{for(const e of [{...eligibility(),disclosure_consumption_id:""},{...eligibility(),transport_executed:true},{...eligibility(),channel:"EMAIL"},{...eligibility(),expires_at:NOW}])await expect(services().delivery.deliver({eligibility:deepCopyAndFreeze(e) as any,manifest:m,projection:{message:"x"}})).rejects.toMatchObject({code:expect.stringMatching(/^GOVERNED_TWILIO_/)});});
 it.each(["SMS","WHATSAPP"] as const)("seals %s deterministically and deeply immutably",channel=>{const a=sealed(channel),b=sealed(channel);expect(a.message_digest).toBe(b.message_digest);expect(a.sealed_message_id).toBe(b.sealed_message_id);expect(Object.isFrozen(a)).toBe(true);expect(Object.isFrozen(a.eligibility)).toBe(true);});
 it("defensively copies the message and detects one-character mutation",()=>{const projection={message:"Order 42 confirmed"},s=sealGovernedTwilioMessageV1({eligibility:eligibility(),lineage:lineage(),destination:destination("SMS"),provider:provider("SMS"),manifest:m,projection});projection.message="changed";expect(s.canonical_message).toBe("Order 42 confirmed");const changed=deepCopyAndFreeze({...s,canonical_message:"Order 42 confirmeD"});expect(()=>verifySealedGovernedTwilioMessageV1(changed as any,NOW)).toThrow(/GOVERNED_TWILIO_MESSAGE_MUTATED/);});
 it("rejects projection, digest, unsupported representation, and arbitrary message substitution",()=>{expect(()=>sealGovernedTwilioMessageV1({eligibility:eligibility(),lineage:lineage(),destination:destination("SMS"),provider:provider("SMS"),manifest:m,projection:{message:"x",other:"y"}})).toThrow(/PROJECTION_MISMATCH/);expect(()=>sealGovernedTwilioMessageV1({eligibility:eligibility("SMS",{representation:"PLAIN_TEXT"}),lineage:lineage(),destination:destination("SMS"),provider:provider("SMS"),manifest:m,projection:{message:"x"}})).toThrow(/PROJECTION_MISMATCH/);const changed=deepCopyAndFreeze({...sealed(),message_digest:"c".repeat(64)});expect(()=>verifySealedGovernedTwilioMessageV1(changed as any,NOW)).toThrow(/MESSAGE_MUTATED/);});
 it("rejects oversized SMS and WhatsApp without truncation or segmentation",()=>{expect(()=>sealed("SMS","x".repeat(71))).toThrow(/MESSAGE_TOO_LARGE/);expect(()=>sealed("WHATSAPP","x".repeat(4097))).toThrow(/MESSAGE_TOO_LARGE/);});
 it("enforces SMS and WhatsApp canonical destination forms",()=>{expect(()=>sealGovernedTwilioMessageV1({eligibility:eligibility("SMS"),lineage:lineage("SMS"),destination:{...destination("SMS"),address:"whatsapp:+391234567890"},provider:provider("SMS"),manifest:m,projection:{message:"x"}})).toThrow(/RECIPIENT_INVALID/);expect(()=>sealGovernedTwilioMessageV1({eligibility:eligibility("WHATSAPP"),lineage:lineage("WHATSAPP"),destination:{...destination("WHATSAPP"),address:"+391234567890"},provider:provider("WHATSAPP"),manifest:m,projection:{message:"x"}})).toThrow(/RECIPIENT_INVALID/);});
 it("denies recipient, sender, channel, and product substitution",()=>{expect(()=>sealGovernedTwilioMessageV1({eligibility:eligibility(),lineage:lineage(),destination:{...destination("SMS"),recipient_id:"other"},provider:provider("SMS"),manifest:m,projection:{message:"x"}})).toThrow(/RECIPIENT_SUBSTITUTED/);expect(()=>sealGovernedTwilioMessageV1({eligibility:eligibility(),lineage:lineage(),destination:destination("SMS"),provider:{...provider("SMS"),sender_identity_reference:""},manifest:m,projection:{message:"x"}})).toThrow(/SENDER_INVALID/);expect(()=>sealGovernedTwilioMessageV1({eligibility:eligibility(),lineage:lineage(),destination:destination("SMS"),provider:provider("WHATSAPP"),manifest:m,projection:{message:"x"}})).toThrow(/PRODUCT_MISMATCH/);});
 it.each(["SMS","WHATSAPP"] as const)("dispatches one exact %s product request",async channel=>{const x=services(channel),out=await x.delivery.deliver({eligibility:eligibility(channel),manifest:m,projection:{message:"Order 42 confirmed"}});expect(x.send).toHaveBeenCalledWith({channel,product:channel==="SMS"?"TWILIO_SMS":"TWILIO_WHATSAPP",destination:destination(channel).address,message:"Order 42 confirmed",sender_identity_reference:`sender:${channel}`});expect(out.status).toBe("SUCCEEDED");expect(out.content_returned).toBe(false);});
 it("rejects arbitrary recipient resolution before transport",async()=>{const x=services(),delivery=new GovernedTwilioDeliveryV1({lineage:{resolve:async()=>lineage()},destination:{resolve:async()=>({...destination("SMS"),recipient_id:"other"})},transport:x.transport,evidence:x.evidence,now:()=>NOW});await expect(delivery.deliver({eligibility:eligibility(),manifest:m,projection:{message:"x"}})).rejects.toMatchObject({code:"GOVERNED_TWILIO_RECIPIENT_SUBSTITUTED"});expect(x.send).not.toHaveBeenCalled();});
 it("allows one concurrent attempt and denies sequential replay",async()=>{const x=services(),input={eligibility:eligibility(),manifest:m,projection:{message:"x"}},results=await Promise.allSettled([x.delivery.deliver(input),x.delivery.deliver(input)]);expect(results.filter(r=>r.status==="fulfilled")).toHaveLength(1);expect(x.send).toHaveBeenCalledTimes(1);await expect(x.delivery.deliver(input)).rejects.toMatchObject({code:"GOVERNED_TWILIO_ALREADY_DISPATCHED"});});
 it.each([["GOVERNED_TWILIO_TIMEOUT","INDETERMINATE"],["GOVERNED_TWILIO_PROVIDER_FAILURE","FAILED"]] as const)("records sanitized %s and never permits reuse",async(code,status)=>{const evidence=new Evidence(),transport={binding:provider("SMS"),send:async()=>{throw new GovernedTwilioError(code);}} as any,delivery=new GovernedTwilioDeliveryV1({lineage:{resolve:async()=>lineage()},destination:{resolve:async()=>destination("SMS")},transport,evidence,now:()=>NOW});const input={eligibility:eligibility(),manifest:m,projection:{message:"x"}};await expect(delivery.deliver(input)).rejects.toMatchObject({code});expect(evidence.events[0]).toMatchObject({status,failure_code:code});await expect(delivery.deliver(input)).rejects.toMatchObject({code:"GOVERNED_TWILIO_ALREADY_DISPATCHED"});});
 it("persists content-free exact evidence",async()=>{const x=services(),out=await x.delivery.deliver({eligibility:eligibility(),manifest:m,projection:{message:"private text"}}),e=out.evidence;expect(e).toMatchObject({message_digest:hash("private text"),destination_digest:hash("+391234567890"),channel:"SMS",product:"TWILIO_SMS"});expect(JSON.stringify(e)).not.toMatch(/private text|391234567890|provider-message-secret|auth.token/i);});
 it("never performs cross-channel fallback",async()=>{const sms=services("SMS"),delivery=new GovernedTwilioDeliveryV1({lineage:{resolve:async()=>lineage("WHATSAPP")},destination:{resolve:async()=>destination("WHATSAPP")},transport:sms.transport,evidence:sms.evidence,now:()=>NOW});await expect(delivery.deliver({eligibility:eligibility("WHATSAPP"),manifest:m,projection:{message:"x"}})).rejects.toMatchObject({code:"GOVERNED_TWILIO_PRODUCT_MISMATCH"});expect(sms.send).not.toHaveBeenCalled();});
});

const config={account_credential_reference:"credential:twilio",sms_sender:{identity_reference:"sender:sms",address:"+15551234567"},whatsapp_sender:{identity_reference:"sender:wa",address:"whatsapp:+15551234567"},provider_endpoint:"https://api.twilio.com/2010-04-01",timeout_ms:100,response_size_limit:1024} as const,credentials={resolve:async()=>({account_sid:`AC${"a".repeat(32)}`,auth_token:"top-secret-token"})};
describe("WU4C low-level Twilio transport",()=>{
 it.each(["SMS","WHATSAPP"] as const)("formats one %s request with its bound sender",async channel=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({sid:"SM123"}),{status:201})),transport=new TwilioHttpTransportV1(config,credentials,channel,fetcher as any),destinationValue=destination(channel).address;await transport.send({channel,product:channel==="SMS"?"TWILIO_SMS":"TWILIO_WHATSAPP",destination:destinationValue,message:"x",sender_identity_reference:channel==="SMS"?"sender:sms":"sender:wa"});const[,init]=(fetcher.mock.calls as unknown as Array<[unknown,RequestInit]>)[0]!,body=init.body as URLSearchParams;expect(body.get("From")).toBe(channel==="SMS"?"+15551234567":"whatsapp:+15551234567");expect(body.get("To")).toBe(destinationValue);expect(body.get("Body")).toBe("x");});
 it("resolves credentials outside governed input and rejects invalid configuration",async()=>{const resolve=vi.fn(credentials.resolve),transport=new TwilioHttpTransportV1(config,{resolve},"SMS",vi.fn(async()=>new Response('{"sid":"SM1"}',{status:201})) as any);await transport.send({channel:"SMS",product:"TWILIO_SMS",destination:"+391234567890",message:"x",sender_identity_reference:"sender:sms"});expect(resolve).toHaveBeenCalledWith("credential:twilio");expect(()=>new TwilioHttpTransportV1({...config,sms_sender:{...config.sms_sender,address:"whatsapp:+15551234567"}},credentials,"SMS")).toThrow(/CONFIGURATION_INVALID/);});
 it("sanitizes provider failures, credentials, destinations, and response bodies",async()=>{const transport=new TwilioHttpTransportV1(config,credentials,"SMS",vi.fn(async()=>new Response('secret token +391234567890',{status:400})) as any);await expect(transport.send({channel:"SMS",product:"TWILIO_SMS",destination:"+391234567890",message:"x",sender_identity_reference:"sender:sms"})).rejects.toMatchObject({code:"GOVERNED_TWILIO_PROVIDER_FAILURE",message:"GOVERNED_TWILIO_PROVIDER_FAILURE"});});
 it("fails closed on timeout, redirects, oversized and invalid responses",async()=>{const hanging=vi.fn(async(_u:any,i:any)=>new Promise<Response>((_r,reject)=>i.signal.addEventListener("abort",()=>reject(new Error("aborted"))))),timeout=new TwilioHttpTransportV1(config,credentials,"SMS",hanging as any);await expect(timeout.send({channel:"SMS",product:"TWILIO_SMS",destination:"+391234567890",message:"x",sender_identity_reference:"sender:sms"})).rejects.toMatchObject({code:"GOVERNED_TWILIO_TIMEOUT"});for(const response of [new Response("x".repeat(1025),{status:201}),new Response("not-json",{status:201})]){const t=new TwilioHttpTransportV1(config,credentials,"SMS",vi.fn(async()=>response) as any);await expect(t.send({channel:"SMS",product:"TWILIO_SMS",destination:"+391234567890",message:"x",sender_identity_reference:"sender:sms"})).rejects.toMatchObject({code:"GOVERNED_TWILIO_RESPONSE_INVALID"});}});
});
