import{describe,expect,it}from"vitest";
import{bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1}from"../../cockpit/operational.signal.evaluation.scope.v1";
import{composeCanonicalOperationalRealityV1,type CanonicalOperationalRealityEvidenceV1}from"../../reality/canonical.operational.reality.composition.v1";
import{createCanonicalExplanationBasisV1,manifestCanonicalExplanationV1,verifyCanonicalExplanationBasisV1,type ExplanationClaimV1}from"../canonicalExplanation";
const at="2026-08-17T10:00:00.000Z",hex=(x:string)=>x.repeat(64).slice(0,64);
async function reality(conflict=false,company="company:1"){const s=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"REQUEST_DATASET",request_id:"request:1",company_id:company,domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1"}),b=await bindOperationalSignalsToScopeV1({scope:s,request_id:"request:1",company_id:company,evidence_as_of:at,evaluated_at:"2026-08-17T10:01:00.000Z"}),e=(n:number,claim:string):CanonicalOperationalRealityEvidenceV1=>({version:1,tenant_id:"tenant:1",company_id:company,request_id:"request:1",scope_id:b.scope.scope_id,scope_digest:b.scope.scope_digest,evidence_as_of:at,evidence_ref:`evidence:${n}`,evidence_digest:hex(String(n)),source_identity_ref:`source:${n}`,source_namespace:`namespace:${n}`,semantic_key:"inventory:item",claim_digest:hex(claim),evidence_role:"CURRENT_FACT",canonical_subject_refs:["subject:item"],canonical_location_refs:["location:1"],qualification_refs:[`qualification:${n}`],provenance_refs:[`provenance:${n}`],causal_lineage_refs:[`lineage:${n}`]});return composeCanonicalOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:b,evidence:conflict?[e(1,"a"),e(2,"b")]:[e(1,"a")],coverage:[]})}
function claim(kind:ExplanationClaimV1["kind"]="IMPACT",status:ExplanationClaimV1["status"]="ESTABLISHED"):ExplanationClaimV1{return{kind,tenant_id:"tenant:1",company_id:"company:1",request_id:"request:1",scope_id:"operational-signal-scope:request:1",scope_digest:"",artifact_ref:`artifact:${kind}`,artifact_digest:hex("a"),status,evidence_refs:[`evidence:${kind}`],qualification_refs:[`qualification:${kind}`],provenance_refs:[`provenance:${kind}`],causal_lineage_refs:[`lineage:${kind}`]}}
const bound=(r:Awaited<ReturnType<typeof reality>>,c:ExplanationClaimV1)=>({...c,scope_id:r.scope_id,scope_digest:r.scope_digest});
async function basis(extra:Record<string,unknown>={}){const r=await reality(),bind=(c:ExplanationClaimV1)=>({...c,scope_id:r.scope_id,scope_digest:r.scope_digest});return createCanonicalExplanationBasisV1({version:1,reality:r,claims:[claim("IMPACT"),claim("DECISION_MARGIN"),claim("URGENCY"),claim("COST_OF_WAITING")].map(bind),...extra}as any)}
describe("EXPLAINABILITY-CANONICAL-COMPLETION-WU1",()=>{
 it("creates, verifies and deterministically replays a canonical basis",async()=>{const a=await basis(),b=await basis();expect(a).toEqual(b);await expect(verifyCanonicalExplanationBasisV1(a)).resolves.toBeUndefined()});
 it("binds exact tenant, company, request and scope",async()=>expect(await basis()).toMatchObject({tenant_id:"tenant:1",company_id:"company:1",request_id:"request:1"}));
 it.each(["IMPACT","DECISION_MARGIN","URGENCY","COST_OF_WAITING"]as const)("binds %s without recalculation",async kind=>expect((await basis()).claims.find(x=>x.kind===kind)?.artifact_ref).toBe(`artifact:${kind}`));
 it("retains evidence, qualification, provenance and lineage",async()=>{const x=await basis();expect(x.evidence_refs).toContain("evidence:IMPACT");expect(x.qualification_refs).toContain("qualification:IMPACT");expect(x.provenance_refs).toContain("provenance:IMPACT");expect(x.causal_lineage_refs).toContain("lineage:IMPACT")});
 it.each(["UNRESOLVED","INSUFFICIENT_EVIDENCE"]as const)("preserves %s",async status=>{const r=await reality();expect((await createCanonicalExplanationBasisV1({version:1,reality:r,claims:[bound(r,claim("URGENCY",status))]})).claims[0]?.status).toBe(status)});
 it("preserves multi-source conflict without choosing a winner",async()=>{const x=await createCanonicalExplanationBasisV1({version:1,reality:await reality(true)});expect(x.reality.status).toBe("UNRESOLVED_CONFLICT");expect(x.reality.semantic_groups[0]).not.toHaveProperty("selected_evidence_ref")});
 it("separates current and counterfactual contexts",async()=>{expect((await basis()).context.mode).toBe("CURRENT");const x=await basis({context:{mode:"COUNTERFACTUAL",scenario_ref:"scenario:1",assumption_refs:["assumption:1"]}});expect(x.context).toMatchObject({mode:"COUNTERFACTUAL",scenario_ref:"scenario:1"})});
 it("rejects unlabeled counterfactual and contaminated current context",async()=>{await expect(basis({context:{mode:"COUNTERFACTUAL"}})).rejects.toThrow("EXPLANATION_SCENARIO_REQUIRED");await expect(basis({context:{mode:"CURRENT",scenario_ref:"scenario:1"}})).rejects.toThrow("EXPLANATION_CURRENT_SCENARIO_FORBIDDEN")});
 it("uses existing identity roles for audience manifestation",async()=>{const x=await basis(),planner=manifestCanonicalExplanationV1(x,{audience:"PLANNER",tier:"JUNIOR"}),executive=manifestCanonicalExplanationV1(x,{audience:"EXECUTIVE",tier:"JUNIOR"});expect(planner.detail).toBe("STANDARD");expect(executive.detail).toBe("SUMMARY");expect(planner.basis_digest).toBe(executive.basis_digest)});
 it.each(["VISION","GRADUATE","JUNIOR","SENIOR","PRINCIPAL","CHARTER"]as const)("keeps truth identical for %s",async tier=>{const x=await basis(),m=manifestCanonicalExplanationV1(x,{audience:"PLANNER",tier});expect(m.basis_id).toBe(x.basis_id);expect(m.truth_unchanged).toBe(true)});
 it("keeps manifestation non-recommending and non-authoritative",async()=>expect(manifestCanonicalExplanationV1(await basis(),{audience:"MANAGER",tier:"PRINCIPAL"})).toMatchObject({recommended:false,grants_authority:false,grants_execution:false}));
 it.each(["commercial_plan","credit_balance","economic_capacity","provider","model","llm_output","recommendation","approval","delegation","execution_payload"])("rejects %s contamination",async key=>await expect(basis({[key]:"forbidden"})).rejects.toThrow("EXPLANATION_UNSAFE_INPUT"));
 it("rejects cross-client cognition claims",async()=>{const r=await reality();await expect(createCanonicalExplanationBasisV1({version:1,reality:r,claims:[bound(r,{...claim(),tenant_id:"tenant:2"})]})).rejects.toThrow("EXPLANATION_CONTEXT_MISMATCH")});
 it("rejects duplicate cognition claims",async()=>{const r=await reality(),c=bound(r,claim());await expect(createCanonicalExplanationBasisV1({version:1,reality:r,claims:[c,c]})).rejects.toThrow("EXPLANATION_DUPLICATE_CLAIM")});
 it("rejects forged claims and forged basis",async()=>{const r=await reality();await expect(createCanonicalExplanationBasisV1({version:1,reality:r,claims:[bound(r,{...claim(),artifact_digest:"forged"})]})).rejects.toThrow("EXPLANATION_CLAIM_DIGEST_INVALID");const x=await basis();await expect(verifyCanonicalExplanationBasisV1({...x,basis_digest:hex("0")})).rejects.toThrow("EXPLANATION_INTEGRITY_INVALID")});
 it("is recursively immutable and not LLM authoritative",async()=>{const x=await basis();expect(Object.isFrozen(x)&&Object.isFrozen(x.claims)&&Object.isFrozen(x.claims[0])).toBe(true);expect(x).toMatchObject({llm_authoritative:false,recommended:false,executable:false,grants_authority:false,grants_execution:false})});
});
