import { describe, expect, it } from 'vitest';
import { createGovernanceIndicatorAggregateV1, createGovernanceIndicatorV1 } from '..';

const at='2026-08-11T00:00:00.000Z', tenant='tenant:1', company='company:1';
const source=(family:'OKS'|'SEC_WU1',id:string,result:string,digest='a'.repeat(64))=>({version:1 as const,source_family:family,source_artifact_id:id,source_artifact_digest:digest,source_result:result,tenant_id:tenant,company_id:company,observed_at:at});
const indicator=(type:string,sources:ReturnType<typeof source>[],overrides:Record<string,unknown>={})=>createGovernanceIndicatorV1({version:1,indicator_type:type,subject_type:'GOVERNED_OPERATION',subject_id:'operation:1',tenant_id:tenant,company_id:company,source_evidence:sources,expected_source_digests:Object.fromEntries(sources.map(x=>[x.source_artifact_id,x.source_artifact_digest])),evaluated_at:at,historical_mode:'VALID_AT_OPERATION_TIME',causal_lineage:sources.map(x=>x.source_artifact_id),...overrides});
const secIndicator=(result:'VERIFIED'|'DENIED'|'INCOMPLETE'|'NOT_APPLICABLE'='VERIFIED',type:'SECURITY_EVIDENCE_COMPOSITION'|'AUTHORITY_INTEGRITY'='SECURITY_EVIDENCE_COMPOSITION')=>createGovernanceIndicatorV1({version:1,indicator_type:type,subject_type:'GOVERNED_OPERATION',subject_id:'operation:1',tenant_id:tenant,company_id:company,source_evidence:[{...source(type==='AUTHORITY_INTEGRITY'?'OKS':'SEC_WU1','source:'+type,result),source_family:type==='AUTHORITY_INTEGRITY'?'OAG' as const:'SEC_WU3' as const}],expected_source_digests:{['source:'+type]:'a'.repeat(64)},evaluated_at:at,historical_mode:'VALID_AT_OPERATION_TIME',causal_lineage:[]});
const aggregate=(contributors:any[],required=contributors.map(x=>x.indicator_type),overrides:Record<string,unknown>={})=>createGovernanceIndicatorAggregateV1({version:1,aggregate_type:'GOVERNANCE_EVIDENCE_COMPLETENESS',subject_type:'GOVERNED_OPERATION',subject_id:'operation:1',tenant_id:tenant,company_id:company,required_indicator_types:required,contributors,evaluated_at:at,historical_mode:'VALID_AT_OPERATION_TIME',causal_lineage:contributors.map(x=>x.indicator_id),...overrides});

describe('GI-WU2 catalog completion',()=>{
	it.each([['ADMITTED','HEALTHY'],['DENIED','DENIED'],['INCOMPLETE','INCOMPLETE'],['NOT_APPLICABLE','NOT_APPLICABLE']] as const)('maps authoritative OKS %s without policy evaluation',(result,status)=>expect(indicator('KNOWLEDGE_EXPOSURE_GOVERNANCE',[source('OKS','oks:1',result)]).status).toBe(status));
	it('keeps knowledge indicator deterministic and provenance-sensitive',()=>{const a=indicator('KNOWLEDGE_EXPOSURE_GOVERNANCE',[source('OKS','oks:1','ADMITTED')]),b=indicator('KNOWLEDGE_EXPOSURE_GOVERNANCE',[source('OKS','oks:1','ADMITTED')]),c=indicator('KNOWLEDGE_EXPOSURE_GOVERNANCE',[source('OKS','oks:1','ADMITTED','b'.repeat(64))]);expect(a).toEqual(b);expect(c.indicator_digest).not.toBe(a.indicator_digest);});
	it('requires credential and attempt evidence before runtime health',()=>{const credential=source('SEC_WU1','credential:1','RESOLUTION_SUCCEEDED'),attempt=source('SEC_WU1','attempt:1','TRANSPORT_SUCCEEDED');expect(indicator('RUNTIME_SECURITY_EVIDENCE',[attempt]).status).toBe('INCOMPLETE');expect(indicator('RUNTIME_SECURITY_EVIDENCE',[credential,attempt]).status).toBe('HEALTHY');});
	it('maps runtime denial, incomplete failure, and credentialless applicability truthfully',()=>{expect(indicator('RUNTIME_SECURITY_EVIDENCE',[source('SEC_WU1','credential:1','RESOLUTION_DENIED')]).status).toBe('DENIED');expect(indicator('RUNTIME_SECURITY_EVIDENCE',[source('SEC_WU1','attempt:1','TRANSPORT_FAILED')]).status).toBe('INCOMPLETE');expect(indicator('RUNTIME_SECURITY_EVIDENCE',[source('SEC_WU1','credential:1','NOT_APPLICABLE'),source('SEC_WU1','attempt:1','CREDENTIAL_NOT_APPLICABLE')]).status).toBe('NOT_APPLICABLE');});
	it('does not invent a DEGRADED source mapping',()=>{expect(()=>indicator('KNOWLEDGE_EXPOSURE_GOVERNANCE',[source('OKS','oks:1','DEGRADED')])).toThrowError(expect.objectContaining({code:'GOVERNANCE_INDICATOR_SOURCE_STATUS_INCONSISTENT'}));});
});

describe('GI-WU2 governance completeness aggregation',()=>{
	it('aggregates healthy contributors and ignores not-applicable contributors',()=>{const healthy=secIndicator(),na=secIndicator('NOT_APPLICABLE','AUTHORITY_INTEGRITY');expect(aggregate([healthy]).status).toBe('HEALTHY');expect(aggregate([healthy,na]).status).toBe('HEALTHY');expect(aggregate([na]).status).toBe('NOT_APPLICABLE');});
	it('uses deterministic denied and incomplete precedence',()=>{const healthy=secIndicator(),denied=secIndicator('DENIED','AUTHORITY_INTEGRITY'),incomplete=secIndicator('INCOMPLETE','AUTHORITY_INTEGRITY');expect(aggregate([healthy,incomplete]).status).toBe('INCOMPLETE');expect(aggregate([healthy,denied]).status).toBe('DENIED');expect(aggregate([denied,incomplete]).status).toBe('DENIED');});
	it('marks a required missing indicator incomplete without raw recomposition',()=>{const healthy=secIndicator();const x=aggregate([healthy],['SECURITY_EVIDENCE_COMPOSITION','PROVIDER_TRUST']);expect(x.status).toBe('INCOMPLETE');expect(JSON.stringify(x)).not.toMatch(/source_evidence|prompt|projection|provider response|credential/i);});
	it('is contributor-order independent and contributor changes alter digest',()=>{const a=secIndicator(),b=secIndicator('NOT_APPLICABLE','AUTHORITY_INTEGRITY'),x=aggregate([a,b]),y=aggregate([b,a]),z=aggregate([a,secIndicator('DENIED','AUTHORITY_INTEGRITY')]);expect(x).toEqual(y);expect(z.aggregate_digest).not.toBe(x.aggregate_digest);});
	it('rejects duplicate, tampered, cross-context, and mixed-history contributors',()=>{const a=secIndicator();expect(()=>aggregate([a,a])).toThrowError(expect.objectContaining({code:'GOVERNANCE_INDICATOR_CONTRIBUTOR_DUPLICATE'}));expect(()=>aggregate([{...a,indicator_digest:'x'}])).toThrowError(expect.objectContaining({code:'GOVERNANCE_INDICATOR_CONTRIBUTOR_DIGEST_MISMATCH'}));expect(()=>aggregate([a],undefined,{tenant_id:'other'})).toThrowError(expect.objectContaining({code:'GOVERNANCE_INDICATOR_CONTRIBUTOR_TENANT_MISMATCH'}));expect(()=>aggregate([a],undefined,{company_id:'other'})).toThrowError(expect.objectContaining({code:'GOVERNANCE_INDICATOR_CONTRIBUTOR_COMPANY_MISMATCH'}));expect(()=>aggregate([a],undefined,{subject_id:'other'})).toThrowError(expect.objectContaining({code:'GOVERNANCE_INDICATOR_CONTRIBUTOR_SUBJECT_MISMATCH'}));expect(()=>aggregate([a],undefined,{historical_mode:'CURRENT'})).toThrowError(expect.objectContaining({code:'GOVERNANCE_INDICATOR_HISTORICAL_MODE_MISMATCH'}));});
	it('remains immutable, content-free, score-free, UI-free, and non-authorizing',()=>{const x=aggregate([secIndicator()]);expect(Object.isFrozen(x)&&Object.isFrozen(x.contributors)).toBe(true);expect(JSON.stringify(x)).not.toMatch(/score|confidence|color|badge|alert|notification|execution_allowed|permit|authorization|business payload/i);});
});
