import{describe,expect,it}from"vitest";import{digest,verifyProviderFactsV1,type ProviderVerificationRequestV1}from"..";
const NOW="2026-08-07T10:00:00.000Z",HEX=`sha256:${"a".repeat(64)}`;
async function fixture():Promise<ProviderVerificationRequestV1>{const account=`provider-account:sha256:${(await digest("openrouter:owner:account-opaque:PRODUCTION")).slice(0,32)}`,deployment=`provider-deployment:sha256:${(await digest(`${account}:deployment-eu`)).slice(0,32)}`,e=(id:string,subject:any,value:any,dep?:string)=>({version:1 as const,evidence_id:id,issuer_id:"PLANNERNET_PROVIDER_CONTRACT_REVIEW",issuer_class:"GOVERNED_MANUAL_CONTRACT_REVIEW"as const,provider_account_id:account,...(dep?{provider_deployment_id:dep}:{}),subject,asserted_value:value,evidence_type:"IMMUTABLE_DOCUMENT_REFERENCE"as const,governed_reference:`vault:${id}`,immutable_digest:HEX,issued_at:NOW,effective_at:NOW,expires_at:"2027-01-01T00:00:00.000Z",verification_state:"ACCEPTED"as const,verifier_id:"PLANNERNET_PROVIDER_CONTRACT_REVIEW",correlation_id:"correlation",causal_references:[]}),d=(id:string,evidence_id:string)=>({version:1 as const,decision_id:id,evidence_id,verifier_id:"PLANNERNET_PROVIDER_CONTRACT_REVIEW",decision:"VERIFIED"as const,reason_codes:[],decided_at:NOW,valid_until:"2027-01-01T00:00:00.000Z",correlation_id:"correlation",causal_references:[evidence_id]});return{claim:{version:1,claim_id:"claim",provider:"openrouter",account_reference:"account-opaque",account_owner_reference:"owner",adapter_identity:"sandbox.llm.openrouter",environment_class:"PRODUCTION",claimed_deployment_reference:"deployment-eu",claimed_deployment_class:"SHARED_REMOTE_PROVIDER",claimant_id:"principal",evidence_references:["account-evidence"],effective_at:NOW,correlation_id:"correlation",causal_references:[]},account_evidence:e("account-evidence","ENTERPRISE_AGREEMENT_ACTIVE",{kind:"BOOLEAN",value:true}),account_decision:d("account-decision","account-evidence"),deployment:{version:1,provider_deployment_id:deployment,deployment_reference:"deployment-eu",deployment_class:"SHARED_REMOTE_PROVIDER",model_references:["openai/gpt-4o-mini"],processing_service_identity:"openrouter",verified_regions:[],credential_reference:"secret://providers/openrouter",effective_at:NOW,evidence_references:["account-evidence"],verified_at:NOW,reverify_at:"2027-01-01T00:00:00.000Z",correlation_id:"correlation",causal_references:[]},attestations:[{evidence:e("dpa","DPA_ACTIVE",{kind:"BOOLEAN",value:true},deployment),decision:d("dpa-decision","dpa")},{evidence:e("training","TRAINING_USE",{kind:"TRAINING_USE",value:"PROHIBITED"},deployment),decision:d("training-decision","training")} ]};}
const fails=async(p:Promise<unknown>,code:string)=>expect(p).rejects.toMatchObject({code});
describe("PT-WU1 provider facts",()=>{
 it("returns deterministic deeply immutable account, deployment, attestations and set digest",async()=>{const r=await fixture(),a=await verifyProviderFactsV1(r,NOW),b=await verifyProviderFactsV1(r,NOW);expect(a).toEqual(b);expect(Object.isFrozen(a)&&Object.isFrozen(a.attestations)).toBe(true);expect(a.attestation_set_digest).toHaveLength(64);});
 it("does not use provider brand, model, endpoint, environment variable or configuration as verification",async()=>{const r=await fixture();for(const x of [{provider_brand:"openrouter"},{model:"gpt"},{endpoint:"https://example"},{OPENROUTER_API_KEY:"secret"},{configured:true}])await fails(verifyProviderFactsV1({...r,account_evidence:undefined,...x}as any,NOW),"PROVIDER_ATTESTATION_EVIDENCE_INVALID");});
 it("denies unsupported providers and malformed exact account claims",async()=>{const r=await fixture();await fails(verifyProviderFactsV1({...r,claim:{...r.claim,provider:"unknown"as any}},NOW),"PROVIDER_ACCOUNT_CLAIM_INVALID");await fails(verifyProviderFactsV1({...r,claim:{...r.claim,account_reference:""}},NOW),"PROVIDER_ACCOUNT_CLAIM_INVALID");});
 it("keeps OpenRouter account distinct from an unproven downstream provider",async()=>{const f=await verifyProviderFactsV1(await fixture(),NOW);expect(f.account.provider).toBe("openrouter");expect(f.deployment?.model_references).toEqual(["openai/gpt-4o-mini"]);expect(f).not.toHaveProperty("downstream_provider_account_id");});
 it("requires evidence for dedicated and sovereign deployment claims",async()=>{const r=await fixture();await fails(verifyProviderFactsV1({...r,deployment:{...r.deployment!,deployment_class:"SOVEREIGN_REGION_EXTERNAL_PROVIDER",evidence_references:[]}},NOW),"PROVIDER_ATTESTATION_EVIDENCE_REQUIRED");});
 it("denies credential secret or substitution-shaped references",async()=>{const r=await fixture();await fails(verifyProviderFactsV1({...r,deployment:{...r.deployment!,credential_reference:"sk-secret"}},NOW),"PROVIDER_CREDENTIAL_BINDING_INVALID");});
 it("denies missing, expired, untrusted, wrong-account and wrong-deployment evidence",async()=>{for(const change of [{issuer_id:"claimant"},{expires_at:NOW},{provider_account_id:"other"},{provider_deployment_id:"other"}]){const r=await fixture();await fails(verifyProviderFactsV1({...r,attestations:[{...r.attestations[0]!,evidence:{...r.attestations[0]!.evidence,...change}}]},NOW),change.issuer_id?"PROVIDER_ATTESTATION_ISSUER_UNTRUSTED":change.expires_at?"PROVIDER_ATTESTATION_EVIDENCE_EXPIRED":change.provider_account_id?"PROVIDER_ATTESTATION_ACCOUNT_MISMATCH":"PROVIDER_ATTESTATION_DEPLOYMENT_MISMATCH");}});
 it("denies marketing language and malformed normalized retention or regions",async()=>{for(const value of [{kind:"RETENTION",value:"30 days"},{kind:"REGIONS",values:["eu west"]}]){const r=await fixture(),p=r.attestations[0]!;await fails(verifyProviderFactsV1({...r,attestations:[{...p,evidence:{...p.evidence,subject:value.kind==="REGIONS"?"PROCESSING_REGION":"RETENTION_LIMIT",asserted_value:value as any}}]},NOW),"PROVIDER_ATTESTATION_VALUE_INVALID");}});
 it("fails closed on contradictory active attestations while keeping unrelated subjects independent",async()=>{const r=await fixture(),p=r.attestations[1]!;await fails(verifyProviderFactsV1({...r,attestations:[...r.attestations,{evidence:{...p.evidence,evidence_id:"training-2",asserted_value:{kind:"TRAINING_USE",value:"ALLOWED"}},decision:{...p.decision,decision_id:"training-decision-2",evidence_id:"training-2"}}]},NOW),"PROVIDER_ATTESTATION_CONTRADICTED");});
 it("contains no credential secret, contract body, prompt, output or tenant knowledge",async()=>{const x=JSON.stringify(await verifyProviderFactsV1(await fixture(),NOW));expect(x).not.toMatch(/sk-|contract_body|prompt|model_output|order|inventory/i);});
});
export{fixture,NOW};
