import{describe,expect,it}from"vitest";import{verifyProviderFactsV1}from"..";import{fixture,NOW}from"./provider.attestation.test.fixtures";
const fails=async(p:Promise<unknown>,code:string)=>expect(p).rejects.toMatchObject({code});
describe("PT-WU1 provider facts",()=>{
 it("returns deterministic deeply immutable account, deployment, attestations and set digest",async()=>{const r=await fixture(),a=await verifyProviderFactsV1(r,NOW),b=await verifyProviderFactsV1(r,NOW);expect(a).toEqual(b);expect(Object.isFrozen(a)&&Object.isFrozen(a.attestations)).toBe(true);expect(a.attestation_set_digest).toHaveLength(64);});
 it("does not use provider brand, model, endpoint, environment variable or configuration as verification",async()=>{const r=await fixture();for(const x of [{provider_brand:"openrouter"},{model:"gpt"},{endpoint:"https://example"},{OPENROUTER_API_KEY:"secret"},{configured:true}])await fails(verifyProviderFactsV1({...r,account_evidence:undefined,...x}as any,NOW),"PROVIDER_ATTESTATION_EVIDENCE_INVALID");});
 it("denies unsupported providers and malformed exact account claims",async()=>{const r=await fixture();await fails(verifyProviderFactsV1({...r,claim:{...r.claim,provider:"unknown"as any}},NOW),"PROVIDER_ACCOUNT_CLAIM_INVALID");await fails(verifyProviderFactsV1({...r,claim:{...r.claim,account_reference:""}},NOW),"PROVIDER_ACCOUNT_CLAIM_INVALID");});
 it("keeps OpenRouter account distinct from an unproven downstream provider",async()=>{const f=await verifyProviderFactsV1(await fixture(),NOW);expect(f.account.provider).toBe("openrouter");expect(f.deployment?.model_references).toEqual(["openai/gpt-4o-mini"]);expect(f).not.toHaveProperty("downstream_provider_account_id");});
 it("requires evidence for dedicated and sovereign deployment claims",async()=>{const r=await fixture();await fails(verifyProviderFactsV1({...r,deployment:{...r.deployment!,deployment_class:"SOVEREIGN_REGION_EXTERNAL_PROVIDER",evidence_references:[]}},NOW),"PROVIDER_ATTESTATION_EVIDENCE_REQUIRED");});
 it("denies credential secret or substitution-shaped references",async()=>{const r=await fixture();await fails(verifyProviderFactsV1({...r,deployment:{...r.deployment!,credential_reference:"sk-secret"}},NOW),"PROVIDER_CREDENTIAL_BINDING_INVALID");});
 it("denies missing, expired, untrusted, wrong-account and wrong-deployment evidence",async()=>{for(const change of [{issuer_id:"claimant"},{expires_at:NOW},{provider_account_id:"other"},{provider_deployment_id:"other"}]){const r=await fixture();await fails(verifyProviderFactsV1({...r,attestations:[{...r.attestations[0]!,evidence:{...r.attestations[0]!.evidence,...change}}]},NOW),change.issuer_id?"PROVIDER_ATTESTATION_ISSUER_UNTRUSTED":change.expires_at?"PROVIDER_ATTESTATION_EVIDENCE_EXPIRED":change.provider_account_id?"PROVIDER_ATTESTATION_ACCOUNT_MISMATCH":"PROVIDER_ATTESTATION_DEPLOYMENT_MISMATCH");}});
 it("denies marketing language and malformed normalized retention or regions",async()=>{for(const value of [{kind:"RETENTION",value:"30 days"},{kind:"REGIONS",values:["eu west"]}]){const r=await fixture(),p=r.attestations[0]!;await fails(verifyProviderFactsV1({...r,attestations:[{...p,evidence:{...p.evidence,subject:value.kind==="REGIONS"?"PROCESSING_REGION":"RETENTION_LIMIT",asserted_value:value as any}}]},NOW),"PROVIDER_ATTESTATION_VALUE_INVALID");}});
 it("fails closed on contradictory active attestations while keeping unrelated subjects independent",async()=>{const r=await fixture(),p=r.attestations[1]!;await fails(verifyProviderFactsV1({...r,attestations:[...r.attestations,{evidence:{...p.evidence,evidence_id:"training-2",asserted_value:{kind:"TRAINING_USE",value:"ALLOWED"}},decision:{...p.decision,decision_id:"training-decision-2",evidence_id:"training-2"}}]},NOW),"PROVIDER_ATTESTATION_CONTRADICTED");});
 it("contains no credential secret, contract body, prompt, output or tenant knowledge",async()=>{const x=JSON.stringify(await verifyProviderFactsV1(await fixture(),NOW));expect(x).not.toMatch(/sk-|contract_body|prompt|model_output|order|inventory/i);});
});
