import{describe,expect,it}from"vitest";import{digest,evaluateProviderTrustV1,issueProviderTrustEligibilityV1,issueTenantProviderTrustPolicyV1,resolveTenantProviderTrustPolicyV1,revalidateProviderTrustEligibilityV1,type ProviderContractualProcessingAttestationV1,type ProviderTrustRequirementV1,type ProviderVerifiedFactSetV1,type TenantProviderTrustPolicyRequestV1}from"..";
export const NOW="2026-08-07T10:00:00.000Z",LATER="2026-09-01T00:00:00.000Z";
const eligibility={version:1 as const,eligibility_id:"orpe:1",authority_id:"orpa:1",actor_principal_id:"principal",membership_id:"membership",legal_entity_id:"le:1",company_binding_id:"binding:1",requested_scope:"DEFINE_TENANT_PROVIDER_TRUST_REQUIREMENTS"as const,future_consumer:"PT_WU2_TENANT_PROVIDER_TRUST_POLICY"as const,issued_at:NOW,expires_at:LATER,policy_version:"ORPA_POLICY_V1"as const,correlation_id:"c",caused_by:["orpa:1"],transferable:false as const,executable:false as const};
const legal={version:1 as const,legal_entity_id:"le:1",canonical_key:"IT:X:1",jurisdiction:"IT",registration_profile:"X",registration_identifier:"1",registered_name:"Tenant",registration_type:"COMPANY",entity_status:"ACTIVE"as const,verification_status:"VERIFIED_BY_AUTHORIZED_REVIEW"as const,verification_method:"GOVERNED_MANUAL_REVIEW"as const,verification_evidence_ids:["e"],effective_at:NOW,verified_at:NOW,reverify_at:LATER,claim_id:"claim",verification_decision_id:"decision",correlation_id:"c",caused_by:[]};
const binding={version:1 as const,binding_id:"binding:1",company_id:"company:1",legal_entity_id:"le:1",bound_at:NOW,binding_reference:"ref",correlation_id:"c",caused_by:[],grants_membership:false as const,grants_authority:false as const,grants_contractual_authority:false as const};
export const context={version:1 as const,tenant_id:"tenant:1",company_id:"company:1",purpose:"LANGUAGE_REFINEMENT"as const,classification:"SENSITIVE"as const,sovereignty:"REGION_LOCKED"as const,target_class:"SHARED_REMOTE_PROVIDER"as const,processing_region:"EU",retention:"NO_RETENTION"as const};
export function request(requirements:readonly ProviderTrustRequirementV1[]=[{requirement_id:"dpa",subject:"DPA_ACTIVE",operator:"REQUIRED_TRUE",value:true},{requirement_id:"training",subject:"TRAINING_USE",operator:"EXACT",value:"PROHIBITED"},{requirement_id:"retention",subject:"RETENTION_LIMIT",operator:"MAXIMUM",maximum_days:30},{requirement_id:"region",subject:"PROCESSING_REGION",operator:"SUBSET_OF",values:["EU"]},{requirement_id:"deployment",subject:"DEPLOYMENT_CLASS",operator:"ONE_OF",values:["SHARED_REMOTE_PROVIDER"]}]):TenantProviderTrustPolicyRequestV1{return{tenant_id:"tenant:1",company_id:"company:1",legal_entity:legal,company_binding:binding,owner_eligibility:eligibility,policy_version:1,scope:{scope_id:"BASE"},requirements,effective_at:NOW,expires_at:LATER,correlation_id:"c",causal_references:[]};}
const att=(subject:any,value:any):ProviderContractualProcessingAttestationV1=>({version:1,attestation_id:`a:${subject}`,provider_account_id:"pa:1",provider_deployment_id:"pd:1",subject,value,evidence_id:`e:${subject}`,issuer_id:"review",issuer_class:"GOVERNED_MANUAL_CONTRACT_REVIEW",status:"VERIFIED",effective_at:NOW,expires_at:LATER,verified_at:NOW,decision_id:`d:${subject}`,correlation_id:"c",causal_references:[]});
export function facts(overrides:Partial<ProviderVerifiedFactSetV1>={}):ProviderVerifiedFactSetV1{return{version:1,account:{version:1,provider_account_id:"pa:1",canonical_key:"openrouter:o:a:PRODUCTION",provider:"openrouter",account_reference:"a",account_owner_reference:"o",adapter_identity:"openrouter",environment_class:"PRODUCTION",effective_at:NOW,verification_status:"VERIFIED",verification_method:"GOVERNED_MANUAL_REVIEW",evidence_references:["e"],verified_at:NOW,reverify_at:LATER,claim_id:"claim",decision_id:"decision",correlation_id:"c",causal_references:[]},deployment:{version:1,provider_deployment_id:"pd:1",provider_account_id:"pa:1",deployment_reference:"dep",deployment_class:"SHARED_REMOTE_PROVIDER",model_references:["openai/gpt"],processing_service_identity:"openrouter",verified_regions:[],effective_at:NOW,verification_status:"VERIFIED",evidence_references:["e"],verified_at:NOW,reverify_at:LATER,correlation_id:"c",causal_references:[]},attestations:[att("DPA_ACTIVE",{kind:"BOOLEAN",value:true}),att("TRAINING_USE",{kind:"TRAINING_USE",value:"PROHIBITED"}),att("RETENTION_LIMIT",{kind:"RETENTION",value:"BOUNDED_DAYS",maximum_days:30}),att("PROCESSING_REGION",{kind:"REGIONS",values:["EU"]})],attestation_set_digest:"set:1",...overrides};}
async function policy(r=request()){return issueTenantProviderTrustPolicyV1(r,NOW)}async function resolved(ps=undefined as any){return resolveTenantProviderTrustPolicyV1(ps??[{policy:await policy()}],context,NOW)}async function evaluation(f=facts(),rs=undefined as any){const p=rs??await resolved();return evaluateProviderTrustV1({legal_entity_id:"le:1",resolved_policy:p,facts:f,context,expires_at:LATER,correlation_id:"c",causal_references:[]},NOW)}const fails=(p:Promise<unknown>,code:string)=>expect(p).rejects.toMatchObject({code});
describe("PT-WU2 ownership and immutable policy",()=>{
 it("accepts only the exact ORPA scope/consumer and identity lineage",async()=>{const p=await policy();expect(p.owner_eligibility_id).toBe("orpe:1");expect(Object.isFrozen(p)&&Object.isFrozen(p.requirements)).toBe(true);for(const owner of [undefined,{...eligibility,requested_scope:"ACCEPT_ENTERPRISE_NDA"},{...eligibility,future_consumer:"PLATFORM_CONTRACT_ACCEPTANCE"},{...eligibility,expires_at:NOW}])await fails(issueTenantProviderTrustPolicyV1({...request(),owner_eligibility:owner}as any,NOW),"PROVIDER_TRUST_POLICY_OWNER_UNAUTHORIZED");});
 it("denies Legal Entity and Company substitution",async()=>{await fails(issueTenantProviderTrustPolicyV1({...request(),legal_entity:{...legal,legal_entity_id:"other"}},NOW),"PROVIDER_TRUST_POLICY_LEGAL_ENTITY_MISMATCH");await fails(issueTenantProviderTrustPolicyV1({...request(),company_id:"other"},NOW),"PROVIDER_TRUST_POLICY_COMPANY_MISMATCH");});
 it("does not accept founder, membership, OAG, commercial tier or Planner level substitutes",async()=>{for(const x of[{founder:true},{membership_id:"m"},{oag_proof_id:"o"},{subscription:"ENTERPRISE"},{planner_level:"PRINCIPAL"}])await fails(issueTenantProviderTrustPolicyV1({...request(),owner_eligibility:undefined,...x}as any,NOW),"PROVIDER_TRUST_POLICY_OWNER_UNAUTHORIZED");});
 it("is deterministic, defensive, and rejects malformed or contradictory requirements",async()=>{const r=request(),a=await policy(r),b=await policy(r);expect(a).toEqual(b);(r.requirements as any[])[0].value=false;expect(a.requirements[0]).not.toEqual(r.requirements[0]);await fails(policy(request([{requirement_id:"x",subject:"RETENTION_LIMIT",operator:"MAXIMUM",maximum_days:-1}])),"PROVIDER_TRUST_POLICY_REQUIREMENT_INVALID");await fails(policy(request([{requirement_id:"a",subject:"DPA_ACTIVE",operator:"REQUIRED_TRUE",value:true},{requirement_id:"b",subject:"DPA_ACTIVE",operator:"REQUIRED_FALSE",value:false}])),"PROVIDER_TRUST_POLICY_CONFLICT");});
});
describe("PT-WU2 resolution and composition",()=>{
 it("resolves one applicable policy deterministically",async()=>{const a=await resolved(),b=await resolved();expect(a).toEqual(b);expect(a.requirements).toHaveLength(5);});
 it("composes base and specific policy using the most restrictive requirement",async()=>{const base=await policy(),specific=await policy({...request([{requirement_id:"retention-zero",subject:"RETENTION_LIMIT",operator:"MAXIMUM",maximum_days:0}]),policy_version:2,scope:{scope_id:"SENSITIVE",classifications:["SENSITIVE"]}});const r=await resolved([{policy:base},{policy:specific}]);expect((r.requirements.find(x=>x.subject==="RETENTION_LIMIT")as any).maximum_days).toBe(0);});
 it("fails closed on equally specific ambiguity and excludes inactive policy records",async()=>{const a=await policy(),b=await policy({...request(),policy_version:2,scope:{scope_id:"OTHER"}});await fails(resolved([{policy:a},{policy:b}]),"PROVIDER_TRUST_POLICY_AMBIGUOUS");await fails(resolved([{policy:a,status:"REVOKED"}]),"PROVIDER_TRUST_POLICY_SCOPE_INVALID");});
});
describe("PT-WU2 deterministic evaluation",()=>{
 it("returns SATISFIED only for current evidence proving every requirement",async()=>{const e=await evaluation();expect(e.outcome).toBe("SATISFIED");expect(e.requirement_results.every(x=>x.outcome==="SATISFIED")).toBe(true);});
 it("distinguishes verified contradiction from insufficient evidence",async()=>{const f=facts(),denied=facts({attestations:f.attestations.map(a=>a.subject==="DPA_ACTIVE"?att("DPA_ACTIVE",{kind:"BOOLEAN",value:false}):a)}),missing=facts({attestations:f.attestations.filter(a=>a.subject!=="DPA_ACTIVE")});expect((await evaluation(denied)).outcome).toBe("DENIED");expect((await evaluation(missing)).outcome).toBe("INSUFFICIENT_EVIDENCE");});
 it("handles training, retention, region and deployment facts fail closed",async()=>{const f=facts();for(const [changed,outcome]of[[facts({attestations:f.attestations.map(a=>a.subject==="TRAINING_USE"?att("TRAINING_USE",{kind:"TRAINING_USE",value:"ALLOWED"}):a)}),"DENIED"],[facts({attestations:f.attestations.map(a=>a.subject==="TRAINING_USE"?att("TRAINING_USE",{kind:"TRAINING_USE",value:"UNSPECIFIED"}):a)}),"INSUFFICIENT_EVIDENCE"],[facts({attestations:f.attestations.map(a=>a.subject==="RETENTION_LIMIT"?att("RETENTION_LIMIT",{kind:"RETENTION",value:"PROVIDER_DEFAULT"}):a)}),"INSUFFICIENT_EVIDENCE"],[facts({attestations:f.attestations.map(a=>a.subject==="PROCESSING_REGION"?att("PROCESSING_REGION",{kind:"REGIONS",values:["US"]}):a)}),"DENIED"],[facts({deployment:{...f.deployment!,deployment_class:"LOCAL_SELF_HOSTED_MODEL"}}),"DENIED"]]as const)expect((await evaluation(changed)).outcome).toBe(outcome);});
 it("does not infer OpenRouter downstream or local/customer-managed protections",async()=>{const r=await resolved([{policy:await policy(request([{requirement_id:"region",subject:"PROCESSING_REGION",operator:"SUBSET_OF",values:["EU"]}]))}]);expect((await evaluation(facts({attestations:[]}),r)).outcome).toBe("INSUFFICIENT_EVIDENCE");for(const cls of["LOCAL_SELF_HOSTED_MODEL","CUSTOMER_MANAGED_INFRASTRUCTURE"]as const)expect((await evaluation(facts({deployment:{...facts().deployment!,deployment_class:cls},attestations:[]}),r)).outcome).toBe("INSUFFICIENT_EVIDENCE");});
});
describe("PT-WU2 eligibility and staleness",()=>{
 it("issues immutable eligibility only for SATISFIED and exact PT-WU3 consumer",async()=>{const e=await evaluation(),x=await issueProviderTrustEligibilityV1(e,"PT_WU3_RUNTIME_PROVIDER_ADMISSION",NOW);expect(x.future_consumer).toBe("PT_WU3_RUNTIME_PROVIDER_ADMISSION");expect(x.executable).toBe(false);expect(JSON.stringify(x)).not.toMatch(/credential|prompt|knowledge|provider_response/i);await fails(issueProviderTrustEligibilityV1({...e,outcome:"DENIED"},"PT_WU3_RUNTIME_PROVIDER_ADMISSION",NOW),"PROVIDER_TRUST_ELIGIBILITY_NOT_GRANTED");await fails(issueProviderTrustEligibilityV1(e,"OTHER",NOW),"PROVIDER_TRUST_ELIGIBILITY_NOT_GRANTED");});
 it("rejects policy, attestation, context, account and deployment changes as stale",async()=>{const e=await evaluation(),x=await issueProviderTrustEligibilityV1(e,"PT_WU3_RUNTIME_PROVIDER_ADMISSION",NOW),current={policy_digest:x.policy_digest,attestation_set_digest:x.attestation_set_digest,context_digest:x.context_digest,provider_account_id:x.provider_account_id,provider_deployment_id:x.provider_deployment_id};for(const change of[{policy_digest:"other"},{attestation_set_digest:"other"},{context_digest:"other"},{provider_account_id:"other"},{provider_deployment_id:"other"}])expect(()=>revalidateProviderTrustEligibilityV1(x,{...current,...change},NOW)).toThrow(/PROVIDER_TRUST_EVALUATION_STALE/);});
});
export{policy,resolved,evaluation};
