import{applyD1Migrations,env}from"cloudflare:test";import{beforeAll,describe,expect,it}from"vitest";import migration from"../../../../migrations/0024_tenant_provider_trust_policy.sql?raw";import{TenantProviderTrustD1V1,issueProviderTrustEligibilityV1}from"..";import{NOW,evaluation,policy,resolved}from"./tenant.provider.trust.runtime.test";
const db=env.POLICIES_DB,repo=new TenantProviderTrustD1V1(db);function queries(sql:string){return sql.split(/;\s*(?=CREATE)/).map(x=>x.trim()).filter(Boolean).map(x=>x.endsWith(";")?x:`${x};`);}beforeAll(()=>applyD1Migrations(db,[{name:"0024",queries:queries(migration)}]));
describe("PT-WU2 actual D1",()=>{
 it("applies migration and makes policy, scope, requirement and audit rows immutable",async()=>{const p=await policy();await repo.persistPolicy(p);expect(await repo.readPolicy(p.policy_id)).toEqual(p);for(const t of["tenant_provider_trust_policies","tenant_provider_trust_policy_scopes","tenant_provider_trust_requirements","provider_trust_audit_events"])await expect(db.prepare(`UPDATE ${t} SET rowid=rowid`).run()).rejects.toThrow(/IMMUTABLE/);});
 it("concurrent identical policy persistence converges",async()=>{const p=await policy(),xs=await Promise.all([repo.persistPolicy(p),repo.persistPolicy(p)]);expect(new Set(xs.map(x=>x.policy_id)).size).toBe(1);expect((await db.prepare("SELECT COUNT(*) n FROM tenant_provider_trust_policies").first<{n:number}>())?.n).toBe(1);});
 it("persists immutable resolution, evaluation, per-requirement results and eligibility",async()=>{const p=await policy(),r=await resolved([{policy:p}]);await repo.persistResolution(r);const e=await evaluation(undefined,r),x=await issueProviderTrustEligibilityV1(e,"PT_WU3_RUNTIME_PROVIDER_ADMISSION",NOW);await repo.persistEvaluation(e,x);for(const t of["tenant_provider_trust_resolutions","provider_trust_evaluations","provider_trust_requirement_results","provider_trust_eligibilities"])await expect(db.prepare(`UPDATE ${t} SET rowid=rowid`).run()).rejects.toThrow(/IMMUTABLE/);expect((await db.prepare("SELECT dispatch_authorized FROM provider_trust_evaluations").first<{dispatch_authorized:number}>())?.dispatch_authorized).toBe(0);});
 it("persists denial and insufficient-evidence outcomes without issuing eligibility",async()=>{const r=await resolved(),base=await evaluation(),denied={...base,evaluation_id:"eval:denied",evaluation_digest:"digest:denied",outcome:"DENIED"as const,reason_codes:["DPA_DENIED"]},insufficient={...base,evaluation_id:"eval:insufficient",evaluation_digest:"digest:insufficient",outcome:"INSUFFICIENT_EVIDENCE"as const,reason_codes:["ATTESTATION_MISSING"]};await repo.persistResolution(r).catch(()=>{});await repo.persistEvaluation(denied);await repo.persistEvaluation(insufficient);expect((await db.prepare("SELECT COUNT(*) n FROM provider_trust_evaluations WHERE outcome!='SATISFIED'").first<{n:number}>())?.n).toBe(2);expect((await db.prepare("SELECT COUNT(*) n FROM provider_trust_eligibilities").first<{n:number}>())?.n).toBe(0);});
 it("persists immutable policy lifecycle and content-free audit",async()=>{const p=await policy();await repo.persistPolicy(p);await repo.transition(p.policy_id,"REVOKED","revoke:1",NOW,"c");await expect(db.prepare("UPDATE tenant_provider_trust_policy_transitions SET status='EXPIRED'").run()).rejects.toThrow(/IMMUTABLE/);const audit=JSON.stringify((await db.prepare("SELECT * FROM provider_trust_audit_events").all()).results);expect(audit).not.toMatch(/secret:\/\/|contract_body|prompt|model_output|inventory|order/i);});
});
