import {describe,expect,it}from"vitest";import{grantOrganizationalRepresentationAuthorityV1,issueOrganizationalRepresentationEligibilityV1,type OrganizationalRepresentationScopeV1}from"..";import{expiry,later,now,orpaRequest}from"./organizational.representation.fixtures.v1";
async function deny(p:Promise<unknown>,code:string){await expect(p).rejects.toMatchObject({code});}
describe("ORPA-WU1 identity, membership, and representation composition",()=>{
 it("grants one deterministic immutable authority without execution",async()=>{const r=await orpaRequest();const a=await grantOrganizationalRepresentationAuthorityV1(r,now);expect(await grantOrganizationalRepresentationAuthorityV1(r,now)).toEqual(a);expect(Object.isFrozen(a)).toBe(true);expect(a.authorized_scopes).toEqual(["ACCEPT_ENTERPRISE_NDA"]);expect(a.grants_execution).toBe(false);});
 it("denies unverified, expired, revoked, superseded, or substituted Legal Entity state",async()=>{const r=await orpaRequest();await deny(grantOrganizationalRepresentationAuthorityV1({...r,state:{...r.state,legal_entity:{...r.state.legal_entity,legal_entity_id:"other"}}},now),"ORPA_LEGAL_ENTITY_NOT_VERIFIED");await deny(grantOrganizationalRepresentationAuthorityV1({...r,state:{...r.state,legal_entity:{...r.state.legal_entity,reverify_at:now}}},now),"ORPA_LEGAL_ENTITY_EXPIRED");await deny(grantOrganizationalRepresentationAuthorityV1({...r,state:{...r.state,legal_entity:{...r.state.legal_entity,verification_status:"REVOKED"}}},now),"ORPA_LEGAL_ENTITY_REVOKED");await deny(grantOrganizationalRepresentationAuthorityV1({...r,state:{...r.state,legal_entity:{...r.state.legal_entity,verification_status:"SUPERSEDED"}}},now),"ORPA_LEGAL_ENTITY_EXPIRED");});
 it("requires the exact Company binding",async()=>{const r=await orpaRequest();await deny(grantOrganizationalRepresentationAuthorityV1({...r,state:{...r.state,company_binding:{...r.state.company_binding,binding_id:"substituted"}}},now),"ORPA_COMPANY_BINDING_INVALID");});
 it("requires active exact principal, session, and membership",async()=>{const r=await orpaRequest();await deny(grantOrganizationalRepresentationAuthorityV1({...r,state:{...r.state,principal:{...r.state.principal,lifecycle_state:"SUSPENDED"}}},now),"ORPA_PRINCIPAL_INVALID");await deny(grantOrganizationalRepresentationAuthorityV1({...r,state:{...r.state,session:{...r.state.session,expires_at:now}}},now),"ORPA_SESSION_INVALID");await deny(grantOrganizationalRepresentationAuthorityV1({...r,state:{...r.state,membership:{...r.state.membership,membership_id:"other"}}},now),"ORPA_MEMBERSHIP_INVALID");});
 it("does not treat membership or founder/CEO/board titles as representation",async()=>{for(const title of[undefined,"FOUNDER","CEO","BOARD_MEMBER"]){const r=await orpaRequest();await deny(grantOrganizationalRepresentationAuthorityV1({...r,claim:{...r.claim,claimed_position:title},evidence:[]},now),"ORPA_REPRESENTATION_EVIDENCE_REQUIRED");}});
 it("admits founder and non-founder actors only through exact evidence",async()=>{for(const title of["FOUNDER","OPERATIONS_DIRECTOR"]){const r=await orpaRequest();await expect(grantOrganizationalRepresentationAuthorityV1({...r,claim:{...r.claim,claimed_position:title}},now)).resolves.toMatchObject({actor_principal_id:"principal-1"});}});
});
describe("ORPA-WU1 evidence, OAG, scopes, and eligibility",()=>{
 it("denies missing, untrusted, expired, cross-entity, and cross-scope evidence",async()=>{const r=await orpaRequest();await deny(grantOrganizationalRepresentationAuthorityV1({...r,evidence:[]},now),"ORPA_REPRESENTATION_EVIDENCE_REQUIRED");await deny(grantOrganizationalRepresentationAuthorityV1({...r,evidence:[{...r.evidence[0]!,issuer_id:"claimant"}]},now),"ORPA_REPRESENTATION_ISSUER_UNTRUSTED");await deny(grantOrganizationalRepresentationAuthorityV1({...r,evidence:[{...r.evidence[0]!,expires_at:now}]},now),"ORPA_REPRESENTATION_EVIDENCE_EXPIRED");await deny(grantOrganizationalRepresentationAuthorityV1({...r,evidence:[{...r.evidence[0]!,legal_entity_id:"other"}]},now),"ORPA_REPRESENTATION_EVIDENCE_INVALID");await deny(grantOrganizationalRepresentationAuthorityV1({...r,evidence:[{...r.evidence[0]!,authorized_scopes:["ACCEPT_DATA_PROCESSING_AGREEMENT"]}]},now),"ORPA_SCOPE_NOT_GRANTED");});
 it("requires exact current OAG proof for policy-ownership scopes and rejects drift",async()=>{const r=await orpaRequest("DEFINE_TENANT_PROVIDER_TRUST_REQUIREMENTS");await deny(grantOrganizationalRepresentationAuthorityV1({...r,state:{...r.state,oag_proof:undefined}},now),"ORPA_AUTHORITY_PROOF_REQUIRED");await deny(grantOrganizationalRepresentationAuthorityV1({...r,state:{...r.state,oag_proof:{...r.state.oag_proof!,drifted:true}}},now),"ORPA_AUTHORITY_DRIFTED");await expect(grantOrganizationalRepresentationAuthorityV1(r,now)).resolves.toHaveProperty("oag_proof_id","oag-proof-1");});
 it("supports every closed narrow scope without implication",async()=>{const scopes:OrganizationalRepresentationScopeV1[]=["ACCEPT_ENTERPRISE_NDA","ACCEPT_DATA_PROCESSING_AGREEMENT","ACCEPT_PROVIDER_PROCESSING_TERMS","DEFINE_TENANT_PROVIDER_TRUST_REQUIREMENTS","APPOINT_PROCESSING_AUTHORITY","REPRESENT_LEGAL_ENTITY_FOR_PLATFORM_ONBOARDING"];for(const scope of scopes){const a=await grantOrganizationalRepresentationAuthorityV1(await orpaRequest(scope),now);expect(a.authorized_scopes).toEqual([scope]);}});
 it("denies prohibited, unsupported, expanded, and ambiguous authority",async()=>{const r=await orpaRequest();await deny(grantOrganizationalRepresentationAuthorityV1({...r,prohibited_scopes:[r.claim.requested_scope]},now),"ORPA_SCOPE_PROHIBITED");await deny(grantOrganizationalRepresentationAuthorityV1({...r,claim:{...r.claim,requested_scope:"FULL_CONTROL" as OrganizationalRepresentationScopeV1}},now),"ORPA_SCOPE_UNSUPPORTED");await deny(grantOrganizationalRepresentationAuthorityV1({...r,evidence:[r.evidence[0]!,{...r.evidence[0]!,evidence_id:"second",governed_reference:"second"}]},now),"ORPA_RECIPIENT_AMBIGUOUS");const a=await grantOrganizationalRepresentationAuthorityV1(r,now);await deny(issueOrganizationalRepresentationEligibilityV1(a,r.state,"ACCEPT_DATA_PROCESSING_AGREEMENT","PLATFORM_CONTRACT_ACCEPTANCE",now,later),"ORPA_SCOPE_EXPANSION_PROHIBITED");});
 it("issues deterministic single-purpose, non-transferable, non-executable eligibility",async()=>{const r=await orpaRequest("DEFINE_TENANT_PROVIDER_TRUST_REQUIREMENTS"),a=await grantOrganizationalRepresentationAuthorityV1(r,now);const e=await issueOrganizationalRepresentationEligibilityV1(a,r.state,"DEFINE_TENANT_PROVIDER_TRUST_REQUIREMENTS","PT_WU2_TENANT_PROVIDER_TRUST_POLICY",now,later);expect(await issueOrganizationalRepresentationEligibilityV1(a,r.state,e.requested_scope,e.future_consumer,now,later)).toEqual(e);expect(e).toMatchObject({transferable:false,executable:false,actor_principal_id:"principal-1",membership_id:"membership-1"});expect(JSON.stringify(e)).not.toMatch(/credential|provider_attestation|operational_data/);expect(Object.isFrozen(e)).toBe(true);});
 it("denies expired, revoked, superseded, or substituted current authority",async()=>{const r=await orpaRequest(),a=await grantOrganizationalRepresentationAuthorityV1(r,now),current={...r.state,session:{...r.state.session,expires_at:"2026-08-06T13:00:00.000Z"}};await deny(issueOrganizationalRepresentationEligibilityV1(a,current,"ACCEPT_ENTERPRISE_NDA","PLATFORM_CONTRACT_ACCEPTANCE",expiry,"2026-08-06T12:00:00.000Z"),"ORPA_ELIGIBILITY_EXPIRED");await deny(issueOrganizationalRepresentationEligibilityV1({...a,lifecycle_state:"REVOKED"},r.state,"ACCEPT_ENTERPRISE_NDA","PLATFORM_CONTRACT_ACCEPTANCE",now,later),"ORPA_AUTHORITY_REVOKED");await deny(issueOrganizationalRepresentationEligibilityV1({...a,lifecycle_state:"SUPERSEDED"},r.state,"ACCEPT_ENTERPRISE_NDA","PLATFORM_CONTRACT_ACCEPTANCE",now,later),"ORPA_AUTHORITY_SUPERSEDED");await deny(issueOrganizationalRepresentationEligibilityV1(a,{...r.state,membership:{...r.state.membership,membership_id:"substituted"}},"ACCEPT_ENTERPRISE_NDA","PLATFORM_CONTRACT_ACCEPTANCE",now,later),"ORPA_ACTOR_SUBSTITUTED");});
});
