import{applyD1Migrations,env}from"cloudflare:test";import{beforeAll,describe,expect,it}from"vitest";import oir from"../../../../migrations/0007_oir_track_a_persistence.sql?raw";import le from"../../../../migrations/0021_legal_entity_verification.sql?raw";import migration from"../../../../migrations/0022_organizational_representation_authority.sql?raw";import{LegalEntityD1V1,verifyLegalEntityV1}from"../../legal-entity";import{legalEntityRequestFixture}from"../../legal-entity/__tests__/legal.entity.fixtures.v1";import{grantOrganizationalRepresentationAuthorityV1,issueOrganizationalRepresentationEligibilityV1,OrganizationalRepresentationD1V1}from"..";import{later,now,orpaRequest}from"./organizational.representation.fixtures.v1";
const db=env.POLICIES_DB,repo=new OrganizationalRepresentationD1V1(db),leRepo=new LegalEntityD1V1(db);function q(s:string){return s.split(/;\s*\r?\n(?=CREATE (?:TABLE|UNIQUE INDEX|TRIGGER))/).map(x=>x.trim()).filter(Boolean).map(x=>x.endsWith(";")?x:`${x};`);}
beforeAll(async()=>{await applyD1Migrations(db,[{name:"0007",queries:q(oir)},{name:"0021",queries:q(le)},{name:"0022",queries:q(migration)}]);await db.prepare("INSERT INTO oir_principals VALUES ('principal-1','HUMAN','ACTIVE',?)").bind(now).run();await db.prepare("INSERT INTO oir_companies VALUES ('company-1','ACTIVE',?)").bind(now).run();await db.prepare("INSERT INTO oir_organization_memberships (membership_id,principal_id,company_id,lifecycle_state,created_at,invitation_or_request_reference) VALUES ('membership-1','principal-1','company-1','REQUESTED',?,'request')").bind(now).run();await db.prepare("UPDATE oir_organization_memberships SET lifecycle_state='ACTIVE',activation_reference='activation',activated_at=? WHERE membership_id='membership-1'").bind(now).run();});
async function setup(scope:Parameters<typeof orpaRequest>[0]="ACCEPT_ENTERPRISE_NDA"){const ler=legalEntityRequestFixture(),identity=await verifyLegalEntityV1(ler,now);await leRepo.persistVerification(ler,identity);const req=await orpaRequest(scope);await leRepo.bindCompany(req.state.company_binding);const authority=await grantOrganizationalRepresentationAuthorityV1(req,now);return{req,authority};}
describe("ORPA-WU1 actual D1 persistence",()=>{
 it("applies migration and persists immutable normalized grant evidence",async()=>{const{req,authority}=await setup();await repo.persistGrant(req.claim,req.evidence,authority,now);const tables=await db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'orpa_%'").all();expect(tables.results).toHaveLength(8);for(const[t,c]of[["orpa_representation_claims","claim_id"],["orpa_representation_evidence","issuer_id"],["orpa_authority_decisions","approver_id"],["orpa_authorities","approver_id"],["orpa_authority_scopes","scope"]])await expect(db.prepare(`UPDATE ${t} SET ${c}=${c}`).run()).rejects.toThrow(/IMMUTABLE/);});
 it("converges concurrent duplicate grant persistence",async()=>{const{req,authority}=await setup();await Promise.all([repo.persistGrant(req.claim,req.evidence,authority,now),repo.persistGrant(req.claim,req.evidence,authority,now)]);expect((await db.prepare("SELECT COUNT(*) count FROM orpa_authorities WHERE authority_id=?").bind(authority.authority_id).first<{count:number}>())?.count).toBe(1);});
 it("persists single-purpose eligibility and atomically denies replay",async()=>{const{req,authority}=await setup("DEFINE_TENANT_PROVIDER_TRUST_REQUIREMENTS");await repo.persistGrant(req.claim,req.evidence,authority,now);const e=await issueOrganizationalRepresentationEligibilityV1(authority,req.state,req.claim.requested_scope,"PT_WU2_TENANT_PROVIDER_TRUST_POLICY",now,later);await repo.persistEligibility(e);const consumedAt="2026-08-06T10:01:00.000Z";const results=await Promise.all([repo.consumeEligibility(e.eligibility_id,consumedAt,"consume-1"),repo.consumeEligibility(e.eligibility_id,consumedAt,"consume-2")]);expect(results.filter(Boolean)).toHaveLength(1);await expect(db.prepare("DELETE FROM orpa_eligibilities").run()).rejects.toThrow(/IMMUTABLE/);});
 it("persists immutable revocation and supersession lineage",async()=>{const{req,authority}=await setup();await repo.persistGrant(req.claim,req.evidence,authority,now);await repo.transition(authority.authority_id,"REVOKED","revoke-1",later,"correlation-r",[authority.authority_id]);expect((await db.prepare("SELECT to_state FROM orpa_authority_transitions").first<{to_state:string}>())?.to_state).toBe("REVOKED");await expect(db.prepare("UPDATE orpa_authority_transitions SET to_state='SUPERSEDED'").run()).rejects.toThrow(/IMMUTABLE/);});
 it("persists denial and ambiguity reasons in content-free audit",async()=>{const{req}=await setup();await repo.persistDenial({...req.claim,claim_id:"claim-denied"},"PLANNERNET_ORPA_REVIEW","ORPA_RECIPIENT_AMBIGUOUS",now);const decision=await db.prepare("SELECT reason_codes_json FROM orpa_authority_decisions").first<{reason_codes_json:string}>();expect(decision?.reason_codes_json).toContain("ORPA_RECIPIENT_AMBIGUOUS");const audit=JSON.stringify((await db.prepare("SELECT * FROM orpa_audit_events").all()).results);expect(audit).not.toMatch(/contract.body|credential|operational_data|provider_attestation/);await expect(db.prepare("UPDATE orpa_audit_events SET outcome='TAMPERED'").run()).rejects.toThrow(/IMMUTABLE/);});
});
