CREATE TABLE provider_runtime_mappings(mapping_id TEXT PRIMARY KEY,version INTEGER NOT NULL CHECK(version=1),provider TEXT NOT NULL CHECK(provider IN('openai','anthropic','openrouter','oss')),selected_model TEXT NOT NULL,provider_account_id TEXT NOT NULL REFERENCES provider_account_identities(provider_account_id),provider_deployment_id TEXT NOT NULL REFERENCES provider_deployment_identities(provider_deployment_id),adapter_identity TEXT NOT NULL,credential_reference TEXT NOT NULL,environment_class TEXT NOT NULL,effective_at TEXT NOT NULL,expires_at TEXT,correlation_id TEXT NOT NULL,causal_references_json TEXT NOT NULL,binding_policy_version TEXT NOT NULL CHECK(binding_policy_version='PROVIDER_RUNTIME_BINDING_POLICY_V1'));
CREATE TABLE provider_runtime_mapping_transitions(transition_id TEXT PRIMARY KEY,mapping_id TEXT NOT NULL REFERENCES provider_runtime_mappings(mapping_id),status TEXT NOT NULL CHECK(status IN('EXPIRED','REVOKED','SUPERSEDED')),reference TEXT NOT NULL UNIQUE,transitioned_at TEXT NOT NULL,correlation_id TEXT NOT NULL);
CREATE TABLE provider_runtime_binding_audit_events(event_id TEXT PRIMARY KEY,event_kind TEXT NOT NULL,mapping_id TEXT,binding_id TEXT,outcome TEXT NOT NULL,failure_code TEXT,correlation_id TEXT NOT NULL,recorded_at TEXT NOT NULL);
CREATE TRIGGER provider_runtime_mapping_immutable BEFORE UPDATE ON provider_runtime_mappings BEGIN SELECT RAISE(ABORT,'PROVIDER_RUNTIME_MAPPING_IMMUTABLE');END;
CREATE TRIGGER provider_runtime_mapping_no_delete BEFORE DELETE ON provider_runtime_mappings BEGIN SELECT RAISE(ABORT,'PROVIDER_RUNTIME_MAPPING_IMMUTABLE');END;
CREATE TRIGGER provider_runtime_mapping_transition_immutable BEFORE UPDATE ON provider_runtime_mapping_transitions BEGIN SELECT RAISE(ABORT,'PROVIDER_RUNTIME_MAPPING_TRANSITION_IMMUTABLE');END;
CREATE TRIGGER provider_runtime_mapping_transition_no_delete BEFORE DELETE ON provider_runtime_mapping_transitions BEGIN SELECT RAISE(ABORT,'PROVIDER_RUNTIME_MAPPING_TRANSITION_IMMUTABLE');END;
CREATE TRIGGER provider_runtime_binding_audit_immutable BEFORE UPDATE ON provider_runtime_binding_audit_events BEGIN SELECT RAISE(ABORT,'PROVIDER_RUNTIME_BINDING_AUDIT_IMMUTABLE');END;
CREATE TRIGGER provider_runtime_binding_audit_no_delete BEFORE DELETE ON provider_runtime_binding_audit_events BEGIN SELECT RAISE(ABORT,'PROVIDER_RUNTIME_BINDING_AUDIT_IMMUTABLE');END;
