import { deepCopyAndFreeze } from '../knowledge-exposure/knowledge.projection.guard.v1';
import { createSecurityEvidenceCompositionV1 } from './security.evidence.composition.v1';
import type { SecurityEvidenceCompositionV1 } from './security.evidence.composition.contracts.v1';
import { SecurityEvidenceCompositionPersistenceFailureV1,type SecurityEvidenceCompositionRepositoryV1 } from './security.evidence.composition.persistence.contracts.v1';
const list=<T=any>(x:D1Result<T>)=>x.results, j=(x:unknown)=>JSON.stringify(x), parse=(x:unknown)=>JSON.parse(String(x));
export class SecurityEvidenceCompositionD1V1 implements SecurityEvidenceCompositionRepositoryV1{
 constructor(private readonly db:D1Database){}
 async persist(c:SecurityEvidenceCompositionV1):Promise<'CREATED'|'IDENTICAL'>{
	if(c.verification_result!=='VERIFIED')throw new SecurityEvidenceCompositionPersistenceFailureV1('SECURITY_COMPOSITION_PERSISTENCE_FAILED');
  const old=await this.db.prepare('SELECT composition_digest FROM security_evidence_compositions WHERE composition_id=?').bind(c.composition_id).first<{composition_digest:string}>();
  if(old){if(old.composition_digest!==c.composition_digest)throw new SecurityEvidenceCompositionPersistenceFailureV1('SECURITY_COMPOSITION_CONFLICT');const rebuilt=await this.read(c.composition_id);if(!rebuilt||rebuilt.composition_digest!==c.composition_digest||JSON.stringify(rebuilt)!==JSON.stringify(c))throw new SecurityEvidenceCompositionPersistenceFailureV1('SECURITY_COMPOSITION_CONFLICT');return'IDENTICAL';}
  const o=c.organizational_authority;
  const statements=[this.db.prepare(`INSERT INTO security_evidence_compositions VALUES (${Array(24).fill('?').join(',')})`).bind(c.composition_id,1,c.composition_digest,c.request_id,c.principal_id??null,c.session_id??null,c.tenant_id,c.company_id,c.oks_request_id,c.oks_decision_id,c.projection_id,c.projection_digest,c.oks_consumption_id,o.applicability_evidence_id,o.requirement,o.authority_evidence_id??null,o.authority_proof_id??null,o.authority_proof_digest??null,c.p9.applicability_evidence_id,c.final_outcome,c.verification_result,c.historical_validity_basis,c.composed_at,j(c.causal_lineage)),
   ...c.pt_admissions.map(x=>this.db.prepare('INSERT INTO security_composition_admissions VALUES (?,?,?)').bind(c.composition_id,x.admission_id,x.admission_digest)),
   ...c.runtime_bindings.map(x=>this.db.prepare('INSERT INTO security_composition_bindings VALUES (?,?,?)').bind(c.composition_id,x.runtime_binding_id,x.runtime_binding_digest)),
   ...c.credential_access_evidence_ids.map(x=>this.db.prepare('INSERT INTO security_composition_credentials VALUES (?,?)').bind(c.composition_id,x)),
   ...c.attempts.map(x=>this.db.prepare('INSERT INTO security_composition_attempts VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(c.composition_id,x.attempt_id,x.sequence,x.outcome,x.predecessor_attempt_id??null,x.admission_id??null,x.admission_digest??null,x.runtime_binding_id??null,x.runtime_binding_digest??null,x.credential_access_evidence_id??null,x.transport_evidence_id??null)),
   ...c.transport_evidence_ids.map(x=>this.db.prepare('INSERT INTO security_composition_transports VALUES (?,?)').bind(c.composition_id,x)),
   ...c.fallback_edges.map(x=>this.db.prepare('INSERT INTO security_composition_fallbacks VALUES (?,?,?,?,?,?)').bind(c.composition_id,x.fallback_edge_id,x.request_id,x.predecessor_attempt_id,x.successor_attempt_id,x.reason)),
   ...c.edges.map(x=>this.db.prepare('INSERT INTO security_composition_edges VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(c.composition_id,x.edge_id,x.source.domain,x.source.evidence_id,x.source.digest??null,x.target.domain,x.target.evidence_id,x.target.digest??null,x.integrity,x.causal_relation,x.referenced_at??null)),
   this.db.prepare('INSERT INTO security_composition_audit VALUES (?,?,?,?,?,?)').bind(`security-composition-audit:${c.composition_id}`,'COMPOSITION_PERSISTED',c.composition_id,c.composition_digest,'PERSISTED',c.composed_at)];
  try{await this.db.batch(statements);return'CREATED';}catch{const concurrent=await this.read(c.composition_id);if(concurrent&&JSON.stringify(concurrent)===JSON.stringify(c))return'IDENTICAL';throw new SecurityEvidenceCompositionPersistenceFailureV1('SECURITY_COMPOSITION_PERSISTENCE_FAILED');}
 }
 async read(id:string):Promise<SecurityEvidenceCompositionV1|null>{
  const r=await this.db.prepare('SELECT * FROM security_evidence_compositions WHERE composition_id=?').bind(id).first<any>();if(!r)return null;
  try{const [aa,bb,cc,tt,ff,ee]=await Promise.all([
   this.db.prepare('SELECT * FROM security_composition_admissions WHERE composition_id=? ORDER BY admission_id').bind(id).all<any>(),this.db.prepare('SELECT * FROM security_composition_bindings WHERE composition_id=? ORDER BY binding_id').bind(id).all<any>(),this.db.prepare('SELECT * FROM security_composition_credentials WHERE composition_id=? ORDER BY evidence_id').bind(id).all<any>(),this.db.prepare('SELECT * FROM security_composition_attempts WHERE composition_id=? ORDER BY sequence,attempt_id').bind(id).all<any>(),this.db.prepare('SELECT * FROM security_composition_fallbacks WHERE composition_id=? ORDER BY edge_id').bind(id).all<any>(),this.db.prepare('SELECT * FROM security_composition_edges WHERE composition_id=? ORDER BY edge_id').bind(id).all<any>()]),trans=await this.db.prepare('SELECT evidence_id FROM security_composition_transports WHERE composition_id=? ORDER BY evidence_id').bind(id).all<any>();
   const semantic:any={version:1,request_id:r.request_id,...(r.principal_id?{principal_id:r.principal_id}:{}),...(r.session_id?{session_id:r.session_id}:{}),tenant_id:r.tenant_id,company_id:r.company_id,oks_request_id:r.oks_request_id,oks_decision_id:r.oks_decision_id,projection_id:r.projection_id,projection_digest:r.projection_digest,oks_consumption_id:r.oks_consumption_id,organizational_authority:{applicability_evidence_id:r.authority_applicability_id,requirement:r.authority_requirement,...(r.authority_evidence_id?{authority_evidence_id:r.authority_evidence_id,authority_proof_id:r.authority_proof_id,authority_proof_digest:r.authority_proof_digest}:{})},p9:{applicability_evidence_id:r.p9_applicability_id,status:'NOT_APPLICABLE'},pt_admissions:list(aa).map(x=>({admission_id:x.admission_id,admission_digest:x.admission_digest})),runtime_bindings:list(bb).map(x=>({runtime_binding_id:x.binding_id,runtime_binding_digest:x.binding_digest})),credential_access_evidence_ids:list(cc).map(x=>x.evidence_id),attempts:list(tt).map(x=>({attempt_id:x.attempt_id,sequence:x.sequence,outcome:x.outcome,...(x.predecessor_attempt_id?{predecessor_attempt_id:x.predecessor_attempt_id}:{}),...(x.admission_id?{admission_id:x.admission_id,admission_digest:x.admission_digest}:{}),...(x.binding_id?{runtime_binding_id:x.binding_id,runtime_binding_digest:x.binding_digest}:{}),...(x.credential_evidence_id?{credential_access_evidence_id:x.credential_evidence_id}:{}),...(x.transport_evidence_id?{transport_evidence_id:x.transport_evidence_id}:{})})),transport_evidence_ids:list(trans).map(x=>x.evidence_id),fallback_edges:list(ff).map(x=>({fallback_edge_id:x.edge_id,request_id:x.request_id,predecessor_attempt_id:x.predecessor_attempt_id,successor_attempt_id:x.successor_attempt_id,reason:x.reason})),edges:list(ee).map(x=>({version:1,edge_id:x.edge_id,source:{domain:x.source_domain,evidence_id:x.source_id,...(x.source_digest?{digest:x.source_digest}:{})},target:{domain:x.target_domain,evidence_id:x.target_id,...(x.target_digest?{digest:x.target_digest}:{})},integrity:x.integrity,causal_relation:x.causal_relation,...(x.referenced_at?{referenced_at:x.referenced_at}:{})})),final_outcome:r.final_outcome,verification_result:r.verification_result,historical_validity_basis:r.historical_validity_basis,composed_at:r.composed_at,causal_lineage:parse(r.causal_lineage_json)};
   const c=createSecurityEvidenceCompositionV1(semantic);if(c.composition_id!==r.composition_id||c.composition_digest!==r.composition_digest)throw 0;return deepCopyAndFreeze(c);
  }catch{throw new SecurityEvidenceCompositionPersistenceFailureV1('SECURITY_COMPOSITION_RECONSTRUCTION_FAILED');}
 }
}
