import { createHash,randomUUID } from 'node:crypto';
import { deepCopyAndFreeze } from '../knowledge-exposure/knowledge.projection.guard.v1';
import { ProviderBoundaryFailureV1,type ProviderCredentialResolverV1,type CredentialResolutionPermitV1,type ProviderRuntimeBindingReferenceV1 } from '../provider-trust';
import type { CredentialAccessEvidenceV1,SecurityEvidenceContextV1,SecurityRuntimeEvidenceRepositoryV1 } from './security.runtime.evidence.contracts.v1';
const hash=(x:unknown)=>createHash('sha256').update(JSON.stringify(x),'utf8').digest('hex');
const permitDigest=(p:CredentialResolutionPermitV1|undefined)=>hash(p?{version:p.version,binding_id:p.binding_id,provider_identity:p.provider_identity,provider_account_id:p.provider_account_id,provider_deployment_id:p.provider_deployment_id,adapter_identity:p.adapter_identity,credential_reference:p.credential_reference,consumer:p.consumer,authorization_reference:p.authorization_reference,admission_id:p.admission_id,admission_digest:p.admission_digest,invocation_consumer:p.invocation_consumer,expires_at:p.expires_at}:null);
export class EvidencedProviderCredentialResolverV1 implements ProviderCredentialResolverV1 {
	readonly latest=new Map<string,CredentialAccessEvidenceV1>();
	constructor(private readonly inner:ProviderCredentialResolverV1,private readonly repository:SecurityRuntimeEvidenceRepositoryV1,private readonly contexts:ReadonlyMap<string,SecurityEvidenceContextV1>,private readonly now:()=>string=()=>new Date().toISOString()){}
	async resolve(binding:ProviderRuntimeBindingReferenceV1,permit:CredentialResolutionPermitV1){
		const at=this.now(),context=this.contexts.get(binding?.binding_id),base=()=>({version:1 as const,evidence_id:`credential-access-evidence:${randomUUID()}`,admission_id:context?.admission_id??permit?.admission_id??'UNKNOWN',admission_digest:context?.admission_digest??permit?.admission_digest??'UNKNOWN',permit_digest:permitDigest(permit),runtime_binding_id:context?.runtime_binding_id??binding?.binding_id??'UNKNOWN',runtime_binding_digest:context?.runtime_binding_digest??'UNKNOWN',provider:binding?.provider_identity??'UNKNOWN',provider_account_id:binding?.provider_account_id??'UNKNOWN',provider_deployment_id:binding?.provider_deployment_id??'UNKNOWN',adapter_identity:binding?.adapter_identity??'UNKNOWN',credential_reference:binding?.credential_reference??'UNKNOWN',attempted_at:at,correlation_id:context?.correlation_id??'UNKNOWN',causal_references:context?.causal_references??[]});
		const persist=async(outcome:CredentialAccessEvidenceV1['outcome'],failure_code?:string)=>{const e=deepCopyAndFreeze({...base(),outcome,completed_at:this.now(),...(failure_code?{failure_code}:{})}) as CredentialAccessEvidenceV1;await this.repository.persistCredential(e);this.latest.set(binding?.binding_id??'UNKNOWN',e);};
		if(!context||!permit||context.admission_id!==permit.admission_id||context.admission_digest!==permit.admission_digest||context.runtime_binding_id!==binding?.binding_id){await persist('RESOLUTION_DENIED','SECURITY_EVIDENCE_CREDENTIAL_ACCESS_DENIED');throw new ProviderBoundaryFailureV1('GOVERNANCE_DENIAL','PROVIDER_CREDENTIAL_RESOLUTION_NOT_AUTHORIZED');}
		try{const secret=await this.inner.resolve(binding,permit);await persist(binding.credential_reference==='NOT_APPLICABLE'?'NOT_APPLICABLE':'RESOLUTION_SUCCEEDED');return secret;}catch(error){await persist(error instanceof ProviderBoundaryFailureV1&&error.category==='GOVERNANCE_DENIAL'?'RESOLUTION_DENIED':'RESOLUTION_FAILED',error instanceof ProviderBoundaryFailureV1?error.code:'SECURITY_EVIDENCE_CREDENTIAL_RESOLUTION_FAILED');throw error;}
	}
}
export const securityEvidenceDigestV1=hash;
