import { deepCopyAndFreeze } from '../knowledge-exposure/knowledge.projection.guard.v1';
import { canonicalProviderRuntimeBindingDigestV1 } from '../provider-trust/provider.precredential.boundary.v1';
import { ProviderRuntimeBindingD1V1 } from '../provider-trust/provider.runtime.repository.d1.v1';
import { SecurityEvidenceCompositionD1V1 } from './security.evidence.composition.d1.v1';
import type { SecurityEvidenceCompositionVerificationResultV1 } from './security.evidence.composition.persistence.contracts.v1';
type Failure=SecurityEvidenceCompositionVerificationResultV1['failures'][number];
const t=(x:unknown)=>Date.parse(String(x));
export async function verifyPersistedSecurityEvidenceCompositionV1(db:D1Database,compositionId:string,verifiedAt:string):Promise<SecurityEvidenceCompositionVerificationResultV1>{
 const denied=new Set<Failure>(),missing=new Set<string>(),verified=new Set<string>();
 const no=(f:Failure)=>denied.add(f), miss=(x:string)=>missing.add(x), one=async(sql:string,...args:unknown[])=>db.prepare(sql).bind(...args).first<any>();
 const root=await one('SELECT composition_digest FROM security_evidence_compositions WHERE composition_id=?',compositionId);if(!root)return out('INCOMPLETE',['SECURITY_COMPOSITION_NOT_FOUND']);
 let c;try{c=await new SecurityEvidenceCompositionD1V1(db).read(compositionId);}catch{return out('DENIED',['SECURITY_COMPOSITION_RECONSTRUCTION_FAILED']);}if(!c)return out('INCOMPLETE',['SECURITY_COMPOSITION_NOT_FOUND']);verified.add(c.composition_id);
 const decision=await one('SELECT * FROM knowledge_exposure_decisions WHERE decision_id=?',c.oks_decision_id);if(!decision)miss(c.oks_decision_id);else{verified.add(c.oks_decision_id);if(decision.request_id!==c.oks_request_id||decision.tenant_id!==c.tenant_id||decision.company_id!==c.company_id||decision.principal_id!==c.principal_id||decision.session_id!==c.session_id||decision.manifest_id!==c.projection_id||decision.projection_digest!==c.projection_digest)no('SECURITY_COMPOSITION_SOURCE_IDENTITY_MISMATCH');}
 const oksBinding=await one('SELECT * FROM knowledge_exposure_projection_bindings WHERE decision_id=?',c.oks_decision_id),consumption=await one('SELECT * FROM knowledge_exposure_consumptions WHERE consumption_id=?',c.oks_consumption_id);if(!oksBinding||!consumption)miss(!oksBinding?c.projection_id:c.oks_consumption_id);else{verified.add(oksBinding.binding_id);verified.add(consumption.consumption_id);if(oksBinding.manifest_id!==c.projection_id||oksBinding.projection_digest!==c.projection_digest||consumption.binding_id!==oksBinding.binding_id||consumption.decision_id!==c.oks_decision_id)no('SECURITY_COMPOSITION_SOURCE_IDENTITY_MISMATCH');}
 const oa=await one('SELECT * FROM security_evidence_applicability WHERE applicability_id=?',c.organizational_authority.applicability_evidence_id),p9=await one('SELECT * FROM security_evidence_applicability WHERE applicability_id=?',c.p9.applicability_evidence_id);if(!oa||!p9)miss(!oa?c.organizational_authority.applicability_evidence_id:c.p9.applicability_evidence_id);else{verified.add(oa.applicability_id);verified.add(p9.applicability_id);if(oa.decision_id!==c.oks_decision_id||oa.projection_digest!==c.projection_digest||oa.status!==(c.organizational_authority.requirement==='REQUIRED'?'APPLICABLE':'NOT_APPLICABLE')||p9.domain!=='P9'||p9.status!=='NOT_APPLICABLE'||p9.decision_id!==c.oks_decision_id)no('SECURITY_COMPOSITION_AUTHORITY_APPLICABILITY_CONFLICT');if(decision&&(t(decision.issued_at)>t(oa.recorded_at)||t(decision.issued_at)>t(p9.recorded_at)))no('SECURITY_COMPOSITION_TEMPORAL_ORDER_INVALID');}
 if(c.organizational_authority.requirement==='REQUIRED'){
  const a=await one('SELECT e.*,b.request_id,b.decision_id,b.projection_digest binding_projection,b.recorded_at FROM knowledge_exposure_authority_evidence e JOIN knowledge_exposure_authority_bindings b ON b.binding_id=e.binding_id WHERE e.evidence_id=?',c.organizational_authority.authority_evidence_id),proof=await one('SELECT * FROM oag_can_authority_proofs WHERE authority_proof_id=?',c.organizational_authority.authority_proof_id);if(!a||!proof)miss(!a?String(c.organizational_authority.authority_evidence_id):String(c.organizational_authority.authority_proof_id));else{verified.add(a.evidence_id);verified.add(proof.authority_proof_id);if(a.authority_proof_digest!==c.organizational_authority.authority_proof_digest||proof.proof_digest!==c.organizational_authority.authority_proof_digest||a.decision_id!==c.oks_decision_id||a.binding_projection!==c.projection_digest||proof.principal_id!==c.principal_id||proof.tenant_id!==c.tenant_id||proof.company_id!==c.company_id)no('SECURITY_COMPOSITION_AUTHORITY_MISMATCH');if(decision){const sources=[['ROOT',proof.root_reference,'oag_can_roots','root_id'],['RESPONSIBILITY',JSON.parse(proof.responsibility_references_json)[0],'oag_can_responsibilities','responsibility_id'],['CONFIRMATION',proof.confirmation_chain_id,'oag_can_confirmation_chains','chain_id']] as const;for(const [kind,id,table,key]of sources){const source=await one(`SELECT effective_from,effective_until FROM ${table} WHERE ${key}=?`,id),transition=await one('SELECT transitioned_at FROM oag_can_transitions WHERE subject_kind=? AND subject_id=?',kind,id);if(!source)miss(String(id));else if(t(source.effective_from)>t(decision.issued_at)||(source.effective_until&&t(source.effective_until)<=t(decision.issued_at))||(transition&&t(transition.transitioned_at)<=t(decision.issued_at)))no('SECURITY_COMPOSITION_HISTORICAL_STATE_UNVERIFIABLE');}if(t(decision.issued_at)>t(a.recorded_at))no('SECURITY_COMPOSITION_TEMPORAL_ORDER_INVALID');}}
 }
 const bindingRepo=new ProviderRuntimeBindingD1V1(db);
 const authoritativeBindings=new Map<string,NonNullable<Awaited<ReturnType<ProviderRuntimeBindingD1V1['readBinding']>>>>();
 for(const ref of c.runtime_bindings){const b=await bindingRepo.readBinding(ref.runtime_binding_id);if(!b)miss(ref.runtime_binding_id);else{authoritativeBindings.set(ref.runtime_binding_id,b);verified.add(ref.runtime_binding_id);const digest=await canonicalProviderRuntimeBindingDigestV1(b.binding);if(digest!==b.binding_digest||digest!==ref.runtime_binding_digest)no('SECURITY_COMPOSITION_RUNTIME_BINDING_DIGEST_MISMATCH');}}
 for(const ref of c.pt_admissions){const a=await one('SELECT * FROM runtime_provider_trust_admissions WHERE admission_id=?',ref.admission_id);if(!a)miss(ref.admission_id);else{verified.add(ref.admission_id);if(a.admission_digest!==ref.admission_digest||a.oks_decision_id!==c.oks_decision_id||a.oks_consumption_id!==c.oks_consumption_id||a.projection_digest!==c.projection_digest||!c.runtime_bindings.some(b=>b.runtime_binding_id===a.runtime_binding_id&&b.runtime_binding_digest===a.runtime_binding_digest))no('SECURITY_COMPOSITION_PT_ADMISSION_MISMATCH');if(oa&&t(oa.recorded_at)>t(a.issued_at))no('SECURITY_COMPOSITION_TEMPORAL_ORDER_INVALID');}}
 for(const ref of c.pt_admissions){const a=await one('SELECT * FROM runtime_provider_trust_admissions WHERE admission_id=?',ref.admission_id),b=a?authoritativeBindings.get(a.runtime_binding_id):undefined;if(a&&b&&(a.provider!==b.binding.provider||a.provider_account_id!==b.binding.provider_account_id||a.provider_deployment_id!==b.binding.provider_deployment_id||a.adapter_identity!==b.binding.adapter_identity||a.selected_model!==b.binding.selected_model||a.credential_reference!==b.binding.credential_reference))no('SECURITY_COMPOSITION_RUNTIME_BINDING_MISMATCH');}
 for(const ref of c.attempts){const a=await one('SELECT * FROM security_provider_runtime_attempts WHERE attempt_id=?',ref.attempt_id);if(!a)miss(ref.attempt_id);else{verified.add(ref.attempt_id);if(a.request_id!==c.request_id||a.sequence!==ref.sequence||a.outcome!==ref.outcome||a.admission_id!==ref.admission_id||a.admission_digest!==ref.admission_digest||a.runtime_binding_id!==ref.runtime_binding_id||a.runtime_binding_digest!==ref.runtime_binding_digest||a.credential_access_evidence_id!==ref.credential_access_evidence_id||a.transport_evidence_id!==ref.transport_evidence_id)no('SECURITY_COMPOSITION_ATTEMPT_MISMATCH');if(t(a.completed_at)>t(c.composed_at))no('SECURITY_COMPOSITION_TEMPORAL_ORDER_INVALID');}
  const binding=ref.runtime_binding_id?authoritativeBindings.get(ref.runtime_binding_id)?.binding:undefined;
  if(binding&&a&&(a.provider!==binding.provider||a.provider_account_id!==binding.provider_account_id||a.provider_deployment_id!==binding.provider_deployment_id||a.adapter_identity!==binding.adapter_identity||a.model!==binding.selected_model))no('SECURITY_COMPOSITION_RUNTIME_BINDING_MISMATCH');
  if(ref.credential_access_evidence_id){const x=await one('SELECT * FROM security_credential_access_evidence WHERE evidence_id=?',ref.credential_access_evidence_id);if(!x)miss(ref.credential_access_evidence_id);else{verified.add(x.evidence_id);if(x.admission_id!==ref.admission_id||x.admission_digest!==ref.admission_digest||x.runtime_binding_id!==ref.runtime_binding_id||x.runtime_binding_digest!==ref.runtime_binding_digest||binding&&(x.provider!==binding.provider||x.provider_account_id!==binding.provider_account_id||x.provider_deployment_id!==binding.provider_deployment_id||x.adapter_identity!==binding.adapter_identity||x.credential_reference!==binding.credential_reference))no('SECURITY_COMPOSITION_CREDENTIAL_EVIDENCE_MISMATCH');const admission=await one('SELECT issued_at FROM runtime_provider_trust_admissions WHERE admission_id=?',ref.admission_id);if(admission&&t(admission.issued_at)>t(x.attempted_at))no('SECURITY_COMPOSITION_TEMPORAL_ORDER_INVALID');}}
  if(ref.transport_evidence_id){const x=await one('SELECT * FROM cognitive_transport_evidence WHERE evidence_id=?',ref.transport_evidence_id);if(!x)miss(ref.transport_evidence_id);else{verified.add(x.evidence_id);if(x.decision_id!==c.oks_decision_id||x.projection_digest!==c.projection_digest||x.consumption_id!==c.oks_consumption_id||x.status!==(ref.outcome==='TRANSPORT_FAILED'?'FAILED':'SUCCEEDED'))no('SECURITY_COMPOSITION_TRANSPORT_MISMATCH');const cr=ref.credential_access_evidence_id?await one('SELECT completed_at FROM security_credential_access_evidence WHERE evidence_id=?',ref.credential_access_evidence_id):null,at=await one('SELECT completed_at FROM security_provider_runtime_attempts WHERE attempt_id=?',ref.attempt_id);if(cr&&t(cr.completed_at)>t(x.dispatched_at)||at&&t(x.dispatched_at)>t(at.completed_at))no('SECURITY_COMPOSITION_TEMPORAL_ORDER_INVALID');}}
 }
 const attemptAdmissions=new Set(c.attempts.flatMap(x=>x.admission_id?[x.admission_id]:[])),attemptBindings=new Set(c.attempts.flatMap(x=>x.runtime_binding_id?[x.runtime_binding_id]:[])),attemptCredentials=new Set(c.attempts.flatMap(x=>x.credential_access_evidence_id?[x.credential_access_evidence_id]:[])),attemptTransports=new Set(c.attempts.flatMap(x=>x.transport_evidence_id?[x.transport_evidence_id]:[]));
 if(c.pt_admissions.some(x=>!attemptAdmissions.has(x.admission_id))||c.runtime_bindings.some(x=>!attemptBindings.has(x.runtime_binding_id))||c.credential_access_evidence_ids.some(x=>!attemptCredentials.has(x))||c.transport_evidence_ids.some(x=>!attemptTransports.has(x)))no('SECURITY_COMPOSITION_SOURCE_IDENTITY_MISMATCH');
 for(const f of c.fallback_edges){const x=await one('SELECT * FROM security_provider_runtime_fallback_lineage WHERE lineage_id=?',f.fallback_edge_id);if(!x)miss(f.fallback_edge_id);else{verified.add(x.lineage_id);if(x.predecessor_attempt_id!==f.predecessor_attempt_id||x.successor_attempt_id!==f.successor_attempt_id||x.reason!==f.reason)no('SECURITY_COMPOSITION_FALLBACK_LINEAGE_INVALID');const a=await one('SELECT completed_at FROM security_provider_runtime_attempts WHERE attempt_id=?',f.predecessor_attempt_id),b=await one('SELECT started_at FROM security_provider_runtime_attempts WHERE attempt_id=?',f.successor_attempt_id);if(a&&b&&t(a.completed_at)>t(b.started_at))no('SECURITY_COMPOSITION_TEMPORAL_ORDER_INVALID');}}
 return denied.size?out('DENIED',[...denied]):missing.size?out('INCOMPLETE',['SECURITY_COMPOSITION_SOURCE_EVIDENCE_NOT_FOUND']):out('VERIFIED',[]);
 function out(result:'VERIFIED'|'DENIED'|'INCOMPLETE',failures:Failure[]):SecurityEvidenceCompositionVerificationResultV1{return deepCopyAndFreeze({version:1,composition_id:compositionId,result,failures:[...new Set(failures)].sort(),verified_sources:[...verified].sort(),unresolved_sources:[...missing].sort(),verified_at:verifiedAt});}
}
