import { describe,expect,it } from 'vitest';
import { createGovernanceIndicatorAggregateV1,createGovernanceIndicatorV1 } from '../../indicators';
import { createOrganizationalGovernanceCommunicationV1 } from '..';
const at='2026-08-12T00:00:00.000Z',tenant='tenant:1',company='company:1';
const families:any={AUTHORITY_INTEGRITY:'OAG',PROVIDER_TRUST:'PT',SECURITY_EVIDENCE_COMPOSITION:'SEC_WU3',KNOWLEDGE_EXPOSURE_GOVERNANCE:'OKS',RUNTIME_SECURITY_EVIDENCE:'SEC_WU1'};
const results:any={HEALTHY:'VERIFIED',DENIED:'DENIED',INCOMPLETE:'INCOMPLETE',NOT_APPLICABLE:'NOT_APPLICABLE'};
const indicator=(type='SECURITY_EVIDENCE_COMPOSITION',status='HEALTHY',overrides:any={})=>{const id=`source:${type}:${status}`,source={version:1 as const,source_family:families[type],source_artifact_id:id,source_artifact_digest:'a'.repeat(64),source_result:results[status],tenant_id:tenant,company_id:company,observed_at:at};return createGovernanceIndicatorV1({version:1,indicator_type:type,subject_type:'GOVERNED_OPERATION',subject_id:'operation:1',tenant_id:tenant,company_id:company,source_evidence:[source],expected_source_digests:{[id]:source.source_artifact_digest},evaluated_at:at,historical_mode:'VALID_AT_OPERATION_TIME',causal_lineage:[id],...overrides});};
const aggregate=(status:'HEALTHY'|'DENIED'|'INCOMPLETE')=>{const source=indicator('SECURITY_EVIDENCE_COMPOSITION',status);return createGovernanceIndicatorAggregateV1({version:1,aggregate_type:'GOVERNANCE_EVIDENCE_COMPLETENESS',subject_type:'GOVERNED_OPERATION',subject_id:'operation:1',tenant_id:tenant,company_id:company,required_indicator_types:[source.indicator_type],contributors:[source],evaluated_at:at,historical_mode:'VALID_AT_OPERATION_TIME',causal_lineage:[source.indicator_id]});};
const communication=(source:any,overrides:any={})=>createOrganizationalGovernanceCommunicationV1({version:1,source,expected_source_id:source.indicator_id??source.aggregate_id,expected_source_digest:source.indicator_digest??source.aggregate_digest,subject_type:'GOVERNED_OPERATION',subject_id:'operation:1',tenant_id:tenant,company_id:company,historical_mode:'VALID_AT_OPERATION_TIME',generated_at:at,causal_lineage:[source.indicator_id??source.aggregate_id],...overrides});
const generated=(source:any,overrides:any={})=>{const x=communication(source,overrides);expect(x.decision).toBe('COMMUNICATION_GENERATED');return (x as any).communication;};
describe('Organizational Governance Communications WU1',()=>{
 it('requires canonical identity and digest and rejects source tampering',()=>{const x=indicator();expect(()=>communication(x,{expected_source_id:'other'})).toThrowError(expect.objectContaining({code:'GOVERNANCE_COMMUNICATION_SOURCE_IDENTITY_MISMATCH'}));expect(()=>communication(x,{expected_source_digest:'other'})).toThrowError(expect.objectContaining({code:'GOVERNANCE_COMMUNICATION_SOURCE_DIGEST_MISMATCH'}));expect(()=>communication({...x,status:'DENIED'})).toThrowError(expect.objectContaining({code:'GOVERNANCE_COMMUNICATION_SOURCE_INVALID'}));});
 it('rejects tenant, company, subject, and historical-mode mismatch',()=>{const x=indicator();for(const [field,value,code]of [['tenant_id','other','GOVERNANCE_COMMUNICATION_TENANT_MISMATCH'],['company_id','other','GOVERNANCE_COMMUNICATION_COMPANY_MISMATCH'],['subject_id','other','GOVERNANCE_COMMUNICATION_SUBJECT_MISMATCH'],['historical_mode','CURRENT','GOVERNANCE_COMMUNICATION_HISTORICAL_MODE_MISMATCH']]as const)expect(()=>communication(x,{[field]:value})).toThrowError(expect.objectContaining({code}));});
 it.each([['AUTHORITY_INTEGRITY','HEALTHY','INFORMATIONAL',false],['AUTHORITY_INTEGRITY','DENIED','BLOCKING',true],['PROVIDER_TRUST','HEALTHY','INFORMATIONAL',false],['PROVIDER_TRUST','DENIED','BLOCKING',true],['SECURITY_EVIDENCE_COMPOSITION','HEALTHY','INFORMATIONAL',false],['SECURITY_EVIDENCE_COMPOSITION','INCOMPLETE','ATTENTION_REQUIRED',false],['KNOWLEDGE_EXPOSURE_GOVERNANCE','DENIED','BLOCKING',true]]as const)('maps %s %s without changing source state',(type,status,classification,blocking)=>expect(generated(indicator(type,status))).toMatchObject({source_status:status,classification,blocking}));
 it.each([['HEALTHY','INFORMATIONAL'],['INCOMPLETE','ATTENTION_REQUIRED'],['DENIED','BLOCKING']]as const)('communicates completeness %s and retains contributors',(status,classification)=>{const x=generated(aggregate(status));expect(x).toMatchObject({source_status:status,classification});expect(x.source.contributor_references).toHaveLength(1);});
 it('returns deterministic provenance-preserving silence for NOT_APPLICABLE',()=>{const source=indicator('AUTHORITY_INTEGRITY','NOT_APPLICABLE'),a=communication(source),b=communication(source);expect(a).toEqual(b);expect(a).toMatchObject({decision:'NO_COMMUNICATION_REQUIRED',source:{status:'NOT_APPLICABLE',source_id:source.indicator_id},reason_code:'SOURCE_NOT_APPLICABLE'});});
 it('is deterministic and changes with canonical source or context',()=>{const a=generated(indicator()),b=generated(indicator()),changed=generated(indicator('SECURITY_EVIDENCE_COMPOSITION','DENIED')),contextSource=indicator(undefined,undefined,{subject_id:'operation:2'});expect(a).toEqual(b);expect(changed.communication_digest).not.toBe(a.communication_digest);expect(generated(contextSource,{subject_id:'operation:2'}).communication_digest).not.toBe(a.communication_digest);});
 it('contains no copy, content, scoring, UI, delivery, audience, or execution capability',()=>{const x=generated(indicator());expect(Object.isFrozen(x)&&Object.isFrozen(x.source)).toBe(true);expect(JSON.stringify(x)).not.toMatch(/prompt|source document|provider response|credential|business payload|projection body|score|confidence|green|amber|red|icon|badge|message|title|recipient|audience|acknowledg|delivery|execute|retry|approve|grant|permit/i);});
});
