import {createHash} from "node:crypto";import {deepCopyAndFreeze} from "../../knowledge-exposure/knowledge.projection.guard.v1";import {D1PlatformAlertRepositoryV1} from "../platform.alert.d1.v1";
import {PLATFORM_COMPANY_ID,PLATFORM_TENANT_ID,PlatformRecipientError,type PlatformAlertChannelV1,type PlatformAlertRecipientEligibilityV1,type PlatformAuthorityProofV1,type PlatformRecipientCandidateV1,type PlatformRecipientEndpointV1,type PlatformRecipientEntitlementV1,type PlatformRecipientRepositoryV1} from "./platform.recipient.contracts.v1";
const hash=(s:string)=>createHash("sha256").update(s,"utf8").digest("hex"),list=(x:unknown)=>{try{const v=JSON.parse(String(x));if(Array.isArray(v)&&v.every(y=>typeof y==="string"))return Object.freeze(v) as readonly string[];}catch{}throw new PlatformRecipientError("PLATFORM_RECIPIENT_RESOLUTION_FAILED")};
export class D1PlatformRecipientRepositoryV1 implements PlatformRecipientRepositoryV1{constructor(private readonly db:D1Database){}
async createAuthorityProof(p:PlatformAuthorityProofV1){try{await this.db.prepare("INSERT INTO platform_operational_authority_proofs VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(p.authority_proof_id,p.platform_tenant_id,p.platform_company_id,p.actor_id,p.principal_id,p.membership_id,p.authority_domain,JSON.stringify(p.effective_scope),p.confirmation_chain_reference,JSON.stringify(p.delegation_references),p.graph_version,p.eligibility_state,p.drift_state,p.issued_at,p.expires_at,p.policy_version,JSON.stringify(p.causal_references)).run();}catch{throw new PlatformRecipientError("PLATFORM_AUTHORITY_INVALID")}}
async createEntitlement(t:PlatformRecipientEntitlementV1){try{await this.db.prepare("INSERT INTO platform_alert_recipient_entitlements VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(t.entitlement_id,1,t.platform_tenant_id,t.platform_company_id,t.actor_id,t.principal_id,t.membership_id,t.authority_domain,t.authority_proof_id,t.communication_family,t.purpose,t.urgency_ceiling,JSON.stringify(t.allowed_channels),t.preferred_channel,t.recipient_priority,t.supervisor_fallback_authorized?1:0,t.lifecycle_state,t.effective_at,t.expires_at,t.correlation_id,JSON.stringify(t.causal_references)).run();await this.audit({event_kind:"ENTITLEMENT_CREATED",entitlement_id:t.entitlement_id,actor_id:t.actor_id,authority_proof_id:t.authority_proof_id,authority_domain:t.authority_domain,family:t.communication_family,purpose:t.purpose,urgency:t.urgency_ceiling,outcome:"CREATED",reason_code:"PLATFORM_ENTITLEMENT_CREATED",correlation_id:t.correlation_id,causal_references:t.causal_references,recorded_at:t.effective_at});}catch(e){if(e instanceof PlatformRecipientError)throw e;throw new PlatformRecipientError("PLATFORM_RECIPIENT_RESOLUTION_FAILED")}}
async bindEndpoint(e:PlatformRecipientEndpointV1){const valid=e.channel==="EMAIL"?/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e.normalized_destination)&&e.normalized_destination===e.normalized_destination.toLowerCase():e.channel==="SMS"?/^\+[1-9]\d{7,14}$/.test(e.normalized_destination):/^whatsapp:\+[1-9]\d{7,14}$/.test(e.normalized_destination);if(!valid||hash(e.normalized_destination)!==e.destination_digest)throw new PlatformRecipientError("PLATFORM_ENDPOINT_SUBSTITUTED");try{await this.db.prepare("INSERT INTO platform_alert_recipient_endpoints VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").bind(e.endpoint_id,e.entitlement_id,e.actor_id,e.channel,e.normalized_destination,e.destination_digest,e.lifecycle_state,e.verification_state,e.effective_at,e.expires_at,e.verification_reference,JSON.stringify(e.causal_references)).run();await this.audit({event_kind:"ENDPOINT_BOUND",entitlement_id:e.entitlement_id,actor_id:e.actor_id,endpoint_id:e.endpoint_id,destination_digest:e.destination_digest,channel:e.channel,outcome:"BOUND",reason_code:"PLATFORM_ENDPOINT_BOUND",correlation_id:e.verification_reference,causal_references:e.causal_references,recorded_at:e.effective_at});}catch(x){if(x instanceof PlatformRecipientError)throw x;throw new PlatformRecipientError("PLATFORM_RECIPIENT_RESOLUTION_FAILED")}}
async revokeEntitlement(id:string,at:string,ref:string){await this.db.prepare("INSERT INTO platform_alert_entitlement_revocations VALUES (?,?,?)").bind(id,at,ref).run();await this.audit({event_kind:"ENTITLEMENT_REVOKED",entitlement_id:id,outcome:"REVOKED",reason_code:"PLATFORM_RECIPIENT_ENTITLEMENT_REVOKED",correlation_id:ref,causal_references:[ref],recorded_at:at});}
async revokeEndpoint(id:string,at:string,ref:string){await this.db.prepare("INSERT INTO platform_alert_endpoint_revocations VALUES (?,?,?)").bind(id,at,ref).run();}
async loadAlert(id:string){const row=await this.db.prepare("SELECT deduplication_id FROM platform_alert_intents WHERE alert_id=?").bind(id).first<{deduplication_id:string}>();if(!row)return null;const alert=await new D1PlatformAlertRepositoryV1(this.db).findByDeduplicationId(row.deduplication_id);if(!alert)return null;const admitted=!!await this.db.prepare("SELECT 1 ok FROM platform_alert_admission_decisions WHERE alert_id=? AND decision='ADMITTED'").bind(id).first();return Object.freeze({alert,admitted});}
async candidates(alertId:string):Promise<readonly PlatformRecipientCandidateV1[]>{const loaded=await this.loadAlert(alertId);if(!loaded)return Object.freeze([]);const rows=await this.db.prepare(`SELECT t.*,p.*,e.endpoint_id,e.channel,e.normalized_destination,e.destination_digest,e.lifecycle_state endpoint_state,e.verification_state,e.effective_at endpoint_effective_at,e.expires_at endpoint_expires_at,e.verification_reference,e.causal_references_json endpoint_causal,
pr.lifecycle_state actor_state,m.lifecycle_state membership_state,o.effective_until,er.entitlement_id entitlement_revoked,xr.endpoint_id endpoint_revoked
FROM platform_alert_recipient_entitlements t JOIN platform_operational_authority_proofs p ON p.authority_proof_id=t.authority_proof_id
JOIN platform_alert_recipient_endpoints e ON e.entitlement_id=t.entitlement_id AND e.channel=t.preferred_channel
LEFT JOIN oir_principals pr ON pr.principal_id=t.principal_id LEFT JOIN oir_organization_memberships m ON m.membership_id=t.membership_id
LEFT JOIN oir_tenant_company_ownership o ON o.tenant_id=t.platform_tenant_id AND o.company_id=t.platform_company_id
LEFT JOIN platform_alert_entitlement_revocations er ON er.entitlement_id=t.entitlement_id LEFT JOIN platform_alert_endpoint_revocations xr ON xr.endpoint_id=e.endpoint_id
WHERE t.platform_tenant_id=? AND t.platform_company_id=? AND t.authority_domain='PLATFORM_OPERATIONS'`).bind(PLATFORM_TENANT_ID,PLATFORM_COMPANY_ID).all<Record<string,unknown>>();return Object.freeze((rows.results??[]).map(r=>{const entitlement=deepCopyAndFreeze({version:1,entitlement_id:String(r.entitlement_id),platform_tenant_id:PLATFORM_TENANT_ID,platform_company_id:PLATFORM_COMPANY_ID,actor_id:String(r.actor_id),principal_id:String(r.principal_id),membership_id:String(r.membership_id),authority_domain:"PLATFORM_OPERATIONS",authority_proof_id:String(r.authority_proof_id),communication_family:String(r.family??r.communication_family??"PLATFORM_OPERATIONAL_ALERT"),purpose:String(r.purpose),urgency_ceiling:r.urgency_ceiling,allowed_channels:list(r.allowed_channels_json),preferred_channel:r.preferred_channel,recipient_priority:r.recipient_priority,supervisor_fallback_authorized:Number(r.supervisor_fallback_authorized)===1,lifecycle_state:r.entitlement_revoked?"REVOKED":r.lifecycle_state,effective_at:r.effective_at,expires_at:r.expires_at,correlation_id:r.correlation_id,causal_references:list(r.causal_references_json)}) as PlatformRecipientEntitlementV1;const proof=deepCopyAndFreeze({authority_proof_id:String(r.authority_proof_id),platform_tenant_id:PLATFORM_TENANT_ID,platform_company_id:PLATFORM_COMPANY_ID,actor_id:String(r.actor_id),principal_id:String(r.principal_id),membership_id:String(r.membership_id),authority_domain:"PLATFORM_OPERATIONS",effective_scope:list(r.effective_scope_json),confirmation_chain_reference:String(r.confirmation_chain_reference),delegation_references:list(r.delegation_references_json),graph_version:String(r.graph_version),eligibility_state:r.eligibility_state,drift_state:r.drift_state,issued_at:String(r.issued_at),expires_at:String(r.expires_at),policy_version:String(r.policy_version),causal_references:list(r.causal_references_json)}) as PlatformAuthorityProofV1;const endpoint=deepCopyAndFreeze({endpoint_id:String(r.endpoint_id),entitlement_id:String(r.entitlement_id),actor_id:String(r.actor_id),channel:r.channel as PlatformAlertChannelV1,normalized_destination:String(r.normalized_destination),destination_digest:String(r.destination_digest),lifecycle_state:r.endpoint_revoked?"REVOKED":r.endpoint_state,verification_state:r.verification_state,effective_at:String(r.endpoint_effective_at),expires_at:String(r.endpoint_expires_at),verification_reference:String(r.verification_reference),causal_references:list(r.endpoint_causal)}) as PlatformRecipientEndpointV1;return deepCopyAndFreeze({alert:loaded.alert,admitted:loaded.admitted,actor_state:r.actor_state??"MISSING",membership_state:r.membership_state??"MISSING",organization_current:r.effective_until==null,proof,entitlement,endpoint}) as PlatformRecipientCandidateV1;}));}
async persist(e:PlatformAlertRecipientEligibilityV1){try{await this.db.batch([this.db.prepare("INSERT INTO platform_alert_recipient_resolution_decisions VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(e.resolution_id,e.eligibility_id,e.alert_id,e.recipient_entitlement_id,e.authority_proof_id,e.accountable_actor_id,e.endpoint_id,e.endpoint_destination_digest,e.channel,e.communication_family,e.purpose,e.urgency,"RESOLVED",e.issued_at,e.expires_at,e.policy_version,e.correlation_id,JSON.stringify(e.causal_references)),this.db.prepare("INSERT INTO platform_alert_recipient_bindings VALUES (?,?,?,?,?)").bind(e.alert_id,e.resolution_id,e.recipient_entitlement_id,e.endpoint_id,e.issued_at)]);}catch{const old=await this.db.prepare("SELECT eligibility_id FROM platform_alert_recipient_resolution_decisions WHERE alert_id=?").bind(e.alert_id).first<{eligibility_id:string}>();if(old?.eligibility_id===e.eligibility_id)return;throw new PlatformRecipientError("PLATFORM_RECIPIENT_RESOLUTION_FAILED")}}
async audit(e:Readonly<Record<string,unknown>>){try{await this.db.prepare("INSERT INTO platform_alert_recipient_audit_events VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(e.audit_event_id??`platform-recipient-audit:${crypto.randomUUID()}`,e.event_kind,e.alert_id??null,e.entitlement_id??null,e.actor_id??null,e.authority_proof_id??null,e.endpoint_id??null,e.destination_digest??null,e.authority_domain??null,e.family??null,e.purpose??null,e.urgency??null,e.channel??null,e.outcome,e.reason_code,e.correlation_id,JSON.stringify(e.causal_references??[]),e.recorded_at).run();}catch{throw new PlatformRecipientError("PLATFORM_RECIPIENT_AUDIT_FAILED")}}
}
