import type { PlatformAlertReviewUrgencyV1,PlatformOperationalAlertIntentV1 } from "../platform.alert.contracts.v1";
export const PLATFORM_RECIPIENT_POLICY_VERSION="PLATFORM_RECIPIENT_POLICY_V1" as const;
export const PLATFORM_TENANT_ID="tenant:planneragent-platform" as const;
export const PLATFORM_COMPANY_ID="company:walcorp-platform" as const;
export type PlatformAlertChannelV1="EMAIL"|"SMS"|"WHATSAPP";
export type PlatformRecipientFailureCode="PLATFORM_RECIPIENT_REQUEST_INVALID"|"PLATFORM_ALERT_NOT_FOUND"|"PLATFORM_ALERT_NOT_ADMITTED"|"PLATFORM_ALERT_EXPIRED"|"PLATFORM_ORGANIZATION_INVALID"|"PLATFORM_ACTOR_NOT_FOUND"|"PLATFORM_ACTOR_INACTIVE"|"PLATFORM_MEMBERSHIP_INVALID"|"PLATFORM_AUTHORITY_MISSING"|"PLATFORM_AUTHORITY_INVALID"|"PLATFORM_AUTHORITY_DRIFTED"|"PLATFORM_DELEGATION_EXPIRED"|"PLATFORM_RECIPIENT_ENTITLEMENT_NOT_FOUND"|"PLATFORM_RECIPIENT_ENTITLEMENT_INACTIVE"|"PLATFORM_RECIPIENT_ENTITLEMENT_REVOKED"|"PLATFORM_RECIPIENT_AMBIGUOUS"|"PLATFORM_RECIPIENT_FAMILY_MISMATCH"|"PLATFORM_RECIPIENT_PURPOSE_MISMATCH"|"PLATFORM_RECIPIENT_URGENCY_EXCEEDED"|"PLATFORM_ENDPOINT_NOT_FOUND"|"PLATFORM_ENDPOINT_INACTIVE"|"PLATFORM_ENDPOINT_UNVERIFIED"|"PLATFORM_ENDPOINT_CHANNEL_MISMATCH"|"PLATFORM_ENDPOINT_SUBSTITUTED"|"PLATFORM_RECIPIENT_RESOLUTION_FAILED"|"PLATFORM_RECIPIENT_AUDIT_FAILED";
export class PlatformRecipientError extends Error{constructor(readonly code:PlatformRecipientFailureCode){super(code);this.name="PlatformRecipientError";}}
export interface PlatformAuthorityProofV1{readonly authority_proof_id:string;readonly platform_tenant_id:typeof PLATFORM_TENANT_ID;readonly platform_company_id:typeof PLATFORM_COMPANY_ID;readonly actor_id:string;readonly principal_id:string;readonly membership_id:string;readonly authority_domain:"PLATFORM_OPERATIONS";readonly effective_scope:readonly ["GOVERNED_DELIVERY_REVIEW"];readonly confirmation_chain_reference:string;readonly delegation_references:readonly string[];readonly graph_version:string;readonly eligibility_state:"ELIGIBLE"|"INELIGIBLE";readonly drift_state:"CURRENT"|"DRIFTED";readonly issued_at:string;readonly expires_at:string;readonly policy_version:string;readonly causal_references:readonly string[];}
export interface PlatformRecipientEntitlementV1{readonly version:1;readonly entitlement_id:string;readonly platform_tenant_id:typeof PLATFORM_TENANT_ID;readonly platform_company_id:typeof PLATFORM_COMPANY_ID;readonly actor_id:string;readonly principal_id:string;readonly membership_id:string;readonly authority_domain:"PLATFORM_OPERATIONS";readonly authority_proof_id:string;readonly communication_family:"PLATFORM_OPERATIONAL_ALERT";readonly purpose:"GOVERNED_DELIVERY_REVIEW";readonly urgency_ceiling:PlatformAlertReviewUrgencyV1;readonly allowed_channels:readonly PlatformAlertChannelV1[];readonly preferred_channel:PlatformAlertChannelV1;readonly recipient_priority:"PRIMARY"|"SUPERVISOR_FALLBACK";readonly supervisor_fallback_authorized:boolean;readonly lifecycle_state:"ACTIVE"|"INACTIVE"|"REVOKED";readonly effective_at:string;readonly expires_at:string;readonly correlation_id:string;readonly causal_references:readonly string[];}
export interface PlatformRecipientEndpointV1{readonly endpoint_id:string;readonly entitlement_id:string;readonly actor_id:string;readonly channel:PlatformAlertChannelV1;readonly normalized_destination:string;readonly destination_digest:string;readonly lifecycle_state:"ACTIVE"|"INACTIVE"|"REVOKED";readonly verification_state:"VERIFIED"|"UNVERIFIED";readonly effective_at:string;readonly expires_at:string;readonly verification_reference:string;readonly causal_references:readonly string[];}
export interface PlatformRecipientCandidateV1{readonly alert:PlatformOperationalAlertIntentV1;readonly admitted:boolean;readonly actor_state:string;readonly membership_state:string;readonly organization_current:boolean;readonly proof:PlatformAuthorityProofV1;readonly entitlement:PlatformRecipientEntitlementV1;readonly endpoint:PlatformRecipientEndpointV1;}
export interface PlatformRecipientResolutionRequestV1{readonly version:1;readonly alert_id:string;readonly requested_at:string;readonly correlation_id:string;readonly causal_references:readonly string[];}
export interface PlatformAlertRecipientEligibilityV1{readonly version:1;readonly eligibility_id:string;readonly resolution_id:string;readonly alert_id:string;readonly alert_admission_decision_reference:string;readonly platform_tenant_id:typeof PLATFORM_TENANT_ID;readonly platform_company_id:typeof PLATFORM_COMPANY_ID;readonly accountable_actor_id:string;readonly authority_proof_id:string;readonly recipient_entitlement_id:string;readonly endpoint_id:string;readonly endpoint_destination_digest:string;readonly channel:PlatformAlertChannelV1;readonly communication_family:"PLATFORM_OPERATIONAL_ALERT";readonly purpose:"GOVERNED_DELIVERY_REVIEW";readonly urgency:PlatformAlertReviewUrgencyV1;readonly issued_at:string;readonly expires_at:string;readonly policy_version:typeof PLATFORM_RECIPIENT_POLICY_VERSION;readonly correlation_id:string;readonly causal_references:readonly string[];}
export interface PlatformRecipientRepositoryV1{loadAlert(alertId:string):Promise<Readonly<{alert:PlatformOperationalAlertIntentV1;admitted:boolean}>|null>;candidates(alertId:string):Promise<readonly PlatformRecipientCandidateV1[]>;persist(eligibility:PlatformAlertRecipientEligibilityV1):Promise<void>;audit(event:Readonly<Record<string,unknown>>):Promise<void>;}
