import{ProviderAttestationFailureV1,type ProviderAccountIdentityV1,type ProviderDeploymentIdentityV1}from"./provider.account.contracts.v1";
import type{ProviderContractualProcessingAttestationV1,ProviderVerificationRequestV1,ProviderVerifiedFactSetV1}from"./provider.attestation.contracts.v1";
import{DEPLOYMENTS,PROVIDERS,digest,freeze,validateEvidence}from"./provider.attestation.policy.v1";
const text=(v:unknown)=>typeof v==="string"&&v.length>0&&v.length<=256&&!/[\r\n\0]/.test(v);
export async function verifyProviderFactsV1(r:ProviderVerificationRequestV1,now:string):Promise<ProviderVerifiedFactSetV1>{
 const c=r?.claim;if(!c||c.version!==1||!text(c.claim_id)||!PROVIDERS.includes(c.provider)||!text(c.account_reference)||!text(c.account_owner_reference)||!text(c.adapter_identity)||!text(c.claimant_id)||!text(c.correlation_id)||!Array.isArray(c.evidence_references)||!c.evidence_references.length||!Array.isArray(c.causal_references))throw new ProviderAttestationFailureV1("PROVIDER_ACCOUNT_CLAIM_INVALID");
 if(c.expires_at&&c.expires_at<=now)throw new ProviderAttestationFailureV1("PROVIDER_ACCOUNT_CLAIM_INVALID");
 const key=`${c.provider}:${c.account_owner_reference}:${c.account_reference}:${c.environment_class}`,accountId=`provider-account:sha256:${(await digest(key)).slice(0,32)}`;
 validateEvidence(r.account_evidence,accountId,undefined,now);if(!c.evidence_references.includes(r.account_evidence.evidence_id))throw new ProviderAttestationFailureV1("PROVIDER_ATTESTATION_EVIDENCE_REQUIRED");
 const ad=r.account_decision;if(!ad||ad.evidence_id!==r.account_evidence.evidence_id||ad.decision!=="VERIFIED"||ad.verifier_id!=="PLANNERNET_PROVIDER_CONTRACT_REVIEW"||ad.valid_until&&ad.valid_until<=now)throw new ProviderAttestationFailureV1("PROVIDER_ACCOUNT_NOT_VERIFIED");
 const account=freeze({version:1,provider_account_id:accountId,canonical_key:key,provider:c.provider,account_reference:c.account_reference,account_owner_reference:c.account_owner_reference,adapter_identity:c.adapter_identity,environment_class:c.environment_class,effective_at:c.effective_at,verification_status:"VERIFIED",verification_method:"GOVERNED_MANUAL_REVIEW",evidence_references:[...c.evidence_references],verified_at:ad.decided_at,...(ad.valid_until?{reverify_at:ad.valid_until}:{}),claim_id:c.claim_id,decision_id:ad.decision_id,correlation_id:ad.correlation_id,causal_references:[...ad.causal_references]})as ProviderAccountIdentityV1;
 let deployment:ProviderDeploymentIdentityV1|undefined;if(r.deployment){const d=r.deployment;if(!text(d.deployment_reference)||!DEPLOYMENTS.includes(d.deployment_class)||!text(d.processing_service_identity)||d.provider_deployment_id!==`provider-deployment:sha256:${(await digest(`${accountId}:${d.deployment_reference}`)).slice(0,32)}`)throw new ProviderAttestationFailureV1("PROVIDER_DEPLOYMENT_INVALID");if((d.deployment_class!=="SHARED_REMOTE_PROVIDER"&&d.deployment_class!=="LOCAL_SELF_HOSTED_MODEL"&&d.deployment_class!=="CUSTOMER_MANAGED_INFRASTRUCTURE")&&!d.evidence_references.length)throw new ProviderAttestationFailureV1("PROVIDER_ATTESTATION_EVIDENCE_REQUIRED");if(d.credential_reference&&!/^secret:\/\/[A-Za-z0-9][A-Za-z0-9/._-]{0,255}$/.test(d.credential_reference))throw new ProviderAttestationFailureV1("PROVIDER_CREDENTIAL_BINDING_INVALID");deployment=freeze({...d,provider_account_id:accountId,verification_status:"VERIFIED"})as ProviderDeploymentIdentityV1;}
 const attestations:ProviderContractualProcessingAttestationV1[]=[];for(const pair of r.attestations){const e=pair.evidence,d=pair.decision;validateEvidence(e,accountId,deployment?.provider_deployment_id,now);if(d.evidence_id!==e.evidence_id||d.decision!=="VERIFIED"||d.verifier_id!=="PLANNERNET_PROVIDER_CONTRACT_REVIEW")throw new ProviderAttestationFailureV1("PROVIDER_ATTESTATION_NOT_VERIFIED");if(d.valid_until&&d.valid_until<=now)throw new ProviderAttestationFailureV1("PROVIDER_ATTESTATION_EXPIRED");attestations.push(freeze({version:1,attestation_id:`provider-attestation:sha256:${(await digest({accountId,deployment:deployment?.provider_deployment_id,subject:e.subject,value:e.asserted_value,evidence:e.evidence_id})).slice(0,32)}`,provider_account_id:accountId,...(deployment?{provider_deployment_id:deployment.provider_deployment_id}:{}),subject:e.subject,value:e.asserted_value,evidence_id:e.evidence_id,issuer_id:e.issuer_id,issuer_class:e.issuer_class,status:"VERIFIED",effective_at:e.effective_at,...(e.expires_at?{expires_at:e.expires_at}:{}),verified_at:d.decided_at,decision_id:d.decision_id,correlation_id:d.correlation_id,causal_references:[...d.causal_references]} )as ProviderContractualProcessingAttestationV1);}
 const grouped=new Map<string,Set<string>>();for(const a of attestations){const k=`${a.provider_account_id}:${a.provider_deployment_id??"ACCOUNT"}:${a.subject}`,s=grouped.get(k)??new Set<string>();s.add(await digest(a.value));grouped.set(k,s);}if([...grouped.values()].some(s=>s.size>1))throw new ProviderAttestationFailureV1("PROVIDER_ATTESTATION_CONTRADICTED");attestations.sort((a,b)=>a.attestation_id.localeCompare(b.attestation_id));return freeze({version:1,account,...(deployment?{deployment}:{}),attestations,attestation_set_digest:await digest(attestations.map(a=>({id:a.attestation_id,subject:a.subject,value:a.value,evidence:a.evidence_id})))})as ProviderVerifiedFactSetV1;
}
export function revalidateProviderFactsV1(f:ProviderVerifiedFactSetV1,now:string):ProviderVerifiedFactSetV1{if(f.account.verification_status!=="VERIFIED")throw new ProviderAttestationFailureV1(f.account.verification_status==="REVOKED"?"PROVIDER_ACCOUNT_REVOKED":"PROVIDER_ACCOUNT_SUPERSEDED");if(f.account.reverify_at&&f.account.reverify_at<=now)throw new ProviderAttestationFailureV1("PROVIDER_ACCOUNT_NOT_VERIFIED");for(const a of f.attestations)if(a.expires_at&&a.expires_at<=now)throw new ProviderAttestationFailureV1("PROVIDER_ATTESTATION_EXPIRED");return freeze(f)as ProviderVerifiedFactSetV1;}
