import{ProviderAttestationFailureV1,type ProviderDeploymentClassV1,type ProviderIdentityV1}from"./provider.account.contracts.v1";
import type{ProviderAttestationEvidenceV1,ProviderAttestationSubjectV1,ProviderAttestationValueV1}from"./provider.attestation.contracts.v1";
export const PROVIDERS:readonly ProviderIdentityV1[]=Object.freeze(["openai","anthropic","openrouter","oss"]);
export const SUBJECTS:readonly ProviderAttestationSubjectV1[]=Object.freeze(["ENTERPRISE_AGREEMENT_ACTIVE","NDA_ACTIVE","DPA_ACTIVE","TRAINING_USE","RETENTION_LIMIT","ZERO_RETENTION","PROCESSING_REGION","DATA_RESIDENCY","DEPLOYMENT_CLASS","DEDICATED_INFRASTRUCTURE","CUSTOMER_MANAGED_KEYS","PROVIDER_MANAGED_KEYS","AUDIT_LOG_AVAILABLE","SUBPROCESSOR_DISCLOSURE_AVAILABLE","CONTRACT_VERSION","PROCESSING_TERMS_VERSION","INCIDENT_NOTIFICATION_COMMITMENT"]);
export const TRUSTED_ISSUERS=Object.freeze(["PLANNERNET_PROVIDER_CONTRACT_REVIEW","PROVIDER_SIGNED_EVIDENCE_INTAKE","QUALIFIED_PROVIDER_AUDITOR"]);
export const DEPLOYMENTS:readonly ProviderDeploymentClassV1[]=Object.freeze(["SHARED_REMOTE_PROVIDER","ENTERPRISE_DEDICATED_EXTERNAL_PROVIDER","SOVEREIGN_REGION_EXTERNAL_PROVIDER","LOCAL_SELF_HOSTED_MODEL","CUSTOMER_MANAGED_INFRASTRUCTURE"]);
export function freeze<T>(x:T):Readonly<T>{const v=structuredClone(x)as any;const f=(o:any):any=>{if(o&&typeof o==="object"&&!Object.isFrozen(o)){Object.values(o).forEach(f);Object.freeze(o);}return o;};return f(v);}
export function canonical(x:unknown):string{if(Array.isArray(x))return`[${x.map(canonical).join(",")}]`;if(x&&typeof x==="object")return`{${Object.entries(x as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${canonical(v)}`).join(",")}}`;return JSON.stringify(x);}
export async function digest(x:unknown){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(x)));return Array.from(new Uint8Array(b)).map(v=>v.toString(16).padStart(2,"0")).join("");}
export function validateValue(subject:ProviderAttestationSubjectV1,v:ProviderAttestationValueV1){let ok=false;if(["ENTERPRISE_AGREEMENT_ACTIVE","NDA_ACTIVE","DPA_ACTIVE","DEDICATED_INFRASTRUCTURE","CUSTOMER_MANAGED_KEYS","PROVIDER_MANAGED_KEYS","AUDIT_LOG_AVAILABLE","SUBPROCESSOR_DISCLOSURE_AVAILABLE","INCIDENT_NOTIFICATION_COMMITMENT"].includes(subject))ok=v.kind==="BOOLEAN";else if(subject==="TRAINING_USE")ok=v.kind==="TRAINING_USE"&&["PROHIBITED","ALLOWED","UNSPECIFIED"].includes(v.value);else if(subject==="RETENTION_LIMIT"||subject==="ZERO_RETENTION")ok=v.kind==="RETENTION"&&(["ZERO_RETENTION","PROVIDER_DEFAULT","UNSPECIFIED"].includes(v.value)||(v.value==="BOUNDED_DAYS"&&Number.isInteger(v.maximum_days)&&v.maximum_days>0));else if(subject==="PROCESSING_REGION"||subject==="DATA_RESIDENCY")ok=v.kind==="REGIONS"&&v.values.length>0&&v.values.every(x=>/^[A-Z0-9_-]{2,32}$/.test(x));else if(subject==="DEPLOYMENT_CLASS")ok=v.kind==="DEPLOYMENT_CLASS"&&DEPLOYMENTS.includes(v.value as ProviderDeploymentClassV1);else ok=v.kind==="VERSION"&&/^[A-Za-z0-9._-]{1,128}$/.test(v.value);if(!ok)throw new ProviderAttestationFailureV1("PROVIDER_ATTESTATION_VALUE_INVALID");}
export function validateEvidence(e:ProviderAttestationEvidenceV1,account:string,deployment:string|undefined,now:string){if(!e||!e.evidence_id||!/^sha256:[a-f0-9]{64}$/.test(e.immutable_digest)||!e.governed_reference||e.verification_state!=="ACCEPTED")throw new ProviderAttestationFailureV1("PROVIDER_ATTESTATION_EVIDENCE_INVALID");if(!SUBJECTS.includes(e.subject))throw new ProviderAttestationFailureV1("PROVIDER_ATTESTATION_SUBJECT_UNSUPPORTED");if(!TRUSTED_ISSUERS.includes(e.issuer_id)||e.issuer_class==="INTERNAL_PLATFORM_CONFIGURATION_EVIDENCE")throw new ProviderAttestationFailureV1("PROVIDER_ATTESTATION_ISSUER_UNTRUSTED");if(e.provider_account_id!==account)throw new ProviderAttestationFailureV1("PROVIDER_ATTESTATION_ACCOUNT_MISMATCH");if(e.provider_deployment_id!==deployment)throw new ProviderAttestationFailureV1("PROVIDER_ATTESTATION_DEPLOYMENT_MISMATCH");if(e.effective_at>now||e.expires_at&&e.expires_at<=now)throw new ProviderAttestationFailureV1("PROVIDER_ATTESTATION_EVIDENCE_EXPIRED");validateValue(e.subject,e.asserted_value);}
