import type{ProviderAccountClaimV1,ProviderAccountIdentityV1,ProviderDeploymentIdentityV1}from"./provider.account.contracts.v1";
export type ProviderAttestationSubjectV1="ENTERPRISE_AGREEMENT_ACTIVE"|"NDA_ACTIVE"|"DPA_ACTIVE"|"TRAINING_USE"|"RETENTION_LIMIT"|"ZERO_RETENTION"|"PROCESSING_REGION"|"DATA_RESIDENCY"|"DEPLOYMENT_CLASS"|"DEDICATED_INFRASTRUCTURE"|"CUSTOMER_MANAGED_KEYS"|"PROVIDER_MANAGED_KEYS"|"AUDIT_LOG_AVAILABLE"|"SUBPROCESSOR_DISCLOSURE_AVAILABLE"|"CONTRACT_VERSION"|"PROCESSING_TERMS_VERSION"|"INCIDENT_NOTIFICATION_COMMITMENT";
export type ProviderAttestationIssuerClassV1="PROVIDER_SIGNED_ATTESTATION"|"GOVERNED_MANUAL_CONTRACT_REVIEW"|"QUALIFIED_THIRD_PARTY_VERIFICATION"|"CUSTOMER_MANAGED_INFRASTRUCTURE_ATTESTATION"|"INTERNAL_PLATFORM_CONFIGURATION_EVIDENCE";
export type ProviderAttestationValueV1=Readonly<{kind:"BOOLEAN";value:boolean}|{kind:"TRAINING_USE";value:"PROHIBITED"|"ALLOWED"|"UNSPECIFIED"}|{kind:"RETENTION";value:"ZERO_RETENTION"|"PROVIDER_DEFAULT"|"UNSPECIFIED";maximum_days?:never}|{kind:"RETENTION";value:"BOUNDED_DAYS";maximum_days:number}|{kind:"REGIONS";values:readonly string[]}|{kind:"DEPLOYMENT_CLASS";value:string}|{kind:"VERSION";value:string}>;
export interface ProviderAttestationEvidenceV1{readonly version:1;readonly evidence_id:string;readonly issuer_id:string;readonly issuer_class:ProviderAttestationIssuerClassV1;readonly provider_account_id:string;readonly provider_deployment_id?:string;readonly subject:ProviderAttestationSubjectV1;readonly asserted_value:ProviderAttestationValueV1;readonly evidence_type:"IMMUTABLE_DOCUMENT_REFERENCE"|"SIGNED_ATTESTATION_REFERENCE"|"GOVERNED_REVIEW_DECISION";readonly governed_reference:string;readonly immutable_digest:string;readonly issued_at:string;readonly effective_at:string;readonly expires_at?:string;readonly verification_state:"SUBMITTED"|"ACCEPTED"|"REJECTED";readonly verifier_id?:string;readonly correlation_id:string;readonly causal_references:readonly string[];}
export interface ProviderAttestationDecisionV1{readonly version:1;readonly decision_id:string;readonly evidence_id:string;readonly verifier_id:string;readonly decision:"VERIFIED"|"REJECTED";readonly reason_codes:readonly string[];readonly decided_at:string;readonly valid_until?:string;readonly correlation_id:string;readonly causal_references:readonly string[];}
export interface ProviderContractualProcessingAttestationV1{readonly version:1;readonly attestation_id:string;readonly provider_account_id:string;readonly provider_deployment_id?:string;readonly subject:ProviderAttestationSubjectV1;readonly value:ProviderAttestationValueV1;readonly evidence_id:string;readonly issuer_id:string;readonly issuer_class:ProviderAttestationIssuerClassV1;readonly status:"VERIFIED";readonly effective_at:string;readonly expires_at?:string;readonly verified_at:string;readonly decision_id:string;readonly correlation_id:string;readonly causal_references:readonly string[];}
export interface ProviderVerificationRequestV1{readonly claim:ProviderAccountClaimV1;readonly account_evidence:ProviderAttestationEvidenceV1;readonly account_decision:ProviderAttestationDecisionV1;readonly deployment?:Omit<ProviderDeploymentIdentityV1,"provider_account_id"|"verification_status">;readonly attestations:readonly{readonly evidence:ProviderAttestationEvidenceV1;readonly decision:ProviderAttestationDecisionV1}[];}
export interface ProviderVerifiedFactSetV1{readonly version:1;readonly account:ProviderAccountIdentityV1;readonly deployment?:ProviderDeploymentIdentityV1;readonly attestations:readonly ProviderContractualProcessingAttestationV1[];readonly attestation_set_digest:string;}
