export type ProviderIdentityV1="openai"|"anthropic"|"openrouter"|"oss";
export type ProviderDeploymentClassV1="SHARED_REMOTE_PROVIDER"|"ENTERPRISE_DEDICATED_EXTERNAL_PROVIDER"|"SOVEREIGN_REGION_EXTERNAL_PROVIDER"|"LOCAL_SELF_HOSTED_MODEL"|"CUSTOMER_MANAGED_INFRASTRUCTURE";
export type ProviderVerificationStatusV1="CLAIMED"|"EVIDENCE_SUBMITTED"|"VERIFIED"|"EXPIRED"|"REVOKED"|"SUPERSEDED"|"REJECTED"|"CONTRADICTED";
export type ProviderFailureCodeV1=
 |"PROVIDER_ACCOUNT_CLAIM_INVALID"|"PROVIDER_ACCOUNT_IDENTITY_INVALID"|"PROVIDER_ACCOUNT_NOT_VERIFIED"|"PROVIDER_ACCOUNT_DUPLICATE"|"PROVIDER_ACCOUNT_CONFLICT"|"PROVIDER_ACCOUNT_SUBSTITUTED"|"PROVIDER_ACCOUNT_REVOKED"|"PROVIDER_ACCOUNT_SUPERSEDED"
 |"PROVIDER_DEPLOYMENT_INVALID"|"PROVIDER_DEPLOYMENT_SUBSTITUTED"|"PROVIDER_CREDENTIAL_BINDING_INVALID"|"PROVIDER_ATTESTATION_SUBJECT_UNSUPPORTED"|"PROVIDER_ATTESTATION_VALUE_INVALID"|"PROVIDER_ATTESTATION_EVIDENCE_REQUIRED"|"PROVIDER_ATTESTATION_EVIDENCE_INVALID"|"PROVIDER_ATTESTATION_EVIDENCE_EXPIRED"|"PROVIDER_ATTESTATION_ISSUER_UNTRUSTED"|"PROVIDER_ATTESTATION_NOT_VERIFIED"|"PROVIDER_ATTESTATION_EXPIRED"|"PROVIDER_ATTESTATION_REVOKED"|"PROVIDER_ATTESTATION_SUPERSEDED"|"PROVIDER_ATTESTATION_CONTRADICTED"|"PROVIDER_ATTESTATION_ACCOUNT_MISMATCH"|"PROVIDER_ATTESTATION_DEPLOYMENT_MISMATCH"|"PROVIDER_ATTESTATION_PERSISTENCE_FAILED"|"PROVIDER_ATTESTATION_AUDIT_FAILED";
export class ProviderAttestationFailureV1 extends Error{constructor(readonly code:ProviderFailureCodeV1){super(code);this.name="ProviderAttestationFailureV1";}}
export interface ProviderAccountClaimV1{readonly version:1;readonly claim_id:string;readonly provider:ProviderIdentityV1;readonly account_reference:string;readonly account_owner_reference:string;readonly adapter_identity:string;readonly environment_class:"PRODUCTION"|"NON_PRODUCTION";readonly claimed_deployment_reference?:string;readonly claimed_deployment_class?:ProviderDeploymentClassV1;readonly claimant_id:string;readonly evidence_references:readonly string[];readonly effective_at:string;readonly expires_at?:string;readonly correlation_id:string;readonly causal_references:readonly string[];}
export interface ProviderAccountIdentityV1{readonly version:1;readonly provider_account_id:string;readonly canonical_key:string;readonly provider:ProviderIdentityV1;readonly account_reference:string;readonly account_owner_reference:string;readonly adapter_identity:string;readonly environment_class:"PRODUCTION"|"NON_PRODUCTION";readonly effective_at:string;readonly verification_status:"VERIFIED";readonly verification_method:"GOVERNED_MANUAL_REVIEW";readonly evidence_references:readonly string[];readonly verified_at:string;readonly reverify_at?:string;readonly claim_id:string;readonly decision_id:string;readonly correlation_id:string;readonly causal_references:readonly string[];}
export interface ProviderDeploymentIdentityV1{readonly version:1;readonly provider_deployment_id:string;readonly provider_account_id:string;readonly deployment_reference:string;readonly deployment_class:ProviderDeploymentClassV1;readonly model_references:readonly string[];readonly processing_service_identity:string;readonly verified_regions:readonly string[];readonly credential_reference?:string;readonly effective_at:string;readonly verification_status:"VERIFIED";readonly evidence_references:readonly string[];readonly verified_at:string;readonly reverify_at?:string;readonly correlation_id:string;readonly causal_references:readonly string[];}
export interface ProviderCredentialBindingV1{readonly version:1;readonly binding_id:string;readonly provider_account_id:string;readonly provider_deployment_id?:string;readonly credential_reference:string;readonly bound_at:string;readonly evidence_reference:string;readonly correlation_id:string;readonly causal_references:readonly string[];}
