import {createHash} from "node:crypto";
import {describe,expect,it,vi} from "vitest";
import {deepCopyAndFreeze} from "../../../knowledge-exposure/knowledge.projection.guard.v1";
import {PLATFORM_ALERT_DISCLOSURE_MANIFEST_ID,PLATFORM_ALERT_DISCLOSURE_POLICY_VERSION,PLATFORM_ALERT_DISCLOSURE_PROFILE_ID,PLATFORM_ALERT_DISCLOSURE_PROFILE_VERSION,type PlatformAlertDispatchEligibilityV1} from "../../disclosure";
import {PlatformAlertDeliveryRuntimeV1} from "../platform.alert.delivery.runtime.v1";
import type {PlatformAlertChannelV1} from "../../recipient";
import type {PlatformAlertDeliveryEvidenceRepositoryV1,PlatformAlertDeliveryEvidenceV1} from "../platform.alert.delivery.contracts.v1";

const NOW="2026-08-06T10:00:00.000Z",hash=(s:string)=>createHash("sha256").update(s,"utf8").digest("hex");
const address=(channel:PlatformAlertChannelV1)=>channel==="EMAIL"?"operator@example.com":channel==="SMS"?"+391234567890":"whatsapp:+391234567890";
function eligibility(channel:PlatformAlertChannelV1="EMAIL",overrides:Partial<PlatformAlertDispatchEligibilityV1>={}):PlatformAlertDispatchEligibilityV1{return deepCopyAndFreeze({version:1,disclosure_id:"disclosure:1",alert_id:"alert:1",recipient_eligibility_id:"eligibility:1",profile_id:PLATFORM_ALERT_DISCLOSURE_PROFILE_ID,profile_version:PLATFORM_ALERT_DISCLOSURE_PROFILE_VERSION,alert_admission_decision_reference:"decision:1",recipient_resolution_id:"resolution:1",family:"PLATFORM_OPERATIONAL_ALERT",purpose:"GOVERNED_DELIVERY_REVIEW",projection:{alert_id:"a",source_class:"WU4B_EMAIL_DELIVERY",source_outcome:"FAILED",review_urgency:"REVIEW_REQUIRED",source_evidence_id:"e",source_evidence_digest:"d",tenant_reference_digest:null,company_reference_digest:null,correlation_id:"c",effective_at:"2026-08-06T09:00:00.000Z",expires_at:"2026-08-06T11:00:00.000Z",acknowledgement_required:true},manifest_id:PLATFORM_ALERT_DISCLOSURE_MANIFEST_ID,projection_digest:"p".repeat(64),representation:"STRUCTURED_JSON",classification:"INTERNAL",sovereignty:"TENANT_LOCAL",retention:"NO_RETENTION",accountable_actor_id:"actor:1",recipient_entitlement_id:"entitlement:1",endpoint_id:"endpoint:1",endpoint_destination_digest:hash(address(channel)),channel,authority_proof_id:"proof:1",urgency:"REVIEW_REQUIRED",policy_version:PLATFORM_ALERT_DISCLOSURE_POLICY_VERSION,admitted_at:"2026-08-06T09:30:00.000Z",expires_at:"2026-08-06T11:00:00.000Z",correlation_id:"correlation:1",causal_references:["cause:1"],canonical_digest:"c".repeat(64),disclosure_consumption_id:"consumption:1",consumed_at:"2026-08-06T09:59:00.000Z",transport_executed:false,...overrides}) as PlatformAlertDispatchEligibilityV1;}
class Evidence implements PlatformAlertDeliveryEvidenceRepositoryV1{used=false;events:PlatformAlertDeliveryEvidenceV1[]=[];async reserve(){if(this.used)return false;this.used=true;return true;}async append(e:PlatformAlertDeliveryEvidenceV1){this.events.push(e);}}
function services(channel:PlatformAlertChannelV1="EMAIL"){const evidence=new Evidence(),sendEmail=vi.fn(async(_request:unknown):Promise<{ok:boolean;provider_message_reference?:string}>=>({ok:true,provider_message_reference:"email-secret"})),sendTwilio=vi.fn(async(_request:unknown)=>({provider_message_reference:"twilio-secret"})),destination=address(channel),endpoints={readBound:vi.fn(async(_id:string)=>({endpoint_id:"endpoint:1",entitlement_id:"entitlement:1",actor_id:"actor:1",channel,normalized_destination:destination,destination_digest:hash(destination)}))},binding={provider_identity:"twilio" as const,product:channel==="WHATSAPP"?"TWILIO_WHATSAPP" as const:"TWILIO_SMS" as const,sender_identity_reference:"sender:1"},runtime=new PlatformAlertDeliveryRuntimeV1({endpoints,transports:{email:{provider_id:"email-provider",send:sendEmail},sms:{binding:{...binding,product:"TWILIO_SMS"},send:sendTwilio},whatsapp:{binding:{...binding,product:"TWILIO_WHATSAPP"},send:sendTwilio}},evidence,now:()=>NOW});return{runtime,evidence,endpoints,sendEmail,sendTwilio};}

describe("PA-WU4 governed platform alert delivery",()=>{
 it("reuses the email provider with the immutable PA-WU3 projection",async()=>{const s=services(),out=await s.runtime.deliver({eligibility:eligibility()});expect(out.status).toBe("SUCCEEDED");expect(s.sendEmail).toHaveBeenCalledOnce();expect((s.sendEmail.mock.calls as unknown as Array<[unknown]>)[0]![0]).toMatchObject({to:"operator@example.com",content_type:"application/json; charset=utf-8"});expect(Object.isFrozen(out.evidence)).toBe(true);});
 it("loads only the already-bound endpoint id",async()=>{const s=services();await s.runtime.deliver({eligibility:eligibility()});expect(s.endpoints.readBound).toHaveBeenCalledWith("endpoint:1");});
 it("rejects endpoint, actor, entitlement, digest, and channel substitution",async()=>{for(const change of [{actor_id:"other"},{entitlement_id:"other"},{destination_digest:"0".repeat(64)},{channel:"SMS" as const}]){const s=services(),base=await s.endpoints.readBound("endpoint:1");s.endpoints.readBound.mockResolvedValue({...base!,...change});await expect(s.runtime.deliver({eligibility:eligibility()})).rejects.toMatchObject({code:expect.stringMatching(/ENDPOINT_SUBSTITUTED|CHANNEL_MISMATCH/)});expect(s.sendEmail).not.toHaveBeenCalled();}});
 it("fails closed for missing, mutable, malformed, and expired eligibility",async()=>{await expect(services().runtime.deliver({eligibility:undefined as any})).rejects.toMatchObject({code:"PLATFORM_ALERT_DELIVERY_ELIGIBILITY_REQUIRED"});await expect(services().runtime.deliver({eligibility:{...eligibility()} as any})).rejects.toMatchObject({code:"PLATFORM_ALERT_DELIVERY_ELIGIBILITY_REQUIRED"});await expect(services().runtime.deliver({eligibility:eligibility("EMAIL",{purpose:"OTHER" as any})})).rejects.toMatchObject({code:"PLATFORM_ALERT_DELIVERY_ELIGIBILITY_INVALID"});await expect(services().runtime.deliver({eligibility:eligibility("EMAIL",{expires_at:NOW})})).rejects.toMatchObject({code:"PLATFORM_ALERT_DELIVERY_EXPIRED"});});
 it("reserves before transport and prevents replay",async()=>{const s=services(),input={eligibility:eligibility()};await s.runtime.deliver(input);await expect(s.runtime.deliver(input)).rejects.toMatchObject({code:"PLATFORM_ALERT_DELIVERY_ALREADY_ATTEMPTED"});expect(s.sendEmail).toHaveBeenCalledOnce();});
 it("records content-free success and typed failure evidence",async()=>{const s=services();await s.runtime.deliver({eligibility:eligibility()});expect(JSON.stringify(s.evidence.events[0])).not.toMatch(/operator@example.com|email-secret/);const f=services();f.sendEmail.mockResolvedValue({ok:false});await expect(f.runtime.deliver({eligibility:eligibility()})).rejects.toMatchObject({code:"PLATFORM_ALERT_DELIVERY_TRANSPORT_FAILED"});expect(f.evidence.events[0]).toMatchObject({status:"FAILED",failure_code:"PLATFORM_ALERT_DELIVERY_TRANSPORT_FAILED"});});
 it("fails closed instead of truncating or falling back when the frozen projection exceeds SMS",async()=>{const s=services("SMS");await expect(s.runtime.deliver({eligibility:eligibility("SMS")})).rejects.toMatchObject({code:"PLATFORM_ALERT_DELIVERY_PAYLOAD_TOO_LARGE"});expect(s.sendTwilio).not.toHaveBeenCalled();expect(s.sendEmail).not.toHaveBeenCalled();});
 it("reuses the exact WhatsApp transport without fallback",async()=>{const s=services("WHATSAPP");await s.runtime.deliver({eligibility:eligibility("WHATSAPP")});expect(s.sendTwilio).toHaveBeenCalledWith(expect.objectContaining({channel:"WHATSAPP",product:"TWILIO_WHATSAPP",destination:"whatsapp:+391234567890"}));expect(s.sendEmail).not.toHaveBeenCalled();});
 it("classifies an ambiguous Twilio timeout as immutable indeterminate evidence",async()=>{const s=services("WHATSAPP");s.sendTwilio.mockRejectedValue({code:"GOVERNED_TWILIO_TIMEOUT"});await expect(s.runtime.deliver({eligibility:eligibility("WHATSAPP")})).rejects.toMatchObject({code:"PLATFORM_ALERT_DELIVERY_INDETERMINATE"});expect(s.evidence.events[0]).toMatchObject({status:"INDETERMINATE",failure_code:"PLATFORM_ALERT_DELIVERY_INDETERMINATE"});});
 it("fails closed when immutable evidence cannot be appended",async()=>{const s=services();s.evidence.append=async()=>{throw new Error("storage")};await expect(s.runtime.deliver({eligibility:eligibility()})).rejects.toMatchObject({code:"PLATFORM_ALERT_DELIVERY_EVIDENCE_FAILED"});});
});
