import {describe,expect,it} from "vitest";
import {bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1} from "../../cockpit/operational.signal.evaluation.scope.v1";
import {createOperationalDomainEvidenceProfileV1,createOperationalSubjectRefV1} from "../../cognition/canonical.operational.roles.v1";
import {classifyGovernedOperationalEvidenceV1,createGovernedOperationalRepresentationV1,createObservationBreadthV1,createOperationalRepresentationRelationshipV1} from "../governed.operational.representation.v1";

const at="2026-08-26T08:00:00.000Z";
async function setup(){const profile=await createOperationalDomainEvidenceProfileV1({version:1,profile_ref:"profile:generic-operations",domain_ref:"domain:operations",profile_version:"1",supported_subject_kinds:["OPERATION"],evidence_mappings:[{evidence_kind:"OBSERVED_STATE",role:"OBSERVATION",modality:"SNAPSHOT"}],relationship_family_ref:"relationship-family:generic"}),subject=await createOperationalSubjectRefV1({version:1,company_id:"company:1",profile,subject_kind:"OPERATION",subject_ref:"operation:all"}),scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"REQUEST_DATASET",request_id:"request:1",company_id:"company:1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1"}),binding=await bindOperationalSignalsToScopeV1({scope,request_id:"request:1",company_id:"company:1",evidence_as_of:at,evaluated_at:"2026-08-26T08:01:00.000Z"});return{subject,binding}}
async function representation(ref:string,bindings=["connector:1"]){const {subject,binding}=await setup();return createGovernedOperationalRepresentationV1({version:1,representation_ref:ref,company_id:"company:1",domain_ref:"domain:operations",governed_scope_refs:[binding.scope.scope_id],subjects:[subject],source_binding_refs:bindings,provenance_refs:[`provenance:${ref}`],causal_lineage_refs:[`lineage:${ref}`],observability:"PERSISTENT",refreshability:"INDEPENDENTLY_REFRESHABLE",refresh_policy_ref:"refresh-policy:scheduled"})}
const adhoc=(kind:"XLSX"|"CSV"|"EMAIL"|"CHAT"|"DOCUMENT"|"USER_STATEMENT")=>classifyGovernedOperationalEvidenceV1({version:1,evidence_ref:`evidence:${kind}`,evidence_kind:kind,provenance_refs:[`provenance:${kind}`],causal_lineage_refs:[`lineage:${kind}`]});

describe("governed I-ORS observation breadth foundation",()=>{
 it("gives one persistent representation stable identity independent of endpoint count",async()=>{const one=await representation("representation:supplier-mailbox",["endpoint:imap"]),many=await representation("representation:supplier-mailbox",["endpoint:imap","endpoint:graph","endpoint:gmail","endpoint:gateway"]);expect(one.representation_id).toBe(many.representation_id);expect(one.artifact_digest).not.toBe(many.artifact_digest);expect(Object.isFrozen(one)&&Object.isFrozen(one.source_binding_refs)).toBe(true);expect(JSON.stringify(one)).not.toMatch(/authority_tier|intelligence_mode|inference_provider|confidence|quality_score/)});
 it("keeps separately observable derived representations distinct without inferring independence",async()=>{const sap=await representation("representation:source"),dw=await representation("representation:warehouse"),bi=await representation("representation:reporting"),a=await createOperationalRepresentationRelationshipV1({version:1,relationship_kind:"DERIVED_FROM",source:dw,target:sap,provenance_refs:["provenance:dw"],causal_lineage_refs:["lineage:dw"]}),b=await createOperationalRepresentationRelationshipV1({version:1,relationship_kind:"DEPENDS_ON",source:bi,target:dw,provenance_refs:["provenance:bi"],causal_lineage_refs:[a.relationship_id]});expect(new Set([sap.representation_id,dw.representation_id,bi.representation_id]).size).toBe(3);expect(a.independence).toBe("NOT_ESTABLISHED");expect(b.causal_lineage_refs).toContain(a.relationship_id);await expect(createOperationalRepresentationRelationshipV1({version:1,relationship_kind:"INDEPENDENT",source:sap,target:dw,provenance_refs:["provenance:test"],causal_lineage_refs:["lineage:test"]})).rejects.toThrow("IORS_INDEPENDENCE_EVIDENCE_REQUIRED")});
 it("counts distinct I-ORS only, independent of confidence and authority",async()=>{const {binding}=await setup(),a=await representation("representation:workforce"),b=await representation("representation:attendance"),breadth=await createObservationBreadthV1({version:1,evaluation_scope:binding,representations:[b,a,a]});expect(breadth.count).toBe(2);expect(breadth.representations).toEqual([...breadth.representations].sort());expect(breadth).toMatchObject({observational_only:true,tier_independent:true,confidence_independent:true,grants_authority:false,grants_execution:false});expect(Object.isFrozen(breadth)&&Object.isFrozen(breadth.representations)).toBe(true);await expect(createObservationBreadthV1({version:1,evaluation_scope:binding,representations:[a],confidence:.9}as any)).rejects.toThrow("IORS_UNSUPPORTED_SEMANTIC")});
 it.each(["XLSX","CSV","EMAIL","CHAT","DOCUMENT","USER_STATEMENT"] as const)("classifies manual %s as ad-hoc evidence without increasing breadth",async kind=>{const {binding}=await setup(),a=await representation("representation:workforce"),b=await representation("representation:attendance"),before=await createObservationBreadthV1({version:1,evaluation_scope:binding,representations:[a,b]}),evidence=adhoc(kind),after=await createObservationBreadthV1({version:1,evaluation_scope:binding,representations:[a,b]});expect(evidence).toMatchObject({introduction_mode:"REQUEST_BOUND_AD_HOC",creates_operational_representation:false});expect(after.count).toBe(before.count)});
 it("treats a persistent mailbox as one I-ORS and its emails as evidence within it",async()=>{const mailbox=await representation("representation:supplier-mailbox",["endpoint:imap","endpoint:provider-api"]),first=classifyGovernedOperationalEvidenceV1({version:1,evidence_ref:"email:1",representation:mailbox,provenance_refs:["provenance:email:1"],causal_lineage_refs:["lineage:email:1"]}),second=classifyGovernedOperationalEvidenceV1({version:1,evidence_ref:"email:2",representation:mailbox,provenance_refs:["provenance:email:2"],causal_lineage_refs:["lineage:email:2"]}),other=await representation("representation:customer-service-mailbox");expect(first).toMatchObject({introduction_mode:"PERSISTENT_REPRESENTATION_OBSERVATION",representation_id:mailbox.representation_id,creates_operational_representation:false});if(second.introduction_mode!=="PERSISTENT_REPRESENTATION_OBSERVATION")throw new Error("test fixture invalid");expect(second.representation_id).toBe(mailbox.representation_id);expect(other.representation_id).not.toBe(mailbox.representation_id)});
});
