import { describe, expect, it } from "vitest";
import { bindOperationalSignalsToScopeV1, createOperationalSignalEvaluationScopeV1 } from "../../cockpit/operational.signal.evaluation.scope.v1";
import { preserveGovernedOperationsFactV1, type GovernedOperationsFactV1 } from "../../industrial/preservation/governed.operational.fact.preservation.v1";
import { retrieveCanonicalStructuredRealityV1 } from "../canonical.operational.reality.composition.v1";
import { createGovernedSubjectBindingV1, createGovernedTemporalBindingV1 } from "../governed.multi-source.reality.alignment.v1";
import { createGovernedOperationalRepresentationV1 } from "../governed.operational.representation.v1";
import { composeExistingObservedOperationalRealityV1 } from "../multi-source.operational.reality.runtime.v1";
import { bridgeGovernedPersistentSourceFactV1, createGovernedPersistentFactSemanticBindingV1 } from "../persistent.source.observation.bridge.v1";

const producedAt="2026-08-26T10:00:00.000Z",receivedAt="2026-08-26T10:15:00.000Z",asOf="2026-08-26T10:30:00.000Z";
const metadata=(source:string)=>({tenantId:"1",companyId:"1",sourceSystem:source,connectorIdentityId:`connector:${source}`,connectorRevision:1,acquisitionReference:`acquisition:${source}`,authorizationReference:`authorization:${source}`,acquiredAt:asOf,capabilityId:"read",sourceRepresentation:`representation-format:${source}`});
async function evaluationScope(){const scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"REQUEST_DATASET",request_id:"request:1",company_id:"company:1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1"});return bindOperationalSignalsToScopeV1({scope,request_id:"request:1",company_id:"company:1",evidence_as_of:asOf,evaluated_at:"2026-08-26T10:31:00.000Z"})}
async function representation(fact:GovernedOperationsFactV1,scope:Awaited<ReturnType<typeof evaluationScope>>,ref:string){return createGovernedOperationalRepresentationV1({version:1,representation_ref:ref,company_id:"company:1",domain_ref:"domain:operations",governed_scope_refs:[scope.scope.scope_id],subjects:[fact.role_bindings.subject],source_binding_refs:[fact.provenance.connector_identity_id],provenance_refs:[`provenance:${ref}`],causal_lineage_refs:[`lineage:${ref}`],observability:"PERSISTENT",refreshability:"INDEPENDENTLY_REFRESHABLE",refresh_policy_ref:"refresh-policy:scheduled"})}
async function fixture(receivedQuantity=95,receivedState="state:WAREHOUSE_RECEIVED",receivedStage="stage:RECEIVING",receivedLocation="location:warehouse"){
 const scope=await evaluationScope(),produced=await preserveGovernedOperationsFactV1("MATERIAL_MOVEMENTS",{movement_id:"M1",production_order_id:"P1",article:"X",quantity:100,unit:"EA",type:"PRODUCED",occurred_at:producedAt},metadata("execution")),received=await preserveGovernedOperationsFactV1("INVENTORY",{inventory_id:"I1",warehouse_id:"WH1",sku:"X",quantity:receivedQuantity,unit:"EA",observed_at:receivedAt},metadata("warehouse")),execution=await representation(produced,scope,"representation:execution"),warehouse=await representation(received,scope,"representation:warehouse"),subject=await createGovernedSubjectBindingV1({version:1,outcome:"SAME_SUBJECT",members:[{representation_identity_ref:execution.representation_id,local_subject_ref:produced.source_fact_ref},{representation_identity_ref:warehouse.representation_id,local_subject_ref:received.source_fact_ref}],canonical_subject:produced.role_bindings.subject,binding_evidence_refs:["evidence:subject-map"],provenance_refs:["provenance:subject-map"],causal_lineage_refs:["lineage:subject-map"]});
 const observe=async(fact:GovernedOperationsFactV1,source:typeof execution,state:string,stage:string,location:string)=>bridgeGovernedPersistentSourceFactV1({version:1,fact,representation:source,evaluation_scope:scope,subject_binding:subject,semantic_binding:await createGovernedPersistentFactSemanticBindingV1({version:1,fact_ref:fact.fact_id,representation_id:source.representation_id,dimension_ref:"dimension:quantity",operational_state_ref:state,process_stage_ref:stage,location_refs:[location],qualification_refs:["qualification:semantic-map"],provenance_refs:["provenance:semantic-map"],causal_lineage_refs:["lineage:semantic-map"]})});
 const left=await observe(produced,execution,"state:PRODUCED","stage:PRODUCTION","location:production"),right=await observe(received,warehouse,receivedState,receivedStage,receivedLocation),temporal=await createGovernedTemporalBindingV1({version:1,left_observation_ref:left.observation_ref,right_observation_ref:right.observation_ref,left_effectivity:{from:left.effective_from!},right_effectivity:{from:right.effective_from!},relevance_evidence_refs:["evidence:process-sequence"]});return{scope,left,right,temporal,execution,warehouse};
}
describe("existing observers multi-source runtime v1",()=>{
 it("composes two existing source realities while preserving identity, stages, complementarity, breadth, and structured retrieval",async()=>{const f=await fixture(),result=await composeExistingObservedOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:f.scope,observations:[f.right,f.left],temporal_bindings:[f.temporal],representation_relationships:[],coverage:[]}),retrieved=await retrieveCanonicalStructuredRealityV1(result.canonical_reality,f.left.observation_ref);expect(result.observation_breadth).toMatchObject({count:2,confidence_independent:true});expect(result.alignment.claim_relationships[0]).toMatchObject({relationship:"COMPLEMENTARY",semantically_comparable:false});expect(result.alignment.canonical_evidence.map(x=>x.source_identity_ref)).toEqual([f.execution.representation_id,f.warehouse.representation_id].sort());expect(result.canonical_reality).toMatchObject({composition_status:"COMPOSED",recommended:false,grants_authority:false,grants_execution:false});expect(result.canonical_reality.semantic_groups).toHaveLength(2);expect(retrieved.comparison_candidates[0]).toMatchObject({observation_ref:f.left.observation_ref,operational_state_ref:"state:PRODUCED",process_stage_ref:"stage:PRODUCTION",claim:{kind:"QUANTITY",value:100,unit_ref:"unit:EACH"}})});
 it("preserves a truly comparable incompatible claim as unresolved conflict without source voting",async()=>{const f=await fixture(95,"state:PRODUCED","stage:PRODUCTION","location:production"),temporal=await createGovernedTemporalBindingV1({version:1,left_observation_ref:f.left.observation_ref,right_observation_ref:f.right.observation_ref,left_effectivity:{from:f.left.effective_from!},right_effectivity:{from:f.left.effective_from!}}),result=await composeExistingObservedOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:f.scope,observations:[f.left,{...f.right,effective_from:f.left.effective_from}],temporal_bindings:[temporal],representation_relationships:[],coverage:[]}),retrieved=await retrieveCanonicalStructuredRealityV1(result.canonical_reality,f.left.observation_ref);expect(result.alignment.claim_relationships[0]).toMatchObject({relationship:"CONFLICTING_COMPARABLE_CLAIM",semantically_comparable:true});expect(result.canonical_reality.composition_status).toBe("UNRESOLVED_CONFLICT");expect(retrieved).toMatchObject({retrieval_status:"UNRESOLVED_CONFLICT",comparison_candidates:[]});expect(retrieved.audit_observations).toHaveLength(2)});
});
