import{describe,expect,it}from"vitest";
import{bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1}from"../../cockpit/operational.signal.evaluation.scope.v1";
import{preserveGovernedOperationsFactV1,type GovernedOperationsFactV1}from"../../industrial/preservation/governed.operational.fact.preservation.v1";
import{composeCanonicalOperationalRealityV1}from"../canonical.operational.reality.composition.v1";
import{alignGovernedMultiSourceOperationalRealityV1,createGovernedSubjectBindingV1,createGovernedTemporalBindingV1}from"../governed.multi-source.reality.alignment.v1";
import{createGovernedOperationalRepresentationV1,createObservationBreadthV1,createOperationalRepresentationRelationshipV1}from"../governed.operational.representation.v1";
import{bridgeGovernedPersistentSourceFactV1,createGovernedPersistentFactSemanticBindingV1}from"../persistent.source.observation.bridge.v1";

const t1="2026-08-26T10:00:00.000Z",t2="2026-08-26T10:15:00.000Z",asOf="2026-08-26T10:30:00.000Z";
const metadata=(source:string,connector=`connector:${source}`)=>({tenantId:"1",companyId:"1",sourceSystem:source,connectorIdentityId:connector,connectorRevision:1,acquisitionReference:`acquisition:${source}`,authorizationReference:`authorization:${source}`,acquiredAt:asOf,capabilityId:"read",sourceRepresentation:`representation-format:${source}`});
async function scope(request="request:1"){const s=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"REQUEST_DATASET",request_id:request,company_id:"company:1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:refresh:7"});return bindOperationalSignalsToScopeV1({scope:s,request_id:request,company_id:"company:1",evidence_as_of:asOf,evaluated_at:"2026-08-26T10:31:00.000Z"})}
async function facts(){const produced=await preserveGovernedOperationsFactV1("MATERIAL_MOVEMENTS",{movement_id:"M1",production_order_id:"P1",article:"X",quantity:100,unit:"EA",type:"PRODUCED",occurred_at:t1},metadata("execution")),received=await preserveGovernedOperationsFactV1("INVENTORY",{inventory_id:"I1",warehouse_id:"WH1",sku:"X",quantity:95,unit:"EA",observed_at:t2},metadata("warehouse"));return{produced,received}}
async function rep(f:GovernedOperationsFactV1,b:Awaited<ReturnType<typeof scope>>,ref:string,endpoints?:readonly string[]){return createGovernedOperationalRepresentationV1({version:1,representation_ref:ref,company_id:"company:1",domain_ref:"domain:operations",governed_scope_refs:[b.scope.scope_id],subjects:[f.role_bindings.subject],source_binding_refs:endpoints??[f.provenance.connector_identity_id],provenance_refs:[`provenance:${ref}`],causal_lineage_refs:[`lineage:${ref}`],observability:"PERSISTENT",refreshability:"INDEPENDENTLY_REFRESHABLE",refresh_policy_ref:"refresh-policy:scheduled"})}
async function subjectBinding(a:GovernedOperationsFactV1,ar:Awaited<ReturnType<typeof rep>>,b?:GovernedOperationsFactV1,br?:Awaited<ReturnType<typeof rep>>){return createGovernedSubjectBindingV1({version:1,outcome:"SAME_SUBJECT",members:[{representation_identity_ref:ar.representation_id,local_subject_ref:a.source_fact_ref},{representation_identity_ref:(br??ar).representation_id,local_subject_ref:(b??a).source_fact_ref+(!b?":corroborated":"")}],canonical_subject:a.role_bindings.subject,binding_evidence_refs:["evidence:subject-map"],provenance_refs:["provenance:subject-map"],causal_lineage_refs:["lineage:subject-map"]})}
async function semantic(f:GovernedOperationsFactV1,r:Awaited<ReturnType<typeof rep>>,state:string,stage:string,location:string){return createGovernedPersistentFactSemanticBindingV1({version:1,fact_ref:f.fact_id,representation_id:r.representation_id,dimension_ref:"dimension:quantity",operational_state_ref:state,process_stage_ref:stage,location_refs:[location],qualification_refs:["qualification:semantic-map"],provenance_refs:["provenance:semantic-map"],causal_lineage_refs:["lineage:semantic-map"]})}

describe("persistent source observation bridge v1",()=>{
 it("projects a governed persistent fact deterministically without losing semantic, temporal, provenance, or snapshot lineage",async()=>{const b=await scope(),{produced}=await facts(),r=await rep(produced,b,"representation:execution",[produced.provenance.connector_identity_id,"endpoint:A","endpoint:B"]),s=await subjectBinding(produced,r),m=await semantic(produced,r,"state:PRODUCED","stage:PRODUCTION","location:production"),input={version:1 as const,fact:produced,representation:r,evaluation_scope:b,subject_binding:s,semantic_binding:m},a=await bridgeGovernedPersistentSourceFactV1(input),c=await bridgeGovernedPersistentSourceFactV1(input);expect(a).toEqual(c);expect(a).toMatchObject({observation_ref:produced.fact_id,local_subject_ref:produced.source_fact_ref,observed_at:t1,effective_from:t1,dimension_ref:"dimension:quantity",operational_state_ref:"state:PRODUCED",process_stage_ref:"stage:PRODUCTION",evidence_role:"REALIZED_EVENT",claim:{kind:"QUANTITY",value:100,unit_ref:"unit:EACH"},location_refs:["location:production"]});expect(a.provenance_refs).toEqual(expect.arrayContaining(["provenance:semantic-map","provenance:representation:execution"]));expect(a.causal_lineage_refs).toEqual(expect.arrayContaining([produced.fact_id,produced.fact_digest,"snapshot:refresh:7"]));expect(Object.isFrozen(a)&&Object.isFrozen(a.source)&&Object.isFrozen(a.location_refs)).toBe(true);expect(JSON.stringify(a)).not.toMatch(/authority_tier|recommendation|source_rank|representation_role/)});
 it("fails closed for forged representation, semantic binding, source, company/request scope, and non-persistent input",async()=>{const b=await scope(),{produced}=await facts(),r=await rep(produced,b,"representation:execution"),s=await subjectBinding(produced,r),m=await semantic(produced,r,"state:PRODUCED","stage:PRODUCTION","location:production"),base={version:1 as const,fact:produced,representation:r,evaluation_scope:b,subject_binding:s,semantic_binding:m};await expect(bridgeGovernedPersistentSourceFactV1({...base,representation:{...r,representation_ref:"forged"}})).rejects.toThrow("PERSISTENT_OBSERVATION_REPRESENTATION_INVALID");await expect(bridgeGovernedPersistentSourceFactV1({...base,semantic_binding:{...m,operational_state_ref:"state:FORGED"}})).rejects.toThrow("PERSISTENT_OBSERVATION_BINDING_INVALID");const unrelated=await createGovernedOperationalRepresentationV1({version:1,representation_ref:"representation:other",company_id:"company:1",domain_ref:"domain:operations",governed_scope_refs:[b.scope.scope_id],subjects:[produced.role_bindings.subject],source_binding_refs:["connector:other"],provenance_refs:["provenance:other"],causal_lineage_refs:["lineage:other"],observability:"PERSISTENT",refreshability:"INDEPENDENTLY_REFRESHABLE",refresh_policy_ref:"refresh-policy:scheduled"});await expect(bridgeGovernedPersistentSourceFactV1({...base,representation:unrelated,semantic_binding:await semantic(produced,unrelated,"state:PRODUCED","stage:PRODUCTION","location:production")})).rejects.toThrow("PERSISTENT_OBSERVATION_SOURCE_BINDING_MISMATCH");await expect(bridgeGovernedPersistentSourceFactV1({...base,representation:{...r,observability:"REQUEST_BOUND_AD_HOC"}as never})).rejects.toThrow("PERSISTENT_OBSERVATION_REPRESENTATION_INVALID");const otherScope=await scope("request:2");await expect(bridgeGovernedPersistentSourceFactV1({...base,evaluation_scope:otherScope})).rejects.toThrow("PERSISTENT_OBSERVATION_SCOPE_MISMATCH")});
 it("keeps endpoint count out of I-ORS breadth and preserves separately observable derived representations without independence",async()=>{const b=await scope(),{produced,received}=await facts(),one=await rep(produced,b,"representation:execution",[produced.provenance.connector_identity_id,"endpoint:A"]),many=await rep(produced,b,"representation:execution",[produced.provenance.connector_identity_id,"endpoint:A","endpoint:B"]),warehouse=await rep(received,b,"representation:warehouse"),breadth=await createObservationBreadthV1({version:1,evaluation_scope:b,representations:[one,many,warehouse]}),derived=await createOperationalRepresentationRelationshipV1({version:1,relationship_kind:"DERIVED_FROM",source:warehouse,target:one,provenance_refs:["provenance:derived"],causal_lineage_refs:["lineage:derived"]});expect(one.representation_id).toBe(many.representation_id);expect(breadth.count).toBe(2);expect(derived).toMatchObject({independence:"NOT_ESTABLISHED",source_representation_id:warehouse.representation_id,target_representation_id:one.representation_id})});
 it("bridges produced 100 and warehouse-received 95 through canonical operational reality without reconciling them",async()=>{const b=await scope(),{produced,received}=await facts(),a=await rep(produced,b,"representation:execution"),r=await rep(received,b,"representation:warehouse"),s=await subjectBinding(produced,a,received,r),ao=await bridgeGovernedPersistentSourceFactV1({version:1,fact:produced,representation:a,evaluation_scope:b,subject_binding:s,semantic_binding:await semantic(produced,a,"state:PRODUCED","stage:PRODUCTION","location:production")}),ro=await bridgeGovernedPersistentSourceFactV1({version:1,fact:received,representation:r,evaluation_scope:b,subject_binding:s,semantic_binding:await semantic(received,r,"state:WAREHOUSE_RECEIVED","stage:RECEIVING","location:warehouse")}),temporal=await createGovernedTemporalBindingV1({version:1,left_observation_ref:ao.observation_ref,right_observation_ref:ro.observation_ref,left_effectivity:{from:ao.effective_from!},right_effectivity:{from:ro.effective_from!},relevance_evidence_refs:["evidence:process-sequence"]}),aligned=await alignGovernedMultiSourceOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:b,observations:[ro,ao],temporal_bindings:[temporal],representation_relationships:[]}),reality=await composeCanonicalOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:b,evidence:aligned.canonical_evidence,coverage:[]});expect(aligned.claim_relationships[0]).toMatchObject({relationship:"COMPLEMENTARY",semantically_comparable:false});expect(reality).toMatchObject({composition_kind:"CANONICAL_OPERATIONAL_REALITY",composition_status:"COMPOSED",recommended:false,grants_authority:false,grants_execution:false});expect(reality.semantic_groups).toHaveLength(2);expect(JSON.stringify({aligned,reality})).not.toMatch(/missing|lost|scrap|explanation/)});
});
