import{describe,expect,it}from"vitest";
import{bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1}from"../../cockpit/operational.signal.evaluation.scope.v1";
import type{CanonicalOrderFact}from"../../industrial/canonicalization/authoritative.order.fact";
import{evaluateOperationsBaselineCommitmentFeasibilityV1}from"../../industrial/cognition/operations.baseline.commitment.feasibility.v1";
import{assessOperationsObjectiveStateV1}from"../../industrial/cognition/operations.objective.state.v1";
import{bindOperationsOrderDeliveryCommitmentV1}from"../../industrial/cognition/operations.protected.objective.v1";
import{createGovernedSubjectBindingV1,type GovernedRepresentationObservationInputV1}from"../governed.multi-source.reality.alignment.v1";
import{evaluateGovernedPlanRealityElementComparisonV1}from"../plan.reality.comparison.doctrine.v1";
import{applyGovernedPlanRealityMaterialityPolicyV1}from"../plan.reality.materiality.policy.v1";

const asOf="2026-08-13T10:00:00.000Z",due="2026-08-20T10:00:00.000Z",meta={evidence_observed_at:"2026-08-13T09:00:00.000Z",evidence_refs:["evidence:1"],qualification_refs:["qualification:1"],provenance_refs:["provenance:1"],causal_lineage_refs:["lineage:1"]};
function order():CanonicalOrderFact{return{factId:"industrial-order:order-1",factFamily:"INDUSTRIAL_ORDER",schemaVersion:"1.0.0",owner:{tenantId:"tenant-1",companyId:"company-1",ownerId:"owner-1"},source:{systemId:"system-1",externalObjectId:"O1",externalObjectVersion:"2"},observedAt:meta.evidence_observed_at,effectiveAt:"2026-08-13T08:00:00.000Z",order:{sku:"SKU1",quantity:{value:5,unit:"EACH"},status:"OPEN",dueAt:due},provenance:{acquisitionReference:"acquisition-1",authorizationReference:"authorization-1",acquiredAt:"2026-08-13T09:05:00.000Z",capabilityId:"read_orders",connectorIdentityId:"connector:1",connectorRevision:1,sourceRepresentation:"PRODUCTION_REST_ERP_ORDERS_V1",transformationId:"PRODUCTION_REST_ERP_ORDER_TO_CANONICAL_ORDER",transformationVersion:"1.0.0",canonicalSchemaVersion:"1.0.0",tenantId:"tenant-1",companyId:"company-1",ownerId:"owner-1",sourceSystem:"system-1",externalObjectId:"O1",externalObjectVersion:"2"}}}
async function foundation(){const fact=order(),scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"ENTITY",request_id:"request-1",company_id:"company-1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1",entity:{entity_type:"ORDER",entity_ref:fact.factId}}),binding=await bindOperationalSignalsToScopeV1({scope,request_id:"request-1",company_id:"company-1",evidence_as_of:asOf,evaluated_at:"2026-08-13T10:01:00.000Z"}),commitment=await bindOperationsOrderDeliveryCommitmentV1({version:1,order_fact:fact,evaluation_scope:binding,selected_objective_kind:"ORDER_DELIVERY_COMMITMENT",objective_selection_ref:"selection:objective",plan_element_ref:"plan:O1",protected_subject_ref:"subject:O1",qualification_refs:["qualification:order"],causal_lineage_refs:["lineage:order"],plan_lineage_refs:["lineage:plan"]}),subject=await createGovernedSubjectBindingV1({version:1,outcome:"SAME_SUBJECT",members:[{representation_identity_ref:"representation:plan",local_subject_ref:"plan:O1"},{representation_identity_ref:"representation:reality",local_subject_ref:"reality:O1"}],canonical_subject:{version:1,company_id:"company-1",domain_ref:"domain:operations",profile_ref:"profile:operations",profile_digest:"a".repeat(64),subject_kind:"ORDER",subject_ref:fact.factId,subject_id:"subject:O1",subject_digest:"b".repeat(64),digest_algorithm:"SHA-256",grants_execution:false},binding_evidence_refs:["evidence:subject"],provenance_refs:["provenance:subject"],causal_lineage_refs:["lineage:subject"]});return{binding,commitment,subject}}
type Observation=GovernedRepresentationObservationInputV1&Readonly<{request_id:string;company_id:string;scope_id:string;scope_digest:string;evidence_as_of:string}>;
async function comparison(value=5){const f=await foundation(),base={version:1 as const,request_id:"request-1",company_id:"company-1",scope_id:f.binding.scope.scope_id,scope_digest:f.binding.scope.scope_digest,evidence_as_of:asOf,subject_binding:f.subject,observed_at:asOf,effective_from:asOf,dimension_ref:"dimension:delivery",operational_state_ref:"state:WAREHOUSE_RECEIVED",location_refs:["location:FG01"],qualification_refs:["qualification:comparison"],provenance_refs:["provenance:comparison"],causal_lineage_refs:["lineage:comparison"]},plan={...base,observation_ref:"observation:plan",source:{}as never,local_subject_ref:"plan:O1",evidence_role:"CURRENT_PLAN"as const,claim:{kind:"QUANTITY"as const,value:5,unit_ref:"unit:EACH"}},reality={...base,observation_ref:"observation:reality",source:{}as never,local_subject_ref:"reality:O1",evidence_role:"CURRENT_FACT"as const,claim:{kind:"QUANTITY"as const,value,unit_ref:"unit:EACH"}},result=await evaluateGovernedPlanRealityElementComparisonV1({version:1,evaluation_scope:f.binding,plan_reference_eligibility:"ELIGIBLE",applicable_plan_context_ref:"plan-context:1",applicable_plan_context_digest:"c".repeat(64),plan_element_ref:"plan:O1",plan_target:plan as Observation,reality_observation:reality as Observation});return{...f,result}}
async function objective(quantity:number,boundary:"COMPLETE"|"PARTIAL"="COMPLETE"){const f=await foundation(),feasibility=await evaluateOperationsBaselineCommitmentFeasibilityV1({version:1,commitment:f.commitment,baseline_semantics:"BASELINE_CURRENT_PLAN",evidence_selection_ref:"selection:1",plan_orders:[{...meta,order_fact_ref:f.commitment.order_fact_ref,order_version_ref:f.commitment.order_version_ref,item_ref:f.commitment.item_ref,quantity:f.commitment.committed_quantity,due_at:f.commitment.committed_due_at}],availability:[{...meta,availability_ref:"availability:1",kind:"EFFECTIVE_INVENTORY",item_ref:f.commitment.item_ref,quantity:{value:quantity,unit_ref:"unit:EACH"},available_at:asOf}],evidence_boundary:boundary}),assessment=await assessOperationsObjectiveStateV1({version:1,assessment_perspective:"CURRENT_EXPECTED",commitment:f.commitment,feasibility});return{...f,assessment}}

describe("governed plan-reality materiality policy v1",()=>{
 it("preserves exact target satisfaction as element alignment support",async()=>{const c=await comparison(),result=await applyGovernedPlanRealityMaterialityPolicyV1({version:1,comparison:c.result});expect(result).toMatchObject({disposition:"ELEMENT_ALIGNED_SUPPORT",supports_element_alignment:true,supports_element_drifting:false,supports_element_misalignment:false,scope_aggregation_performed:false})});
 it("fails closed when exact element satisfaction conflicts with a breached objective",async()=>{const[c,o]=await Promise.all([comparison(),objective(2)]),result=await applyGovernedPlanRealityMaterialityPolicyV1({version:1,comparison:c.result,protected_objective:o.commitment.objective_binding,objective_assessment:o.assessment});expect(result).toMatchObject({disposition:"NOT_ASSERTABLE",supports_element_alignment:false,supports_element_drifting:false,supports_element_misalignment:false,reason_codes:["OBJECTIVE_STATE_CONFLICT"]})});
 it("does not turn a value difference alone into drifting or misalignment",async()=>{const c=await comparison(4),result=await applyGovernedPlanRealityMaterialityPolicyV1({version:1,comparison:c.result});expect(result).toMatchObject({disposition:"NOT_ASSERTABLE",supports_element_drifting:false,supports_element_misalignment:false});expect(result.reason_codes).toContain("OBJECTIVE_STATE_UNRESOLVED")});
 it("freezes protected-objective breach as material incompatibility",async()=>{const[c,o]=await Promise.all([comparison(4),objective(2)]),result=await applyGovernedPlanRealityMaterialityPolicyV1({version:1,comparison:c.result,protected_objective:o.commitment.objective_binding,objective_assessment:o.assessment});expect(o.assessment.objective_state).toBe("BREACHED");expect(result).toMatchObject({disposition:"MATERIAL_INCOMPATIBILITY_ESTABLISHED",supports_element_alignment:false,supports_element_drifting:false,supports_element_misalignment:true,reason_codes:["PROTECTED_OBJECTIVE_BREACHED"]})});
 it("keeps preserved-but-deviated realization unresolved until recoverability doctrine exists",async()=>{const[c,o]=await Promise.all([comparison(4),objective(5)]),result=await applyGovernedPlanRealityMaterialityPolicyV1({version:1,comparison:c.result,protected_objective:o.commitment.objective_binding,objective_assessment:o.assessment});expect(o.assessment.objective_state).toBe("PRESERVED");expect(result).toMatchObject({disposition:"DEVIATION_RECOVERABILITY_UNRESOLVED",supports_element_drifting:false,supports_element_misalignment:false,reason_codes:["DRIFTING_RECOVERABILITY_POLICY_REQUIRED"]})});
 it("keeps incomplete objective evidence non-assertable",async()=>{const[c,o]=await Promise.all([comparison(4),objective(5,"PARTIAL")]),result=await applyGovernedPlanRealityMaterialityPolicyV1({version:1,comparison:c.result,protected_objective:o.commitment.objective_binding,objective_assessment:o.assessment});expect(result).toMatchObject({disposition:"NOT_ASSERTABLE",supports_element_misalignment:false,reason_codes:["OBJECTIVE_STATE_UNRESOLVED"]})});
 it("ignores pressure, intrinsic reality state, breadth, and source count",async()=>{const c=await comparison(),baseline=await applyGovernedPlanRealityMaterialityPolicyV1({version:1,comparison:c.result}),unrelated=await applyGovernedPlanRealityMaterialityPolicyV1({version:1,comparison:c.result,decision_pressure:"HIGH",reality_state:"UNSTABLE",observation_breadth:9,source_count:9}as any);expect(unrelated).toEqual(baseline)});
 it("fails closed on forged comparison, objective, or cross-scope evidence",async()=>{const[c,o]=await Promise.all([comparison(4),objective(2)]);await expect(applyGovernedPlanRealityMaterialityPolicyV1({version:1,comparison:{...c.result,comparison_digest:"0".repeat(64)}}as any)).rejects.toThrow("PLAN_REALITY_COMPARISON_INTEGRITY_INVALID");await expect(applyGovernedPlanRealityMaterialityPolicyV1({version:1,comparison:c.result,protected_objective:{...o.commitment.objective_binding,governing_plan_element_refs:["plan:other"]},objective_assessment:o.assessment}as any)).rejects.toThrow();await expect(applyGovernedPlanRealityMaterialityPolicyV1({version:1,comparison:c.result,protected_objective:o.commitment.objective_binding,objective_assessment:{...o.assessment,scope_id:"scope:other"}}as any)).rejects.toThrow()});
});
