import{describe,expect,it}from"vitest";
import{bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1}from"../../cockpit/operational.signal.evaluation.scope.v1";
import{createGovernedSubjectBindingV1,type GovernedRepresentationObservationInputV1}from"../governed.multi-source.reality.alignment.v1";
import{evaluateGovernedPlanRealityElementComparisonV1}from"../plan.reality.comparison.doctrine.v1";

const at="2026-08-20T10:00:00.000Z";
async function fixture(){const scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"ENTITY",request_id:"request:1",company_id:"company:1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1",entity:{entity_type:"ORDER",entity_ref:"order:1"}}),binding=await bindOperationalSignalsToScopeV1({scope,request_id:"request:1",company_id:"company:1",evidence_as_of:at,evaluated_at:"2026-08-20T10:01:00.000Z"}),subject=await createGovernedSubjectBindingV1({version:1,outcome:"SAME_SUBJECT",members:[{representation_identity_ref:"representation:plan",local_subject_ref:"plan:order:1"},{representation_identity_ref:"representation:reality",local_subject_ref:"reality:order:1"}],canonical_subject:{version:1,company_id:"company:1",domain_ref:"domain:operations",profile_ref:"profile:operations",profile_digest:"a".repeat(64),subject_kind:"ORDER",subject_ref:"order:1",subject_id:"subject:order:1",subject_digest:"b".repeat(64),digest_algorithm:"SHA-256",grants_execution:false},binding_evidence_refs:["evidence:subject"],provenance_refs:["provenance:subject"],causal_lineage_refs:["lineage:subject"]});return{binding,subject}}
type Observation=GovernedRepresentationObservationInputV1&Readonly<{request_id:string;company_id:string;scope_id:string;scope_digest:string;evidence_as_of:string}>;
async function observations(){const f=await fixture(),base={version:1 as const,request_id:"request:1",company_id:"company:1",scope_id:f.binding.scope.scope_id,scope_digest:f.binding.scope.scope_digest,evidence_as_of:at,local_subject_ref:"plan:order:1",subject_binding:f.subject,observed_at:at,effective_from:at,dimension_ref:"dimension:inventory",operational_state_ref:"state:AVAILABLE",location_refs:["location:FG01"],qualification_refs:["qualification:1"],provenance_refs:["provenance:1"],causal_lineage_refs:["lineage:1"]},plan={...base,observation_ref:"observation:plan",source:{}as never,evidence_role:"CURRENT_PLAN"as const,claim:{kind:"QUANTITY"as const,value:100,unit_ref:"unit:EACH"}},reality={...base,local_subject_ref:"reality:order:1",observation_ref:"observation:reality",source:{}as never,evidence_role:"CURRENT_FACT"as const,claim:{kind:"QUANTITY"as const,value:100,unit_ref:"unit:EACH"}};return{...f,plan:plan as Observation,reality:reality as Observation}}
async function compare(overrides:Record<string,unknown>={}){const f=await observations();return evaluateGovernedPlanRealityElementComparisonV1({version:1,evaluation_scope:f.binding,plan_reference_eligibility:"ELIGIBLE",applicable_plan_context_ref:"plan-context:1",applicable_plan_context_digest:"a".repeat(64),plan_element_ref:"plan-element:1",plan_target:f.plan,reality_observation:f.reality,...overrides}as any)}

describe("governed plan-reality element comparison doctrine v1",()=>{
 it("freezes exact governed target satisfaction without source ownership",async()=>{const a=await compare(),f=await observations(),b=await compare({plan_target:{...f.plan,source:{kind:"ANY_OTHER_SOURCE"}},reality_observation:{...f.reality,source:{kind:"YET_ANOTHER_SOURCE"}}});expect(a).toMatchObject({comparison_status:"ASSERTABLE",disposition:"EXACT_TARGET_SATISFIED",supports_element_alignment:true,establishes_deviation:false,establishes_drifting:false,establishes_misalignment:false,source_identity_independent:true});expect(b.disposition).toBe(a.disposition)});
 it.each([["subject",async()=>{const f=await observations();return{reality_observation:{...f.reality,subject_binding:{...f.reality.subject_binding,outcome:"DIFFERENT_SUBJECT",canonical_subject:undefined}}}},"SUBJECT_MISMATCH"],["state",async()=>{const f=await observations();return{reality_observation:{...f.reality,operational_state_ref:"state:PRODUCED"}}},"OPERATIONAL_STATE_MISMATCH"],["location",async()=>{const f=await observations();return{reality_observation:{...f.reality,location_refs:["location:OTHER"]}}},"LOCATION_MISMATCH"],["unit",async()=>{const f=await observations();return{reality_observation:{...f.reality,claim:{...f.reality.claim,unit_ref:"unit:KG"}}}},"UNIT_MISMATCH"],["time",async()=>{const f=await observations();return{reality_observation:{...f.reality,effective_from:"2026-08-20T11:00:00.000Z"}}},"TEMPORAL_RELATIONSHIP_UNRESOLVED"]]as const)("fails closed on %s incompatibility",async(_name,build,reason)=>{const result=await compare(await build());expect(result).toMatchObject({comparison_status:"NOT_ASSERTABLE",disposition:"NOT_COMPARABLE",supports_element_alignment:false});expect(result.reason_codes).toContain(reason)});
 it("does not treat a future target as currently misaligned",async()=>{const f=await observations(),result=await compare({plan_target:{...f.plan,effective_from:"2026-08-20T18:00:00.000Z"}});expect(result).toMatchObject({comparison_status:"NOT_ASSERTABLE",disposition:"NOT_COMPARABLE",establishes_drifting:false,establishes_misalignment:false});expect(result.reason_codes).toContain("TEMPORAL_RELATIONSHIP_UNRESOLVED")});
 it("establishes an exact comparable difference but requires governed materiality",async()=>{const f=await observations(),result=await compare({reality_observation:{...f.reality,claim:{kind:"QUANTITY",value:95,unit_ref:"unit:EACH"}}});expect(result).toMatchObject({comparison_status:"NOT_ASSERTABLE",disposition:"DEVIATION_ESTABLISHED_MATERIALITY_UNRESOLVED",establishes_deviation:true,establishes_drifting:false,establishes_misalignment:false});expect(result.reason_codes).toContain("MATERIALITY_POLICY_REQUIRED")});
 it.each(["NO_APPLICABLE_PLAN","AMBIGUOUS_PLAN","INSUFFICIENT_EVIDENCE","SCOPE_MISMATCH","NON_ASSERTABLE_PLAN"]as const)("keeps %s non-assertable",async status=>{const result=await compare({plan_reference_eligibility:status});expect(result.comparison_status).toBe("NOT_ASSERTABLE");expect(result.establishes_misalignment).toBe(false);expect(result.reason_codes).toContain(status)});
 it("keeps process stages complementary rather than directly conflicting",async()=>{const f=await observations(),result=await compare({plan_target:{...f.plan,operational_state_ref:"state:WAREHOUSE_RECEIVED",process_stage_ref:"stage:WAREHOUSE"},reality_observation:{...f.reality,operational_state_ref:"state:PRODUCED",process_stage_ref:"stage:PRODUCTION",claim:{kind:"QUANTITY",value:100,unit_ref:"unit:EACH"}}});expect(result.disposition).toBe("NOT_COMPARABLE");expect(result.reason_codes).toEqual(expect.arrayContaining(["OPERATIONAL_STATE_MISMATCH","PROCESS_STAGE_MISMATCH"]))});
 it("keeps intrinsic reality state, observation breadth, and legacy risk outside comparison",async()=>{const baseline=await compare(),unrelated=await compare({reality_state:"UNSTABLE",observation_breadth:99,stockout_risk:1,supplier_dependency:1});expect(unrelated).toEqual(baseline);expect(unrelated).not.toHaveProperty("reality_state");expect(unrelated).not.toHaveProperty("observation_breadth")});
});
