import { describe,expect,it } from "vitest";
import { bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1 } from "../../cockpit/operational.signal.evaluation.scope.v1";
import { createGovernedSourceEventCoverageCapabilityV1 } from "../../cognition/governed.source.event.coverage.capability.v1";
import { composeCanonicalOperationalRealityV1,verifyCanonicalOperationalRealityCompositionV1,type CanonicalOperationalRealityEvidenceV1 } from "../canonical.operational.reality.composition.v1";
const at="2026-08-17T10:00:00.000Z",hex=(x:string)=>x.repeat(64).slice(0,64);
async function scope(company="company:1",request="request:1"){const s=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"REQUEST_DATASET",request_id:request,company_id:company,domain:"operations",evidence_selection_ref:"evidence-selection:current",source_snapshot_ref:"source-snapshot:current"});return bindOperationalSignalsToScopeV1({scope:s,request_id:request,company_id:company,evidence_as_of:at,evaluated_at:"2026-08-17T10:01:00.000Z"})}
function evidence(binding:Awaited<ReturnType<typeof scope>>,n=1,overrides:Partial<CanonicalOperationalRealityEvidenceV1>={}):CanonicalOperationalRealityEvidenceV1{return{version:1,tenant_id:"tenant:1",company_id:binding.scope.company_id,request_id:binding.scope.request_id,scope_id:binding.scope.scope_id,scope_digest:binding.scope.scope_digest,evidence_as_of:at,evidence_ref:`evidence:${n}`,evidence_digest:hex(String(n)),source_identity_ref:`source:${n}`,source_namespace:`namespace:${n}`,semantic_key:`inventory:item-${n}`,claim_digest:hex(String(n+2)),evidence_role:"CURRENT_FACT",canonical_subject_refs:[`subject:${n}`],canonical_location_refs:[`location:${n}`],qualification_refs:[`qualification:${n}`],provenance_refs:[`provenance:${n}`],causal_lineage_refs:[`lineage:${n}`],...overrides}}
async function coverage(binding:Awaited<ReturnType<typeof scope>>,status:"COMPLETE"|"PARTIAL"="COMPLETE"){return createGovernedSourceEventCoverageCapabilityV1({version:1,capability_policy_ref:"policy:coverage",capability_policy_version:"1",tenant_id:"tenant:1",source_identity_ref:"source:1",source_profile_ref:"source-profile:1",source_profile_version:"1",source_boundary_ref:"source-boundary:1",evaluation_scope:binding,event_class_capabilities:[{domain_ref:"domain:operations",event_class_ref:"event-class:inventory",required_semantic_field_refs:["field:item"],guaranteed_semantic_field_refs:status==="COMPLETE"?["field:item"]:[],optional_semantic_field_refs:[]}],coverage_start:"2026-08-01T00:00:00.000Z",coverage_end:at,coverage_status:status,profile_capability_evidence_refs:["evidence:profile"],snapshot_completeness_evidence_refs:status==="COMPLETE"?["evidence:complete"]:[],qualification_refs:status==="COMPLETE"?["qualification:complete"]:[],provenance_refs:["provenance:coverage"],causal_lineage_refs:["lineage:coverage"]})}
async function compose(items?:CanonicalOperationalRealityEvidenceV1[],withCoverage=false){const s=await scope();return composeCanonicalOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:s,evidence:items??[evidence(s)],coverage:withCoverage?[await coverage(s)]:[]})}
describe("MULTI-SOURCE-REALITY-CANONICAL-COMPLETION-WU1",()=>{
 it("composes and verifies one governed source deterministically",async()=>{const a=await compose(),b=await compose();expect(a).toEqual(b);expect(a.semantic_groups[0]?.status).toBe("SINGLE_SOURCE");await expect(verifyCanonicalOperationalRealityCompositionV1(a)).resolves.toBeUndefined()});
 it("composes complementary source families without conflict",async()=>{const s=await scope(),a=evidence(s,1,{semantic_key:"inventory:item",claim_digest:hex("a")}),b=evidence(s,2,{semantic_key:"future-supply:item",claim_digest:hex("b"),evidence_role:"GOVERNED_FUTURE_SUPPLY"}),c=evidence(s,3,{semantic_key:"planned-production:item",claim_digest:hex("c"),evidence_role:"PLANNED_PRODUCTION"});const v=await composeCanonicalOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:s,evidence:[c,a,b],coverage:[]});expect(v.composition_status).toBe("COMPOSED");expect(v.semantic_groups).toHaveLength(3)});
 it("treats identical claims from different sources as complementary",async()=>{const s=await scope(),claim=hex("a"),v=await composeCanonicalOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:s,evidence:[evidence(s,1,{semantic_key:"inventory:item",claim_digest:claim}),evidence(s,2,{semantic_key:"inventory:item",claim_digest:claim})],coverage:[]});expect(v.semantic_groups[0]?.status).toBe("COMPLEMENTARY");expect(v.source_identity_refs).toEqual(["source:1","source:2"])});
 it("retains source, canonical identity, qualification, provenance and lineage",async()=>{const v=await compose();expect(v).toMatchObject({source_identity_refs:["source:1"],canonical_subject_refs:["subject:1"],canonical_location_refs:["location:1"],qualification_refs:["qualification:1"],provenance_refs:["provenance:1"],causal_lineage_refs:["lineage:1"]})});
 it("binds the exact scope and evidence boundary",async()=>{const v=await compose();expect(v).toMatchObject({company_id:"company:1",request_id:"request:1",evidence_as_of:at,evidence_selection_ref:"evidence-selection:current",source_snapshot_ref:"source-snapshot:current"})});
 it("reuses COMPLETE coverage without asserting absence",async()=>{const v=await compose(undefined,true);expect(v.coverage_refs).toHaveLength(1);expect(v).not.toHaveProperty("asserts_event_absence")});
 it("accepts partial coverage and does not infer absence",async()=>{const s=await scope(),v=await composeCanonicalOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:s,evidence:[evidence(s)],coverage:[await coverage(s,"PARTIAL")]});expect(v.composition_status).toBe("COMPOSED")});
 it("surfaces unresolved same-semantic contradiction",async()=>{const s=await scope(),v=await composeCanonicalOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:s,evidence:[evidence(s,1,{semantic_key:"inventory:item",claim_digest:hex("a")}),evidence(s,2,{semantic_key:"inventory:item",claim_digest:hex("b")})],coverage:[]});expect(v.composition_status).toBe("UNRESOLVED_CONFLICT");expect(v.semantic_groups[0]).not.toHaveProperty("selected_evidence_ref")});
 it("applies only explicit governed resolution",async()=>{const s=await scope(),r="resolution:currentness-1",v=await composeCanonicalOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:s,evidence:[evidence(s,1,{semantic_key:"inventory:item",claim_digest:hex("a"),governed_resolution_ref:r}),evidence(s,2,{semantic_key:"inventory:item",claim_digest:hex("b"),governed_resolution_ref:r,governed_resolution_selected:true})],coverage:[]});expect(v.semantic_groups[0]).toMatchObject({status:"GOVERNED_RESOLVED",selected_evidence_ref:"evidence:2",governed_resolution_ref:r})});
 it("does not resolve by provider name",async()=>{const s=await scope(),v=await composeCanonicalOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:s,evidence:[evidence(s,1,{semantic_key:"x",claim_digest:hex("a"),source_namespace:"MES"}),evidence(s,2,{semantic_key:"x",claim_digest:hex("b"),source_namespace:"ERP"})],coverage:[]});expect(v.composition_status).toBe("UNRESOLVED_CONFLICT")});
 it("accepts effective inventory, future supply, production and realized events",async()=>{const s=await scope(),roles=["CURRENT_FACT","GOVERNED_FUTURE_SUPPLY","PLANNED_PRODUCTION","REALIZED_EVENT"] as const,v=await composeCanonicalOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:s,evidence:roles.map((role,i)=>evidence(s,i+1,{semantic_key:`family:${role}`,evidence_role:role})),coverage:[]});expect(v.semantic_groups).toHaveLength(4)});
 it("accepts explicit governed user-confirmed current evidence",async()=>{const s=await scope(),v=await composeCanonicalOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:s,evidence:[evidence(s,1,{evidence_role:"USER_CONFIRMED_CURRENT",source_namespace:"user-confirmation"})],coverage:[]});expect(v.current_reality).toBe(true)});
 it.each(["scenario","counterfactual","optimizer","simulation","learned_expectation","llm_result","knowledge_override"])("rejects %s contamination",async key=>{const s=await scope(),item={...evidence(s),[key]:"artifact:1"};await expect(composeCanonicalOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:s,evidence:[item] as never,coverage:[]})).rejects.toThrow("OPERATIONAL_REALITY_NON_CURRENT_EVIDENCE_REJECTED")});
 it("rejects alternative file plans unless admitted as current evidence",async()=>{const s=await scope(),item={...evidence(s),scenario:"xlsx:alternative-plan"};await expect(composeCanonicalOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:s,evidence:[item] as never,coverage:[]})).rejects.toThrow()});
 it("remains format neutral for admitted CSV or XLSX evidence",async()=>{const s=await scope(),v=await composeCanonicalOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:s,evidence:[evidence(s,1,{source_namespace:"admitted-file:xlsx"})],coverage:[]});expect(v.source_identity_refs).toEqual(["source:1"])});
 it.each(["VISION","GRADUATE","JUNIOR","SENIOR","PRINCIPAL","CHARTER"])("is tier-independent for %s",async()=>{const v=await compose();expect(v.tier_independent).toBe(true);expect(v).not.toHaveProperty("tier")});
 it("rejects cross-tenant evidence",async()=>{const s=await scope();await expect(composeCanonicalOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:s,evidence:[evidence(s,1,{tenant_id:"tenant:2"})],coverage:[]})).rejects.toThrow("OPERATIONAL_REALITY_CONTEXT_MISMATCH")});
 it("rejects cross-company evidence",async()=>{const s=await scope();await expect(composeCanonicalOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:s,evidence:[evidence(s,1,{company_id:"company:2"})],coverage:[]})).rejects.toThrow("OPERATIONAL_REALITY_CONTEXT_MISMATCH")});
 it("rejects cross-request, scope, digest and as-of evidence",async()=>{const s=await scope();for(const x of [{request_id:"request:2"},{scope_id:"scope:other"},{scope_digest:hex("f")},{evidence_as_of:"2026-08-17T09:00:00.000Z"}])await expect(composeCanonicalOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:s,evidence:[evidence(s,1,x)],coverage:[]})).rejects.toThrow("OPERATIONAL_REALITY_CONTEXT_MISMATCH")});
 it("rejects forged evidence digests and composition digests",async()=>{const s=await scope();await expect(composeCanonicalOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:s,evidence:[evidence(s,1,{evidence_digest:"forged"})],coverage:[]})).rejects.toThrow("OPERATIONAL_REALITY_EVIDENCE_DIGEST_INVALID");const v=await compose();await expect(verifyCanonicalOperationalRealityCompositionV1({...v,composition_digest:hex("0")})).rejects.toThrow("OPERATIONAL_REALITY_INTEGRITY_INVALID")});
 it("does not recommend, authorize, execute, or depend on commercial capacity",async()=>{const v=await compose();expect(v).toMatchObject({recommended:false,executable:false,grants_authority:false,grants_execution:false});expect(v).not.toHaveProperty("commercial_plan");expect(v).not.toHaveProperty("credit_balance")});
 it("recursively freezes canonical output",async()=>{const v=await compose();expect(Object.isFrozen(v)).toBe(true);expect(Object.isFrozen(v.semantic_groups)).toBe(true);expect(Object.isFrozen(v.semantic_groups[0])).toBe(true)});
});
