import type { DataClassification } from "../../security/encryption.domains";
import type { KnowledgeExposureEligibilityV1 } from "../knowledge-exposure/persistence";
import type { KnowledgeProjectionRepresentationV1 } from "../knowledge-exposure/knowledge.exposure.contracts.v1";

export const OUTBOUND_DISCLOSURE_POLICY_VERSION="OUTBOUND_DISCLOSURE_POLICY_V1" as const;
export type CommunicationFamilyV1="TENANT_OPERATIONAL_DISCLOSURE"|"COMMERCIAL_LIFECYCLE_COMMUNICATION"|"ORGANIZATIONAL_GOVERNANCE_COMMUNICATION"|"SECURITY_GOVERNANCE_NOTIFICATION"|"PLATFORM_OPERATIONAL_ALERT"|"SYSTEM_HEALTH_SIGNAL"|"INTERNAL_RUNTIME_COMMUNICATION";
export type DisclosureChannelV1="EMAIL"|"SMS"|"WHATSAPP"|"WEBHOOK";
export interface DisclosureRecipientV1{readonly version:1;readonly recipient_id:string;readonly recipient_class:"AUTHORIZED_BUSINESS_RECIPIENT";readonly entitlement_reference:string;readonly tenant_id:string;readonly company_id:string;}
export interface OutboundDisclosureAdmissionRequestV1{readonly version:1;readonly eligibility:KnowledgeExposureEligibilityV1;readonly authority_reference:string;readonly governance_references:readonly string[];readonly communication_family:CommunicationFamilyV1;readonly recipient:DisclosureRecipientV1;readonly channel:DisclosureChannelV1;readonly representation:KnowledgeProjectionRepresentationV1;readonly classification:DataClassification;readonly requested_at:string;readonly expires_at:string;readonly correlation_id:string;readonly causal_references:readonly string[];}
export interface OutboundDisclosureAdmissionV1{readonly version:1;readonly disclosure_id:string;readonly decision_id:string;readonly binding_id:string;readonly knowledge_consumption_id:string;readonly authority_reference:string;readonly governance_references:readonly string[];readonly tenant_id:string;readonly company_id:string;readonly purpose:string;readonly communication_family:CommunicationFamilyV1;readonly manifest_id:string;readonly projection_digest:string;readonly recipient:DisclosureRecipientV1;readonly channel:DisclosureChannelV1;readonly representation:KnowledgeProjectionRepresentationV1;readonly classification:DataClassification;readonly policy_version:typeof OUTBOUND_DISCLOSURE_POLICY_VERSION;readonly admitted_at:string;readonly expires_at:string;readonly correlation_id:string;readonly causal_references:readonly string[];readonly canonical_digest:string;}
export interface OutboundDisclosureConsumptionClaimV1{readonly version:1;readonly disclosure_id:string;readonly authority_reference:string;readonly recipient_id:string;readonly entitlement_reference:string;readonly channel:DisclosureChannelV1;readonly representation:KnowledgeProjectionRepresentationV1;readonly manifest_id:string;readonly projection_digest:string;readonly consuming_runtime:string;readonly correlation_id:string;readonly causal_references:readonly string[];}
export interface OutboundDisclosureDispatchEligibilityV1 extends OutboundDisclosureAdmissionV1{readonly disclosure_consumption_id:string;readonly consumed_at:string;readonly transport_executed:false;}
export type OutboundDisclosureFailureCode="DISCLOSURE_REQUEST_INVALID"|"DISCLOSURE_ELIGIBILITY_INVALID"|"DISCLOSURE_AUTHORITY_SUBSTITUTED"|"DISCLOSURE_PURPOSE_NOT_ADMITTED"|"DISCLOSURE_FAMILY_NOT_ADMITTED"|"DISCLOSURE_OWNER_SUBSTITUTED"|"DISCLOSURE_RECIPIENT_INVALID"|"DISCLOSURE_RECIPIENT_SUBSTITUTED"|"DISCLOSURE_CHANNEL_NOT_ADMITTED"|"DISCLOSURE_CHANNEL_SUBSTITUTED"|"DISCLOSURE_REPRESENTATION_SUBSTITUTED"|"DISCLOSURE_PROJECTION_SUBSTITUTED"|"DISCLOSURE_CURRENT_STATE_INVALID"|"DISCLOSURE_EXPIRED"|"DISCLOSURE_NOT_FOUND"|"DISCLOSURE_IDENTITY_CONFLICT"|"DISCLOSURE_PERSISTENCE_FAILED"|"DISCLOSURE_REPLAYED"|"DISCLOSURE_AUDIT_FAILED";
export class OutboundDisclosureError extends Error{constructor(readonly code:OutboundDisclosureFailureCode){super(code);this.name="OutboundDisclosureError";}}
export interface OutboundDisclosureCurrentStateV1{readonly authority_current:boolean;readonly recipient_entitled:boolean;readonly ownership_current:boolean;readonly channel_permitted:boolean;}
export interface OutboundDisclosureRepositoryV1{persist(admission:OutboundDisclosureAdmissionV1):Promise<"CREATED"|"IDENTICAL">;read(id:string):Promise<OutboundDisclosureAdmissionV1|null>;consume(admission:OutboundDisclosureAdmissionV1,claim:OutboundDisclosureConsumptionClaimV1,id:string,at:string):Promise<boolean>;audit(event:Readonly<Record<string,string|undefined>>):Promise<void>;}
export interface OutboundDisclosureCurrentStateRepositoryV1{verifyCurrent(admission:OutboundDisclosureAdmissionV1,claim:OutboundDisclosureConsumptionClaimV1,now:string):Promise<OutboundDisclosureCurrentStateV1>;}
