import { createHash,randomUUID } from "node:crypto";
import { deepCopyAndFreeze } from "../knowledge-exposure/knowledge.projection.guard.v1";
import { buildOutboundDisclosureAdmissionV1 } from "./outbound.disclosure.policy.v1";
import { OutboundDisclosureError,type OutboundDisclosureAdmissionRequestV1,type OutboundDisclosureConsumptionClaimV1,type OutboundDisclosureCurrentStateRepositoryV1,type OutboundDisclosureDispatchEligibilityV1,type OutboundDisclosureFailureCode,type OutboundDisclosureRepositoryV1 } from "./outbound.disclosure.contracts.v1";
const digest=(v:unknown)=>createHash("sha256").update(JSON.stringify(v),"utf8").digest("hex"),equal=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b),fail=(c:OutboundDisclosureFailureCode):never=>{throw new OutboundDisclosureError(c);};
export class OutboundDisclosureRuntimeV1{
 constructor(private readonly repository:OutboundDisclosureRepositoryV1,private readonly current:OutboundDisclosureCurrentStateRepositoryV1,private readonly now:()=>string=()=>new Date().toISOString()){}
 async admit(request:OutboundDisclosureAdmissionRequestV1){if(!Object.isFrozen(request))fail("DISCLOSURE_REQUEST_INVALID");const admission=buildOutboundDisclosureAdmissionV1(request,this.now()),disposition=await this.repository.persist(admission);return deepCopyAndFreeze({version:1 as const,disposition,admission});}
 async consume(unsafe:OutboundDisclosureConsumptionClaimV1):Promise<OutboundDisclosureDispatchEligibilityV1>{const c=deepCopyAndFreeze(unsafe) as OutboundDisclosureConsumptionClaimV1,found=await this.repository.read(c.disclosure_id);if(!found)throw new OutboundDisclosureError("DISCLOSURE_NOT_FOUND");const a=found;const deny=async(code:OutboundDisclosureFailureCode,kind="SUBSTITUTION_DENIED")=>{await this.repository.audit({audit_event_id:`outbound-disclosure-audit:${randomUUID()}`,event_kind:kind,disclosure_id:a.disclosure_id,outcome:"DENIED",failure_code:code,projection_digest:a.projection_digest,correlation_id:c.correlation_id,causal_references_json:JSON.stringify(c.causal_references),recorded_at:this.now()});fail(code);};
  if(!equal(buildOutboundDisclosureAdmissionV1({version:1,eligibility:{version:1,decision_id:a.decision_id,binding_id:a.binding_id,consumption_id:a.knowledge_consumption_id,principal_id:"persisted",session_id:"persisted",membership_id:"persisted",tenant_id:a.tenant_id,company_id:a.company_id,operation:"OUTBOUND_DISCLOSURE",purpose:a.purpose,target_class:"AUTHORIZED_BUSINESS_RECIPIENT",target_identity:a.recipient.recipient_id,target_region:"persisted",requested_retention:"NO_RETENTION",manifest_id:a.manifest_id,projection_digest:a.projection_digest,knowledge_digests:[],correlation_id:a.correlation_id,causal_references:a.causal_references,policy_version:"persisted",consumed_at:a.admitted_at},authority_reference:a.authority_reference,governance_references:a.governance_references,communication_family:a.communication_family,recipient:a.recipient,channel:a.channel,representation:a.representation,classification:a.classification,requested_at:a.admitted_at,expires_at:a.expires_at,correlation_id:a.correlation_id,causal_references:a.causal_references},a.admitted_at),a))await deny("DISCLOSURE_IDENTITY_CONFLICT");
  if(Date.parse(a.expires_at)<=Date.parse(this.now()))await deny("DISCLOSURE_EXPIRED","EXPIRY_DENIED");if(c.authority_reference!==a.authority_reference)await deny("DISCLOSURE_AUTHORITY_SUBSTITUTED");if(c.recipient_id!==a.recipient.recipient_id||c.entitlement_reference!==a.recipient.entitlement_reference)await deny("DISCLOSURE_RECIPIENT_SUBSTITUTED");if(c.channel!==a.channel)await deny("DISCLOSURE_CHANNEL_SUBSTITUTED");if(c.representation!==a.representation)await deny("DISCLOSURE_REPRESENTATION_SUBSTITUTED");if(c.manifest_id!==a.manifest_id||c.projection_digest!==a.projection_digest)await deny("DISCLOSURE_PROJECTION_SUBSTITUTED");
  const s=await this.current.verifyCurrent(a,c,this.now());if(!s.authority_current||!s.recipient_entitled||!s.ownership_current||!s.channel_permitted)await deny("DISCLOSURE_CURRENT_STATE_INVALID","CURRENT_STATE_DENIED");const at=this.now(),id=`outbound-disclosure-consumption:sha256:${digest({disclosure_id:a.disclosure_id,consumed_at:at,correlation_id:c.correlation_id})}`;if(!await this.repository.consume(a,c,id,at))await deny("DISCLOSURE_REPLAYED","REPLAY_DENIED");return deepCopyAndFreeze({...a,disclosure_consumption_id:id,consumed_at:at,transport_executed:false}) as OutboundDisclosureDispatchEligibilityV1;
 }
}
