import { deepCopyAndFreeze } from "../knowledge-exposure/knowledge.projection.guard.v1";
import { OutboundDisclosureError,type OutboundDisclosureAdmissionV1,type OutboundDisclosureConsumptionClaimV1,type OutboundDisclosureCurrentStateRepositoryV1,type OutboundDisclosureCurrentStateV1,type OutboundDisclosureRepositoryV1 } from "./outbound.disclosure.contracts.v1";
const array=(v:unknown):readonly string[]=>{try{const x=JSON.parse(String(v));if(Array.isArray(x)&&x.every(y=>typeof y==="string"))return Object.freeze([...x]);}catch{}throw new OutboundDisclosureError("DISCLOSURE_PERSISTENCE_FAILED");};
export class D1OutboundDisclosureRepositoryV1 implements OutboundDisclosureRepositoryV1{
 constructor(private readonly db:D1Database){}
 async persist(a:OutboundDisclosureAdmissionV1):Promise<"CREATED"|"IDENTICAL">{const old=await this.db.prepare("SELECT canonical_digest FROM outbound_disclosure_admissions WHERE disclosure_id=?").bind(a.disclosure_id).first<{canonical_digest:string}>();if(old){if(old.canonical_digest!==a.canonical_digest)throw new OutboundDisclosureError("DISCLOSURE_IDENTITY_CONFLICT");return"IDENTICAL";}const r=a.recipient,insert=this.db.prepare(`INSERT INTO outbound_disclosure_admissions SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,? FROM knowledge_exposure_decisions d JOIN knowledge_exposure_projection_bindings b ON b.decision_id=d.decision_id JOIN knowledge_exposure_consumptions c ON c.decision_id=d.decision_id AND c.binding_id=b.binding_id WHERE d.decision_id=? AND b.binding_id=? AND c.consumption_id=? AND d.authority_reference=? AND d.operation='OUTBOUND_DISCLOSURE' AND d.purpose=? AND d.tenant_id=? AND d.company_id=? AND d.target_identity=? AND b.manifest_id=? AND b.projection_digest=?`).bind(a.disclosure_id,a.decision_id,a.binding_id,a.knowledge_consumption_id,a.authority_reference,JSON.stringify(a.governance_references),a.tenant_id,a.company_id,a.purpose,a.communication_family,a.manifest_id,a.projection_digest,r.recipient_id,r.recipient_class,r.entitlement_reference,a.channel,a.representation,a.classification,a.policy_version,a.admitted_at,a.expires_at,a.correlation_id,JSON.stringify(a.causal_references),a.canonical_digest,a.decision_id,a.binding_id,a.knowledge_consumption_id,a.authority_reference,a.purpose,a.tenant_id,a.company_id,r.recipient_id,a.manifest_id,a.projection_digest),audit=this.statement({audit_event_id:`audit:admit:${a.disclosure_id}`,event_kind:"ADMISSION_PERSISTED",disclosure_id:a.disclosure_id,outcome:"ADMITTED",projection_digest:a.projection_digest,correlation_id:a.correlation_id,causal_references_json:JSON.stringify(a.causal_references),recorded_at:a.admitted_at});try{const results=await this.db.batch([insert,audit]);if(results[0]?.meta.changes!==1)throw new Error("lineage");return"CREATED";}catch{throw new OutboundDisclosureError("DISCLOSURE_PERSISTENCE_FAILED");}}
 async read(id:string):Promise<OutboundDisclosureAdmissionV1|null>{const x=await this.db.prepare("SELECT * FROM outbound_disclosure_admissions WHERE disclosure_id=?").bind(id).first<Record<string,unknown>>();if(!x)return null;return deepCopyAndFreeze({version:1,disclosure_id:x.disclosure_id,decision_id:x.decision_id,binding_id:x.binding_id,knowledge_consumption_id:x.knowledge_consumption_id,authority_reference:x.authority_reference,governance_references:array(x.governance_references_json),tenant_id:x.tenant_id,company_id:x.company_id,purpose:x.purpose,communication_family:x.communication_family,manifest_id:x.manifest_id,projection_digest:x.projection_digest,recipient:{version:1,recipient_id:x.recipient_id,recipient_class:x.recipient_class,entitlement_reference:x.entitlement_reference,tenant_id:x.tenant_id,company_id:x.company_id},channel:x.channel,representation:x.representation,classification:x.classification,policy_version:x.policy_version,admitted_at:x.admitted_at,expires_at:x.expires_at,correlation_id:x.correlation_id,causal_references:array(x.causal_references_json),canonical_digest:x.canonical_digest}) as OutboundDisclosureAdmissionV1;}
 async consume(a:OutboundDisclosureAdmissionV1,c:OutboundDisclosureConsumptionClaimV1,id:string,at:string):Promise<boolean>{try{await this.db.batch([this.db.prepare("INSERT INTO outbound_disclosure_consumptions VALUES (?,?,?,?,?,?,?)").bind(id,a.disclosure_id,c.consuming_runtime,at,c.correlation_id,JSON.stringify(c.causal_references),"CONSUMED"),this.statement({audit_event_id:`audit:consume:${id}`,event_kind:"CONSUMED",disclosure_id:a.disclosure_id,disclosure_consumption_id:id,outcome:"CONSUMED",projection_digest:a.projection_digest,correlation_id:c.correlation_id,causal_references_json:JSON.stringify(c.causal_references),recorded_at:at})]);return true;}catch{return false;}}
 async audit(e:Readonly<Record<string,string|undefined>>){try{await this.statement(e).run();}catch{throw new OutboundDisclosureError("DISCLOSURE_AUDIT_FAILED");}}
 private statement(e:Readonly<Record<string,string|undefined>>){return this.db.prepare("INSERT INTO outbound_disclosure_audit_events VALUES (?,?,?,?,?,?,?,?,?,?)").bind(e.audit_event_id,e.event_kind,e.disclosure_id,e.disclosure_consumption_id??null,e.outcome,e.failure_code??null,e.projection_digest,e.correlation_id,e.causal_references_json??"[]",e.recorded_at);}
}
export class D1OutboundDisclosureCurrentStateV1 implements OutboundDisclosureCurrentStateRepositoryV1{
 constructor(private readonly db:D1Database,private readonly policy:(a:OutboundDisclosureAdmissionV1,c:OutboundDisclosureConsumptionClaimV1)=>Promise<Pick<OutboundDisclosureCurrentStateV1,"authority_current"|"recipient_entitled"|"channel_permitted">>){}
 async verifyCurrent(a:OutboundDisclosureAdmissionV1,c:OutboundDisclosureConsumptionClaimV1,now:string):Promise<OutboundDisclosureCurrentStateV1>{const x=await this.db.prepare("SELECT EXISTS(SELECT 1 FROM oir_tenant_company_ownership WHERE tenant_id=? AND company_id=? AND effective_from<=? AND (effective_until IS NULL OR effective_until>?)) ownership_current").bind(a.tenant_id,a.company_id,now,now).first<{ownership_current:number}>(),p=await this.policy(a,c);return Object.freeze({...p,ownership_current:x?.ownership_current===1});}
}
