import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import { getSession, identityControlLabelV1, projectServerSession, setAnonymousSession } from "./auth/AuthProvider.ts";
import { IdentityClientErrorV1, IdentityClientV1 } from "./identity.client.ts";
const response=(body:unknown,status=200)=>Promise.resolve(new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}}));
describe("ID registration server-session projection",()=>{
 it("boots labels from anonymous or registered server session state",async()=>{let fetcher=async()=>response({version:1,status:"ANONYMOUS"});let client=new IdentityClientV1(fetcher as any),session=projectServerSession(await client.session());assert.deepEqual(session,{status:"ANONYMOUS"});assert.equal(identityControlLabelV1(session),"ID");fetcher=async()=>response({version:1,status:"REGISTERED",email:"User.Name@example.com",expires_at:"2099-01-01T00:00:00.000Z"});client=new IdentityClientV1(fetcher as any);session=projectServerSession(await client.session());assert.deepEqual(session,{status:"REGISTERED",email:"User.Name@example.com",expires_at:"2099-01-01T00:00:00.000Z"});assert.equal(identityControlLabelV1(session),"ID · User.Name@example.com")});
 it("restores verified email after verification and removes it on logout",async()=>{const calls:{path:string;init?:RequestInit}[]=[],fetcher=async(path:string,init?:RequestInit)=>{calls.push({path,init});if(path.endsWith("challenge"))return response({challenge_id:"challenge",expires_at:"later"});if(path.endsWith("verify"))return response({status:"REGISTERED",expires_at:"later"});if(path.endsWith("session"))return response({status:"REGISTERED",email:"person@example.com",expires_at:"later"});return response({status:"ANONYMOUS"})},client=new IdentityClientV1(fetcher as any);assert.deepEqual(await client.challenge("person@example.com"),{challenge_id:"challenge",expires_at:"later"});const registered=await client.verify("challenge","12345678");assert.deepEqual(registered,{status:"REGISTERED",email:"person@example.com",expires_at:"later"});assert.equal(identityControlLabelV1(projectServerSession(registered)),"ID · person@example.com");const anonymous=await client.logout();assert.equal(identityControlLabelV1(projectServerSession(anonymous)),"ID");assert.deepEqual(calls.map(x=>x.path),["/identity/email/challenge","/identity/email/verify","/identity/session","/identity/logout"]);assert.ok(calls.every(x=>x.init?.credentials==="same-origin"));assert.ok(calls.every(x=>!x.path.startsWith("http")))});
 it("does not authenticate on challenge or bounded failure",async()=>{setAnonymousSession();const client=new IdentityClientV1((async()=>response({error:"EMAIL_DELIVERY_FAILED"},503))as any);await assert.rejects(client.challenge("person@example.com"),IdentityClientErrorV1);assert.deepEqual(getSession(),{status:"ANONYMOUS"})});
 it("shows verified email in the modal without browser persistence or organization fields",()=>{const files=["./auth/AuthProvider.ts","./identity.client.ts","./identity.modal.ts","./main.ts"].map(path=>readFileSync(new URL(path,import.meta.url),"utf8")).join("\n");assert.doesNotMatch(files,/localStorage|sessionStorage|principal_id|tenant_id|company_id|membership_id|role selector/i);assert.doesNotMatch(files,/type=["']password/i);assert.match(files,/identity-account-email/);assert.match(files,/escapeHtml\(registeredEmail\)/);assert.match(files,/Account identity only\. No organization or authority\./);assert.match(files,/challenge=undefined;onSession\(registered\);close\(\)/);assert.match(files,/conversation-invitation/)});
});
