import type { AccountSessionState } from "./auth/AuthProvider";
import { IdentityClientErrorV1, type IdentityClientV1 } from "./identity.client";
const safeError=(error:unknown)=>{const code=error instanceof IdentityClientErrorV1?error.code:"TEMPORARY_FAILURE";if(code==="EMAIL_INVALID"||code==="REQUEST_INVALID")return"Enter a valid email address.";if(code==="EMAIL_CHALLENGE_EXPIRED")return"That code has expired. Request a new one.";if(code==="EMAIL_CHALLENGE_INVALID")return"That code is not correct.";if(code==="EMAIL_CHALLENGE_ALREADY_USED")return"That code can no longer be used.";if(code==="EMAIL_DELIVERY_FAILED")return"Email delivery is temporarily unavailable.";return"PlannerAgent could not complete this request. Try again."};
const escapeHtml=(value:string)=>value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");
export function createIdentityModalV1(document:Document,client:IdentityClientV1,session:AccountSessionState,onSession:(value:AccountSessionState)=>void){const overlay=document.createElement("div");overlay.className="identity-overlay";overlay.setAttribute("role","presentation");const registeredEmail=session.status==="REGISTERED"?session.email:"";let stage:"EMAIL"|"CODE"|"REGISTERED"=session.status==="REGISTERED"?"REGISTERED":"EMAIL",email="",challenge:{challenge_id:string;expires_at:string}|undefined,busy=false;
 const close=()=>overlay.remove(),render=()=>{overlay.innerHTML=`<section class="identity-modal" role="dialog" aria-modal="true" aria-labelledby="identity-title"><button class="identity-close" type="button" aria-label="Close">&times;</button>${stage==="REGISTERED"?`<h2 id="identity-title">PlannerAgent ID</h2><p class="identity-account-email">${escapeHtml(registeredEmail)}</p><p class="identity-status">Registered</p><p class="identity-note">Account identity only. No organization or authority.</p><button class="identity-primary" data-action="logout" type="button">Logout</button>`:stage==="EMAIL"?`<h2 id="identity-title">Identify with PlannerAgent</h2><p class="identity-note">Continue with email. No password.</p><form data-form="email"><label for="identity-email">Email</label><input id="identity-email" type="email" autocomplete="email" required maxlength="320"><p class="identity-error" aria-live="polite"></p><button class="identity-primary" type="submit">Continue</button></form>`:`<h2 id="identity-title">Enter verification code</h2><p class="identity-note">Sent to ${escapeHtml(email)}</p><form data-form="code"><label for="identity-code">8-digit code</label><input id="identity-code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{8}" maxlength="8" required><p class="identity-error" aria-live="polite"></p><button class="identity-primary" type="submit">Verify</button></form><div class="identity-secondary-row"><button data-action="change" type="button">Change email</button><button data-action="resend" type="button">Resend code</button></div>`}</section>`;wire();};
 const fail=(error:unknown)=>{const target=overlay.querySelector<HTMLElement>(".identity-error");if(target)target.textContent=safeError(error)},run=async(task:()=>Promise<void>)=>{if(busy)return;busy=true;overlay.querySelectorAll<HTMLButtonElement|HTMLInputElement>("button,input").forEach(x=>x.disabled=true);try{await task()}catch(error){fail(error)}finally{busy=false;overlay.querySelectorAll<HTMLButtonElement|HTMLInputElement>("button,input").forEach(x=>x.disabled=false)}};
 const requestCode=async()=>{challenge=await client.challenge(email);stage="CODE";render();overlay.querySelector<HTMLInputElement>("#identity-code")?.focus()};
 const wire=()=>{overlay.querySelector(".identity-close")?.addEventListener("click",close);overlay.querySelector<HTMLFormElement>('[data-form="email"]')?.addEventListener("submit",event=>{event.preventDefault();const input=overlay.querySelector<HTMLInputElement>("#identity-email");email=input?.value.trim()??"";void run(requestCode)});const code=overlay.querySelector<HTMLInputElement>("#identity-code");code?.addEventListener("input",()=>{code.value=code.value.replace(/\D/g,"").slice(0,8)});overlay.querySelector<HTMLFormElement>('[data-form="code"]')?.addEventListener("submit",event=>{event.preventDefault();void run(async()=>{if(!challenge)throw new IdentityClientErrorV1("TEMPORARY_FAILURE");const registered=await client.verify(challenge.challenge_id,code?.value??"");challenge=undefined;onSession(registered);close()})});overlay.querySelector('[data-action="change"]')?.addEventListener("click",()=>{challenge=undefined;stage="EMAIL";render()});overlay.querySelector('[data-action="resend"]')?.addEventListener("click",()=>void run(requestCode));overlay.querySelector('[data-action="logout"]')?.addEventListener("click",()=>void run(async()=>{onSession(await client.logout());close()}));};render();return overlay;}
