import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import { getSession, projectServerSession, setAnonymousSession } from "./auth/AuthProvider.ts";
import { IdentityClientErrorV1, IdentityClientV1 } from "./identity.client.ts";
const response=(body:unknown,status=200)=>Promise.resolve(new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}}));
describe("ID registration server-session projection",()=>{
 it("boots anonymous and registered exclusively from the session endpoint",async()=>{let fetcher=async()=>response({version:1,status:"ANONYMOUS"});let client=new IdentityClientV1(fetcher as any);assert.deepEqual(projectServerSession(await client.session()),{status:"ANONYMOUS"});fetcher=async()=>response({version:1,status:"REGISTERED",expires_at:"2099-01-01T00:00:00.000Z"});client=new IdentityClientV1(fetcher as any);assert.deepEqual(projectServerSession(await client.session()),{status:"REGISTERED",expires_at:"2099-01-01T00:00:00.000Z"})});
 it("uses relative credentialed challenge, verify, session, and logout requests",async()=>{const calls:{path:string;init?:RequestInit}[]=[],fetcher=async(path:string,init?:RequestInit)=>{calls.push({path,init});if(path.endsWith("challenge"))return response({challenge_id:"challenge",expires_at:"later"});if(path.endsWith("verify"))return response({status:"REGISTERED",expires_at:"later"});return response({status:"ANONYMOUS"})},client=new IdentityClientV1(fetcher as any);assert.deepEqual(await client.session(),{status:"ANONYMOUS"});assert.deepEqual(await client.challenge("person@example.com"),{challenge_id:"challenge",expires_at:"later"});assert.deepEqual(await client.verify("challenge","12345678"),{status:"REGISTERED",expires_at:"later"});assert.deepEqual(await client.logout(),{status:"ANONYMOUS"});assert.deepEqual(calls.map(x=>x.path),["/identity/session","/identity/email/challenge","/identity/email/verify","/identity/logout"]);assert.ok(calls.every(x=>x.init?.credentials==="same-origin"));assert.ok(calls.every(x=>!x.path.startsWith("http")))});
 it("does not authenticate on challenge or bounded failure",async()=>{setAnonymousSession();const client=new IdentityClientV1((async()=>response({error:"EMAIL_DELIVERY_FAILED"},503))as any);await assert.rejects(client.challenge("person@example.com"),IdentityClientErrorV1);assert.deepEqual(getSession(),{status:"ANONYMOUS"})});
 it("binds the ID modal lifecycle without browser identity persistence or organization flow",()=>{const files=["./auth/AuthProvider.ts","./identity.client.ts","./identity.modal.ts","./main.ts"].map(path=>readFileSync(new URL(path,import.meta.url),"utf8")).join("\n");assert.doesNotMatch(files,/localStorage|sessionStorage|principal_id|tenant_id|company_id|membership_id|role selector/i);assert.doesNotMatch(files,/type=["']password/i);assert.match(files,/Continue with email/);assert.match(files,/createIdentityModalV1/);assert.match(files,/challenge=undefined;onSession\(registered\);close\(\)/);assert.match(files,/conversation-invitation/)});
});
