import type { IdentityRole } from "../identity/identity.types";
import type { CanonicalOperationalRealityCompositionV1 } from "../reality/canonical.operational.reality.composition.v1";
import { verifyCanonicalOperationalRealityCompositionV1 } from "../reality/canonical.operational.reality.composition.v1";
import type { CanonicalDecisionPressureCompositionV1 } from "../decision/canonical.decision.pressure.composition.v1";
import { verifyCanonicalDecisionPressureCompositionV1 } from "../decision/canonical.decision.pressure.composition.v1";
import type { GovernedObservedOperationalOutcomeV1 } from "../experience/observedOutcome";
import { verifyGovernedObservedOperationalOutcomeV1 } from "../experience/observedOutcome";
import type { GovernedExperienceLearningResultV1 } from "../learning/governedLearning";
import { verifyGovernedExperienceLearningResultV1 } from "../learning/governedLearning";

export type ExplanationClaimKindV1="IMPACT"|"DECISION_MARGIN"|"OPPORTUNITY"|"INFLUENCEABILITY"|"URGENCY"|"COST_OF_WAITING"|"WORKING_ATTENTION";
export type ExplanationEpistemicStatusV1="ESTABLISHED"|"UNRESOLVED"|"INSUFFICIENT_EVIDENCE";
export type ExplanationClaimV1=Readonly<{kind:ExplanationClaimKindV1;tenant_id:string;company_id:string;request_id:string;scope_id:string;scope_digest:string;artifact_ref:string;artifact_digest:string;status:ExplanationEpistemicStatusV1;evidence_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[]}>;
export type ExplanationContextV1=Readonly<{mode:"CURRENT"|"COUNTERFACTUAL";scenario_ref?:string;assumption_refs?:readonly string[]}>;
export type CanonicalExplanationBasisV1=Readonly<{version:1;explanation_kind:"CANONICAL_EXPLANATION_BASIS";tenant_id:string;company_id:string;request_id:string;scope_id:string;scope_digest:string;context:ExplanationContextV1;reality:Readonly<{ref:string;digest:string;status:"COMPOSED"|"UNRESOLVED_CONFLICT";semantic_groups:CanonicalOperationalRealityCompositionV1["semantic_groups"]}>;claims:readonly ExplanationClaimV1[];pressure?:Readonly<{ref:string;digest:string;status:CanonicalDecisionPressureCompositionV1["completeness_status"];components:CanonicalDecisionPressureCompositionV1["components"]}>;observed_outcome?:Readonly<{ref:string;digest:string;execution_status:string;comparison_status:string;operational_success_classified:false;causal_attribution_established:false}>;learned_guidance?:Readonly<{ref:string;digest:string;status:GovernedExperienceLearningResultV1["learning_status"];guidance_semantics:"GUIDANCE_ONLY";current_fact:false}>;evidence_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[];basis_id:string;basis_digest:string;digest_algorithm:"SHA-256";deterministic:true;tier_independent:true;recommended:false;executable:false;grants_authority:false;grants_execution:false;llm_authoritative:false}>;
export type ExplanationTierV1="VISION"|"GRADUATE"|"JUNIOR"|"SENIOR"|"PRINCIPAL"|"CHARTER";
export type ExplanationManifestationV1=Readonly<{basis_id:string;basis_digest:string;audience:IdentityRole;tier:ExplanationTierV1;detail:"SUMMARY"|"STANDARD"|"AUDIT";visible_sections:readonly ("SITUATION"|"EVIDENCE"|"CONSEQUENCE"|"TIMING"|"UNCERTAINTY"|"OUTCOME"|"GUIDANCE")[];truth_unchanged:true;recommended:false;grants_authority:false;grants_execution:false}>;

const forbidden=["commercial_plan","credit_balance","economic_capacity","provider","model","llm_output","recommendation","approval","delegation","execution_payload"];
const required=(v:string,c:string)=>{const x=v?.trim();if(!x)throw new Error(c);return x};
const refs=(v:readonly string[],c:string,empty=false)=>{if(!Array.isArray(v))throw new Error(c);const x=[...new Set(v.map(y=>required(y,c)))].sort();if(!empty&&!x.length)throw new Error(c);return x};
const canonical=(v:unknown):string=>Array.isArray(v)?`[${v.map(canonical).join(",")}]`:v&&typeof v==="object"?`{${Object.entries(v as Record<string,unknown>).filter(([,x])=>x!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(",")}}`:JSON.stringify(v);
async function sha(v:unknown){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(v)));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}
function freeze<T>(v:T):Readonly<T>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v as Record<string,unknown>).forEach(freeze);Object.freeze(v)}return v}
function same(x:{company_id:string;request_id:string;scope_id:string;scope_digest:string},r:CanonicalOperationalRealityCompositionV1){if(x.company_id!==r.company_id||x.request_id!==r.request_id||x.scope_id!==r.scope_id||x.scope_digest!==r.scope_digest)throw new Error("EXPLANATION_CONTEXT_MISMATCH")}
function semantic(v:CanonicalExplanationBasisV1){const{basis_id:_i,basis_digest:_d,digest_algorithm:_a,deterministic:_dt,tier_independent:_t,recommended:_r,executable:_e,grants_authority:_ga,grants_execution:_ge,llm_authoritative:_l,...x}=v;return x}

export async function createCanonicalExplanationBasisV1(input:Readonly<{version:1;reality:CanonicalOperationalRealityCompositionV1;context?:ExplanationContextV1;claims?:readonly ExplanationClaimV1[];pressure?:CanonicalDecisionPressureCompositionV1;observed_outcome?:GovernedObservedOperationalOutcomeV1;learned_guidance?:GovernedExperienceLearningResultV1}>):Promise<CanonicalExplanationBasisV1>{
 if(input.version!==1)throw new Error("EXPLANATION_VERSION_UNSUPPORTED");for(const k of forbidden)if(k in(input as object))throw new Error("EXPLANATION_UNSAFE_INPUT");await verifyCanonicalOperationalRealityCompositionV1(input.reality);const r=input.reality,context=input.context??{mode:"CURRENT"as const};if(context.mode==="CURRENT"&&(context.scenario_ref||context.assumption_refs?.length))throw new Error("EXPLANATION_CURRENT_SCENARIO_FORBIDDEN");if(context.mode==="COUNTERFACTUAL"&&!context.scenario_ref)throw new Error("EXPLANATION_SCENARIO_REQUIRED");
 if(input.pressure){await verifyCanonicalDecisionPressureCompositionV1(input.pressure);same(input.pressure,r)}if(input.observed_outcome){await verifyGovernedObservedOperationalOutcomeV1(input.observed_outcome);same(input.observed_outcome,r)}if(input.learned_guidance){await verifyGovernedExperienceLearningResultV1(input.learned_guidance);same(input.learned_guidance,r)}
 const claims=[...(input.claims??[])].map(c=>{if(c.tenant_id!==r.tenant_id||c.company_id!==r.company_id||c.request_id!==r.request_id||c.scope_id!==r.scope_id||c.scope_digest!==r.scope_digest)throw new Error("EXPLANATION_CONTEXT_MISMATCH");return freeze({...c,artifact_ref:required(c.artifact_ref,"EXPLANATION_CLAIM_REF_REQUIRED"),artifact_digest:/^[a-f0-9]{64}$/.test(c.artifact_digest)?c.artifact_digest:(()=>{throw new Error("EXPLANATION_CLAIM_DIGEST_INVALID")})(),evidence_refs:refs(c.evidence_refs,"EXPLANATION_EVIDENCE_REQUIRED"),qualification_refs:refs(c.qualification_refs,"EXPLANATION_QUALIFICATION_REQUIRED"),provenance_refs:refs(c.provenance_refs,"EXPLANATION_PROVENANCE_REQUIRED"),causal_lineage_refs:refs(c.causal_lineage_refs,"EXPLANATION_LINEAGE_REQUIRED")})}).sort((a,b)=>a.kind.localeCompare(b.kind));if(new Set(claims.map(c=>c.kind)).size!==claims.length)throw new Error("EXPLANATION_DUPLICATE_CLAIM");
 const evidence_refs=refs([...r.evidence_refs,...claims.flatMap(c=>c.evidence_refs),...(input.pressure?.evidence_refs??[])],"EXPLANATION_EVIDENCE_REQUIRED"),qualification_refs=refs([...r.qualification_refs,...claims.flatMap(c=>c.qualification_refs),...(input.pressure?.qualification_refs??[]),...(input.observed_outcome?.qualification_refs??[]),...(input.learned_guidance?.qualification_refs??[])],"EXPLANATION_QUALIFICATION_REQUIRED"),provenance_refs=refs([...r.provenance_refs,...claims.flatMap(c=>c.provenance_refs),...(input.pressure?.provenance_refs??[]),...(input.observed_outcome?.provenance_refs??[]),...(input.learned_guidance?.provenance_refs??[])],"EXPLANATION_PROVENANCE_REQUIRED"),causal_lineage_refs=refs([...r.causal_lineage_refs,r.composition_id,...claims.flatMap(c=>c.causal_lineage_refs),...(input.pressure?.causal_lineage_refs??[]),...(input.observed_outcome?.causal_lineage_refs??[]),...(input.learned_guidance?.causal_lineage_refs??[])],"EXPLANATION_LINEAGE_REQUIRED");
 const value={version:1 as const,explanation_kind:"CANONICAL_EXPLANATION_BASIS"as const,tenant_id:r.tenant_id,company_id:r.company_id,request_id:r.request_id,scope_id:r.scope_id,scope_digest:r.scope_digest,context:freeze({...context,...(context.assumption_refs?{assumption_refs:refs(context.assumption_refs,"EXPLANATION_ASSUMPTION_REQUIRED")}:{})}),reality:freeze({ref:r.composition_id,digest:r.composition_digest,status:r.composition_status,semantic_groups:r.semantic_groups}),claims,...(input.pressure?{pressure:freeze({ref:input.pressure.pressure_id,digest:input.pressure.pressure_digest,status:input.pressure.completeness_status,components:input.pressure.components})}:{}),...(input.observed_outcome?{observed_outcome:freeze({ref:input.observed_outcome.outcome_id,digest:input.observed_outcome.outcome_digest,execution_status:input.observed_outcome.execution_status,comparison_status:input.observed_outcome.comparison_status,operational_success_classified:false as const,causal_attribution_established:false as const})}:{}),...(input.learned_guidance?{learned_guidance:freeze({ref:input.learned_guidance.learning_id,digest:input.learned_guidance.learning_digest,status:input.learned_guidance.learning_status,guidance_semantics:"GUIDANCE_ONLY"as const,current_fact:false as const})}:{}),evidence_refs,qualification_refs,provenance_refs,causal_lineage_refs};const basis_digest=await sha(value);return freeze({...value,basis_id:`canonical-explanation-basis:sha256:${basis_digest}`,basis_digest,digest_algorithm:"SHA-256"as const,deterministic:true as const,tier_independent:true as const,recommended:false as const,executable:false as const,grants_authority:false as const,grants_execution:false as const,llm_authoritative:false as const})
}
export async function verifyCanonicalExplanationBasisV1(v:CanonicalExplanationBasisV1){const d=await sha(semantic(v));if(v.basis_digest!==d||v.basis_id!==`canonical-explanation-basis:sha256:${d}`||v.deterministic!==true||v.tier_independent!==true||v.recommended!==false||v.executable!==false||v.grants_authority!==false||v.grants_execution!==false||v.llm_authoritative!==false)throw new Error("EXPLANATION_INTEGRITY_INVALID")}
export function manifestCanonicalExplanationV1(basis:CanonicalExplanationBasisV1,input:Readonly<{audience:IdentityRole;tier:ExplanationTierV1}>):ExplanationManifestationV1{const detail:ExplanationManifestationV1["detail"]=input.audience==="ADMIN"?"AUDIT":input.audience==="EXECUTIVE"||input.audience==="DIRECTOR"?"SUMMARY":"STANDARD",all=["SITUATION","EVIDENCE","CONSEQUENCE","TIMING","UNCERTAINTY","OUTCOME","GUIDANCE"]as const,visible_sections=detail==="SUMMARY"?all.filter(x=>x!=="EVIDENCE"&&x!=="UNCERTAINTY"):all;return freeze({basis_id:basis.basis_id,basis_digest:basis.basis_digest,audience:input.audience,tier:input.tier,detail,visible_sections,truth_unchanged:true,recommended:false,grants_authority:false,grants_execution:false})}
