import {describe,expect,it} from "vitest";
import {bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1} from "../../cockpit/operational.signal.evaluation.scope.v1";
import {createProtectedOperationalObjectiveBindingV1} from "../../cognition/protected.operational.objective.v1";
import {createCanonicalDecisionMarginV1} from "../canonical.decision.margin.v1";

async function context(scope_type:"ENTITY"|"PATH"|"REQUEST_DATASET"="ENTITY"){
  const common={version:1 as const,scope_type,request_id:"request:1",company_id:"company:1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1"};
  const scope=await createOperationalSignalEvaluationScopeV1(scope_type==="ENTITY"?{...common,entity:{entity_type:"ORDER",entity_ref:"order:1"}}:scope_type==="PATH"?{...common,path:{subgraph_ref:"path:1",seed_refs:["subject:1"]}}:common);
  const evaluation_scope=await bindOperationalSignalsToScopeV1({scope,request_id:"request:1",company_id:"company:1",evidence_as_of:"2026-08-14T10:00:00Z",evaluated_at:"2026-08-14T10:01:00Z"});
  const protected_objective=await createProtectedOperationalObjectiveBindingV1({version:1,request_id:"request:1",company_id:"company:1",evaluation_scope,domain_profile_ref:"domain-profile:operations",domain_profile_version:"1",objective_kind_ref:"objective-kind:delivery",objective_ref:"objective:1",governing_expected_state_refs:["baseline:1"],governing_plan_element_refs:["plan-element:1"],protected_subject_refs:["subject:1"],commitment_criteria_refs:["criterion:1"],objective_selection_ref:"selection:objective",source_evidence_refs:["evidence:objective"],provenance_refs:["provenance:objective"],qualification_refs:["qualification:objective"],causal_lineage_refs:["lineage:objective"],plan_lineage_refs:["lineage:plan"],effective_at:"2026-08-14T09:00:00Z",evidence_as_of:evaluation_scope.evidence_as_of,evaluated_at:evaluation_scope.evaluated_at});
  return{evaluation_scope,protected_objective};
}
async function margin(overrides:Record<string,unknown>={}){const c=await context();return createCanonicalDecisionMarginV1({version:1,request_id:"request:1",company_id:"company:1",...c,governing_condition_ref:"condition:delay",governing_dimension_ref:"dimension:elapsed-time",current_position_ref:"position:current-delay",compromise_boundary_ref:"boundary:material-compromise",material_compromise_refs:["consequence:service-impact"],status:"AVAILABLE",remaining_margin:{value:1,unit_ref:"duration:days",measurement_ref:"measurement:remaining-delay"},epistemic_basis:"DETERMINISTIC",producer_ref:"producer:operations-margin",policy_ref:"policy:operations-margin-v1",evidence_refs:["evidence:condition","evidence:boundary"],qualification_refs:["qualification:condition"],provenance_refs:["provenance:condition"],causal_lineage_refs:["lineage:objective","lineage:condition","lineage:boundary"],evidence_as_of:c.evaluation_scope.evidence_as_of,evaluated_at:c.evaluation_scope.evaluated_at,...overrides} as any);}

describe("UNIVERSAL-DECISION-MARGIN-SEMANTICS-WU1",()=>{
  it("creates deterministic recursively immutable observational margin",async()=>{const a=await margin(),b=await margin();expect(a.margin_id).toBe(b.margin_id);expect(a).toMatchObject({observational_only:true,grants_authority:false,grants_execution:false,grants_remediation:false,company_global_claim:false});expect(Object.isFrozen(a)&&Object.isFrozen(a.remaining_margin)).toBe(true);});
  it("represents a reached boundary as exact zero without claiming compromise",async()=>{const x=await margin({status:"BOUNDARY_REACHED",remaining_margin:{value:0,unit_ref:"duration:days",measurement_ref:"measurement:boundary"}});expect(x.status).toBe("BOUNDARY_REACHED");expect(x).not.toHaveProperty("objective_state");});
  it("represents exceeded boundary semantically without negative margin",async()=>{const x=await margin({status:"BOUNDARY_EXCEEDED",remaining_margin:undefined});expect(x).not.toHaveProperty("remaining_margin");});
  it.each(["UNRESOLVED","INSUFFICIENT_EVIDENCE"] as const)("fails closed for %s without fabricating margin",async status=>{const x=await margin({status,remaining_margin:undefined});expect(x).not.toHaveProperty("remaining_margin");});
  it("enforces positive available and zero reached semantics",async()=>{await expect(margin({remaining_margin:{value:0,unit_ref:"duration:days",measurement_ref:"measurement:x"}})).rejects.toThrow("DECISION_MARGIN_AVAILABLE_MUST_BE_POSITIVE");await expect(margin({status:"BOUNDARY_REACHED",remaining_margin:{value:1,unit_ref:"duration:days",measurement_ref:"measurement:x"}})).rejects.toThrow("DECISION_MARGIN_REACHED_MUST_BE_ZERO");});
  it("rejects negative and unitless measures",async()=>{await expect(margin({remaining_margin:{value:-1,unit_ref:"duration:days",measurement_ref:"measurement:x"}})).rejects.toThrow("DECISION_MARGIN_MEASURE_INVALID");await expect(margin({remaining_margin:{value:1,unit_ref:"",measurement_ref:"measurement:x"}})).rejects.toThrow("DECISION_MARGIN_MEASURE_INVALID");});
  it("retains objective, condition, boundary, evidence, qualification, provenance, and lineage",async()=>{const x=await margin();expect(x.objective_binding_ref).toMatch(/^protected-operational-objective:/);expect(x.material_compromise_refs).toEqual(["consequence:service-impact"]);expect(x.qualification_refs).toEqual(["qualification:condition"]);});
  it("rejects request, company, scope, objective, and evidence-time substitution",async()=>{await expect(margin({company_id:"company:2"})).rejects.toThrow();const path=await context("PATH");await expect(margin({...path})).rejects.toThrow("DECISION_MARGIN_SCOPE_UNSUPPORTED");await expect(margin({evidence_as_of:"2026-08-14T09:59:00Z"})).rejects.toThrow("DECISION_MARGIN_TIME_BINDING_MISMATCH");});
  it.each(["evidence_refs","qualification_refs","provenance_refs","causal_lineage_refs","material_compromise_refs"])("requires %s",async key=>{await expect(margin({[key]:[]})).rejects.toThrow();});
  it("does not equate margin with slack, window, safety margin, response timing, or action",async()=>{const x=await margin();expect(JSON.stringify(x)).not.toMatch(/absorbable_delay|decision_window|safety_margin|response_timing|corrective_option|availableInDays/i);});
  it("has no tier, authority, recommendation, attention, pressure, or urgency dependency",async()=>{const x=await margin();expect(JSON.stringify(x)).not.toMatch(/VISION|JUNIOR|SENIOR|recommend|attention|urgency|cost_of_waiting|decision_pressure/i);});
  it("rejects learned estimates from deterministic v1",async()=>{await expect(margin({epistemic_basis:"QUALIFIED_LEARNED_ESTIMATE"})).rejects.toThrow("DECISION_MARGIN_EPISTEMIC_BASIS_UNSUPPORTED");});
  it("changes identity with natural dimension and boundary evidence",async()=>{const a=await margin(),b=await margin({governing_dimension_ref:"dimension:capacity",remaining_margin:{value:2,unit_ref:"capacity:units",measurement_ref:"measurement:capacity"}});expect(a.margin_id).not.toBe(b.margin_id);});
  it.each(["PATH","REQUEST_DATASET"] as const)("requires a future domain-owned projection for %s",async scope_type=>{const c=await context(scope_type);await expect(margin({...c})).rejects.toThrow("DECISION_MARGIN_SCOPE_UNSUPPORTED");});
});
