import {describe,expect,it} from "vitest";
import {bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1} from "../../cockpit/operational.signal.evaluation.scope.v1";
import {composeCanonicalDecisionPressureV1,verifyCanonicalDecisionPressureCompositionV1,type CanonicalPressureDimensionOperandV1} from "../canonical.decision.pressure.composition.v1";
import {createCanonicalDecisionPressureDimensionV1,type CanonicalDecisionPressureDimensionV1} from "../canonical.decision.pressure.dimension.v1";
import {createCanonicalDecisionPressureProducerCertificationV1} from "../canonical.decision.pressure.normalization.policy.v1";

const asOf="2026-08-13T10:00:00.000Z",evaluated="2026-08-13T10:01:00.000Z",meta={evidence_refs:["evidence:dimension"],qualification_refs:["qualification:dimension"],provenance_refs:["provenance:dimension"],causal_lineage_refs:["lineage:dimension"]};
async function binding(){const scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"ENTITY",request_id:"request-1",company_id:"company-1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1",entity:{entity_type:"ORDER",entity_ref:"order:1"}});return bindOperationalSignalsToScopeV1({scope,request_id:"request-1",company_id:"company-1",evidence_as_of:asOf,evaluated_at:evaluated});}
async function dimension(kind:"IMPACT"|"URGENCY"|"COST_OF_WAITING",value:number|string){const evaluation_scope=await binding(),continuous=typeof value==="number",cert=await createCanonicalDecisionPressureProducerCertificationV1({version:1,dimension:kind,producer_id:`producer:${kind.toLowerCase()}`,producer_version:"1",normalization_policy_id:`normalization-policy:${kind.toLowerCase()}`,normalization_policy_version:"1",domain_profile_id:"domain-profile:operations",domain_profile_version:"1",supported_scope_kinds:["ENTITY"],endpoint_semantics:"CANONICAL_PRESSURE_DIMENSION_ENDPOINTS_V1",monotonicity:"NON_DECREASING_CANONICAL_MAGNITUDE",reference_basis_semantics:"fixture canonical governed basis",evidence_requirement_refs:["requirement:evidence"],qualification_requirement_refs:["requirement:qualification"],composition_restriction:"DOMAIN_SCOPED_PROJECTION_NO_GENERIC_CHILD_COMPOSITION",provenance_required:true,causal_lineage_required:true,...(continuous?{projection_mode:"CONTINUOUS"as const,precision_policy:{kind:"DECIMAL_PLACES"as const,decimal_places:4}}:{projection_mode:"ORDINAL"as const,ordinal_vocabulary:kind==="IMPACT"?["LOW","MODERATE","HIGH","CRITICAL"]:["NEGLIGIBLE","LIMITED","MATERIAL","SEVERE"]} )});return createCanonicalDecisionPressureDimensionV1({version:1,dimension:kind,request_id:"request-1",company_id:"company-1",evaluation_scope,evidence_as_of:asOf,evaluated_at:evaluated,producer_certification:cert,normalization_input_refs:[`input:${kind}`],...meta,...(continuous?{projection_mode:"CONTINUOUS"as const,value,numerator_ref:`numerator:${kind}`,denominator_ref:`denominator:${kind}`,precision_decimal_places:4,...(kind==="URGENCY"?{decision_opportunity_status:"USEFUL_DECISION_REMAINS"as const}:{})}:{projection_mode:"ORDINAL"as const,ordinal_state:value as "LOW"})});}
function operand(d:CanonicalDecisionPressureDimensionV1):CanonicalPressureDimensionOperandV1{return{dimension:d.dimension,status:"ESTABLISHED",value:d,...meta};}
function missing(d:"URGENCY"|"COST_OF_WAITING",status:"UNRESOLVED"|"INSUFFICIENT_EVIDENCE"|"WINDOW_EXHAUSTED"):CanonicalPressureDimensionOperandV1{return{dimension:d,status,...meta};}
async function inputs(values:{impact?:string;urgency?:number;cow?:number}={}){return{version:1 as const,impact:operand(await dimension("IMPACT",values.impact??"HIGH")),urgency:operand(await dimension("URGENCY",values.urgency??0.2)),cost_of_waiting:operand(await dimension("COST_OF_WAITING",values.cow??0))};}

describe("PRESSURE-CANONICAL-COMPOSITION-WU1",()=>{
 it("creates and verifies deterministic immutable canonical Pressure",async()=>{const a=await composeCanonicalDecisionPressureV1(await inputs()),b=await composeCanonicalDecisionPressureV1(await inputs());expect(a.pressure_id).toBe(b.pressure_id);await expect(verifyCanonicalDecisionPressureCompositionV1(a)).resolves.toBeUndefined();expect(Object.isFrozen(a)&&Object.isFrozen(a.components)).toBe(true);});
 it("binds exact request company scope and evidence time",async()=>expect(await composeCanonicalDecisionPressureV1(await inputs())).toMatchObject({request_id:"request-1",company_id:"company-1",evidence_as_of:asOf,evaluated_at:evaluated}));
 it("accepts exact certified Impact Urgency and Cost of Waiting",async()=>expect((await composeCanonicalDecisionPressureV1(await inputs())).components.map(x=>x.dimension)).toEqual(["IMPACT","URGENCY","COST_OF_WAITING"]));
 it.each(["IMPACT","URGENCY","COST_OF_WAITING"]as const)("rejects forged certified %s",async kind=>{const x=await inputs(),key=kind==="IMPACT"?"impact":kind==="URGENCY"?"urgency":"cost_of_waiting",o=x[key];await expect(composeCanonicalDecisionPressureV1({...x,[key]:{...o,value:{...o.value!,dimension_digest:"forged"}}})).rejects.toThrow("PRESSURE_COMPOSITION_DIMENSION_INTEGRITY_INVALID");});
 it("binds exact immutable policy identity and digest",async()=>expect(await composeCanonicalDecisionPressureV1(await inputs())).toMatchObject({composition_policy_id:"pressure-composition-policy:certified-dimension-vector-v1",composition_policy_version:"1",aggregation_semantics:"VECTOR_PRESERVING_NO_AGGREGATE_WEIGHTS_OR_THRESHOLDS",composition_policy_digest:expect.any(String)}));
 it("represents low temporal Pressure without collapsing its high Impact",async()=>{const x=await composeCanonicalDecisionPressureV1(await inputs({impact:"HIGH",urgency:0.1,cow:0}));expect(x.components).toEqual(expect.arrayContaining([expect.objectContaining({dimension:"IMPACT",ordinal_state:"HIGH"}),expect.objectContaining({dimension:"URGENCY",continuous_value:0.1}),expect.objectContaining({dimension:"COST_OF_WAITING",continuous_value:0})]));});
 it("represents rising Pressure as a distinct vector with the same Impact",async()=>{const low=await composeCanonicalDecisionPressureV1(await inputs({urgency:0.1,cow:0})),rising=await composeCanonicalDecisionPressureV1(await inputs({urgency:0.8,cow:1}));expect(low.components[0]).toEqual(rising.components[0]);expect(low.pressure_id).not.toBe(rising.pressure_id);});
 it("distinguishes high Impact with ample time from moderate Impact with narrow time and high CoW",async()=>{const a=await composeCanonicalDecisionPressureV1(await inputs({impact:"HIGH",urgency:0.1,cow:0})),b=await composeCanonicalDecisionPressureV1(await inputs({impact:"MODERATE",urgency:0.9,cow:1}));expect(a.components).not.toEqual(b.components);});
 it("treats established zero CoW differently from unresolved CoW",async()=>{const complete=await composeCanonicalDecisionPressureV1(await inputs({cow:0})),base=await inputs(),partial=await composeCanonicalDecisionPressureV1({...base,cost_of_waiting:missing("COST_OF_WAITING","UNRESOLVED")});expect(complete.completeness_status).toBe("COMPLETE");expect(complete.components[2]?.continuous_value).toBe(0);expect(partial.completeness_status).toBe("QUALIFIED_PARTIAL_UNRESOLVED");expect(partial.components[2]).not.toHaveProperty("continuous_value");});
 it("preserves insufficient Cost of Waiting without a fabricated value",async()=>{const base=await inputs(),x=await composeCanonicalDecisionPressureV1({...base,cost_of_waiting:missing("COST_OF_WAITING","INSUFFICIENT_EVIDENCE")});expect(x.completeness_status).toBe("QUALIFIED_PARTIAL_INSUFFICIENT_EVIDENCE");expect(x.components[2]).not.toHaveProperty("continuous_value");});
 it("preserves WINDOW_EXHAUSTED without fabricating maximum Urgency",async()=>{const base=await inputs(),x=await composeCanonicalDecisionPressureV1({...base,urgency:missing("URGENCY","WINDOW_EXHAUSTED")});expect(x.completeness_status).toBe("QUALIFIED_PARTIAL_UNRESOLVED");expect(x.components[1]).toEqual({dimension:"URGENCY",status:"WINDOW_EXHAUSTED"});});
 it("requires established Impact while permitting explicitly qualified partial peers",async()=>{const base=await inputs();await expect(composeCanonicalDecisionPressureV1({...base,impact:{...base.impact,status:"UNRESOLVED",value:undefined}as any})).rejects.toThrow("PRESSURE_COMPOSITION_IMPACT_REQUIRED");});
 it("retains qualification provenance and causal lineage",async()=>{const x=await composeCanonicalDecisionPressureV1(await inputs());expect(x.qualification_refs).toContain("qualification:dimension");expect(x.provenance_refs).toContain("provenance:dimension");expect(x.causal_lineage_refs).toEqual(expect.arrayContaining(x.components.map(c=>c.dimension_id!)));});
 it("detects forged result and policy digest",async()=>{const x=await composeCanonicalDecisionPressureV1(await inputs());await expect(verifyCanonicalDecisionPressureCompositionV1({...x,composition_policy_digest:"forged"})).rejects.toThrow("PRESSURE_COMPOSITION_INTEGRITY_INVALID");});
 it.each(["impact","urgency","cost_of_waiting"]as const)("rejects raw %s scalar substitution",async key=>await expect(composeCanonicalDecisionPressureV1({...await inputs(),[key]:0.8}as any)).rejects.toThrow());
 it.each(["decision_margin","raw_lateness","simulator_score","optimizer_score","llm_score","level","priority","attention","authority_tier","subscription_tier","commercial_plan","credit_balance","provider","model","approval","delegation","recommendation","action"])("rejects raw or downstream %s substitution",async key=>await expect(composeCanonicalDecisionPressureV1({...await inputs(),[key]:"forbidden"}as any)).rejects.toThrow("PRESSURE_COMPOSITION_UNSUPPORTED_INPUT"));
 it.each(["VISION","GRADUATE","JUNIOR","SENIOR","PRINCIPAL","CHARTER"])("is identical at independent tier %s",async()=>{const a=await composeCanonicalDecisionPressureV1(await inputs()),b=await composeCanonicalDecisionPressureV1(await inputs());expect(a.pressure_id).toBe(b.pressure_id);expect(a).not.toHaveProperty("subscription_tier");});
 it("remains source-neutral observational and separate from recommendation authority execution and Attention",async()=>{const x=await composeCanonicalDecisionPressureV1(await inputs());expect(x).toMatchObject({recommended:false,executable:false,grants_authority:false,grants_execution:false,grants_remediation:false,opens_attention:false,company_global_claim:false});expect(JSON.stringify(x)).not.toMatch(/SAP|ERP|MES|email|chat|provider_name|llm_score|optimizer_score/i);});
});
