import {describe,expect,it} from "vitest";
import {bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1} from "../../cockpit/operational.signal.evaluation.scope.v1";
import {createMaterialOperationalConsequenceRefV1,createOperationalSubjectRefV1,createOperationsEvidenceProfileV1} from "../../cognition/canonical.operational.roles.v1";
import {createProtectedOperationalObjectiveBindingV1} from "../../cognition/protected.operational.objective.v1";
import {createCanonicalDecisionInfluenceabilityV1,verifyCanonicalDecisionInfluenceabilityV1} from "../canonical.decision.influenceability.v1";

async function context(){const scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"ENTITY",request_id:"request:1",company_id:"company:1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1",entity:{entity_type:"ORDER",entity_ref:"order:1"}}),evaluation_scope=await bindOperationalSignalsToScopeV1({scope,request_id:"request:1",company_id:"company:1",evidence_as_of:"2026-08-14T10:00:00Z",evaluated_at:"2026-08-14T10:01:00Z"}),protected_objective=await createProtectedOperationalObjectiveBindingV1({version:1,request_id:"request:1",company_id:"company:1",evaluation_scope,domain_profile_ref:"domain-profile:operations",domain_profile_version:"1",objective_kind_ref:"objective-kind:delivery",objective_ref:"objective:1",governing_expected_state_refs:["baseline:1"],governing_plan_element_refs:["plan:1"],protected_subject_refs:["subject:1"],commitment_criteria_refs:["criterion:1"],objective_selection_ref:"selection:objective",source_evidence_refs:["evidence:objective"],provenance_refs:["provenance:objective"],qualification_refs:["qualification:objective"],causal_lineage_refs:["lineage:objective"],plan_lineage_refs:["lineage:plan"],effective_at:"2026-08-14T09:00:00Z",evidence_as_of:evaluation_scope.evidence_as_of,evaluated_at:evaluation_scope.evaluated_at});return{evaluation_scope,protected_objective};}
async function result(overrides:Record<string,unknown>={}){const c=await context();return createCanonicalDecisionInfluenceabilityV1({version:1,request_id:"request:1",company_id:"company:1",...c,governing_condition_ref:"condition:trajectory",trajectory_ref:"trajectory:preservation",decision_purpose:"PRESERVATION",status:"INFLUENCEABLE",intervention_class_refs:["intervention-class:governed-adjustment"],material_effect_refs:["material-effect:objective-transition"],determination_basis_refs:["basis:domain-cognition"],evidence_refs:["evidence:influenceability"],qualification_refs:["qualification:influenceability"],provenance_refs:["provenance:influenceability"],causal_lineage_refs:["lineage:condition-to-material-effect"],evidence_as_of:c.evaluation_scope.evidence_as_of,evaluated_at:c.evaluation_scope.evaluated_at,...overrides} as any);}

describe("UNIVERSAL-DECISION-INFLUENCEABILITY-SEMANTICS-WU1",()=>{
 it("creates deterministic recursively immutable observational influenceability",async()=>{const a=await result(),b=await result();expect(a.influenceability_id).toBe(b.influenceability_id);expect(Object.isFrozen(a)&&Object.isFrozen(a.evidence_refs)).toBe(true);expect(a).toMatchObject({selects_option:false,guarantees_success:false,recommended:false,executable:false,grants_authority:false,grants_execution:false,global_no_decision_claim:false});await expect(verifyCanonicalDecisionInfluenceabilityV1(a)).resolves.toBeUndefined();});
 it.each(["INFLUENCEABLE","NOT_INFLUENCEABLE","UNRESOLVED","INSUFFICIENT_EVIDENCE"] as const)("supports %s fail-closed vocabulary",async status=>{const x=await result({status,intervention_class_refs:status==="INFLUENCEABLE"?["intervention-class:governed"]:[]});expect(x.status).toBe(status);expect(x.global_no_decision_claim).toBe(false);});
 it("requires an intervention class but never a selected option for INFLUENCEABLE",async()=>{await expect(result({intervention_class_refs:[]})).rejects.toThrow("DECISION_INFLUENCEABILITY_INTERVENTION_REQUIRED");expect(await result()).not.toHaveProperty("selected_option_ref");});
 it("forbids intervention claims for unresolved or NOT_INFLUENCEABLE results",async()=>{for(const status of ["NOT_INFLUENCEABLE","UNRESOLVED","INSUFFICIENT_EVIDENCE"])await expect(result({status})).rejects.toThrow("DECISION_INFLUENCEABILITY_INTERVENTION_NOT_ESTABLISHED");});
 it("binds exact objective, condition, trajectory, purpose, and causal material effect",async()=>{const x=await result();expect(x).toMatchObject({protected_objective_ref:expect.stringMatching(/^protected-operational-objective:/),governing_condition_ref:"condition:trajectory",trajectory_ref:"trajectory:preservation",decision_purpose:"PRESERVATION",material_effect_refs:["material-effect:objective-transition"]});});
 it("supports material-consequence context without an objective",async()=>{const c=await context(),profile=await createOperationsEvidenceProfileV1(),subject=await createOperationalSubjectRefV1({version:1,company_id:"company:1",profile,subject_kind:"ORDER",subject_ref:"order:1"}),material_consequence=await createMaterialOperationalConsequenceRefV1({version:1,subject,scope_ref:c.evaluation_scope.scope.scope_id,evidence_refs:["evidence:consequence"],provenance_refs:["provenance:consequence"],causal_lineage_refs:["lineage:consequence"],consequence_ref:"consequence:1",consequence_kind_ref:"consequence-kind:material",materiality_ref:"materiality:1"}),x=await result({protected_objective:undefined,material_consequence});expect(x.material_consequence_ref).toBe(material_consequence.role_id);});
 it("requires objective or consequence context and all epistemic bindings",async()=>{for(const x of [{protected_objective:undefined},{governing_condition_ref:""},{trajectory_ref:""},{material_effect_refs:[]},{determination_basis_refs:[]},{evidence_refs:[]},{qualification_refs:[]},{provenance_refs:[]},{causal_lineage_refs:[]}])await expect(result(x)).rejects.toThrow();});
 it("rejects forged identity and objective digest",async()=>{const x=await result();await expect(verifyCanonicalDecisionInfluenceabilityV1({...x,influenceability_digest:"forged"})).rejects.toThrow("DECISION_INFLUENCEABILITY_INTEGRITY_INVALID");const c=await context();await expect(result({protected_objective:{...c.protected_objective,objective_binding_digest:"forged"}})).rejects.toThrow();});
 it("rejects cross-request/company/scope and timestamp substitutions",async()=>{for(const x of [{request_id:"request:2"},{company_id:"company:2"},{evidence_as_of:"2026-08-14T09:59:00Z"}])await expect(result(x)).rejects.toThrow();});
 it.each(["capability_registry_ref","optimizer_candidate_ref","selected_option_ref","recommended_action_ref","execution_capability_ref"])("does not promote %s to influenceability",async key=>await expect(result({[key]:"forbidden:1"})).rejects.toThrow("DECISION_INFLUENCEABILITY_UNSUPPORTED_INPUT"));
 it.each(["authority_tier","subscription_tier","approval_ref","delegation_ref","credential_ref"])("rejects authority contamination %s",async key=>await expect(result({[key]:"forbidden:1"})).rejects.toThrow("DECISION_INFLUENCEABILITY_UNSUPPORTED_INPUT"));
 it("keeps Decision Margin, Opportunity, Urgency, Cost of Waiting, and Pressure separate",async()=>{for(const key of ["decision_margin_ref","urgency","cost_of_waiting","pressure"])await expect(result({[key]:"forbidden:1"})).rejects.toThrow("DECISION_INFLUENCEABILITY_UNSUPPORTED_INPUT");});
 it("preserves qualification, provenance, causal lineage and source neutrality",async()=>{const x=await result(),json=JSON.stringify(x);expect(x).toMatchObject({qualification_refs:["qualification:influenceability"],provenance_refs:["provenance:influenceability"],causal_lineage_refs:["lineage:condition-to-material-effect"]});expect(json).not.toMatch(/ERP|MES|SAP|email|chat|VISION|JUNIOR|SENIOR|working.attention|reversibilityScore/i);});
});
