import {describe,expect,it} from "vitest";
import {bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1} from "../../cockpit/operational.signal.evaluation.scope.v1";
import {createProtectedOperationalObjectiveBindingV1} from "../../cognition/protected.operational.objective.v1";
import {createMaterialOperationalConsequenceRefV1,createOperationalSubjectRefV1,createOperationsEvidenceProfileV1} from "../../cognition/canonical.operational.roles.v1";
import {createCanonicalDecisionMarginV1} from "../canonical.decision.margin.v1";
import {createCanonicalDecisionOpportunityV1,verifyCanonicalDecisionOpportunityV1} from "../canonical.decision.opportunity.v1";

async function context(asOf="2026-08-14T10:00:00Z",evaluated="2026-08-14T10:01:00Z"){const scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"ENTITY",request_id:"request:1",company_id:"company:1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1",entity:{entity_type:"ORDER",entity_ref:"order:1"}}),evaluation_scope=await bindOperationalSignalsToScopeV1({scope,request_id:"request:1",company_id:"company:1",evidence_as_of:asOf,evaluated_at:evaluated}),protected_objective=await createProtectedOperationalObjectiveBindingV1({version:1,request_id:"request:1",company_id:"company:1",evaluation_scope,domain_profile_ref:"domain-profile:operations",domain_profile_version:"1",objective_kind_ref:"objective-kind:delivery",objective_ref:"objective:1",governing_expected_state_refs:["baseline:1"],governing_plan_element_refs:["plan-element:1"],protected_subject_refs:["subject:1"],commitment_criteria_refs:["criterion:1"],objective_selection_ref:"selection:objective",source_evidence_refs:["evidence:objective"],provenance_refs:["provenance:objective"],qualification_refs:["qualification:objective"],causal_lineage_refs:["lineage:objective"],plan_lineage_refs:["lineage:plan"],effective_at:"2026-08-14T09:00:00Z",evidence_as_of:asOf,evaluated_at:evaluated});return{evaluation_scope,protected_objective};}
async function margin(c:Awaited<ReturnType<typeof context>>,status:"AVAILABLE"|"BOUNDARY_REACHED"|"BOUNDARY_EXCEEDED"="BOUNDARY_REACHED"){return createCanonicalDecisionMarginV1({version:1,request_id:"request:1",company_id:"company:1",...c,governing_condition_ref:"condition:preservation",governing_dimension_ref:"dimension:time",current_position_ref:"position:1",compromise_boundary_ref:"boundary:1",material_compromise_refs:["consequence:1"],status,...(status==="AVAILABLE"?{remaining_margin:{value:1,unit_ref:"duration:hours",measurement_ref:"measurement:1"}}:status==="BOUNDARY_REACHED"?{remaining_margin:{value:0,unit_ref:"duration:hours",measurement_ref:"measurement:1"}}:{}),epistemic_basis:"DETERMINISTIC",producer_ref:"producer:operations",policy_ref:"policy:margin",evidence_refs:["evidence:margin"],qualification_refs:["qualification:margin"],provenance_refs:["provenance:margin"],causal_lineage_refs:["lineage:margin"],evidence_as_of:c.evaluation_scope.evidence_as_of,evaluated_at:c.evaluation_scope.evaluated_at});}
async function opportunity(overrides:Record<string,unknown>={}){const c=await context(),decision_margin=await margin(c);return createCanonicalDecisionOpportunityV1({version:1,request_id:"request:1",company_id:"company:1",...c,governing_condition_ref:"condition:preservation",purpose:"PRESERVATION",status:"OPEN",decision_margin,transition_trigger_refs:[],evidence_refs:["evidence:opportunity"],qualification_refs:["qualification:opportunity"],provenance_refs:["provenance:opportunity"],causal_lineage_refs:["lineage:opportunity"],evidence_as_of:c.evaluation_scope.evidence_as_of,evaluated_at:c.evaluation_scope.evaluated_at,...overrides} as any);}

describe("UNIVERSAL-DECISION-OPPORTUNITY-SEMANTICS-WU1",()=>{
 it("creates deterministic immutable observational identity",async()=>{const a=await opportunity(),b=await opportunity();expect(a.opportunity_id).toBe(b.opportunity_id);expect(a).toMatchObject({status:"OPEN",current_opportunity_claim:true,global_no_decision_claim:false,successor_created_automatically:false,observational_only:true,grants_authority:false,grants_execution:false,recommended:false,executable:false});expect(Object.isFrozen(a)&&Object.isFrozen(a.evidence_refs)).toBe(true);await expect(verifyCanonicalDecisionOpportunityV1(a)).resolves.toBeUndefined();});
 it.each(["PRESERVATION","RECOVERY","CONTAINMENT","ADAPTATION"] as const)("supports %s purpose",async purpose=>expect((await opportunity({purpose})).purpose).toBe(purpose));
 it("supports zero margin while opportunity remains OPEN",async()=>expect(await opportunity()).toMatchObject({status:"OPEN",decision_margin_ref:expect.stringMatching(/^canonical-decision-margin:/)}));
 it("does not infer status from AVAILABLE or EXCEEDED margin",async()=>{for(const status of ["AVAILABLE","BOUNDARY_EXCEEDED"] as const){const c=await context(),decision_margin=await margin(c,status);expect((await opportunity({decision_margin})).status).toBe("OPEN");}});
 it("makes CLOSED local, evidenced, and never a global no-decision claim",async()=>{const x=await opportunity({status:"CLOSED",closure_reason_ref:"reason:crossed",transition_trigger_refs:["condition:changed"]});expect(x).toMatchObject({status:"CLOSED",current_opportunity_claim:false,global_no_decision_claim:false});await expect(opportunity({status:"CLOSED"})).rejects.toThrow("DECISION_OPPORTUNITY_CLOSURE_EVIDENCE_REQUIRED");});
 it.each(["UNRESOLVED","INSUFFICIENT_EVIDENCE"] as const)("fails closed for %s",async status=>expect((await opportunity({status,decision_margin:undefined})).current_opportunity_claim).toBe(false));
 it("binds a distinct evidenced successor without automatic creation",async()=>{const predecessor=await opportunity({status:"CLOSED",closure_reason_ref:"reason:breach",transition_trigger_refs:["consequence:breach"]}),c=await context("2026-08-14T10:01:00Z","2026-08-14T10:02:00Z"),successor=await createCanonicalDecisionOpportunityV1({version:1,request_id:"request:1",company_id:"company:1",...c,governing_condition_ref:"condition:recovery",purpose:"RECOVERY",status:"OPEN",predecessor_opportunity:predecessor,transition_trigger_refs:["consequence:breach"],evidence_refs:["evidence:recovery"],qualification_refs:["qualification:recovery"],provenance_refs:["provenance:recovery"],causal_lineage_refs:[predecessor.opportunity_id],evidence_as_of:c.evaluation_scope.evidence_as_of,evaluated_at:c.evaluation_scope.evaluated_at});expect(successor.predecessor_opportunity_ref).toBe(predecessor.opportunity_id);expect(successor.opportunity_id).not.toBe(predecessor.opportunity_id);expect(successor.successor_created_automatically).toBe(false);});
 it("supports independently governed consequence context without requiring an objective",async()=>{const c=await context(),profile=await createOperationsEvidenceProfileV1(),subject=await createOperationalSubjectRefV1({version:1,company_id:"company:1",profile,subject_kind:"ORDER",subject_ref:"order:1"}),material_consequence=await createMaterialOperationalConsequenceRefV1({version:1,subject,scope_ref:c.evaluation_scope.scope.scope_id,evidence_refs:["evidence:consequence"],provenance_refs:["provenance:consequence"],causal_lineage_refs:["lineage:consequence"],consequence_ref:"consequence:recovery",consequence_kind_ref:"operations-consequence:RECOVERY",materiality_ref:"materiality:recovery"}),x=await opportunity({protected_objective:undefined,material_consequence,decision_margin:undefined,purpose:"CONTAINMENT",governing_condition_ref:"condition:containment"});expect(x.material_consequence_ref).toBe(material_consequence.role_id);expect(x).not.toHaveProperty("protected_objective_ref");});
 it("requires coherent transition timing/trigger and rejects stale margin on a new condition",async()=>{await expect(opportunity({predecessor_opportunity:await opportunity()})).rejects.toThrow();const c=await context(),old=await margin(c);await expect(opportunity({governing_condition_ref:"condition:recovery",decision_margin:old})).rejects.toThrow("DECISION_OPPORTUNITY_MARGIN_BINDING_MISMATCH");});
 it("requires context, condition, evidence, qualification, provenance and lineage",async()=>{for(const x of [{protected_objective:undefined},{governing_condition_ref:""},{evidence_refs:[]},{qualification_refs:[]},{provenance_refs:[]},{causal_lineage_refs:[]}])await expect(opportunity(x)).rejects.toThrow();});
 it("rejects forged identity and scope/time substitution",async()=>{const x=await opportunity();await expect(verifyCanonicalDecisionOpportunityV1({...x,opportunity_digest:"forged"})).rejects.toThrow("DECISION_OPPORTUNITY_INTEGRITY_INVALID");for(const y of [{company_id:"company:2"},{request_id:"request:2"},{evidence_as_of:"2026-08-14T09:59:00Z"}])await expect(opportunity(y)).rejects.toThrow();});
 it.each(["authority_tier","approval_ref","delegation_ref","credential_ref","recommended_action_ref","candidate_action_ref","optimizer_output_ref","successor_opportunity"])("rejects %s contamination",async key=>await expect(opportunity({[key]:"forbidden:1"})).rejects.toThrow("DECISION_OPPORTUNITY_UNSUPPORTED_INPUT"));
 it("preserves evidence bindings and source/tier/attention/learning neutrality",async()=>{const x=await opportunity(),json=JSON.stringify(x);expect(x).toMatchObject({qualification_refs:["qualification:opportunity"],provenance_refs:["provenance:opportunity"],causal_lineage_refs:["lineage:opportunity"]});expect(json).not.toMatch(/ERP|MES|SAP|email|chat|VISION|JUNIOR|SENIOR|working.attention|learned|recommendation|optimizer/i);});
});
