import {describe,expect,it} from "vitest";
import {bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1} from "../../cockpit/operational.signal.evaluation.scope.v1";
import {createEffectiveOperationalResponseTimingV1,createGovernedOperationalSafetyMarginV1} from "../effective.operational.response.timing.v1";

async function base(){const scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"ENTITY",request_id:"request:1",company_id:"company:1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1",entity:{entity_type:"ORDER",entity_ref:"order:1"}});const evaluation_scope=await bindOperationalSignalsToScopeV1({scope,request_id:"request:1",company_id:"company:1",evidence_as_of:"2026-08-13T10:00:00Z",evaluated_at:"2026-08-13T11:00:00Z"});return{version:1 as const,request_id:"request:1",company_id:"company:1",evaluation_scope,evidence_selection_ref:"selection:1",evidence_refs:["evidence:1"],qualification_refs:["qualification:1"],provenance_refs:["provenance:1"],causal_lineage_refs:["condition:1"],producer_ref:"producer:operations",policy_ref:"policy:response-timing"};}
async function timing(overrides={}){return createEffectiveOperationalResponseTimingV1({...await base(),response_class_ref:"response-class:qualified-capability",protected_objective_ref:"objective:1",governing_condition_ref:"condition:1",feasibility:"AVAILABLE" as const,usefulness:"USEFUL" as const,usefulness_evidence_refs:["evidence:useful"],effective_duration:{value:12,unit_ref:"duration:hours"},...overrides});}

describe("effective operational response timing",()=>{
  it("creates a deterministic immutable observational duration",async()=>{const a=await timing(),b=await timing();expect(a.response_timing_id).toBe(b.response_timing_id);expect(a).toMatchObject({observational_only:true,grants_authority:false,grants_execution:false,grants_remediation:false,executable:false,recommended:false});expect(Object.isFrozen(a)).toBe(true);expect(Object.isFrozen(a.effective_duration)).toBe(true);});
  it("supports an authoritative future effect boundary",async()=>{const x=await timing({effective_duration:undefined,effective_at:"2026-08-14T11:00:00Z"});expect(x.effective_at).toBe("2026-08-14T11:00:00Z");});
  it.each(["evidence_refs","qualification_refs","provenance_refs","causal_lineage_refs","usefulness_evidence_refs"] as const)("requires %s",async key=>{await expect(timing({[key]:[]})).rejects.toThrow();});
  it("binds evidence selection",async()=>{await expect(timing({evidence_selection_ref:"selection:other"})).rejects.toThrow("RESPONSE_TIMING_EVIDENCE_SELECTION_MISMATCH");});
  it("requires exactly one timing representation for a useful available response",async()=>{await expect(timing({effective_duration:undefined})).rejects.toThrow("RESPONSE_TIMING_VALUE_REQUIRED");await expect(timing({effective_at:"2026-08-14T11:00:00Z"})).rejects.toThrow("RESPONSE_TIMING_VALUE_AMBIGUOUS");});
  it("rejects timing for unresolved or non-useful responses",async()=>{await expect(timing({usefulness:"UNRESOLVED"})).rejects.toThrow("RESPONSE_TIMING_VALUE_NOT_RESOLVED");await expect(timing({feasibility:"UNAVAILABLE"})).rejects.toThrow("RESPONSE_TIMING_VALUE_NOT_RESOLVED");});
  it("rejects past effect boundaries and invalid temporal units",async()=>{await expect(timing({effective_duration:undefined,effective_at:"2026-08-13T10:59:59Z"})).rejects.toThrow("RESPONSE_EFFECTIVE_AT_PAST");await expect(timing({effective_duration:{value:1,unit_ref:""}})).rejects.toThrow("RESPONSE_DURATION_INVALID");});
  it("contains no optimizer, recommendation, urgency, cost, or pressure semantics",async()=>{const x=await timing();expect(JSON.stringify(x)).not.toMatch(/availableInDays|candidate|optimizer|urgency|cost.of.waiting|ordinal_state/i);});
});

describe("governed operational safety margin",()=>{
  async function margin(overrides={}){const response=await timing();return createGovernedOperationalSafetyMarginV1({...await base(),response_timing_ref:response.response_timing_id,governing_condition_ref:"condition:1",applicability:"APPLIES" as const,margin_duration:{value:2,unit_ref:"duration:hours"},determination_evidence_refs:["evidence:margin-policy"],...overrides});}
  it("represents an applicable governed margin",async()=>{const x=await margin();expect(x.margin_duration).toEqual({value:2,unit_ref:"duration:hours"});expect(x.observational_only).toBe(true);});
  it("distinguishes positive no-separate-margin determination from missing evidence",async()=>{const none=await margin({applicability:"NO_SEPARATE_MARGIN_APPLICABLE",margin_duration:undefined});const unresolved=await margin({applicability:"UNRESOLVED",margin_duration:undefined});expect(none.safety_margin_id).not.toBe(unresolved.safety_margin_id);expect(none.determination_evidence_refs).toEqual(["evidence:margin-policy"]);});
  it("never defaults a missing margin to zero",async()=>{await expect(margin({margin_duration:undefined})).rejects.toThrow("SAFETY_MARGIN_DURATION_REQUIRED");});
  it("forbids a duration when no separate margin applies or evidence is unresolved",async()=>{for(const applicability of ["NO_SEPARATE_MARGIN_APPLICABLE","UNRESOLVED","INSUFFICIENT_EVIDENCE"] as const)await expect(margin({applicability})).rejects.toThrow("SAFETY_MARGIN_DURATION_NOT_APPLICABLE");});
  it("does not alias absorbable delay",async()=>{const x=await margin();expect(JSON.stringify(x)).not.toMatch(/absorbable_delay|slack/);});
});
