import {describe,expect,it} from "vitest";
import {bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1} from "../../cockpit/operational.signal.evaluation.scope.v1";
import {createProtectedOperationalObjectiveBindingV1} from "../../cognition/protected.operational.objective.v1";
import {createOperationsGovernedInterventionClassV1} from "../../industrial/cognition/operations.governed.intervention.class.v1";
import {createGovernedInterventionDiscoveryV1,verifyGovernedInterventionDiscoveryV1} from "../governed.intervention.discovery.policy.v1";
const asOf="2026-08-14T10:00:00Z",evaluated="2026-08-14T10:01:00Z";
async function context(classKey="INVENTORY_REALLOCATION") {const scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"REQUEST_DATASET",request_id:"request-1",company_id:"company-1",domain:"operations",evidence_selection_ref:"selection:current",source_snapshot_ref:"snapshot:current"}),binding=await bindOperationalSignalsToScopeV1({scope,request_id:"request-1",company_id:"company-1",evidence_as_of:asOf,evaluated_at:evaluated}),objective=await createProtectedOperationalObjectiveBindingV1({version:1,request_id:"request-1",company_id:"company-1",evaluation_scope:binding,domain_profile_ref:"profile:operations-v1",domain_profile_version:"1",objective_kind_ref:"objective-kind:service",objective_ref:"objective:protected",governing_expected_state_refs:["state:expected"],governing_plan_element_refs:["plan:protected"],protected_subject_refs:["subject:protected"],commitment_criteria_refs:["criterion:protected"],objective_selection_ref:"selection:objective",source_evidence_refs:["evidence:objective"],provenance_refs:["provenance:objective"],qualification_refs:["qualification:objective"],causal_lineage_refs:["lineage:objective"],plan_lineage_refs:["lineage:plan"],effective_at:"2026-08-14T09:00:00Z",evidence_as_of:asOf,evaluated_at:evaluated}),intervention=await createOperationsGovernedInterventionClassV1({version:1,domain_profile_ref:"profile:operations-v1",domain_profile_version:"1",class_key:classKey,producer_ref:"producer:operations-intervention-evidence-v1",policy_ref:"policy:operations-intervention-v1"});return{binding,objective,intervention};}
async function discovery(overrides:Record<string,unknown>={}){const x=await context();return createGovernedInterventionDiscoveryV1({version:1,request_id:"request-1",company_id:"company-1",evaluation_scope:x.binding,domain_profile_ref:"profile:operations-v1",domain_profile_version:"1",current_state_ref:"state:current",dimension_ref:"dimension:resource-assignment",changeability_status:"CHANGEABLE",changeability_evidence_refs:["evidence:changeability"],principle_hypothesis_ref:"hypothesis:resource-reassignment",principle_origin_ref:"domain-model:operations-v1",admission_status:"ADMITTED",admitted_intervention_class_ref:x.intervention.intervention_class_id,admitted_intervention_class_digest:x.intervention.intervention_class_digest,admission_evidence_refs:["evidence:principle-admission"],admissibility_status:"ADMISSIBLE",constraint_refs:["constraint:current-domain"],admissibility_evidence_refs:["evidence:constraint-evaluation"],baseline_ref:"baseline:current",perturbation_ref:"perturbation:bounded",evaluator_ref:"evaluator:qualified-domain",causal_test_result_ref:"causal-test:result",material_effect_status:"MATERIAL_EFFECT_ESTABLISHED",material_effect_evidence_refs:["evidence:material-effect"],protected_objective:x.objective,governing_condition_ref:"condition:governing",trajectory_ref:"trajectory:protected",determination_basis_refs:["basis:governed-causal-test"],qualification_refs:["qualification:admitted"],provenance_refs:["provenance:current-facts"],causal_lineage_refs:["lineage:state-to-effect"],epistemic_basis:"DETERMINISTIC_COUNTERFACTUAL",evidence_as_of:asOf,evaluated_at:evaluated,...overrides} as any);}
describe("INTERVENTION-DISCOVERY-POLICY-WU1",()=>{
 it("creates deterministic recursively immutable identity with verifiable integrity",async()=>{const a=await discovery(),b=await discovery();expect(a.discovery_id).toBe(b.discovery_id);expect(Object.isFrozen(a)&&Object.isFrozen(a.constraint_refs)).toBe(true);await expect(verifyGovernedInterventionDiscoveryV1(a)).resolves.toBeUndefined();});
 it.each([["CHANGEABLE","NOT_ADMISSIBLE","UNRESOLVED"],["NOT_CHANGEABLE","ADMISSIBLE","MATERIAL_EFFECT_ESTABLISHED"],["UNRESOLVED","UNRESOLVED","NO_MATERIAL_EFFECT_ESTABLISHED"]] as const)("keeps changeability %s, admissibility %s, and effect %s independent",async(changeability_status,admissibility_status,material_effect_status)=>expect(await discovery({changeability_status,admissibility_status,material_effect_status})).toMatchObject({changeability_status,admissibility_status,material_effect_status}));
 it("distinguishes a hypothesis from an admitted class",async()=>{const admitted=await discovery();expect(admitted).toMatchObject({hypothesis_is_truth:false,admission_status:"ADMITTED"});const unresolved=await discovery({admission_status:"UNRESOLVED",admitted_intervention_class_ref:undefined,admitted_intervention_class_digest:undefined});expect(unresolved).not.toHaveProperty("admitted_intervention_class_ref");});
 it("requires a governed class identity only for ADMITTED",async()=>{await expect(discovery({admitted_intervention_class_ref:undefined})).rejects.toThrow("INTERVENTION_DISCOVERY_ADMITTED_CLASS_REQUIRED");await expect(discovery({admission_status:"REJECTED"})).rejects.toThrow("INTERVENTION_DISCOVERY_CLASS_NOT_ADMITTED");});
 it.each([["changeability_evidence_refs","INTERVENTION_DISCOVERY_CHANGEABILITY_EVIDENCE_REQUIRED"],["admission_evidence_refs","INTERVENTION_DISCOVERY_ADMISSION_EVIDENCE_REQUIRED"],["constraint_refs","INTERVENTION_DISCOVERY_CONSTRAINT_REQUIRED"],["admissibility_evidence_refs","INTERVENTION_DISCOVERY_ADMISSIBILITY_EVIDENCE_REQUIRED"],["material_effect_evidence_refs","INTERVENTION_DISCOVERY_EFFECT_EVIDENCE_REQUIRED"],["qualification_refs","INTERVENTION_DISCOVERY_QUALIFICATION_REQUIRED"],["provenance_refs","INTERVENTION_DISCOVERY_PROVENANCE_REQUIRED"],["causal_lineage_refs","INTERVENTION_DISCOVERY_LINEAGE_REQUIRED"]])("fails closed without %s",async(key,code)=>await expect(discovery({[key]:[]})).rejects.toThrow(code));
 it("binds baseline, bounded perturbation, specialized evaluator, exact objective, condition and trajectory",async()=>expect(await discovery()).toMatchObject({baseline_ref:"baseline:current",perturbation_ref:"perturbation:bounded",evaluator_ref:"evaluator:qualified-domain",protected_objective_ref:expect.stringMatching(/^protected-operational-objective:/),governing_condition_ref:"condition:governing",trajectory_ref:"trajectory:protected"}));
 it("rejects cross-request, company, scope, profile, and timestamp substitution",async()=>{for(const x of [{request_id:"other"},{company_id:"other"},{domain_profile_ref:"profile:other"},{evidence_as_of:"2026-08-14T09:59:00Z"},{evaluation_scope:{...(await context()).binding,scope:{...(await context()).binding.scope,scope_digest:"forged"}}}])await expect(discovery(x)).rejects.toThrow();});
 it.each(["llm_output","optimizer_candidate_ref","candidate_plan_ref","simulation_result","capability_registry_ref","execution_capability_ref","authority_tier","subscription_tier","approval_ref","delegation_ref","credential_ref","recommendation_ref","selected_action_ref","action_instance","execution_payload"])("rejects direct substitution by %s",async key=>await expect(discovery({[key]:"forbidden:1"})).rejects.toThrow("INTERVENTION_DISCOVERY_UNSUPPORTED_INPUT"));
 it("accepts only deterministic epistemic bases",async()=>{expect((await discovery({epistemic_basis:"DETERMINISTIC"})).epistemic_basis).toBe("DETERMINISTIC");await expect(discovery({epistemic_basis:"LEARNED"})).rejects.toThrow("INTERVENTION_DISCOVERY_EPISTEMIC_INVALID");});
 it("keeps material effect observational and separate from recommendation, authority, execution and downstream decisions",async()=>{const x=await discovery();expect(x).toMatchObject({material_effect_status:"MATERIAL_EFFECT_ESTABLISHED",guarantees_success:false,selects_action:false,recommended:false,executable:false,grants_authority:false,grants_execution:false,grants_remediation:false});for(const k of ["recommendation","decision_influenceability","decision_opportunity","decision_margin","urgency","cost_of_waiting","pressure"])expect(x).not.toHaveProperty(k);});
 it.each(["INVENTORY_REALLOCATION","PRODUCTION_SEQUENCE_ADJUSTMENT"])("uses %s only as an extensible class fixture",async classKey=>{const c=await context(classKey),x=await discovery({admitted_intervention_class_ref:c.intervention.intervention_class_id,admitted_intervention_class_digest:c.intervention.intervention_class_digest,dimension_ref:classKey==="INVENTORY_REALLOCATION"?"dimension:allocation":"dimension:sequence"});expect(x.admitted_intervention_class_ref).toBe(c.intervention.intervention_class_id);});
 it("is source-neutral and structurally cross-domain",async()=>{const json=JSON.stringify(await discovery());expect(json).not.toMatch(/SKU|ORDER|SUPPLIER|ERP|SAP|MES|email|chat|telephone|API|VISION|JUNIOR|SENIOR/);for(const ref of ["maintenance-principle:repair","project-principle:resource-assignment","finance-principle:payment-timing"])expect(ref).toMatch(/^[A-Za-z0-9][A-Za-z0-9._-]*:[^\s]+$/);});
 it("changes identity when any governed stage changes",async()=>{const a=await discovery();for(const b of [await discovery({dimension_ref:"dimension:other"}),await discovery({admissibility_status:"NOT_ADMISSIBLE"}),await discovery({causal_test_result_ref:"causal-test:other"}),await discovery({material_effect_status:"UNRESOLVED"})])expect(b.discovery_id).not.toBe(a.discovery_id);});
});
