import{describe,expect,it}from"vitest";
import type{ConfirmationChainV1,OagActorBindingV1,OrganizationalResponsibilityScopeV1}from"../../../operational-identity/contracts/track-b.v1";
import type{OrganizationalRepresentationEligibilityV1}from"../../organizational-representation";
import{activateResponsibilityV1,buildCanonicalActorBindingV1,buildCanonicalRootV1,buildDelegationV1,buildGraphVersionV1,organizationalAuthorityPolicyV1,semanticReferenceV1}from"..";
const now="2026-08-09T10:00:00.000Z",later="2026-08-10T10:00:00.000Z";
const scope=(scopes=["OPERATE"]):OrganizationalResponsibilityScopeV1=>({domain:"operations",intents:["EXECUTE"],scopes,limits:[],team_or_subordinate_actor_ids:[],operational_constraints:[]}) as any;
const binding=(actor="actor:1",principal="principal:1",membership="membership:1")=>buildCanonicalActorBindingV1({version:1,tenant_id:"tenant:1",binding:{version:1,oag_actor_binding_id:`binding:${actor}`,oag_actor_id:actor,principal_id:principal,membership_id:membership,company_id:"company:1",lifecycle_state:"ACTIVE",bound_at:now,binding_reference:"oir:binding"}as any,effective_from:now,policy_id:"OAG_AUTHORITY_POLICY_V1",causal_references:[]},{principal_id:principal,membership_id:membership,tenant_id:"tenant:1",company_id:"company:1",principal_state:"ACTIVE",membership_state:"ACTIVE",resolved_tenant_id:"tenant:1"});
const eligibility=(overrides:Partial<OrganizationalRepresentationEligibilityV1>={}):OrganizationalRepresentationEligibilityV1=>({version:1,eligibility_id:"orpe:1",authority_id:"orpa:1",actor_principal_id:"principal:1",membership_id:"membership:1",legal_entity_id:"legal:1",company_binding_id:"company-binding:1",requested_scope:"REPRESENT_LEGAL_ENTITY_FOR_PLATFORM_ONBOARDING",future_consumer:"OAG_AUTHORITY_ROOT_BOOTSTRAP_V1",issued_at:now,expires_at:later,policy_version:"ORPA_POLICY_V1",correlation_id:"correlation",caused_by:[],transferable:false,executable:false,...overrides});
const root=()=>buildCanonicalRootV1({version:1,tenant_id:"tenant:1",company_id:"company:1",oag_actor_id:"actor:1",actor_binding_id:"binding:actor:1",principal_id:"principal:1",membership_id:"membership:1",domain:"operations",permitted_scope:scope(["OPERATE","REVIEW"]),effective_from:now,effective_until:later,bootstrap_eligibility_id:"orpe:1",bootstrap_authority_id:"orpa:1",legal_entity_id:"legal:1",company_binding_id:"company-binding:1",policy_id:"OAG_AUTHORITY_POLICY_V1",graph_version_id:"graph:bootstrap",causal_references:[]},{eligibility:eligibility(),actor_binding:binding(),tenant_id:"tenant:1",company_id:"company:1",legal_entity_id:"legal:1",company_binding_id:"company-binding:1",requested_at:now});
const chain=(subject="responsibility:1",target="actor:2"):{version:1;chain:ConfirmationChainV1;authority_source_id:string;authority_source_actor_id:string;subject_fact_id:string;policy_id:"OAG_AUTHORITY_POLICY_V1";effective_from:string;evidence_references:string[];causal_references:string[]}=>({version:1,chain:{version:1,confirmation_chain_id:`chain:${subject}`,subject_actor_id:target,tenant_id:"tenant:1",company_id:"company:1",declaration_version_id:"declaration:1",steps:[{ordinal:1,confirmation_decision_id:"decision:1",confirming_actor_id:"actor:1",confirmed_scope:scope()}],terminal_scope:scope(),graph_version:"graph:bootstrap",policy_version:"OAG_AUTHORITY_POLICY_V1",completed_at:now}as any,authority_source_id:root().root_id,authority_source_actor_id:"actor:1",subject_fact_id:subject,policy_id:"OAG_AUTHORITY_POLICY_V1",effective_from:now,evidence_references:["evidence:1"],causal_references:[]});
describe("OAG-CAN-WU1 canonical authority state",()=>{
 it("defines deterministic immutable V1 policy",()=>{const a=organizationalAuthorityPolicyV1(now,"c"),b=organizationalAuthorityPolicyV1(now,"c");expect(a).toEqual(b);expect(a.max_delegation_depth).toBe(1);expect(a.graph_supersession_rule).toBe("NO_GRANDFATHERING");expect(Object.isFrozen(a)).toBe(true);});
 it("requires exact OIR identities",()=>{expect(()=>binding("actor:1","principal:other")).not.toThrow();expect(()=>buildCanonicalActorBindingV1({version:1,tenant_id:"tenant:1",binding:binding().binding,effective_from:now,policy_id:"OAG_AUTHORITY_POLICY_V1",causal_references:[]},{principal_id:"other",membership_id:"membership:1",tenant_id:"tenant:1",company_id:"company:1",principal_state:"ACTIVE",membership_state:"ACTIVE",resolved_tenant_id:"tenant:1"})).toThrow(/OAG_CAN_ACTOR_BINDING_INVALID/);});
 it("bootstraps only from exact current ORPA eligibility",()=>{expect(root().root_id).toMatch(/^oag-root:sha256:/);for(const patch of[{future_consumer:"PLATFORM_CONTRACT_ACCEPTANCE"},{requested_scope:"ACCEPT_ENTERPRISE_NDA"},{expires_at:now}] as const)expect(()=>buildCanonicalRootV1({...root(),root_id:undefined}as any,{eligibility:eligibility(patch as any),actor_binding:binding(),tenant_id:"tenant:1",company_id:"company:1",legal_entity_id:"legal:1",company_binding_id:"company-binding:1",requested_at:now})).toThrow(/OAG_CAN_ROOT_BOOTSTRAP_UNAUTHORIZED/);});
 it("activates responsibility only through a covering non-self confirmation",()=>{const r={version:1,responsibility_id:"responsibility:1",declaration_version_id:"declaration:1",tenant_id:"tenant:1",company_id:"company:1",subject_actor_id:"actor:2",scope:scope(),effective_from:now,lifecycle_state:"DECLARED",policy_id:"OAG_AUTHORITY_POLICY_V1",causal_references:[]}as const;expect(activateResponsibilityV1(r as any,chain()as any,root(),now).lifecycle_state).toBe("ACTIVE");expect(()=>activateResponsibilityV1({...r,subject_actor_id:"actor:1"}as any,chain("responsibility:1","actor:1")as any,root(),now)).toThrow(/SELF_REFERENCE/);});
 it("permits one nonexpanding delegation and denies widening or second hop",()=>{const d={version:1,delegation_id:"delegation:1",tenant_id:"tenant:1",company_id:"company:1",source_authority_id:root().root_id,source_actor_id:"actor:1",target_actor_id:"actor:2",target_actor_binding_id:"binding:actor:2",domain:"operations",delegated_scope:scope(),effective_from:now,effective_until:later,depth:1,confirmation_chain_id:"chain:delegation:1",policy_id:"OAG_AUTHORITY_POLICY_V1",graph_version_id:"graph:bootstrap",causal_references:[]}as const,c=chain("delegation:1");expect(buildDelegationV1(d as any,{id:root().root_id,actor_id:"actor:1",tenant_id:"tenant:1",company_id:"company:1",scope:root().permitted_scope,expires_at:later},binding("actor:2","principal:2","membership:2"),c as any,now).depth).toBe(1);expect(()=>buildDelegationV1({...d,delegated_scope:scope(["UNKNOWN"])}as any,{id:root().root_id,actor_id:"actor:1",tenant_id:"tenant:1",company_id:"company:1",scope:root().permitted_scope},binding("actor:2","principal:2","membership:2"),c as any,now)).toThrow(/SCOPE_EXPANDED/);expect(()=>buildDelegationV1({...d,depth:2}as any,{id:root().root_id,actor_id:"actor:1",tenant_id:"tenant:1",company_id:"company:1",scope:root().permitted_scope},binding("actor:2","principal:2","membership:2"),c as any,now)).toThrow(/DEPTH_EXCEEDED/);});
 it("builds deterministic substitution-sensitive graph versions",()=>{const ref=semanticReferenceV1("ROOT",root().root_id,root()),a=buildGraphVersionV1({version:1,tenant_id:"tenant:1",company_id:"company:1",policy_id:"OAG_AUTHORITY_POLICY_V1",state_references:[ref],effective_from:now,correlation_id:"c",causal_references:[]}),b=buildGraphVersionV1({version:1,tenant_id:"tenant:1",company_id:"company:1",policy_id:"OAG_AUTHORITY_POLICY_V1",state_references:[ref],effective_from:later,correlation_id:"other",causal_references:["audit"]});expect(a.graph_version_id).toBe(b.graph_version_id);expect(buildGraphVersionV1({...a,state_references:[semanticReferenceV1("ROOT",root().root_id,{changed:true})]}).graph_digest).not.toBe(a.graph_digest);});
});
