import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import {auditRoles,completeAudit,loadAnnotations} from "./audit_v04_qualification.mjs";

const expected=role=>({interaction:"AUDIENCE_DECLARATION",audience_declaration:{declared_role:role}}),parsed=role=>({audience_declaration:{declared_role:role}});
test("exact role span is exact and typo correction is changed",()=>{const sidecar=new Map(),cases=[{case_id:"exact",input_text:"CFO here.",role_span:{start:0,end:3,text:"CFO"},expected:expected("CFO"),parsed_output:parsed("CFO")},{case_id:"typo",input_text:"I'm the prodution planr.",role_span:{start:8,end:23,text:"prodution planr"},expected:expected("prodution planr"),parsed_output:parsed("production planr")}],audit=auditRoles("synthetic",cases,sidecar);assert.equal(audit.counts.ROLE_SURFACE_EXACT,1);assert.equal(audit.counts.ROLE_SURFACE_CHANGED,1)});
test("historical target cannot override requester surface",()=>{const audit=auditRoles("historical",[{case_id:"h",input_text:"I oversee plant operations.",role_span:{start:2,end:26,text:"oversee plant operations"},expected:expected("plant manager"),parsed_output:parsed("plant manager")}],new Map());assert.equal(audit.counts.EVALUATION_ORACLE_CONFLICT,1)});
test("missing role metadata is not automatically changed",()=>{const audit=auditRoles("missing",[{case_id:"m",input_text:"CFO here.",expected:expected("CFO"),parsed_output:parsed("CFO")}],new Map());assert.equal(audit.counts.NOT_APPLICABLE,1);assert.equal(audit.counts.ROLE_SURFACE_CHANGED,0)});

const root=process.env.GCC4Q_ARTIFACT_ROOT;
if(root)test("raw metrics and predictions remain identical and corrected decision is reproducible",()=>{const sidecar=loadAnnotations(path.join(path.dirname(new URL(import.meta.url).pathname.replace(/^\/(.:)/,"$1")),"role.span.audit.sidecar.json")),files=fs.readdirSync(path.join(root,"evaluation")).map(n=>path.join(root,"evaluation",n,"result.json")),hashes=files.map(f=>crypto.createHash("sha256").update(fs.readFileSync(f)).digest("hex")),first=completeAudit(root,"482a0bd0aeb6423b2f847f483ceed2ffa451735698cd64ef69ee0597a0ca336f",sidecar),second=completeAudit(root,"482a0bd0aeb6423b2f847f483ceed2ffa451735698cd64ef69ee0597a0ca336f",sidecar);assert.deepEqual(first,second);for(const [name,metrics] of Object.entries(first.raw_metrics_preserved)){const original=JSON.parse(fs.readFileSync(path.join(root,"evaluation",name,"result.json"),"utf8")).metrics;for(const [key,value] of Object.entries(metrics))assert.deepEqual(value,original[key])}assert.deepEqual(files.map(f=>crypto.createHash("sha256").update(fs.readFileSync(f)).digest("hex")),hashes);assert.equal(first.corrected_qualification.decision,"OFFLINE_QUALIFICATION_FAILED");assert.equal(first.corrected_qualification.gates.role_fidelity,false);assert.equal(first.corrected_qualification.gates.hard_boundary_regression.status,"QUALIFICATION_POLICY_DECISION_REQUIRED");assert.equal(first.ood_residual_failure_map.length,8);assert.equal(first.product_focus_audit.ood_v1.by_class.TIER,0)});
