import { describe, expect, it, vi } from "vitest";
import { PRODUCTION_ERP_PROFILES } from "../../connectors/generic.erp.adapter";
import { MES_PROFILE, MES_PROFILE_VERSION, MesConnectorError, createMesConnector, initializeMesConnector, validateMesConnectorConfig, type MesConnectorConfig, type MesLaneName } from "../../connectors/generic.mes.adapter";
import type { ConnectorExecutionAccess } from "../connector.access";

const NOW = Date.parse("2026-08-01T10:00:00.000Z");
const config: MesConnectorConfig = { profile: MES_PROFILE, profileVersion: MES_PROFILE_VERSION, baseUrl: "https://mes.example", healthPath: "/ready", tenantId: "tenant-1", companyId: "C1", ownerId: "owner-1", sourceSystem: "MES-1", sourceRegion: "EU", credentialReference: "secret://mes/readonly", authenticationProfile: "BEARER_TOKEN_V1", requestTimeoutMs: 100, maxResponseBytes: 100_000, profilePaths: { PRODUCTION_ORDERS: "/production-orders", MATERIAL_MOVEMENTS: "/material-movements", INVENTORY: "/inventory" } };
const rows = {
  PRODUCTION_ORDERS: { production_order_id: "P1", company_id: "C1", source_system: "MES-1", article: "FG1", output_article: "FG1", quantity: 5, unit: "EA", scheduled_at: "2026-08-01T09:00:00.000Z" },
  MATERIAL_MOVEMENTS: { movement_id: "M1", production_order_id: "P1", company_id: "C1", source_system: "MES-1", article: "RM1", quantity: 4, type: "CONSUMPTION", unit: "EA", occurred_at: "2026-08-01T09:00:00.000Z" },
  INVENTORY: { inventory_id: "I1", company_id: "C1", source_system: "MES-1", warehouse_id: "W1", sku: "RM1", quantity: 7, unit: "EA", observed_at: "2026-08-01T09:00:00.000Z" },
} as const;
const collections = { PRODUCTION_ORDERS: "productionOrders", MATERIAL_MOVEMENTS: "materialMovements", INVENTORY: "inventory" } as const;
const capabilities = { PRODUCTION_ORDERS: "read_production_plan", MATERIAL_MOVEMENTS: "read_movements", INVENTORY: "read_inventory" } as const;
function access(change: any = {}): ConnectorExecutionAccess { return { workload: { workloadId: "worker", tenantId: "tenant-1", authenticationId: "auth-1" }, credential: { credentialReference: "secret://mes/readonly", secret: "top-secret" }, dataPolicyAdmission: { decision: "ADMITTED", connectorIdentityId: "connector-identity:mes-production-rest", connectorRevision: 1, credentialReference: "secret://mes/readonly", authorizationReference: "auth-1", evaluatedAt: new Date(NOW).toISOString(), context: { contextId: "access-1", tenantId: "tenant-1", targetTenantId: "tenant-1", sourceSystem: "MES-1", sourceRegion: "EU", targetRegion: "EU", runtimeLocality: "TENANT_LOCAL", encryptionDomain: "EXECUTION_MEMORY", transportEvidence: { contextId: "access-1", connectorIdentityId: "connector-identity:mes-production-rest", scheme: "HTTPS", secure: true }, encryptionEvidence: { contextId: "access-1", connectorIdentityId: "connector-identity:mes-production-rest", domain: "EXECUTION_MEMORY", encryptedInTransit: true, encryptedAtRest: true }, ...change.context }, ...change } } as ConnectorExecutionAccess; }
const response = (name: MesLaneName, values: unknown[] = [rows[name]]) => new Response(JSON.stringify({ schema_version: PRODUCTION_ERP_PROFILES[name], source_system: "MES-1", [collections[name]]: values }), { headers: { "content-type": "application/json" } });
async function run(name: MesLaneName, fetcher: typeof fetch = async () => response(name)) { return createMesConnector(config, { fetch: fetcher, now: () => NOW }).execute(capabilities[name], { providerProfile: PRODUCTION_ERP_PROFILES[name] }, access()); }
async function denied(promise: Promise<unknown>, code: string) { try { await promise; throw new Error("expected denial"); } catch (error) { expect(error).toBeInstanceOf(MesConnectorError); expect((error as MesConnectorError).code).toBe(code); expect(JSON.stringify(error)).not.toContain("top-secret"); } }

describe("WU12E — Generic read-only MES connector", () => {
  it("does not register without configuration", () => expect(initializeMesConnector({})).toBe(false));
  it("registers complete configuration idempotently and rejects drift", () => { const env = { INDUSTRIAL_MES_PROFILE: MES_PROFILE, INDUSTRIAL_MES_PROFILE_VERSION: "1", INDUSTRIAL_MES_BASE_URL: "https://mes-init.example", INDUSTRIAL_MES_HEALTH_PATH: "/ready", INDUSTRIAL_MES_TENANT_ID: "tenant-init", INDUSTRIAL_MES_COMPANY_ID: "company-init", INDUSTRIAL_MES_OWNER_ID: "owner-init", INDUSTRIAL_MES_SOURCE_SYSTEM: "MES-INIT", INDUSTRIAL_MES_SOURCE_REGION: "EU", INDUSTRIAL_MES_CREDENTIAL_REFERENCE: "secret://mes/init", INDUSTRIAL_MES_AUTHENTICATION_PROFILE: "BEARER_TOKEN_V1", INDUSTRIAL_MES_REQUEST_TIMEOUT_MS: "100", INDUSTRIAL_MES_PRODUCTION_ORDERS_PATH: "/production-orders" }; expect(initializeMesConnector(env)).toBe(true); expect(initializeMesConnector(env)).toBe(true); expect(() => initializeMesConnector({ ...env, INDUSTRIAL_MES_PRODUCTION_ORDERS_PATH: "/changed" })).toThrow("Invalid MES connector configuration"); });
  it("validates and deeply freezes configuration", () => { const value = validateMesConnectorConfig(config); expect(Object.isFrozen(value)).toBe(true); expect(Object.isFrozen(value.profilePaths)).toBe(true); });
  it.each([["profile", "OTHER", "MES_PROFILE_UNSUPPORTED"], ["profileVersion", "2", "MES_PROFILE_VERSION_UNSUPPORTED"], ["baseUrl", "http://mes.example", "MES_CONFIGURATION_INVALID"], ["authenticationProfile", "BASIC", "MES_CONFIGURATION_INVALID"]] as const)("rejects invalid %s", (field, value, code) => { try { validateMesConnectorConfig({ ...config, [field]: value } as any); throw new Error("expected"); } catch (error) { expect((error as MesConnectorError).code).toBe(code); } });
  it("rejects empty and non-MES lanes", () => { expect(() => validateMesConnectorConfig({ ...config, profilePaths: {} })).toThrow("Invalid MES connector configuration"); try { validateMesConnectorConfig({ ...config, profilePaths: { ORDERS: "/orders" } } as any); } catch (error) { expect((error as MesConnectorError).code).toBe("MES_PROFILE_UNSUPPORTED"); } });
  it("declares only configured read capabilities", () => { const connector = createMesConnector({ ...config, profilePaths: { INVENTORY: "/inventory" } }); expect(connector.capabilities.map(c => c.id)).toEqual(["read_inventory"]); expect(connector.capabilities.map(c => c.id)).not.toContain("notify_supplier"); });
  it.each(Object.keys(rows) as MesLaneName[])("acquires and validates %s", async name => { const output = await run(name) as any; expect(output.providerProfile).toBe(PRODUCTION_ERP_PROFILES[name]); expect(output.mes).toEqual({ profile: MES_PROFILE, profileVersion: "1" }); expect(output.acquisition.connectorIdentityId).toBe("connector-identity:mes-production-rest"); expect(Object.isFrozen(output)).toBe(true); });
  it.each([["PRODUCTION_ORDERS", "movord", { order: "P1", article: "FG1", quantity: 5 }], ["MATERIAL_MOVEMENTS", "movmag", { order: "P1", article: "RM1", quantity: 4, type: "CONSUMPTION" }], ["INVENTORY", "inventory", { sku: "RM1", qty: 7 }]] as const)("reuses frozen cognition for %s", async (name, lane, expected) => { const output = await run(name) as any; expect(output.cognitionLane).toBe(lane); expect(output.cognitionRows).toEqual([expected]); });
  it("uses GET bearer authentication without exposing credentials", async () => { const fetcher = vi.fn<typeof fetch>(async (_url, init) => { expect(init?.method).toBe("GET"); expect(new Headers(init?.headers).get("Authorization")).toBe("Bearer top-secret"); return response("INVENTORY"); }); const output = await run("INVENTORY", fetcher); expect(JSON.stringify(output)).not.toContain("top-secret"); });
  it.each([[{ decision: "DENIED" }, "decision"], [{ credentialReference: "secret://other" }, "credential"], [{ context: { tenantId: "other" } }, "tenant"], [{ context: { transportEvidence: { ...access().dataPolicyAdmission.context.transportEvidence, secure: false } } }, "transport"]] as const)("fails closed for invalid %s admission", async (change) => denied(createMesConnector(config).execute("read_inventory", {}, access(change)), "MES_ACQUISITION_FAILED"));
  it.each(["POST", "PUT", "PATCH", "DELETE"])("prohibits %s", async method => denied(createMesConnector(config).execute("read_inventory", { method }, access()), "MES_WRITE_OPERATION_PROHIBITED"));
  it("rejects unconfigured capabilities and unsupported profiles", async () => { const connector = createMesConnector({ ...config, profilePaths: { INVENTORY: "/inventory" } }); await denied(connector.execute("read_movements", {}, access()), "MES_CAPABILITY_NOT_CONFIGURED"); await denied(createMesConnector(config).execute("read_movements", { providerProfile: PRODUCTION_ERP_PROFILES.MOVEMENTS }, access()), "MES_PROFILE_UNSUPPORTED"); });
  it.each([["missing", [{}], "MES_REQUIRED_FIELD_MISSING"], ["unknown", [{ ...rows.INVENTORY, extra: true }], "MES_UNKNOWN_FIELD"], ["numeric string", [{ ...rows.INVENTORY, quantity: "7" }], "MES_NUMERIC_FORMAT_INVALID"], ["duplicate", [rows.INVENTORY, rows.INVENTORY], "MES_DUPLICATE_IDENTITY"]] as const)("fails closed for %s payload", async (_label, values, code) => denied(run("INVENTORY", async () => response("INVENTORY", values as unknown[])), code));
  it("rejects MES semantics without a frozen consumer", async () => denied(run("MATERIAL_MOVEMENTS", async () => response("MATERIAL_MOVEMENTS", [{ ...rows.MATERIAL_MOVEMENTS, type: "OPERATION_COMPLETION" }])), "MES_CAPABILITY_PAYLOAD_MISMATCH"));
  it("enforces source identity", async () => denied(run("INVENTORY", async () => response("INVENTORY", [{ ...rows.INVENTORY, source_system: "OTHER" }])), "MES_SOURCE_CONTRADICTION"));
  it("performs bounded sanitized health checks", async () => { const fetcher = vi.fn<typeof fetch>(async () => new Response(null, { status: 204 })); const health = await createMesConnector(config, { fetch: fetcher, now: () => NOW }).health(); expect(health).toMatchObject({ ok: true, connectorIdentityId: "connector-identity:mes-production-rest" }); expect(fetcher.mock.calls[0]![1]?.method).toBe("HEAD"); });
  it("maps timeout, redirect, content type and size failures", async () => { await denied(run("INVENTORY", async () => new Response(null, { status: 302 })), "MES_REDIRECT_PROHIBITED"); await denied(run("INVENTORY", async () => new Response("x", { headers: { "content-type": "text/plain" } })), "MES_CONTENT_TYPE_INVALID"); await denied(createMesConnector({ ...config, maxResponseBytes: 4 }, { fetch: async () => response("INVENTORY"), now: () => NOW }).execute("read_inventory", {}, access()), "MES_RESPONSE_TOO_LARGE"); });
  it("defensively copies and deeply freezes output", async () => { const row = structuredClone(rows.INVENTORY); const output = await run("INVENTORY", async () => response("INVENTORY", [row])) as any; row.sku = "changed"; expect(output.inventory[0].sku).toBe("RM1"); expect(Object.isFrozen(output.inventory[0])).toBe(true); });
  it("contains no ORS, execution-event, upload, or external-authority surface", async () => { const text = JSON.stringify(await run("PRODUCTION_ORDERS")); expect(text).not.toMatch(/OperationalReality|operationCompletion|machineStatus|AuthoritativeExternalData|uploadId/); });
});
