import { describe, expect, it, vi } from "vitest";
import { OPERATIONAL_EDGE_PROFILE, OPERATIONAL_EDGE_PROFILE_VERSION, OPERATIONAL_EDGE_REPRESENTATION, OperationalEdgeConnectorError, createOperationalEdgeConnector, initializeOperationalEdgeConnector, validateOperationalEdgeConnectorConfig, type OperationalEdgeConnectorConfig } from "../../connectors/generic.operational-edge.adapter";
import type { ConnectorExecutionAccess } from "../connector.access";

const NOW = Date.parse("2026-08-02T10:00:00.000Z");
const config: OperationalEdgeConnectorConfig = { profile: OPERATIONAL_EDGE_PROFILE, profileVersion: OPERATIONAL_EDGE_PROFILE_VERSION, baseUrl: "https://edge.example/api", observationsPath: "/observations", healthPath: "/ready", tenantId: "tenant-1", companyId: "company-1", ownerId: "owner-1", sourceSystem: "EDGE-GATEWAY-1", sourceRegion: "EU", credentialReference: "secret://edge/readonly", authenticationProfile: "BEARER_TOKEN_V1", requestTimeoutMs: 100, maxResponseBytes: 100_000, maxObservations: 10 };
const observation = { observation_id: "OBS-1", source_asset_id: "ASSET-1", observed_at: "2026-08-02T09:59:00.000Z", payload: { tag: "temperature", value: 21.5, quality: "GOOD", nested: { raw: true }, samples: [1, 2, null] } };
const response = (observations: unknown[] = [observation], change: Record<string, unknown> = {}) => new Response(JSON.stringify({ schema_version: OPERATIONAL_EDGE_REPRESENTATION, source_system: "EDGE-GATEWAY-1", observations, ...change }), { headers: { "content-type": "application/json" } });
function access(change: any = {}): ConnectorExecutionAccess { return { workload: { workloadId: "worker", tenantId: "tenant-1", authenticationId: "auth-1" }, credential: { credentialReference: "secret://edge/readonly", secret: "top-secret" }, dataPolicyAdmission: { decision: "ADMITTED", connectorIdentityId: "connector-identity:operational-edge-production-rest", connectorRevision: 1, capabilityId: "read_edge_observations", credentialReference: "secret://edge/readonly", authorizationReference: "auth-1", admittedAt: new Date(NOW).toISOString(), context: { contextId: "access-1", tenantId: "tenant-1", targetTenantId: "tenant-1", sourceSystem: "EDGE-GATEWAY-1", sourceRegion: "EU", targetRegion: "EU", runtimeLocality: "TENANT_LOCAL", encryptionDomain: "EXECUTION_MEMORY", transportEvidence: { contextId: "access-1", connectorIdentityId: "connector-identity:operational-edge-production-rest", scheme: "HTTPS", secure: true }, encryptionEvidence: { contextId: "access-1", connectorIdentityId: "connector-identity:operational-edge-production-rest", domain: "EXECUTION_MEMORY", encryptedInTransit: true, encryptedAtRest: true }, ...change.context }, ...change } } as ConnectorExecutionAccess; }
async function run(fetcher: typeof fetch = async () => response()) { return createOperationalEdgeConnector(config, { fetch: fetcher, now: () => NOW }).execute("read_edge_observations", {}, access()); }
async function denied(promise: Promise<unknown>, code: string) { try { await promise; throw new Error("expected denial"); } catch (error) { expect(error).toBeInstanceOf(OperationalEdgeConnectorError); expect((error as OperationalEdgeConnectorError).code).toBe(code); expect(JSON.stringify(error)).not.toContain("top-secret"); } }

describe("WU12G — Generic read-only Operational Edge connector", () => {
  it("does not register without configuration", () => expect(initializeOperationalEdgeConnector({})).toBe(false));
  it("registers complete configuration idempotently and rejects drift", () => { const env = { INDUSTRIAL_EDGE_PROFILE: OPERATIONAL_EDGE_PROFILE, INDUSTRIAL_EDGE_PROFILE_VERSION: "1", INDUSTRIAL_EDGE_BASE_URL: "https://edge-init.example", INDUSTRIAL_EDGE_OBSERVATIONS_PATH: "/observations", INDUSTRIAL_EDGE_HEALTH_PATH: "/ready", INDUSTRIAL_EDGE_TENANT_ID: "tenant-init", INDUSTRIAL_EDGE_COMPANY_ID: "company-init", INDUSTRIAL_EDGE_OWNER_ID: "owner-init", INDUSTRIAL_EDGE_SOURCE_SYSTEM: "EDGE-INIT", INDUSTRIAL_EDGE_SOURCE_REGION: "EU", INDUSTRIAL_EDGE_CREDENTIAL_REFERENCE: "secret://edge/init", INDUSTRIAL_EDGE_AUTHENTICATION_PROFILE: "BEARER_TOKEN_V1", INDUSTRIAL_EDGE_REQUEST_TIMEOUT_MS: "100" }; expect(initializeOperationalEdgeConnector(env)).toBe(true); expect(initializeOperationalEdgeConnector(env)).toBe(true); expect(() => initializeOperationalEdgeConnector({ ...env, INDUSTRIAL_EDGE_OBSERVATIONS_PATH: "/changed" })).toThrow("Invalid operational edge connector configuration"); });
  it("validates, normalizes, and deeply freezes configuration", () => { const value = validateOperationalEdgeConnectorConfig({ ...config, baseUrl: "https://edge.example/api/", observationsPath: "/observations/" }); expect(value.baseUrl).toBe("https://edge.example/api"); expect(value.observationsPath).toBe("/observations"); expect(Object.isFrozen(value)).toBe(true); });
  it.each([["profile", "OTHER", "EDGE_PROFILE_UNSUPPORTED"], ["profileVersion", "2", "EDGE_PROFILE_VERSION_UNSUPPORTED"], ["baseUrl", "http://edge.example", "EDGE_CONFIGURATION_INVALID"], ["observationsPath", "../observations", "EDGE_ENDPOINT_INVALID"], ["authenticationProfile", "BASIC", "EDGE_AUTHENTICATION_PROFILE_INVALID"], ["requestTimeoutMs", 0, "EDGE_CONFIGURATION_INVALID"], ["maxObservations", 0, "EDGE_CONFIGURATION_INVALID"]] as const)("rejects invalid %s", (field, value, code) => { try { validateOperationalEdgeConnectorConfig({ ...config, [field]: value } as any); throw new Error("expected"); } catch (error) { expect((error as OperationalEdgeConnectorError).code).toBe(code); } });
  it("declares only acquisition-only read capability", () => { const connector = createOperationalEdgeConnector(config); expect(connector.capabilities.map(c => c.id)).toEqual(["read_edge_observations"]); expect(connector.capabilities[0]?.verb).toBe("read"); });
  it("acquires raw observations without interpreting their payload", async () => { const output = await run() as any; expect(output.observations).toEqual([observation]); expect(output.providerProfile).toBe(OPERATIONAL_EDGE_PROFILE); expect(output.sourceRepresentation).toBe(OPERATIONAL_EDGE_REPRESENTATION); expect(output.acquisition.connectorIdentityId).toBe("connector-identity:operational-edge-production-rest"); });
  it("does not create cognition, canonical facts, ORS, or composition", async () => { const output = await run() as any; expect(output).not.toHaveProperty("cognitionLane"); expect(output).not.toHaveProperty("cognitionRows"); expect(output).not.toHaveProperty("canonicalFacts"); expect(output).not.toHaveProperty("operationalReality"); expect(output).not.toHaveProperty("sources"); });
  it("uses authenticated GET without exposing credentials", async () => { const fetcher = vi.fn<typeof fetch>(async (_url, init) => { expect(init?.method).toBe("GET"); expect(init?.redirect).toBe("error"); expect(new Headers(init?.headers).get("Authorization")).toBe("Bearer top-secret"); return response(); }); const output = await run(fetcher); expect(JSON.stringify(output)).not.toContain("top-secret"); });
  it.each(["POST", "PUT", "PATCH", "DELETE"])("prohibits %s", async method => denied(createOperationalEdgeConnector(config).execute("read_edge_observations", { method }, access()), "EDGE_WRITE_OPERATION_PROHIBITED"));
  it("rejects other capabilities and acquisition parameters", async () => { await denied(createOperationalEdgeConnector(config).execute("read_inventory", {}, access()), "EDGE_CAPABILITY_PAYLOAD_MISMATCH"); await denied(createOperationalEdgeConnector(config).execute("read_edge_observations", { filter: "machine" }, access()), "EDGE_CAPABILITY_PAYLOAD_MISMATCH"); });
  it.each([[{ decision: "DENIED" }, "decision"], [{ capabilityId: "read_inventory" }, "capability"], [{ credentialReference: "secret://other" }, "credential"], [{ context: { tenantId: "other" } }, "tenant"], [{ context: { transportEvidence: { ...access().dataPolicyAdmission.context.transportEvidence, secure: false } } }, "transport"]] as const)("fails closed for invalid %s admission", async (change, _label) => denied(createOperationalEdgeConnector(config).execute("read_edge_observations", {}, access(change)), "EDGE_ACQUISITION_FAILED"));
  it.each([["missing observation field", [{}], {}, "EDGE_REQUIRED_FIELD_MISSING"], ["unknown observation field", [{ ...observation, meaning: "RUNNING" }], {}, "EDGE_UNKNOWN_FIELD"], ["invalid date", [{ ...observation, observed_at: "today" }], {}, "EDGE_DATE_FORMAT_INVALID"], ["array payload", [{ ...observation, payload: [] }], {}, "EDGE_VALUE_TYPE_INVALID"], ["duplicate identity", [observation, observation], {}, "EDGE_DUPLICATE_OBSERVATION"], ["source contradiction", [observation], { source_system: "OTHER" }, "EDGE_SOURCE_CONTRADICTION"], ["unknown envelope field", [observation], { interpretation: "running" }, "EDGE_UNKNOWN_FIELD"], ["wrong schema version", [observation], { schema_version: "V2" }, "EDGE_PROFILE_VERSION_UNSUPPORTED"]] as const)("rejects %s", async (_label, rows, change, code) => denied(run(async () => response(rows as unknown as unknown[], change as Record<string, unknown>)), code));
  it("enforces observation count and response size", async () => { await denied(createOperationalEdgeConnector({ ...config, maxObservations: 1 }, { fetch: async () => response([observation, { ...observation, observation_id: "OBS-2" }]), now: () => NOW }).execute("read_edge_observations", {}, access()), "EDGE_OBSERVATION_LIMIT_EXCEEDED"); await denied(createOperationalEdgeConnector({ ...config, maxResponseBytes: 4 }, { fetch: async () => response(), now: () => NOW }).execute("read_edge_observations", {}, access()), "EDGE_RESPONSE_TOO_LARGE"); });
  it("rejects redirects, content type, and provider unavailability", async () => { await denied(run(async () => new Response(null, { status: 302 })), "EDGE_REDIRECT_PROHIBITED"); await denied(run(async () => new Response("x", { headers: { "content-type": "text/plain" } })), "EDGE_CONTENT_TYPE_INVALID"); await denied(run(async () => { throw new Error("infrastructure secret"); }), "EDGE_PROVIDER_UNREACHABLE"); });
  it("maps provider timeout", async () => denied(createOperationalEdgeConnector({ ...config, requestTimeoutMs: 1 }, { now: () => NOW, fetch: async (_url, init) => new Promise((_resolve, reject) => init?.signal?.addEventListener("abort", () => reject(new Error("secret")))) }).execute("read_edge_observations", {}, access()), "EDGE_PROVIDER_TIMEOUT"));
  it("performs sanitized HEAD health without acquiring observations", async () => { const fetcher = vi.fn<typeof fetch>(async () => new Response(null, { status: 204 })); const health = await createOperationalEdgeConnector(config, { fetch: fetcher, now: () => NOW }).health(); expect(health).toMatchObject({ ok: true, connectorIdentityId: "connector-identity:operational-edge-production-rest" }); expect(fetcher.mock.calls[0]![1]?.method).toBe("HEAD"); expect(JSON.stringify(health)).not.toContain("edge.example"); });
  it("defensively copies and deeply freezes output", async () => { const row = structuredClone(observation); const output = await run(async () => response([row])) as any; row.payload.tag = "changed"; expect(output.observations[0].payload.tag).toBe("temperature"); expect(Object.isFrozen(output)).toBe(true); expect(Object.isFrozen(output.observations[0].payload.nested)).toBe(true); });
});
