import { describe, expect, it } from "vitest";
import { preserveGovernedOperationsFactV1, type GovernedOperationsFactFamilyV1 } from "../preservation/governed.operational.fact.preservation.v1";

const acquisition={tenantId:"tenant-1",companyId:"company-1",sourceSystem:"ERP-1",connectorIdentityId:"connector-1",connectorRevision:1,acquisitionReference:"acquisition-1",authorizationReference:"authorization-1",acquiredAt:"2026-08-13T10:00:00.000Z",capabilityId:"read",sourceRepresentation:"PROFILE_V1"};
const rows:Record<GovernedOperationsFactFamilyV1,Record<string,unknown>>={
  ORDERS:{external_order_id:"O1",external_order_version:"2",sku:"SKU1",quantity_value:5,quantity_unit:"EA",status:"OPEN",observed_at:"2026-08-13T09:00:00.000Z",effective_at:"2026-08-13T08:00:00.000Z",due_at:"2026-08-20T10:00:00.000Z"},
  INVENTORY:{inventory_id:"I1",warehouse_id:"W1",sku:"SKU1",quantity:7,unit:"KG",observed_at:"2026-08-13T09:00:00.000Z"},
  MOVEMENTS:{movement_id:"M1",sku:"SKU1",quantity:3,unit:"KG",type:"RECEIPT",occurred_at:"2026-08-13T07:00:00.000Z"},
  PRODUCTION_ORDERS:{production_order_id:"P1",article:"FG1",output_article:"FG1",quantity:4,unit:"EA",scheduled_at:"2026-08-14T06:00:00.000Z"},
  MATERIAL_MOVEMENTS:{movement_id:"MM1",production_order_id:"P1",article:"RM1",quantity:2,unit:"KG",type:"CONSUMPTION",occurred_at:"2026-08-13T06:00:00.000Z"},
  MASTER_BOM:{parent:"FG1",component:"RM1",ratio:2,unit:"EA",revision:"R3",valid_from:"2026-08-01T00:00:00.000Z"},
};
const fact=(family:GovernedOperationsFactFamilyV1,a=acquisition)=>preserveGovernedOperationsFactV1(family,rows[family],a);

describe("PRESSURE-TEMPORAL-PRESERVATION-WU1",()=>{
  it("preserves governed order unit, dates, identity and quantity",async()=>{const x=await fact("ORDERS");expect(x.semantic).toEqual(expect.objectContaining({order_id:"O1",order_version:"2",quantity:{value:5,source_unit:"EA",canonical_unit:"EACH"},observed_at:rows.ORDERS.observed_at,effective_at:rows.ORDERS.effective_at,due_at:rows.ORDERS.due_at}));});
  it("binds order subject and plan element without changing ORDER",async()=>{const x=await fact("ORDERS");expect(x.role_bindings.subject).toMatchObject({subject_kind:"ORDER",subject_ref:"order:O1"});expect(x.role_bindings.plan_element?.plan_element_ref).toBe("operations-order:O1");});
  it("preserves delivery deadline without component-requirement semantics",async()=>{const x=await fact("ORDERS");expect(x.role_bindings.temporal?.temporal_role).toBe("REQUIREMENT_DEADLINE");expect(JSON.stringify(x)).not.toMatch(/component_requirement|decision_window|consequence_onset/);});
  it("preserves inventory unit, warehouse and observed time",async()=>{const x=await fact("INVENTORY");expect(x.semantic).toMatchObject({warehouse_id:"W1",quantity:{value:7,source_unit:"KG"},observed_at:rows.INVENTORY.observed_at});expect((x.semantic as any).quantity).not.toHaveProperty("canonical_unit");});
  it("binds governed inventory as observation only",async()=>{const x=await fact("INVENTORY");expect(x.role_bindings.observation).toMatchObject({role:"OBSERVATION",observed_at:rows.INVENTORY.observed_at});expect(x.role_bindings).not.toHaveProperty("temporal");});
  it("preserves movement unit, type, identity and occurred time",async()=>{const x=await fact("MOVEMENTS");expect(x.semantic).toMatchObject({movement_id:"M1",movement_type:"RECEIPT",quantity:{value:3,source_unit:"KG"},occurred_at:rows.MOVEMENTS.occurred_at});});
  it("binds movement deterministically as observation and behavioral event",async()=>{const a=await fact("MOVEMENTS"),b=await fact("MOVEMENTS");expect(a).toEqual(b);expect(a.role_bindings.evidence_roles).toEqual(["OBSERVATION","BEHAVIORAL_EVENT"]);});
  it("preserves production-order unit and scheduled time",async()=>{const x=await fact("PRODUCTION_ORDERS");expect(x.semantic).toMatchObject({production_order_id:"P1",quantity:{value:4,source_unit:"EA",canonical_unit:"EACH"},scheduled_at:rows.PRODUCTION_ORDERS.scheduled_at});});
  it("does not reinterpret scheduled time",async()=>{const x=await fact("PRODUCTION_ORDERS");expect(x.role_bindings).not.toHaveProperty("temporal");expect(JSON.stringify(x)).not.toMatch(/availability_time|requirement_time|completion_time/);});
  it("binds production order plan element against exact SKU subject",async()=>{const x=await fact("PRODUCTION_ORDERS");expect(x.role_bindings.subject).toMatchObject({subject_kind:"SKU",subject_ref:"sku:FG1"});expect(x.role_bindings.plan_element?.plan_element_ref).toBe("production-order:P1");});
  it("preserves material movement order, unit, type, and time",async()=>{const x=await fact("MATERIAL_MOVEMENTS");expect(x.semantic).toMatchObject({movement_id:"MM1",production_order_id:"P1",article:"RM1",quantity:{value:2,source_unit:"KG"},movement_type:"CONSUMPTION",occurred_at:rows.MATERIAL_MOVEMENTS.occurred_at});});
  it("preserves BOM revision, validity, unit and ratio",async()=>{const x=await fact("MASTER_BOM");expect(x.semantic).toMatchObject({parent:"FG1",component:"RM1",ratio:2,source_unit:"EA",canonical_unit:"EACH",revision:"R3",valid_from:rows.MASTER_BOM.valid_from});});
  it("binds BOM as domain-owned structural plan relationship",async()=>{const x=await fact("MASTER_BOM");expect(x.role_bindings.plan_relationship).toMatchObject({role:"PLAN_RELATIONSHIP",relationship_kind_ref:"operations-relationship:BOM_COMPONENT"});expect(x.role_bindings.evidence_roles).toEqual(["PLAN_RELATIONSHIP","STRUCTURAL_RELATIONSHIP"]);});
  it("changes governed identity and role binding on provider substitution",async()=>{const a=await fact("ORDERS"),b=await fact("ORDERS",{...acquisition,sourceSystem:"ERP-2"});expect(a.fact_digest).not.toBe(b.fact_digest);expect(a.role_bindings.plan_element?.role_digest).not.toBe(b.role_bindings.plan_element?.role_digest);});
  it("keeps source fact identity stable across later acquisition while preserving new provenance",async()=>{const a=await fact("ORDERS"),b=await fact("ORDERS",{...acquisition,acquiredAt:"2026-08-13T11:00:00.000Z"});expect(a.fact_id).toBe(b.fact_id);expect(a.fact_digest).not.toBe(b.fact_digest);});
  it("does not introduce new unit conversion or defaults",async()=>{for(const family of ["INVENTORY","MOVEMENTS","MATERIAL_MOVEMENTS"] as const){const x=await fact(family);expect((x.semantic as any).quantity.source_unit).toBe("KG");expect((x.semantic as any).quantity).not.toHaveProperty("canonical_unit");}});
  it("keeps role artifacts reference-oriented",async()=>{const x=await fact("ORDERS");const role=JSON.stringify(x.role_bindings.plan_element);expect(role).not.toMatch(/quantity|due_at|status|warehouse|scheduled_at/);});
  it("is content-free and non-authorizing",async()=>{const x=await fact("ORDERS");expect(x).toMatchObject({grants_execution:false,observational_only:true});expect(JSON.stringify(x)).not.toMatch(/raw_email|chat_text|prompt|credential|provider_response/i);});
  it("introduces no temporal cognition output",async()=>{for(const family of Object.keys(rows) as GovernedOperationsFactFamilyV1[]){const x=await fact(family);expect(x).not.toHaveProperty("slack");expect(x).not.toHaveProperty("decision_window");expect(x).not.toHaveProperty("pressure_level");}});
});
