import { describe, expect, it, vi } from "vitest";
import { OPERATIONAL_EDGE_PROFILE, OPERATIONAL_EDGE_PROFILE_VERSION, OPERATIONAL_EDGE_REPRESENTATION, OperationalEdgeConnectorError } from "../../connectors/generic.operational-edge.adapter";
import { INDUSTRIAL_SIGNAL_GATEWAY_PROFILE, INDUSTRIAL_SIGNAL_GATEWAY_PROFILE_VERSION, IndustrialSignalGatewayError, createIndustrialSignalGatewayProfile, initializeIndustrialSignalGatewayProfile, validateIndustrialSignalGatewayConfig, type IndustrialSignalGatewayConfig } from "../../connectors/industrial.signal.gateway.profile";
import type { ConnectorExecutionAccess } from "../connector.access";

const NOW = Date.parse("2026-08-02T12:00:00.000Z");
const config: IndustrialSignalGatewayConfig = { profile: INDUSTRIAL_SIGNAL_GATEWAY_PROFILE, profileVersion: INDUSTRIAL_SIGNAL_GATEWAY_PROFILE_VERSION, edge: { profile: OPERATIONAL_EDGE_PROFILE, profileVersion: OPERATIONAL_EDGE_PROFILE_VERSION, baseUrl: "https://signals.example", observationsPath: "/observations", healthPath: "/ready", tenantId: "tenant-1", companyId: "company-1", ownerId: "owner-1", sourceSystem: "SIGNAL-FACADE-1", sourceRegion: "EU", credentialReference: "secret://signals/readonly", authenticationProfile: "BEARER_TOKEN_V1", requestTimeoutMs: 100, maxResponseBytes: 100_000, maxObservations: 10 } };
const signal = { observation_id: "OBS-1", source_asset_id: "ASSET-1", observed_at: "2026-08-02T11:59:00.000Z", payload: { signal_id: "temperature", value_type: "NUMBER", value: 21.5, unit: "C", quality: "GOOD" } };
const response = (observations: unknown[] = [signal]) => new Response(JSON.stringify({ schema_version: OPERATIONAL_EDGE_REPRESENTATION, source_system: "SIGNAL-FACADE-1", observations }), { headers: { "content-type": "application/json" } });
function access(change: any = {}): ConnectorExecutionAccess { return { workload: { workloadId: "worker", tenantId: "tenant-1", authenticationId: "auth-1" }, credential: { credentialReference: "secret://signals/readonly", secret: "top-secret" }, dataPolicyAdmission: { decision: "ADMITTED", connectorIdentityId: "connector-identity:operational-edge-production-rest", connectorRevision: 1, capabilityId: "read_edge_observations", credentialReference: "secret://signals/readonly", authorizationReference: "auth-1", admittedAt: new Date(NOW).toISOString(), context: { contextId: "access-1", tenantId: "tenant-1", targetTenantId: "tenant-1", sourceSystem: "SIGNAL-FACADE-1", sourceRegion: "EU", targetRegion: "EU", runtimeLocality: "TENANT_LOCAL", encryptionDomain: "EXECUTION_MEMORY", transportEvidence: { contextId: "access-1", connectorIdentityId: "connector-identity:operational-edge-production-rest", scheme: "HTTPS", secure: true }, encryptionEvidence: { contextId: "access-1", connectorIdentityId: "connector-identity:operational-edge-production-rest", domain: "EXECUTION_MEMORY", encryptedInTransit: true, encryptedAtRest: true }, ...change.context }, ...change } } as ConnectorExecutionAccess; }
async function run(observations: unknown[] = [signal], fetcher: typeof fetch = async () => response(observations)) { return createIndustrialSignalGatewayProfile(config, { fetch: fetcher, now: () => NOW }).execute("read_edge_observations", {}, access()); }
async function denied(promise: Promise<unknown>, code: string, kind: "signal" | "edge" = "signal") { try { await promise; throw new Error("expected denial"); } catch (error) { expect(error).toBeInstanceOf(kind === "signal" ? IndustrialSignalGatewayError : OperationalEdgeConnectorError); expect((error as any).code).toBe(code); expect(JSON.stringify(error)).not.toContain("top-secret"); } }

describe("WU12H — Industrial Signal Gateway provider profile", () => {
  it("does not register without configuration", () => expect(initializeIndustrialSignalGatewayProfile({})).toBe(false));
  it("registers complete configuration idempotently and rejects drift", () => { const env = { INDUSTRIAL_SIGNAL_GATEWAY_PROFILE: INDUSTRIAL_SIGNAL_GATEWAY_PROFILE, INDUSTRIAL_SIGNAL_GATEWAY_PROFILE_VERSION: "1", INDUSTRIAL_SIGNAL_GATEWAY_BASE_URL: "https://signal-init.example", INDUSTRIAL_SIGNAL_GATEWAY_OBSERVATIONS_PATH: "/observations", INDUSTRIAL_SIGNAL_GATEWAY_HEALTH_PATH: "/ready", INDUSTRIAL_SIGNAL_GATEWAY_TENANT_ID: "tenant-init", INDUSTRIAL_SIGNAL_GATEWAY_COMPANY_ID: "company-init", INDUSTRIAL_SIGNAL_GATEWAY_OWNER_ID: "owner-init", INDUSTRIAL_SIGNAL_GATEWAY_SOURCE_SYSTEM: "SIGNAL-INIT", INDUSTRIAL_SIGNAL_GATEWAY_SOURCE_REGION: "EU", INDUSTRIAL_SIGNAL_GATEWAY_CREDENTIAL_REFERENCE: "secret://signal/init", INDUSTRIAL_SIGNAL_GATEWAY_AUTHENTICATION_PROFILE: "BEARER_TOKEN_V1", INDUSTRIAL_SIGNAL_GATEWAY_REQUEST_TIMEOUT_MS: "100" }; expect(initializeIndustrialSignalGatewayProfile(env)).toBe(true); expect(initializeIndustrialSignalGatewayProfile(env)).toBe(true); try { initializeIndustrialSignalGatewayProfile({ ...env, INDUSTRIAL_SIGNAL_GATEWAY_OBSERVATIONS_PATH: "/changed" }); throw new Error("expected"); } catch (error) { expect((error as IndustrialSignalGatewayError).code).toBe("SIGNAL_CONFIGURATION_INVALID"); } });
  it("validates and deeply freezes profile configuration", () => { const value = validateIndustrialSignalGatewayConfig(config); expect(Object.isFrozen(value)).toBe(true); expect(Object.isFrozen(value.edge)).toBe(true); });
  it.each([["profile", "OTHER", "SIGNAL_PROFILE_UNSUPPORTED"], ["profileVersion", "2", "SIGNAL_PROFILE_VERSION_UNSUPPORTED"]] as const)("rejects invalid %s", (field, value, code) => { try { validateIndustrialSignalGatewayConfig({ ...config, [field]: value } as any); throw new Error("expected"); } catch (error) { expect((error as IndustrialSignalGatewayError).code).toBe(code); } });
  it("reuses the frozen connector identity, capability, policy binding, and health", async () => { const fetcher = vi.fn<typeof fetch>(async () => new Response(null, { status: 204 })); const connector = createIndustrialSignalGatewayProfile(config, { fetch: fetcher, now: () => NOW }); expect(connector.id).toBe("operational-edge-production-rest"); expect(connector.identity.identityId).toBe("connector-identity:operational-edge-production-rest"); expect(connector.capabilities.map(c => c.id)).toEqual(["read_edge_observations"]); expect(await connector.health()).toMatchObject({ ok: true, connectorIdentityId: connector.identity.identityId }); expect(fetcher.mock.calls[0]![1]?.method).toBe("HEAD"); });
  it.each([["BOOLEAN", true], ["NUMBER", 12.5], ["STRING", "operator-note"], ["STATE", "RUNNING"]] as const)("accepts typed %s scalar without interpreting it", async (value_type, value) => { const output = await run([{ ...signal, payload: { signal_id: "machine.signal", value_type, value } }]) as any; expect(output.observations[0].payload).toEqual({ signal_id: "machine.signal", value_type, value }); expect(output.observationProfile).toEqual({ profile: INDUSTRIAL_SIGNAL_GATEWAY_PROFILE, profileVersion: "1" }); });
  it.each([["BOOLEAN", 1], ["NUMBER", "12.5"], ["STRING", false], ["STATE", 1]] as const)("rejects mismatched %s values", async (value_type, value) => denied(run([{ ...signal, payload: { signal_id: "s", value_type, value } }]), "SIGNAL_VALUE_INVALID"));
  it("preserves optional unit and quality without defaulting them", async () => { const withEvidence = await run() as any; expect(withEvidence.observations[0].payload).toMatchObject({ unit: "C", quality: "GOOD" }); const absent = await run([{ ...signal, payload: { signal_id: "door", value_type: "BOOLEAN", value: true } }]) as any; expect(absent.observations[0].payload).not.toHaveProperty("unit"); expect(absent.observations[0].payload).not.toHaveProperty("quality"); });
  it.each([[{ value_type: "BINARY", value: "x" }, "SIGNAL_VALUE_TYPE_UNSUPPORTED"], [{ value_type: "NUMBER" }, "SIGNAL_REQUIRED_FIELD_MISSING"], [{ value_type: "STATE", value: "X", provider_state: 7 }, "SIGNAL_UNKNOWN_FIELD"], [{ value_type: "NUMBER", value: 1, unit: "degrees C" }, "SIGNAL_UNIT_INVALID"], [{ value_type: "NUMBER", value: 1, quality: "VALID" }, "SIGNAL_QUALITY_UNSUPPORTED"], [{ value_type: "STRING", value: "x".repeat(1025) }, "SIGNAL_STRING_LIMIT_EXCEEDED"], [{ value_type: "STATE", value: "x".repeat(129) }, "SIGNAL_STRING_LIMIT_EXCEEDED"], [{ value_type: "STRING", value: { nested: true } }, "SIGNAL_VALUE_INVALID"]] as const)("rejects invalid signal payload", async (change, code) => denied(run([{ ...signal, payload: { signal_id: "signal", ...change } }]), code));
  it("rejects missing and malformed signal identifiers", async () => { await denied(run([{ ...signal, payload: { value_type: "NUMBER", value: 1 } }]), "SIGNAL_REQUIRED_FIELD_MISSING"); await denied(run([{ ...signal, payload: { signal_id: "bad id", value_type: "NUMBER", value: 1 } }]), "SIGNAL_IDENTIFIER_INVALID"); });
  it("inherits WU12G authentication, read-only, source, and envelope failures", async () => { await denied(createIndustrialSignalGatewayProfile(config).execute("read_edge_observations", { method: "POST" }, access()), "EDGE_WRITE_OPERATION_PROHIBITED", "edge"); await denied(run([signal], async () => new Response(JSON.stringify({ schema_version: OPERATIONAL_EDGE_REPRESENTATION, source_system: "OTHER", observations: [signal] }), { headers: { "content-type": "application/json" } })), "EDGE_SOURCE_CONTRADICTION", "edge"); });
  it("uses bearer GET and preserves frozen acquisition evidence", async () => { const fetcher = vi.fn<typeof fetch>(async (_url, init) => { expect(init?.method).toBe("GET"); expect(new Headers(init?.headers).get("Authorization")).toBe("Bearer top-secret"); return response(); }); const output = await run([signal], fetcher) as any; expect(output.acquisition).toMatchObject({ connectorIdentityId: "connector-identity:operational-edge-production-rest", sourceSystem: "SIGNAL-FACADE-1", capabilityId: "read_edge_observations" }); expect(JSON.stringify(output)).not.toContain("top-secret"); });
  it("produces no cognition, canonical facts, ORS, composition, or production load", async () => { const output = await run() as any; expect(output).not.toHaveProperty("cognitionLane"); expect(output).not.toHaveProperty("cognitionRows"); expect(output).not.toHaveProperty("canonicalFacts"); expect(output).not.toHaveProperty("operationalReality"); expect(output).not.toHaveProperty("sources"); expect(JSON.stringify(output)).not.toContain("PRODUCTION_LOAD"); });
  it("defensively copies and deeply freezes the validated result", async () => { const row = structuredClone(signal); const output = await run([row]) as any; row.payload.value = 99; expect(output.observations[0].payload.value).toBe(21.5); expect(Object.isFrozen(output)).toBe(true); expect(Object.isFrozen(output.observations[0].payload)).toBe(true); });
});
