import { describe, expect, expectTypeOf, it } from "vitest";
import { bindOperationalSignalsToScopeV1, createOperationalSignalEvaluationScopeV1 } from "../../cockpit/operational.signal.evaluation.scope.v1";
import type { CanonicalOrderFact } from "../canonicalization/authoritative.order.fact";
import { bindOperationsOrderDeliveryCommitmentV1, type OperationsProtectedObjectiveStateV1 } from "../cognition/operations.protected.objective.v1";

function order(overrides:Partial<CanonicalOrderFact["order"]>={}):CanonicalOrderFact{return {factId:"industrial-order:order-1",factFamily:"INDUSTRIAL_ORDER",schemaVersion:"1.0.0",owner:{tenantId:"tenant-1",companyId:"company-1",ownerId:"owner-1"},source:{systemId:"system-1",externalObjectId:"O1",externalObjectVersion:"2"},observedAt:"2026-08-13T09:00:00.000Z",effectiveAt:"2026-08-13T08:00:00.000Z",order:{sku:"SKU1",quantity:{value:5,unit:"EACH"},status:"OPEN",dueAt:"2026-08-20T10:00:00.000Z",...overrides},provenance:{acquisitionReference:"acquisition-1",authorizationReference:"authorization-1",acquiredAt:"2026-08-13T09:05:00.000Z",capabilityId:"read_orders",connectorIdentityId:"connector-identity:erp-production-rest",connectorRevision:1,sourceRepresentation:"PRODUCTION_REST_ERP_ORDERS_V1",transformationId:"PRODUCTION_REST_ERP_ORDER_TO_CANONICAL_ORDER",transformationVersion:"1.0.0",canonicalSchemaVersion:"1.0.0",tenantId:"tenant-1",companyId:"company-1",ownerId:"owner-1",sourceSystem:"system-1",externalObjectId:"O1",externalObjectVersion:"2"}};}

async function scope(entity_type:"ORDER"|"SKU"|"SUPPLIER"="ORDER",entity_ref="industrial-order:order-1",company_id="company-1"){
 const s=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"ENTITY",request_id:"request-1",company_id,domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1",entity:{entity_type,entity_ref}});
 return bindOperationalSignalsToScopeV1({scope:s,request_id:"request-1",company_id,evidence_as_of:"2026-08-13T10:00:00.000Z",evaluated_at:"2026-08-13T10:01:00.000Z"});
}
async function input(){return {version:1 as const,order_fact:order(),evaluation_scope:await scope(),selected_objective_kind:"ORDER_DELIVERY_COMMITMENT" as const,objective_selection_ref:"objective-selection:explicit-order-delivery",plan_element_ref:"plan-element:order-O1",protected_subject_ref:"subject:order-O1",qualification_refs:["qualification:1"],causal_lineage_refs:["lineage:causal-1"],plan_lineage_refs:["lineage:plan-1"]};}

describe("PRESSURE-OPS-PROTECTED-OBJECTIVE-POLICY-WU1",()=>{
 it("creates deterministic recursively immutable order-delivery commitments",async()=>{const a=await bindOperationsOrderDeliveryCommitmentV1(await input()),b=await bindOperationsOrderDeliveryCommitmentV1(await input());expect(a).toEqual(b);expect(a.commitment_id).toMatch(/^operations-order-delivery-commitment:sha256:/);expect(Object.isFrozen(a)&&Object.isFrozen(a.committed_quantity)&&Object.isFrozen(a.objective_binding)).toBe(true);});
 it("binds exact Operations profile, scope, request and company",async()=>{const x=await bindOperationsOrderDeliveryCommitmentV1(await input());expect(x.objective_binding).toMatchObject({request_id:"request-1",company_id:"company-1",domain_profile_ref:"domain-profile:operations",domain_profile_version:"1",scope_id:x.objective_binding.evaluation_scope.scope.scope_id});});
 it("preserves exact order identity, version, quantity, unit, due time and OPEN commitment",async()=>{const x=await bindOperationsOrderDeliveryCommitmentV1(await input());expect(x).toMatchObject({order_fact_ref:"industrial-order:order-1",order_version_ref:"order-version:2",item_ref:"operations-item:SKU1",committed_quantity:{value:5,unit_ref:"unit:EACH"},committed_due_at:"2026-08-20T10:00:00.000Z",commitment_status:"OPEN"});});
 it("changes identity when governed quantity or due time changes",async()=>{const base=await input();const a=await bindOperationsOrderDeliveryCommitmentV1(base);const q=await bindOperationsOrderDeliveryCommitmentV1({...base,order_fact:order({quantity:{value:6,unit:"EACH"}})});const d=await bindOperationsOrderDeliveryCommitmentV1({...base,order_fact:order({dueAt:"2026-08-21T10:00:00.000Z"})});expect(q.commitment_digest).not.toBe(a.commitment_digest);expect(d.commitment_digest).not.toBe(a.commitment_digest);});
 it("rejects unsupported objective kinds",async()=>{await expect(bindOperationsOrderDeliveryCommitmentV1({...await input(),selected_objective_kind:"SERVICE_LEVEL" as any})).rejects.toThrow("OPS_OBJECTIVE_KIND_UNSUPPORTED");});
 it("rejects request substitution",async()=>{const x=await input();await expect(bindOperationsOrderDeliveryCommitmentV1({...x,evaluation_scope:{...x.evaluation_scope,scope:{...x.evaluation_scope.scope,request_id:"request-other"}} as any})).rejects.toThrow();});
 it("rejects company substitution",async()=>{await expect(bindOperationsOrderDeliveryCommitmentV1({...await input(),evaluation_scope:await scope("ORDER","industrial-order:order-1","company-other")})).rejects.toThrow("OPS_OBJECTIVE_ORDER_COMPANY_MISMATCH");});
 it.each([["SKU","SKU1"],["SUPPLIER","supplier-1"]] as const)("does not resolve an objective from %s alone",async(entity_type,entity_ref)=>{await expect(bindOperationsOrderDeliveryCommitmentV1({...await input(),evaluation_scope:await scope(entity_type,entity_ref)})).rejects.toThrow("OPS_OBJECTIVE_ORDER_SCOPE_MISMATCH");});
 it("does not resolve an objective from PATH alone",async()=>{const s=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"PATH",request_id:"request-1",company_id:"company-1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1",path:{subgraph_ref:"subgraph:1",seed_refs:["SKU1"]}});const b=await bindOperationalSignalsToScopeV1({scope:s,request_id:"request-1",company_id:"company-1",evidence_as_of:"2026-08-13T10:00:00.000Z",evaluated_at:"2026-08-13T10:01:00.000Z"});await expect(bindOperationsOrderDeliveryCommitmentV1({...await input(),evaluation_scope:b})).rejects.toThrow("OPS_OBJECTIVE_ORDER_SCOPE_MISMATCH");});
 it("does not resolve an objective from REQUEST_DATASET alone",async()=>{const s=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"REQUEST_DATASET",request_id:"request-1",company_id:"company-1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1"});const b=await bindOperationalSignalsToScopeV1({scope:s,request_id:"request-1",company_id:"company-1",evidence_as_of:"2026-08-13T10:00:00.000Z",evaluated_at:"2026-08-13T10:01:00.000Z"});await expect(bindOperationsOrderDeliveryCommitmentV1({...await input(),evaluation_scope:b})).rejects.toThrow("OPS_OBJECTIVE_ORDER_SCOPE_MISMATCH");});
 it.each(["optimizer_score","candidate","serviceShortfall","decision_pressure","watch_state"])("contains no %s semantics",async field=>{const x=await bindOperationsOrderDeliveryCommitmentV1(await input());expect(x).not.toHaveProperty(field);expect(x.objective_binding).not.toHaveProperty(field);});
 it("is source-neutral, observational and non-authorizing",async()=>{const x=await bindOperationsOrderDeliveryCommitmentV1(await input()),json=JSON.stringify(x);expect(json).not.toMatch(/raw_order|candidate|optimizer|attention|pressure_level|ERP|SAP|MES|email|chat|telephone/i);expect(x).toMatchObject({observational_only:true,grants_execution:false,grants_authority:false});expect(x.objective_binding).toMatchObject({grants_remediation:false,company_global_claim:false});});
 it("produces no objective state or Impact dimension",async()=>{const x=await bindOperationsOrderDeliveryCommitmentV1(await input());expect(x).not.toHaveProperty("objective_state");expect(x).not.toHaveProperty("impact");expect(x).not.toHaveProperty("dimension");});
 it("freezes state vocabulary without producing it",()=>{expectTypeOf<OperationsProtectedObjectiveStateV1>().toEqualTypeOf<"PRESERVED"|"DEGRADED"|"BREACHED"|"LOST">();});
});
