import{describe,expect,it,vi}from"vitest";
import{bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1}from"../../cockpit/operational.signal.evaluation.scope.v1";
import{createGovernedSourceEventCoverageCapabilityV1}from"../../cognition/governed.source.event.coverage.capability.v1";
import type{AdapterExecutionResult}from"../adapter.runtime";
import{createOperationsCanonicalLocationV1}from"../cognition/operations.canonical.location.v1";
import{projectCanonicalAdmittedInventoryToBaselineAvailabilityV1,projectCanonicalAdmittedOrderToOperationsCommitmentV1}from"../cognition/operations.canonical.reality.cognition.projection.v1";
import{OPERATIONS_INVENTORY_DELTA_EVENT_CLASS,OPERATIONS_INVENTORY_DELTA_REQUIRED_FIELDS,OPERATIONS_INVENTORY_OBSERVATION_EVENT_CLASS,OPERATIONS_INVENTORY_OBSERVATION_REQUIRED_FIELDS}from"../cognition/operations.inventory.currentness.reconstruction.v1";
import{preserveGovernedOperationsFactV1,type GovernedOperationsFactV1}from"../preservation/governed.operational.fact.preservation.v1";
import{executeGovernedAcquisitionEvaluationBatchV1,retrieveCanonicalAdmittedGovernedFactV1,type GovernedAcquisitionEntryV1}from"../../reality/governed.acquisition.evaluation.batch.v1";
import{createGovernedSubjectBindingV1}from"../../reality/governed.multi-source.reality.alignment.v1";
import{createGovernedOperationalRepresentationV1}from"../../reality/governed.operational.representation.v1";
import{createGovernedPersistentFactSemanticBindingV1}from"../../reality/persistent.source.observation.bridge.v1";

const tenant="tenant-1",company="company-1",request="request-1",asOf="2026-08-16T12:00:00.000Z",evaluated="2026-08-16T12:01:00.000Z",due="2026-08-20T12:00:00.000Z",kind="operations-location-kind:INVENTORY_STATE_LOCATION";
async function binding(type:"REQUEST_DATASET"|"ENTITY"="REQUEST_DATASET",entityRef?:string){const scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:type,request_id:request,company_id:company,domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1",...(type==="ENTITY"?{entity:{entity_type:"ORDER",entity_ref:entityRef!}}:{})});return bindOperationalSignalsToScopeV1({scope,request_id:request,company_id:company,evidence_as_of:asOf,evaluated_at:evaluated})}
const metadata=(source:string)=>({tenantId:tenant,companyId:company,sourceSystem:source,connectorIdentityId:`connector:${source}`,connectorRevision:1,acquisitionReference:`acquisition:${source}`,authorizationReference:`authorization:${source}`,acquiredAt:asOf,capabilityId:`read:${source}`,sourceRepresentation:`format:${source}`});
async function coverage(scope:Awaited<ReturnType<typeof binding>>,event:string,fields:readonly string[]){return createGovernedSourceEventCoverageCapabilityV1({version:1,capability_policy_ref:`policy:${event}`,capability_policy_version:"1",tenant_id:`tenant:${tenant}`,source_identity_ref:"source:inventory",source_profile_ref:"profile:operations",source_profile_version:"1",source_boundary_ref:"boundary:SKU1:WH1",evaluation_scope:scope,event_class_capabilities:[{domain_ref:"domain:operations",event_class_ref:event,required_semantic_field_refs:fields,guaranteed_semantic_field_refs:fields,optional_semantic_field_refs:[]}],coverage_start:"2026-08-16T00:00:00.000Z",coverage_end:asOf,coverage_status:"COMPLETE",profile_capability_evidence_refs:["evidence:profile"],snapshot_completeness_evidence_refs:["evidence:complete"],qualification_refs:["qualification:coverage"],provenance_refs:["provenance:coverage"],causal_lineage_refs:["lineage:coverage"]})}
const execution=(source:string)=>({capability_id:`read:${source}`,payload:{},workload_identity:{workloadId:"workload:1",tenantId:`tenant:${tenant}`,authenticationEvidence:"evidence:auth"},data_access_context:{tenantId:`tenant:${tenant}`}as any});
const result=(source:string,fact:GovernedOperationsFactV1):AdapterExecutionResult=>Object.freeze({ok:true,capability_id:`read:${source}`,connector_id:`connector-registration:${source}`,connector_identity_id:`connector:${source}`,connector_revision:1,acquisition_reference:`acquisition:${source}`,authorization_reference:`authorization:${source}`,tenant_id:`tenant:${tenant}`,source_system:source,output:Object.freeze({governedFacts:[fact]}),executed_at:asOf});
async function setup(){const scope=await binding(),order=await preserveGovernedOperationsFactV1("ORDERS",{external_order_id:"O1",external_order_version:"7",sku:"SKU1",quantity_value:5,quantity_unit:"EA",status:"OPEN",observed_at:"2026-08-16T09:00:00.000Z",effective_at:"2026-08-16T08:00:00.000Z",due_at:due},metadata("orders")),inventory=await preserveGovernedOperationsFactV1("INVENTORY",{inventory_id:"I1",warehouse_id:"WH1",sku:"SKU1",quantity:2,unit:"EA",observed_at:"2026-08-16T10:00:00.000Z"},metadata("inventory"));async function entry(fact:GovernedOperationsFactV1,source:string,state:string,location:string){const representation=await createGovernedOperationalRepresentationV1({version:1,representation_ref:`representation:${source}`,company_id:company,domain_ref:"domain:operations",governed_scope_refs:[scope.scope.scope_id],subjects:[fact.role_bindings.subject],source_binding_refs:[`connector:${source}`],provenance_refs:[`provenance:${source}`],causal_lineage_refs:[`lineage:${source}`],observability:"PERSISTENT",refreshability:"INDEPENDENTLY_REFRESHABLE",refresh_policy_ref:"refresh:scheduled"}),subject=await createGovernedSubjectBindingV1({version:1,outcome:"SAME_SUBJECT",members:[{representation_identity_ref:representation.representation_id,local_subject_ref:fact.source_fact_ref}],canonical_subject:fact.role_bindings.subject,binding_evidence_refs:[`evidence:subject:${source}`],provenance_refs:[`provenance:subject:${source}`],causal_lineage_refs:[`lineage:subject:${source}`]}),semantic=await createGovernedPersistentFactSemanticBindingV1({version:1,fact_ref:fact.fact_id,representation_id:representation.representation_id,dimension_ref:"dimension:quantity",operational_state_ref:state,location_refs:[location],qualification_refs:[`qualification:${source}`],provenance_refs:[`provenance:${source}`],causal_lineage_refs:[`lineage:${source}`]});return{version:1,acquisition_id:`entry:${source}`,execution:execution(source),representation,fact_bindings:[{fact_ref:fact.fact_id,subject_binding:subject,semantic_binding:semantic}]}as GovernedAcquisitionEntryV1}const entries=[await entry(order,"orders","state:ORDERED","location:customer"),await entry(inventory,"inventory","state:EFFECTIVE_INVENTORY","location:WH1")],results=new Map([["read:orders",result("orders",order)],["read:inventory",result("inventory",inventory)]]),execute=vi.fn(async(input:any)=>results.get(input.capability_id)!),batch=await executeGovernedAcquisitionEvaluationBatchV1({version:1,tenant_id:`tenant:${tenant}`,company_id:company,request_id:request,evaluation_scope:scope,evidence_as_of:asOf,evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1",acquisitions:entries,temporal_bindings:[],representation_relationships:[],coverage:[]},{access_services:{}as any,execute_adapter:execute as any});return{scope,order,inventory,batch}}

describe("canonical-admitted governed fact operations cognition projection v1",()=>{
 it("recovers exact admitted ORDERS semantics and binds the existing commitment",async()=>{const x=await setup(),entity=await binding("ENTITY",x.order.fact_id),projected=await projectCanonicalAdmittedOrderToOperationsCommitmentV1({version:1,acquisition_result:x.batch,canonical_evidence_ref:x.order.fact_id,evaluation_scope:entity,objective_selection_ref:"selection:objective",plan_element_ref:"plan:O1",protected_subject_ref:"subject:O1"});expect(projected.order_fact).toMatchObject({source:{externalObjectId:"O1",externalObjectVersion:"7"},order:{sku:"SKU1",status:"OPEN",dueAt:due}});expect(projected.commitment).toMatchObject({order_version_ref:"order-version:7",item_ref:"operations-item:SKU1",committed_due_at:due,commitment_status:"OPEN"});expect(projected.commitment.objective_binding.causal_lineage_refs).toEqual(expect.arrayContaining([x.batch.canonical_reality.composition_id,x.batch.canonical_reality.composition_digest,x.order.fact_digest]))});
 it("retrieves admitted INVENTORY and reaches the existing effective-inventory availability producer",async()=>{const x=await setup(),observation=await coverage(x.scope,OPERATIONS_INVENTORY_OBSERVATION_EVENT_CLASS,OPERATIONS_INVENTORY_OBSERVATION_REQUIRED_FIELDS),delta=await coverage(x.scope,OPERATIONS_INVENTORY_DELTA_EVENT_CLASS,OPERATIONS_INVENTORY_DELTA_REQUIRED_FIELDS),location=await createOperationsCanonicalLocationV1({version:1,tenant_id:`tenant:${tenant}`,evaluation_scope:x.scope,canonical_location_key:"WH1",inventory_state_granularity_ref:kind,source_bindings:[{source_namespace:"inventory",external_location_ref:"WH1",location_kind_ref:kind,mapping_evidence_refs:["evidence:map"],qualification_refs:["qualification:map"],provenance_refs:["provenance:map"],causal_lineage_refs:["lineage:map"]}],qualification_refs:["qualification:location"],provenance_refs:["provenance:location"],causal_lineage_refs:["lineage:location"]}),projected=await projectCanonicalAdmittedInventoryToBaselineAvailabilityV1({version:1,acquisition_result:x.batch,canonical_evidence_ref:x.inventory.fact_id,evaluation_scope:x.scope,observation_coverage:observation,delta_coverage:delta,location_candidates:[location]});expect(projected.availability).toMatchObject({kind:"EFFECTIVE_INVENTORY",item_ref:"operations-item:SKU1",quantity:{value:2,unit_ref:"unit:EACH"},available_at:asOf});expect(projected.availability.causal_lineage_refs).toEqual(expect.arrayContaining([x.batch.canonical_reality.composition_id,x.batch.canonical_reality.composition_digest,x.inventory.fact_digest]))});
 it("does not derive cross-subject feasibility from coincident SKU strings",async()=>{const x=await setup(),order=await retrieveCanonicalAdmittedGovernedFactV1(x.batch,x.order.fact_id),inventory=await retrieveCanonicalAdmittedGovernedFactV1(x.batch,x.inventory.fact_id);expect(order.fact.role_bindings.subject.subject_kind).toBe("ORDER");expect(inventory.fact.role_bindings.subject.subject_kind).toBe("SKU");expect(order.fact.role_bindings.subject.subject_id).not.toBe(inventory.fact.role_bindings.subject.subject_id)});
});
