import {describe,expect,it} from "vitest";
import {bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1} from "../../cockpit/operational.signal.evaluation.scope.v1";
import type {CanonicalOrderFact} from "../canonicalization/authoritative.order.fact";
import {evaluateOperationsBaselineCommitmentFeasibilityV1,type BaselineAvailabilityV1,type BaselinePlanOrderV1} from "../cognition/operations.baseline.commitment.feasibility.v1";
import {deriveOperationsCostOfWaitingV1,verifyOperationsCostOfWaitingV1} from "../cognition/operations.cost.of.waiting.v1";
import {deriveOperationsCurrentFulfillmentPositionV1} from "../cognition/operations.current.fulfillment.position.v1";
import {deriveOperationsDecisionMarginV1} from "../cognition/operations.decision.margin.v1";
import {bindOperationsOrderDeliveryCommitmentV1} from "../cognition/operations.protected.objective.v1";
import {deriveOperationsUrgencyV1} from "../cognition/operations.urgency.v1";

const asOf="2026-08-13T10:00:00.000Z",due="2026-08-20T10:00:00.000Z",end="2026-08-15T10:00:00.000Z",ev={evidence_observed_at:"2026-08-13T09:00:00.000Z",evidence_refs:["evidence:availability"],qualification_refs:["qualification:admitted"],provenance_refs:["provenance:source"],causal_lineage_refs:["lineage:baseline"]};
function fact():CanonicalOrderFact{return{factId:"industrial-order:order-1",factFamily:"INDUSTRIAL_ORDER",schemaVersion:"1.0.0",owner:{tenantId:"tenant-1",companyId:"company-1",ownerId:"owner-1"},source:{systemId:"system-1",externalObjectId:"order-1",externalObjectVersion:"2"},observedAt:ev.evidence_observed_at,effectiveAt:"2026-08-13T08:00:00.000Z",order:{sku:"SKU1",quantity:{value:5,unit:"EACH"},status:"OPEN",dueAt:due},provenance:{acquisitionReference:"acquisition-order-1",authorizationReference:"authorization-1",acquiredAt:"2026-08-13T09:05:00.000Z",capabilityId:"read_orders",connectorIdentityId:"connector-identity:any",connectorRevision:1,sourceRepresentation:"PRODUCTION_REST_ERP_ORDERS_V1",transformationId:"PRODUCTION_REST_ERP_ORDER_TO_CANONICAL_ORDER",transformationVersion:"1.0.0",canonicalSchemaVersion:"1.0.0",tenantId:"tenant-1",companyId:"company-1",ownerId:"owner-1",sourceSystem:"system-1",externalObjectId:"order-1",externalObjectVersion:"2"}};}
async function state(options:{at?:string;quantity?:number;boundary?:"COMPLETE"|"PARTIAL"}={}){const f=fact(),scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"ENTITY",request_id:"request-1",company_id:"company-1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1",entity:{entity_type:"ORDER",entity_ref:f.factId}}),binding=await bindOperationalSignalsToScopeV1({scope,request_id:"request-1",company_id:"company-1",evidence_as_of:asOf,evaluated_at:"2026-08-13T10:01:00.000Z"}),commitment=await bindOperationsOrderDeliveryCommitmentV1({version:1,order_fact:f,evaluation_scope:binding,selected_objective_kind:"ORDER_DELIVERY_COMMITMENT",objective_selection_ref:"selection:objective",plan_element_ref:"plan:order-1",protected_subject_ref:"subject:order-1",qualification_refs:["qualification:order"],causal_lineage_refs:["lineage:order"],plan_lineage_refs:["lineage:plan"]}),order:BaselinePlanOrderV1={...ev,order_fact_ref:commitment.order_fact_ref,order_version_ref:commitment.order_version_ref,item_ref:commitment.item_ref,quantity:commitment.committed_quantity,due_at:commitment.committed_due_at},availability:BaselineAvailabilityV1={...ev,availability_ref:"availability:1",kind:"GOVERNED_FUTURE_SUPPLY",item_ref:commitment.item_ref,quantity:{value:options.quantity??5,unit_ref:"unit:EACH"},available_at:options.at??"2026-08-18T10:00:00.000Z"},evidence_boundary=options.boundary??"COMPLETE",feasibility=await evaluateOperationsBaselineCommitmentFeasibilityV1({version:1,commitment,baseline_semantics:"BASELINE_CURRENT_PLAN",evidence_selection_ref:"selection:1",plan_orders:[order],availability:[availability],evidence_boundary}),position=await deriveOperationsCurrentFulfillmentPositionV1({version:1,commitment,baseline_feasibility:feasibility,baseline_semantics:"BASELINE_CURRENT_PLAN",evidence_selection_ref:"selection:1",plan_orders:[order],availability:[availability],evidence_boundary}),margin=await deriveOperationsDecisionMarginV1({version:1,commitment,current_position:position,governing_condition_ref:"condition:fulfillment-timing",material_compromise_refs:["consequence:delivery"]}),urgency=await deriveOperationsUrgencyV1({version:1,commitment,decision_margin:margin});return{commitment,position,urgency};}
const consequence=(delayed?:string,status:"RESOLVED"|"UNRESOLVED"|"INSUFFICIENT_EVIDENCE"="RESOLVED")=>({status,delayed_expected_fulfillment_at:delayed,evidence_ref:"evidence:bounded-delay",evidence_refs:["evidence:bounded-delay"],qualification_refs:["qualification:bounded-delay"],provenance_refs:["provenance:bounded-delay"],causal_lineage_refs:["lineage:bounded-delay"]} as const);
async function cost(delayed?:string,options:Parameters<typeof state>[0]={},extra:Record<string,unknown>={}){const x=await state(options);return{...x,result:await deriveOperationsCostOfWaitingV1({version:1,commitment:x.commitment,current_position:x.position,urgency:x.urgency,waiting_interval:{start_at:asOf,end_at:end},bounded_delay_consequence:consequence(delayed??x.position.current_position_at),governing_condition_ref:"condition:bounded-waiting",...extra} as any)};}

describe("PRESSURE-OPS-COST-OF-WAITING-COGNITION-WU1",()=>{
 it("creates deterministic immutable verifiable cost evidence",async()=>{const a=await cost(),b=await cost();expect(a.result.cost_of_waiting_id).toBe(b.result.cost_of_waiting_id);await expect(verifyOperationsCostOfWaitingV1(a.result)).resolves.toBeUndefined();expect(Object.isFrozen(a.result)&&Object.isFrozen(a.result.waiting_interval)).toBe(true);});
 it("binds exact context objective consequence trajectory condition and evidence time",async()=>{const x=await cost();expect(x.result).toMatchObject({request_id:"request-1",company_id:"company-1",scope_id:x.position.scope_id,objective_ref:x.commitment.commitment_id,material_consequence_refs:["consequence:delivery"],trajectory_ref:x.position.position_id,governing_condition_ref:"condition:bounded-waiting",evidence_as_of:asOf});});
 it("retains the explicit deterministic waiting interval",async()=>{expect((await cost()).result.waiting_interval).toEqual({start_at:asOf,end_at:end,duration:{value:172800000,unit_ref:"duration:milliseconds"}});});
 it("establishes zero when bounded waiting causes no deterioration",async()=>{const x=await cost("2026-08-18T10:00:00.000Z");expect(x.result).toMatchObject({status:"NO_ADDITIONAL_COST_ESTABLISHED",additional_lateness:{value:0},pressure_dimension:{dimension:"COST_OF_WAITING",value:0}});});
 it("establishes additional lateness independently of urgency",async()=>{const x=await cost("2026-08-22T10:00:00.000Z");expect(x.result).toMatchObject({status:"FEASIBILITY_LOSS_ESTABLISHED",baseline_lateness:{value:0},delayed_lateness:{value:172800000},additional_lateness:{value:172800000},pressure_dimension:{value:1}});});
 it("establishes feasibility loss only when delay crosses the deadline",async()=>{expect((await cost("2026-08-20T11:00:00.000Z")).result.status).toBe("FEASIBILITY_LOSS_ESTABLISHED");});
 it("supports exhausted window with further deterioration",async()=>{const x=await cost("2026-08-23T10:00:00.000Z",{at:"2026-08-21T10:00:00.000Z"});expect(x.urgency.status).toBe("WINDOW_EXHAUSTED");expect(x.result.status).toBe("ADDITIONAL_LATENESS_ESTABLISHED");});
 it("supports exhausted window with no further deterioration",async()=>{const x=await cost("2026-08-21T10:00:00.000Z",{at:"2026-08-21T10:00:00.000Z"});expect(x.urgency.status).toBe("WINDOW_EXHAUSTED");expect(x.result.status).toBe("NO_ADDITIONAL_COST_ESTABLISHED");});
 it("preserves unresolved and insufficient evidence",async()=>{for(const [options,status]of [[{boundary:"PARTIAL"},"UNRESOLVED"],[{quantity:4},"INSUFFICIENT_EVIDENCE"]]as const){const x=await cost(undefined,options);expect(x.result.status).toBe(status);expect(x.result).not.toHaveProperty("additional_lateness");}});
 it("same urgency can have different deterioration",async()=>{const zero=await cost("2026-08-18T10:00:00.000Z"),loss=await cost("2026-08-22T10:00:00.000Z");expect(zero.urgency.urgency_id).toBe(loss.urgency.urgency_id);expect(zero.result.status).not.toBe(loss.result.status);});
 it("same material consequence and Impact context can have different waiting deltas",async()=>{const zero=(await cost("2026-08-18T10:00:00.000Z")).result,loss=(await cost("2026-08-22T10:00:00.000Z")).result;expect(zero.material_consequence_refs).toEqual(loss.material_consequence_refs);expect(zero.additional_lateness?.value).toBe(0);expect(loss.additional_lateness?.value).toBeGreaterThan(0);});
 it("rejects invalid ordering cross-context substitution and forged digests",async()=>{await expect(cost("2026-08-17T10:00:00.000Z")).rejects.toThrow("OPS_WAITING_TEMPORAL_ORDER_INVALID");const x=await state();await expect(deriveOperationsCostOfWaitingV1({version:1,commitment:x.commitment,current_position:{...x.position,company_id:"other"},urgency:x.urgency,waiting_interval:{start_at:asOf,end_at:end},bounded_delay_consequence:consequence(x.position.current_position_at),governing_condition_ref:"condition:x"} as any)).rejects.toThrow();await expect(verifyOperationsCostOfWaitingV1({...((await cost()).result),cost_of_waiting_digest:"forged"})).rejects.toThrow();});
 it("retains qualification provenance lineage and fabricates no money",async()=>{const x=(await cost()).result;expect(x.qualification_refs).toEqual(expect.arrayContaining(["qualification:admitted","qualification:bounded-delay"]));expect(x.provenance_refs).toContain("provenance:bounded-delay");expect(x.causal_lineage_refs).toEqual(expect.arrayContaining([x.trajectory_ref,x.urgency_ref]));expect(x.monetary_cost_asserted).toBe(false);expect(x).not.toHaveProperty("currency");});
 it.each(["impact","impact_score","decision_margin","cost","money","currency","authority_tier","subscription_tier","commercial_plan","credit_balance","provider","model","approval","delegation","recommendation","scenario","simulation","optimizer_candidate","llm_output","learned_result"])("rejects %s substitution or contamination",async key=>await expect(cost(undefined,{}, {[key]:"forbidden"})).rejects.toThrow("OPS_WAITING_UNSAFE_INPUT"));
 it.each(["VISION","GRADUATE","JUNIOR","SENIOR","PRINCIPAL","CHARTER"])("is identical at independent tier %s",async()=>{const a=(await cost()).result,b=(await cost()).result;expect(a.cost_of_waiting_id).toBe(b.cost_of_waiting_id);expect(a).not.toHaveProperty("subscription_tier");});
 it("is observational with no recommendation authority execution LLM learning or source switchboard",async()=>{const x=(await cost()).result;expect(x).toMatchObject({recommended:false,executable:false,grants_authority:false,grants_execution:false,grants_remediation:false,company_global_claim:false});expect(JSON.stringify(x)).not.toMatch(/SAP|ERP|MES|llm_output|learned_result|optimizer_candidate|simulation_result/i);});
});
