import {describe,it,expect} from "vitest";
import {bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1} from "../../cockpit/operational.signal.evaluation.scope.v1";
import {createOperationsCanonicalLocationV1,resolveOperationsCanonicalLocationV1,verifyOperationsCanonicalLocationV1} from "../cognition/operations.canonical.location.v1";
const at="2026-08-16T10:00:00.000Z";
async function scope(company="company-1"){const s=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"REQUEST_DATASET",request_id:"request-1",company_id:company,domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1"});return bindOperationalSignalsToScopeV1({scope:s,request_id:"request-1",company_id:company,evidence_as_of:at,evaluated_at:"2026-08-16T10:01:00.000Z"});}
const binding=(namespace:string,external:string)=>({source_namespace:namespace,external_location_ref:external,location_kind_ref:"operations-location-kind:INVENTORY_STATE_LOCATION",mapping_evidence_refs:[`evidence:mapping-${namespace}-${external}`],qualification_refs:["qualification:exact-location-mapping"],provenance_refs:["provenance:configured-location-map"],causal_lineage_refs:["lineage:location-map"]});
async function location(overrides:Record<string,unknown>={}){return createOperationsCanonicalLocationV1({version:1,tenant_id:"tenant-1",evaluation_scope:await scope(),canonical_location_key:"warehouse-main",inventory_state_granularity_ref:"operations-location-kind:INVENTORY_STATE_LOCATION",source_bindings:[binding("ERP-1","WH01"),binding("WMS-1","MAIN")],qualification_refs:["qualification:location"],provenance_refs:["provenance:location"],causal_lineage_refs:["lineage:location"],...overrides} as any);}
describe("operations canonical location",()=>{
 it("creates deterministic immutable many-to-one identity",async()=>{const a=await location(),b=await location();expect(a.location_id).toBe(b.location_id);expect(a.source_bindings).toHaveLength(2);expect(Object.isFrozen(a)&&Object.isFrozen(a.source_bindings)&&Object.isFrozen(a.source_bindings[0])).toBe(true);await expect(verifyOperationsCanonicalLocationV1(a)).resolves.toBeUndefined();});
 it("resolves inventory and movement refs through one exact layer",async()=>{const x=await location();for(const [ns,ref] of [["ERP-1","WH01"],["WMS-1","MAIN"]])expect((await resolveOperationsCanonicalLocationV1({version:1,tenant_id:"tenant-1",company_id:"company-1",source_namespace:ns!,external_location_ref:ref!,location_kind_ref:"operations-location-kind:INVENTORY_STATE_LOCATION",evidence_as_of:at,candidates:[x]})).location_id).toBe(x.location_id);});
 it("does not equate the same raw string across namespaces",async()=>{const x=await location({source_bindings:[binding("ERP-1","WH01")]});await expect(resolveOperationsCanonicalLocationV1({version:1,tenant_id:"tenant-1",company_id:"company-1",source_namespace:"MES-1",external_location_ref:"WH01",location_kind_ref:"operations-location-kind:INVENTORY_STATE_LOCATION",evidence_as_of:at,candidates:[x]})).rejects.toThrow("OPS_LOCATION_RESOLUTION_NOT_FOUND");});
 it("does not cross company boundaries",async()=>{const x=await location();await expect(resolveOperationsCanonicalLocationV1({version:1,tenant_id:"tenant-1",company_id:"company-2",source_namespace:"ERP-1",external_location_ref:"WH01",location_kind_ref:"operations-location-kind:INVENTORY_STATE_LOCATION",evidence_as_of:at,candidates:[x]})).rejects.toThrow("OPS_LOCATION_RESOLUTION_NOT_FOUND");});
 it("fails closed for missing mapping and ambiguous active mapping",async()=>{const a=await location(),b=await location({canonical_location_key:"warehouse-other",source_bindings:[binding("ERP-1","WH01")]});const q={version:1 as const,tenant_id:"tenant-1",company_id:"company-1",source_namespace:"ERP-1",external_location_ref:"UNKNOWN",location_kind_ref:"operations-location-kind:INVENTORY_STATE_LOCATION",evidence_as_of:at,candidates:[a]};await expect(resolveOperationsCanonicalLocationV1(q)).rejects.toThrow("OPS_LOCATION_RESOLUTION_NOT_FOUND");await expect(resolveOperationsCanonicalLocationV1({...q,external_location_ref:"WH01",candidates:[a,b]})).rejects.toThrow("OPS_LOCATION_RESOLUTION_AMBIGUOUS");});
 it("rejects granularity mismatch and hierarchy substitution",async()=>{await expect(location({source_bindings:[{...binding("ERP-1","WH01"),location_kind_ref:"operations-location-kind:PLANT"}]})).rejects.toThrow("OPS_LOCATION_GRANULARITY_MISMATCH");await expect(location({topology_relation:"contains"})).rejects.toThrow("OPS_LOCATION_UNSAFE_INPUT");});
 it("rejects string-only, fuzzy, and unqualified mappings",async()=>{await expect(location({source_bindings:[{...binding("ERP-1","WH01"),mapping_evidence_refs:[]}]})).rejects.toThrow("OPS_LOCATION_MAPPING_EVIDENCE_REQUIRED");await expect(location({similar_name:"Main Warehouse"})).rejects.toThrow("OPS_LOCATION_UNSAFE_INPUT");});
 it("detects forged location and binding digests",async()=>{const x=await location();await expect(verifyOperationsCanonicalLocationV1({...x,location_digest:"0".repeat(64)})).rejects.toThrow("OPS_LOCATION_INTEGRITY_INVALID");await expect(verifyOperationsCanonicalLocationV1({...x,source_bindings:[{...x.source_bindings[0]!,external_location_ref:"FORGED"}]})).rejects.toThrow("OPS_LOCATION_BINDING_INTEGRITY_INVALID");});
 it("binds current configured mappings to the evidence boundary",async()=>{const x=await location();expect(x).toMatchObject({evidence_as_of:at,current_configured_binding:true,historical_remapping_supported:false,hierarchy_establishes_identity:false,recommended:false,executable:false,grants_authority:false,grants_execution:false});});
});
