import {describe,expect,it} from "vitest";
import {bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1} from "../../cockpit/operational.signal.evaluation.scope.v1";
import type {CanonicalOrderFact} from "../canonicalization/authoritative.order.fact";
import {evaluateOperationsBaselineCommitmentFeasibilityV1,type BaselineAvailabilityV1,type BaselinePlanOrderV1} from "../cognition/operations.baseline.commitment.feasibility.v1";
import {deriveOperationsCurrentFulfillmentPositionV1} from "../cognition/operations.current.fulfillment.position.v1";
import {deriveOperationsDecisionMarginV1,OPERATIONS_DECISION_MARGIN_DURATION_UNIT} from "../cognition/operations.decision.margin.v1";
import {bindOperationsOrderDeliveryCommitmentV1} from "../cognition/operations.protected.objective.v1";

const asOf="2026-08-13T10:00:00.000Z",due="2026-08-20T10:00:00.000Z",ev={evidence_observed_at:"2026-08-13T09:00:00.000Z",evidence_refs:["evidence:availability"],qualification_refs:["qualification:admitted"],provenance_refs:["provenance:source"],causal_lineage_refs:["lineage:baseline"]};
function fact(id="order-1",version="2",sku="SKU1"):CanonicalOrderFact{return{factId:`industrial-order:${id}`,factFamily:"INDUSTRIAL_ORDER",schemaVersion:"1.0.0",owner:{tenantId:"tenant-1",companyId:"company-1",ownerId:"owner-1"},source:{systemId:"system-1",externalObjectId:id,externalObjectVersion:version},observedAt:ev.evidence_observed_at,effectiveAt:"2026-08-13T08:00:00.000Z",order:{sku,quantity:{value:5,unit:"EACH"},status:"OPEN",dueAt:due},provenance:{acquisitionReference:`acquisition-${id}`,authorizationReference:"authorization-1",acquiredAt:"2026-08-13T09:05:00.000Z",capabilityId:"read_orders",connectorIdentityId:"connector-identity:any",connectorRevision:1,sourceRepresentation:"PRODUCTION_REST_ERP_ORDERS_V1",transformationId:"PRODUCTION_REST_ERP_ORDER_TO_CANONICAL_ORDER",transformationVersion:"1.0.0",canonicalSchemaVersion:"1.0.0",tenantId:"tenant-1",companyId:"company-1",ownerId:"owner-1",sourceSystem:"system-1",externalObjectId:id,externalObjectVersion:version}};}
async function chain(options:{at?:string;quantity?:number;boundary?:"COMPLETE"|"PARTIAL";id?:string;version?:string;sku?:string}={}){const f=fact(options.id,options.version,options.sku),scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"ENTITY",request_id:"request-1",company_id:"company-1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1",entity:{entity_type:"ORDER",entity_ref:f.factId}}),binding=await bindOperationalSignalsToScopeV1({scope,request_id:"request-1",company_id:"company-1",evidence_as_of:asOf,evaluated_at:"2026-08-13T10:01:00.000Z"}),c=await bindOperationsOrderDeliveryCommitmentV1({version:1,order_fact:f,evaluation_scope:binding,selected_objective_kind:"ORDER_DELIVERY_COMMITMENT",objective_selection_ref:"selection:objective",plan_element_ref:`plan:${f.factId}`,protected_subject_ref:`subject:${f.factId}`,qualification_refs:["qualification:order"],causal_lineage_refs:["lineage:order"],plan_lineage_refs:["lineage:plan"]}),order:BaselinePlanOrderV1={...ev,order_fact_ref:c.order_fact_ref,order_version_ref:c.order_version_ref,item_ref:c.item_ref,quantity:c.committed_quantity,due_at:c.committed_due_at},availability:BaselineAvailabilityV1={...ev,availability_ref:"availability:1",kind:"GOVERNED_FUTURE_SUPPLY",item_ref:c.item_ref,quantity:{value:options.quantity??5,unit_ref:"unit:EACH"},available_at:options.at??"2026-08-18T10:00:00.000Z"},evidence_boundary=options.boundary??"COMPLETE",feasibility=await evaluateOperationsBaselineCommitmentFeasibilityV1({version:1,commitment:c,baseline_semantics:"BASELINE_CURRENT_PLAN",evidence_selection_ref:"selection:1",plan_orders:[order],availability:[availability],evidence_boundary}),position=await deriveOperationsCurrentFulfillmentPositionV1({version:1,commitment:c,baseline_feasibility:feasibility,baseline_semantics:"BASELINE_CURRENT_PLAN",evidence_selection_ref:"selection:1",plan_orders:[order],availability:[availability],evidence_boundary});return{c,position};}
async function margin(x?:Awaited<ReturnType<typeof chain>>,overrides:Record<string,unknown>={}){const state=x??await chain();return deriveOperationsDecisionMarginV1({version:1,commitment:state.c,current_position:state.position,governing_condition_ref:"condition:fulfillment-timing",material_compromise_refs:["consequence:order-delivery-commitment"],...overrides} as any);}

describe("OPS-DECISION-MARGIN-PRODUCER-WU1",()=>{
 it("produces exact positive AVAILABLE temporal margin from position rather than wall-clock time",async()=>{const x=await margin();expect(x).toMatchObject({status:"AVAILABLE",remaining_margin:{value:172800000,unit_ref:OPERATIONS_DECISION_MARGIN_DURATION_UNIT},governing_dimension_ref:"dimension:time",epistemic_basis:"DETERMINISTIC"});expect(x.remaining_margin?.value).not.toBe(Date.parse(due)-Date.parse(asOf));});
 it("maps exact equality to BOUNDARY_REACHED with exact zero",async()=>{const x=await margin(await chain({at:due}));expect(x).toMatchObject({status:"BOUNDARY_REACHED",remaining_margin:{value:0,unit_ref:"duration:milliseconds"}});});
 it("maps a later position to BOUNDARY_EXCEEDED without negative margin",async()=>{const x=await margin(await chain({at:"2026-08-21T10:00:00.000Z"}));expect(x.status).toBe("BOUNDARY_EXCEEDED");expect(x).not.toHaveProperty("remaining_margin");});
 it("preserves UNRESOLVED and INSUFFICIENT_EVIDENCE without fabricating zero",async()=>{const unresolved=await margin(await chain({boundary:"PARTIAL"})),insufficient=await margin(await chain({quantity:4}));expect(unresolved.status).toBe("UNRESOLVED");expect(insufficient.status).toBe("INSUFFICIENT_EVIDENCE");expect(unresolved).not.toHaveProperty("remaining_margin");expect(insufficient).not.toHaveProperty("remaining_margin");});
 it("rejects forged protected-objective and current-position integrity",async()=>{const x=await chain();await expect(margin({...x,c:{...x.c,commitment_digest:"forged"}} as any)).rejects.toThrow("OPS_MARGIN_OBJECTIVE_INTEGRITY_INVALID");await expect(margin({...x,position:{...x.position,position_digest:"forged"}} as any)).rejects.toThrow("OPS_MARGIN_POSITION_INTEGRITY_INVALID");});
 it("rejects wrong order, version, item, company, request, scope, evidence selection, and timestamps",async()=>{const x=await chain(),other=await chain({id:"other",version:"3",sku:"OTHER"});await expect(margin({c:x.c,position:other.position})).rejects.toThrow();for(const position of [{...x.position,company_id:"other"},{...x.position,request_id:"other"},{...x.position,scope_id:"other"},{...x.position,evidence_selection_ref:"other"},{...x.position,evidence_as_of:"2026-08-13T09:59:00Z"}])await expect(margin({c:x.c,position:position as any})).rejects.toThrow();});
 it("rejects unsupported position/scope and missing evidence bindings",async()=>{const x=await chain();for(const position of [{...x.position,position_kind:"CUSTOMER_DELIVERY_TIME"},{...x.position,temporal_unit_ref:"time:LOCAL"},{...x.position,qualification_refs:[]},{...x.position,provenance_refs:[]},{...x.position,causal_lineage_refs:[]}])await expect(margin({c:x.c,position:position as any})).rejects.toThrow();await expect(margin({c:{...x.c,objective_binding:{...x.c.objective_binding,evaluation_scope:{...x.c.objective_binding.evaluation_scope,scope:{...x.c.objective_binding.evaluation_scope.scope,scope_type:"PATH"}}}} as any,position:x.position})).rejects.toThrow();});
 it("rejects candidate, scenario, tier, and learned-basis contamination",async()=>{const x=await chain();await expect(margin(x,{corrective_action_refs:["candidate:1"]})).rejects.toThrow("OPS_MARGIN_CORRECTIVE_CANDIDATE_REJECTED");await expect(margin(x,{scenario_modification_refs:["scenario:1"]})).rejects.toThrow("OPS_MARGIN_SCENARIO_REJECTED");await expect(margin(x,{authority_tier_ref:"SENIOR"})).rejects.toThrow("OPS_MARGIN_TIER_INPUT_REJECTED");await expect(margin(x,{epistemic_basis:"LEARNED"})).rejects.toThrow("OPS_MARGIN_EPISTEMIC_BASIS_UNSUPPORTED");});
 it("preserves qualification, provenance, evidence, and causal lineage",async()=>{const x=await margin();expect(x.qualification_refs).toContain("qualification:admitted");expect(x.provenance_refs).toContain("provenance:source");expect(x.evidence_refs).toContain("evidence:availability");expect(x.causal_lineage_refs).toEqual(expect.arrayContaining([expect.stringMatching(/^operations-current-fulfillment-position:/),expect.stringMatching(/^operations-order-delivery-commitment:/)]));});
 it("is deterministic, recursively immutable, source-neutral, observational, and tier-independent",async()=>{const a=await margin(),b=await margin(),json=JSON.stringify(a);expect(a.margin_id).toBe(b.margin_id);expect(Object.isFrozen(a)&&Object.isFrozen(a.remaining_margin)&&Object.isFrozen(a.causal_lineage_refs)).toBe(true);expect(a).toMatchObject({observational_only:true,grants_authority:false,grants_execution:false,grants_remediation:false,company_global_claim:false});expect(json).not.toMatch(/customer.delivery|impact|urgency|cost.of.waiting|pressure.level|recommendation|approval|delegation|credential/i);});
});
