import {describe,expect,it} from "vitest";
import {bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1} from "../../cockpit/operational.signal.evaluation.scope.v1";
import {createProtectedOperationalObjectiveBindingV1} from "../../cognition/protected.operational.objective.v1";
import {createOperationsGovernedInterventionClassV1,createOperationsGovernedInterventionEvidenceV1} from "../cognition/operations.governed.intervention.class.v1";

const asOf="2026-08-14T10:00:00Z",evaluated="2026-08-14T10:01:00Z";
async function fixtures(company="company-1",request="request-1",condition="condition:shortage"){
 const scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"ENTITY",request_id:request,company_id:company,domain:"operations",evidence_selection_ref:"selection:current",source_snapshot_ref:"snapshot:current",entity:{entity_type:"ORDER",entity_ref:"order:1"}}),binding=await bindOperationalSignalsToScopeV1({scope,request_id:request,company_id:company,evidence_as_of:asOf,evaluated_at:evaluated});
 const objective=await createProtectedOperationalObjectiveBindingV1({version:1,request_id:request,company_id:company,evaluation_scope:binding,domain_profile_ref:"profile:operations-v1",domain_profile_version:"1",objective_kind_ref:"objective-kind:order-delivery",objective_ref:"objective:order-1-delivery",governing_expected_state_refs:["state:on-time"],governing_plan_element_refs:["plan:order-1"],protected_subject_refs:["subject:order-1"],commitment_criteria_refs:["criterion:due"],objective_selection_ref:"selection:objective",source_evidence_refs:["evidence:order"],provenance_refs:["provenance:order"],qualification_refs:["qualification:order"],causal_lineage_refs:["lineage:objective"],plan_lineage_refs:["lineage:plan"],effective_at:"2026-08-14T09:00:00Z",evidence_as_of:asOf,evaluated_at:evaluated});
 const intervention=await createOperationsGovernedInterventionClassV1({version:1,domain_profile_ref:"profile:operations-v1",domain_profile_version:"1",class_key:"INVENTORY_REALLOCATION",producer_ref:"producer:operations-intervention-evidence-v1",policy_ref:"policy:operations-intervention-v1"});
 return{binding,objective,intervention,company,request,condition};
}
async function evidence(overrides:Record<string,unknown>={}){const f=await fixtures();return createOperationsGovernedInterventionEvidenceV1({version:1,intervention_class:f.intervention,request_id:f.request,company_id:f.company,evaluation_scope:f.binding,protected_objective:f.objective,governing_condition_ref:f.condition,trajectory_ref:"trajectory:order-1-delivery",applicability_status:"APPLICABLE",applicability_evidence_refs:["evidence:allocable-stock"],material_effect_status:"MATERIAL_EFFECT_ESTABLISHED",material_effect_evidence_refs:["causal-test:allocation-v1"],determination_basis_refs:["basis:governed-deterministic"],qualification_refs:["qualification:admitted"],provenance_refs:["provenance:inventory"],causal_lineage_refs:["lineage:condition-to-effect"],epistemic_basis:"DETERMINISTIC_COUNTERFACTUAL",evidence_as_of:asOf,evaluated_at:evaluated,...overrides} as any);}

describe("OPS-GOVERNED-INTERVENTION-CLASS-CONTRACT-WU1",()=>{
 it("creates stable, recursively immutable class identity independent of action instances",async()=>{const a=(await fixtures()).intervention,b=(await fixtures()).intervention;expect(a.intervention_class_id).toBe(b.intervention_class_id);expect(Object.isFrozen(a)).toBe(true);expect(a).toMatchObject({domain_ref:"domain:operations",domain_profile_ref:"profile:operations-v1",class_only:true,instance_payload_absent:true});expect(a).not.toHaveProperty("action");});
 it("binds exact context, class, objective, condition and trajectory deterministically",async()=>{const a=await evidence(),b=await evidence();expect(a.intervention_evidence_id).toBe(b.intervention_evidence_id);expect(a).toMatchObject({request_id:"request-1",company_id:"company-1",governing_condition_ref:"condition:shortage",trajectory_ref:"trajectory:order-1-delivery"});expect(a.protected_objective_ref).toMatch(/^protected-operational-objective:/);});
 it("keeps applicability and material effect independent",async()=>{expect(await evidence({applicability_status:"APPLICABLE",material_effect_status:"UNRESOLVED"})).toMatchObject({applicability_status:"APPLICABLE",material_effect_status:"UNRESOLVED"});expect(await evidence({applicability_status:"NOT_APPLICABLE",material_effect_status:"MATERIAL_EFFECT_ESTABLISHED"})).toMatchObject({applicability_status:"NOT_APPLICABLE",material_effect_status:"MATERIAL_EFFECT_ESTABLISHED"});});
 it.each([["applicability_evidence_refs","OPS_INTERVENTION_APPLICABILITY_EVIDENCE_REQUIRED"],["material_effect_evidence_refs","OPS_INTERVENTION_EFFECT_EVIDENCE_REQUIRED"],["qualification_refs","OPS_INTERVENTION_QUALIFICATION_REQUIRED"],["provenance_refs","OPS_INTERVENTION_PROVENANCE_REQUIRED"],["causal_lineage_refs","OPS_INTERVENTION_LINEAGE_REQUIRED"]])("fails closed when %s is absent",async(key,code)=>await expect(evidence({[key]:[]})).rejects.toThrow(code));
 it("rejects cross-request, cross-company, cross-scope, profile, condition, trajectory, and timestamp substitution",async()=>{const f=await fixtures();for(const override of [{request_id:"other"},{company_id:"other"},{evaluation_scope:(await fixtures("company-1","other")).binding},{intervention_class:{...f.intervention,domain_profile_ref:"profile:other"}},{governing_condition_ref:""},{trajectory_ref:""},{evidence_as_of:"2026-08-14T09:59:00Z"}])await expect(evidence(override)).rejects.toThrow();});
 it.each(["execution_capability_ref","optimizer_candidate_ref","candidate_plan_ref","recommendation_ref","authority_tier","subscription_tier","approval_ref","delegation_ref","credential_ref","selected_action_ref","action_instance","execution_payload","correction_effect"])("rejects forbidden substitution %s",async key=>await expect(evidence({[key]:"forbidden:1"})).rejects.toThrow("OPS_INTERVENTION_UNSUPPORTED_INPUT"));
 it("preserves deterministic and governed counterfactual epistemic bases but rejects learned impersonation",async()=>{expect((await evidence({epistemic_basis:"DETERMINISTIC"})).epistemic_basis).toBe("DETERMINISTIC");expect((await evidence()).epistemic_basis).toBe("DETERMINISTIC_COUNTERFACTUAL");await expect(evidence({epistemic_basis:"LEARNED"})).rejects.toThrow("OPS_INTERVENTION_EPISTEMIC_BASIS_UNSUPPORTED");});
 it("is recursively immutable, source-neutral, observational, non-recommending, non-authorizing and non-executable",async()=>{const x=await evidence(),json=JSON.stringify(x);expect(Object.isFrozen(x)&&Object.isFrozen(x.applicability_evidence_refs)&&Object.isFrozen(x.causal_lineage_refs)).toBe(true);expect(x).toMatchObject({guarantees_success:false,observational_only:true,recommended:false,selected:false,executable:false,grants_authority:false,grants_execution:false,grants_remediation:false,company_global_claim:false});expect(json).not.toMatch(/ERP|MES|SAP|email|chat|telephone|optimizer|VISION|JUNIOR|SENIOR/);});
 it("does not produce downstream decision concepts or require an instance payload",async()=>{const x=await evidence();for(const key of ["decision_opportunity","decision_influenceability","decision_margin","urgency","cost_of_waiting","pressure","action_instance","execution_payload"])expect(x).not.toHaveProperty(key);});
 it("changes identity across class, scope, company, condition, objective, trajectory, evidence, and epistemic basis",async()=>{const base=await evidence(),variants=[await evidence({governing_condition_ref:"condition:capacity"}),await evidence({trajectory_ref:"trajectory:other"}),await evidence({applicability_evidence_refs:["evidence:other"]}),await evidence({epistemic_basis:"DETERMINISTIC"})];for(const variant of variants)expect(variant.intervention_evidence_id).not.toBe(base.intervention_evidence_id);});
});
