import { describe, expect, it } from "vitest";
import { bindOperationalSignalsToScopeV1, createOperationalSignalEvaluationScopeV1 } from "../../cockpit/operational.signal.evaluation.scope.v1";
import { createGovernedSourceEventCoverageCapabilityV1 } from "../../cognition/governed.source.event.coverage.capability.v1";
import { createOperationsGovernedFutureSupplyFactV1 } from "../cognition/operations.governed.future.supply.fact.v1";
import { OPERATIONS_FUTURE_SUPPLY_EVENT_CLASS, OPERATIONS_FUTURE_SUPPLY_REQUIRED_FIELDS, produceOperationsGovernedFutureSupplyCurrentSetV1 } from "../cognition/operations.governed.future.supply.currentness.v1";
import { bindOperationsCanonicalGovernedFutureSupplyV1, projectOperationsCanonicalGovernedFutureSupplyToBaselineAvailabilityV1, verifyOperationsCanonicalGovernedFutureSupplyV1 } from "../cognition/operations.canonical.governed.future.supply.v1";

const asOf="2026-08-18T10:00:00.000Z",available="2026-09-10T10:00:00.000Z",effective="2026-08-16T10:00:00.000Z";
async function setup(overrides:Record<string,unknown>={}){const scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"REQUEST_DATASET",request_id:"request-1",company_id:"company-1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1"}),evaluation_scope=await bindOperationalSignalsToScopeV1({scope,request_id:"request-1",company_id:"company-1",evidence_as_of:asOf,evaluated_at:"2026-08-18T10:01:00.000Z"}),fact=await createOperationsGovernedFutureSupplyFactV1({version:1,tenant_id:"tenant-1",company_id:"company-1",source_namespace:"source:erp-1",source_record_ref:"record:S1-v1",external_commitment_ref:"supply:S1",external_line_ref:"line:1",commitment_version_ref:"version:1",item_ref:"operations-item:SKU1",quantity:{value:10,source_unit:"EA"},available_at:available,effective_at:effective,observed_at:"2026-08-16T09:59:00.000Z",lifecycle:"ACTIVE",lifecycle_evidence_ref:"evidence:lifecycle",qualification_refs:["qualification:fact"],provenance_refs:["provenance:fact"],causal_lineage_refs:["lineage:fact"],...overrides}as any),coverage=await createGovernedSourceEventCoverageCapabilityV1({version:1,capability_policy_ref:"policy:supply-coverage",capability_policy_version:"1",tenant_id:"tenant-1",source_identity_ref:"source:erp-1",source_profile_ref:"profile:supply",source_profile_version:"1",source_boundary_ref:"boundary:snapshot",evaluation_scope,event_class_capabilities:[{domain_ref:"domain:operations",event_class_ref:OPERATIONS_FUTURE_SUPPLY_EVENT_CLASS,required_semantic_field_refs:OPERATIONS_FUTURE_SUPPLY_REQUIRED_FIELDS,guaranteed_semantic_field_refs:OPERATIONS_FUTURE_SUPPLY_REQUIRED_FIELDS,optional_semantic_field_refs:[]}],coverage_start:"2026-08-01T00:00:00.000Z",coverage_end:asOf,coverage_status:"COMPLETE",profile_capability_evidence_refs:["evidence:profile"],snapshot_completeness_evidence_refs:["evidence:complete"],qualification_refs:["qualification:coverage"],provenance_refs:["provenance:coverage"],causal_lineage_refs:["lineage:coverage"]}),current_set_result=await produceOperationsGovernedFutureSupplyCurrentSetV1({version:1,tenant_id:"tenant-1",source_namespace:"source:erp-1",evaluation_scope,source_coverage:coverage,source_facts:[fact],qualification_refs:["qualification:set"],provenance_refs:["provenance:set"],causal_lineage_refs:["lineage:set"]});return{fact,current_set_result}}
async function bind(overrides:Record<string,unknown>={},factOverrides:Record<string,unknown>={}){const x=await setup(factOverrides);return bindOperationsCanonicalGovernedFutureSupplyV1({version:1,current_set_result:x.current_set_result,source_fact:x.fact,qualification_refs:["qualification:canonical"],provenance_refs:["provenance:canonical"],causal_lineage_refs:["lineage:canonical"],...overrides}as any)}

describe("canonical governed future supply",()=>{
  it("binds exact current-set membership deterministically and immutably",async()=>{const a=await bind(),b=await bind();expect(a.canonical_supply_id).toBe(b.canonical_supply_id);expect(a).toMatchObject({current_governed_knowledge:true,physical_inventory:false,supply_kind:"GOVERNED_FUTURE_SUPPLY",request_id:"request-1",company_id:"company-1",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1"});expect(Object.isFrozen(a)&&Object.isFrozen(a.quantity)&&Object.isFrozen(a.causal_lineage_refs)).toBe(true);await expect(verifyOperationsCanonicalGovernedFutureSupplyV1(a)).resolves.toBeUndefined()});
  it("preserves commitment, item, quantity, unit and distinct temporal semantics",async()=>{const x=await bind();expect(x).toMatchObject({external_commitment_ref:"supply:S1",external_line_ref:"line:1",commitment_version_ref:"version:1",item_ref:"operations-item:SKU1",quantity:{value:10,source_unit:"EA"},knowledge_effective_at:effective,available_at:available,evidence_as_of:asOf});expect(x.available_at).not.toBe(x.knowledge_effective_at);expect(x.available_at>asOf).toBe(true)});
  it("rejects forged source facts, current sets and non-members",async()=>{const x=await setup();await expect(bindOperationsCanonicalGovernedFutureSupplyV1({version:1,current_set_result:x.current_set_result,source_fact:{...x.fact,quantity:{value:999,source_unit:"EA"}},qualification_refs:["q"],provenance_refs:["p"],causal_lineage_refs:["l"]})).rejects.toThrow("FACT_INTEGRITY_INVALID");await expect(bindOperationsCanonicalGovernedFutureSupplyV1({version:1,current_set_result:{...x.current_set_result,current_set:{...x.current_set_result.current_set,current_set_digest:"forged"}},source_fact:x.fact,qualification_refs:["q"],provenance_refs:["p"],causal_lineage_refs:["l"]})).rejects.toThrow("CURRENT_SET_INTEGRITY_INVALID");const other=(await setup({source_record_ref:"record:S2",external_commitment_ref:"supply:S2",commitment_version_ref:"version:S2"})).fact;await expect(bindOperationsCanonicalGovernedFutureSupplyV1({version:1,current_set_result:x.current_set_result,source_fact:other,qualification_refs:["q"],provenance_refs:["p"],causal_lineage_refs:["l"]})).rejects.toThrow("EXACT_MEMBERSHIP_REQUIRED")});
  it.each(["CANCELLED","REALIZED","SUPERSEDED"] as const)("cannot canonicalize %s",async lifecycle=>{const x=await setup(),bad={...x.fact,lifecycle,...(lifecycle==="REALIZED"?{realization:{receipt_event_ref:"receipt:1",realized_quantity:{value:10,source_unit:"EA"}}}:{})}as any;await expect(bindOperationsCanonicalGovernedFutureSupplyV1({version:1,current_set_result:x.current_set_result,source_fact:bad,qualification_refs:["q"],provenance_refs:["p"],causal_lineage_refs:["l"]})).rejects.toThrow()});
  it("changes identity for distinct governed commitments without aggregation",async()=>{const a=await bind(),b=await bind({}, {source_record_ref:"record:S2",external_commitment_ref:"supply:S2",commitment_version_ref:"version:S2"});expect(a.canonical_supply_id).not.toBe(b.canonical_supply_id);expect(a.aggregated).toBe(false);expect(b.aggregated).toBe(false)});
  it("projects exact governed future supply to baseline availability",async()=>{const x=await bind(),p=await projectOperationsCanonicalGovernedFutureSupplyToBaselineAvailabilityV1(x);expect(p).toMatchObject({availability_ref:x.canonical_supply_id,kind:"GOVERNED_FUTURE_SUPPLY",item_ref:x.item_ref,quantity:{value:10,unit_ref:"unit:EACH"},available_at:available,evidence_observed_at:effective});expect(p.evidence_refs).toEqual(expect.arrayContaining([x.current_set_ref,x.source_fact_ref]))});
  it("fails closed for unsupported unit projection",async()=>{await expect(projectOperationsCanonicalGovernedFutureSupplyToBaselineAvailabilityV1(await bind({}, {quantity:{value:10,source_unit:"KG"}}))).rejects.toThrow("UNIT_PROJECTION_UNSUPPORTED")});
  it("rejects caller truth, scenario, tier, plan, credit and economic contamination",async()=>{for(const unsafe of [{quantity:999},{available_at:"x"},{current_version:"x"},{scenario_supply:"x"},{optimizer_supply:"x"},{counterfactual_supply:"x"},{learned_supply:"x"},{llm_eta:"x"},{authority_tier:"CHARTER"},{commercial_plan:"paid"},{credit_balance:1},{remaining_capacity:1},{economic_approval:true},{upgrade_state:"approved"},{model_cost:1}])await expect(bind(unsafe)).rejects.toThrow("UNSAFE_INPUT")});
  it("retains qualification, provenance and lineage without recommendation, authority or execution",async()=>{const x=await bind();expect(x.qualification_refs).toEqual(expect.arrayContaining(["qualification:fact","qualification:set","qualification:canonical"]));expect(x.provenance_refs).toEqual(expect.arrayContaining(["provenance:fact","provenance:set","provenance:canonical"]));expect(x.causal_lineage_refs).toEqual(expect.arrayContaining([x.current_set_ref,x.source_fact_ref,"lineage:canonical"]));expect(x).toMatchObject({selected:false,recommended:false,executable:false,grants_authority:false,grants_execution:false})});
});
