import { describe,expect,it } from "vitest";
import { createMaterialOperationalConsequenceRefV1,createOperationalSubjectRefV1,createOperationsEvidenceProfileV1 } from "../../cognition/canonical.operational.roles.v1";
import { bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1 } from "../../cockpit/operational.signal.evaluation.scope.v1";
import { createCanonicalDecisionPressureProducerCertificationV1 } from "../../decision/canonical.decision.pressure.normalization.policy.v1";
import type { CanonicalOrderFact } from "../canonicalization/authoritative.order.fact";
import { evaluateOperationsBaselineCommitmentFeasibilityV1 } from "../cognition/operations.baseline.commitment.feasibility.v1";
import { assessOperationsImpactV1,createOperationsImpactProducerCertificationV1 } from "../cognition/operations.impact.v1";
import { assessOperationsObjectiveStateV1 } from "../cognition/operations.objective.state.v1";
import { bindOperationsOrderDeliveryCommitmentV1 } from "../cognition/operations.protected.objective.v1";

const asOf="2026-08-13T10:00:00.000Z",due="2026-08-20T10:00:00.000Z",ev={evidence_observed_at:"2026-08-13T09:00:00.000Z",evidence_refs:["evidence:1"],qualification_refs:["qualification:1"],provenance_refs:["provenance:1"],causal_lineage_refs:["lineage:1"]};
function order():CanonicalOrderFact{return {factId:"industrial-order:order-1",factFamily:"INDUSTRIAL_ORDER",schemaVersion:"1.0.0",owner:{tenantId:"t1",companyId:"company-1",ownerId:"owner-1"},source:{systemId:"s1",externalObjectId:"O1",externalObjectVersion:"2"},observedAt:ev.evidence_observed_at,effectiveAt:"2026-08-13T08:00:00.000Z",order:{sku:"SKU1",quantity:{value:5,unit:"EACH"},status:"OPEN",dueAt:due},provenance:{acquisitionReference:"acquisition-1",authorizationReference:"authorization-1",acquiredAt:"2026-08-13T09:05:00.000Z",capabilityId:"read_orders",connectorIdentityId:"connector-identity:erp-production-rest",connectorRevision:1,sourceRepresentation:"PRODUCTION_REST_ERP_ORDERS_V1",transformationId:"PRODUCTION_REST_ERP_ORDER_TO_CANONICAL_ORDER",transformationVersion:"1.0.0",canonicalSchemaVersion:"1.0.0",tenantId:"t1",companyId:"company-1",ownerId:"owner-1",sourceSystem:"s1",externalObjectId:"O1",externalObjectVersion:"2"}};}
async function chain(qty=2,boundary:"COMPLETE"|"PARTIAL"="COMPLETE"){const o=order(),scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"ENTITY",request_id:"request-1",company_id:"company-1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1",entity:{entity_type:"ORDER",entity_ref:o.factId}}),binding=await bindOperationalSignalsToScopeV1({scope,request_id:"request-1",company_id:"company-1",evidence_as_of:asOf,evaluated_at:"2026-08-13T10:01:00.000Z"}),c=await bindOperationsOrderDeliveryCommitmentV1({version:1,order_fact:o,evaluation_scope:binding,selected_objective_kind:"ORDER_DELIVERY_COMMITMENT",objective_selection_ref:"selection:objective",plan_element_ref:"plan:O1",protected_subject_ref:"subject:O1",qualification_refs:["qualification:order"],causal_lineage_refs:["lineage:order"],plan_lineage_refs:["lineage:plan"]}),f=await evaluateOperationsBaselineCommitmentFeasibilityV1({version:1,commitment:c,baseline_semantics:"BASELINE_CURRENT_PLAN",evidence_selection_ref:"selection:1",plan_orders:[{...ev,order_fact_ref:c.order_fact_ref,order_version_ref:c.order_version_ref,item_ref:c.item_ref,quantity:c.committed_quantity,due_at:c.committed_due_at}],availability:[{...ev,availability_ref:"availability:1",kind:"EFFECTIVE_INVENTORY",item_ref:c.item_ref,quantity:{value:qty,unit_ref:"unit:EACH"},available_at:asOf}],evidence_boundary:boundary}),state=await assessOperationsObjectiveStateV1({version:1,assessment_perspective:"CURRENT_EXPECTED",commitment:c,feasibility:f}),profile=await createOperationsEvidenceProfileV1(),subject=await createOperationalSubjectRefV1({version:1,company_id:"company:company-1",profile,subject_kind:"ORDER",subject_ref:"order:O1"}),consequence=await createMaterialOperationalConsequenceRefV1({version:1,subject,scope_ref:state.scope_id,evidence_refs:["evidence:consequence"],provenance_refs:["provenance:consequence"],causal_lineage_refs:[c.commitment_id,state.assessment_id],consequence_ref:"consequence:delivery-commitment-compromise",consequence_kind_ref:"operations-consequence:ORDER_DELIVERY_COMMITMENT_COMPROMISE",materiality_ref:"materiality:delivery-commitment"}),materiality={consequence_ref:consequence.consequence_ref,material_within_scope:true,affected_operational_refs:[c.commitment_id],materiality_evidence_refs:["evidence:materiality"],qualification_refs:["qualification:materiality"],provenance_refs:["provenance:materiality"],causal_lineage_refs:[c.commitment_id,state.assessment_id,consequence.role_id]},cert=await createOperationsImpactProducerCertificationV1();return{c,state,consequence,materiality,cert};}
async function impact(qty=2,boundary:"COMPLETE"|"PARTIAL"="COMPLETE"){const x=await chain(qty,boundary);return assessOperationsImpactV1({version:1,commitment:x.c,objective_state:x.state,consequence:x.consequence,materiality:x.materiality,producer_certification:x.cert});}

describe("PRESSURE-OPS-IMPACT-COGNITION-WU1 RESUME",()=>{
 it("produces deterministic immutable HIGH for an exact material current-expected breach",async()=>{const a=await impact(),b=await impact();expect(a).toEqual(b);expect(a).toMatchObject({dimension:"IMPACT",projection_mode:"ORDINAL",ordinal_state:"HIGH",producer_id:"pressure-producer:operations-order-delivery-impact-v1",observational_only:true,grants_execution:false});expect(Object.isFrozen(a)&&Object.isFrozen(a!.causal_lineage_refs)).toBe(true);expect(a).not.toHaveProperty("value");});
 it("does not default PRESERVED or UNRESOLVED objectives to LOW",async()=>{expect(await impact(5)).toBeNull();expect(await impact(5,"PARTIAL")).toBeNull();});
 it("requires materiality within scope and produces no unsupported anchor",async()=>{const x=await chain();expect(await assessOperationsImpactV1({version:1,commitment:x.c,objective_state:x.state,consequence:x.consequence,materiality:{...x.materiality,material_within_scope:false},producer_certification:x.cert})).toBeNull();expect((await impact())!).toMatchObject({projection_mode:"ORDINAL",ordinal_state:"HIGH"});});
 it("rejects unrelated consequences and missing exact causal links",async()=>{const x=await chain();await expect(assessOperationsImpactV1({version:1,commitment:x.c,objective_state:x.state,consequence:x.consequence,materiality:{...x.materiality,consequence_ref:"consequence:other"},producer_certification:x.cert})).rejects.toThrow("OPS_IMPACT_CONSEQUENCE_MISMATCH");await expect(assessOperationsImpactV1({version:1,commitment:x.c,objective_state:x.state,consequence:x.consequence,materiality:{...x.materiality,affected_operational_refs:["objective:other"]},producer_certification:x.cert})).rejects.toThrow("OPS_IMPACT_CONSEQUENCE_OBJECTIVE_LINK_REQUIRED");});
 it("rejects objective-state digest, company, scope, evidence-selection, and time substitution",async()=>{const x=await chain();for(const state of [{...x.state,assessment_digest:"bad"},{...x.state,company_id:"other"},{...x.state,scope_id:"scope:other"},{...x.state,evidence_selection_ref:"selection:other"},{...x.state,evidence_as_of:"2026-08-12T10:00:00.000Z"}])await expect(assessOperationsImpactV1({version:1,commitment:x.c,objective_state:state as any,consequence:x.consequence,materiality:x.materiality,producer_certification:x.cert})).rejects.toThrow();});
 it("requires exact canonical producer certification",async()=>{const x=await chain(),wrong=await createCanonicalDecisionPressureProducerCertificationV1({...x.cert,producer_id:"pressure-producer:other"});await expect(assessOperationsImpactV1({version:1,commitment:x.c,objective_state:x.state,consequence:x.consequence,materiality:x.materiality,producer_certification:wrong})).rejects.toThrow("OPS_IMPACT_CERTIFICATION_MISMATCH");expect(x.cert).toMatchObject({dimension:"IMPACT",projection_mode:"ORDINAL",supported_scope_kinds:["ENTITY"]});});
 it("retains qualification, provenance, consequence, materiality and causal lineage",async()=>{const x=await impact();expect(x!.qualification_refs).toEqual(expect.arrayContaining(["qualification:1","qualification:materiality"]));expect(x!.provenance_refs).toEqual(expect.arrayContaining(["provenance:1","provenance:consequence","provenance:materiality"]));expect(x!.normalization_input_refs).toHaveLength(3);});
 it("contains no Plan, Reality, V2, Pressure, Urgency, Cost-of-Waiting, or Junior shortcuts",async()=>{const json=JSON.stringify(await impact());expect(json).not.toMatch(/plan_state|reality_state|serviceShortfall|problemType|pressure_level|urgency|cost_of_waiting|recommendation|optimizer|candidate|ERP|SAP|MES/i);});
});
