import {describe,expect,it} from "vitest";
import {createOperationsDomainContextBindingV1,createOperationsDomainInterventionProfileV1} from "../cognition/operations.domain.intervention.profile.v1";
import {createOperationsInterventionCurrentPolicyProfileV1,resolveOperationsAllocationBoundaryPolicyV1,resolveOperationsAllocationConstraintPolicyV1,verifyOperationsInterventionCurrentPolicyProfileV1} from "../cognition/operations.intervention.current.policy.profile.v1";
async function policy(version="1",extra:readonly {fixation_class_key:string;fixation_class_ref:string}[]=[]){const [domain_context,intervention_profile]=await Promise.all([createOperationsDomainContextBindingV1(),createOperationsDomainInterventionProfileV1()]);return createOperationsInterventionCurrentPolicyProfileV1({version:1,domain_context,intervention_profile,policy_version:version,additional_fixation_classes:extra});}
describe("OPERATIONS-ALLOCATION-FIXATION-AND-PRIORITY-POLICY-DECISION-WU1",()=>{
 it("creates deterministic recursively immutable identity bound to exact Operations context/profile",async()=>{const a=await policy(),b=await policy(),context=await createOperationsDomainContextBindingV1(),profile=await createOperationsDomainInterventionProfileV1();expect(a.policy_profile_id).toBe(b.policy_profile_id);expect(a).toMatchObject({domain_context_ref:context.domain_context_id,intervention_profile_ref:profile.binding_profile_id,supported_dimension_key:"ALLOCATION_RELATIONSHIP",declarative_only:true});expect(Object.isFrozen(a)&&Object.isFrozen(a.fixation_classes)&&Object.isFrozen(a.constraint_bindings[0])).toBe(true);await expect(verifyOperationsInterventionCurrentPolicyProfileV1(a)).resolves.toBeUndefined();});
 it("supports only the allocation dimension and rejects silent dimension expansion",async()=>{const x=await policy();expect(resolveOperationsAllocationBoundaryPolicyV1(x,"ALLOCATION_RELATIONSHIP").boundary_policy_ref).toBe("policy:operations-allocation-effective-fixation-v1");expect(()=>resolveOperationsAllocationBoundaryPolicyV1(x,"MATERIAL_DEPENDENCY_RELATIONSHIP")).toThrow("OPS_CURRENT_POLICY_DIMENSION_UNSUPPORTED");});
 it("distinguishes planned/logical states from effected fixation",async()=>{const x=await policy();for(const key of ["PLANNED_ALLOCATION","RESERVATION","OPTIMIZER_ASSIGNMENT","SCENARIO_MUTATION","SOFTWARE_CAPABILITY_STATE","PLANNING_FREEZE_HORIZON","INTERNAL_SOFTWARE_LOCK"])expect(x.non_fixation_state_keys).toContain(key);expect(x.fixation_classes.map(y=>y.fixation_class_key)).toEqual(["EFFECTED_CONSUMPTION_OR_USE","EFFECTED_DESTINATION_SHIPMENT"]);expect(x.fixation_requires_exact_quantity_binding).toBe(true);});
 it("keeps fixation classes Operations-extensible by policy version",async()=>{const x=await policy("2",[{fixation_class_key:"FUTURE_GOVERNED_FIXATION",fixation_class_ref:"operations-fixation-class:future-governed"}]);expect(x.fixation_classes.at(-1)).toMatchObject({fixation_class_key:"FUTURE_GOVERNED_FIXATION",requires_effected_physical_evidence:true});expect(x.policy_profile_id).not.toBe((await policy()).policy_profile_id);});
 it("requires complete current coverage and explicit governed reversal evidence",async()=>{const x=await policy();expect(x).toMatchObject({absence_of_fixation_is_changeable_only_with_complete_coverage:true,release_requires_explicit_governed_reversal_evidence:true,release_currently_supported:false});});
 it.each([["ITEM_UNIT_COHERENCE","APPLICABLE","HARD"],["QUANTITY_CONSERVATION","APPLICABLE","HARD"],["COMPETING_DEMAND_PRIORITY","APPLICABLE","NON_BLOCKING"],["MATERIAL_FEASIBILITY","NOT_APPLICABLE",undefined],["TOPOLOGY_VALIDITY","NOT_APPLICABLE",undefined],["COMMITMENT_BOUNDARY","NOT_APPLICABLE",undefined]] as const)("binds %s to %s / %s",async(family,applicability,role)=>expect(resolveOperationsAllocationConstraintPolicyV1(await policy(),family)).toEqual({constraint_family_key:family,applicability,...(role?{constraint_role:role}:{})}));
 it("makes the full six-family set explicit so no inapplicable or required family disappears",async()=>{const x=await policy();expect(x.required_constraint_family_keys).toEqual(["COMMITMENT_BOUNDARY","COMPETING_DEMAND_PRIORITY","ITEM_UNIT_COHERENCE","MATERIAL_FEASIBILITY","QUANTITY_CONSERVATION","TOPOLOGY_VALIDITY"]);expect(x.constraint_bindings.map(y=>y.constraint_family_key)).toEqual(x.required_constraint_family_keys);});
 it("is compatible with the universal composer without embedding an Operations algorithm",async()=>{const x=await policy();expect(x).toMatchObject({admissibility_policy_ref:"policy:operations-allocation-admissibility-v1",zero_hard_constraint_rule:"ADMISSIBLE_WHEN_APPLICABILITY_COMPLETE",establishes_admissibility:false});});
 it("contains no current/company/source/tier/recommendation/authority/execution facts",async()=>{const x=await policy(),json=JSON.stringify(x);expect(x).toMatchObject({company_specific:false,establishes_current_changeability:false,establishes_current_constraint_result:false,recommended:false,selected:false,executable:false,grants_authority:false,grants_execution:false});expect(json).not.toMatch(/company_id|request_id|scope_id|order[-_:]?\d|sku[-_:]?\d|quantity_value|warehouse|customer|occurred_at|ERP|MES|SAP|email|chat|document|API|connector|VISION|GRADUATE|JUNIOR|SENIOR|PRINCIPAL|CHARTER|approval|delegation|credential/i);});
 it("rejects forged identity and exact profile substitution",async()=>{const x=await policy();await expect(verifyOperationsInterventionCurrentPolicyProfileV1({...x,policy_profile_digest:"0".repeat(64)})).rejects.toThrow("OPS_CURRENT_POLICY_INTEGRITY_INVALID");const context=await createOperationsDomainContextBindingV1(),profile=await createOperationsDomainInterventionProfileV1();await expect(createOperationsInterventionCurrentPolicyProfileV1({version:1,domain_context:{...context,domain_context_id:"canonical-domain-context:forged"},intervention_profile:profile,policy_version:"1"})).rejects.toThrow();});
});
