import { describe, expect, it } from "vitest";
import { bindOperationalSignalsToScopeV1, createOperationalSignalEvaluationScopeV1 } from "../../cockpit/operational.signal.evaluation.scope.v1";
import type { CanonicalOrderFact } from "../canonicalization/authoritative.order.fact";
import { evaluateOperationsBaselineCommitmentFeasibilityV1 } from "../cognition/operations.baseline.commitment.feasibility.v1";
import { assessOperationsObjectiveStateV1 } from "../cognition/operations.objective.state.v1";
import { bindOperationsOrderDeliveryCommitmentV1 } from "../cognition/operations.protected.objective.v1";

const asOf="2026-08-13T10:00:00.000Z",due="2026-08-20T10:00:00.000Z",e={evidence_observed_at:"2026-08-13T09:00:00.000Z",evidence_refs:["evidence:1"],qualification_refs:["qualification:1"],provenance_refs:["provenance:1"],causal_lineage_refs:["lineage:1"]};
function order():CanonicalOrderFact{return {factId:"industrial-order:order-1",factFamily:"INDUSTRIAL_ORDER",schemaVersion:"1.0.0",owner:{tenantId:"tenant-1",companyId:"company-1",ownerId:"owner-1"},source:{systemId:"system-1",externalObjectId:"O1",externalObjectVersion:"2"},observedAt:e.evidence_observed_at,effectiveAt:"2026-08-13T08:00:00.000Z",order:{sku:"SKU1",quantity:{value:5,unit:"EACH"},status:"OPEN",dueAt:due},provenance:{acquisitionReference:"acquisition-1",authorizationReference:"authorization-1",acquiredAt:"2026-08-13T09:05:00.000Z",capabilityId:"read_orders",connectorIdentityId:"connector-identity:erp-production-rest",connectorRevision:1,sourceRepresentation:"PRODUCTION_REST_ERP_ORDERS_V1",transformationId:"PRODUCTION_REST_ERP_ORDER_TO_CANONICAL_ORDER",transformationVersion:"1.0.0",canonicalSchemaVersion:"1.0.0",tenantId:"tenant-1",companyId:"company-1",ownerId:"owner-1",sourceSystem:"system-1",externalObjectId:"O1",externalObjectVersion:"2"}};}
async function commitment(){const f=order(),s=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"ENTITY",request_id:"request-1",company_id:"company-1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1",entity:{entity_type:"ORDER",entity_ref:f.factId}}),b=await bindOperationalSignalsToScopeV1({scope:s,request_id:"request-1",company_id:"company-1",evidence_as_of:asOf,evaluated_at:"2026-08-13T10:01:00.000Z"});return bindOperationsOrderDeliveryCommitmentV1({version:1,order_fact:f,evaluation_scope:b,selected_objective_kind:"ORDER_DELIVERY_COMMITMENT",objective_selection_ref:"selection:objective",plan_element_ref:"plan:O1",protected_subject_ref:"subject:O1",qualification_refs:["qualification:order"],causal_lineage_refs:["lineage:order"],plan_lineage_refs:["lineage:plan"]});}
async function pair(quantity=5,boundary:"COMPLETE"|"PARTIAL"="COMPLETE"){const c=await commitment(),f=await evaluateOperationsBaselineCommitmentFeasibilityV1({version:1,commitment:c,baseline_semantics:"BASELINE_CURRENT_PLAN",evidence_selection_ref:"selection:1",plan_orders:[{...e,order_fact_ref:c.order_fact_ref,order_version_ref:c.order_version_ref,item_ref:c.item_ref,quantity:c.committed_quantity,due_at:c.committed_due_at}],availability:[{...e,availability_ref:"availability:1",kind:"EFFECTIVE_INVENTORY",item_ref:c.item_ref,quantity:{value:quantity,unit_ref:"unit:EACH"},available_at:asOf}],evidence_boundary:boundary});return{c,f};}
async function assess(quantity=5,boundary:"COMPLETE"|"PARTIAL"="COMPLETE"){const{c,f}=await pair(quantity,boundary);return assessOperationsObjectiveStateV1({version:1,assessment_perspective:"CURRENT_EXPECTED",commitment:c,feasibility:f});}

describe("PRESSURE-OPS-OBJECTIVE-STATE-COGNITION-WU1 RESUME",()=>{
 it("maps complete current-expected feasibility only to PRESERVED",async()=>{const a=await assess(),b=await assess();expect(a).toEqual(b);expect(a).toMatchObject({assessment_perspective:"CURRENT_EXPECTED",assessment_status:"ASSESSED",objective_state:"PRESERVED",observational_only:true,grants_execution:false,grants_authority:false});expect(Object.isFrozen(a)&&Object.isFrozen(a.causal_lineage_refs)).toBe(true);});
 it("maps deterministic current-expected non-fulfillment to BREACHED, never LOST",async()=>{const x=await assess(2);expect(x).toMatchObject({assessment_status:"ASSESSED",objective_state:"BREACHED"});expect(JSON.stringify(x)).not.toMatch(/LOST/);});
 it("does not fabricate a state from UNRESOLVED feasibility",async()=>{const x=await assess(5,"PARTIAL");expect(x.assessment_status).toBe("UNRESOLVED");expect(x).not.toHaveProperty("objective_state");});
 it("fails closed on objective, order, version and item substitution",async()=>{const{c,f}=await pair();for(const changed of [{...f,protected_objective_ref:"objective:other"},{...f,order_fact_ref:"industrial-order:other"},{...f,order_version_ref:"order-version:other"},{...f,item_ref:"operations-item:other"}])await expect(assessOperationsObjectiveStateV1({version:1,assessment_perspective:"CURRENT_EXPECTED",commitment:c,feasibility:changed as any})).rejects.toThrow();});
 it("fails closed on company, scope, evidence-selection and timestamp substitution",async()=>{const{c,f}=await pair();for(const changed of [{...f,company_id:"other"},{...f,scope_id:"scope:other"},{...f,evidence_selection_ref:"selection:other"},{...f,evidence_as_of:"2026-08-12T10:00:00.000Z"}])await expect(assessOperationsObjectiveStateV1({version:1,assessment_perspective:"CURRENT_EXPECTED",commitment:c,feasibility:changed as any})).rejects.toThrow();});
 it("rejects candidate/scenario semantic substitution",async()=>{const{c,f}=await pair();await expect(assessOperationsObjectiveStateV1({version:1,assessment_perspective:"CURRENT_EXPECTED",commitment:c,feasibility:{...f,baseline_semantics:"CANDIDATE"} as any})).rejects.toThrow();await expect(assessOperationsObjectiveStateV1({version:1,assessment_perspective:"CANDIDATE" as any,commitment:c,feasibility:f})).rejects.toThrow("OPS_OBJECTIVE_STATE_PERSPECTIVE_UNSUPPORTED");});
 it("retains feasibility qualification, provenance and causal lineage",async()=>{const x=await assess();expect(x.qualification_refs).toEqual(["qualification:1"]);expect(x.provenance_refs).toEqual(["provenance:1"]);expect(x.causal_lineage_refs).toEqual(expect.arrayContaining(["lineage:1",x.feasibility_ref,x.protected_objective_ref]));});
 it("produces no unsupported DEGRADED/LOST, Impact, Pressure, or Junior semantics",async()=>{for(const x of [await assess(),await assess(2),await assess(5,"PARTIAL")])expect(JSON.stringify(x)).not.toMatch(/DEGRADED|LOST|impact|urgency|cost_of_waiting|pressure_level|recommendation|candidate|optimizer|ERP|SAP|MES|email|chat/i);});
});
