import { describe, expect, it } from "vitest";
import { bindOperationalSignalsToScopeV1, createOperationalSignalEvaluationScopeV1 } from "../../cockpit/operational.signal.evaluation.scope.v1";
import { createGovernedSourceEventCoverageCapabilityV1 } from "../../cognition/governed.source.event.coverage.capability.v1";
import { createOperationsGovernedFutureSupplyFactV1 } from "../cognition/operations.governed.future.supply.fact.v1";
import { OPERATIONS_FUTURE_SUPPLY_EVENT_CLASS, OPERATIONS_FUTURE_SUPPLY_REQUIRED_FIELDS, produceOperationsGovernedFutureSupplyCurrentSetV1, verifyOperationsGovernedFutureSupplyCurrentSetV1 } from "../cognition/operations.governed.future.supply.currentness.v1";

const asOf = "2026-08-18T10:00:00.000Z";
async function scope(company = "company-1", selection = "selection:1", snapshot = "snapshot:1") { const value = await createOperationalSignalEvaluationScopeV1({ version: 1, scope_type: "REQUEST_DATASET", request_id: "request-1", company_id: company, domain: "operations", evidence_selection_ref: selection, source_snapshot_ref: snapshot }); return bindOperationalSignalsToScopeV1({ scope: value, request_id: "request-1", company_id: company, evidence_as_of: asOf, evaluated_at: "2026-08-18T10:01:00.000Z" }); }
async function coverage(status: "COMPLETE" | "PARTIAL" | "INSUFFICIENT" = "COMPLETE", binding?: Awaited<ReturnType<typeof scope>>, source = "source:erp-1") { const evaluation_scope = binding ?? await scope(); return createGovernedSourceEventCoverageCapabilityV1({ version: 1, capability_policy_ref: "policy:supply-coverage", capability_policy_version: "1", tenant_id: "tenant-1", source_identity_ref: source, source_profile_ref: "profile:supply", source_profile_version: "1", source_boundary_ref: "boundary:snapshot", evaluation_scope, event_class_capabilities: [{ domain_ref: "domain:operations", event_class_ref: OPERATIONS_FUTURE_SUPPLY_EVENT_CLASS, required_semantic_field_refs: OPERATIONS_FUTURE_SUPPLY_REQUIRED_FIELDS, guaranteed_semantic_field_refs: status === "COMPLETE" ? OPERATIONS_FUTURE_SUPPLY_REQUIRED_FIELDS : [], optional_semantic_field_refs: [] }], coverage_start: "2026-08-01T00:00:00.000Z", coverage_end: asOf, coverage_status: status, profile_capability_evidence_refs: ["evidence:profile"], snapshot_completeness_evidence_refs: status === "COMPLETE" ? ["evidence:complete"] : [], qualification_refs: status === "COMPLETE" ? ["qualification:coverage"] : [], provenance_refs: ["provenance:coverage"], causal_lineage_refs: ["lineage:coverage"] }); }
const raw = { version: 1 as const, tenant_id: "tenant-1", company_id: "company-1", source_namespace: "source:erp-1", source_record_ref: "record:S1-v1", external_commitment_ref: "supply:S1", external_line_ref: "line:1", commitment_version_ref: "version:1", item_ref: "operations-item:SKU1", quantity: { value: 10, source_unit: "EA" }, available_at: "2026-09-10T10:00:00.000Z", effective_at: "2026-08-16T10:00:00.000Z", observed_at: "2026-08-16T09:59:00.000Z", lifecycle: "ACTIVE" as const, lifecycle_evidence_ref: "evidence:lifecycle", qualification_refs: ["qualification:fact"], provenance_refs: ["provenance:fact"], causal_lineage_refs: ["lineage:fact"] };
const fact = (overrides: Record<string, unknown> = {}) => createOperationsGovernedFutureSupplyFactV1({ ...raw, ...overrides } as any);
async function produce(facts: readonly any[], overrides: Record<string, unknown> = {}) { const evaluation_scope = await scope(); return produceOperationsGovernedFutureSupplyCurrentSetV1({ version: 1, tenant_id: "tenant-1", source_namespace: "source:erp-1", evaluation_scope, source_coverage: await coverage("COMPLETE", evaluation_scope), source_facts: facts, qualification_refs: ["qualification:set"], provenance_refs: ["provenance:set"], causal_lineage_refs: ["lineage:set"], ...overrides } as any); }

describe("operations governed future supply currentness", () => {
  it("produces a deterministic immutable complete scoped ACTIVE set", async () => { const source = await fact(), a = await produce([source]), b = await produce([source]); expect(a.current_set.current_set_id).toBe(b.current_set.current_set_id); expect(a.current_facts.map(value => value.fact_id)).toEqual([source.fact_id]); expect(a.current_set).toMatchObject({ company_id: "company-1", request_id: "request-1", evidence_selection_ref: "selection:1", source_snapshot_ref: "snapshot:1", evidence_as_of: asOf, complete_current_set: true, caller_selected_membership: false, caller_asserted_completeness: false }); expect(Object.isFrozen(a) && Object.isFrozen(a.current_set) && Object.isFrozen(a.current_facts)).toBe(true); await expect(verifyOperationsGovernedFutureSupplyCurrentSetV1(a)).resolves.toBeUndefined(); });
  it("admits future physical availability but excludes future-effective knowledge", async () => { const current = await fact(), future = await fact({ source_record_ref: "record:S2-v1", external_commitment_ref: "supply:S2", commitment_version_ref: "version:S2-1", effective_at: "2026-08-19T10:00:00.000Z" }); const result = await produce([future, current]); expect(result.current_facts.map(value => value.fact_id)).toEqual([current.fact_id]); expect(current.available_at > asOf).toBe(true); });
  it("uses explicit supersession, independent of input order and lexical version", async () => { const v1 = await fact({ commitment_version_ref: "version:z" }), v2 = await fact({ source_record_ref: "record:S1-v2", commitment_version_ref: "version:a", supersedes_version_ref: "version:z", available_at: "2026-09-14T10:00:00.000Z", quantity: { value: 8, source_unit: "EA" } }); const a = await produce([v1, v2]), b = await produce([v2, v1]); expect(a.current_facts[0]?.fact_id).toBe(v2.fact_id); expect(a.current_set.current_set_id).toBe(b.current_set.current_set_id); expect(a.current_set.historical_or_excluded_fact_refs).toContain(v1.fact_id); });
  it.each(["CANCELLED", "REALIZED", "SUPERSEDED"] as const)("excludes governing %s lifecycle", async lifecycle => { const v1 = await fact(), terminal = await fact({ source_record_ref: `record:${lifecycle}`, commitment_version_ref: "version:2", supersedes_version_ref: "version:1", lifecycle, ...(lifecycle === "REALIZED" ? { realization: { receipt_event_ref: "movement:receipt-1", realized_quantity: { value: 10, source_unit: "EA" } } } : {}) }); const result = await produce([v1, terminal]); expect(result.current_facts).toEqual([]); expect(result.current_set.historical_or_excluded_fact_refs).toEqual([terminal.fact_id, v1.fact_id].sort()); });
  it("rejects missing predecessors, cross-commitment supersession, cycles, branches and ambiguity", async () => { const missing = await fact({ commitment_version_ref: "version:2", supersedes_version_ref: "version:missing" }); await expect(produce([missing])).rejects.toThrow("PREDECESSOR_MISSING"); const other = await fact({ external_commitment_ref: "supply:S2", commitment_version_ref: "version:other" }), cross = await fact({ commitment_version_ref: "version:2", supersedes_version_ref: "version:other" }); await expect(produce([other, cross])).rejects.toThrow("CROSS_COMMITMENT"); const a = await fact({ commitment_version_ref: "version:a", supersedes_version_ref: "version:b" }), b = await fact({ source_record_ref: "record:b", commitment_version_ref: "version:b", supersedes_version_ref: "version:a" }); await expect(produce([a, b])).rejects.toThrow("SUPERSESSION_CYCLE"); const root = await fact(), left = await fact({ source_record_ref: "record:left", commitment_version_ref: "version:left", supersedes_version_ref: "version:1" }), right = await fact({ source_record_ref: "record:right", commitment_version_ref: "version:right", supersedes_version_ref: "version:1" }); await expect(produce([root, left, right])).rejects.toThrow("SUCCESSOR_BRANCH"); const ambiguous = await fact({ source_record_ref: "record:ambiguous", commitment_version_ref: "version:x" }); await expect(produce([root, ambiguous])).rejects.toThrow("CURRENT_VERSION_AMBIGUOUS"); });
  it.each(["PARTIAL", "INSUFFICIENT"] as const)("rejects %s coverage", async status => { const evaluation_scope = await scope(); await expect(produceOperationsGovernedFutureSupplyCurrentSetV1({ version: 1, tenant_id: "tenant-1", source_namespace: "source:erp-1", evaluation_scope, source_coverage: await coverage(status, evaluation_scope), source_facts: [await fact()], qualification_refs: ["qualification:set"], provenance_refs: ["provenance:set"], causal_lineage_refs: ["lineage:set"] })).rejects.toThrow("COMPLETE_COVERAGE_REQUIRED"); });
  it("rejects snapshot, company and source substitution", async () => { const source = await fact(); const wrongScope = await scope("company-1", "selection:1", "snapshot:2"); await expect(produce([source], { evaluation_scope: wrongScope })).rejects.toThrow(); await expect(produce([await fact({ company_id: "company-2" })])).rejects.toThrow("SOURCE_CONTEXT_MISMATCH"); await expect(produce([await fact({ source_namespace: "source:erp-2" })])).rejects.toThrow("SOURCE_CONTEXT_MISMATCH"); });
  it("rejects caller membership, current-version, completeness, scenario, optimizer, LLM, learning and tier authority", async () => { const source = await fact(); for (const unsafe of [{ current_members: [source] }, { current_version: source.fact_id }, { complete_current_set: true }, { scenario_supply: [] }, { optimizer_supply: [] }, { counterfactual_supply: [] }, { learned_eta: "x" }, { llm_eta: "x" }, { authority_tier: "CHARTER" }]) await expect(produce([source], unsafe)).rejects.toThrow("UNSAFE_INPUT"); });
  it("retains qualification, provenance and lineage with no authority or execution", async () => { const result = await produce([await fact()]); expect(result.current_set.qualification_refs).toEqual(expect.arrayContaining(["qualification:fact", "qualification:coverage", "qualification:set"])); expect(result.current_set.provenance_refs).toEqual(expect.arrayContaining(["provenance:fact", "provenance:coverage", "provenance:set"])); expect(result.current_set.causal_lineage_refs).toEqual(expect.arrayContaining(["lineage:fact", "lineage:set", result.current_set.coverage_ref])); expect(result.current_set).toMatchObject({ counterfactual: false, recommended: false, executable: false, grants_authority: false, grants_execution: false }); });
});
