import { describe, expect, it } from "vitest";
import { bindOperationalSignalsToScopeV1, createOperationalSignalEvaluationScopeV1 } from "../../cockpit/operational.signal.evaluation.scope.v1";
import type { CanonicalOrderFact } from "../canonicalization/authoritative.order.fact";
import { evaluateOperationsBaselineCommitmentFeasibilityV1, type BaselineAvailabilityV1, type BaselinePlanOrderV1 } from "../cognition/operations.baseline.commitment.feasibility.v1";
import { bindOperationsOrderDeliveryCommitmentV1 } from "../cognition/operations.protected.objective.v1";

const at="2026-08-13T10:00:00.000Z",due="2026-08-20T10:00:00.000Z";
function fact():CanonicalOrderFact{return {factId:"industrial-order:order-1",factFamily:"INDUSTRIAL_ORDER",schemaVersion:"1.0.0",owner:{tenantId:"tenant-1",companyId:"company-1",ownerId:"owner-1"},source:{systemId:"system-1",externalObjectId:"O1",externalObjectVersion:"2"},observedAt:"2026-08-13T09:00:00.000Z",effectiveAt:"2026-08-13T08:00:00.000Z",order:{sku:"SKU1",quantity:{value:5,unit:"EACH"},status:"OPEN",dueAt:due},provenance:{acquisitionReference:"acquisition-1",authorizationReference:"authorization-1",acquiredAt:"2026-08-13T09:05:00.000Z",capabilityId:"read_orders",connectorIdentityId:"connector-identity:erp-production-rest",connectorRevision:1,sourceRepresentation:"PRODUCTION_REST_ERP_ORDERS_V1",transformationId:"PRODUCTION_REST_ERP_ORDER_TO_CANONICAL_ORDER",transformationVersion:"1.0.0",canonicalSchemaVersion:"1.0.0",tenantId:"tenant-1",companyId:"company-1",ownerId:"owner-1",sourceSystem:"system-1",externalObjectId:"O1",externalObjectVersion:"2"}};}
async function commitment(){const f=fact(),s=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"ENTITY",request_id:"request-1",company_id:"company-1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1",entity:{entity_type:"ORDER",entity_ref:f.factId}}),b=await bindOperationalSignalsToScopeV1({scope:s,request_id:"request-1",company_id:"company-1",evidence_as_of:at,evaluated_at:"2026-08-13T10:01:00.000Z"});return bindOperationsOrderDeliveryCommitmentV1({version:1,order_fact:f,evaluation_scope:b,selected_objective_kind:"ORDER_DELIVERY_COMMITMENT",objective_selection_ref:"selection:objective",plan_element_ref:"plan:O1",protected_subject_ref:"subject:O1",qualification_refs:["qualification:order"],causal_lineage_refs:["lineage:order"],plan_lineage_refs:["lineage:plan"]});}
const evidence={evidence_observed_at:"2026-08-13T09:00:00.000Z",evidence_refs:["evidence:1"],qualification_refs:["qualification:1"],provenance_refs:["provenance:1"],causal_lineage_refs:["lineage:1"]};
async function plan(overrides:Partial<BaselinePlanOrderV1>={}):Promise<BaselinePlanOrderV1>{const c=await commitment();return {...evidence,order_fact_ref:c.order_fact_ref,order_version_ref:c.order_version_ref,item_ref:c.item_ref,quantity:c.committed_quantity,due_at:c.committed_due_at,...overrides};}
function availability(overrides:Partial<BaselineAvailabilityV1>={}):BaselineAvailabilityV1{return {...evidence,availability_ref:"availability:1",kind:"EFFECTIVE_INVENTORY",item_ref:"operations-item:SKU1",quantity:{value:5,unit_ref:"unit:EACH"},available_at:at,...overrides};}
async function input(overrides:Record<string,unknown>={}){return {version:1 as const,commitment:await commitment(),baseline_semantics:"BASELINE_CURRENT_PLAN" as const,evidence_selection_ref:"selection:1",plan_orders:[await plan()],availability:[availability()],evidence_boundary:"COMPLETE" as const,...overrides};}

describe("PRESSURE-OPS-BASELINE-COMMITMENT-FEASIBILITY-WU1",()=>{
 it("binds exact protected order/version/item/quantity/unit/scope and produces deterministic immutable feasibility",async()=>{const a=await evaluateOperationsBaselineCommitmentFeasibilityV1(await input()),b=await evaluateOperationsBaselineCommitmentFeasibilityV1(await input());expect(a).toEqual(b);expect(a).toMatchObject({result:"FULFILLABLE_BY_COMMITMENT",order_fact_ref:"industrial-order:order-1",order_version_ref:"order-version:2",item_ref:"operations-item:SKU1",committed_quantity:{value:5,unit_ref:"unit:EACH"},request_id:"request-1",company_id:"company-1",baseline_semantics:"BASELINE_CURRENT_PLAN"});expect(Object.isFrozen(a)&&Object.isFrozen(a.evidence_refs)&&Object.isFrozen(a.allocated_quantity)).toBe(true);});
 it("rejects wrong order, version, item, company, scope, and evidence selection",async()=>{const x=await input();await expect(evaluateOperationsBaselineCommitmentFeasibilityV1({...x,plan_orders:[await plan({order_fact_ref:"industrial-order:other"})]})).rejects.toThrow("OPS_BASELINE_ORDER_REQUIRED");await expect(evaluateOperationsBaselineCommitmentFeasibilityV1({...x,plan_orders:[await plan({order_version_ref:"order-version:3"})]})).rejects.toThrow("OPS_BASELINE_ORDER_VERSION_MISMATCH");await expect(evaluateOperationsBaselineCommitmentFeasibilityV1({...x,plan_orders:[await plan({item_ref:"operations-item:OTHER"})]})).rejects.toThrow("OPS_BASELINE_ITEM_MISMATCH");await expect(evaluateOperationsBaselineCommitmentFeasibilityV1({...x,commitment:{...x.commitment,objective_binding:{...x.commitment.objective_binding,company_id:"other"}}} as any)).rejects.toThrow("OPS_BASELINE_REQUEST_COMPANY_MISMATCH");await expect(evaluateOperationsBaselineCommitmentFeasibilityV1({...x,commitment:{...x.commitment,objective_binding:{...x.commitment.objective_binding,evaluation_scope:{...x.commitment.objective_binding.evaluation_scope,scope:{...x.commitment.objective_binding.evaluation_scope.scope,scope_type:"PATH"}}}}} as any)).rejects.toThrow("OPS_BASELINE_SCOPE_MISMATCH");await expect(evaluateOperationsBaselineCommitmentFeasibilityV1({...x,evidence_selection_ref:"selection:other"})).rejects.toThrow("OPS_BASELINE_EVIDENCE_SELECTION_MISMATCH");});
 it("uses matching effective inventory and ignores unrelated inventory",async()=>{const x=await evaluateOperationsBaselineCommitmentFeasibilityV1(await input({availability:[availability({item_ref:"operations-item:OTHER",quantity:{value:99,unit_ref:"unit:EACH"}}),availability({quantity:{value:5,unit_ref:"unit:EACH"}})]}));expect(x.result).toBe("FULFILLABLE_BY_COMMITMENT");expect(x.allocated_quantity.value).toBe(5);});
 it("admits temporally valid governed supply",async()=>{const x=await evaluateOperationsBaselineCommitmentFeasibilityV1(await input({availability:[availability({kind:"GOVERNED_FUTURE_SUPPLY",available_at:"2026-08-19T10:00:00.000Z"})]}));expect(x.result).toBe("FULFILLABLE_BY_COMMITMENT");});
 it("does not assume late or unknown future supply",async()=>{const late=await evaluateOperationsBaselineCommitmentFeasibilityV1(await input({availability:[availability({kind:"GOVERNED_FUTURE_SUPPLY",available_at:"2026-08-21T10:00:00.000Z"})],evidence_boundary:"PARTIAL"}));expect(late.result).toBe("UNRESOLVED");const unknown=await evaluateOperationsBaselineCommitmentFeasibilityV1(await input({availability:[availability({kind:"GOVERNED_FUTURE_SUPPLY",available_at:undefined as any})]}));expect(unknown.result).toBe("UNRESOLVED");});
 it("admits planned production only with established material feasibility and valid time",async()=>{const yes=await evaluateOperationsBaselineCommitmentFeasibilityV1(await input({availability:[availability({kind:"PLANNED_PRODUCTION",available_at:"2026-08-18T10:00:00.000Z",material_feasibility:"ESTABLISHED"})]}));expect(yes.result).toBe("FULFILLABLE_BY_COMMITMENT");const unresolved=await evaluateOperationsBaselineCommitmentFeasibilityV1(await input({availability:[availability({kind:"PLANNED_PRODUCTION",material_feasibility:"UNRESOLVED"})]}));expect(unresolved.result).toBe("UNRESOLVED");});
 it("produces NOT_FULFILLABLE only from a complete current-plan evidence boundary",async()=>{const no=await evaluateOperationsBaselineCommitmentFeasibilityV1(await input({availability:[availability({quantity:{value:2,unit_ref:"unit:EACH"}})]}));expect(no).toMatchObject({result:"NOT_FULFILLABLE_BY_COMMITMENT",allocated_quantity:{value:2},shortage_quantity:{value:3}});const partial=await evaluateOperationsBaselineCommitmentFeasibilityV1(await input({availability:[availability({quantity:{value:2,unit_ref:"unit:EACH"}})],evidence_boundary:"PARTIAL"}));expect(partial.result).toBe("UNRESOLVED");});
 it("does not turn a partial evidence boundary into an optimistic conclusion",async()=>{const x=await evaluateOperationsBaselineCommitmentFeasibilityV1(await input({evidence_boundary:"PARTIAL"}));expect(x.result).toBe("UNRESOLVED");});
 it("fails closed on unit mismatch and evidence observed after as-of",async()=>{await expect(evaluateOperationsBaselineCommitmentFeasibilityV1(await input({availability:[availability({quantity:{value:5,unit_ref:"unit:KG" as any}})]}))).rejects.toThrow("OPS_BASELINE_UNIT_MISMATCH");await expect(evaluateOperationsBaselineCommitmentFeasibilityV1(await input({availability:[availability({evidence_observed_at:"2026-08-14T10:00:00.000Z"})]}))).rejects.toThrow("OPS_BASELINE_EVIDENCE_AFTER_AS_OF");});
 it("keeps competing current-plan orders in allocation while unrelated SKU orders cannot affect it",async()=>{const competing=await plan({order_fact_ref:"industrial-order:earlier",order_version_ref:"order-version:1",quantity:{value:3,unit_ref:"unit:EACH"},due_at:"2026-08-19T10:00:00.000Z"});const x=await evaluateOperationsBaselineCommitmentFeasibilityV1(await input({plan_orders:[await plan(),competing],availability:[availability({quantity:{value:5,unit_ref:"unit:EACH"}})]}));expect(x.result).toBe("NOT_FULFILLABLE_BY_COMMITMENT");const unrelated=await plan({order_fact_ref:"industrial-order:other",order_version_ref:"order-version:1",item_ref:"operations-item:OTHER",quantity:{value:100,unit_ref:"unit:EACH"}});const y=await evaluateOperationsBaselineCommitmentFeasibilityV1(await input({plan_orders:[await plan(),unrelated]}));expect(y.result).toBe("FULFILLABLE_BY_COMMITMENT");});
 it("rejects corrective optimizer and scenario contamination",async()=>{await expect(evaluateOperationsBaselineCommitmentFeasibilityV1(await input({corrective_action_refs:["candidate:1"]}))).rejects.toThrow("OPS_BASELINE_CORRECTIVE_CANDIDATE_REJECTED");await expect(evaluateOperationsBaselineCommitmentFeasibilityV1(await input({scenario_modification_refs:["scenario:1"]}))).rejects.toThrow("OPS_BASELINE_SCENARIO_REJECTED");});
 it("retains qualification, provenance, causal evidence and remains observational VISION cognition",async()=>{const x=await evaluateOperationsBaselineCommitmentFeasibilityV1(await input()),json=JSON.stringify(x);expect(x).toMatchObject({qualification_refs:["qualification:1"],provenance_refs:["provenance:1"],causal_lineage_refs:["lineage:1"],observational_only:true,grants_execution:false,grants_authority:false,grants_remediation:false});expect(json).not.toMatch(/impact|urgency|cost_of_waiting|pressure_level|objective_state|recommendation|ERP|SAP|MES|email|chat/i);});
});
