import {describe,expect,it} from "vitest";
import {bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1} from "../../cockpit/operational.signal.evaluation.scope.v1";
import {createOperationsDomainContextBindingV1,createOperationsDomainInterventionProfileV1} from "../cognition/operations.domain.intervention.profile.v1";
import {createOperationsInterventionCurrentPolicyProfileV1} from "../cognition/operations.intervention.current.policy.profile.v1";
import {createOperationsGovernedAllocationStateV1} from "../cognition/operations.qualified.causal.evaluation.v1";
import {createOperationsAllocationFixationEvidenceCoverageV1,createOperationsAllocationFixationEvidenceV1,verifyOperationsAllocationFixationEvidenceV1} from "../cognition/operations.allocation.fixation.evidence.v1";
const at="2026-08-15T10:00:00.000Z",ev={evidence_observed_at:at,evidence_refs:["evidence:1"],qualification_refs:["qualification:1"],provenance_refs:["provenance:1"],causal_lineage_refs:["lineage:1"]};
async function setup(){const [context,profile]=await Promise.all([createOperationsDomainContextBindingV1(),createOperationsDomainInterventionProfileV1()]),policy=await createOperationsInterventionCurrentPolicyProfileV1({version:1,domain_context:context,intervention_profile:profile,policy_version:"1"}),scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"REQUEST_DATASET",request_id:"request:1",company_id:"company:1",domain:"operations",evidence_selection_ref:"selection:fixation",source_snapshot_ref:"snapshot:fixation"}),binding=await bindOperationalSignalsToScopeV1({scope,request_id:"request:1",company_id:"company:1",evidence_as_of:at,evaluated_at:"2026-08-15T10:01:00.000Z"}),order={...ev,order_fact_ref:"order:1",order_version_ref:"order-version:1",item_ref:"item:X",quantity:{value:100,unit_ref:"unit:EACH" as const},due_at:"2026-08-16T10:00:00.000Z"},availability={...ev,availability_ref:"availability:1",kind:"EFFECTIVE_INVENTORY" as const,item_ref:"item:X",quantity:{value:100,unit_ref:"unit:EACH" as const},available_at:at},state=await createOperationsGovernedAllocationStateV1({version:1,state_semantics:"CURRENT_GOVERNED",evaluation_scope:binding,plan_orders:[order],availability:[availability],order_precedence_refs:[order.order_fact_ref],governed_state_evidence_ref:"evidence:allocation-state"});return{policy,state};}
async function evidence(overrides:Record<string,unknown>={}){const f=await setup();return createOperationsAllocationFixationEvidenceV1({version:1,policy:f.policy,current_state:f.state,evidence_selection_ref:"selection:fixation",allocation_relationship_ref:"allocation-relationship:1",fixation_class_key:"EFFECTED_CONSUMPTION_OR_USE",governed_event_ref:"governed-event:1",canonical_event_identity_ref:"physical-event:1",allocation_attribution_ref:"allocation-attribution:1",item_ref:"item:X",allocation_quantity:{value:100,unit_ref:"unit:EACH"},attributed_fixation_quantity:{value:40,unit_ref:"unit:EACH"},process_or_usage_ref:"process:1",occurred_at:"2026-08-15T09:00:00.000Z",effected_at:"2026-08-15T09:01:00.000Z",...ev,evidence_as_of:at,...overrides} as any);}
describe("OPERATIONS-ALLOCATION-FIXATION-EVIDENCE-BINDING-SEMANTICS-WU1",()=>{
 it("creates deterministic recursively immutable exact relationship/state/event/quantity evidence",async()=>{const a=await evidence(),b=await evidence();expect(a.fixation_evidence_id).toBe(b.fixation_evidence_id);expect(a).toMatchObject({allocation_relationship_ref:"allocation-relationship:1",allocation_current_state_ref:expect.stringMatching(/^operations-governed-allocation-state:/),canonical_event_identity_ref:"physical-event:1",attributed_fixation_quantity:{value:40,unit_ref:"unit:EACH"},partial_fixation:true,whole_relationship_fixation_asserted:false});expect(Object.isFrozen(a)&&Object.isFrozen(a.attributed_fixation_quantity)).toBe(true);await expect(verifyOperationsAllocationFixationEvidenceV1(a)).resolves.toBeUndefined();});
 it("supports consumption only with exact process attribution",async()=>{await expect(evidence({process_or_usage_ref:undefined})).rejects.toThrow("OPS_FIXATION_USAGE_REQUIRED");});
 it("supports shipment only with exact destination or commitment attribution",async()=>{await expect(evidence({fixation_class_key:"EFFECTED_DESTINATION_SHIPMENT",process_or_usage_ref:undefined})).rejects.toThrow("OPS_FIXATION_DESTINATION_REQUIRED");expect(await evidence({fixation_class_key:"EFFECTED_DESTINATION_SHIPMENT",process_or_usage_ref:undefined,destination_or_commitment_ref:"commitment:1"})).toMatchObject({fixation_class_key:"EFFECTED_DESTINATION_SHIPMENT",destination_or_commitment_ref:"commitment:1"});});
 it("preserves partial quantities and rejects over-attribution or unit substitution",async()=>{expect((await evidence()).partial_fixation).toBe(true);await expect(evidence({attributed_fixation_quantity:{value:101,unit_ref:"unit:EACH"}})).rejects.toThrow("OPS_FIXATION_ATTRIBUTED_QUANTITY_EXCEEDS_ALLOCATION");await expect(evidence({attributed_fixation_quantity:{value:40,unit_ref:"unit:KG"}})).rejects.toThrow("OPS_FIXATION_UNIT_MISMATCH");});
 it("keeps multiple physical events individually identifiable and canonically deduplicable",async()=>{const a=await evidence(),b=await evidence({governed_event_ref:"governed-event:2",canonical_event_identity_ref:"physical-event:2"});expect(a.fixation_evidence_id).not.toBe(b.fixation_evidence_id);expect((await evidence()).fixation_evidence_id).toBe(a.fixation_evidence_id);});
 it.each(["source_movement_type","sku_only_attribution","quantity_coincidence","timestamp_proximity","order_guess","planned_allocation","reservation","optimizer_assignment","internal_freeze","llm_attribution"])("rejects unsafe attribution source %s",async key=>await expect(evidence({[key]:"unsafe:1"})).rejects.toThrow("OPS_FIXATION_UNSAFE_ATTRIBUTION"));
 it("rejects another state, company or scope through exact immutable state binding",async()=>{const x=await evidence();await expect(verifyOperationsAllocationFixationEvidenceV1({...x,allocation_current_state_ref:"state:other"})).rejects.toThrow("OPS_FIXATION_INTEGRITY_INVALID");await expect(verifyOperationsAllocationFixationEvidenceV1({...x,company_id:"company:other"})).rejects.toThrow("OPS_FIXATION_INTEGRITY_INVALID");});
 it("binds coverage to exact relationship/state/classes/time without asserting event absence",async()=>{const f=await setup(),classes=f.policy.fixation_classes.map(x=>x.fixation_class_key),x=await createOperationsAllocationFixationEvidenceCoverageV1({version:1,policy:f.policy,current_state:f.state,evidence_selection_ref:"selection:fixation",allocation_relationship_ref:"allocation-relationship:1",covered_fixation_class_keys:classes,coverage_from:"2026-08-15T08:00:00.000Z",coverage_through:at,coverage_basis_ref:"data-awareness:fixation-events",coverage_status:"COMPLETE",...ev});expect(x).toMatchObject({allocation_current_state_ref:f.state.state_id,covered_fixation_class_keys:classes.sort(),coverage_status:"COMPLETE",asserts_event_absence:false,establishes_changeability:false});});
 it("prevents incomplete class coverage from impersonating COMPLETE",async()=>{const f=await setup();await expect(createOperationsAllocationFixationEvidenceCoverageV1({version:1,policy:f.policy,current_state:f.state,evidence_selection_ref:"selection:fixation",allocation_relationship_ref:"allocation-relationship:1",covered_fixation_class_keys:["EFFECTED_CONSUMPTION_OR_USE"],coverage_from:"2026-08-15T08:00:00.000Z",coverage_through:at,coverage_basis_ref:"data-awareness:fixation-events",coverage_status:"COMPLETE",...ev})).rejects.toThrow("OPS_FIXATION_COVERAGE_COMPLETE_CLASSES_REQUIRED");});
 it("keeps coverage status distinct from unrelated evidence-boundary labels",async()=>{const f=await setup();await expect(createOperationsAllocationFixationEvidenceCoverageV1({version:1,policy:f.policy,current_state:f.state,evidence_selection_ref:"selection:fixation",allocation_relationship_ref:"allocation-relationship:1",covered_fixation_class_keys:[],coverage_from:"2026-08-15T08:00:00.000Z",coverage_through:at,coverage_basis_ref:"data-awareness:fixation-events",coverage_status:"EVIDENCE_BOUNDARY_COMPLETE" as any,...ev})).rejects.toThrow("OPS_FIXATION_COVERAGE_STATUS_INVALID");});
 it("requires qualification, provenance and causal lineage",async()=>{await expect(evidence({qualification_refs:[]})).rejects.toThrow("OPS_FIXATION_QUALIFICATION_REQUIRED");await expect(evidence({provenance_refs:[]})).rejects.toThrow("OPS_FIXATION_PROVENANCE_REQUIRED");await expect(evidence({causal_lineage_refs:[]})).rejects.toThrow("OPS_FIXATION_LINEAGE_REQUIRED");});
 it("produces no changeability, constraints, admissibility, recommendation, authority or execution",async()=>{const x=await evidence(),json=JSON.stringify(x);expect(x).toMatchObject({establishes_changeability:false,establishes_constraint_result:false,establishes_admissibility:false,recommended:false,executable:false,grants_authority:false,grants_execution:false});expect(json).not.toMatch(/changeability_status|constraint_result_status|admissibility_status|VISION|GRADUATE|JUNIOR|SENIOR|PRINCIPAL|CHARTER/);});
});
