import {describe,expect,it} from "vitest";
import {bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1} from "../../cockpit/operational.signal.evaluation.scope.v1";
import {createGovernedCausalBaselineV1} from "../../cognition/qualified.causal.evaluation.v1";
import {createProtectedOperationalObjectiveBindingV1} from "../../cognition/protected.operational.objective.v1";
import {createOperationsDomainContextBindingV1,createOperationsDomainInterventionProfileV1} from "../cognition/operations.domain.intervention.profile.v1";
import {bindOperationsGovernedPerturbationV1,createOperationsGovernedPerturbationOperandV1,verifyOperationsGovernedPerturbationOperandV1} from "../cognition/operations.governed.perturbation.operand.v1";

const at="2026-08-15T10:00:00Z",done="2026-08-15T10:01:00Z";
async function context(){const domain_context=await createOperationsDomainContextBindingV1(),intervention_profile=await createOperationsDomainInterventionProfileV1(),scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"REQUEST_DATASET",request_id:"request:1",company_id:"company:1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1"}),evaluation_scope=await bindOperationalSignalsToScopeV1({scope,request_id:"request:1",company_id:"company:1",evidence_as_of:at,evaluated_at:done}),objective=await createProtectedOperationalObjectiveBindingV1({version:1,request_id:"request:1",company_id:"company:1",evaluation_scope,domain_profile_ref:"domain-profile:operations",domain_profile_version:"1",objective_kind_ref:"objective-kind:delivery",objective_ref:"objective:1",governing_expected_state_refs:["state:accepted-plan"],governing_plan_element_refs:["plan:1"],protected_subject_refs:["subject:1"],commitment_criteria_refs:["criterion:1"],objective_selection_ref:"selection:objective",source_evidence_refs:["evidence:objective"],provenance_refs:["provenance:objective"],qualification_refs:["qualification:objective"],causal_lineage_refs:["lineage:objective"],plan_lineage_refs:["lineage:plan"],effective_at:"2026-08-15T09:00:00Z",evidence_as_of:at,evaluated_at:done}),baseline=await createGovernedCausalBaselineV1({version:1,request_id:"request:1",company_id:"company:1",evaluation_scope,domain_context,current_state_ref:"state:accepted-plan",protected_objective:objective,governing_condition_ref:"condition:delivery",trajectory_ref:"trajectory:baseline-feasibility",evidence_refs:["evidence:baseline"],qualification_refs:["qualification:baseline"],provenance_refs:["provenance:baseline"],causal_lineage_refs:["lineage:baseline"],evidence_as_of:at,evaluated_at:done});return{domain_context,intervention_profile,evaluation_scope,objective,baseline};}
async function operand(overrides:Record<string,unknown>={}){const c=await context(),primitive=c.intervention_profile.intervention_primitives.find(x=>x.primitive_key==="CHANGE_ALLOCATION_RELATIONSHIP")!;const input={version:1 as const,baseline:c.baseline,domain_context:c.domain_context,intervention_profile:c.intervention_profile,dimension_key:"ALLOCATION_RELATIONSHIP",intervention_primitive_key:"CHANGE_ALLOCATION_RELATIONSHIP",affected_relationship_ref:"relationship:allocation-set",baseline_state_ref:"allocation-state:current",counterfactual_state_ref:"allocation-state:governed-alternative",derivation_basis:"EXISTING_GOVERNED_ALTERNATIVE" as const,derivation_policy_ref:"policy:operations-existing-alternative-v1",governed_alternative_evidence_ref:"evidence:governed-alternative",constraint_family_keys:["COMPETING_DEMAND_PRIORITY","ITEM_UNIT_COHERENCE","QUANTITY_CONSERVATION"],bound_refs:["bound:competing-demand","bound:quantity-conservation"],quantity_invariant:{baseline_quantity_ref:"quantity-state:current",counterfactual_quantity_ref:"quantity-state:alternative",unit_ref:"unit:EACH",conservation_evidence_ref:"evidence:quantity-conservation"},evidence_refs:["evidence:governed-alternative","evidence:baseline"],qualification_refs:["qualification:governed-alternative"],provenance_refs:["provenance:current-plan"],causal_lineage_refs:["lineage:alternative-enumeration"],...overrides};return{...c,primitive,input,value:await createOperationsGovernedPerturbationOperandV1(input as never)};}

describe("OPERATIONS-GOVERNED-PERTURBATION-OPERAND-SEMANTICS-WU1",()=>{
 it("creates deterministic recursively immutable Operations operand identity",async()=>{const a=await operand(),b=await operand();expect(a.value.operand_id).toBe(b.value.operand_id);expect(Object.isFrozen(a.value)&&Object.isFrozen(a.value.constraint_family_keys)&&Object.isFrozen(a.value.quantity_invariant)).toBe(true);await expect(verifyOperationsGovernedPerturbationOperandV1(a.value)).resolves.toBeUndefined();});
 it("binds exact context, profile, baseline, request, company and scope",async()=>{const x=await operand();expect(x.value).toMatchObject({domain_ref:"domain:operations",domain_context_ref:x.domain_context.domain_context_id,intervention_profile_ref:x.intervention_profile.binding_profile_id,baseline_ref:x.baseline.baseline_id,request_id:"request:1",company_id:"company:1",scope_id:x.evaluation_scope.scope.scope_id});});
 it("binds admitted dimension, primitive and class through the frozen profile",async()=>{const x=await operand();expect(x.value).toMatchObject({dimension_key:"ALLOCATION_RELATIONSHIP",intervention_primitive_key:"CHANGE_ALLOCATION_RELATIONSHIP",admitted_intervention_class_ref:x.primitive.admitted_intervention_class_ref});for(const overrides of [{dimension_key:"UNKNOWN"},{intervention_primitive_key:"UNKNOWN"},{dimension_key:"COMMITMENT_TIMING_RELATIONSHIP"}])await expect(operand(overrides)).rejects.toThrow("OPS_PERTURBATION_PROFILE_BINDING_UNSUPPORTED");});
 it("represents an existing governed alternative by reference without mutating current facts",async()=>{const x=await operand();expect(x.value).toMatchObject({affected_relationship_ref:"relationship:allocation-set",baseline_state_ref:"allocation-state:current",counterfactual_state_ref:"allocation-state:governed-alternative",derivation_basis:"EXISTING_GOVERNED_ALTERNATIVE",derived_not_observed:true,current_fact:false});expect(x.baseline.current_state_ref).toBe("state:accepted-plan");});
 it("requires a distinct governed alternative and explicit source, policy and baseline lineage",async()=>{await expect(operand({counterfactual_state_ref:"allocation-state:current"})).rejects.toThrow("OPS_PERTURBATION_ALTERNATIVE_MUST_DIFFER");await expect(operand({governed_alternative_evidence_ref:""})).rejects.toThrow("OPS_PERTURBATION_ALTERNATIVE_EVIDENCE_REQUIRED");await expect(operand({derivation_policy_ref:""})).rejects.toThrow("OPS_PERTURBATION_POLICY_REQUIRED");const x=await operand();expect(x.value.causal_lineage_refs).toEqual(expect.arrayContaining([x.baseline.baseline_id,"allocation-state:current","allocation-state:governed-alternative"]));});
 it("preserves quantitative unit and conservation evidence by reference",async()=>{const x=await operand();expect(x.value.quantity_invariant).toEqual({baseline_quantity_ref:"quantity-state:current",counterfactual_quantity_ref:"quantity-state:alternative",unit_ref:"unit:EACH",conservation_evidence_ref:"evidence:quantity-conservation"});await expect(operand({quantity_invariant:{baseline_quantity_ref:"quantity:1",counterfactual_quantity_ref:"quantity:2",unit_ref:"",conservation_evidence_ref:"evidence:1"}})).rejects.toThrow("OPS_PERTURBATION_UNIT_REQUIRED");});
 it("supports timing/effectivity alternatives through the same envelope when already governed",async()=>{const x=await operand({dimension_key:"COMMITMENT_TIMING_RELATIONSHIP",intervention_primitive_key:"CHANGE_AVAILABILITY_TIMING",affected_relationship_ref:"relationship:availability",baseline_state_ref:"availability-state:current",counterfactual_state_ref:"availability-state:governed-alternative",constraint_family_keys:["COMMITMENT_BOUNDARY","MATERIAL_FEASIBILITY"],bound_refs:["bound:commitment","bound:material"],quantity_invariant:undefined,effectivity_binding:{baseline_effectivity_ref:"effectivity:current",counterfactual_effectivity_ref:"effectivity:alternative",temporal_bound_refs:["bound:temporal"]}});expect(x.value.effectivity_binding?.temporal_bound_refs).toEqual(["bound:temporal"]);});
 it("requires profile-governed constraints and explicit bounds",async()=>{await expect(operand({constraint_family_keys:["UNKNOWN"]})).rejects.toThrow("OPS_PERTURBATION_CONSTRAINT_UNSUPPORTED");await expect(operand({bound_refs:[]})).rejects.toThrow("OPS_PERTURBATION_BOUND_REQUIRED");await expect(operand({quantity_invariant:undefined})).rejects.toThrow("OPS_PERTURBATION_DOMAIN_INVARIANT_REQUIRED");});
 it.each(["action_instance","action_payload","recommendation_ref","execution_payload","authority_tier","optimizer_candidate_ref","random_candidate","generated_candidate","heuristic_action","scenario_mutation","simulation_result"])('rejects prohibited source "%s"',async key=>{await expect(operand({[key]:"forbidden:1"})).rejects.toThrow("OPS_PERTURBATION_UNSUPPORTED_SOURCE");});
 it("binds the domain operand into unchanged GovernedBoundedPerturbationV1",async()=>{const x=await operand(),bounded=await bindOperationsGovernedPerturbationV1({operand:x.value,baseline:x.baseline,domain_context:x.domain_context,intervention_profile:x.intervention_profile,admissibility_boundary_ref:"admissibility-boundary:unresolved"});expect(bounded).toMatchObject({baseline_ref:x.baseline.baseline_id,perturbation_parameter_ref:x.value.operand_id,dimension_key:x.value.dimension_key,intervention_primitive_key:x.value.intervention_primitive_key,epistemic_basis:"DETERMINISTIC_COUNTERFACTUAL",hypothetical_only:true,action_instance_absent:true});});
 it("claims neither changeability, admissibility, material effect, recommendation nor execution",async()=>{const x=await operand();expect(x.value).toMatchObject({claims_changeability:false,claims_admissibility:false,establishes_material_effect:false,recommended:false,selected:false,executable:false,grants_authority:false,grants_execution:false,grants_remediation:false});});
 it.each(["VISION","GRADUATE","JUNIOR","SENIOR","PRINCIPAL","CHARTER"])("is tier-independent for %s",async()=>{const x=await operand();expect(JSON.stringify(x.value)).not.toMatch(/VISION|GRADUATE|JUNIOR|SENIOR|PRINCIPAL|CHARTER|subscription|approval|delegation|credential/i);});
 it("is source neutral and introduces no downstream cognition",async()=>{const x=await operand(),json=JSON.stringify(x.value);expect(json).not.toMatch(/ERP|MES|SAP|API|email|chat|document|connector/i);expect(json).not.toMatch(/influenceability|opportunity|urgency|cost.of.waiting|pressure/i);});
 it("rejects forged identity and boundary flags",async()=>{const x=await operand();await expect(verifyOperationsGovernedPerturbationOperandV1({...x.value,operand_digest:"0".repeat(64)})).rejects.toThrow("OPS_PERTURBATION_INTEGRITY_INVALID");await expect(verifyOperationsGovernedPerturbationOperandV1({...x.value,recommended:true as false})).rejects.toThrow("OPS_PERTURBATION_BOUNDARY_INVALID");});
});
