import {describe,expect,it} from "vitest";
import {bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1} from "../../cockpit/operational.signal.evaluation.scope.v1";
import type {CanonicalOrderFact} from "../canonicalization/authoritative.order.fact";
import {evaluateOperationsBaselineCommitmentFeasibilityV1,type BaselineAvailabilityV1,type BaselinePlanOrderV1} from "../cognition/operations.baseline.commitment.feasibility.v1";
import {deriveOperationsCurrentFulfillmentPositionV1} from "../cognition/operations.current.fulfillment.position.v1";
import {bindOperationsOrderDeliveryCommitmentV1} from "../cognition/operations.protected.objective.v1";

const asOf="2026-08-13T10:00:00.000Z",due="2026-08-20T10:00:00.000Z";
const ev={evidence_observed_at:"2026-08-13T09:00:00.000Z",evidence_refs:["evidence:availability"],qualification_refs:["qualification:admitted"],provenance_refs:["provenance:source"],causal_lineage_refs:["lineage:baseline"]};
function fact():CanonicalOrderFact{return{factId:"industrial-order:order-1",factFamily:"INDUSTRIAL_ORDER",schemaVersion:"1.0.0",owner:{tenantId:"tenant-1",companyId:"company-1",ownerId:"owner-1"},source:{systemId:"system-1",externalObjectId:"O1",externalObjectVersion:"2"},observedAt:ev.evidence_observed_at,effectiveAt:"2026-08-13T08:00:00.000Z",order:{sku:"SKU1",quantity:{value:5,unit:"EACH"},status:"OPEN",dueAt:due},provenance:{acquisitionReference:"acquisition-1",authorizationReference:"authorization-1",acquiredAt:"2026-08-13T09:05:00.000Z",capabilityId:"read_orders",connectorIdentityId:"connector-identity:any",connectorRevision:1,sourceRepresentation:"PRODUCTION_REST_ERP_ORDERS_V1",transformationId:"PRODUCTION_REST_ERP_ORDER_TO_CANONICAL_ORDER",transformationVersion:"1.0.0",canonicalSchemaVersion:"1.0.0",tenantId:"tenant-1",companyId:"company-1",ownerId:"owner-1",sourceSystem:"system-1",externalObjectId:"O1",externalObjectVersion:"2"}};}
async function commitment(){const f=fact(),scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"ENTITY",request_id:"request-1",company_id:"company-1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1",entity:{entity_type:"ORDER",entity_ref:f.factId}}),binding=await bindOperationalSignalsToScopeV1({scope,request_id:"request-1",company_id:"company-1",evidence_as_of:asOf,evaluated_at:"2026-08-13T10:01:00.000Z"});return bindOperationsOrderDeliveryCommitmentV1({version:1,order_fact:f,evaluation_scope:binding,selected_objective_kind:"ORDER_DELIVERY_COMMITMENT",objective_selection_ref:"selection:objective",plan_element_ref:"plan:O1",protected_subject_ref:"subject:O1",qualification_refs:["qualification:order"],causal_lineage_refs:["lineage:order"],plan_lineage_refs:["lineage:plan"]});}
function availability(overrides:Partial<BaselineAvailabilityV1>={}):BaselineAvailabilityV1{return{...ev,availability_ref:"availability:1",kind:"GOVERNED_FUTURE_SUPPLY",item_ref:"operations-item:SKU1",quantity:{value:5,unit_ref:"unit:EACH"},available_at:"2026-08-18T10:00:00.000Z",...overrides};}
async function setup(overrides:{availability?:BaselineAvailabilityV1[];orders?:BaselinePlanOrderV1[];boundary?:"COMPLETE"|"PARTIAL"}={}){const c=await commitment(),protectedOrder:BaselinePlanOrderV1={...ev,order_fact_ref:c.order_fact_ref,order_version_ref:c.order_version_ref,item_ref:c.item_ref,quantity:c.committed_quantity,due_at:c.committed_due_at},plan_orders=overrides.orders??[protectedOrder],availabilityFacts=overrides.availability??[availability()],evidence_boundary=overrides.boundary??"COMPLETE",f=await evaluateOperationsBaselineCommitmentFeasibilityV1({version:1,commitment:c,baseline_semantics:"BASELINE_CURRENT_PLAN",evidence_selection_ref:"selection:1",plan_orders,availability:availabilityFacts,evidence_boundary});return{c,f,plan_orders,availability:availabilityFacts,evidence_boundary};}
async function position(x?:Awaited<ReturnType<typeof setup>>,overrides:Record<string,unknown>={}){const state=x??await setup();return deriveOperationsCurrentFulfillmentPositionV1({version:1,commitment:state.c,baseline_feasibility:state.f,baseline_semantics:"BASELINE_CURRENT_PLAN",evidence_selection_ref:"selection:1",plan_orders:state.plan_orders,availability:state.availability,evidence_boundary:state.evidence_boundary,...overrides} as any);}

describe("OPS-CURRENT-FULFILLMENT-POSITION-WU1",()=>{
 it("resolves the earliest full-quantity fulfillment-relevant availability position deterministically and immutably",async()=>{const x=await setup({availability:[availability({availability_ref:"availability:early",quantity:{value:2,unit_ref:"unit:EACH"},available_at:asOf}),availability({availability_ref:"availability:full",quantity:{value:3,unit_ref:"unit:EACH"}})]}),a=await position(x),b=await position(x);expect(a).toMatchObject({status:"RESOLVED",position_kind:"CURRENT_PLAN_FULFILLMENT_RELEVANT_AVAILABILITY",current_position_at:"2026-08-18T10:00:00.000Z",temporal_unit_ref:"time:INSTANT",committed_quantity:{value:5,unit_ref:"unit:EACH"}});expect(a.position_id).toBe(b.position_id);expect(Object.isFrozen(a)&&Object.isFrozen(a.committed_quantity)&&Object.isFrozen(a.evidence_refs)).toBe(true);});
 it("requires full quantity and never promotes partial readiness",async()=>{const x=await setup({availability:[availability({quantity:{value:4,unit_ref:"unit:EACH"}})]}),result=await position(x);expect(result.status).toBe("INSUFFICIENT_EVIDENCE");expect(result).not.toHaveProperty("current_position_at");});
 it("accounts for accepted-plan allocation precedence",async()=>{const base=await setup(),other:BaselinePlanOrderV1={...base.plan_orders[0],order_fact_ref:"industrial-order:earlier",order_version_ref:"order-version:1",quantity:{value:3,unit_ref:"unit:EACH"},due_at:"2026-08-19T10:00:00.000Z"};const x=await setup({orders:[base.plan_orders[0],other],availability:[availability({quantity:{value:5,unit_ref:"unit:EACH"},available_at:asOf}),availability({quantity:{value:3,unit_ref:"unit:EACH"}})]});expect((await position(x)).current_position_at).toBe("2026-08-18T10:00:00.000Z");});
 it("does not let unrelated inventory or production establish the position",async()=>{const x=await setup({availability:[availability({item_ref:"operations-item:OTHER",quantity:{value:99,unit_ref:"unit:EACH"}})]});expect((await position(x)).status).toBe("INSUFFICIENT_EVIDENCE");});
 it("fails closed for unresolved material feasibility and partial evidence",async()=>{for(const x of [await setup({availability:[availability({kind:"PLANNED_PRODUCTION",material_feasibility:"UNRESOLVED"})]}),await setup({boundary:"PARTIAL"})])expect((await position(x)).status).toBe("UNRESOLVED");});
 it("requires qualified, provenanced, causally grounded contributor evidence",async()=>{for(const key of ["evidence_refs","qualification_refs","provenance_refs","causal_lineage_refs"] as const){const x=await setup({availability:[availability({[key]:[]} as any)]});await expect(position(x)).rejects.toThrow();}});
 it("rejects forged objective, order version, item, company, scope, evidence selection, and baseline binding",async()=>{const x=await setup();for(const commitment of [{...x.c,commitment_digest:"forged"},{...x.c,order_version_ref:"order-version:other"},{...x.c,item_ref:"operations-item:OTHER"},{...x.c,objective_binding:{...x.c.objective_binding,company_id:"other"}},{...x.c,objective_binding:{...x.c.objective_binding,evaluation_scope:{...x.c.objective_binding.evaluation_scope,scope:{...x.c.objective_binding.evaluation_scope.scope,scope_type:"PATH"}}}}])await expect(position({...x,c:commitment as any})).rejects.toThrow();await expect(position(x,{evidence_selection_ref:"selection:other"})).rejects.toThrow();await expect(position(x,{baseline_feasibility:{...x.f,feasibility_digest:"forged"}})).rejects.toThrow();});
 it("rejects incompatible units, future effective inventory, and evidence observed after as-of",async()=>{for(const a of [availability({quantity:{value:5,unit_ref:"unit:KG" as any}}),availability({kind:"EFFECTIVE_INVENTORY",available_at:"2026-08-14T00:00:00Z"}),availability({evidence_observed_at:"2026-08-14T00:00:00Z"})]){const c=await commitment(),p:BaselinePlanOrderV1={...ev,order_fact_ref:c.order_fact_ref,order_version_ref:c.order_version_ref,item_ref:c.item_ref,quantity:c.committed_quantity,due_at:c.committed_due_at};await expect(evaluateOperationsBaselineCommitmentFeasibilityV1({version:1,commitment:c,baseline_semantics:"BASELINE_CURRENT_PLAN",evidence_selection_ref:"selection:1",plan_orders:[p],availability:[a],evidence_boundary:"COMPLETE"})).rejects.toThrow();}});
 it("rejects corrective, scenario, and authority-tier contamination",async()=>{const x=await setup();await expect(position(x,{corrective_action_refs:["candidate:1"]})).rejects.toThrow("OPS_POSITION_CORRECTIVE_CANDIDATE_REJECTED");await expect(position(x,{scenario_modification_refs:["scenario:1"]})).rejects.toThrow("OPS_POSITION_SCENARIO_REJECTED");await expect(position(x,{authority_tier_ref:"SENIOR"})).rejects.toThrow("OPS_POSITION_TIER_INPUT_REJECTED");});
 it("preserves qualification, provenance, evidence, lineage, source neutrality, and observational tier independence",async()=>{const x=await position(),json=JSON.stringify(x);expect(x).toMatchObject({qualification_refs:expect.arrayContaining(["qualification:admitted"]),provenance_refs:expect.arrayContaining(["provenance:source"]),causal_lineage_refs:expect.arrayContaining(["lineage:baseline"]),observational_only:true,grants_authority:false,grants_execution:false,grants_remediation:false,epistemic_basis:"DETERMINISTIC"});expect(json).not.toMatch(/ERP|MES|SAP|email|chat|customer.delivery|decision.margin|urgency|cost.of.waiting|pressure|recommendation|approval|delegation/i);});
});
