import {describe,expect,it} from "vitest";
import {bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1} from "../../cockpit/operational.signal.evaluation.scope.v1";
import type {CanonicalOrderFact} from "../canonicalization/authoritative.order.fact";
import {evaluateOperationsBaselineCommitmentFeasibilityV1,type BaselineAvailabilityV1,type BaselinePlanOrderV1} from "../cognition/operations.baseline.commitment.feasibility.v1";
import {deriveOperationsCurrentFulfillmentPositionV1} from "../cognition/operations.current.fulfillment.position.v1";
import {deriveOperationsDecisionMarginV1} from "../cognition/operations.decision.margin.v1";
import {bindOperationsOrderDeliveryCommitmentV1} from "../cognition/operations.protected.objective.v1";
import {deriveOperationsUrgencyV1,verifyOperationsUrgencyV1} from "../cognition/operations.urgency.v1";

const asOf="2026-08-13T10:00:00.000Z",due="2026-08-20T10:00:00.000Z",ev={evidence_observed_at:"2026-08-13T09:00:00.000Z",evidence_refs:["evidence:availability"],qualification_refs:["qualification:admitted"],provenance_refs:["provenance:source"],causal_lineage_refs:["lineage:baseline"]};
function fact():CanonicalOrderFact{return{factId:"industrial-order:order-1",factFamily:"INDUSTRIAL_ORDER",schemaVersion:"1.0.0",owner:{tenantId:"tenant-1",companyId:"company-1",ownerId:"owner-1"},source:{systemId:"system-1",externalObjectId:"order-1",externalObjectVersion:"2"},observedAt:ev.evidence_observed_at,effectiveAt:"2026-08-13T08:00:00.000Z",order:{sku:"SKU1",quantity:{value:5,unit:"EACH"},status:"OPEN",dueAt:due},provenance:{acquisitionReference:"acquisition-order-1",authorizationReference:"authorization-1",acquiredAt:"2026-08-13T09:05:00.000Z",capabilityId:"read_orders",connectorIdentityId:"connector-identity:any",connectorRevision:1,sourceRepresentation:"PRODUCTION_REST_ERP_ORDERS_V1",transformationId:"PRODUCTION_REST_ERP_ORDER_TO_CANONICAL_ORDER",transformationVersion:"1.0.0",canonicalSchemaVersion:"1.0.0",tenantId:"tenant-1",companyId:"company-1",ownerId:"owner-1",sourceSystem:"system-1",externalObjectId:"order-1",externalObjectVersion:"2"}};}
async function state(options:{at?:string;quantity?:number;boundary?:"COMPLETE"|"PARTIAL";consequence?:string}={}){const f=fact(),scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"ENTITY",request_id:"request-1",company_id:"company-1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1",entity:{entity_type:"ORDER",entity_ref:f.factId}}),binding=await bindOperationalSignalsToScopeV1({scope,request_id:"request-1",company_id:"company-1",evidence_as_of:asOf,evaluated_at:"2026-08-13T10:01:00.000Z"}),commitment=await bindOperationsOrderDeliveryCommitmentV1({version:1,order_fact:f,evaluation_scope:binding,selected_objective_kind:"ORDER_DELIVERY_COMMITMENT",objective_selection_ref:"selection:objective",plan_element_ref:`plan:${f.factId}`,protected_subject_ref:`subject:${f.factId}`,qualification_refs:["qualification:order"],causal_lineage_refs:["lineage:order"],plan_lineage_refs:["lineage:plan"]}),order:BaselinePlanOrderV1={...ev,order_fact_ref:commitment.order_fact_ref,order_version_ref:commitment.order_version_ref,item_ref:commitment.item_ref,quantity:commitment.committed_quantity,due_at:commitment.committed_due_at},availability:BaselineAvailabilityV1={...ev,availability_ref:"availability:1",kind:"GOVERNED_FUTURE_SUPPLY",item_ref:commitment.item_ref,quantity:{value:options.quantity??5,unit_ref:"unit:EACH"},available_at:options.at??"2026-08-14T10:00:00.000Z"},evidence_boundary=options.boundary??"COMPLETE",feasibility=await evaluateOperationsBaselineCommitmentFeasibilityV1({version:1,commitment,baseline_semantics:"BASELINE_CURRENT_PLAN",evidence_selection_ref:"selection:1",plan_orders:[order],availability:[availability],evidence_boundary}),position=await deriveOperationsCurrentFulfillmentPositionV1({version:1,commitment,baseline_feasibility:feasibility,baseline_semantics:"BASELINE_CURRENT_PLAN",evidence_selection_ref:"selection:1",plan_orders:[order],availability:[availability],evidence_boundary}),margin=await deriveOperationsDecisionMarginV1({version:1,commitment,current_position:position,governing_condition_ref:"condition:fulfillment-timing",material_compromise_refs:[options.consequence??"consequence:delivery"]});return{commitment,margin};}
async function urgency(options:Parameters<typeof state>[0]={}){const x=await state(options);return{...x,result:await deriveOperationsUrgencyV1({version:1,commitment:x.commitment,decision_margin:x.margin})};}

describe("PRESSURE-OPS-URGENCY-COGNITION-WU1",()=>{
 it("derives deterministic, immutable, verifiable open-window urgency",async()=>{const a=await urgency(),b=await urgency();expect(a.result.urgency_id).toBe(b.result.urgency_id);await expect(verifyOperationsUrgencyV1(a.result)).resolves.toBeUndefined();expect(Object.isFrozen(a.result)&&Object.isFrozen(a.result.pressure_dimension)).toBe(true);});
 it("represents ample margin as threshold-free relative window consumption",async()=>{const{result}=await urgency();expect(result).toMatchObject({status:"WINDOW_OPEN",remaining_window:{value:518400000,unit_ref:"duration:milliseconds"},reference_window:{value:604800000,unit_ref:"duration:milliseconds"},window_consumption_ratio:0.1429});});
 it("represents a narrowing window monotonically without magic urgency bands",async()=>{const ample=(await urgency()).result,narrow=(await urgency({at:"2026-08-19T10:00:00.000Z"})).result;expect(narrow.window_consumption_ratio).toBe(0.8571);expect(narrow.window_consumption_ratio!).toBeGreaterThan(ample.window_consumption_ratio!);expect(narrow).not.toHaveProperty("urgency_band");});
 it("maps exact and crossed boundaries to exhausted without asserting a current pressure dimension",async()=>{for(const at of [due,"2026-08-21T10:00:00.000Z"]){const{result}=await urgency({at});expect(result.status).toBe("WINDOW_EXHAUSTED");expect(result).not.toHaveProperty("window_consumption_ratio");expect(result).not.toHaveProperty("pressure_dimension");}});
 it("preserves unresolved and insufficient evidence without fabricated numeric urgency",async()=>{for(const options of [{boundary:"PARTIAL" as const},{quantity:4}]){const{result}=await urgency(options);expect(["UNRESOLVED","INSUFFICIENT_EVIDENCE"]).toContain(result.status);expect(result).not.toHaveProperty("window_consumption_ratio");expect(result).not.toHaveProperty("pressure_dimension");}});
 it("keeps urgency time-sensitive while retaining distinct material consequence identity",async()=>{const early=(await urgency({consequence:"consequence:A"})).result,late=(await urgency({at:"2026-08-19T10:00:00.000Z",consequence:"consequence:A"})).result,other=(await urgency({consequence:"consequence:B"})).result;expect(early.window_consumption_ratio).not.toBe(late.window_consumption_ratio);expect(other.window_consumption_ratio).toBe(early.window_consumption_ratio);expect(other.material_consequence_refs).toEqual(["consequence:B"]);expect(other.urgency_id).not.toBe(early.urgency_id);});
 it("binds exact governed context and evidence time",async()=>{const{commitment,margin,result}=await urgency();expect(result).toMatchObject({request_id:"request-1",company_id:"company-1",scope_id:margin.scope_id,scope_digest:margin.scope_digest,objective_ref:commitment.commitment_id,objective_digest:commitment.commitment_digest,material_consequence_refs:margin.material_compromise_refs,trajectory_ref:margin.current_position_ref,governing_condition_ref:margin.governing_condition_ref,evidence_as_of:asOf,decision_margin_ref:margin.margin_id,decision_margin_digest:margin.margin_digest});});
 it("projects open-window urgency through the certified canonical pressure dimension",async()=>{const{result}=await urgency();expect(result.pressure_dimension).toMatchObject({dimension:"URGENCY",projection_mode:"CONTINUOUS",value:0.1429,precision_decimal_places:4,decision_opportunity_status:"USEFUL_DECISION_REMAINS"});expect(result.pressure_dimension?.normalization_input_refs).toEqual(expect.arrayContaining([result.decision_margin_ref,result.objective_ref,result.trajectory_ref]));});
 it("preserves evidence qualification, provenance, and causal lineage",async()=>{const{result}=await urgency();expect(result.evidence_refs).toContain("evidence:availability");expect(result.qualification_refs).toContain("qualification:admitted");expect(result.provenance_refs).toContain("provenance:source");expect(result.causal_lineage_refs).toEqual(expect.arrayContaining([result.decision_margin_ref,result.objective_ref,result.trajectory_ref]));});
 it("rejects forged margin and objective integrity",async()=>{const x=await state();await expect(deriveOperationsUrgencyV1({version:1,commitment:x.commitment,decision_margin:{...x.margin,margin_digest:"forged"}} as any)).rejects.toThrow("OPS_URGENCY_MARGIN_INTEGRITY_INVALID");await expect(deriveOperationsUrgencyV1({version:1,commitment:{...x.commitment,commitment_digest:"forged"},decision_margin:x.margin} as any)).rejects.toThrow("OPS_URGENCY_OBJECTIVE_INTEGRITY_INVALID");});
 it.each(["authority_tier","subscription_tier","commercial_plan","credit_balance","provider","model","approval","delegation","recommendation","scenario","simulation","optimizer_candidate","llm_classification","learned_urgency","impact","cost_of_waiting"])("rejects independent %s contamination",async key=>{const x=await state();await expect(deriveOperationsUrgencyV1({version:1,commitment:x.commitment,decision_margin:x.margin,[key]:"forbidden"} as any)).rejects.toThrow("OPS_URGENCY_UNSAFE_INPUT");});
 it.each(["VISION","GRADUATE","JUNIOR","SENIOR","PRINCIPAL","CHARTER"])("is identical when observed from the independent %s commercial tier",async()=>{const a=(await urgency()).result,b=(await urgency()).result;expect(a.urgency_id).toBe(b.urgency_id);expect(a).not.toHaveProperty("authority_tier");expect(a).not.toHaveProperty("subscription_tier");});
 it("remains observational, source-neutral, tier-independent, and separate from Impact and Cost of Waiting",async()=>{const{result}=await urgency(),keys:string[]=[];const visit=(value:unknown)=>{if(Array.isArray(value))value.forEach(visit);else if(value&&typeof value==="object")for(const[key,child]of Object.entries(value)){keys.push(key);visit(child);}};visit(result);expect(result).toMatchObject({observational_only:true,recommended:false,executable:false,grants_authority:false,grants_execution:false,grants_remediation:false,company_global_claim:false});expect(keys).not.toEqual(expect.arrayContaining(["subscription_tier","commercial_plan","credit_balance","provider","model","approval","delegation","recommendation","scenario","simulation","optimizer_candidate","llm_classification","learned_urgency","impact","impact_score","cost_of_waiting"]));});
 it("detects mutation or forged output",async()=>{const{result}=await urgency();await expect(verifyOperationsUrgencyV1({...result,status:"WINDOW_EXHAUSTED"} as any)).rejects.toThrow("OPS_URGENCY_INTEGRITY_INVALID");});
});
