import {describe,expect,it} from "vitest";
import {bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1} from "../../cockpit/operational.signal.evaluation.scope.v1";
import {buildOperationalAvailabilityReadModelV1} from "../../cockpit/operational.availability.read-model.v1";
import {buildOperationalCockpitSnapshotV1} from "../../cockpit/operational.cockpit.snapshot.v1";
import {createGovernedSourceEventCoverageCapabilityV1} from "../../cognition/governed.source.event.coverage.capability.v1";
import type {CanonicalOrderFact} from "../canonicalization/authoritative.order.fact";
import {evaluateOperationsBaselineCommitmentFeasibilityV1,type BaselineAvailabilityV1,type BaselinePlanOrderV1} from "../cognition/operations.baseline.commitment.feasibility.v1";
import {deriveOperationsCurrentFulfillmentPositionV1} from "../cognition/operations.current.fulfillment.position.v1";
import {evaluateOperationsPlannedProductionMaterialFeasibilityV1} from "../cognition/operations.planned.production.material.feasibility.v1";
import {OPERATIONS_PLANNED_PRODUCTION_EVENT_CLASS,OPERATIONS_PLANNED_PRODUCTION_OPTIONAL_FIELDS,OPERATIONS_PLANNED_PRODUCTION_REQUIRED_FIELDS} from "../cognition/operations.planned.production.snapshot.coverage.v1";
import {bindOperationsOrderDeliveryCommitmentV1} from "../cognition/operations.protected.objective.v1";
import {preserveGovernedOperationsFactV1} from "../preservation/governed.operational.fact.preservation.v1";

const asOf="2026-08-13T10:00:00.000Z",outputAt="2026-08-18T10:00:00.000Z",due="2026-08-20T10:00:00.000Z",ev={evidence_observed_at:"2026-08-13T09:00:00.000Z",evidence_refs:["evidence:material"],qualification_refs:["qualification:material"],provenance_refs:["provenance:material"],causal_lineage_refs:["lineage:material"]};
const acquisition={tenantId:"1",companyId:"company-1",sourceSystem:"ERP-1",connectorIdentityId:"connector-1",connectorRevision:1,acquisitionReference:"acquisition-1",authorizationReference:"authorization-1",acquiredAt:asOf,capabilityId:"read",sourceRepresentation:"PROFILE_V1"};
async function productionScope(){const s=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"REQUEST_DATASET",request_id:"request-1",company_id:"company-1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1"});return bindOperationalSignalsToScopeV1({scope:s,request_id:"request-1",company_id:"company-1",evidence_as_of:asOf,evaluated_at:"2026-08-13T10:01:00.000Z"})}
async function coverage(){return createGovernedSourceEventCoverageCapabilityV1({version:1,capability_policy_ref:"policy:governed-source-event-coverage-v1",capability_policy_version:"1",tenant_id:"tenant-1",source_identity_ref:"source:production",source_profile_ref:"source-profile:generic-erp",source_profile_version:"1",source_boundary_ref:"source-boundary:company-1",evaluation_scope:await productionScope(),event_class_capabilities:[{domain_ref:"domain:operations",event_class_ref:OPERATIONS_PLANNED_PRODUCTION_EVENT_CLASS,required_semantic_field_refs:OPERATIONS_PLANNED_PRODUCTION_REQUIRED_FIELDS,guaranteed_semantic_field_refs:OPERATIONS_PLANNED_PRODUCTION_REQUIRED_FIELDS,optional_semantic_field_refs:OPERATIONS_PLANNED_PRODUCTION_OPTIONAL_FIELDS}],coverage_start:"2026-08-01T00:00:00.000Z",coverage_end:asOf,coverage_status:"COMPLETE",profile_capability_evidence_refs:["evidence:profile"],snapshot_completeness_evidence_refs:["evidence:complete"],qualification_refs:["qualification:coverage"],provenance_refs:["provenance:coverage"],causal_lineage_refs:["lineage:coverage"]})}
async function prod(id="P1",item="FG1",quantity=5,at=outputAt){return preserveGovernedOperationsFactV1("PRODUCTION_ORDERS",{production_order_id:id,article:item,output_article:item,quantity,unit:"EA",scheduled_at:"2026-08-16T10:00:00.000Z",planned_output_available_at:at},acquisition)}
async function bom(parent="FG1",component="RM1",ratio=2){return preserveGovernedOperationsFactV1("MASTER_BOM",{parent,component,ratio,unit:"EA",revision:"R1",valid_from:"2026-08-01T00:00:00.000Z"},acquisition)}
function supply(kind:"EFFECTIVE_INVENTORY"|"GOVERNED_FUTURE_SUPPLY",item="RM1",quantity=10,at=asOf):BaselineAvailabilityV1{return{...ev,availability_ref:`availability:${kind}:${item}:${quantity}`,kind,item_ref:`operations-item:${item}`,quantity:{value:quantity,unit_ref:"unit:EACH"},available_at:at}}
async function evaluate(overrides:Record<string,unknown>={}){const evaluation_scope=await productionScope(),production_facts=[await prod()],bom_facts=[await bom()],material_availability=[supply("EFFECTIVE_INVENTORY")];return evaluateOperationsPlannedProductionMaterialFeasibilityV1({version:1,tenant_id:"tenant-1",source_namespace:"ERP-1",evaluation_scope,coverage:await coverage(),production_facts,bom_facts,material_availability,material_evidence_boundary:"COMPLETE",qualification_refs:["qualification:calculation"],provenance_refs:["provenance:calculation"],causal_lineage_refs:["lineage:calculation"],...overrides}as any)}
function orderFact():CanonicalOrderFact{return{factId:"industrial-order:order-1",factFamily:"INDUSTRIAL_ORDER",schemaVersion:"1.0.0",owner:{tenantId:"tenant-1",companyId:"company-1",ownerId:"owner-1"},source:{systemId:"system-1",externalObjectId:"O1",externalObjectVersion:"1"},observedAt:ev.evidence_observed_at,effectiveAt:"2026-08-13T08:00:00.000Z",order:{sku:"FG1",quantity:{value:5,unit:"EACH"},status:"OPEN",dueAt:due},provenance:{acquisitionReference:"acquisition-order",authorizationReference:"authorization-order",acquiredAt:asOf,capabilityId:"read_orders",connectorIdentityId:"connector",connectorRevision:1,sourceRepresentation:"PRODUCTION_REST_ERP_ORDERS_V1",transformationId:"PRODUCTION_REST_ERP_ORDER_TO_CANONICAL_ORDER",transformationVersion:"1.0.0",canonicalSchemaVersion:"1.0.0",tenantId:"tenant-1",companyId:"company-1",ownerId:"owner-1",sourceSystem:"system-1",externalObjectId:"O1",externalObjectVersion:"1"}}}
async function downstream(availability:BaselineAvailabilityV1[]){const f=orderFact(),s=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"ENTITY",request_id:"request-1",company_id:"company-1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1",entity:{entity_type:"ORDER",entity_ref:f.factId}}),scope=await bindOperationalSignalsToScopeV1({scope:s,request_id:"request-1",company_id:"company-1",evidence_as_of:asOf,evaluated_at:"2026-08-13T10:01:00.000Z"}),commitment=await bindOperationsOrderDeliveryCommitmentV1({version:1,order_fact:f,evaluation_scope:scope,selected_objective_kind:"ORDER_DELIVERY_COMMITMENT",objective_selection_ref:"selection:objective",plan_element_ref:"plan:O1",protected_subject_ref:"subject:O1",qualification_refs:["qualification:order"],causal_lineage_refs:["lineage:order"],plan_lineage_refs:["lineage:plan"]}),plan:BaselinePlanOrderV1={...ev,order_fact_ref:commitment.order_fact_ref,order_version_ref:commitment.order_version_ref,item_ref:commitment.item_ref,quantity:commitment.committed_quantity,due_at:commitment.committed_due_at},feasibility=await evaluateOperationsBaselineCommitmentFeasibilityV1({version:1,commitment,baseline_semantics:"BASELINE_CURRENT_PLAN",evidence_selection_ref:"selection:1",plan_orders:[plan],availability,evidence_boundary:"COMPLETE"}),position=await deriveOperationsCurrentFulfillmentPositionV1({version:1,commitment,baseline_feasibility:feasibility,baseline_semantics:"BASELINE_CURRENT_PLAN",evidence_selection_ref:"selection:1",plan_orders:[plan],availability,evidence_boundary:"COMPLETE"});return{feasibility,position}}

describe("PLANNED-PRODUCTION-TO-COCKPIT-VERTICAL-SLICE-WU1",()=>{
 it("uses qualified current snapshot facts directly without historical version recertification",async()=>{const x=await evaluate();expect(x.results[0]).toMatchObject({status:"FEASIBLE",planned_quantity:{value:5},feasible_quantity:{value:5},planned_output_available_at:outputAt,source_snapshot_ref:"snapshot:1"});expect(x.results[0]).not.toHaveProperty("production_version")});
 it("reuses deterministic BOM propagation with effective inventory",async()=>{const a=await evaluate(),b=await evaluate();expect(a).toEqual(b);expect(a.availability[0]).toMatchObject({kind:"PLANNED_PRODUCTION",item_ref:"operations-item:FG1",quantity:{value:5,unit_ref:"unit:EACH"},available_at:outputAt,material_feasibility:"ESTABLISHED"})});
 it("uses governed future supply only before the output boundary",async()=>{expect((await evaluate({material_availability:[supply("GOVERNED_FUTURE_SUPPLY","RM1",10,"2026-08-17T10:00:00.000Z")]})).results[0].status).toBe("FEASIBLE");expect((await evaluate({material_availability:[supply("GOVERNED_FUTURE_SUPPLY","RM1",10,"2026-08-19T10:00:00.000Z")]})).results[0].status).toBe("ZERO_FEASIBLE")});
 it("projects partial quantity and never fabricates zero availability",async()=>{const partial=await evaluate({material_availability:[supply("EFFECTIVE_INVENTORY","RM1",6)]}),zero=await evaluate({material_availability:[supply("EFFECTIVE_INVENTORY","OTHER",10)]});expect(partial.results[0]).toMatchObject({status:"PARTIALLY_FEASIBLE",feasible_quantity:{value:3}});expect(partial.availability[0].quantity.value).toBe(3);expect(zero.results[0].status).toBe("ZERO_FEASIBLE");expect(zero.availability).toEqual([])});
 it("preserves unresolved peers without killing usable production",async()=>{const x=await evaluate({production_facts:[await prod("P1"),await prod("P2","OTHER",2)],bom_facts:[await bom()]});expect(x.results.map(r=>r.status).sort()).toEqual(["FEASIBLE","UNRESOLVED"]);expect(x.availability).toHaveLength(1)});
 it("keeps partial material evidence unresolved",async()=>{const x=await evaluate({material_evidence_boundary:"PARTIAL"});expect(x.results[0].status).toBe("UNRESOLVED");expect(x.availability).toEqual([])});
 it("feeds existing baseline feasibility and current fulfillment",async()=>{const x=await evaluate(),down=await downstream([...x.availability]);expect(down.feasibility.result).toBe("FULFILLABLE_BY_COMMITMENT");expect(down.position).toMatchObject({status:"RESOLVED",current_position_at:outputAt})});
 it("composes inventory future supply and planned production in the existing cockpit snapshot",async()=>{const x=await evaluate(),scope=await productionScope(),all=[supply("EFFECTIVE_INVENTORY","FG1",2),supply("GOVERNED_FUTURE_SUPPLY","FG1",3,"2026-08-17T10:00:00.000Z"),...x.availability],read=await buildOperationalAvailabilityReadModelV1({version:1,evaluation_scope:scope,availability:all,planned_production_results:x.results}),snapshot=await buildOperationalCockpitSnapshotV1({request_id:"request-1",company_id:"company-1",domain:"operations",evaluation_scope:scope,data_awareness:"STRUCTURAL",plan:{level:"COHERENT",source:"MASTER",confidence:1,score:1,quality:"HIGH",quality_score:1},reality:{state:"STABLE",confidence:1,reasons:[]},decision_pressure:{level:"LOW",pressure_type:"NONE"},operational_availability:read});expect(snapshot.signals.operational_availability?.breakdown.map(r=>[r.kind,r.quantity])).toEqual([["EFFECTIVE_INVENTORY",2],["GOVERNED_FUTURE_SUPPLY",3],["PLANNED_PRODUCTION",5]]);expect(snapshot.signals.operational_availability?.planned_production[0]).toMatchObject({planned_quantity:5,feasible_quantity:5,available_at:outputAt,feasibility:"FEASIBLE"});expect(snapshot.lineage_refs).toContain(read.read_model_id)});
 it("rejects forged cockpit availability read models",async()=>{const x=await evaluate(),scope=await productionScope(),read=await buildOperationalAvailabilityReadModelV1({version:1,evaluation_scope:scope,availability:x.availability,planned_production_results:x.results});await expect(buildOperationalCockpitSnapshotV1({request_id:"request-1",company_id:"company-1",domain:"operations",evaluation_scope:scope,data_awareness:"STRUCTURAL",plan:{level:"COHERENT",source:"MASTER",confidence:1,score:1,quality:"HIGH",quality_score:1},reality:{state:"STABLE",confidence:1,reasons:[]},decision_pressure:{level:"LOW",pressure_type:"NONE"},operational_availability:{...read,read_model_digest:"forged"}})).rejects.toThrow("COCKPIT_AVAILABILITY_INTEGRITY_INVALID")});
 it("rejects recursive planned-production supply, incompatible units and cross-company BOM",async()=>{await expect(evaluate({material_availability:[{...supply("EFFECTIVE_INVENTORY"),kind:"PLANNED_PRODUCTION",material_feasibility:"ESTABLISHED"}]})).rejects.toThrow("RECURSIVE_SUPPLY_REJECTED");await expect(evaluate({material_availability:[{...supply("EFFECTIVE_INVENTORY"),quantity:{value:10,unit_ref:"unit:KG"}}]})).rejects.toThrow("MATERIAL_UNIT_UNSUPPORTED");await expect(evaluate({bom_facts:[await preserveGovernedOperationsFactV1("MASTER_BOM",{parent:"FG1",component:"RM1",ratio:2,unit:"EA",revision:"R1",valid_from:"2026-08-01T00:00:00.000Z"},{...acquisition,companyId:"company-2"})]})).rejects.toThrow("COMPANY_MISMATCH")});
 it("rejects simulation optimizer chat alternative-plan tier and commercial contamination",async()=>{for(const key of ["scenario","counterfactual","chat_hypothesis","alternative_plan","optimizer_candidate","authority_tier","commercial_plan","credit_balance","quantity_override","timing_override"])await expect(evaluate({[key]:"forbidden"})).rejects.toThrow("OPS_PRODUCTION_FEASIBILITY_UNSAFE_INPUT")});
 it("is source-neutral, observational, tier-independent and retains evidence lineage",async()=>{const x=await evaluate(),r=x.results[0],json=JSON.stringify(r);expect(r).toMatchObject({qualification_refs:expect.arrayContaining(["qualification:coverage","qualification:calculation","qualification:material"]),provenance_refs:expect.arrayContaining(["provenance:coverage","provenance:calculation","provenance:material"]),observational_only:true,counterfactual:false,recommended:false,executable:false,grants_authority:false,grants_execution:false});expect(json).not.toMatch(/VISION|GRADUATE|JUNIOR|SENIOR|PRINCIPAL|CHARTER|SAP|MES|commercial.plan|credit.balance|recommendation/i)});
});
