import { describe, expect, it, vi } from "vitest";
import { PRODUCTION_ERP_PROFILES, type ProductionErpProfileName } from "../../connectors/generic.erp.adapter";
import { SAP_PROFILE, SAP_PROFILE_VERSION, SapConnectorError, createSapConnector, initializeSapConnector, validateSapConnectorConfig, type SapConnectorConfig } from "../../connectors/erp.sap.adapter";
import type { ConnectorExecutionAccess } from "../connector.access";

const NOW = Date.parse("2026-08-01T10:00:00.000Z");
const paths = { ORDERS: "/odata/orders", INVENTORY: "/odata/inventory", MOVEMENTS: "/odata/movements", PRODUCTION_ORDERS: "/odata/production-orders", MATERIAL_MOVEMENTS: "/odata/material-movements", MASTER_BOM: "/odata/bom" } as const;
const config: SapConnectorConfig = { profile: SAP_PROFILE, profileVersion: SAP_PROFILE_VERSION, baseUrl: "https://sap.example", healthPath: "/ready", tenantId: "tenant-1", companyId: "C1", ownerId: "owner-1", sourceSystem: "SAP-FACADE-1", sourceRegion: "EU", credentialReference: "secret://sap/facade", authenticationProfile: "BEARER_TOKEN_V1", requestTimeoutMs: 100, maxResponseBytes: 100_000, maxPages: 3, maxRecords: 10, lanes: Object.fromEntries(Object.entries(paths).map(([name, path]) => [name, { path, representationProfile: PRODUCTION_ERP_PROFILES[name as ProductionErpProfileName] }])) };
const rows: Record<ProductionErpProfileName, Record<string, unknown>> = {
  ORDERS: { SalesOrder: "O1", SalesOrderVersion: "1", CompanyCode: "C1", OwnerId: "owner-1", SourceSystem: "SAP-FACADE-1", Material: "SKU1", RequestedQuantity: 2, RequestedQuantityUnit: "EA", OverallStatus: "OPEN", LastChangeDateTime: "2026-08-01T09:00:00.000Z", CreationDateTime: "2026-08-01T08:00:00.000Z", RequestedDeliveryDateTime: "2026-08-02T08:00:00.000Z" },
  INVENTORY: { InventoryItem: "I1", CompanyCode: "C1", SourceSystem: "SAP-FACADE-1", StorageLocation: "W1", Material: "SKU1", Quantity: 7, Unit: "EA", LastChangeDateTime: "2026-08-01T09:00:00.000Z" },
  MOVEMENTS: { MaterialDocumentItem: "M1", CompanyCode: "C1", SourceSystem: "SAP-FACADE-1", Material: "SKU1", Quantity: 3, MovementType: "RECEIPT", Unit: "EA", PostingDateTime: "2026-08-01T09:00:00.000Z" },
  PRODUCTION_ORDERS: { ManufacturingOrder: "P1", CompanyCode: "C1", SourceSystem: "SAP-FACADE-1", Material: "FG1", OutputMaterial: "FG1", TotalQuantity: 5, Unit: "EA", ScheduledStartDateTime: "2026-08-01T09:00:00.000Z" },
  MATERIAL_MOVEMENTS: { MaterialDocumentItem: "MM1", ManufacturingOrder: "P1", CompanyCode: "C1", SourceSystem: "SAP-FACADE-1", Material: "RM1", Quantity: 4, MovementType: "CONSUMPTION", Unit: "EA", PostingDateTime: "2026-08-01T09:00:00.000Z" },
  MASTER_BOM: { BillOfMaterial: "FG1", BillOfMaterialItem: "RM1", CompanyCode: "C1", SourceSystem: "SAP-FACADE-1", ComponentQuantity: 2, Unit: "EA", RevisionLevel: "R1", ValidityStartDateTime: "2026-08-01T09:00:00.000Z" },
};
const capability: Record<ProductionErpProfileName, string> = { ORDERS: "read_orders", INVENTORY: "read_inventory", MOVEMENTS: "read_movements", PRODUCTION_ORDERS: "read_production_plan", MATERIAL_MOVEMENTS: "read_movements", MASTER_BOM: "read_master_bom" };
function access(change: any = {}): ConnectorExecutionAccess { return { workload: { workloadId: "worker", tenantId: "tenant-1", authenticationId: "auth-1" }, credential: { credentialReference: "secret://sap/facade", secret: "top-secret" }, dataPolicyAdmission: { decision: "ADMITTED", connectorIdentityId: "connector-identity:erp-sap-odata-v4", connectorRevision: 1, credentialReference: "secret://sap/facade", authorizationReference: "auth-1", evaluatedAt: new Date(NOW).toISOString(), context: { contextId: "access-1", tenantId: "tenant-1", targetTenantId: "tenant-1", sourceSystem: "SAP-FACADE-1", sourceRegion: "EU", targetRegion: "EU", runtimeLocality: "TENANT_LOCAL", encryptionDomain: "EXECUTION_MEMORY", transportEvidence: { contextId: "access-1", connectorIdentityId: "connector-identity:erp-sap-odata-v4", scheme: "HTTPS", secure: true }, encryptionEvidence: { contextId: "access-1", connectorIdentityId: "connector-identity:erp-sap-odata-v4", domain: "EXECUTION_MEMORY", encryptedInTransit: true, encryptedAtRest: true }, ...change.context }, ...change } } as ConnectorExecutionAccess; }
const response = (value: unknown[], next?: string) => new Response(JSON.stringify({ "@odata.context": "$metadata", value, ...(next ? { "@odata.nextLink": next } : {}) }), { headers: { "content-type": "application/json" } });
async function run(name: ProductionErpProfileName, fetcher: typeof fetch = async () => response([rows[name]])) { return createSapConnector(config, { fetch: fetcher, now: () => NOW }).execute(capability[name], { providerProfile: PRODUCTION_ERP_PROFILES[name] }, access()); }
async function denied(promise: Promise<unknown>, code: string) { try { await promise; throw new Error("expected denial"); } catch (error) { expect(error).toBeInstanceOf(SapConnectorError); expect((error as SapConnectorError).code).toBe(code); expect(JSON.stringify(error)).not.toContain("top-secret"); } }

describe("WU12D — SAP read-only provider profile", () => {
  it("does not register without configuration", () => expect(initializeSapConnector({})).toBe(false));
  it("keeps identical initialization idempotent and rejects drift", () => { const env = { INDUSTRIAL_SAP_PROFILE: SAP_PROFILE, INDUSTRIAL_SAP_PROFILE_VERSION: "1", INDUSTRIAL_SAP_BASE_URL: "https://sap-init.example", INDUSTRIAL_SAP_HEALTH_PATH: "/ready", INDUSTRIAL_SAP_TENANT_ID: "tenant-init", INDUSTRIAL_SAP_COMPANY_ID: "company-init", INDUSTRIAL_SAP_OWNER_ID: "owner-init", INDUSTRIAL_SAP_SOURCE_SYSTEM: "SAP-INIT", INDUSTRIAL_SAP_SOURCE_REGION: "EU", INDUSTRIAL_SAP_CREDENTIAL_REFERENCE: "secret://sap/init", INDUSTRIAL_SAP_AUTHENTICATION_PROFILE: "BEARER_TOKEN_V1", INDUSTRIAL_SAP_REQUEST_TIMEOUT_MS: "100", INDUSTRIAL_SAP_MAX_PAGES: "2", INDUSTRIAL_SAP_MAX_RECORDS: "10", INDUSTRIAL_SAP_ORDERS_PATH: "/orders" }; expect(initializeSapConnector(env)).toBe(true); expect(initializeSapConnector(env)).toBe(true); expect(() => initializeSapConnector({ ...env, INDUSTRIAL_SAP_ORDERS_PATH: "/changed" })).toThrow("Invalid SAP connector configuration"); });
  it("accepts and deeply freezes complete configuration", () => { const value = validateSapConnectorConfig(config); expect(Object.isFrozen(value)).toBe(true); expect(Object.isFrozen(value.lanes)).toBe(true); });
  it("declares only configured capabilities", () => expect(createSapConnector({ ...config, lanes: { INVENTORY: config.lanes.INVENTORY } }).capabilities.map(c => c.id)).toEqual(["read_inventory"]));
  it.each([["invalid base", { baseUrl: "http://sap.example" }, "SAP_CONFIGURATION_INVALID"], ["invalid path", { healthPath: "../ready" }, "SAP_ENDPOINT_INVALID"], ["missing version", { profileVersion: undefined }, "SAP_PROFILE_VERSION_UNSUPPORTED"], ["unsupported profile", { profile: "SAP_ALL" }, "SAP_PROFILE_UNSUPPORTED"], ["bad auth", { authenticationProfile: "BASIC" }, "SAP_AUTHENTICATION_PROFILE_INVALID"]] as const)("rejects %s", (_label, change, code) => { try { validateSapConnectorConfig({ ...config, ...change } as any); throw new Error("expected"); } catch (error) { expect((error as SapConnectorError).code).toBe(code); } });
  it.each(Object.keys(rows) as ProductionErpProfileName[])("validates and projects %s through the generic profile", async name => { const output = await run(name) as any; expect(output.providerProfile).toBe(PRODUCTION_ERP_PROFILES[name]); expect(output.cognitionRows).toHaveLength(1); expect(output.sap).toEqual({ profile: SAP_PROFILE, profileVersion: "1" }); expect(output.acquisition.connectorIdentityId).toBe("connector-identity:erp-sap-odata-v4"); expect(Object.isFrozen(output)).toBe(true); expect(JSON.stringify(output)).not.toMatch(/AuthoritativeExternalData|uploadId/); });
  const parity = [["ORDERS", "orders", { orderId: "O1", sku: "SKU1", qty: 2 }], ["INVENTORY", "inventory", { sku: "SKU1", qty: 7 }], ["MOVEMENTS", "movements", { sku: "SKU1", qty: 3, type: "RECEIPT" }], ["PRODUCTION_ORDERS", "movord", { order: "P1", article: "FG1", quantity: 5 }], ["MATERIAL_MOVEMENTS", "movmag", { order: "P1", article: "RM1", quantity: 4, type: "CONSUMPTION" }], ["MASTER_BOM", "masterBom", { parent: "FG1", component: "RM1", ratio: 2 }]] as const;
  it.each(parity)("produces provider-neutral %s parity", async (name, lane, expected) => { const output = await run(name) as any; expect(output.cognitionLane).toBe(lane); expect(output.cognitionRows).toEqual([expected]); });
  it.each([["missing field", (r: Record<string, unknown>) => { delete r.Material; }, "SAP_REQUIRED_FIELD_MISSING"], ["unknown field", (r: Record<string, unknown>) => { r.Unknown = 1; }, "SAP_UNKNOWN_FIELD"], ["numeric string", (r: Record<string, unknown>) => { r.RequestedQuantity = "2"; }, "SAP_NUMERIC_FORMAT_INVALID"], ["duplicate", (_r: Record<string, unknown>) => {}, "SAP_DUPLICATE_IDENTITY"]] as const)("rejects %s", async (_label, mutate, code) => { const row = structuredClone(rows.ORDERS); mutate(row); await denied(run("ORDERS", async () => response(code === "SAP_DUPLICATE_IDENTITY" ? [row, row] : [row])), code); });
  it.each([["MOVEMENTS", "MovementType", "UNKNOWN", "SAP_CAPABILITY_PAYLOAD_MISMATCH"], ["MOVEMENTS", "PostingDateTime", "01/08/2026", "SAP_DATE_FORMAT_INVALID"], ["MOVEMENTS", "Unit", "BOX", "SAP_VALUE_TYPE_INVALID"], ["PRODUCTION_ORDERS", "OutputMaterial", "OTHER", "SAP_CAPABILITY_PAYLOAD_MISMATCH"], ["MATERIAL_MOVEMENTS", "Quantity", -1, "SAP_VALUE_TYPE_INVALID"], ["MASTER_BOM", "ComponentQuantity", 0, "SAP_VALUE_TYPE_INVALID"]] as const)("rejects invalid %s %s", async (name, field, value, code) => { const row = { ...rows[name], [field]: value }; await denied(run(name, async () => response([row])), code); });
  it("supports bounded same-origin pagination", async () => { const fetcher = vi.fn<typeof fetch>().mockResolvedValueOnce(response([rows.ORDERS], "/odata/orders?page=2")).mockResolvedValueOnce(response([{ ...rows.ORDERS, SalesOrder: "O2" }])); const output = await run("ORDERS", fetcher) as any; expect(output.orders).toHaveLength(2); expect(fetcher).toHaveBeenCalledTimes(2); });
  it.each([["cross origin", "https://evil.example/orders"], ["loop", "/odata/orders"]] as const)("rejects %s pagination", async (_label, next) => denied(run("ORDERS", async () => response([rows.ORDERS], next)), "SAP_PAGINATION_INVALID"));
  it("rejects page and record limits", async () => { const limited = { ...config, maxRecords: 1 }; await denied(createSapConnector(limited, { fetch: async () => response([rows.ORDERS, { ...rows.ORDERS, SalesOrder: "O2" }]), now: () => NOW }).execute("read_orders", {}, access()), "SAP_PAGINATION_LIMIT_EXCEEDED"); });
  it.each(["POST", "PUT", "PATCH", "DELETE"])("prohibits %s", async method => denied(createSapConnector(config).execute("read_orders", { method }, access()), "SAP_WRITE_OPERATION_PROHIBITED"));
  it("does not expose notify_supplier", () => expect(createSapConnector(config).capabilities.map(c => c.id)).not.toContain("notify_supplier"));
  it("uses bearer authentication without exposing it", async () => { const fetcher = vi.fn<typeof fetch>(async (_url, init) => { expect(new Headers(init?.headers).get("Authorization")).toBe("Bearer top-secret"); return response([rows.ORDERS]); }); const output = await run("ORDERS", fetcher); expect(JSON.stringify(output)).not.toContain("top-secret"); });
  it("performs sanitized readiness without business acquisition", async () => { const fetcher = vi.fn<typeof fetch>(async () => new Response(null, { status: 204 })); const health = await createSapConnector(config, { fetch: fetcher, now: () => NOW }).health(); expect(health.ok).toBe(true); expect(fetcher.mock.calls[0]![1]?.method).toBe("HEAD"); expect(JSON.stringify(health)).not.toContain("sap.example"); });
  it("bounds and sanitizes readiness timeout", async () => { const connector = createSapConnector({ ...config, requestTimeoutMs: 1 }, { now: () => NOW, fetch: async (_url, init) => new Promise((_resolve, reject) => init?.signal?.addEventListener("abort", () => reject(new Error("provider secret")))) }); await expect(connector.health()).resolves.toMatchObject({ ok: false }); });
  it("sanitizes provider failures", async () => denied(run("ORDERS", async () => { throw new Error("secret body infrastructure-42"); }), "SAP_PROVIDER_UNREACHABLE"));
  it("defensively copies and deeply freezes output", async () => { const row = structuredClone(rows.INVENTORY); const output = await run("INVENTORY", async () => response([row])) as any; row.Material = "changed"; expect(output.inventory[0].sku).toBe("SKU1"); expect(Object.isFrozen(output.inventory[0])).toBe(true); });
});
