import {describe,expect,it} from "vitest";
import {bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1} from "../../cockpit/operational.signal.evaluation.scope.v1";
import {composeCanonicalDecisionPressureV1,type CanonicalPressureDimensionOperandV1} from "../../decision/canonical.decision.pressure.composition.v1";
import {createCanonicalDecisionPressureDimensionV1} from "../../decision/canonical.decision.pressure.dimension.v1";
import {createCanonicalDecisionPressureProducerCertificationV1} from "../../decision/canonical.decision.pressure.normalization.policy.v1";
import {bindAttentionV1,verifyAttentionBindingV1} from "../canonicalAttention";
import {evaluateAttentionSubscriptions} from "../attention.engine";
import type {AttentionLifecycleEvaluation} from "../attention.lifecycle";
import type {AttentionSubscription} from "../attention.types";

const asOf="2026-08-13T10:00:00.000Z",evaluated="2026-08-13T10:01:00.000Z",meta={evidence_refs:["evidence:pressure"],qualification_refs:["qualification:pressure"],provenance_refs:["provenance:pressure"],causal_lineage_refs:["lineage:pressure"]};
async function dim(kind:"IMPACT"|"URGENCY"|"COST_OF_WAITING",value:number|string){const scope=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"ENTITY",request_id:"request-1",company_id:"company-1",domain:"operations",evidence_selection_ref:"selection:1",source_snapshot_ref:"snapshot:1",entity:{entity_type:"ORDER",entity_ref:"order:1"}}),evaluation_scope=await bindOperationalSignalsToScopeV1({scope,request_id:"request-1",company_id:"company-1",evidence_as_of:asOf,evaluated_at:evaluated}),continuous=typeof value==="number",cert=await createCanonicalDecisionPressureProducerCertificationV1({version:1,dimension:kind,producer_id:`producer:${kind}`,producer_version:"1",normalization_policy_id:`policy:${kind}`,normalization_policy_version:"1",domain_profile_id:"domain-profile:operations",domain_profile_version:"1",supported_scope_kinds:["ENTITY"],endpoint_semantics:"CANONICAL_PRESSURE_DIMENSION_ENDPOINTS_V1",monotonicity:"NON_DECREASING_CANONICAL_MAGNITUDE",reference_basis_semantics:"governed attention fixture",evidence_requirement_refs:["requirement:evidence"],qualification_requirement_refs:["requirement:qualification"],composition_restriction:"DOMAIN_SCOPED_PROJECTION_NO_GENERIC_CHILD_COMPOSITION",provenance_required:true,causal_lineage_required:true,...(continuous?{projection_mode:"CONTINUOUS"as const,precision_policy:{kind:"DECIMAL_PLACES"as const,decimal_places:4}}:{projection_mode:"ORDINAL"as const,ordinal_vocabulary:["LOW","MODERATE","HIGH","CRITICAL"]as const})});return createCanonicalDecisionPressureDimensionV1({version:1,dimension:kind,request_id:"request-1",company_id:"company-1",evaluation_scope,evidence_as_of:asOf,evaluated_at:evaluated,producer_certification:cert,normalization_input_refs:[`input:${kind}`],...meta,...(continuous?{projection_mode:"CONTINUOUS"as const,value,numerator_ref:`numerator:${kind}`,denominator_ref:`denominator:${kind}`,precision_decimal_places:4,...(kind==="URGENCY"?{decision_opportunity_status:"USEFUL_DECISION_REMAINS"as const}:{})}:{projection_mode:"ORDINAL"as const,ordinal_state:value as "HIGH"})});}
async function pressure(mode:"COMPLETE"|"UNRESOLVED"|"INSUFFICIENT"|"EXHAUSTED"="COMPLETE",urgency=.4){const impact=await dim("IMPACT","HIGH"),u=await dim("URGENCY",urgency),cow=await dim("COST_OF_WAITING",.2),op=(value:Awaited<ReturnType<typeof dim>>):CanonicalPressureDimensionOperandV1=>({dimension:value.dimension,status:"ESTABLISHED",value,...meta}),missing=(dimension:"URGENCY"|"COST_OF_WAITING",status:"UNRESOLVED"|"INSUFFICIENT_EVIDENCE"|"WINDOW_EXHAUSTED"):CanonicalPressureDimensionOperandV1=>({dimension,status,...meta});return composeCanonicalDecisionPressureV1({version:1,impact:op(impact),urgency:mode==="EXHAUSTED"?missing("URGENCY","WINDOW_EXHAUSTED"):op(u),cost_of_waiting:mode==="UNRESOLVED"?missing("COST_OF_WAITING","UNRESOLVED"):mode==="INSUFFICIENT"?missing("COST_OF_WAITING","INSUFFICIENT_EVIDENCE"):op(cow)});}
function subscription(overrides:Partial<AttentionSubscription>={}):AttentionSubscription{return{attention_id:"attention:1",tenant_id:"tenant-1",company_id:"company-1",context_id:"request-1",actor_id:"actor-1",scope:"ORDER",trigger:"DECISION_PRESSURE_HIGH",priority:"HIGH",status:"ACTIVE",noise_policy:"SILENT_UNLESS_TRIGGERED",target_ref:undefined,human_request:"Watch this governed decision situation",created_at:asOf,updated_at:asOf,...overrides};}
function lifecycle(state:AttentionLifecycleEvaluation["lifecycleState"]="ACTIVE"):AttentionLifecycleEvaluation{return{attention_id:"attention:1",status:"ACTIVE",lifecycleState:state,realityPresence:state==="OBSOLETE"?"MISSING":"PRESENT",cancellable:["RESOLVED","OBSOLETE","EXPIRED"].includes(state),humanReviewRequired:state==="STALE",reason:`state:${state}`,summary:[`lifecycle:${state}`]};}
async function binding(mode:Parameters<typeof pressure>[0]="COMPLETE",previous?:Awaited<ReturnType<typeof bindAttentionV1>>,state:AttentionLifecycleEvaluation["lifecycleState"]="ACTIVE",urgency=.4){return bindAttentionV1({version:1,subscription:subscription(),lifecycle:lifecycle(state),pressure:await pressure(mode,urgency),previous});}

describe("WORKING-ATTENTION-CANONICAL-COMPLETION-WU1",()=>{
 it("accepts and verifies canonical Pressure deterministically",async()=>{const a=await binding(),b=await binding();expect(a.binding_id).toBe(b.binding_id);await expect(verifyAttentionBindingV1(a)).resolves.toBeUndefined();expect(Object.isFrozen(a)&&Object.isFrozen(a.component_statuses)).toBe(true);});
 it("rejects forged canonical Pressure",async()=>{const p=await pressure();await expect(bindAttentionV1({version:1,subscription:subscription(),lifecycle:lifecycle(),pressure:{...p,pressure_digest:"forged"}})).rejects.toThrow("PRESSURE_COMPOSITION_INTEGRITY_INVALID");});
 it("keeps the legacy scalar subscription engine compatible",()=>{const s=subscription(),x=evaluateAttentionSubscriptions({subscriptions:[s],context:{tenant_id:"tenant-1",company_id:"company-1",context_id:"request-1",now_iso:evaluated,signals:{decision_pressure:"HIGH"}}});expect(x.triggered).toHaveLength(1);});
 it("opens existing user-directed attention without autonomous expansion",async()=>expect(await binding()).toMatchObject({attention_origin:"USER_SUBSCRIPTION",continuity_action:"OPENED"}));
 it("maintains the same attention identity across evidence updates",async()=>{const first=await binding(),next=await binding("COMPLETE",first,"ACTIVE",.8);expect(next).toMatchObject({attention_id:first.attention_id,continuity_action:"MAINTAINED"});expect(next.pressure_ref).not.toBe(first.pressure_ref);});
 it("does not create duplicate attention identity when Pressure changes",async()=>{const first=await binding(),next=await binding("COMPLETE",first,"ACTIVE",.8);expect(next.attention_id).toBe(first.attention_id);expect(next.binding_id).not.toBe(first.binding_id);});
 it("preserves qualified partial and insufficient Pressure uncertainty",async()=>{for(const mode of ["UNRESOLVED","INSUFFICIENT"]as const){const x=await binding(mode);expect(x.uncertainty_preserved).toBe(true);expect(x.pressure_completeness).toMatch(/QUALIFIED_PARTIAL/);}});
 it("preserves WINDOW_EXHAUSTED without requiring numeric urgency",async()=>{const x=await binding("EXHAUSTED");expect(x.component_statuses).toContainEqual({dimension:"URGENCY",status:"WINDOW_EXHAUSTED"});expect(x.uncertainty_preserved).toBe(true);});
 it.each(["RESOLVED","OBSOLETE","EXPIRED","DISABLED"]as const)("closes through existing %s lifecycle semantics",async state=>expect(await binding("COMPLETE",undefined,state)).toMatchObject({lifecycle_state:state,continuity_action:"CLOSED"}));
 it("keeps explicit user watch distinct from autonomous cognition",async()=>{const x=await binding();expect(x.attention_origin).toBe("USER_SUBSCRIPTION");expect(x).not.toHaveProperty("system_opened");});
 it("does not automatically emit notification",async()=>expect((await binding()).notification_requested).toBe(false));
 it("preserves deterministic replay and memory continuity identity",async()=>{const sequence=async()=>{const a=await binding();return binding("COMPLETE",a,"ACTIVE",.8)};expect((await sequence()).binding_id).toBe((await sequence()).binding_id);});
 it("binds request company scope tenant qualification provenance and lineage",async()=>{const x=await binding();expect(x).toMatchObject({tenant_id:"tenant-1",company_id:"company-1",context_id:"request-1",qualification_refs:["qualification:pressure"],provenance_refs:["provenance:pressure"]});expect(x.causal_lineage_refs).toEqual(expect.arrayContaining([x.pressure_ref,x.attention_id]));});
 it("rejects cross-company context scope lifecycle and continuity substitution",async()=>{const p=await pressure();for(const s of [subscription({company_id:"other"}),subscription({context_id:"other"}),subscription({target_ref:"scope:other"})])await expect(bindAttentionV1({version:1,subscription:s,lifecycle:lifecycle(),pressure:p})).rejects.toThrow();await expect(bindAttentionV1({version:1,subscription:subscription(),lifecycle:{...lifecycle(),attention_id:"other"},pressure:p})).rejects.toThrow();});
 it.each(["attention_priority_score","pressure_level","authority_tier","subscription_tier","commercial_plan","credit_balance","provider","model","approval","delegation","recommendation","execution_payload","llm_output","learned_attention"])("rejects %s contamination",async key=>await expect(bindAttentionV1({version:1,subscription:subscription(),lifecycle:lifecycle(),pressure:await pressure(),[key]:"forbidden"}as any)).rejects.toThrow("ATTENTION_PRESSURE_UNSUPPORTED_INPUT"));
 it.each(["VISION","GRADUATE","JUNIOR","SENIOR","PRINCIPAL","CHARTER"])("is identical at independent tier %s",async()=>expect((await binding()).binding_id).toBe((await binding()).binding_id));
 it("grants no recommendation authority execution or Experience Learning",async()=>expect(await binding()).toMatchObject({recommended:false,executable:false,grants_authority:false,grants_execution:false,learning_record_created:false}));
});
