import{describe,expect,it}from"vitest";import{bindOperationalSignalsToScopeV1,createOperationalSignalEvaluationScopeV1}from"../../cockpit/operational.signal.evaluation.scope.v1";import{composeCanonicalOperationalRealityV1,type CanonicalOperationalRealityEvidenceV1}from"../../reality/canonical.operational.reality.composition.v1";import{bindGovernedObservedOperationalOutcomeV1,createGovernedInterventionContextV1,verifyGovernedInterventionContextV1,verifyGovernedObservedOperationalOutcomeV1}from"../observedOutcome";
const beforeAt="2026-08-17T10:00:00.000Z",actionAt="2026-08-17T11:00:00.000Z",afterAt="2026-08-17T12:00:00.000Z",hex=(x:string)=>x.repeat(64).slice(0,64);
async function scope(at:string,company="company:1",request="request:1"){const s=await createOperationalSignalEvaluationScopeV1({version:1,scope_type:"REQUEST_DATASET",request_id:request,company_id:company,domain:"operations",evidence_selection_ref:"selection:current",source_snapshot_ref:"snapshot:operational"});return bindOperationalSignalsToScopeV1({scope:s,request_id:request,company_id:company,evidence_as_of:at,evaluated_at:at})}
async function reality(at:string,n=1,overrides:Partial<CanonicalOperationalRealityEvidenceV1>={}){const s=await scope(at),e:CanonicalOperationalRealityEvidenceV1={version:1,tenant_id:"tenant:1",company_id:s.scope.company_id,request_id:s.scope.request_id,scope_id:s.scope.scope_id,scope_digest:s.scope.scope_digest,evidence_as_of:at,evidence_ref:`evidence:${n}`,evidence_digest:hex(String(n)),source_identity_ref:"source:1",source_namespace:"source-neutral",semantic_key:"order:1:delivery",claim_digest:hex(String(n+2)),evidence_role:"CURRENT_FACT",canonical_subject_refs:["order:1"],canonical_location_refs:[],qualification_refs:[`qualification:${n}`],provenance_refs:[`provenance:${n}`],causal_lineage_refs:[`lineage:${n}`],...overrides};return composeCanonicalOperationalRealityV1({version:1,tenant_id:"tenant:1",evaluation_scope:s,evidence:[e],coverage:[]})}
async function isolatedReality(at:string,n:number,tenant:string,company:string){const s=await scope(at,company),e:CanonicalOperationalRealityEvidenceV1={version:1,tenant_id:tenant,company_id:company,request_id:s.scope.request_id,scope_id:s.scope.scope_id,scope_digest:s.scope.scope_digest,evidence_as_of:at,evidence_ref:`evidence:${n}`,evidence_digest:hex(String(n)),source_identity_ref:"source:1",source_namespace:"source-neutral",semantic_key:"order:1:delivery",claim_digest:hex(String(n+2)),evidence_role:"CURRENT_FACT",canonical_subject_refs:["order:1"],canonical_location_refs:[],qualification_refs:[`qualification:${n}`],provenance_refs:[`provenance:${n}`],causal_lineage_refs:[`lineage:${n}`]};return composeCanonicalOperationalRealityV1({version:1,tenant_id:tenant,evaluation_scope:s,evidence:[e],coverage:[]})}
async function context(overrides:Record<string,unknown>={}){const b=await reality(beforeAt);return createGovernedInterventionContextV1({version:1,tenant_id:"tenant:1",company_id:b.company_id,request_id:b.request_id,scope_id:b.scope_id,scope_digest:b.scope_digest,context_kind:"EXECUTION",artifact_ref:"execution:1",artifact_digest:hex("a"),occurred_at:actionAt,execution_status:"COMPLETED",qualification_refs:["qualification:intervention"],provenance_refs:["provenance:intervention"],causal_lineage_refs:["lineage:intervention"],...overrides}as never)}
async function outcome(overrides:Record<string,unknown>={}){const before=await reality(beforeAt),after=await reality(afterAt,2),intervention=await context();return bindGovernedObservedOperationalOutcomeV1({version:1,before,intervention,after,...overrides}as never)}
describe("GOVERNED-OBSERVED-OPERATIONAL-OUTCOME-BINDING-WU1",()=>{
 it("binds verified before, intervention and subsequent reality",async()=>{const v=await outcome();expect(v).toMatchObject({outcome_kind:"SUBSEQUENT_GOVERNED_REALITY_OBSERVATION",before_evidence_as_of:beforeAt,intervention_occurred_at:actionAt,after_evidence_as_of:afterAt,observed_outcome:true});await expect(verifyGovernedObservedOperationalOutcomeV1(v)).resolves.toBeUndefined()});
 it("verifies the governed intervention context",async()=>{await expect(verifyGovernedInterventionContextV1(await context())).resolves.toBeUndefined()});
 it("accepts a governed difference comparison without inferring it",async()=>{const v=await outcome({comparison:{status:"DIFFERENCE_ESTABLISHED",ref:"comparison:1",digest:hex("c"),qualification_refs:["qualification:comparison"],provenance_refs:["provenance:comparison"],causal_lineage_refs:["lineage:comparison"]}});expect(v.comparison_status).toBe("DIFFERENCE_ESTABLISHED")});
 it("accepts governed material equivalence",async()=>{const v=await outcome({comparison:{status:"MATERIAL_EQUIVALENCE_ESTABLISHED",ref:"comparison:1",digest:hex("c"),qualification_refs:["qualification:comparison"],provenance_refs:["provenance:comparison"],causal_lineage_refs:["lineage:comparison"]}});expect(v.comparison_status).toBe("MATERIAL_EQUIVALENCE_ESTABLISHED")});
 it("does not fabricate change when no comparison exists",async()=>expect((await outcome()).comparison_status).toBe("NOT_EVALUATED"));
 it.each([[beforeAt,beforeAt],[beforeAt,"2026-08-17T09:00:00.000Z"]])("rejects after time %s not subsequent",async(_b,a)=>{const before=await reality(beforeAt),after=await reality(a,2),intervention=await context({occurred_at:"2026-08-17T09:30:00.000Z"});await expect(bindGovernedObservedOperationalOutcomeV1({version:1,before,intervention,after})).rejects.toThrow("OBSERVED_OUTCOME_TIME_ORDER_INVALID")});
 it("rejects intervention before the before boundary",async()=>{await expect(outcome({intervention:await context({occurred_at:"2026-08-17T09:59:59.000Z"})})).rejects.toThrow("OBSERVED_OUTCOME_TIME_ORDER_INVALID")});
 it("rejects intervention at the after boundary",async()=>{await expect(outcome({intervention:await context({occurred_at:afterAt})})).rejects.toThrow("OBSERVED_OUTCOME_TIME_ORDER_INVALID")});
 it.each(["DECISION","INTERVENTION","NO_ACTION"])("supports governed %s context without execution",async context_kind=>{const v=await outcome({intervention:await context({context_kind,execution_status:"NOT_APPLICABLE",artifact_ref:`${context_kind.toLowerCase()}:1`})});expect(v.intervention_kind).toBe(context_kind)});
 it("keeps successful execution distinct from operational success",async()=>{const v=await outcome();expect(v.execution_status).toBe("COMPLETED");expect(v.operational_success_classified).toBe(false)});
 it("accepts failed execution when later reality is observed",async()=>{const v=await outcome({intervention:await context({execution_status:"FAILED"})});expect(v.execution_status).toBe("FAILED");expect(v.observed_outcome).toBe(true)});
 it("rejects a forged before reality",async()=>{const before={...await reality(beforeAt),composition_digest:hex("0")},after=await reality(afterAt,2),intervention=await context();await expect(bindGovernedObservedOperationalOutcomeV1({version:1,before,intervention,after}as never)).rejects.toThrow("OPERATIONAL_REALITY_INTEGRITY_INVALID")});
 it("rejects a forged after reality",async()=>{const before=await reality(beforeAt),after={...await reality(afterAt,2),composition_digest:hex("0")},intervention=await context();await expect(bindGovernedObservedOperationalOutcomeV1({version:1,before,intervention,after}as never)).rejects.toThrow("OPERATIONAL_REALITY_INTEGRITY_INVALID")});
 it("rejects a forged intervention binding",async()=>{await expect(outcome({intervention:{...await context(),artifact_ref:"execution:forged"}})).rejects.toThrow("OBSERVED_OUTCOME_CONTEXT_INTEGRITY_INVALID")});
 it.each(["scenario","counterfactual","simulation","optimizer","learned_expectation","llm_claim","causal_result"])("rejects %s substitution",async key=>{const before=await reality(beforeAt),intervention=await context(),after={...await reality(afterAt,2),[key]:"artifact:1"};await expect(bindGovernedObservedOperationalOutcomeV1({version:1,before,intervention,after}as never)).rejects.toThrow()});
 it("rejects cross-company after reality",async()=>{const before=await reality(beforeAt),after=await isolatedReality(afterAt,2,"tenant:1","company:2"),intervention=await context();await expect(bindGovernedObservedOperationalOutcomeV1({version:1,before,intervention,after})).rejects.toThrow("OBSERVED_OUTCOME_CONTEXT_MISMATCH")});
 it("rejects cross-tenant after reality",async()=>{const before=await reality(beforeAt),after=await isolatedReality(afterAt,2,"tenant:2","company:1"),intervention=await context();await expect(bindGovernedObservedOperationalOutcomeV1({version:1,before,intervention,after})).rejects.toThrow("OBSERVED_OUTCOME_CONTEXT_MISMATCH")});
 it("rejects cross-request intervention context",async()=>await expect(outcome({intervention:await context({request_id:"request:2"})})).rejects.toThrow("OBSERVED_OUTCOME_CONTEXT_MISMATCH"));
 it("retains qualification, provenance and lineage",async()=>{const v=await outcome();expect(v.qualification_refs).toEqual(expect.arrayContaining(["qualification:1","qualification:2","qualification:intervention"]));expect(v.provenance_refs).toEqual(expect.arrayContaining(["provenance:1","provenance:2","provenance:intervention"]));expect(v.causal_lineage_refs).toEqual(expect.arrayContaining([v.before_reality_ref,v.after_reality_ref,v.intervention_context_ref]))});
 it("binds correction and supersession without mutating reality",async()=>{for(const status of["CORRECTED","SUPERSEDED"]as const){const v=await outcome({correction:{status,ref:"correction:1",digest:hex("d"),qualification_refs:["qualification:correction"],provenance_refs:["provenance:correction"],causal_lineage_refs:["lineage:correction"]}});expect(v.after_observation_status).toBe(status)}});
 it("is deterministic and recursively immutable",async()=>{const a=await outcome(),b=await outcome();expect(a).toEqual(b);expect(Object.isFrozen(a)).toBe(true);expect(Object.isFrozen(a.qualification_refs)).toBe(true)});
 it("changes identity when subsequent reality changes",async()=>{const a=await outcome(),before=await reality(beforeAt),after=await reality(afterAt,3),intervention=await context(),b=await bindGovernedObservedOperationalOutcomeV1({version:1,before,intervention,after});expect(a.outcome_id).not.toBe(b.outcome_id)});
 it("does not assert causal attribution",async()=>expect((await outcome()).causal_attribution_established).toBe(false));
 it.each(["VISION","GRADUATE","JUNIOR","SENIOR","PRINCIPAL","CHARTER"])("is identical canonical truth for %s",async()=>{const v=await outcome();expect(v.tier_independent).toBe(true);expect(v).not.toHaveProperty("tier")});
 it("grants no recommendation, authority, or execution",async()=>expect(await outcome()).toMatchObject({recommended:false,executable:false,grants_authority:false,grants_execution:false}));
 it("is commercial and credit independent",async()=>{const v=await outcome();expect(v).not.toHaveProperty("commercial_plan");expect(v).not.toHaveProperty("credit_balance");expect(v).not.toHaveProperty("economic_capacity")});
 it("rejects forged outcome identity",async()=>{const v=await outcome();await expect(verifyGovernedObservedOperationalOutcomeV1({...v,outcome_digest:hex("0")})).rejects.toThrow("OBSERVED_OUTCOME_INTEGRITY_INVALID")});
});
