import{applyD1Migrations,env}from"cloudflare:test";import{beforeAll,beforeEach,describe,expect,it}from"vitest";
import m7 from"../../../../migrations/0007_oir_track_a_persistence.sql?raw";import m8 from"../../../../migrations/0008_oir_authentication_runtime.sql?raw";import m33 from"../../../../migrations/0033_email_ownership_registration.sql?raw";
import{D1EmailOwnershipRepositoryV1,EmailOwnershipErrorV1,EmailOwnershipRegistrationRuntimeV1,normalizeEmailIdentityV1}from"../email.ownership.v1";import{emailOwnershipRouteV1}from"../email.ownership.route.v1";
const db=env.POLICIES_DB,now="2026-08-27T10:00:00.000Z";let clock=now,sequence=0,delivered:{email:string;code:string;challenge_id:string;expires_at:string}[]=[];
const queries=(sql:string)=>sql.split(/;\s*\r?\n(?=CREATE (?:TABLE|INDEX|UNIQUE INDEX|TRIGGER))/).map(x=>x.trim()).filter(Boolean).map(x=>x.endsWith(";")?x:`${x};`);
function runtime(){return new EmailOwnershipRegistrationRuntimeV1({store:new D1EmailOwnershipRepositoryV1(db),delivery:{async send(input){delivered.push({...input});return true}},challenge_secret:"challenge-secret-with-sufficient-entropy",identity_secret:"identity-secret-with-sufficient-entropy",now:()=>clock,challenge_ttl_ms:600_000,session_ttl_ms:86_400_000,ids:{challenge:()=>`challenge-${++sequence}`,evidence:()=>`evidence-${++sequence}`,nonce:()=>`nonce-${++sequence}`,audit:()=>`audit-${++sequence}`,session:()=>`session-${++sequence}`}})}
async function code(p:Promise<unknown>,expected:string){await expect(p).rejects.toMatchObject({code:expected})}
beforeAll(async()=>applyD1Migrations(db,[{name:"0007",queries:queries(m7)},{name:"0008",queries:queries(m8)},{name:"0033",queries:queries(m33)}]));
beforeEach(async()=>{clock=now;sequence=0;delivered=[]});
describe("email ownership first-principal enrollment v1",()=>{
 it("normalizes only the domain and creates a digest-only challenge",async()=>{expect(normalizeEmailIdentityV1("  User.Name@EXAMPLE.COM ")).toBe("User.Name@example.com");const result=await runtime().challenge("User.Name@EXAMPLE.COM"),row=await db.prepare("SELECT * FROM email_ownership_challenges WHERE challenge_id=?").bind(result.challenge_id).first<Record<string,unknown>>();expect(delivered).toHaveLength(1);expect(row).toMatchObject({normalized_email:"User.Name@example.com",lifecycle_state:"ISSUED",failed_attempts:0});expect(row?.secret_digest).not.toBe(delivered[0]!.code);expect(JSON.stringify(row)).not.toContain(delivered[0]!.code)});
 it("rejects unknown, wrong, expired, malformed and consumed challenges",async()=>{const r=runtime();await code(r.verify({challenge_id:"unknown",code:"00000000"}),"EMAIL_CHALLENGE_UNKNOWN");const one=await r.challenge("one@example.com");await code(r.verify({challenge_id:one.challenge_id,code:"wrong"}),"EMAIL_CHALLENGE_INVALID");const two=await r.challenge("two@example.com");clock="2026-08-27T10:11:00.000Z";await code(r.verify({challenge_id:two.challenge_id,code:delivered[1]!.code}),"EMAIL_CHALLENGE_EXPIRED");await code(r.verify({challenge_id:"",code:""}),"EMAIL_CHALLENGE_MALFORMED");clock=now;await r.verify({challenge_id:one.challenge_id,code:delivered[0]!.code});await code(r.verify({challenge_id:one.challenge_id,code:delivered[0]!.code}),"EMAIL_CHALLENGE_ALREADY_USED")});
 it("creates one account-only principal, binding and reloadable server session",async()=>{const r=runtime(),challenge=await r.challenge("person@example.com"),result=await r.verify({challenge_id:challenge.challenge_id,code:delivered[0]!.code}),session=await db.prepare("SELECT * FROM oir_server_sessions WHERE session_id=?").bind(result.session.session_id).first<Record<string,unknown>>();expect(result.status).toBe("REGISTERED");expect(session).toMatchObject({principal_id:result.session.principal_id,lifecycle_state:"ACTIVE"});for(const table of["oir_principals","oir_external_authentication_bindings"])expect((await db.prepare(`SELECT COUNT(*) count FROM ${table}`).first<{count:number}>())?.count).toBe(1);for(const table of["oir_organization_memberships","oir_tenants","oir_companies"])expect((await db.prepare(`SELECT COUNT(*) count FROM ${table}`).first<{count:number}>())?.count).toBe(0);const audit=await db.prepare("SELECT executing_runtime FROM oir_authentication_audit_events WHERE session_id=?").bind(result.session.session_id).first<{executing_runtime:string}>();expect(audit?.executing_runtime).toBe("operational-identity.email-ownership.v1")});
 it("reuses the principal and converges concurrent first enrollment",async()=>{const r=runtime(),a=await r.challenge("same@example.com"),b=await r.challenge("same@EXAMPLE.COM"),[x,y]=await Promise.all([r.verify({challenge_id:a.challenge_id,code:delivered[0]!.code}),r.verify({challenge_id:b.challenge_id,code:delivered[1]!.code})]);expect(x.session.principal_id).toBe(y.session.principal_id);expect((await db.prepare("SELECT COUNT(*) count FROM oir_principals").first<{count:number}>())?.count).toBe(1);expect((await db.prepare("SELECT COUNT(*) count FROM oir_external_authentication_bindings").first<{count:number}>())?.count).toBe(1);const c=await r.challenge("same@example.com"),z=await r.verify({challenge_id:c.challenge_id,code:delivered[2]!.code});expect(z.session.principal_id).toBe(x.session.principal_id)});
 it("rejects caller identity claims and returns an HttpOnly session cookie",async()=>{const r=runtime();let response=await emailOwnershipRouteV1(new Request("https://planneragent.test/identity/email/challenge",{method:"POST",body:JSON.stringify({email:"route@example.com",principal_id:"attacker"})}),env as any,r);expect(response.status).toBe(400);expect((await db.prepare("SELECT COUNT(*) count FROM oir_principals").first<{count:number}>())?.count).toBe(0);response=await emailOwnershipRouteV1(new Request("https://planneragent.test/identity/email/challenge",{method:"POST",body:JSON.stringify({email:"route@example.com"})}),env as any,r);const challenge=await response.json()as any;response=await emailOwnershipRouteV1(new Request("https://planneragent.test/identity/email/verify",{method:"POST",body:JSON.stringify({challenge_id:challenge.challenge_id,code:delivered[0]!.code})}),env as any,r);expect(response.status).toBe(200);expect(response.headers.get("set-cookie")).toMatch(/^planneragent_session=.*HttpOnly; SameSite=Lax/);expect(await response.json()).toMatchObject({version:1,status:"REGISTERED"})});
});
