import { applyD1Migrations, env } from "cloudflare:test";
import { beforeAll, beforeEach, describe, expect, it } from "vitest";
import m7 from "../../../../migrations/0007_oir_track_a_persistence.sql?raw";
import m8 from "../../../../migrations/0008_oir_authentication_runtime.sql?raw";
import m33 from "../../../../migrations/0033_email_ownership_registration.sql?raw";
import m34 from "../../../../migrations/0034_email_account_identity_label.sql?raw";
import { emailSessionRouteV1 } from "../email.session.route.v1";

const db=env.POLICIES_DB,queries=(sql:string)=>sql.split(/;\s*\r?\n(?=CREATE (?:TABLE|INDEX|UNIQUE INDEX|TRIGGER))/).map(x=>x.trim()).filter(Boolean).map(x=>x.endsWith(";")?x:`${x};`),request=(path:string,method="GET",cookie?:string)=>new Request(`https://planneragent.test${path}`,{method,headers:cookie?{cookie:`planneragent_session=${cookie}`}:{}});
let sequence=0;
async function seed(state="ACTIVE",expires="2099-01-01T00:00:00.000Z",email="User.Name@example.com"){
  const challenge=`session-email-${++sequence}`,reference=`email-challenge:${challenge}`;
  await db.prepare("INSERT INTO oir_principals (principal_id,actor_kind,lifecycle_state,created_at) VALUES ('principal-session','HUMAN','ACTIVE','2026-01-01T00:00:00.000Z')").run();
  await db.prepare("INSERT INTO oir_external_authentication_bindings (external_authentication_identity_id,principal_id,actor_kind,provider,issuer,external_subject,authentication_method,assurance,verified_at,verification_reference,verified_normalized_email) VALUES ('binding-session','principal-session','HUMAN','EMAIL_OWNERSHIP','planneragent:email-ownership','subject','ONE_TIME_EMAIL_CODE','SINGLE_FACTOR','2026-01-01T00:00:00.000Z',?,?)").bind(reference,email).run();
  await db.prepare("INSERT INTO oir_server_sessions (session_id,principal_id,external_authentication_identity_id,issued_at,expires_at,assurance,lifecycle_state,revocation_reference) VALUES ('session-browser','principal-session','binding-session','2026-01-01T00:00:00.000Z',?,'SINGLE_FACTOR',?,?)").bind(expires,state,state==="ACTIVE"?null:"test-fixture-revocation").run();
}
beforeAll(async()=>applyD1Migrations(db,[{name:"0007",queries:queries(m7)},{name:"0008",queries:queries(m8)},{name:"0033",queries:queries(m33)},{name:"0034",queries:queries(m34)}]));
beforeEach(async()=>{for(const table of["oir_server_sessions","oir_external_authentication_bindings","oir_principals"])await db.prepare(`DELETE FROM ${table}`).run()});
describe("browser email session route v1",()=>{
  it("returns anonymous without a cookie and exposes no email",async()=>{expect(await (await emailSessionRouteV1(request("/identity/session"),env)).json()).toEqual({version:1,status:"ANONYMOUS"});expect(await (await emailSessionRouteV1(new Request("https://planneragent.test/identity/session?email=attacker@example.com&principal_id=attacker"),env)).json()).toEqual({version:1,status:"ANONYMOUS"})});
  it("restores durable verified email without a consumed challenge row and ignores browser email",async()=>{await seed();const expected={version:1,status:"REGISTERED",email:"User.Name@example.com",expires_at:"2099-01-01T00:00:00.000Z"};expect(await db.prepare("SELECT COUNT(*) count FROM email_ownership_challenges").first<{count:number}>()).toMatchObject({count:0});expect(await (await emailSessionRouteV1(request("/identity/session?email=attacker@example.com","GET","session-browser"),env)).json()).toEqual(expected);expect(await (await emailSessionRouteV1(request("/identity/session","GET","session-browser"),env)).json()).toEqual(expected)});
  it("fails closed for missing or non-canonical durable identity and mismatched binding",async()=>{await seed();await db.prepare("UPDATE oir_external_authentication_bindings SET verified_normalized_email=NULL WHERE external_authentication_identity_id='binding-session'").run();expect(await (await emailSessionRouteV1(request("/identity/session","GET","session-browser"),env)).json()).toEqual({version:1,status:"ANONYMOUS"});await db.prepare("UPDATE oir_external_authentication_bindings SET verified_normalized_email='user@EXAMPLE.COM' WHERE external_authentication_identity_id='binding-session'").run();expect(await (await emailSessionRouteV1(request("/identity/session","GET","session-browser"),env)).json()).toEqual({version:1,status:"ANONYMOUS"});await db.prepare("INSERT INTO oir_external_authentication_bindings (external_authentication_identity_id,principal_id,actor_kind,provider,issuer,external_subject,authentication_method,assurance,verified_at,verification_reference) VALUES ('binding-other','principal-session','HUMAN','OTHER','other:issuer','other-subject','OTHER','SINGLE_FACTOR','2026-01-01T00:00:00.000Z','other-ref')").run();await db.prepare("UPDATE oir_server_sessions SET external_authentication_identity_id='binding-other' WHERE session_id='session-browser'").run();expect(await (await emailSessionRouteV1(request("/identity/session","GET","session-browser"),env)).json()).toEqual({version:1,status:"ANONYMOUS"})});
  it("fails closed for expired and revoked sessions",async()=>{await seed("ACTIVE","2026-01-02T00:00:00.000Z");expect(await (await emailSessionRouteV1(request("/identity/session","GET","session-browser"),env)).json()).toMatchObject({status:"ANONYMOUS"});expect((await db.prepare("SELECT lifecycle_state FROM oir_server_sessions WHERE session_id='session-browser'").first<{lifecycle_state:string}>())?.lifecycle_state).toBe("EXPIRED");for(const table of["oir_server_sessions","oir_external_authentication_bindings","oir_principals"])await db.prepare(`DELETE FROM ${table}`).run();await seed("REVOKED");expect(await (await emailSessionRouteV1(request("/identity/session","GET","session-browser"),env)).json()).toMatchObject({status:"ANONYMOUS"})});
  it("logs out, removes display identity, and creates no organization state",async()=>{await seed();const response=await emailSessionRouteV1(request("/identity/logout","POST","session-browser"),env);expect(await response.json()).toEqual({version:1,status:"ANONYMOUS"});expect(response.headers.get("set-cookie")).toMatch(/planneragent_session=;.*HttpOnly.*Max-Age=0/);expect((await db.prepare("SELECT lifecycle_state FROM oir_server_sessions WHERE session_id='session-browser'").first<{lifecycle_state:string}>())?.lifecycle_state).toBe("REVOKED");expect(await (await emailSessionRouteV1(request("/identity/session","GET","session-browser"),env)).json()).toEqual({version:1,status:"ANONYMOUS"});for(const table of["oir_organization_memberships","oir_tenants","oir_companies"])expect((await db.prepare(`SELECT COUNT(*) count FROM ${table}`).first<{count:number}>())?.count).toBe(0)});
});
