import type { OperationalSignalScopeBindingV1 } from "../cockpit/operational.signal.evaluation.scope.v1";
import { verifyOperationalSignalEvaluationScopeV1 } from "../cockpit/operational.signal.evaluation.scope.v1";
import type { GovernedSourceEventCoverageCapabilityV1 } from "../cognition/governed.source.event.coverage.capability.v1";
import { verifyGovernedSourceEventCoverageCapabilityV1 } from "../cognition/governed.source.event.coverage.capability.v1";
import type { GovernedRepresentationObservationInputV1 } from "./governed.multi-source.reality.alignment.v1";

export type OperationalRealityEvidenceRoleV1 = "CURRENT_FACT" | "CURRENT_PLAN" | "REALIZED_EVENT" | "GOVERNED_FUTURE_SUPPLY" | "PLANNED_PRODUCTION" | "USER_CONFIRMED_CURRENT";
export type CanonicalStructuredRealityObservationV1=GovernedRepresentationObservationInputV1&Readonly<{request_id:string;company_id:string;scope_id:string;scope_digest:string;evidence_as_of:string}>;
export type CanonicalOperationalRealityEvidenceV1 = Readonly<{ version:1; tenant_id:string; company_id:string; request_id:string; scope_id:string; scope_digest:string; evidence_as_of:string; evidence_ref:string; evidence_digest:string; source_identity_ref:string; source_namespace:string; semantic_key:string; claim_digest:string; evidence_role:OperationalRealityEvidenceRoleV1; canonical_subject_refs:readonly string[]; canonical_location_refs:readonly string[]; qualification_refs:readonly string[]; provenance_refs:readonly string[]; causal_lineage_refs:readonly string[]; structured_observation?:CanonicalStructuredRealityObservationV1;structured_observation_digest?:string; governed_resolution_ref?:string; governed_resolution_selected?:boolean }>;
export type CanonicalStructuredRealityRetrievalV1=Readonly<{version:1;composition_ref:string;semantic_key:string;group_status:"SINGLE_SOURCE"|"COMPLEMENTARY"|"GOVERNED_RESOLVED"|"UNRESOLVED_CONFLICT";audit_observations:readonly CanonicalStructuredRealityObservationV1[];comparison_candidates:readonly CanonicalStructuredRealityObservationV1[];retrieval_status:"RESOLVED"|"COMPLEMENTARY"|"UNRESOLVED_CONFLICT";observational_only:true;grants_authority:false;grants_execution:false}>;
export type CanonicalOperationalRealityCompositionV1 = Readonly<{ version:1; composition_kind:"CANONICAL_OPERATIONAL_REALITY"; tenant_id:string; company_id:string; request_id:string; scope_id:string; scope_digest:string; evidence_selection_ref:string; source_snapshot_ref:string; evidence_as_of:string; evidence_refs:readonly string[]; structured_evidence:readonly CanonicalOperationalRealityEvidenceV1[]; source_identity_refs:readonly string[]; canonical_subject_refs:readonly string[]; canonical_location_refs:readonly string[]; coverage_refs:readonly string[]; qualification_refs:readonly string[]; provenance_refs:readonly string[]; causal_lineage_refs:readonly string[]; semantic_groups:readonly Readonly<{semantic_key:string; evidence_refs:readonly string[]; status:"SINGLE_SOURCE"|"COMPLEMENTARY"|"UNRESOLVED_CONFLICT"|"GOVERNED_RESOLVED"; selected_evidence_ref?:string; governed_resolution_ref?:string}>[]; composition_status:"COMPOSED"|"UNRESOLVED_CONFLICT"; composition_id:string; composition_digest:string; digest_algorithm:"SHA-256"; observational_only:true; current_reality:true; counterfactual:false; tier_independent:true; recommended:false; executable:false; grants_authority:false; grants_execution:false }>;

const forbidden=["tier","authority_tier","commercial_plan","credit_balance","economic_capacity","recommendation","approval","delegation","execution","scenario","counterfactual","optimizer","simulation","learned_expectation","llm_result","knowledge_override"];
const roles=new Set<OperationalRealityEvidenceRoleV1>(["CURRENT_FACT","CURRENT_PLAN","REALIZED_EVENT","GOVERNED_FUTURE_SUPPLY","PLANNED_PRODUCTION","USER_CONFIRMED_CURRENT"]);
function required(v:string|undefined,c:string){const x=v?.trim();if(!x)throw new Error(c);return x}
function refs(v:readonly string[],c:string,empty=false){if(!Array.isArray(v))throw new Error(c);const x=[...new Set(v.map(y=>required(y,c)))].sort();if(!empty&&!x.length)throw new Error(c);return x}
function instant(v:string,c:string){const n=Date.parse(v);if(!Number.isFinite(n)||new Date(n).toISOString()!==v)throw new Error(c);return v}
function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return`{${Object.entries(v as Record<string,unknown>).filter(([,x])=>x!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(",")}}`;return JSON.stringify(v)}
async function sha(v:unknown){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(v)));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}
function freeze<T>(v:T):Readonly<T>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v as Record<string,unknown>).forEach(freeze);Object.freeze(v)}return v}
function semantic(v:CanonicalOperationalRealityCompositionV1){const{composition_id:_id,composition_digest:_digest,digest_algorithm:_algorithm,observational_only:_observational,current_reality:_current,counterfactual:_counterfactual,tier_independent:_tier,recommended:_recommended,executable:_executable,grants_authority:_authority,grants_execution:_execution,...x}=v;return x}

export async function composeCanonicalOperationalRealityV1(input:Readonly<{version:1;tenant_id:string;evaluation_scope:OperationalSignalScopeBindingV1;evidence:readonly CanonicalOperationalRealityEvidenceV1[];coverage:readonly GovernedSourceEventCoverageCapabilityV1[]}>):Promise<CanonicalOperationalRealityCompositionV1>{
 if(input.version!==1)throw new Error("OPERATIONAL_REALITY_VERSION_UNSUPPORTED");for(const k of forbidden)if(k in(input as object))throw new Error("OPERATIONAL_REALITY_UNSAFE_INPUT");
 await verifyOperationalSignalEvaluationScopeV1(input.evaluation_scope.scope,input.evaluation_scope.scope);await Promise.all(input.coverage.map(verifyGovernedSourceEventCoverageCapabilityV1));
 const tenant=required(input.tenant_id,"OPERATIONAL_REALITY_TENANT_REQUIRED"),scope=input.evaluation_scope.scope,asOf=instant(input.evaluation_scope.evidence_as_of,"OPERATIONAL_REALITY_AS_OF_INVALID");if(!input.evidence.length)throw new Error("OPERATIONAL_REALITY_EVIDENCE_REQUIRED");
 const normalized=[] as CanonicalOperationalRealityEvidenceV1[];for(const e of input.evidence){for(const k of forbidden)if(k in(e as object))throw new Error("OPERATIONAL_REALITY_NON_CURRENT_EVIDENCE_REJECTED");if(e.version!==1||!roles.has(e.evidence_role))throw new Error("OPERATIONAL_REALITY_EVIDENCE_ROLE_INVALID");if(e.tenant_id!==tenant||e.company_id!==scope.company_id||e.request_id!==scope.request_id||e.scope_id!==scope.scope_id||e.scope_digest!==scope.scope_digest||e.evidence_as_of!==asOf)throw new Error("OPERATIONAL_REALITY_CONTEXT_MISMATCH");if(!/^[a-f0-9]{64}$/.test(e.evidence_digest)||!/^[a-f0-9]{64}$/.test(e.claim_digest))throw new Error("OPERATIONAL_REALITY_EVIDENCE_DIGEST_INVALID");if(Boolean(e.structured_observation)!==Boolean(e.structured_observation_digest))throw new Error("OPERATIONAL_REALITY_STRUCTURED_OBSERVATION_PAIR_REQUIRED");if(e.structured_observation){const o=e.structured_observation,d=await sha(o);if(d!==e.structured_observation_digest||o.observation_ref!==e.evidence_ref||o.request_id!==e.request_id||o.company_id!==e.company_id||o.scope_id!==e.scope_id||o.scope_digest!==e.scope_digest||o.evidence_as_of!==e.evidence_as_of||o.evidence_role!==e.evidence_role)throw new Error("OPERATIONAL_REALITY_STRUCTURED_OBSERVATION_INVALID")}if(e.governed_resolution_selected&&!e.governed_resolution_ref)throw new Error("OPERATIONAL_REALITY_RESOLUTION_REF_REQUIRED");normalized.push(freeze({...e,evidence_ref:required(e.evidence_ref,"OPERATIONAL_REALITY_EVIDENCE_REF_REQUIRED"),source_identity_ref:required(e.source_identity_ref,"OPERATIONAL_REALITY_SOURCE_REQUIRED"),source_namespace:required(e.source_namespace,"OPERATIONAL_REALITY_SOURCE_NAMESPACE_REQUIRED"),semantic_key:required(e.semantic_key,"OPERATIONAL_REALITY_SEMANTIC_KEY_REQUIRED"),canonical_subject_refs:refs(e.canonical_subject_refs,"OPERATIONAL_REALITY_SUBJECT_INVALID",true),canonical_location_refs:refs(e.canonical_location_refs,"OPERATIONAL_REALITY_LOCATION_INVALID",true),qualification_refs:refs(e.qualification_refs,"OPERATIONAL_REALITY_QUALIFICATION_REQUIRED"),provenance_refs:refs(e.provenance_refs,"OPERATIONAL_REALITY_PROVENANCE_REQUIRED"),causal_lineage_refs:refs(e.causal_lineage_refs,"OPERATIONAL_REALITY_LINEAGE_REQUIRED")}))}normalized.sort((a,b)=>a.evidence_ref.localeCompare(b.evidence_ref));
 if(new Set(normalized.map(e=>e.evidence_ref)).size!==normalized.length)throw new Error("OPERATIONAL_REALITY_DUPLICATE_EVIDENCE");for(const c of input.coverage)if(c.tenant_id!==tenant||c.company_id!==scope.company_id||c.request_id!==scope.request_id||c.scope_id!==scope.scope_id||c.scope_digest!==scope.scope_digest||c.coverage_end!==asOf)throw new Error("OPERATIONAL_REALITY_COVERAGE_CONTEXT_MISMATCH");
 const grouped=new Map<string,typeof normalized>();for(const e of normalized)grouped.set(e.semantic_key,[...(grouped.get(e.semantic_key)??[]),e]);const semantic_groups=[...grouped].sort(([a],[b])=>a.localeCompare(b)).map(([semantic_key,items])=>{const claims=new Set(items.map(e=>e.claim_digest));if(items.length===1)return{semantic_key,evidence_refs:[items[0]!.evidence_ref],status:"SINGLE_SOURCE"as const};if(claims.size===1)return{semantic_key,evidence_refs:items.map(e=>e.evidence_ref),status:"COMPLEMENTARY"as const};const selected=items.filter(e=>e.governed_resolution_selected),resolutionRefs=new Set(items.map(e=>e.governed_resolution_ref).filter(Boolean));if(selected.length===1&&resolutionRefs.size===1&&items.every(e=>e.governed_resolution_ref===selected[0]!.governed_resolution_ref))return{semantic_key,evidence_refs:items.map(e=>e.evidence_ref),status:"GOVERNED_RESOLVED"as const,selected_evidence_ref:selected[0]!.evidence_ref,governed_resolution_ref:selected[0]!.governed_resolution_ref};return{semantic_key,evidence_refs:items.map(e=>e.evidence_ref),status:"UNRESOLVED_CONFLICT"as const}});
 const composition_status=semantic_groups.some(g=>g.status==="UNRESOLVED_CONFLICT")?"UNRESOLVED_CONFLICT"as const:"COMPOSED"as const,value={version:1 as const,composition_kind:"CANONICAL_OPERATIONAL_REALITY"as const,tenant_id:tenant,company_id:scope.company_id,request_id:scope.request_id,scope_id:scope.scope_id,scope_digest:scope.scope_digest,evidence_selection_ref:scope.evidence_selection_ref,source_snapshot_ref:scope.source_snapshot_ref,evidence_as_of:asOf,evidence_refs:normalized.map(e=>e.evidence_ref),structured_evidence:Object.freeze(normalized),source_identity_refs:refs(normalized.map(e=>e.source_identity_ref),"OPERATIONAL_REALITY_SOURCE_REQUIRED"),canonical_subject_refs:refs(normalized.flatMap(e=>e.canonical_subject_refs),"OPERATIONAL_REALITY_SUBJECT_INVALID",true),canonical_location_refs:refs(normalized.flatMap(e=>e.canonical_location_refs),"OPERATIONAL_REALITY_LOCATION_INVALID",true),coverage_refs:refs(input.coverage.map(c=>c.capability_id),"OPERATIONAL_REALITY_COVERAGE_INVALID",true),qualification_refs:refs(normalized.flatMap(e=>e.qualification_refs),"OPERATIONAL_REALITY_QUALIFICATION_REQUIRED"),provenance_refs:refs(normalized.flatMap(e=>e.provenance_refs),"OPERATIONAL_REALITY_PROVENANCE_REQUIRED"),causal_lineage_refs:refs([...normalized.flatMap(e=>e.causal_lineage_refs),...input.coverage.map(c=>c.capability_id)],"OPERATIONAL_REALITY_LINEAGE_REQUIRED"),semantic_groups,composition_status};const composition_digest=await sha(value);return freeze({...value,composition_id:`canonical-operational-reality:sha256:${composition_digest}`,composition_digest,digest_algorithm:"SHA-256"as const,observational_only:true as const,current_reality:true as const,counterfactual:false as const,tier_independent:true as const,recommended:false as const,executable:false as const,grants_authority:false as const,grants_execution:false as const});
}
export async function verifyCanonicalOperationalRealityCompositionV1(v:CanonicalOperationalRealityCompositionV1){const d=await sha(semantic(v));if(v.composition_digest!==d||v.composition_id!==`canonical-operational-reality:sha256:${d}`||v.digest_algorithm!=="SHA-256"||v.observational_only!==true||v.current_reality!==true||v.counterfactual!==false||v.tier_independent!==true||v.recommended!==false||v.executable!==false||v.grants_authority!==false||v.grants_execution!==false)throw new Error("OPERATIONAL_REALITY_INTEGRITY_INVALID")}

export async function retrieveCanonicalStructuredRealityV1(composition:CanonicalOperationalRealityCompositionV1,evidence_ref:string):Promise<CanonicalStructuredRealityRetrievalV1>{await verifyCanonicalOperationalRealityCompositionV1(composition);const ref=required(evidence_ref,"OPERATIONAL_REALITY_EVIDENCE_REF_REQUIRED"),seed=composition.structured_evidence.find(x=>x.evidence_ref===ref);if(!seed||!composition.evidence_refs.includes(ref))throw new Error("OPERATIONAL_REALITY_EVIDENCE_NOT_ADMITTED");const group=composition.semantic_groups.find(x=>x.evidence_refs.includes(ref));if(!group)throw new Error("OPERATIONAL_REALITY_SEMANTIC_GROUP_MISSING");const members=composition.structured_evidence.filter(x=>group.evidence_refs.includes(x.evidence_ref));if(members.length!==group.evidence_refs.length||members.some(x=>!x.structured_observation||!x.structured_observation_digest))throw new Error("OPERATIONAL_REALITY_STRUCTURED_RETENTION_UNAVAILABLE");for(const x of members)if(await sha(x.structured_observation)!==x.structured_observation_digest)throw new Error("OPERATIONAL_REALITY_STRUCTURED_OBSERVATION_INVALID");const audit=Object.freeze(members.map(x=>x.structured_observation!)),comparison=group.status==="UNRESOLVED_CONFLICT"?[]:group.status==="GOVERNED_RESOLVED"?audit.filter(x=>x.observation_ref===group.selected_evidence_ref):audit,status=group.status==="UNRESOLVED_CONFLICT"?"UNRESOLVED_CONFLICT"as const:group.status==="COMPLEMENTARY"?"COMPLEMENTARY"as const:"RESOLVED"as const;return freeze({version:1 as const,composition_ref:composition.composition_id,semantic_key:group.semantic_key,group_status:group.status,audit_observations:audit,comparison_candidates:Object.freeze(comparison),retrieval_status:status,observational_only:true as const,grants_authority:false as const,grants_execution:false as const})}
