import { verifyOperationalSignalEvaluationScopeV1, type OperationalSignalScopeBindingV1 } from "../cockpit/operational.signal.evaluation.scope.v1";
import { verifyOperationsCurrentPlanMembershipSetV1, type OperationsCurrentPlanMembershipSetV1 } from "../industrial/cognition/operations.current.plan.membership.v1";
import { verifyOperationsProtectedObjectiveSetV1, type OperationsProtectedObjectiveSetV1 } from "../industrial/cognition/operations.protected.objective.set.v1";
import { verifyCanonicalOperationalRealityCompositionV1, type CanonicalOperationalRealityCompositionV1 } from "./canonical.operational.reality.composition.v1";
import { verifyGovernedPlanRealityElementComparisonV1, type GovernedPlanRealityElementComparisonV1 } from "./plan.reality.comparison.doctrine.v1";
import { verifyGovernedPlanRealityElementMaterialityV1, type GovernedPlanRealityElementMaterialityV1 } from "./plan.reality.materiality.policy.v1";
import { aggregateGovernedScopeRealityAlignmentV1, type GovernedScopeRealityAlignmentV1 } from "./plan.reality.scope.aggregation.doctrine.v1";

export type CanonicalPlanRelativeRealityAlignmentReasonV1="OBJECTIVE_EVALUATION_COVERAGE_INCOMPLETE"|"REQUIRED_CANONICAL_REALITY_CONFLICT"|"REQUIRED_OBJECTIVE_UNRESOLVED"|"ALL_REQUIRED_OBJECTIVES_ALIGNED"|"REQUIRED_RECOVERABLE_DEVIATION"|"REQUIRED_MATERIAL_INCOMPATIBILITY";
export type CanonicalPlanRelativeRealityAlignmentV1=Readonly<{version:1;evaluation_kind:"CANONICAL_PLAN_RELATIVE_REALITY_ALIGNMENT";policy_ref:"policy:canonical-plan-relative-reality-alignment-v1";tenant_id:string;company_id:string;request_id:string;scope_id:string;scope_digest:string;evidence_as_of:string;evaluated_at:string;current_plan_context_ref:string;current_plan_context_digest:string;protected_objective_set_ref:string;protected_objective_set_digest:string;canonical_reality_ref:string;canonical_reality_digest:string;objective_evaluation_refs:readonly string[];objective_evaluation_count:number;required_objective_count:number;aggregation_ref?:string;aggregation_digest?:string;assertability:"ASSERTABLE"|"NOT_ASSERTABLE";alignment?:GovernedScopeRealityAlignmentV1;reason_codes:readonly CanonicalPlanRelativeRealityAlignmentReasonV1[];evidence_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[];evaluation_id:string;evaluation_digest:string;digest_algorithm:"SHA-256";deterministic:true;source_agnostic:true;current_reality:true;plan_relative:true;tier_independent:true;observational_only:true;recommended:false;executable:false;grants_authority:false;grants_execution:false}>;

function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return`{${Object.entries(v as Record<string,unknown>).filter(([,x])=>x!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(",")}}`;return JSON.stringify(v)}
async function sha(v:unknown){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(v)));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}
function freeze<T>(v:T):Readonly<T>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v as Record<string,unknown>).forEach(freeze);Object.freeze(v)}return v}
function refs(v:readonly string[]){return Object.freeze([...new Set(v.map(x=>x.trim()).filter(Boolean))].sort())}

export async function evaluateCanonicalPlanRelativeRealityAlignmentV1(input:Readonly<{version:1;evaluation_scope:OperationalSignalScopeBindingV1;current_plan:OperationsCurrentPlanMembershipSetV1;protected_objective_set:OperationsProtectedObjectiveSetV1;canonical_reality:CanonicalOperationalRealityCompositionV1;element_evaluations:readonly Readonly<{comparison:GovernedPlanRealityElementComparisonV1;materiality:GovernedPlanRealityElementMaterialityV1}>[]}>):Promise<CanonicalPlanRelativeRealityAlignmentV1>{
 if(input.version!==1)throw new Error("CANONICAL_REALITY_ALIGNMENT_VERSION_UNSUPPORTED");await Promise.all([verifyOperationalSignalEvaluationScopeV1(input.evaluation_scope.scope,input.evaluation_scope.scope),verifyOperationsCurrentPlanMembershipSetV1(input.current_plan),verifyOperationsProtectedObjectiveSetV1(input.protected_objective_set),verifyCanonicalOperationalRealityCompositionV1(input.canonical_reality)]);const s=input.evaluation_scope.scope,p=input.current_plan.context,o=input.protected_objective_set,r=input.canonical_reality;if(s.scope_type!=="REQUEST_DATASET"||s.domain!=="operations")throw new Error("CANONICAL_REALITY_ALIGNMENT_SCOPE_UNSUPPORTED");if(p.context_id!==o.current_plan_context_ref||p.context_digest!==o.current_plan_context_digest||p.scope_id!==s.scope_id||p.scope_digest!==s.scope_digest||p.request_id!==s.request_id||p.company_id!==s.company_id||p.tenant_id!==o.tenant_id||p.evidence_as_of!==input.evaluation_scope.evidence_as_of)throw new Error("CANONICAL_REALITY_ALIGNMENT_PLAN_MISMATCH");if(o.scope_id!==s.scope_id||o.scope_digest!==s.scope_digest||o.request_id!==s.request_id||o.company_id!==s.company_id||o.evidence_as_of!==input.evaluation_scope.evidence_as_of||o.evaluated_at!==input.evaluation_scope.evaluated_at)throw new Error("CANONICAL_REALITY_ALIGNMENT_OBJECTIVE_SET_MISMATCH");if(r.tenant_id!==o.tenant_id||r.company_id!==s.company_id||r.request_id!==s.request_id||r.scope_id!==s.scope_id||r.scope_digest!==s.scope_digest||r.evidence_selection_ref!==s.evidence_selection_ref||r.source_snapshot_ref!==s.source_snapshot_ref||r.evidence_as_of!==input.evaluation_scope.evidence_as_of)throw new Error("CANONICAL_REALITY_ALIGNMENT_REALITY_MISMATCH");
 await Promise.all(input.element_evaluations.flatMap(x=>[verifyGovernedPlanRealityElementComparisonV1(x.comparison),verifyGovernedPlanRealityElementMaterialityV1(x.materiality)]));const expectedBindings=new Set(o.members.map(x=>x.objective_binding_ref)),seen=new Set<string>();for(const x of input.element_evaluations){const c=x.comparison,m=x.materiality;if(m.comparison_ref!==c.comparison_id||m.comparison_digest!==c.comparison_digest||c.applicable_plan_context_ref!==p.context_id||c.applicable_plan_context_digest!==p.context_digest||!m.protected_objective_ref||!expectedBindings.has(m.protected_objective_ref)||seen.has(m.protected_objective_ref))throw new Error("CANONICAL_REALITY_ALIGNMENT_ELEMENT_BINDING_INVALID");if(!r.evidence_refs.includes(c.reality_observation_ref))throw new Error("CANONICAL_REALITY_ALIGNMENT_REALITY_EVIDENCE_MISSING");seen.add(m.protected_objective_ref)}if(input.element_evaluations.length>o.member_count)throw new Error("CANONICAL_REALITY_ALIGNMENT_OBJECTIVE_SUBSTITUTION");
 const incomplete=input.element_evaluations.length!==o.member_count||seen.size!==o.member_count,requiredConflict=input.element_evaluations.some(x=>r.semantic_groups.some(g=>g.status==="UNRESOLVED_CONFLICT"&&g.evidence_refs.includes(x.comparison.reality_observation_ref)));let aggregation:Awaited<ReturnType<typeof aggregateGovernedScopeRealityAlignmentV1>>|undefined;if(!incomplete&&!requiredConflict)aggregation=await aggregateGovernedScopeRealityAlignmentV1({version:1,objective_set:o,element_materialities:input.element_evaluations.map(x=>x.materiality)});const assertability=incomplete||requiredConflict?"NOT_ASSERTABLE"as const:aggregation!.assertability,alignment=assertability==="ASSERTABLE"?aggregation!.alignment:undefined,reason_codes:CanonicalPlanRelativeRealityAlignmentReasonV1[]=incomplete?["OBJECTIVE_EVALUATION_COVERAGE_INCOMPLETE"]:requiredConflict?["REQUIRED_CANONICAL_REALITY_CONFLICT"]:[aggregation!.reason];
 const ordered=[...input.element_evaluations].sort((a,b)=>a.materiality.protected_objective_ref!.localeCompare(b.materiality.protected_objective_ref!)),evidence_refs=refs([...r.evidence_refs,...o.evidence_refs,...ordered.flatMap(x=>x.materiality.evidence_refs)]),qualification_refs=refs([...r.qualification_refs,...o.qualification_refs,...ordered.flatMap(x=>x.materiality.qualification_refs)]),provenance_refs=refs([...r.provenance_refs,...o.provenance_refs,...ordered.flatMap(x=>x.materiality.provenance_refs)]),causal_lineage_refs=refs([...r.causal_lineage_refs,...o.causal_lineage_refs,r.composition_id,o.objective_set_id,...ordered.flatMap(x=>[x.comparison.comparison_id,x.materiality.materiality_id]),...(aggregation?[aggregation.aggregation_id]:[])]),semantic={version:1 as const,evaluation_kind:"CANONICAL_PLAN_RELATIVE_REALITY_ALIGNMENT"as const,policy_ref:"policy:canonical-plan-relative-reality-alignment-v1"as const,tenant_id:o.tenant_id,company_id:s.company_id,request_id:s.request_id,scope_id:s.scope_id,scope_digest:s.scope_digest,evidence_as_of:input.evaluation_scope.evidence_as_of,evaluated_at:input.evaluation_scope.evaluated_at,current_plan_context_ref:p.context_id,current_plan_context_digest:p.context_digest,protected_objective_set_ref:o.objective_set_id,protected_objective_set_digest:o.objective_set_digest,canonical_reality_ref:r.composition_id,canonical_reality_digest:r.composition_digest,objective_evaluation_refs:Object.freeze(ordered.map(x=>x.materiality.materiality_id)),objective_evaluation_count:ordered.length,required_objective_count:o.member_count,...(aggregation?{aggregation_ref:aggregation.aggregation_id,aggregation_digest:aggregation.aggregation_digest}:{}),assertability,...(alignment?{alignment}:{}),reason_codes:Object.freeze(reason_codes),evidence_refs,qualification_refs,provenance_refs,causal_lineage_refs},evaluation_digest=await sha(semantic);return freeze({...semantic,evaluation_id:`canonical-plan-relative-reality-alignment:sha256:${evaluation_digest}`,evaluation_digest,digest_algorithm:"SHA-256"as const,deterministic:true as const,source_agnostic:true as const,current_reality:true as const,plan_relative:true as const,tier_independent:true as const,observational_only:true as const,recommended:false as const,executable:false as const,grants_authority:false as const,grants_execution:false as const})
}

export async function verifyCanonicalPlanRelativeRealityAlignmentV1(value:CanonicalPlanRelativeRealityAlignmentV1):Promise<void>{const{evaluation_id,evaluation_digest,digest_algorithm,deterministic,source_agnostic,current_reality,plan_relative,tier_independent,observational_only,recommended,executable,grants_authority,grants_execution,...semantic}=value,expected=await sha(semantic);if(evaluation_id!==`canonical-plan-relative-reality-alignment:sha256:${expected}`||evaluation_digest!==expected||digest_algorithm!=="SHA-256"||deterministic!==true||source_agnostic!==true||current_reality!==true||plan_relative!==true||tier_independent!==true||observational_only!==true||recommended!==false||executable!==false||grants_authority!==false||grants_execution!==false||(value.assertability==="ASSERTABLE")!==Boolean(value.alignment)||value.objective_evaluation_count>value.required_objective_count)throw new Error("CANONICAL_REALITY_ALIGNMENT_INTEGRITY_INVALID")}
