import type { OperationalSubjectRefV1 } from "../cognition/canonical.operational.roles.v1";
import type { OperationalSignalScopeBindingV1 } from "../cockpit/operational.signal.evaluation.scope.v1";
import { verifyOperationalSignalEvaluationScopeV1 } from "../cockpit/operational.signal.evaluation.scope.v1";

export type OperationalRepresentationRelationshipKindV1="DERIVED_FROM"|"DEPENDS_ON"|"SHARED_ORIGIN"|"INDEPENDENT";
export type AdHocOperationalEvidenceKindV1="XLSX"|"CSV"|"EMAIL"|"CHAT"|"DOCUMENT"|"USER_STATEMENT"|"OTHER";
export type GovernedOperationalRepresentationV1=Readonly<{version:1;representation_ref:string;representation_id:string;representation_digest:string;artifact_digest:string;digest_algorithm:"SHA-256";company_id:string;domain_ref:string;governed_scope_refs:readonly string[];subject_refs:readonly string[];source_binding_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[];observability:"PERSISTENT";refreshability:"INDEPENDENTLY_REFRESHABLE";refresh_policy_ref:string;observational_only:true;grants_authority:false;grants_execution:false}>;
export type OperationalRepresentationRelationshipV1=Readonly<{version:1;relationship_kind:OperationalRepresentationRelationshipKindV1;source_representation_id:string;target_representation_id:string;independence:"ESTABLISHED"|"NOT_ESTABLISHED";independence_evidence_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[];relationship_id:string;relationship_digest:string;digest_algorithm:"SHA-256";observational_only:true;grants_authority:false;grants_execution:false}>;
export type GovernedOperationalEvidenceIntroductionV1=Readonly<{version:1;evidence_ref:string;introduction_mode:"REQUEST_BOUND_AD_HOC";evidence_kind:AdHocOperationalEvidenceKindV1;provenance_refs:readonly string[];causal_lineage_refs:readonly string[];creates_operational_representation:false}>|Readonly<{version:1;evidence_ref:string;introduction_mode:"PERSISTENT_REPRESENTATION_OBSERVATION";representation_id:string;provenance_refs:readonly string[];causal_lineage_refs:readonly string[];creates_operational_representation:false}>;
export type ObservationBreadthV1=Readonly<{version:1;breadth_kind:"DISTINCT_GOVERNED_OPERATIONAL_REPRESENTATIONS";company_id:string;scope_id:string;scope_digest:string;evidence_as_of:string;evaluated_at:string;representations:readonly string[];count:number;breadth_id:string;breadth_digest:string;digest_algorithm:"SHA-256";observational_only:true;tier_independent:true;confidence_independent:true;grants_authority:false;grants_execution:false}>;

const forbidden=["authority_tier","intelligence_mode","inference_provider","commercial_plan","confidence","quality_score","price"];
const relationshipKinds=new Set<OperationalRepresentationRelationshipKindV1>(["DERIVED_FROM","DEPENDS_ON","SHARED_ORIGIN","INDEPENDENT"]),evidenceKinds=new Set<AdHocOperationalEvidenceKindV1>(["XLSX","CSV","EMAIL","CHAT","DOCUMENT","USER_STATEMENT","OTHER"]);
function required(v:string|undefined,code:string){const x=v?.trim();if(!x)throw new Error(code);return x}
function refs(v:readonly string[],code:string,empty=false){if(!Array.isArray(v))throw new Error(code);const x=[...new Set(v.map(y=>required(y,code)))].sort();if(!empty&&!x.length)throw new Error(code);return x}
function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return`{${Object.entries(v as Record<string,unknown>).filter(([,x])=>x!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(",")}}`;return JSON.stringify(v)}
async function sha(v:unknown){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(v)));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}
function freeze<T>(v:T):Readonly<T>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v as Record<string,unknown>).forEach(freeze);Object.freeze(v)}return v}
function safe(input:object){for(const key of forbidden)if(key in input)throw new Error("IORS_UNSUPPORTED_SEMANTIC")}

export async function createGovernedOperationalRepresentationV1(input:Readonly<{version:1;representation_ref:string;company_id:string;domain_ref:string;governed_scope_refs:readonly string[];subjects:readonly OperationalSubjectRefV1[];source_binding_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[];observability:"PERSISTENT";refreshability:"INDEPENDENTLY_REFRESHABLE";refresh_policy_ref:string}>):Promise<GovernedOperationalRepresentationV1>{
 safe(input as object);if(input.version!==1)throw new Error("IORS_VERSION_UNSUPPORTED");if(input.observability!=="PERSISTENT"||input.refreshability!=="INDEPENDENTLY_REFRESHABLE")throw new Error("IORS_PERSISTENT_REFRESHABILITY_REQUIRED");
 const company_id=required(input.company_id,"IORS_COMPANY_REQUIRED"),domain_ref=required(input.domain_ref,"IORS_DOMAIN_REQUIRED");for(const subject of input.subjects)if(subject.company_id!==company_id||subject.domain_ref!==domain_ref)throw new Error("IORS_SUBJECT_SCOPE_MISMATCH");
 const identity={version:1 as const,representation_ref:required(input.representation_ref,"IORS_REPRESENTATION_REF_REQUIRED"),company_id,domain_ref,governed_scope_refs:refs(input.governed_scope_refs,"IORS_SCOPE_REQUIRED"),subject_refs:refs(input.subjects.map(x=>x.subject_id),"IORS_SUBJECT_REQUIRED",true),observability:input.observability,refreshability:input.refreshability,refresh_policy_ref:required(input.refresh_policy_ref,"IORS_REFRESH_POLICY_REQUIRED")};const representation_digest=await sha(identity),representation_id=`governed-operational-representation:sha256:${representation_digest}`;
 const semantic={...identity,representation_id,representation_digest,source_binding_refs:refs(input.source_binding_refs,"IORS_SOURCE_BINDING_REQUIRED"),provenance_refs:refs(input.provenance_refs,"IORS_PROVENANCE_REQUIRED"),causal_lineage_refs:refs(input.causal_lineage_refs,"IORS_LINEAGE_REQUIRED")};const artifact_digest=await sha(semantic);return freeze({...semantic,artifact_digest,digest_algorithm:"SHA-256"as const,observational_only:true as const,grants_authority:false as const,grants_execution:false as const});
}
export async function createOperationalRepresentationRelationshipV1(input:Readonly<{version:1;relationship_kind:OperationalRepresentationRelationshipKindV1;source:GovernedOperationalRepresentationV1;target:GovernedOperationalRepresentationV1;independence_evidence_refs?:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[]}>):Promise<OperationalRepresentationRelationshipV1>{
 safe(input as object);if(input.version!==1||!relationshipKinds.has(input.relationship_kind)||input.source.company_id!==input.target.company_id||input.source.representation_id===input.target.representation_id)throw new Error("IORS_RELATIONSHIP_INVALID");const independence=input.relationship_kind==="INDEPENDENT"?"ESTABLISHED"as const:"NOT_ESTABLISHED"as const,evidence=refs(input.independence_evidence_refs??[],"IORS_INDEPENDENCE_EVIDENCE_REQUIRED",input.relationship_kind!=="INDEPENDENT");if(input.relationship_kind==="INDEPENDENT"&&!evidence.length)throw new Error("IORS_INDEPENDENCE_EVIDENCE_REQUIRED");
 const semantic={version:1 as const,relationship_kind:input.relationship_kind,source_representation_id:input.source.representation_id,target_representation_id:input.target.representation_id,independence,independence_evidence_refs:evidence,provenance_refs:refs(input.provenance_refs,"IORS_RELATIONSHIP_PROVENANCE_REQUIRED"),causal_lineage_refs:refs([...input.causal_lineage_refs,input.source.representation_id,input.target.representation_id],"IORS_RELATIONSHIP_LINEAGE_REQUIRED")};const relationship_digest=await sha(semantic);return freeze({...semantic,relationship_id:`operational-representation-relationship:sha256:${relationship_digest}`,relationship_digest,digest_algorithm:"SHA-256"as const,observational_only:true as const,grants_authority:false as const,grants_execution:false as const});
}
export function classifyGovernedOperationalEvidenceV1(input:Readonly<{version:1;evidence_ref:string;evidence_kind:AdHocOperationalEvidenceKindV1;provenance_refs:readonly string[];causal_lineage_refs:readonly string[]}>|Readonly<{version:1;evidence_ref:string;representation:GovernedOperationalRepresentationV1;provenance_refs:readonly string[];causal_lineage_refs:readonly string[]}>):GovernedOperationalEvidenceIntroductionV1{
 if(input.version!==1)throw new Error("IORS_EVIDENCE_VERSION_UNSUPPORTED");if("evidence_kind"in input&&!evidenceKinds.has(input.evidence_kind))throw new Error("IORS_EVIDENCE_KIND_UNSUPPORTED");const base={version:1 as const,evidence_ref:required(input.evidence_ref,"IORS_EVIDENCE_REF_REQUIRED"),provenance_refs:refs(input.provenance_refs,"IORS_EVIDENCE_PROVENANCE_REQUIRED"),causal_lineage_refs:refs(input.causal_lineage_refs,"IORS_EVIDENCE_LINEAGE_REQUIRED"),creates_operational_representation:false as const};return freeze("representation"in input?{...base,introduction_mode:"PERSISTENT_REPRESENTATION_OBSERVATION"as const,representation_id:input.representation.representation_id}:{...base,introduction_mode:"REQUEST_BOUND_AD_HOC"as const,evidence_kind:input.evidence_kind});
}
export async function createObservationBreadthV1(input:Readonly<{version:1;evaluation_scope:OperationalSignalScopeBindingV1;representations:readonly GovernedOperationalRepresentationV1[]}>):Promise<ObservationBreadthV1>{
 safe(input as object);if(input.version!==1)throw new Error("OBSERVATION_BREADTH_VERSION_UNSUPPORTED");const scope=input.evaluation_scope.scope;await verifyOperationalSignalEvaluationScopeV1(scope,scope);const eligible=input.representations.filter(x=>x.company_id===scope.company_id&&x.governed_scope_refs.includes(scope.scope_id));if(eligible.length!==input.representations.length)throw new Error("OBSERVATION_BREADTH_SCOPE_MISMATCH");const representations=refs(eligible.map(x=>x.representation_id),"OBSERVATION_BREADTH_REPRESENTATION_INVALID",true),semantic={version:1 as const,breadth_kind:"DISTINCT_GOVERNED_OPERATIONAL_REPRESENTATIONS"as const,company_id:scope.company_id,scope_id:scope.scope_id,scope_digest:scope.scope_digest,evidence_as_of:input.evaluation_scope.evidence_as_of,evaluated_at:input.evaluation_scope.evaluated_at,representations,count:representations.length};const breadth_digest=await sha(semantic);return freeze({...semantic,breadth_id:`observation-breadth:sha256:${breadth_digest}`,breadth_digest,digest_algorithm:"SHA-256"as const,observational_only:true as const,tier_independent:true as const,confidence_independent:true as const,grants_authority:false as const,grants_execution:false as const});
}
