import type { OperationalSubjectRefV1 } from "../cognition/canonical.operational.roles.v1";
import type { OperationalSignalScopeBindingV1 } from "../cockpit/operational.signal.evaluation.scope.v1";
import { verifyOperationalSignalEvaluationScopeV1 } from "../cockpit/operational.signal.evaluation.scope.v1";
import type { CanonicalOperationalRealityEvidenceV1, OperationalRealityEvidenceRoleV1 } from "./canonical.operational.reality.composition.v1";
import type { GovernedOperationalEvidenceIntroductionV1, GovernedOperationalRepresentationV1, OperationalRepresentationRelationshipV1 } from "./governed.operational.representation.v1";

export type GovernedSubjectBindingOutcomeV1="SAME_SUBJECT"|"DIFFERENT_SUBJECT"|"UNRESOLVED";
export type GovernedTemporalBindingOutcomeV1="ALIGNED"|"RELEVANT"|"NON_OVERLAPPING"|"UNRESOLVED";
export type GovernedClaimRelationshipV1="CONSISTENT_COMPARABLE_CLAIM"|"CONFLICTING_COMPARABLE_CLAIM"|"COMPLEMENTARY"|"INSUFFICIENT_EVIDENCE";
export type GovernedSubjectBindingV1=Readonly<{version:1;outcome:GovernedSubjectBindingOutcomeV1;members:readonly Readonly<{representation_identity_ref:string;local_subject_ref:string}>[];canonical_subject?:OperationalSubjectRefV1;binding_evidence_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[];binding_id:string;binding_digest:string;digest_algorithm:"SHA-256";observational_only:true;grants_authority:false;grants_execution:false}>;
export type GovernedTemporalBindingV1=Readonly<{version:1;left_observation_ref:string;right_observation_ref:string;left_effectivity?:Readonly<{from:string;until?:string}>;right_effectivity?:Readonly<{from:string;until?:string}>;outcome:GovernedTemporalBindingOutcomeV1;relevance_evidence_refs:readonly string[];binding_id:string;binding_digest:string;digest_algorithm:"SHA-256";observational_only:true;grants_authority:false;grants_execution:false}>;
export type GovernedOperationalClaimValueV1=Readonly<{kind:"QUANTITY";value:number;unit_ref:string}>|Readonly<{kind:"STATE";value_ref:string}>;
type ObservationSourceV1=Readonly<{kind:"PERSISTENT_REPRESENTATION";representation:GovernedOperationalRepresentationV1;original_source_identity_ref:string}>|Readonly<{kind:"REQUEST_BOUND_AD_HOC";introduction:GovernedOperationalEvidenceIntroductionV1;original_source_identity_ref:string}>;
export type GovernedRepresentationObservationInputV1=Readonly<{version:1;observation_ref:string;source:ObservationSourceV1;local_subject_ref:string;subject_binding:GovernedSubjectBindingV1;observed_at:string;effective_from?:string;effective_until?:string;dimension_ref:string;operational_state_ref:string;process_stage_ref?:string;evidence_role:OperationalRealityEvidenceRoleV1;claim:GovernedOperationalClaimValueV1;location_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[]}>;
export type GovernedClaimRelationshipArtifactV1=Readonly<{version:1;left_observation_ref:string;right_observation_ref:string;relationship:GovernedClaimRelationshipV1;subject_outcome:GovernedSubjectBindingOutcomeV1;temporal_outcome:GovernedTemporalBindingOutcomeV1;semantically_comparable:boolean;independence_established:boolean;relationship_id:string;relationship_digest:string;digest_algorithm:"SHA-256";observational_only:true;grants_authority:false;grants_execution:false}>;
export type GovernedMultiSourceRealityAlignmentV1=Readonly<{version:1;alignment_kind:"MULTI_SOURCE_GOVERNED_REALITY_ALIGNMENT";company_id:string;scope_id:string;scope_digest:string;evidence_as_of:string;canonical_evidence:readonly CanonicalOperationalRealityEvidenceV1[];claim_relationships:readonly GovernedClaimRelationshipArtifactV1[];representation_relationship_refs:readonly string[];alignment_id:string;alignment_digest:string;digest_algorithm:"SHA-256";observational_only:true;tier_independent:true;recommended:false;executable:false;grants_authority:false;grants_execution:false}>;

const roles=new Set<OperationalRealityEvidenceRoleV1>(["CURRENT_FACT","CURRENT_PLAN","REALIZED_EVENT","GOVERNED_FUTURE_SUPPLY","PLANNED_PRODUCTION","USER_CONFIRMED_CURRENT"]);
function required(v:string|undefined,c:string){const x=v?.trim();if(!x)throw new Error(c);return x}
function refs(v:readonly string[],c:string,empty=false){if(!Array.isArray(v))throw new Error(c);const x=[...new Set(v.map(y=>required(y,c)))].sort();if(!empty&&!x.length)throw new Error(c);return x}
function instant(v:string|undefined,c:string){if(!v)return undefined;const n=Date.parse(v);if(!Number.isFinite(n)||new Date(n).toISOString()!==v)throw new Error(c);return v}
function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return`{${Object.entries(v as Record<string,unknown>).filter(([,x])=>x!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(",")}}`;return JSON.stringify(v)}
async function sha(v:unknown){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(v)));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}
function freeze<T>(v:T):Readonly<T>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v as Record<string,unknown>).forEach(freeze);Object.freeze(v)}return v}

export async function createGovernedSubjectBindingV1(input:Readonly<{version:1;outcome:GovernedSubjectBindingOutcomeV1;members:readonly Readonly<{representation_identity_ref:string;local_subject_ref:string}>[];canonical_subject?:OperationalSubjectRefV1;binding_evidence_refs?:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[]}>):Promise<GovernedSubjectBindingV1>{
 if(input.version!==1)throw new Error("MULTI_SOURCE_SUBJECT_BINDING_VERSION_UNSUPPORTED");const members=[...input.members].map(x=>({representation_identity_ref:required(x.representation_identity_ref,"MULTI_SOURCE_SUBJECT_REPRESENTATION_REQUIRED"),local_subject_ref:required(x.local_subject_ref,"MULTI_SOURCE_LOCAL_SUBJECT_REQUIRED")})).sort((a,b)=>canonical(a).localeCompare(canonical(b)));if(members.length<2||new Set(members.map(canonical)).size!==members.length)throw new Error("MULTI_SOURCE_SUBJECT_BINDING_MEMBERS_INVALID");const evidence=refs(input.binding_evidence_refs??[],"MULTI_SOURCE_SUBJECT_BINDING_EVIDENCE_REQUIRED",true);if(input.outcome==="SAME_SUBJECT"&&(!input.canonical_subject||!evidence.length))throw new Error("MULTI_SOURCE_SUBJECT_EQUIVALENCE_UNESTABLISHED");if(input.outcome==="DIFFERENT_SUBJECT"&&(!evidence.length||input.canonical_subject))throw new Error("MULTI_SOURCE_SUBJECT_DIFFERENCE_UNESTABLISHED");if(input.outcome==="UNRESOLVED"&&input.canonical_subject)throw new Error("MULTI_SOURCE_UNRESOLVED_SUBJECT_CANNOT_BE_CANONICAL");if(input.canonical_subject&&members.some(x=>input.canonical_subject!.company_id.trim()===""))throw new Error("MULTI_SOURCE_SUBJECT_SCOPE_INVALID");const semantic={version:1 as const,outcome:input.outcome,members,...(input.canonical_subject?{canonical_subject:input.canonical_subject}:{}),binding_evidence_refs:evidence,provenance_refs:refs(input.provenance_refs,"MULTI_SOURCE_SUBJECT_PROVENANCE_REQUIRED"),causal_lineage_refs:refs(input.causal_lineage_refs,"MULTI_SOURCE_SUBJECT_LINEAGE_REQUIRED")};const binding_digest=await sha(semantic);return freeze({...semantic,binding_id:`governed-subject-binding:sha256:${binding_digest}`,binding_digest,digest_algorithm:"SHA-256"as const,observational_only:true as const,grants_authority:false as const,grants_execution:false as const})
}

export async function createGovernedTemporalBindingV1(input:Readonly<{version:1;left_observation_ref:string;right_observation_ref:string;left_effectivity?:Readonly<{from:string;until?:string}>;right_effectivity?:Readonly<{from:string;until?:string}>;relevance_evidence_refs?:readonly string[]}>):Promise<GovernedTemporalBindingV1>{
 if(input.version!==1)throw new Error("MULTI_SOURCE_TEMPORAL_BINDING_VERSION_UNSUPPORTED");const normalize=(x:Readonly<{from:string;until?:string}>|undefined)=>{if(!x)return undefined;const from=instant(x.from,"MULTI_SOURCE_EFFECTIVITY_INVALID")!,until=instant(x.until,"MULTI_SOURCE_EFFECTIVITY_INVALID");if(until&&Date.parse(until)<Date.parse(from))throw new Error("MULTI_SOURCE_EFFECTIVITY_INVALID");return freeze({from,...(until?{until}:{})})};const left_effectivity=normalize(input.left_effectivity),right_effectivity=normalize(input.right_effectivity),evidence=refs(input.relevance_evidence_refs??[],"MULTI_SOURCE_TEMPORAL_RELEVANCE_EVIDENCE_INVALID",true);let outcome:GovernedTemporalBindingOutcomeV1="UNRESOLVED";if(left_effectivity&&right_effectivity){const le=Date.parse(left_effectivity.until??left_effectivity.from),rs=Date.parse(right_effectivity.from),re=Date.parse(right_effectivity.until??right_effectivity.from),ls=Date.parse(left_effectivity.from),overlap=ls<=re&&rs<=le;if(canonical(left_effectivity)===canonical(right_effectivity))outcome="ALIGNED";else if(overlap||evidence.length)outcome="RELEVANT";else outcome="NON_OVERLAPPING"}const semantic={version:1 as const,left_observation_ref:required(input.left_observation_ref,"MULTI_SOURCE_OBSERVATION_REF_REQUIRED"),right_observation_ref:required(input.right_observation_ref,"MULTI_SOURCE_OBSERVATION_REF_REQUIRED"),...(left_effectivity?{left_effectivity}:{}),...(right_effectivity?{right_effectivity}:{}),outcome,relevance_evidence_refs:evidence};const binding_digest=await sha(semantic);return freeze({...semantic,binding_id:`governed-temporal-binding:sha256:${binding_digest}`,binding_digest,digest_algorithm:"SHA-256"as const,observational_only:true as const,grants_authority:false as const,grants_execution:false as const})
}

function sourceIdentity(o:GovernedRepresentationObservationInputV1){return o.source.kind==="PERSISTENT_REPRESENTATION"?o.source.representation.representation_id:o.source.introduction.evidence_ref}
function coordinate(o:GovernedRepresentationObservationInputV1){return{subject:o.subject_binding.outcome==="SAME_SUBJECT"?o.subject_binding.canonical_subject!.subject_id:`unresolved:${sourceIdentity(o)}:${o.local_subject_ref}`,dimension_ref:required(o.dimension_ref,"MULTI_SOURCE_DIMENSION_REQUIRED"),operational_state_ref:required(o.operational_state_ref,"MULTI_SOURCE_STATE_REQUIRED"),process_stage_ref:o.process_stage_ref?required(o.process_stage_ref,"MULTI_SOURCE_STAGE_INVALID"):undefined,location_refs:refs(o.location_refs,"MULTI_SOURCE_LOCATION_INVALID",true),unit_ref:o.claim.kind==="QUANTITY"?required(o.claim.unit_ref,"MULTI_SOURCE_UNIT_REQUIRED"):undefined,effective_from:o.effective_from,effective_until:o.effective_until}}
function bindingFor(a:GovernedRepresentationObservationInputV1,b:GovernedRepresentationObservationInputV1,bindings:readonly GovernedTemporalBindingV1[]){return bindings.find(x=>(x.left_observation_ref===a.observation_ref&&x.right_observation_ref===b.observation_ref)||(x.left_observation_ref===b.observation_ref&&x.right_observation_ref===a.observation_ref))}
function independence(a:string,b:string,relationships:readonly OperationalRepresentationRelationshipV1[]){return relationships.some(x=>x.relationship_kind==="INDEPENDENT"&&x.independence==="ESTABLISHED"&&((x.source_representation_id===a&&x.target_representation_id===b)||(x.source_representation_id===b&&x.target_representation_id===a)))}

export async function alignGovernedMultiSourceOperationalRealityV1(input:Readonly<{version:1;tenant_id:string;evaluation_scope:OperationalSignalScopeBindingV1;observations:readonly GovernedRepresentationObservationInputV1[];temporal_bindings:readonly GovernedTemporalBindingV1[];representation_relationships:readonly OperationalRepresentationRelationshipV1[]}>):Promise<GovernedMultiSourceRealityAlignmentV1>{
 if(input.version!==1)throw new Error("MULTI_SOURCE_ALIGNMENT_VERSION_UNSUPPORTED");await verifyOperationalSignalEvaluationScopeV1(input.evaluation_scope.scope,input.evaluation_scope.scope);if(!input.observations.length)throw new Error("MULTI_SOURCE_OBSERVATIONS_REQUIRED");const scope=input.evaluation_scope.scope,asOf=input.evaluation_scope.evidence_as_of,observations=[...input.observations].sort((a,b)=>a.observation_ref.localeCompare(b.observation_ref));const canonical_evidence:CanonicalOperationalRealityEvidenceV1[]=[];
 for(const o of observations){if(o.version!==1||!roles.has(o.evidence_role))throw new Error("MULTI_SOURCE_OBSERVATION_INVALID");instant(o.observed_at,"MULTI_SOURCE_OBSERVED_AT_INVALID");instant(o.effective_from,"MULTI_SOURCE_EFFECTIVITY_INVALID");instant(o.effective_until,"MULTI_SOURCE_EFFECTIVITY_INVALID");if(o.effective_from&&o.effective_until&&Date.parse(o.effective_until)<Date.parse(o.effective_from))throw new Error("MULTI_SOURCE_EFFECTIVITY_INVALID");const identity=sourceIdentity(o),member=o.subject_binding.members.some(x=>x.representation_identity_ref===identity&&x.local_subject_ref===o.local_subject_ref);if(!member)throw new Error("MULTI_SOURCE_SUBJECT_BINDING_MISMATCH");if(o.subject_binding.canonical_subject&&o.subject_binding.canonical_subject.company_id!==scope.company_id)throw new Error("MULTI_SOURCE_SUBJECT_SCOPE_MISMATCH");if(o.source.kind==="PERSISTENT_REPRESENTATION"&&o.source.representation.company_id!==scope.company_id)throw new Error("MULTI_SOURCE_REPRESENTATION_SCOPE_MISMATCH");if(o.source.kind==="REQUEST_BOUND_AD_HOC"&&o.source.introduction.introduction_mode!=="REQUEST_BOUND_AD_HOC")throw new Error("MULTI_SOURCE_AD_HOC_INTRODUCTION_REQUIRED");if(o.claim.kind==="QUANTITY"&&!Number.isFinite(o.claim.value))throw new Error("MULTI_SOURCE_QUANTITY_INVALID");const c=coordinate(o),semantic_key=canonical(c),claim_digest=await sha({coordinate:c,claim:o.claim}),evidence_digest=await sha({observation_ref:o.observation_ref,source_identity_ref:identity,original_source_identity_ref:o.source.original_source_identity_ref,local_subject_ref:o.local_subject_ref,observed_at:o.observed_at,coordinate:c,claim:o.claim});const rels=input.representation_relationships.filter(x=>x.source_representation_id===identity||x.target_representation_id===identity);canonical_evidence.push(freeze({version:1,tenant_id:required(input.tenant_id,"MULTI_SOURCE_TENANT_REQUIRED"),company_id:scope.company_id,request_id:scope.request_id,scope_id:scope.scope_id,scope_digest:scope.scope_digest,evidence_as_of:asOf,evidence_ref:required(o.observation_ref,"MULTI_SOURCE_OBSERVATION_REF_REQUIRED"),evidence_digest,source_identity_ref:identity,source_namespace:required(o.source.original_source_identity_ref,"MULTI_SOURCE_ORIGINAL_SOURCE_REQUIRED"),semantic_key,claim_digest,evidence_role:o.evidence_role,canonical_subject_refs:o.subject_binding.canonical_subject?[o.subject_binding.canonical_subject.subject_id]:[],canonical_location_refs:c.location_refs,qualification_refs:refs(o.qualification_refs,"MULTI_SOURCE_QUALIFICATION_REQUIRED"),provenance_refs:refs([...o.provenance_refs,...o.subject_binding.provenance_refs],"MULTI_SOURCE_PROVENANCE_REQUIRED"),causal_lineage_refs:refs([...o.causal_lineage_refs,...o.subject_binding.causal_lineage_refs,o.subject_binding.binding_id,identity,o.source.original_source_identity_ref,...rels.flatMap(x=>[x.relationship_id,...x.causal_lineage_refs])],"MULTI_SOURCE_LINEAGE_REQUIRED")}))}
 const claim_relationships:GovernedClaimRelationshipArtifactV1[]=[];for(let i=0;i<observations.length;i++)for(let j=i+1;j<observations.length;j++){const a=observations[i]!,b=observations[j]!,sameBinding=a.subject_binding.binding_id===b.subject_binding.binding_id?a.subject_binding.outcome:"UNRESOLVED",temporal=bindingFor(a,b,input.temporal_bindings)?.outcome??"UNRESOLVED",semantically_comparable=sameBinding==="SAME_SUBJECT"&&temporal==="ALIGNED"&&canonical(coordinate(a))===canonical(coordinate(b));let relationship:GovernedClaimRelationshipV1="INSUFFICIENT_EVIDENCE";if(semantically_comparable)relationship=canonical(a.claim)===canonical(b.claim)?"CONSISTENT_COMPARABLE_CLAIM":"CONFLICTING_COMPARABLE_CLAIM";else if(sameBinding==="SAME_SUBJECT"&&(temporal==="ALIGNED"||temporal==="RELEVANT")&&canonical(coordinate(a))!==canonical(coordinate(b)))relationship="COMPLEMENTARY";const ia=sourceIdentity(a),ib=sourceIdentity(b),semantic={version:1 as const,left_observation_ref:a.observation_ref,right_observation_ref:b.observation_ref,relationship,subject_outcome:sameBinding,temporal_outcome:temporal,semantically_comparable,independence_established:independence(ia,ib,input.representation_relationships)};const relationship_digest=await sha(semantic);claim_relationships.push(freeze({...semantic,relationship_id:`governed-claim-relationship:sha256:${relationship_digest}`,relationship_digest,digest_algorithm:"SHA-256"as const,observational_only:true as const,grants_authority:false as const,grants_execution:false as const}))}
 const semantic={version:1 as const,alignment_kind:"MULTI_SOURCE_GOVERNED_REALITY_ALIGNMENT"as const,company_id:scope.company_id,scope_id:scope.scope_id,scope_digest:scope.scope_digest,evidence_as_of:asOf,canonical_evidence,claim_relationships,representation_relationship_refs:refs(input.representation_relationships.map(x=>x.relationship_id),"MULTI_SOURCE_RELATIONSHIP_REF_INVALID",true)};const alignment_digest=await sha(semantic);return freeze({...semantic,alignment_id:`multi-source-reality-alignment:sha256:${alignment_digest}`,alignment_digest,digest_algorithm:"SHA-256"as const,observational_only:true as const,tier_independent:true as const,recommended:false as const,executable:false as const,grants_authority:false as const,grants_execution:false as const})
}
