import type { OperationalSignalScopeBindingV1 } from "../cockpit/operational.signal.evaluation.scope.v1";
import { verifyOperationalSignalEvaluationScopeV1 } from "../cockpit/operational.signal.evaluation.scope.v1";
import type { GovernedOperationsFactV1 } from "../industrial/preservation/governed.operational.fact.preservation.v1";
import type { OperationalRealityEvidenceRoleV1 } from "./canonical.operational.reality.composition.v1";
import type { GovernedRepresentationObservationInputV1, GovernedSubjectBindingV1 } from "./governed.multi-source.reality.alignment.v1";
import type { GovernedOperationalRepresentationV1 } from "./governed.operational.representation.v1";

export type GovernedPersistentFactSemanticBindingV1=Readonly<{version:1;fact_ref:string;representation_id:string;dimension_ref:string;operational_state_ref:string;process_stage_ref?:string;location_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[];binding_id:string;binding_digest:string;digest_algorithm:"SHA-256";observational_only:true;grants_authority:false;grants_execution:false}>;

const forbidden=["authority","authority_tier","approval","execution","recommendation","confidence","source_rank","plan_role","representation_role"];
function required(v:string|undefined,c:string){const x=v?.trim();if(!x)throw new Error(c);return x}
function refs(v:readonly string[],c:string,empty=false){if(!Array.isArray(v))throw new Error(c);const x=[...new Set(v.map(y=>required(y,c)))].sort();if(!empty&&!x.length)throw new Error(c);return x}
function instant(v:string,c:string){const n=Date.parse(v);if(!Number.isFinite(n)||new Date(n).toISOString()!==v)throw new Error(c);return v}
function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return`{${Object.entries(v as Record<string,unknown>).filter(([,x])=>x!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(",")}}`;return JSON.stringify(v)}
async function sha(v:unknown){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(v)));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}
function freeze<T>(v:T):Readonly<T>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v as Record<string,unknown>).forEach(freeze);Object.freeze(v)}return v}
function safe(v:object){for(const k of forbidden)if(k in v)throw new Error("PERSISTENT_OBSERVATION_UNSAFE_SEMANTIC")}

export async function createGovernedPersistentFactSemanticBindingV1(input:Readonly<{version:1;fact_ref:string;representation_id:string;dimension_ref:string;operational_state_ref:string;process_stage_ref?:string;location_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[]}>):Promise<GovernedPersistentFactSemanticBindingV1>{
 safe(input as object);if(input.version!==1)throw new Error("PERSISTENT_OBSERVATION_BINDING_VERSION_UNSUPPORTED");const value={version:1 as const,fact_ref:required(input.fact_ref,"PERSISTENT_OBSERVATION_FACT_REF_REQUIRED"),representation_id:required(input.representation_id,"PERSISTENT_OBSERVATION_REPRESENTATION_REQUIRED"),dimension_ref:required(input.dimension_ref,"PERSISTENT_OBSERVATION_DIMENSION_REQUIRED"),operational_state_ref:required(input.operational_state_ref,"PERSISTENT_OBSERVATION_STATE_REQUIRED"),...(input.process_stage_ref?{process_stage_ref:required(input.process_stage_ref,"PERSISTENT_OBSERVATION_STAGE_INVALID")}:{ }),location_refs:refs(input.location_refs,"PERSISTENT_OBSERVATION_LOCATION_INVALID",true),qualification_refs:refs(input.qualification_refs,"PERSISTENT_OBSERVATION_QUALIFICATION_REQUIRED"),provenance_refs:refs(input.provenance_refs,"PERSISTENT_OBSERVATION_PROVENANCE_REQUIRED"),causal_lineage_refs:refs(input.causal_lineage_refs,"PERSISTENT_OBSERVATION_LINEAGE_REQUIRED")};const binding_digest=await sha(value);return freeze({...value,binding_id:`governed-persistent-fact-semantic-binding:sha256:${binding_digest}`,binding_digest,digest_algorithm:"SHA-256"as const,observational_only:true as const,grants_authority:false as const,grants_execution:false as const})
}

async function verifyRepresentation(r:GovernedOperationalRepresentationV1){
 const identity={version:r.version,representation_ref:r.representation_ref,company_id:r.company_id,domain_ref:r.domain_ref,governed_scope_refs:r.governed_scope_refs,subject_refs:r.subject_refs,observability:r.observability,refreshability:r.refreshability,refresh_policy_ref:r.refresh_policy_ref},digest=await sha(identity);if(r.version!==1||r.observability!=="PERSISTENT"||r.refreshability!=="INDEPENDENTLY_REFRESHABLE"||r.representation_digest!==digest||r.representation_id!==`governed-operational-representation:sha256:${digest}`)throw new Error("PERSISTENT_OBSERVATION_REPRESENTATION_INVALID");const semantic={...identity,representation_id:r.representation_id,representation_digest:r.representation_digest,source_binding_refs:r.source_binding_refs,provenance_refs:r.provenance_refs,causal_lineage_refs:r.causal_lineage_refs};if(r.artifact_digest!==await sha(semantic)||r.digest_algorithm!=="SHA-256"||r.observational_only!==true||r.grants_authority!==false||r.grants_execution!==false)throw new Error("PERSISTENT_OBSERVATION_REPRESENTATION_INVALID")
}
async function verifyBinding(b:GovernedPersistentFactSemanticBindingV1){const value={version:b.version,fact_ref:b.fact_ref,representation_id:b.representation_id,dimension_ref:b.dimension_ref,operational_state_ref:b.operational_state_ref,...(b.process_stage_ref?{process_stage_ref:b.process_stage_ref}:{}),location_refs:b.location_refs,qualification_refs:b.qualification_refs,provenance_refs:b.provenance_refs,causal_lineage_refs:b.causal_lineage_refs},digest=await sha(value);if(b.binding_digest!==digest||b.binding_id!==`governed-persistent-fact-semantic-binding:sha256:${digest}`||b.digest_algorithm!=="SHA-256"||b.observational_only!==true||b.grants_authority!==false||b.grants_execution!==false)throw new Error("PERSISTENT_OBSERVATION_BINDING_INVALID")}
function role(f:GovernedOperationsFactV1):OperationalRealityEvidenceRoleV1{return f.semantic.family==="ORDERS"?"CURRENT_PLAN":f.semantic.family==="PRODUCTION_ORDERS"?"PLANNED_PRODUCTION":f.semantic.family==="INVENTORY"?"CURRENT_FACT":f.semantic.family==="MOVEMENTS"||f.semantic.family==="MATERIAL_MOVEMENTS"?"REALIZED_EVENT":(()=>{throw new Error("PERSISTENT_OBSERVATION_FACT_FAMILY_UNSUPPORTED")})()}
function temporal(f:GovernedOperationsFactV1){const s=f.semantic;if(s.family==="ORDERS")return{observed_at:instant(s.observed_at,"PERSISTENT_OBSERVATION_TIME_INVALID"),effective_from:instant(s.effective_at,"PERSISTENT_OBSERVATION_TIME_INVALID")};if(s.family==="INVENTORY")return{observed_at:instant(s.observed_at,"PERSISTENT_OBSERVATION_TIME_INVALID"),effective_from:instant(s.observed_at,"PERSISTENT_OBSERVATION_TIME_INVALID")};if(s.family==="MOVEMENTS"||s.family==="MATERIAL_MOVEMENTS")return{observed_at:instant(s.occurred_at,"PERSISTENT_OBSERVATION_TIME_INVALID"),effective_from:instant(s.occurred_at,"PERSISTENT_OBSERVATION_TIME_INVALID")};if(s.family==="PRODUCTION_ORDERS")return{observed_at:instant(f.provenance.acquired_at,"PERSISTENT_OBSERVATION_TIME_INVALID"),effective_from:instant(s.scheduled_at,"PERSISTENT_OBSERVATION_TIME_INVALID")};throw new Error("PERSISTENT_OBSERVATION_FACT_FAMILY_UNSUPPORTED")}
function claim(f:GovernedOperationsFactV1){const s=f.semantic;if(s.family==="MASTER_BOM")throw new Error("PERSISTENT_OBSERVATION_FACT_FAMILY_UNSUPPORTED");return{kind:"QUANTITY"as const,value:s.quantity.value,unit_ref:`unit:${s.quantity.canonical_unit??s.quantity.source_unit}`}}
function primaryRole(f:GovernedOperationsFactV1){const value=f.role_bindings.observation??f.role_bindings.plan_element;if(!value)throw new Error("PERSISTENT_OBSERVATION_ROLE_BINDING_REQUIRED");return value}

export async function bridgeGovernedPersistentSourceFactV1(input:Readonly<{version:1;fact:GovernedOperationsFactV1;representation:GovernedOperationalRepresentationV1;evaluation_scope:OperationalSignalScopeBindingV1;subject_binding:GovernedSubjectBindingV1;semantic_binding:GovernedPersistentFactSemanticBindingV1}>):Promise<GovernedRepresentationObservationInputV1>{
 safe(input as object);if(input.version!==1)throw new Error("PERSISTENT_OBSERVATION_BRIDGE_VERSION_UNSUPPORTED");await Promise.all([verifyRepresentation(input.representation),verifyBinding(input.semantic_binding),verifyOperationalSignalEvaluationScopeV1(input.evaluation_scope.scope,input.evaluation_scope.scope)]);const{fact,representation:r,evaluation_scope:e,subject_binding:s,semantic_binding:b}=input,scope=e.scope;if(r.company_id!==scope.company_id||r.domain_ref!==fact.domain_ref||!r.governed_scope_refs.includes(scope.scope_id)||!r.subject_refs.includes(fact.role_bindings.subject.subject_id)||fact.role_bindings.subject.company_id!==scope.company_id)throw new Error("PERSISTENT_OBSERVATION_SCOPE_MISMATCH");if(b.fact_ref!==fact.fact_id||b.representation_id!==r.representation_id)throw new Error("PERSISTENT_OBSERVATION_BINDING_MISMATCH");if(!r.source_binding_refs.some(x=>x===fact.provenance.connector_identity_id||x===fact.provenance.source_representation||x===fact.provenance.source_system))throw new Error("PERSISTENT_OBSERVATION_SOURCE_BINDING_MISMATCH");if(!s.members.some(x=>x.representation_identity_ref===r.representation_id&&x.local_subject_ref===fact.source_fact_ref)||s.canonical_subject?.subject_id!==fact.role_bindings.subject.subject_id)throw new Error("PERSISTENT_OBSERVATION_SUBJECT_BINDING_MISMATCH");const pr=primaryRole(fact);return freeze({version:1,observation_ref:fact.fact_id,source:{kind:"PERSISTENT_REPRESENTATION",representation:r,original_source_identity_ref:fact.provenance.source_system},local_subject_ref:fact.source_fact_ref,subject_binding:s,...temporal(fact),dimension_ref:b.dimension_ref,operational_state_ref:b.operational_state_ref,...(b.process_stage_ref?{process_stage_ref:b.process_stage_ref}:{}),evidence_role:role(fact),claim:claim(fact),location_refs:b.location_refs,qualification_refs:refs([...b.qualification_refs,...("qualification_ref"in pr?[pr.qualification_ref]:pr.evidence_refs)],"PERSISTENT_OBSERVATION_QUALIFICATION_REQUIRED"),provenance_refs:refs([...b.provenance_refs,...pr.provenance_refs,...r.provenance_refs],"PERSISTENT_OBSERVATION_PROVENANCE_REQUIRED"),causal_lineage_refs:refs([...b.causal_lineage_refs,...pr.causal_lineage_refs,...r.causal_lineage_refs,fact.fact_id,fact.fact_digest,scope.source_snapshot_ref],"PERSISTENT_OBSERVATION_LINEAGE_REQUIRED")})
}
