import { verifyOperationsProtectedObjectiveSetV1, type OperationsProtectedObjectiveSetV1 } from "../industrial/cognition/operations.protected.objective.set.v1";
import { verifyGovernedPlanRealityElementMaterialityV1, type GovernedPlanRealityElementMaterialityV1 } from "./plan.reality.materiality.policy.v1";

export type GovernedScopeRealityAlignmentV1="ALIGNED"|"DRIFTING"|"MISALIGNED";
export type GovernedScopeRealityAlignmentAggregationV1=Readonly<{version:1;policy_ref:"policy:governed-scope-reality-alignment-aggregation-v1";objective_set_ref:string;objective_set_digest:string;current_plan_context_ref:string;current_plan_context_digest:string;request_id:string;company_id:string;scope_id:string;scope_digest:string;evidence_as_of:string;assertability:"ASSERTABLE"|"NOT_ASSERTABLE";alignment?:GovernedScopeRealityAlignmentV1;reason:"ALL_REQUIRED_OBJECTIVES_ALIGNED"|"REQUIRED_RECOVERABLE_DEVIATION"|"REQUIRED_MATERIAL_INCOMPATIBILITY"|"REQUIRED_OBJECTIVE_UNRESOLVED";required_objective_count:number;evaluated_objective_count:number;element_materiality_refs:readonly string[];conjunctive_required_objectives:true;complete_objective_coverage:true;source_count_independent:true;observation_breadth_independent:true;decision_pressure_independent:true;intrinsic_reality_state_independent:true;evidence_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[];aggregation_id:string;aggregation_digest:string;digest_algorithm:"SHA-256";observational_only:true;recommended:false;executable:false;grants_authority:false;grants_execution:false}>;

function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return`{${Object.entries(v as Record<string,unknown>).filter(([,x])=>x!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(",")}}`;return JSON.stringify(v)}
async function sha(v:unknown){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(v)));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}
function freeze<T>(v:T):Readonly<T>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v as Record<string,unknown>).forEach(freeze);Object.freeze(v)}return v}
function refs(v:readonly string[]){return Object.freeze([...new Set(v.map(x=>x.trim()).filter(Boolean))].sort())}

export async function aggregateGovernedScopeRealityAlignmentV1(input:Readonly<{version:1;objective_set:OperationsProtectedObjectiveSetV1;element_materialities:readonly GovernedPlanRealityElementMaterialityV1[]}>):Promise<GovernedScopeRealityAlignmentAggregationV1>{
 if(input.version!==1)throw new Error("PLAN_REALITY_SCOPE_AGGREGATION_VERSION_UNSUPPORTED");await verifyOperationsProtectedObjectiveSetV1(input.objective_set);await Promise.all(input.element_materialities.map(verifyGovernedPlanRealityElementMaterialityV1));const set=input.objective_set;if(input.element_materialities.length!==set.members.length)throw new Error("PLAN_REALITY_SCOPE_OBJECTIVE_COVERAGE_INCOMPLETE");const byBinding=new Map(set.members.map(x=>[x.objective_binding_ref,x]as const)),seen=new Set<string>();for(const m of input.element_materialities){if(!m.protected_objective_ref)throw new Error("PLAN_REALITY_SCOPE_NORMATIVE_OBJECTIVE_REQUIRED");const member=byBinding.get(m.protected_objective_ref);if(!member||seen.has(m.protected_objective_ref))throw new Error("PLAN_REALITY_SCOPE_OBJECTIVE_SUBSTITUTION");if(m.plan_element_ref!==member.plan_element_ref||m.protected_objective_digest!==member.objective_binding_digest||m.request_id!==set.request_id||m.company_id!==set.company_id||m.scope_id!==member.objective_scope_id||m.scope_digest!==member.objective_scope_digest||m.evidence_as_of!==set.evidence_as_of)throw new Error("PLAN_REALITY_SCOPE_ELEMENT_CONTEXT_MISMATCH");seen.add(m.protected_objective_ref)}if(seen.size!==set.members.length)throw new Error("PLAN_REALITY_SCOPE_OBJECTIVE_COVERAGE_INCOMPLETE");
 const unresolved=input.element_materialities.some(x=>x.disposition==="NOT_ASSERTABLE"||x.disposition==="DEVIATION_RECOVERABILITY_UNRESOLVED"),misaligned=input.element_materialities.some(x=>x.supports_element_misalignment),drifting=input.element_materialities.some(x=>x.supports_element_drifting),allAligned=input.element_materialities.every(x=>x.supports_element_alignment);let assertability:"ASSERTABLE"|"NOT_ASSERTABLE"="NOT_ASSERTABLE",alignment:GovernedScopeRealityAlignmentV1|undefined,reason:GovernedScopeRealityAlignmentAggregationV1["reason"]="REQUIRED_OBJECTIVE_UNRESOLVED";if(!unresolved){if(misaligned){assertability="ASSERTABLE";alignment="MISALIGNED";reason="REQUIRED_MATERIAL_INCOMPATIBILITY"}else if(drifting){assertability="ASSERTABLE";alignment="DRIFTING";reason="REQUIRED_RECOVERABLE_DEVIATION"}else if(allAligned){assertability="ASSERTABLE";alignment="ALIGNED";reason="ALL_REQUIRED_OBJECTIVES_ALIGNED"}}
 const ordered=[...input.element_materialities].sort((a,b)=>a.protected_objective_ref!.localeCompare(b.protected_objective_ref!)),evidence_refs=refs([...set.evidence_refs,...ordered.flatMap(x=>x.evidence_refs)]),qualification_refs=refs([...set.qualification_refs,...ordered.flatMap(x=>x.qualification_refs)]),provenance_refs=refs([...set.provenance_refs,...ordered.flatMap(x=>x.provenance_refs)]),causal_lineage_refs=refs([...set.causal_lineage_refs,...ordered.flatMap(x=>x.causal_lineage_refs),set.objective_set_id,...ordered.map(x=>x.materiality_id)]),semantic={version:1 as const,policy_ref:"policy:governed-scope-reality-alignment-aggregation-v1"as const,objective_set_ref:set.objective_set_id,objective_set_digest:set.objective_set_digest,current_plan_context_ref:set.current_plan_context_ref,current_plan_context_digest:set.current_plan_context_digest,request_id:set.request_id,company_id:set.company_id,scope_id:set.scope_id,scope_digest:set.scope_digest,evidence_as_of:set.evidence_as_of,assertability,...(alignment?{alignment}:{}),reason,required_objective_count:set.member_count,evaluated_objective_count:ordered.length,element_materiality_refs:Object.freeze(ordered.map(x=>x.materiality_id)),conjunctive_required_objectives:true as const,complete_objective_coverage:true as const,source_count_independent:true as const,observation_breadth_independent:true as const,decision_pressure_independent:true as const,intrinsic_reality_state_independent:true as const,evidence_refs,qualification_refs,provenance_refs,causal_lineage_refs},aggregation_digest=await sha(semantic);return freeze({...semantic,aggregation_id:`governed-scope-reality-alignment-aggregation:sha256:${aggregation_digest}`,aggregation_digest,digest_algorithm:"SHA-256"as const,observational_only:true as const,recommended:false as const,executable:false as const,grants_authority:false as const,grants_execution:false as const})
}
