export type CanonicalOperationalEvidenceRoleV1 = "PLAN_ELEMENT" | "PLAN_RELATIONSHIP" | "BASELINE" | "OBSERVATION" | "BEHAVIORAL_EVENT" | "STRUCTURAL_RELATIONSHIP" | "DEVIATION" | "CONSEQUENCE" | "TEMPORAL_REQUIREMENT" | "TEMPORAL_AVAILABILITY" | "CORRECTIVE_OPTION";
export type OperationalEvidenceModalityV1 = "SNAPSHOT" | "BEHAVIORAL" | "STRUCTURAL";
export type GenericTemporalRoleV1 = "REQUIREMENT_DEADLINE" | "FULFILLMENT_EXPECTATION" | "CONSEQUENCE_EVENT" | "MARGIN_EVIDENCE" | "OPTION_EVENT";

export type OperationalDomainEvidenceProfileInputV1 = Readonly<{ version: 1; profile_ref: string; domain_ref: string; profile_version: string; supported_subject_kinds: readonly string[]; evidence_mappings: readonly Readonly<{ evidence_kind: string; role: CanonicalOperationalEvidenceRoleV1; modality: OperationalEvidenceModalityV1 }>[]; relationship_family_ref: string; consequence_family_ref?: string }>;
export type OperationalDomainEvidenceProfileV1 = OperationalDomainEvidenceProfileInputV1 & Readonly<{ profile_id: string; profile_digest: string; digest_algorithm: "SHA-256"; declarative_only: true; grants_execution: false }>;
export type OperationalSubjectRefInputV1 = Readonly<{ version: 1; tenant_id?: string; company_id: string; profile: OperationalDomainEvidenceProfileV1; subject_kind: string; subject_ref: string }>;
export type OperationalSubjectRefV1 = Readonly<{ version: 1; tenant_id?: string; company_id: string; domain_ref: string; profile_ref: string; profile_digest: string; subject_kind: string; subject_ref: string; subject_id: string; subject_digest: string; digest_algorithm: "SHA-256"; grants_execution: false }>;

type RoleBase = Readonly<{ version: 1; subject: OperationalSubjectRefV1; scope_ref: string; evidence_refs: readonly string[]; provenance_refs: readonly string[]; causal_lineage_refs: readonly string[] }>;
type RoleOutput = Readonly<{ role_id: string; role_digest: string; digest_algorithm: "SHA-256"; observational_only: true; grants_execution: false; grants_authority: false }>;
export type OperationalPlanElementRefV1 = RoleBase & RoleOutput & Readonly<{ role: "PLAN_ELEMENT"; plan_element_ref: string }>;
export type OperationalPlanRelationshipRefV1 = RoleBase & RoleOutput & Readonly<{ role: "PLAN_RELATIONSHIP"; relationship_ref: string; relationship_kind_ref: string; source_plan_element_ref: string; target_plan_element_ref: string }>;
export type ExpectedOperationalStateRefV1 = RoleBase & RoleOutput & Readonly<{ role: "BASELINE"; baseline_ref: string }>;
export type OperationalObservationRefV1 = RoleBase & RoleOutput & Readonly<{ role: "OBSERVATION"; observation_ref: string; observed_at: string; effective_at: string; qualification_ref: string }>;
export type OperationalDeviationRefV1 = RoleBase & RoleOutput & Readonly<{ role: "DEVIATION"; deviation_ref: string; baseline_role_ref: string; observation_role_ref: string }>;
export type MaterialOperationalConsequenceRefV1 = RoleBase & RoleOutput & Readonly<{ role: "CONSEQUENCE"; consequence_ref: string; consequence_kind_ref: string; materiality_ref: string }>;
export type CorrectiveOperationalOptionRefV1 = RoleBase & RoleOutput & Readonly<{ role: "CORRECTIVE_OPTION"; corrective_option_ref: string }>;
export type GenericOperationalTemporalRefV1 = RoleBase & RoleOutput & Readonly<{ role: "TEMPORAL"; temporal_ref: string; temporal_role: GenericTemporalRoleV1; authoritative_time_ref?: string }>;
export type OperationalCausalChainV1 = Readonly<{ version: 1; chain_id: string; chain_digest: string; scope_ref: string; ordered_role_refs: readonly string[]; evidence_refs: readonly string[]; digest_algorithm: "SHA-256"; observational_only: true; grants_execution: false }>;

const roles = new Set<string>(["PLAN_ELEMENT","PLAN_RELATIONSHIP","BASELINE","OBSERVATION","BEHAVIORAL_EVENT","STRUCTURAL_RELATIONSHIP","DEVIATION","CONSEQUENCE","TEMPORAL_REQUIREMENT","TEMPORAL_AVAILABILITY","CORRECTIVE_OPTION"]);
const modalities = new Set<string>(["SNAPSHOT","BEHAVIORAL","STRUCTURAL"]);
const temporalRoles = new Set<string>(["REQUIREMENT_DEADLINE","FULFILLMENT_EXPECTATION","CONSEQUENCE_EVENT","MARGIN_EVIDENCE","OPTION_EVENT"]);
function ref(value: string | undefined, code: string): string { const v=value?.trim(); if(!v||!/^[A-Za-z0-9][A-Za-z0-9._-]*:[^\s]+$/.test(v)) throw new Error(code); return v; }
function token(value: string | undefined, code: string): string { const v=value?.trim(); if(!v||!/^[A-Z][A-Z0-9_]{0,63}$/.test(v)) throw new Error(code); return v; }
function refs(values: readonly string[], code: string, required=true): readonly string[] { if(!Array.isArray(values)) throw new Error(code); const v=[...new Set(values.map(x=>ref(x,code)))].sort(); if(required&&!v.length) throw new Error(code); return v; }
function canonical(value: unknown): string { if(Array.isArray(value))return`[${value.map(canonical).join(",")}]`;if(value&&typeof value==="object"){const e=Object.entries(value as Record<string,unknown>).filter(([,v])=>v!==undefined).sort(([a],[b])=>a.localeCompare(b));return`{${e.map(([k,v])=>`${JSON.stringify(k)}:${canonical(v)}`).join(",")}}`;}return JSON.stringify(value); }
async function sha(value: unknown): Promise<string>{const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(value)));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("");}
function freeze<T>(v:T):Readonly<T>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v as Record<string,unknown>).forEach(freeze);Object.freeze(v);}return v;}

export async function createOperationalDomainEvidenceProfileV1(input: OperationalDomainEvidenceProfileInputV1): Promise<OperationalDomainEvidenceProfileV1>{if(input.version!==1)throw new Error("PROFILE_VERSION_UNSUPPORTED");const kinds=[...new Set(input.supported_subject_kinds.map(x=>token(x,"PROFILE_SUBJECT_KIND_INVALID")))].sort();if(!kinds.length||kinds.length!==input.supported_subject_kinds.length)throw new Error("PROFILE_SUBJECT_KINDS_INVALID");const seen=new Set<string>();const mappings=input.evidence_mappings.map(m=>{const kind=token(m.evidence_kind,"PROFILE_EVIDENCE_KIND_INVALID");if(seen.has(kind)||!roles.has(m.role)||!modalities.has(m.modality))throw new Error("PROFILE_EVIDENCE_MAPPING_INVALID");seen.add(kind);return{evidence_kind:kind,role:m.role,modality:m.modality};}).sort((a,b)=>a.evidence_kind.localeCompare(b.evidence_kind));const semantic={version:1 as const,profile_ref:ref(input.profile_ref,"PROFILE_REF_INVALID"),domain_ref:ref(input.domain_ref,"PROFILE_DOMAIN_INVALID"),profile_version:input.profile_version.trim(),supported_subject_kinds:kinds,evidence_mappings:mappings,relationship_family_ref:ref(input.relationship_family_ref,"PROFILE_RELATIONSHIP_FAMILY_INVALID"),...(input.consequence_family_ref?{consequence_family_ref:ref(input.consequence_family_ref,"PROFILE_CONSEQUENCE_FAMILY_INVALID")}:{})};if(!semantic.profile_version)throw new Error("PROFILE_VERSION_INVALID");const d=await sha(semantic);return freeze({...semantic,profile_id:`operational-domain-profile:sha256:${d}`,profile_digest:d,digest_algorithm:"SHA-256",declarative_only:true,grants_execution:false});}
export async function createOperationalSubjectRefV1(input: OperationalSubjectRefInputV1): Promise<OperationalSubjectRefV1>{if(input.version!==1)throw new Error("SUBJECT_VERSION_UNSUPPORTED");const kind=token(input.subject_kind,"SUBJECT_KIND_INVALID");if(!input.profile.supported_subject_kinds.includes(kind))throw new Error("SUBJECT_KIND_NOT_GOVERNED_BY_PROFILE");const semantic={version:1 as const,...(input.tenant_id?{tenant_id:ref(input.tenant_id,"SUBJECT_TENANT_INVALID")}:{ }),company_id:ref(input.company_id,"SUBJECT_COMPANY_INVALID"),domain_ref:input.profile.domain_ref,profile_ref:input.profile.profile_ref,profile_digest:input.profile.profile_digest,subject_kind:kind,subject_ref:ref(input.subject_ref,"SUBJECT_REF_INVALID")};const d=await sha(semantic);return freeze({...semantic,subject_id:`operational-subject:sha256:${d}`,subject_digest:d,digest_algorithm:"SHA-256",grants_execution:false});}
type BaseInput={version:1;subject:OperationalSubjectRefV1;scope_ref:string;evidence_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[]};
async function roleArtifact<T extends object>(name:string,base:BaseInput,detail:T):Promise<BaseInput&T&RoleOutput>{if(base.version!==1)throw new Error("ROLE_VERSION_UNSUPPORTED");const normalized={...base,scope_ref:ref(base.scope_ref,"ROLE_SCOPE_INVALID"),evidence_refs:refs(base.evidence_refs,"ROLE_EVIDENCE_REQUIRED"),provenance_refs:refs(base.provenance_refs,"ROLE_PROVENANCE_REQUIRED"),causal_lineage_refs:refs(base.causal_lineage_refs,"ROLE_LINEAGE_REQUIRED"),...detail};const d=await sha(normalized);return freeze({...normalized,role_id:`operational-role:${name}:sha256:${d}`,role_digest:d,digest_algorithm:"SHA-256",observational_only:true,grants_execution:false,grants_authority:false});}
export const createOperationalPlanElementRefV1=(i:BaseInput&{plan_element_ref:string})=>roleArtifact("plan-element",i,{role:"PLAN_ELEMENT" as const,plan_element_ref:ref(i.plan_element_ref,"PLAN_ELEMENT_REF_INVALID")}) as Promise<OperationalPlanElementRefV1>;
export const createOperationalPlanRelationshipRefV1=(i:BaseInput&{relationship_ref:string;relationship_kind_ref:string;source_plan_element_ref:string;target_plan_element_ref:string})=>roleArtifact("plan-relationship",i,{role:"PLAN_RELATIONSHIP" as const,relationship_ref:ref(i.relationship_ref,"PLAN_RELATIONSHIP_REF_INVALID"),relationship_kind_ref:ref(i.relationship_kind_ref,"PLAN_RELATIONSHIP_KIND_INVALID"),source_plan_element_ref:ref(i.source_plan_element_ref,"PLAN_RELATIONSHIP_SOURCE_INVALID"),target_plan_element_ref:ref(i.target_plan_element_ref,"PLAN_RELATIONSHIP_TARGET_INVALID")}) as Promise<OperationalPlanRelationshipRefV1>;
export const createExpectedOperationalStateRefV1=(i:BaseInput&{baseline_ref:string})=>roleArtifact("baseline",i,{role:"BASELINE" as const,baseline_ref:ref(i.baseline_ref,"BASELINE_REF_INVALID")}) as Promise<ExpectedOperationalStateRefV1>;
export const createOperationalObservationRefV1=(i:BaseInput&{observation_ref:string;observed_at:string;effective_at:string;qualification_ref:string})=>{if(!Number.isFinite(Date.parse(i.observed_at))||!Number.isFinite(Date.parse(i.effective_at)))throw new Error("OBSERVATION_TIME_INVALID");return roleArtifact("observation",i,{role:"OBSERVATION" as const,observation_ref:ref(i.observation_ref,"OBSERVATION_REF_INVALID"),observed_at:i.observed_at,effective_at:i.effective_at,qualification_ref:ref(i.qualification_ref,"OBSERVATION_QUALIFICATION_INVALID")}) as Promise<OperationalObservationRefV1>;};
export const createOperationalDeviationRefV1=(i:BaseInput&{deviation_ref:string;baseline_role_ref:string;observation_role_ref:string})=>roleArtifact("deviation",i,{role:"DEVIATION" as const,deviation_ref:ref(i.deviation_ref,"DEVIATION_REF_INVALID"),baseline_role_ref:ref(i.baseline_role_ref,"DEVIATION_BASELINE_INVALID"),observation_role_ref:ref(i.observation_role_ref,"DEVIATION_OBSERVATION_INVALID")}) as Promise<OperationalDeviationRefV1>;
export const createMaterialOperationalConsequenceRefV1=(i:BaseInput&{consequence_ref:string;consequence_kind_ref:string;materiality_ref:string})=>roleArtifact("consequence",i,{role:"CONSEQUENCE" as const,consequence_ref:ref(i.consequence_ref,"CONSEQUENCE_REF_INVALID"),consequence_kind_ref:ref(i.consequence_kind_ref,"CONSEQUENCE_KIND_INVALID"),materiality_ref:ref(i.materiality_ref,"CONSEQUENCE_MATERIALITY_INVALID")}) as Promise<MaterialOperationalConsequenceRefV1>;
export const createCorrectiveOperationalOptionRefV1=(i:BaseInput&{corrective_option_ref:string})=>roleArtifact("corrective-option",i,{role:"CORRECTIVE_OPTION" as const,corrective_option_ref:ref(i.corrective_option_ref,"CORRECTIVE_OPTION_REF_INVALID")}) as Promise<CorrectiveOperationalOptionRefV1>;
export const createGenericOperationalTemporalRefV1=(i:BaseInput&{temporal_ref:string;temporal_role:GenericTemporalRoleV1;authoritative_time_ref?:string})=>{if(!temporalRoles.has(i.temporal_role))throw new Error("TEMPORAL_ROLE_INVALID");return roleArtifact("temporal",i,{role:"TEMPORAL" as const,temporal_ref:ref(i.temporal_ref,"TEMPORAL_REF_INVALID"),temporal_role:i.temporal_role,...(i.authoritative_time_ref?{authoritative_time_ref:ref(i.authoritative_time_ref,"TEMPORAL_TIME_REF_INVALID")}:{})}) as Promise<GenericOperationalTemporalRefV1>;};
export async function createOperationalCausalChainV1(input:Readonly<{version:1;scope_ref:string;ordered_role_refs:readonly string[];evidence_refs:readonly string[]}>):Promise<OperationalCausalChainV1>{if(input.version!==1)throw new Error("CAUSAL_CHAIN_VERSION_UNSUPPORTED");const semantic={version:1 as const,scope_ref:ref(input.scope_ref,"CAUSAL_CHAIN_SCOPE_INVALID"),ordered_role_refs:input.ordered_role_refs.map(x=>ref(x,"CAUSAL_CHAIN_ROLE_INVALID")),evidence_refs:refs(input.evidence_refs,"CAUSAL_CHAIN_EVIDENCE_REQUIRED")};if(semantic.ordered_role_refs.length<2)throw new Error("CAUSAL_CHAIN_TOO_SHORT");const d=await sha(semantic);return freeze({...semantic,chain_id:`operational-causal-chain:sha256:${d}`,chain_digest:d,digest_algorithm:"SHA-256",observational_only:true,grants_execution:false});}
export function resolveOperationalEvidenceRoleV1(profile:OperationalDomainEvidenceProfileV1,evidenceKind:string){const mapping=profile.evidence_mappings.find(x=>x.evidence_kind===evidenceKind);if(!mapping)throw new Error("EVIDENCE_ROLE_MAPPING_UNSUPPORTED");return mapping;}

export const createOperationsEvidenceProfileV1 = () => createOperationalDomainEvidenceProfileV1({version:1,profile_ref:"profile:operations-v1",domain_ref:"domain:operations",profile_version:"1",supported_subject_kinds:["SKU","ORDER","SUPPLIER"],relationship_family_ref:"relationship-family:operations-v1",consequence_family_ref:"consequence-family:operations-pressure-v1",evidence_mappings:[
  {evidence_kind:"PLAN_ORDER",role:"PLAN_ELEMENT",modality:"SNAPSHOT"},{evidence_kind:"ORDER_RELATIONSHIP",role:"PLAN_RELATIONSHIP",modality:"STRUCTURAL"},{evidence_kind:"PLAN_BOM_EDGE",role:"STRUCTURAL_RELATIONSHIP",modality:"STRUCTURAL"},{evidence_kind:"AUTHORITATIVE_MASTER_BOM",role:"STRUCTURAL_RELATIONSHIP",modality:"STRUCTURAL"},{evidence_kind:"OPERATIONAL_TOPOLOGY",role:"STRUCTURAL_RELATIONSHIP",modality:"STRUCTURAL"},{evidence_kind:"MOVEMENT_EVENT",role:"BEHAVIORAL_EVENT",modality:"BEHAVIORAL"},{evidence_kind:"INVENTORY_SNAPSHOT",role:"OBSERVATION",modality:"SNAPSHOT"},{evidence_kind:"REALITY_ASSESSMENT",role:"OBSERVATION",modality:"SNAPSHOT"},{evidence_kind:"PROCESS_INSTABILITY_ASSESSMENT",role:"DEVIATION",modality:"BEHAVIORAL"},{evidence_kind:"BOM_DIVERGENCE_ASSESSMENT",role:"DEVIATION",modality:"STRUCTURAL"},{evidence_kind:"INVENTORY_RECONCILIATION_RESULT",role:"DEVIATION",modality:"SNAPSHOT"},{evidence_kind:"EXECUTION_GAP_ASSESSMENT",role:"DEVIATION",modality:"BEHAVIORAL"},{evidence_kind:"OPTIMIZER_SHORTAGE_RESULT",role:"DEVIATION",modality:"SNAPSHOT"}
]});
