import type { OperationalSignalScopeBindingV1 } from "../cockpit/operational.signal.evaluation.scope.v1";
import { verifyOperationalSignalEvaluationScopeV1 } from "../cockpit/operational.signal.evaluation.scope.v1";
import type { GovernedInterventionAdmissibilityStatusV1, GovernedChangeabilityStatusV1 } from "../decision/governed.intervention.discovery.policy.v1";
import type { CanonicalDomainContextBindingV1 } from "./canonical.domain.context.v1";
import { verifyCanonicalDomainContextBindingV1 } from "./canonical.domain.context.v1";
import type { GovernedBoundedPerturbationV1 } from "./qualified.causal.evaluation.v1";
import { verifyGovernedBoundedPerturbationV1 } from "./qualified.causal.evaluation.v1";

export type GovernedConstraintResultStatusV1="SATISFIED"|"VIOLATED"|"UNRESOLVED"|"INSUFFICIENT_EVIDENCE";
export type GovernedConstraintApplicabilityV1="APPLICABLE"|"NOT_APPLICABLE"|"UNRESOLVED"|"INSUFFICIENT_EVIDENCE";
export type GovernedConstraintRoleV1="HARD"|"NON_BLOCKING";
type Boundary=Readonly<{digest_algorithm:"SHA-256";observational_only:true;recommended:false;selected:false;executable:false;grants_authority:false;grants_execution:false;grants_remediation:false;company_global_claim:false}>;
type Evidence=Readonly<{evidence_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];causal_lineage_refs:readonly string[];evidence_as_of:string;evaluated_at:string}>;

export type GovernedCurrentChangeabilityResultV1=Readonly<{
 version:1;request_id:string;company_id:string;scope_id:string;scope_digest:string;evidence_selection_ref:string;
 domain_context_ref:string;domain_context_digest:string;domain_ref:string;domain_profile_ref:string;domain_profile_version:string;
 dimension_ref:string;governed_relationship_ref:string;current_state_ref:string;governing_condition_ref:string;
 protected_objective_ref?:string;material_consequence_ref?:string;trajectory_ref?:string;
 boundary_policy_ref:string;boundary_policy_version:string;boundary_determination_ref:string;boundary_result_evidence_refs:readonly string[];
 changeability_status:GovernedChangeabilityStatusV1;epistemic_basis:"DETERMINISTIC_CURRENT_STATE";
 changeability_id:string;changeability_digest:string;current_fact:true;
}>&Evidence&Boundary;

export type GovernedCurrentConstraintResultV1=Readonly<{
 version:1;request_id:string;company_id:string;scope_id:string;scope_digest:string;evidence_selection_ref:string;
 domain_context_ref:string;domain_context_digest:string;domain_ref:string;domain_profile_ref:string;domain_profile_version:string;
 perturbation_ref:string;perturbation_digest:string;constraint_family_key:string;constraint_policy_ref:string;constraint_policy_version:string;
 applicability:GovernedConstraintApplicabilityV1;constraint_role?:GovernedConstraintRoleV1;result_status?:GovernedConstraintResultStatusV1;
 current_operand_refs:readonly string[];bound_refs:readonly string[];determination_ref:string;
 epistemic_basis:"DETERMINISTIC_CURRENT_CONSTRAINT_EVALUATION";constraint_result_id:string;constraint_result_digest:string;
 current_evidence_counterfactual_evaluation:true;
}>&Evidence&Boundary;

export type GovernedAdmissibilityCompositionV1=Readonly<{
 version:1;perturbation_ref:string;perturbation_digest:string;domain_context_ref:string;domain_context_digest:string;
 policy_ref:string;policy_version:string;required_constraint_family_keys:readonly string[];constraint_result_refs:readonly string[];
 missing_constraint_family_keys:readonly string[];admissibility_status:GovernedInterventionAdmissibilityStatusV1;
 zero_hard_constraint_rule:"ADMISSIBLE_WHEN_APPLICABILITY_COMPLETE";
 composition_id:string;composition_digest:string;digest_algorithm:"SHA-256";deterministic:true;
 recommended:false;selected:false;executable:false;grants_authority:false;grants_execution:false;
}>;

const statuses=new Set(["CHANGEABLE","NOT_CHANGEABLE","UNRESOLVED","INSUFFICIENT_EVIDENCE"]),results=new Set(["SATISFIED","VIOLATED","UNRESOLVED","INSUFFICIENT_EVIDENCE"]),applicability=new Set(["APPLICABLE","NOT_APPLICABLE","UNRESOLVED","INSUFFICIENT_EVIDENCE"]),roles=new Set(["HARD","NON_BLOCKING"]);
const forbidden=["authority_tier","subscription_tier","recommendation_ref","approval_ref","delegation_ref","credential_ref","execution_capability_ref","capability_registry_ref","optimizer_variable","optimizer_candidate_ref","scenario_mutation","alternative_state_as_changeability","action_instance","execution_payload","causal_effect_status","material_effect_status"];
function required(v:string|undefined,c:string){const n=v?.trim();if(!n)throw new Error(c);return n;}
function ref(v:string|undefined,c:string){const n=required(v,c);if(!/^[A-Za-z0-9][A-Za-z0-9._-]*:[^\s]+$/.test(n))throw new Error(c);return n;}
function token(v:string|undefined,c:string){const n=required(v,c);if(!/^[A-Z][A-Z0-9_]{0,95}$/.test(n))throw new Error(c);return n;}
function refs(v:readonly string[],c:string,allowEmpty=false){if(!Array.isArray(v))throw new Error(c);const n=[...new Set(v.map(x=>ref(x,c)))].sort();if(!allowEmpty&&!n.length)throw new Error(c);return n;}
function tokens(v:readonly string[],c:string){if(!Array.isArray(v))throw new Error(c);const n=[...new Set(v.map(x=>token(x,c)))].sort();if(!n.length)throw new Error(c);return n;}
function time(v:string,c:string){if(!Number.isFinite(Date.parse(v)))throw new Error(c);return v;}
function reject(v:object,c:string){for(const k of forbidden)if(k in (v as Record<string,unknown>))throw new Error(c);}
function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return`{${Object.entries(v as Record<string,unknown>).filter(([,x])=>x!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(",")}}`;return JSON.stringify(v);}
async function sha(v:unknown){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(v)));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("");}
function freeze<T>(v:T):Readonly<T>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v as Record<string,unknown>).forEach(freeze);Object.freeze(v);}return v;}
const boundary={digest_algorithm:"SHA-256" as const,observational_only:true as const,recommended:false as const,selected:false as const,executable:false as const,grants_authority:false as const,grants_execution:false as const,grants_remediation:false as const,company_global_claim:false as const};
function semantic(v:Record<string,unknown>,id:string,digest:string,extras:string[]=[]){const out={...v};for(const k of [id,digest,"digest_algorithm","observational_only","recommended","selected","executable","grants_authority","grants_execution","grants_remediation","company_global_claim",...extras])delete out[k];return out;}
function verifyBoundary(v:Boundary,c:string){if(v.digest_algorithm!=="SHA-256"||v.observational_only!==true||v.recommended!==false||v.selected!==false||v.executable!==false||v.grants_authority!==false||v.grants_execution!==false||v.grants_remediation!==false||v.company_global_claim!==false)throw new Error(c);}
async function context(scope:OperationalSignalScopeBindingV1,domain:CanonicalDomainContextBindingV1,input:Readonly<{request_id:string;company_id:string;evidence_as_of:string;evaluated_at:string}>){await verifyOperationalSignalEvaluationScopeV1(scope.scope,input);await verifyCanonicalDomainContextBindingV1(domain);if(domain.domain_ref!==`domain:${scope.scope.domain}`)throw new Error("CURRENT_SEMANTICS_DOMAIN_MISMATCH");if(input.evidence_as_of!==scope.evidence_as_of||input.evaluated_at!==scope.evaluated_at||Date.parse(input.evidence_as_of)>Date.parse(input.evaluated_at))throw new Error("CURRENT_SEMANTICS_TIME_MISMATCH");}

export async function createGovernedCurrentChangeabilityResultV1(input:Readonly<{version:1;request_id:string;company_id:string;evaluation_scope:OperationalSignalScopeBindingV1;domain_context:CanonicalDomainContextBindingV1;dimension_ref:string;governed_relationship_ref:string;current_state_ref:string;governing_condition_ref:string;protected_objective_ref?:string;material_consequence_ref?:string;trajectory_ref?:string;boundary_policy_ref:string;boundary_policy_version:string;boundary_determination_ref:string;boundary_result_evidence_refs:readonly string[];changeability_status:GovernedChangeabilityStatusV1}>&Evidence):Promise<GovernedCurrentChangeabilityResultV1>{
 if(input.version!==1)throw new Error("CHANGEABILITY_VERSION_UNSUPPORTED");reject(input,"CHANGEABILITY_UNSUPPORTED_INPUT");await context(input.evaluation_scope,input.domain_context,input);if(!statuses.has(input.changeability_status))throw new Error("CHANGEABILITY_STATUS_INVALID");
 const s=input.evaluation_scope.scope,value={version:1 as const,request_id:required(input.request_id,"CHANGEABILITY_REQUEST_REQUIRED"),company_id:required(input.company_id,"CHANGEABILITY_COMPANY_REQUIRED"),scope_id:s.scope_id,scope_digest:s.scope_digest,evidence_selection_ref:ref(s.evidence_selection_ref,"CHANGEABILITY_SELECTION_REQUIRED"),domain_context_ref:input.domain_context.domain_context_id,domain_context_digest:input.domain_context.domain_context_digest,domain_ref:input.domain_context.domain_ref,domain_profile_ref:input.domain_context.domain_semantic_profile_ref,domain_profile_version:input.domain_context.domain_semantic_profile_version,dimension_ref:ref(input.dimension_ref,"CHANGEABILITY_DIMENSION_REQUIRED"),governed_relationship_ref:ref(input.governed_relationship_ref,"CHANGEABILITY_RELATIONSHIP_REQUIRED"),current_state_ref:ref(input.current_state_ref,"CHANGEABILITY_CURRENT_STATE_REQUIRED"),governing_condition_ref:ref(input.governing_condition_ref,"CHANGEABILITY_CONDITION_REQUIRED"),...(input.protected_objective_ref?{protected_objective_ref:ref(input.protected_objective_ref,"CHANGEABILITY_OBJECTIVE_INVALID")}:{}) ,...(input.material_consequence_ref?{material_consequence_ref:ref(input.material_consequence_ref,"CHANGEABILITY_CONSEQUENCE_INVALID")}:{}) ,...(input.trajectory_ref?{trajectory_ref:ref(input.trajectory_ref,"CHANGEABILITY_TRAJECTORY_INVALID")}:{}) ,boundary_policy_ref:ref(input.boundary_policy_ref,"CHANGEABILITY_BOUNDARY_POLICY_REQUIRED"),boundary_policy_version:required(input.boundary_policy_version,"CHANGEABILITY_BOUNDARY_POLICY_VERSION_REQUIRED"),boundary_determination_ref:ref(input.boundary_determination_ref,"CHANGEABILITY_BOUNDARY_DETERMINATION_REQUIRED"),boundary_result_evidence_refs:refs(input.boundary_result_evidence_refs,"CHANGEABILITY_BOUNDARY_EVIDENCE_REQUIRED"),changeability_status:input.changeability_status,epistemic_basis:"DETERMINISTIC_CURRENT_STATE" as const,evidence_refs:refs(input.evidence_refs,"CHANGEABILITY_EVIDENCE_REQUIRED"),qualification_refs:refs(input.qualification_refs,"CHANGEABILITY_QUALIFICATION_REQUIRED"),provenance_refs:refs(input.provenance_refs,"CHANGEABILITY_PROVENANCE_REQUIRED"),causal_lineage_refs:refs(input.causal_lineage_refs,"CHANGEABILITY_LINEAGE_REQUIRED"),evidence_as_of:time(input.evidence_as_of,"CHANGEABILITY_AS_OF_INVALID"),evaluated_at:time(input.evaluated_at,"CHANGEABILITY_EVALUATED_AT_INVALID")};const changeability_digest=await sha(value);return freeze({...value,changeability_id:`governed-current-changeability:sha256:${changeability_digest}`,changeability_digest,current_fact:true as const,...boundary});
}
export async function verifyGovernedCurrentChangeabilityResultV1(v:GovernedCurrentChangeabilityResultV1){verifyBoundary(v,"CHANGEABILITY_BOUNDARY_INVALID");const d=await sha(semantic(v as unknown as Record<string,unknown>,"changeability_id","changeability_digest",["current_fact"]));if(v.changeability_digest!==d||v.changeability_id!==`governed-current-changeability:sha256:${d}`||v.current_fact!==true)throw new Error("CHANGEABILITY_INTEGRITY_INVALID");}

export async function createGovernedCurrentConstraintResultV1(input:Readonly<{version:1;request_id:string;company_id:string;evaluation_scope:OperationalSignalScopeBindingV1;domain_context:CanonicalDomainContextBindingV1;perturbation:GovernedBoundedPerturbationV1;constraint_family_key:string;constraint_policy_ref:string;constraint_policy_version:string;applicability:GovernedConstraintApplicabilityV1;constraint_role?:GovernedConstraintRoleV1;result_status?:GovernedConstraintResultStatusV1;current_operand_refs:readonly string[];bound_refs:readonly string[];determination_ref:string}>&Evidence):Promise<GovernedCurrentConstraintResultV1>{
 if(input.version!==1)throw new Error("CONSTRAINT_RESULT_VERSION_UNSUPPORTED");reject(input,"CONSTRAINT_RESULT_UNSUPPORTED_INPUT");await context(input.evaluation_scope,input.domain_context,input);await verifyGovernedBoundedPerturbationV1(input.perturbation);if(input.perturbation.domain_context_ref!==input.domain_context.domain_context_id)throw new Error("CONSTRAINT_RESULT_DOMAIN_CONTEXT_MISMATCH");const family=token(input.constraint_family_key,"CONSTRAINT_RESULT_FAMILY_REQUIRED");if(!input.perturbation.constraint_family_keys.includes(family))throw new Error("CONSTRAINT_RESULT_FAMILY_NOT_BOUND");if(!applicability.has(input.applicability))throw new Error("CONSTRAINT_RESULT_APPLICABILITY_INVALID");if(input.applicability==="APPLICABLE"&&(!input.constraint_role||!roles.has(input.constraint_role)||!input.result_status||!results.has(input.result_status)))throw new Error("CONSTRAINT_RESULT_APPLICABLE_DETERMINATION_REQUIRED");if(input.applicability!=="APPLICABLE"&&(input.constraint_role||input.result_status))throw new Error("CONSTRAINT_RESULT_INAPPLICABLE_DETERMINATION_FORBIDDEN");
 const s=input.evaluation_scope.scope,value={version:1 as const,request_id:required(input.request_id,"CONSTRAINT_RESULT_REQUEST_REQUIRED"),company_id:required(input.company_id,"CONSTRAINT_RESULT_COMPANY_REQUIRED"),scope_id:s.scope_id,scope_digest:s.scope_digest,evidence_selection_ref:ref(s.evidence_selection_ref,"CONSTRAINT_RESULT_SELECTION_REQUIRED"),domain_context_ref:input.domain_context.domain_context_id,domain_context_digest:input.domain_context.domain_context_digest,domain_ref:input.domain_context.domain_ref,domain_profile_ref:input.domain_context.domain_semantic_profile_ref,domain_profile_version:input.domain_context.domain_semantic_profile_version,perturbation_ref:input.perturbation.perturbation_id,perturbation_digest:input.perturbation.perturbation_digest,constraint_family_key:family,constraint_policy_ref:ref(input.constraint_policy_ref,"CONSTRAINT_RESULT_POLICY_REQUIRED"),constraint_policy_version:required(input.constraint_policy_version,"CONSTRAINT_RESULT_POLICY_VERSION_REQUIRED"),applicability:input.applicability,...(input.constraint_role?{constraint_role:input.constraint_role}:{}),...(input.result_status?{result_status:input.result_status}:{}),current_operand_refs:refs(input.current_operand_refs,"CONSTRAINT_RESULT_OPERANDS_REQUIRED"),bound_refs:refs(input.bound_refs,"CONSTRAINT_RESULT_BOUNDS_REQUIRED"),determination_ref:ref(input.determination_ref,"CONSTRAINT_RESULT_DETERMINATION_REQUIRED"),epistemic_basis:"DETERMINISTIC_CURRENT_CONSTRAINT_EVALUATION" as const,evidence_refs:refs(input.evidence_refs,"CONSTRAINT_RESULT_EVIDENCE_REQUIRED"),qualification_refs:refs(input.qualification_refs,"CONSTRAINT_RESULT_QUALIFICATION_REQUIRED"),provenance_refs:refs(input.provenance_refs,"CONSTRAINT_RESULT_PROVENANCE_REQUIRED"),causal_lineage_refs:refs(input.causal_lineage_refs,"CONSTRAINT_RESULT_LINEAGE_REQUIRED"),evidence_as_of:time(input.evidence_as_of,"CONSTRAINT_RESULT_AS_OF_INVALID"),evaluated_at:time(input.evaluated_at,"CONSTRAINT_RESULT_EVALUATED_AT_INVALID")};const constraint_result_digest=await sha(value);return freeze({...value,constraint_result_id:`governed-current-constraint-result:sha256:${constraint_result_digest}`,constraint_result_digest,current_evidence_counterfactual_evaluation:true as const,...boundary});
}
export async function verifyGovernedCurrentConstraintResultV1(v:GovernedCurrentConstraintResultV1){verifyBoundary(v,"CONSTRAINT_RESULT_BOUNDARY_INVALID");const d=await sha(semantic(v as unknown as Record<string,unknown>,"constraint_result_id","constraint_result_digest",["current_evidence_counterfactual_evaluation"]));if(v.constraint_result_digest!==d||v.constraint_result_id!==`governed-current-constraint-result:sha256:${d}`||v.current_evidence_counterfactual_evaluation!==true)throw new Error("CONSTRAINT_RESULT_INTEGRITY_INVALID");}

export async function composeGovernedAdmissibilityV1(input:Readonly<{version:1;perturbation:GovernedBoundedPerturbationV1;policy_ref:string;policy_version:string;required_constraint_family_keys:readonly string[];constraint_results:readonly GovernedCurrentConstraintResultV1[];zero_hard_constraint_rule:"ADMISSIBLE_WHEN_APPLICABILITY_COMPLETE"}>):Promise<GovernedAdmissibilityCompositionV1>{
 if(input.version!==1)throw new Error("ADMISSIBILITY_COMPOSITION_VERSION_UNSUPPORTED");await verifyGovernedBoundedPerturbationV1(input.perturbation);if(input.zero_hard_constraint_rule!=="ADMISSIBLE_WHEN_APPLICABILITY_COMPLETE")throw new Error("ADMISSIBILITY_ZERO_HARD_RULE_REQUIRED");const requiredFamilies=tokens(input.required_constraint_family_keys,"ADMISSIBILITY_REQUIRED_SET_REQUIRED");if(requiredFamilies.some(x=>!input.perturbation.constraint_family_keys.includes(x)))throw new Error("ADMISSIBILITY_REQUIRED_SET_NOT_BOUND");const byFamily=new Map<string,GovernedCurrentConstraintResultV1>();for(const result of input.constraint_results){await verifyGovernedCurrentConstraintResultV1(result);if(result.perturbation_ref!==input.perturbation.perturbation_id||result.domain_context_ref!==input.perturbation.domain_context_ref||!requiredFamilies.includes(result.constraint_family_key)||byFamily.has(result.constraint_family_key))throw new Error("ADMISSIBILITY_CONSTRAINT_RESULT_MISMATCH");byFamily.set(result.constraint_family_key,result);}const missing=requiredFamilies.filter(x=>!byFamily.has(x));const values=[...byFamily.values()];let status:GovernedInterventionAdmissibilityStatusV1;if(values.some(x=>x.applicability==="APPLICABLE"&&x.constraint_role==="HARD"&&x.result_status==="VIOLATED"))status="NOT_ADMISSIBLE";else if(missing.length||values.some(x=>x.applicability==="INSUFFICIENT_EVIDENCE"||(x.applicability==="APPLICABLE"&&x.constraint_role==="HARD"&&x.result_status==="INSUFFICIENT_EVIDENCE")))status="INSUFFICIENT_EVIDENCE";else if(values.some(x=>x.applicability==="UNRESOLVED"||(x.applicability==="APPLICABLE"&&x.constraint_role==="HARD"&&x.result_status==="UNRESOLVED")))status="UNRESOLVED";else status="ADMISSIBLE";
 const value={version:1 as const,perturbation_ref:input.perturbation.perturbation_id,perturbation_digest:input.perturbation.perturbation_digest,domain_context_ref:input.perturbation.domain_context_ref,domain_context_digest:input.perturbation.domain_context_digest,policy_ref:ref(input.policy_ref,"ADMISSIBILITY_POLICY_REQUIRED"),policy_version:required(input.policy_version,"ADMISSIBILITY_POLICY_VERSION_REQUIRED"),required_constraint_family_keys:requiredFamilies,constraint_result_refs:refs(values.map(x=>x.constraint_result_id),"ADMISSIBILITY_RESULT_REFS_INVALID",true),missing_constraint_family_keys:missing,admissibility_status:status,zero_hard_constraint_rule:input.zero_hard_constraint_rule};const composition_digest=await sha(value);return freeze({...value,composition_id:`governed-admissibility-composition:sha256:${composition_digest}`,composition_digest,digest_algorithm:"SHA-256" as const,deterministic:true as const,recommended:false as const,selected:false as const,executable:false as const,grants_authority:false as const,grants_execution:false as const});
}
