import type { OperationalCockpitSnapshotV1 } from "./operational.cockpit.snapshot.v1";
import type { CockpitSignalEvidenceQualificationV1, CockpitSignalFamilyV1 } from "../minimum-operational-evidence";
import { cockpitDigestV1, evaluateCockpitSignalAssertabilityV1, type CockpitSignalAssertabilityV1 } from "./cockpit.signal.assertability.v1";
export type OperationalCockpitManifestationV1=Readonly<{version:1;manifestation_id:string;manifestation_digest:string;digest_algorithm:"SHA-256";snapshot_id:string;snapshot_digest:string;request_id:string;company_id:string;scope_id:string;scope_digest:string;evidence_as_of:string;manifested_at:string;question_ref?:string;assertability:Readonly<Record<CockpitSignalFamilyV1,CockpitSignalAssertabilityV1>>;manifested_family_count:0|1|2|3|4;lineage_refs:readonly string[];company_global_claim:false;grants_execution:false;observational_only:true}>;
const families=["DATA_AWARENESS","PLAN_COHERENCE","REALITY_STABILITY","DECISION_PRESSURE"] as const;
export async function buildOperationalCockpitManifestationV1(input:Readonly<{snapshot:OperationalCockpitSnapshotV1;qualifications:readonly CockpitSignalEvidenceQualificationV1[];manifested_at:string}>):Promise<OperationalCockpitManifestationV1>{
 if(!Number.isFinite(Date.parse(input.manifested_at))||Date.parse(input.manifested_at)<Date.parse(input.snapshot.evaluated_at))throw new Error("COCKPIT_MANIFESTATION_TIME_INVALID");
 const byFamily=new Map(input.qualifications.map(q=>[q.signal_family,q])); if(byFamily.size!==4||input.qualifications.length!==4)throw new Error("COCKPIT_MANIFESTATION_QUALIFICATIONS_INVALID");
 const entries=await Promise.all(families.map(async f=>[f,await evaluateCockpitSignalAssertabilityV1(input.snapshot,byFamily.get(f)!)] as const)); const assertability=Object.freeze(Object.fromEntries(entries)) as Readonly<Record<CockpitSignalFamilyV1,CockpitSignalAssertabilityV1>>;
 const manifested_family_count=entries.filter(([,a])=>a.status==="ASSERTABLE").length as 0|1|2|3|4;
 const semantic={version:1 as const,snapshot_id:input.snapshot.snapshot_id,snapshot_digest:input.snapshot.snapshot_digest,request_id:input.snapshot.request_id,company_id:input.snapshot.company_id,scope_id:input.snapshot.evaluation_scope.scope.scope_id,scope_digest:input.snapshot.evaluation_scope.scope.scope_digest,evidence_as_of:input.snapshot.evidence_as_of,manifested_at:input.manifested_at,...(input.snapshot.question_ref?{question_ref:input.snapshot.question_ref}:{}),assertability,manifested_family_count,lineage_refs:Object.freeze([input.snapshot.snapshot_id,...entries.map(([,a])=>a.assertability_id)]),company_global_claim:false as const,grants_execution:false as const,observational_only:true as const};
 const manifestation_digest=await cockpitDigestV1(semantic);return Object.freeze({...semantic,manifestation_id:`operational-cockpit-manifestation:sha256:${manifestation_digest}`,manifestation_digest,digest_algorithm:"SHA-256"});
}
