import type { BaselineAvailabilityV1 } from "../industrial/cognition/operations.baseline.commitment.feasibility.v1";
import { verifyOperationsPlannedProductionMaterialFeasibilityV1, type OperationsPlannedProductionMaterialFeasibilityV1 } from "../industrial/cognition/operations.planned.production.material.feasibility.v1";
import type { OperationalSignalScopeBindingV1 } from "./operational.signal.evaluation.scope.v1";
import { verifyOperationalSignalEvaluationScopeV1 } from "./operational.signal.evaluation.scope.v1";

export type OperationalAvailabilityReadModelV1=Readonly<{version:1;read_model_kind:"CURRENT_OPERATIONAL_AVAILABILITY";request_id:string;company_id:string;scope_id:string;scope_digest:string;evidence_selection_ref:string;source_snapshot_ref:string;evidence_as_of:string;status:"CURRENT_GOVERNED"|"PARTIALLY_UNRESOLVED";breakdown:readonly Readonly<{kind:"EFFECTIVE_INVENTORY"|"GOVERNED_FUTURE_SUPPLY"|"PLANNED_PRODUCTION";quantity:number;unit:"EA"}>[];planned_production:readonly Readonly<{production_fact_ref:string;item_ref:string;planned_quantity:number;feasible_quantity:number;available_at:string;feasibility:"FEASIBLE"|"PARTIALLY_FEASIBLE"|"ZERO_FEASIBLE"|"UNRESOLVED"}>[];evidence_refs:readonly string[];qualification_refs:readonly string[];provenance_refs:readonly string[];lineage_refs:readonly string[];read_model_id:string;read_model_digest:string;digest_algorithm:"SHA-256";observational_only:true;counterfactual:false;recommended:false;executable:false;grants_authority:false;grants_execution:false}>;
function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(v&&typeof v==="object")return`{${Object.entries(v as Record<string,unknown>).filter(([,x])=>x!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(",")}}`;return JSON.stringify(v)}
async function sha(v:unknown){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(v)));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}
function refs(v:readonly string[],code:string){const x=[...new Set(v.map(y=>y.trim()).filter(Boolean))].sort();if(!x.length)throw new Error(code);return x}
function freeze<T>(v:T):Readonly<T>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v as Record<string,unknown>).forEach(freeze);Object.freeze(v)}return v}
export async function buildOperationalAvailabilityReadModelV1(input:Readonly<{version:1;evaluation_scope:OperationalSignalScopeBindingV1;availability:readonly BaselineAvailabilityV1[];planned_production_results:readonly OperationsPlannedProductionMaterialFeasibilityV1[]}>):Promise<OperationalAvailabilityReadModelV1>{
 if(input.version!==1)throw new Error("COCKPIT_AVAILABILITY_VERSION_UNSUPPORTED");await verifyOperationalSignalEvaluationScopeV1(input.evaluation_scope.scope,input.evaluation_scope.scope);const s=input.evaluation_scope.scope;if(s.domain!=="operations")throw new Error("COCKPIT_AVAILABILITY_SCOPE_UNSUPPORTED");await Promise.all(input.planned_production_results.map(verifyOperationsPlannedProductionMaterialFeasibilityV1));
 for(const r of input.planned_production_results)if(r.request_id!==s.request_id||r.company_id!==s.company_id||r.scope_id!==s.scope_id||r.scope_digest!==s.scope_digest||r.evidence_selection_ref!==s.evidence_selection_ref||r.source_snapshot_ref!==s.source_snapshot_ref||r.evidence_as_of!==input.evaluation_scope.evidence_as_of)throw new Error("COCKPIT_AVAILABILITY_CONTEXT_MISMATCH");
 for(const a of input.availability){if(a.quantity.unit_ref!=="unit:EACH"||!Number.isFinite(a.quantity.value)||a.quantity.value<=0)throw new Error("COCKPIT_AVAILABILITY_OPERAND_INVALID");if(a.kind==="PLANNED_PRODUCTION"&&(a.material_feasibility!=="ESTABLISHED"||!input.planned_production_results.some(r=>r.result_id===a.availability_ref&&r.feasible_quantity.value===a.quantity.value)))throw new Error("COCKPIT_AVAILABILITY_PLANNED_PRODUCTION_INVALID")}
 const kinds=["EFFECTIVE_INVENTORY","GOVERNED_FUTURE_SUPPLY","PLANNED_PRODUCTION"]as const,breakdown=kinds.map(kind=>freeze({kind,quantity:input.availability.filter(a=>a.kind===kind).reduce((n,a)=>n+a.quantity.value,0),unit:"EA"as const}));const planned_production=input.planned_production_results.map(r=>freeze({production_fact_ref:r.production_fact_ref,item_ref:r.item_ref,planned_quantity:r.planned_quantity.value,feasible_quantity:r.feasible_quantity.value,available_at:r.planned_output_available_at,feasibility:r.status}));const all=[...input.availability],semantic={version:1 as const,read_model_kind:"CURRENT_OPERATIONAL_AVAILABILITY"as const,request_id:s.request_id,company_id:s.company_id,scope_id:s.scope_id,scope_digest:s.scope_digest,evidence_selection_ref:s.evidence_selection_ref,source_snapshot_ref:s.source_snapshot_ref,evidence_as_of:input.evaluation_scope.evidence_as_of,status:(planned_production.some(x=>x.feasibility==="UNRESOLVED")?"PARTIALLY_UNRESOLVED":"CURRENT_GOVERNED")as "CURRENT_GOVERNED"|"PARTIALLY_UNRESOLVED",breakdown,planned_production,evidence_refs:refs([...all.flatMap(x=>x.evidence_refs),...input.planned_production_results.flatMap(x=>x.evidence_refs)],"COCKPIT_AVAILABILITY_EVIDENCE_REQUIRED"),qualification_refs:refs([...all.flatMap(x=>x.qualification_refs),...input.planned_production_results.flatMap(x=>x.qualification_refs)],"COCKPIT_AVAILABILITY_QUALIFICATION_REQUIRED"),provenance_refs:refs([...all.flatMap(x=>x.provenance_refs),...input.planned_production_results.flatMap(x=>x.provenance_refs)],"COCKPIT_AVAILABILITY_PROVENANCE_REQUIRED"),lineage_refs:refs([...all.flatMap(x=>x.causal_lineage_refs),...input.planned_production_results.flatMap(x=>x.causal_lineage_refs)],"COCKPIT_AVAILABILITY_LINEAGE_REQUIRED")};const read_model_digest=await sha(semantic);return freeze({...semantic,read_model_id:`operational-availability-read-model:sha256:${read_model_digest}`,read_model_digest,digest_algorithm:"SHA-256"as const,observational_only:true as const,counterfactual:false as const,recommended:false as const,executable:false as const,grants_authority:false as const,grants_execution:false as const})
}
export async function verifyOperationalAvailabilityReadModelV1(value:OperationalAvailabilityReadModelV1):Promise<void>{const{read_model_id:_id,read_model_digest:_digest,digest_algorithm:_algorithm,observational_only:_observational,counterfactual:_counterfactual,recommended:_recommended,executable:_executable,grants_authority:_authority,grants_execution:_execution,...semantic}=value,digest=await sha(semantic);if(value.read_model_digest!==digest||value.read_model_id!==`operational-availability-read-model:sha256:${digest}`||value.digest_algorithm!=="SHA-256"||value.observational_only!==true||value.counterfactual!==false||value.recommended!==false||value.executable!==false||value.grants_authority!==false||value.grants_execution!==false)throw new Error("COCKPIT_AVAILABILITY_INTEGRITY_INVALID")}
